import type { ArchitectureBoundary } from "./types.js";

/** Canonical EmpireAI system boundaries — Phase 2 architecture understanding. */
export const ARCHITECTURE_BOUNDARIES: ArchitectureBoundary[] = [
  {
    id: "cockpit",
    name: "EmpireAI Cockpit",
    layer: "frontend",
    owner: "empireai-web",
    rootPath: "empireai-web/app/cockpit",
    responsibilities: [
      "Grand King operating environment UI",
      "Department navigation and executive widgets",
      "Pillow global assistant panel (SCR-800)",
    ],
    dependsOn: ["bff", "brain"],
  },
  {
    id: "bff",
    name: "Next.js BFF Proxy",
    layer: "bff",
    owner: "empireai-web/app/api",
    rootPath: "empireai-web/app/api",
    responsibilities: [
      "Proxy /api/brain/* and /api/pillow/* to Railway Brain",
      "Session cookie forwarding for authenticated requests",
    ],
    dependsOn: ["brain"],
  },
  {
    id: "brain",
    name: "EmpireAI Brain API",
    layer: "brain",
    owner: "backend/src/brain",
    rootPath: "backend/src/brain",
    responsibilities: [
      "Fastify HTTP API and tool dispatch",
      "LLM routing (OpenAI, Anthropic, Google)",
      "Session auth and permissions",
    ],
    dependsOn: ["redis", "database", "pillow-host"],
  },
  {
    id: "pillow-host",
    name: "Pillow Host (in-process)",
    layer: "pillow",
    owner: "backend/src/orchestration/pillow-host",
    rootPath: "backend/src/orchestration/pillow-host",
    responsibilities: [
      "Pillow bootstrap and repository reconstruction",
      "Session management and chat routing",
      "Context assembly and LLM completion",
    ],
    dependsOn: ["pillow-package", "brain"],
  },
  {
    id: "pillow-package",
    name: "Pillow Intelligence Package",
    layer: "pillow",
    owner: "@empireai/pillow",
    rootPath: "pillow/src",
    responsibilities: [
      "Repository bootstrap (PILLOW-002)",
      "Repository intelligence (PILLOW-003)",
      "Context builder (PILLOW-004)",
      "Executive reasoning and command interface",
    ],
    dependsOn: ["governance"],
  },
  {
    id: "redis",
    name: "Redis / Upstash Queue",
    layer: "redis",
    owner: "infrastructure",
    rootPath: "backend/src/brain/queue",
    responsibilities: ["BullMQ job queue", "Worker task dispatch"],
    dependsOn: [],
  },
  {
    id: "worker",
    name: "Brain Worker",
    layer: "worker",
    owner: "backend/src/worker.ts",
    rootPath: "backend/src",
    responsibilities: ["Background BullMQ jobs", "Scheduled tasks"],
    dependsOn: ["redis", "database", "brain"],
  },
  {
    id: "database",
    name: "SQLite Brain Database",
    layer: "database",
    owner: "backend/src/brain/database.ts",
    rootPath: "backend/src/brain",
    responsibilities: [
      "Users, sessions, audit logs",
      "Pillow approval state and executive learning",
    ],
    dependsOn: [],
  },
  {
    id: "railway",
    name: "Railway Production Backend",
    layer: "deployment",
    owner: "deployment/railway.md",
    rootPath: "railway.toml",
    responsibilities: [
      "Brain API + Pillow in-process container",
      "Governance bundle at backend/.pillow-governance-bundle",
    ],
    dependsOn: ["github"],
  },
  {
    id: "vercel",
    name: "Vercel Cockpit Frontend",
    layer: "deployment",
    owner: "empireai-web/vercel.json",
    rootPath: "empireai-web",
    responsibilities: ["empire-ai.co Cockpit hosting", "BFF proxy to Railway"],
    dependsOn: ["railway", "github"],
  },
  {
    id: "github",
    name: "GitHub Source Repository",
    layer: "governance",
    owner: "empireaios/EmpireAI",
    rootPath: ".",
    responsibilities: ["Canonical source", "CI/CD trigger for Railway and Vercel"],
    dependsOn: [],
  },
  {
    id: "automation",
    name: "Business Automation Layer",
    layer: "automation",
    owner: "backend/src/orchestration/business-automation",
    rootPath: "backend/src/orchestration/business-automation",
    responsibilities: ["Workflow orchestration", "Automation triggers and brokers"],
    dependsOn: ["brain", "registry"],
  },
  {
    id: "registry",
    name: "Empire Registry Loader",
    layer: "business_engine",
    owner: "backend/src/registry",
    rootPath: "backend/src/registry",
    responsibilities: [
      "Doctrine, commerce, certification registry rows",
      "Plugin manifest discovery",
    ],
    dependsOn: ["governance"],
  },
  {
    id: "grand-king",
    name: "Grand King Account",
    layer: "governance",
    owner: "backend/src/grand-king",
    rootPath: "backend/src/grand-king",
    responsibilities: [
      "Founder platform identity (founder@empireai.com)",
      "Grand King seed and executive permissions",
    ],
    dependsOn: ["brain", "auth"],
  },
];
