/** T3-04 — Assembles theme definition code from tokens. */

import type { ThemeRequirement } from "./theme-requirement-interpreter.js";
import type { ThemeScope, ThemeToken } from "./types.js";
import { appendThemeLog } from "./theme-logging.js";

export class ThemeCodeAssembler {
  assemble(input: {
    themeName: string;
    scope: ThemeScope;
    requirement: ThemeRequirement;
    allTokens: ThemeToken[];
    designConstraints: string[];
    executiveConstraints: string[];
  }): string {
    appendThemeLog({
      event: "theme_code_generation",
      level: "info",
      details: `Assembling theme: ${input.themeName}`,
    });

    const cssVars = input.allTokens
      .map((t) => `  ${t.tokenId}: ${t.tokenValue};`)
      .join("\n");

    const constraintComments = [
      ...input.designConstraints.map((c) => ` * Design: ${c}`),
      ...input.executiveConstraints.map((c) => ` * Executive: ${c}`),
    ].join("\n");

    return `/**
 * EmpireAI Theme — ${input.themeName}
 * Scope: ${input.scope}
${constraintComments}
 * Generated by Pillow Theme Builder (T3-04)
 */
:root[data-theme="${input.themeName}"] {
${cssVars}
}

/* Dynamic visual styling for ${input.scope} */
.theme-${input.scope} {
  color: var(--${this.toKebab(input.themeName)}-foreground, hsl(var(--foreground)));
  background: var(--${this.toKebab(input.themeName)}-background, hsl(var(--background)));
}
`;
  }

  resolveTargetFiles(themeName: string, allowedDirs: string[]): string[] {
    const fileName = `${themeName}.css`;
    const dir = allowedDirs[0] ?? "empireai-web/styles/themes";
    const path = `${dir}/${fileName}`;
    if (allowedDirs.some((d) => path.startsWith(d))) return [path];
    return [`empireai-web/styles/themes/${fileName}`];
  }

  private toKebab(name: string): string {
    return name.replace(/([a-z])([A-Z])/g, "$1-$2").toLowerCase();
  }
}
