import type { AccountProviderDefinition, AccountProviderId } from "../models/account-provider.js";

/** Provider profiles — EA never stores passwords; OAuth/API only. */
export const ACCOUNT_PROVIDER_DEFINITIONS: Record<AccountProviderId, AccountProviderDefinition> = {
  "amazon-seller": {
    providerId: "amazon-seller",
    displayName: "Amazon Seller",
    category: "marketplace",
    marketplaceId: "amazon",
    connectorId: "amazon",
    philosophy: "Connect Once. EA Operates Forever.",
    requiredPermissions: ["sellingpartnerapi::catalog", "sellingpartnerapi::orders"],
    oauthSupported: true,
    apiSupported: true,
    requiredHumanSteps: ["Create Seller Central account", "Complete identity verification", "Authorize SP-API OAuth"],
    setupSteps: ["Register at sellercentral.amazon.com", "Complete tax interview", "Register SP-API developer app"],
    humanOnlyActions: ["identity_verification", "tax_verification", "marketplace_approval"],
    neverStoresPasswords: true,
  },
  "walmart-marketplace": {
    providerId: "walmart-marketplace",
    displayName: "Walmart Marketplace",
    category: "marketplace",
    marketplaceId: "walmart",
    philosophy: "Connect Once. EA Operates Forever.",
    requiredPermissions: ["marketplace.items", "marketplace.orders"],
    oauthSupported: true,
    apiSupported: true,
    requiredHumanSteps: ["Apply for Walmart seller account", "Complete business verification", "Authorize API OAuth"],
    setupSteps: ["Submit Walmart Marketplace application", "Await approval", "Configure API credentials"],
    humanOnlyActions: ["identity_verification", "marketplace_approval", "document_upload"],
    neverStoresPasswords: true,
  },
  shopify: {
    providerId: "shopify",
    displayName: "Shopify",
    category: "marketplace",
    marketplaceId: "shopify",
    connectorId: "shopify",
    philosophy: "Connect Once. EA Operates Forever.",
    requiredPermissions: ["read_products", "write_products", "read_orders", "write_orders"],
    oauthSupported: true,
    apiSupported: true,
    requiredHumanSteps: ["Create Shopify store", "Install EmpireAI app or custom OAuth app"],
    setupSteps: ["Create store at shopify.com", "Configure payments", "Authorize Admin API"],
    humanOnlyActions: ["account_creation", "banking_verification", "oauth_authorization"],
    neverStoresPasswords: true,
  },
  "tiktok-shop": {
    providerId: "tiktok-shop",
    displayName: "TikTok Shop",
    category: "marketplace",
    marketplaceId: "tiktok-shop",
    philosophy: "Connect Once. EA Operates Forever.",
    requiredPermissions: ["product.manage", "order.manage"],
    oauthSupported: true,
    apiSupported: true,
    requiredHumanSteps: ["Register TikTok Shop seller", "Complete business verification", "Authorize Shop API"],
    setupSteps: ["Create Seller Center account", "Verify business entity", "Connect catalog"],
    humanOnlyActions: ["identity_verification", "marketplace_approval", "document_upload"],
    neverStoresPasswords: true,
  },
  ebay: {
    providerId: "ebay",
    displayName: "eBay",
    category: "marketplace",
    marketplaceId: "ebay",
    connectorId: "ebay",
    philosophy: "Connect Once. EA Operates Forever.",
    requiredPermissions: ["sell.inventory", "sell.fulfillment"],
    oauthSupported: true,
    apiSupported: true,
    requiredHumanSteps: ["Create eBay seller account", "Register developer app", "Authorize OAuth consent"],
    setupSteps: ["Create seller account", "Join eBay Developer Program", "Configure OAuth redirect"],
    humanOnlyActions: ["identity_verification", "banking_verification", "oauth_authorization"],
    neverStoresPasswords: true,
  },
  "google-merchant-center": {
    providerId: "google-merchant-center",
    displayName: "Google Merchant Center",
    category: "marketplace",
    marketplaceId: "google-merchant",
    philosophy: "Connect Once. EA Operates Forever.",
    requiredPermissions: ["content.readonly", "content"],
    oauthSupported: true,
    apiSupported: true,
    requiredHumanSteps: ["Create Merchant Center account", "Verify domain", "Authorize Content API"],
    setupSteps: ["Register Merchant Center", "Claim store domain", "Link Google Ads if needed"],
    humanOnlyActions: ["document_upload", "identity_verification", "oauth_authorization"],
    neverStoresPasswords: true,
  },
  "meta-business": {
    providerId: "meta-business",
    displayName: "Meta Business",
    category: "advertising",
    marketplaceId: "facebook-shop",
    connectorId: "meta-ads",
    philosophy: "Connect Once. EA Operates Forever.",
    requiredPermissions: ["ads_management", "catalog_management", "business_management"],
    oauthSupported: true,
    apiSupported: true,
    requiredHumanSteps: ["Create Business Manager", "Set up Commerce Manager", "Authorize Meta OAuth"],
    setupSteps: ["Create Business Manager account", "Configure ad account", "Connect catalog"],
    humanOnlyActions: ["identity_verification", "marketplace_approval", "oauth_authorization"],
    neverStoresPasswords: true,
  },
  "instagram-shop": {
    providerId: "instagram-shop",
    displayName: "Instagram Shop",
    category: "marketplace",
    marketplaceId: "instagram-shop",
    connectorId: "meta-ads",
    philosophy: "Connect Once. EA Operates Forever.",
    requiredPermissions: ["instagram_shopping", "catalog_management"],
    oauthSupported: true,
    apiSupported: true,
    requiredHumanSteps: ["Convert to Business account", "Link Commerce Manager catalog", "Authorize Meta OAuth"],
    setupSteps: ["Switch Instagram to Business", "Connect Facebook catalog", "Enable shopping"],
    humanOnlyActions: ["account_creation", "marketplace_approval", "oauth_authorization"],
    neverStoresPasswords: true,
  },
  stripe: {
    providerId: "stripe",
    displayName: "Stripe",
    category: "payments",
    connectorId: "stripe",
    philosophy: "Connect Once. EA Operates Forever.",
    requiredPermissions: ["checkout.sessions", "payment_intents", "webhooks"],
    oauthSupported: true,
    apiSupported: true,
    requiredHumanSteps: ["Create Stripe account", "Complete business verification", "Connect API keys via OAuth/vault"],
    setupSteps: ["Register at stripe.com", "Enable live payments", "Configure webhook endpoint"],
    humanOnlyActions: ["identity_verification", "banking_verification", "tax_verification"],
    neverStoresPasswords: true,
  },
  "cj-dropshipping": {
    providerId: "cj-dropshipping",
    displayName: "CJ Dropshipping",
    category: "supplier",
    connectorId: "cj-dropshipping",
    philosophy: "Connect Once. EA Operates Forever.",
    requiredPermissions: ["catalog.read", "order.create", "tracking.read"],
    oauthSupported: false,
    apiSupported: true,
    requiredHumanSteps: ["Create CJ account", "Generate API key in CJ dashboard", "Store credentials in vault ref"],
    setupSteps: ["Register CJ account", "Complete sandbox testing", "Enable live API key"],
    humanOnlyActions: ["account_creation", "identity_verification"],
    neverStoresPasswords: true,
  },
};

export function getAccountProviderDefinition(providerId: AccountProviderId): AccountProviderDefinition {
  return ACCOUNT_PROVIDER_DEFINITIONS[providerId];
}
