import { DATABASE_WORKER_ID, DATABASE_WORKER_IDENTITY, DATABASE_WORKER_REPORT_VERSION, DBW_CAPABILITIES, DBW_METADATA_VERSION, INTEGRATION_TARGETS } from "./paths.js";
import { DatabaseBuilder } from "./database-builder.js";
import { DatabaseStore } from "./database-store.js";
import { DatabaseValidator, HealthMonitor, RecoveryManager } from "./database-validator.js";
import { IntegrationCoordinator, type DatabaseWorkerDependencies } from "./integrations.js";
import { appendDbwLog } from "./dbw-logging.js";
import type { DatabaseBuildReport, DatabaseWorkerCatalog, DatabaseWorkerEngineRecord, DatabaseWorkerInput, DatabaseWorkerRunReport, IntegrationHandshake } from "./types.js";
import type { DatabaseWorkerConfiguration } from "./configuration.js";
export class DatabaseManager {
  private readonly store = new DatabaseStore(); private readonly builder = new DatabaseBuilder(); private readonly validator = new DatabaseValidator(); private readonly health = new HealthMonitor(); private readonly recovery = new RecoveryManager(); private readonly integrations = new IntegrationCoordinator(); private engineRecord: DatabaseWorkerEngineRecord | null = null; private seeded = false; private handshakes: IntegrationHandshake[] = [];
  bindIntegrations(deps: DatabaseWorkerDependencies = {}) { this.integrations.bind(deps); }
  ensureSeeded(config: DatabaseWorkerConfiguration) { if (!this.seeded) { this.store.seed(config.seedDatabaseBuildReports); this.seeded = true; this.record("connected", config, "pass"); } }
  connect(_: Record<string, unknown>, config: DatabaseWorkerConfiguration) { const started = Date.now(); this.ensureSeeded(config); this.handshakes = this.integrations.connect(config.workerId); this.record("connected", config, "pass"); return this.report("connect", [], null, this.validator.finalize("pass", [], [], started), started); }
  receiveApprovedRequirementsReports(input: DatabaseWorkerInput, config: DatabaseWorkerConfiguration) { return this.stage("receive_approved_requirements_reports", input, config, (report) => report, true, true); }
  receiveApprovedArchitectureReports(input: DatabaseWorkerInput, config: DatabaseWorkerConfiguration) { return this.stage("receive_approved_architecture_reports", input, config, (report, architecture) => this.builder.attachArchitecture(report, architecture?.architectureId ?? input.architectureReportId ?? report.architectureReportId, architecture?.databaseType ?? (architecture?.moduleArchitecture?.length ? "relational" : "hybrid")), true); }
  designRelationalAndNonRelationalSchemas(input: DatabaseWorkerInput, config: DatabaseWorkerConfiguration) { return this.stage("design_relational_and_non_relational_schemas", input, config, (report, architecture) => this.builder.addSchemas(report, architecture?.moduleArchitecture ?? [])); }
  createTablesRelationshipsAndConstraints(input: DatabaseWorkerInput, config: DatabaseWorkerConfiguration) { return this.stage("create_tables_relationships_and_constraints", input, config, (report) => this.builder.addTables(report)); }
  createIndexesForPerformance(input: DatabaseWorkerInput, config: DatabaseWorkerConfiguration) { return this.stage("create_indexes_for_performance", input, config, (report) => this.builder.addIndexes(report)); }
  generateDatabaseMigrations(input: DatabaseWorkerInput, config: DatabaseWorkerConfiguration) { return this.stage("generate_database_migrations", input, config, (report) => this.builder.addMigrations(report)); }
  validateReferentialIntegrity(input: DatabaseWorkerInput, config: DatabaseWorkerConfiguration) { return this.stage("validate_referential_integrity", input, config, (report) => this.builder.validateIntegrity(report)); }
  supportBackupAndRecoveryPlanning(input: DatabaseWorkerInput, config: DatabaseWorkerConfiguration) { return this.stage("support_backup_and_recovery_planning", input, config, (report) => this.builder.addBackup(report)); }
  produceOptimizedProductionReadyDatabaseStructures(input: DatabaseWorkerInput, config: DatabaseWorkerConfiguration) { return this.stage("produce_optimized_production_ready_database_structures", input, config, (report) => this.builder.optimize(report)); }
  produceDatabaseBuildReport(input: DatabaseWorkerInput, config: DatabaseWorkerConfiguration) { return this.stage("produce_database_build_report", input, config, (report) => this.builder.complete(report), false); }
  submitReport(input: DatabaseWorkerInput, config: DatabaseWorkerConfiguration) { const started = Date.now(); const produced = this.produceDatabaseBuildReport(input, config); const latest = produced.latestDatabaseBuildReport; if (!latest || produced.validation.decision === "fail") return produced; const submission = this.integrations.submitReport(latest); const saved = submission.submitted ? this.store.markSubmitted(latest.buildId, submission.executiveReportId!)! : latest; return this.finish("submit_report", [saved], saved, this.validator.validateDatabaseBuildReports([saved], input, started), started, config); }
  list(config: DatabaseWorkerConfiguration) { this.ensureSeeded(config); const reports = this.store.list(); return this.finish("list", reports, reports.at(-1) ?? null, this.validator.validateDatabaseBuildReports(reports.length ? reports : null, { validated: true }, Date.now(), true), Date.now(), config); }
  validate(input: DatabaseWorkerInput, config: DatabaseWorkerConfiguration) { const reports = this.store.list(); return this.finish("validate", reports, reports.at(-1) ?? null, this.validator.validateDatabaseBuildReports(reports.length ? reports : null, input, Date.now()), Date.now(), config); }
  diagnostics(config: DatabaseWorkerConfiguration) { return this.list(config); }
  getDatabaseBuildReports() { return this.store.list(); } getLatestDatabaseBuildReportId() { return this.store.getLatestDatabaseBuildReportId(); } getAuditTrail() { return this.store.getAuditTrail(); } getIntegrations() { return this.handshakes.map((item) => ({ ...item })); } getEngineRecord() { return this.engineRecord ? structuredClone(this.engineRecord) : null; }
  getCatalog(): DatabaseWorkerCatalog { return { reportVersion: DATABASE_WORKER_REPORT_VERSION, workerId: this.engineRecord?.workerId ?? DATABASE_WORKER_IDENTITY.workerId, databaseBuildReports: this.store.list(), integrations: this.getIntegrations(), metadataVersion: DBW_METADATA_VERSION, executiveAuthority: "pillow", neverBuildFrontend: true, neverBuildBackendBusinessLogic: true, neverOverrideApprovedArchitecture: true, neverOverridePillow: true, neverOverrideGrandKing: true, neverImplementQ607OrLater: true }; }
  private stage(action: string, input: DatabaseWorkerInput, config: DatabaseWorkerConfiguration, mutate: (report: DatabaseBuildReport, architecture?: ReturnType<IntegrationCoordinator["enrich"]>["architecture"]) => DatabaseBuildReport, incomplete = true, newShell = false) { const started = Date.now(); this.ensureSeeded(config); const enriched = this.integrations.enrich(input); const violations = this.validator.validateDatabaseBuildReports(null, enriched.input, started); if (violations.decision === "fail") return this.finish(action, [], null, violations, started, config); let report = !newShell ? this.store.list().at(-1) : null; if (!report) report = this.builder.createShell(enriched.input, config); report = mutate(report, enriched.architecture); this.store.save(report, action); return this.finish(action, [report], report, this.validator.validateDatabaseBuildReports([report], enriched.input, started, incomplete), started, config); }
  private finish(action: string, reports: DatabaseBuildReport[], latest: DatabaseBuildReport | null, validation: DatabaseWorkerRunReport["validation"], started: number, config: DatabaseWorkerConfiguration) { if (validation.decision === "fail") this.recovery.recordFailure(); else this.recovery.reset(); this.record(validation.decision === "fail" ? "failed" : "active", config, validation.decision, latest); appendDbwLog({ event: action, details: `build=${latest?.buildId ?? "none"}` }); return this.report(action, reports, latest, validation, started); }
  private record(state: string, config: DatabaseWorkerConfiguration, validation: "pass" | "partial" | "fail", latest: DatabaseBuildReport | null = null) { const report = latest ?? this.store.list().at(-1) ?? null; this.engineRecord = { engineRecordId: this.engineRecord?.engineRecordId ?? `dbw-eng-${Date.now()}`, timestamp: new Date().toISOString(), engineId: DATABASE_WORKER_ID, engineVersion: "PILLOW-DBW-001", currentOperationalState: state, healthStatus: this.health.status(validation, config.enabled), validationStatus: validation === "pass" ? "passed" : validation === "fail" ? "failed" : "partial", supportedCapabilities: [...DBW_CAPABILITIES], totalDatabaseBuildReports: this.store.count(), lastDatabaseBuildReportId: report?.buildId ?? null, lastConfidenceScore: report?.confidenceScore ?? null, workerId: config.workerId, integrationTargets: [...INTEGRATION_TARGETS], metadataVersion: DBW_METADATA_VERSION }; }
  private report(action: string, reports: DatabaseBuildReport[], latest: DatabaseBuildReport | null, validation: DatabaseWorkerRunReport["validation"], started: number): DatabaseWorkerRunReport { return { databaseRunReportId: `dbw-run-${Date.now()}`, runTimestamp: new Date().toISOString(), action, engineRecord: this.engineRecord!, catalog: this.getCatalog(), databaseBuildReports: reports, latestDatabaseBuildReport: latest, integrations: this.getIntegrations(), validation, durationMs: Date.now() - started, metadataVersion: DBW_METADATA_VERSION }; }
}
