import type { EmpireBootstrapContext } from "../bootstrap/types.js";
import { RepositoryReader } from "../bootstrap/repository-reader.js";
import { buildDatabaseWorkerConfiguration, type DatabaseWorkerConfiguration } from "./configuration.js";
import { DatabaseWorkerController } from "./database-worker-controller.js";
import { DatabaseManager } from "./database-manager.js";
import type { DatabaseWorkerDependencies } from "./integrations.js";
import { resetDbwLogsForTesting } from "./dbw-logging.js";
import { resetDatabaseSequenceForTesting } from "./database-builder.js";
import { DATABASE_WORKER_SYSTEM_PATH } from "./paths.js";
import type { DatabaseWorkerCockpitSnapshot, DatabaseWorkerInput, DatabaseWorkerState } from "./types.js";
export interface DatabaseWorkerOptions { configuration?: Partial<DatabaseWorkerConfiguration>; dependencies?: DatabaseWorkerDependencies; }
export class DatabaseWorker {
  private initializedAt: string | null = null;
  private readonly controller: DatabaseWorkerController;
  constructor(private readonly bootstrap: EmpireBootstrapContext, options: DatabaseWorkerOptions = {}) { const manager = new DatabaseManager(); if (options.dependencies) manager.bindIntegrations(options.dependencies); this.controller = new DatabaseWorkerController(manager, buildDatabaseWorkerConfiguration(bootstrap.repositoryRoot, options.configuration)); }
  async initialize() { const document = await new RepositoryReader(this.bootstrap.repositoryRoot).readText(DATABASE_WORKER_SYSTEM_PATH); if (!document?.includes("Database Worker")) throw new Error(`${DATABASE_WORKER_SYSTEM_PATH} missing — Q6-06 system doc required.`); this.controller.initialize(); this.initializedAt = new Date().toISOString(); return this.getState(); }
  bindIntegrations(deps: DatabaseWorkerDependencies = {}) { this.controller.bindIntegrations(deps); }
  getState(): DatabaseWorkerState { if (!this.initializedAt) throw new Error("Database Worker not initialized. Call initialize() first."); const configuration = this.controller.getConfiguration(); const engineRecord = this.controller.getManager().getEngineRecord(); const latestReport = this.controller.getLatestReport(); return { engineVersion: "PILLOW-DBW-001", missionId: "Q6-06", status: this.controller.getStatus(), initializedAt: this.initializedAt, configuration, latestReport, engineRecord, health: { status: engineRecord?.healthStatus ?? "standby", healthScore: engineRecord?.healthStatus === "healthy" ? 100 : engineRecord ? 70 : 50, engineEnabled: configuration.enabled, lastOperationAt: latestReport?.runTimestamp ?? null, lastValidationDecision: latestReport?.validation.decision ?? null, totalDatabaseBuildReports: engineRecord?.totalDatabaseBuildReports ?? 0, lastDatabaseBuildReportId: engineRecord?.lastDatabaseBuildReportId ?? null, lastConfidenceScore: engineRecord?.lastConfidenceScore ?? null, notes: ["Database Worker creates structural database signals from approved requirements and architecture; it does not build frontend, backend business logic, application business logic, override authority, or implement Q6-07 or later."] } }; }
  connect(input: Record<string, unknown> = {}) { return this.controller.connect(input); }
  receiveApprovedRequirementsReports(input: DatabaseWorkerInput = {}) { return this.controller.receiveApprovedRequirementsReports(input); } receiveApprovedRequirementsReport(input: DatabaseWorkerInput = {}) { return this.controller.receiveApprovedRequirementsReport(input); }
  receiveApprovedArchitectureReports(input: DatabaseWorkerInput = {}) { return this.controller.receiveApprovedArchitectureReports(input); } receiveApprovedArchitectureReport(input: DatabaseWorkerInput = {}) { return this.controller.receiveApprovedArchitectureReport(input); }
  designRelationalAndNonRelationalSchemas(input: DatabaseWorkerInput = {}) { return this.controller.designRelationalAndNonRelationalSchemas(input); } createTablesRelationshipsAndConstraints(input: DatabaseWorkerInput = {}) { return this.controller.createTablesRelationshipsAndConstraints(input); } createIndexesForPerformance(input: DatabaseWorkerInput = {}) { return this.controller.createIndexesForPerformance(input); } generateDatabaseMigrations(input: DatabaseWorkerInput = {}) { return this.controller.generateDatabaseMigrations(input); } validateReferentialIntegrity(input: DatabaseWorkerInput = {}) { return this.controller.validateReferentialIntegrity(input); } supportBackupAndRecoveryPlanning(input: DatabaseWorkerInput = {}) { return this.controller.supportBackupAndRecoveryPlanning(input); } produceOptimizedProductionReadyDatabaseStructures(input: DatabaseWorkerInput = {}) { return this.controller.produceOptimizedProductionReadyDatabaseStructures(input); } produceDatabaseBuildReport(input: DatabaseWorkerInput = {}) { return this.controller.produceDatabaseBuildReport(input); }
  submitReport(input: DatabaseWorkerInput = {}) { return this.controller.submitReport(input); } list() { return this.controller.list(); } validate(input: DatabaseWorkerInput = {}) { return this.controller.validate(input); } diagnostics() { return this.controller.diagnostics(); }
  getDatabaseBuildReports() { return this.controller.getManager().getDatabaseBuildReports(); } getCatalog() { return this.controller.getManager().getCatalog(); } getEngineRecord() { return this.controller.getManager().getEngineRecord(); } getLatestDatabaseBuildReportId() { return this.controller.getManager().getLatestDatabaseBuildReportId(); } getAuditTrail() { return this.controller.getManager().getAuditTrail(); } getIntegrations() { return this.controller.getManager().getIntegrations(); }
  validateForSupervisorSync() { const state = this.getState(); const score = state.latestReport?.validation.decision === "fail" ? 40 : state.latestReport?.validation.decision === "partial" ? 70 : 100; return { valid: state.health.status !== "failed", health: score >= 75 ? "healthy" as const : score >= 50 ? "degraded" as const : "blocked" as const, readinessScore: score, notes: state.health.notes }; }
  getCockpitSnapshot(): DatabaseWorkerCockpitSnapshot { const state = this.getState(); return { missionId: "Q6-06", status: state.status, healthStatus: state.health.status, totalDatabaseBuildReports: state.health.totalDatabaseBuildReports, latestDatabaseBuildReportId: this.getLatestDatabaseBuildReportId(), lastConfidenceScore: state.health.lastConfidenceScore, workerId: state.configuration.workerId, neverBuildFrontend: true, neverBuildBackendBusinessLogic: true, neverOverrideApprovedArchitecture: true, neverImplementQ607OrLater: true }; }
}
export const createDatabaseWorker = (bootstrap: EmpireBootstrapContext, options?: DatabaseWorkerOptions) => new DatabaseWorker(bootstrap, options);
export function resetDatabaseWorkerForTesting() { resetDbwLogsForTesting(); resetDatabaseSequenceForTesting(); }
