import { DATABASE_WORKER_IDENTITY, INTEGRATION_TARGETS } from "./paths.js";
import { appendDbwLog } from "./dbw-logging.js";
import type { DatabaseBuildReport, DatabaseWorkerInput, DbwIntegrationTarget, IntegrationHandshake } from "./types.js";
export type RequirementsWorker = { getRequirementsReports?: () => Array<{ requirementsId?: string; platformId?: string; platformName?: string; businessId?: string; factoryMissionId?: string; businessObjective?: string }>; getLatestRequirementsReportId?: () => string | null };
export type ArchitectureWorkerSurface = { getArchitectureReports?: () => Array<{ architectureId?: string; platformId?: string; platformName?: string; businessId?: string; factoryMissionId?: string; businessObjective?: string; requirementsReportId?: string; moduleArchitecture?: Array<{ id?: string; name?: string }>; databaseType?: string }>; getLatestArchitectureReportId?: () => string | null };
export type DatabaseWorkerDependencies = {
  workerRegistry?: { registerWorker: (input: Record<string, unknown>) => unknown } | null; workerLifecycle?: { createWorker: (input: Record<string, unknown>) => unknown; activateWorker: (input: Record<string, unknown>) => unknown } | null; workerAssignmentEngine?: { discoverEligibleWorkers: (input: Record<string, unknown>) => unknown } | null;
  enterprisePlatformFactoryCore?: { getMissions?: () => Array<{ factoryMissionId?: string; platformId?: string; platformName?: string; businessId?: string; businessObjective?: string }>; getLatestMissionId?: () => string | null } | null;
  requirementsWorker?: RequirementsWorker | null; architectureWorker?: ArchitectureWorkerSurface | null;
  backendWorker?: { getBackendBuildReports?: () => Array<{ buildId?: string; platformId?: string; architectureReportId?: string; requirementsReportId?: string; servicesImplemented?: Array<{ id?: string; name?: string }> }>; getLatestBackendBuildReportId?: () => string | null } | null;
  executiveReportingRuntime?: { submitWorkerReport: (input: Record<string, unknown>) => { records?: Array<{ reportId?: string }> } } | null; workerPerformanceReview?: { registerPerformanceWorker: (input: Record<string, unknown>) => unknown } | null; workerRecoverySystem?: { registerRecoverableWorker: (input: Record<string, unknown>) => unknown } | null;
};
export class IntegrationCoordinator {
  private deps: DatabaseWorkerDependencies = {}; private handshakes: IntegrationHandshake[] = [];
  bind(deps: DatabaseWorkerDependencies = {}) { this.deps = { ...deps }; }
  connect(workerId: string) { const timestamp = new Date().toISOString(); this.handshakes = INTEGRATION_TARGETS.map((target) => { const status = this.bound(target) ? "bound" : "ready"; appendDbwLog({ event: "integration_handshake", details: `${target}:${status}` }); return { target, status, details: `Database Worker ${workerId} ↔ ${target} (${status})`, timestamp }; }); this.provision(workerId); return this.getHandshakes(); }
  getHandshakes() { return this.handshakes.map((item) => ({ ...item })); }
  enrich(input: DatabaseWorkerInput) {
    const requirements = this.deps.requirementsWorker?.getRequirementsReports?.() ?? []; const req = requirements.find((item) => item.requirementsId === input.requirementsReportId) ?? requirements.at(-1);
    const architectures = this.deps.architectureWorker?.getArchitectureReports?.() ?? []; const architecture = architectures.find((item) => item.architectureId === input.architectureReportId || item.platformId === input.platformId || item.businessId === input.businessId) ?? architectures.at(-1);
    const missions = this.deps.enterprisePlatformFactoryCore?.getMissions?.() ?? []; const mission = missions.find((item) => item.factoryMissionId === input.factoryMissionId || item.platformId === input.platformId || item.businessId === input.businessId) ?? missions.at(-1);
    const backend = this.deps.backendWorker?.getBackendBuildReports?.().at(-1);
    return { input: { ...input, requirementsReportId: input.requirementsReportId ?? req?.requirementsId ?? backend?.requirementsReportId ?? this.deps.requirementsWorker?.getLatestRequirementsReportId?.() ?? null, architectureReportId: input.architectureReportId ?? architecture?.architectureId ?? backend?.architectureReportId ?? this.deps.architectureWorker?.getLatestArchitectureReportId?.() ?? null, platformId: input.platformId ?? architecture?.platformId ?? req?.platformId ?? backend?.platformId ?? mission?.platformId ?? null, platformName: input.platformName ?? architecture?.platformName ?? req?.platformName ?? mission?.platformName ?? null, businessId: input.businessId ?? architecture?.businessId ?? req?.businessId ?? mission?.businessId ?? null, factoryMissionId: input.factoryMissionId ?? architecture?.factoryMissionId ?? req?.factoryMissionId ?? mission?.factoryMissionId ?? this.deps.enterprisePlatformFactoryCore?.getLatestMissionId?.() ?? null, businessObjective: input.businessObjective ?? architecture?.businessObjective ?? req?.businessObjective ?? mission?.businessObjective ?? null }, architecture };
  }
  submitReport(report: DatabaseBuildReport) {
    const runtime = this.deps.executiveReportingRuntime; if (!runtime?.submitWorkerReport) return { submitted: false, executiveReportId: null, details: "executive_reporting_runtime_unavailable" };
    const result = runtime.submitWorkerReport({ reportingEntity: report.workerId, entityType: "worker", businessId: report.businessId, missionId: "Q6-06", currentStatus: "database_build_report_prepared", progress: Math.round(report.confidenceScore), blockers: report.selfReviewPassed ? [] : [`self_review_blocker:${report.buildId}`], evidence: [`requirements:${report.requirementsReportId}`, `architecture:${report.architectureReportId}`, `tables:${report.tablesCreated.length}`, `indexes:${report.indexes.length}`], nextAction: "awaiting_pillow_review_of_database_build_no_frontend_or_backend_business_logic", completionStatus: "completed", reportType: "worker", validated: true });
    const executiveReportId = result.records?.find((record) => record.reportId)?.reportId ?? `ert-dbw-${Date.now()}`; appendDbwLog({ event: "submit_report", details: `build=${report.buildId} executive=${executiveReportId}` }); return { submitted: true, executiveReportId, details: "submitted_to_executive_reporting_runtime" };
  }
  private provision(workerId: string) { const identity = { ...DATABASE_WORKER_IDENTITY, workerId, reportingLine: [...DATABASE_WORKER_IDENTITY.reportingLine], certificationStatus: "certified", operationalStatus: "active", validated: true }; try { this.deps.workerRegistry?.registerWorker?.(identity); this.deps.workerLifecycle?.createWorker?.(identity); this.deps.workerLifecycle?.activateWorker?.({ workerId, validated: true }); this.deps.workerAssignmentEngine?.discoverEligibleWorkers?.({ missionId: "Q6-06", validated: true }); this.deps.workerPerformanceReview?.registerPerformanceWorker?.({ workerId, validated: true }); this.deps.workerRecoverySystem?.registerRecoverableWorker?.({ workerId, validated: true }); } catch { /* optional integration failures do not block local operation */ } }
  private bound(target: DbwIntegrationTarget) { const d = this.deps; switch (target) { case "worker_registry": return Boolean(d.workerRegistry?.registerWorker); case "worker_lifecycle": return Boolean(d.workerLifecycle?.createWorker); case "worker_assignment_engine": return Boolean(d.workerAssignmentEngine?.discoverEligibleWorkers); case "enterprise_platform_factory_core": return Boolean(d.enterprisePlatformFactoryCore?.getMissions); case "requirements_worker": return Boolean(d.requirementsWorker?.getRequirementsReports); case "architecture_worker": return Boolean(d.architectureWorker?.getArchitectureReports); case "backend_worker": return Boolean(d.backendWorker?.getBackendBuildReports); case "executive_reporting_runtime": return Boolean(d.executiveReportingRuntime?.submitWorkerReport); case "worker_performance_review": return Boolean(d.workerPerformanceReview?.registerPerformanceWorker); case "worker_recovery_system": return Boolean(d.workerRecoverySystem?.registerRecoverableWorker); } }
}
