import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import path from "path";

const API_PROXY_PATHS = [
  "/auth",
  "/empire-constitution",
  "/empire-governance-doctrine",
  "/empire-architecture-constraints",
  "/empire-ux-identity-doctrine",
  "/empire-commercial-business-doctrine",
  "/ecommerce-os",
  "/product-discovery",
  "/business-workspace",
  "/brain",
  "/customer-orders",
  "/commerce-readiness",
  "/operation-first-dollar",
  "/eye-series",
  "/reality-integration",
  "/amazon-global-seller",
  "/commerce-intelligence-studio",
  "/executive-council",
  "/executive-surveillance",
  "/grand-king",
  "/grand-king-revenue-pipeline",
  "/marketplace-infrastructure",
  "/execution-layer",
  "/empire-self-inspection",
  "/master-completion-ledger",
  "/operational-access",
  "/integrations-hub",
  "/commerce-intelligence-core",
  "/supplier-intelligence",
  "/marketplace-publishing",
  "/listing-intelligence",
  "/product-media",
  "/commerce-execution-pipeline",
  "/global-commerce-execution",
  "/global-marketplace-operations",
  "/global-command-center",
  "/empire-economics",
  "/grand-king-financial-command-center",
  "/founder-platform-preparation",
  "/ai-self-improvement-engine",
  "/version-2-backlog-engine",
  "/version-1-readiness-audit",
  "/version-1-lockdown",
  "/customer-intelligence",
  "/competitor-intelligence",
  "/customer-psychology-engine",
  "/global-category-expansion-engine",
  "/global-revenue-simulation",
  "/ai-chief-of-commerce",
  "/ai-chief-of-growth",
  "/ai-chief-of-customer",
  "/global-strategy-engine",
  "/success-001-command-center",
  "/unified-grand-king-headquarters",
  "/world-operations-map",
  "/global-market-share-engine",
  "/product-portfolio-command",
  "/executive-war-room",
  "/soul-decision-chamber",
  "/mission-command-engine",
  "/global-execution-timeline",
  "/autonomous-analysis-engine",
  "/commercial-memory-engine",
  "/grand-king-live-operations-mode",
  "/global-operational-command-center",
  "/global-advertising-intelligence",
  "/first-order-operations",
  "/global-order-intelligence",
  "/post-purchase-intelligence",
  "/global-knowledge-evolution",
  "/ai-strategic-memory",
  "/empire-playbook-engine",
  "/global-risk-command",
  "/founder-platform-readiness",
  "/production-hardening",
  "/version-1-acceptance-test",
  "/grand-king-go-live-checklist",
  "/version-1-gold-master",
  "/live-product-intelligence",
  "/executive-product-optimization",
  "/supplier-intelligence-loop",
  "/global-opportunity-engine",
  "/revenue-improvement-engine",
  "/executive-visual-debate",
  "/health",
  "/global-business-health-engine",
  "/empire-kpi-engine",
  "/live-commercial-investigations",
  "/commercial-simulation-engine",
  "/global-expansion-command",
  "/commercial-explorer",
  "/empire-strategic-center",
  "/version-1-governance-review",
  "/success-001-readiness-review",
  "/version-1-executive-sign-off",
  "/global-supplier-market",
  "/global-marketplace-adapter-framework",
  "/marketplace-difference-engine",
  "/country-difference-engine",
  "/global-price-intelligence",
  "/shipping-intelligence",
  "/product-launch-commander",
  "/post-launch-commander",
  "/product-scale-engine",
  "/product-retirement-engine",
  "/empire-revenue-forecast",
  "/empire-cashflow-engine",
  "/empire-investment-engine",
  "/global-opportunity-board",
  "/executive-strategy-room",
  "/king-decision-history",
  "/soul-learning-review",
  "/empire-pattern-library",
  "/global-expansion-score",
  "/empire-priority-engine",
  "/command-center-polish",
  "/ux-review-preparation",
  "/performance-review",
  "/security-review",
  "/architecture-review",
  "/commercial-review",
  "/version-1-freeze-review",
  "/version-1-release-candidate",
  "/version-1-go-live-approval",
  "/version-1-completion",
];

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  server: {
    port: 5173,
    proxy: Object.fromEntries(
      API_PROXY_PATHS.map((prefix) => [
        prefix,
        { target: "http://127.0.0.1:4000", changeOrigin: true },
      ]),
    ),
  },
});
