import type { EmpireBootstrapContext } from "../bootstrap/types.js";
import { RepositoryReader } from "../bootstrap/repository-reader.js";
import { buildEmpireResilienceEngineConfiguration, type EmpireResilienceEngineConfiguration } from "./configuration.js";
import { EmpireResilienceController } from "./empire-resilience-controller.js";
import { EmpireResilienceManager, type EmpireResilienceDependencies } from "./empire-resilience-manager.js";
import { EMPIRE_RESILIENCE_ENGINE_SYSTEM_PATH } from "./paths.js";
import type { EmpireResilienceCockpitSnapshot, EmpireResilienceInput, EmpireResilienceState } from "./types.js";
export type { EmpireResilienceDependencies }; export interface EmpireResilienceEngineOptions { configuration?: Partial<EmpireResilienceEngineConfiguration>; }
export class EmpireResilienceEngine {
  private initializedAt: string | null = null; private readonly controller: EmpireResilienceController;
  constructor(private readonly bootstrap: EmpireBootstrapContext, dependencies: EmpireResilienceDependencies = {}, options: EmpireResilienceEngineOptions = {}) { this.controller = new EmpireResilienceController(new EmpireResilienceManager(dependencies), buildEmpireResilienceEngineConfiguration(bootstrap.repositoryRoot, options.configuration)); }
  async initialize() { const doc = await new RepositoryReader(this.bootstrap.repositoryRoot).readText(EMPIRE_RESILIENCE_ENGINE_SYSTEM_PATH); if (!doc?.includes("Empire Resilience Engine")) throw new Error(`${EMPIRE_RESILIENCE_ENGINE_SYSTEM_PATH} missing — X5-08 system doc required.`); this.controller.initialize(); this.initializedAt = new Date().toISOString(); return this.getState(); }
  getState(): EmpireResilienceState { if (!this.initializedAt) throw new Error("Empire Resilience Engine not initialized. Call initialize() first."); const configuration = this.controller.getConfiguration(), engineRecord = this.controller.getManager().getEngineRecord(), latestReport = this.controller.getLatestReport(), count = this.getResilienceRecords().length; return { engineVersion: "PILLOW-ERS-001", missionId: "X5-08", status: this.controller.getStatus(), initializedAt: this.initializedAt, configuration, latestReport, engineRecord, health: { status: engineRecord?.healthStatus ?? "standby", healthScore: engineRecord?.healthStatus === "healthy" ? 100 : engineRecord ? 70 : 50, engineEnabled: configuration.enabled, lastOperationAt: latestReport?.runTimestamp ?? null, lastValidationDecision: latestReport?.validation.decision ?? null, totalResilienceRecords: count, notes: ["Structural resilience signals only; recovery coordination never executes destructive actions."] } }; }
  connectEmpireResilienceEngine(input: Record<string, unknown> = {}) { return this.controller.connect(input); }
  monitorEnterpriseResilience(input: EmpireResilienceInput = {}) { return this.controller.run("monitor_enterprise_resilience", input); } detectOperationalFailures(input: EmpireResilienceInput = {}) { return this.controller.run("detect_operational_failures", { ...input, failureCategory: "operational" }); } detectInfrastructureFailures(input: EmpireResilienceInput = {}) { return this.controller.run("detect_infrastructure_failures", { ...input, failureCategory: "infrastructure" }); } detectBusinessDisruptions(input: EmpireResilienceInput = {}) { return this.controller.run("detect_business_disruptions", { ...input, failureCategory: "business" }); } detectSupplyChainDisruptions(input: EmpireResilienceInput = {}) { return this.controller.run("detect_supply_chain_disruptions", { ...input, failureCategory: "supply_chain" }); } detectFinancialDisruptions(input: EmpireResilienceInput = {}) { return this.controller.run("detect_financial_disruptions", { ...input, failureCategory: "financial" }); } assessEnterpriseResilience(input: EmpireResilienceInput = {}) { return this.controller.run("assess", input); } recommendResilienceActions(input: EmpireResilienceInput = {}) { return this.controller.run("recommend", input); } coordinateRecoveryActions(input: EmpireResilienceInput = {}) { return this.controller.run("coordinate_recovery", input); }
  runDiagnostics() { return this.controller.diagnostics(); } getResilienceRecords() { return this.controller.getManager().getResilienceRecords(); } getRecommendations() { return this.controller.getManager().getRecommendations(); } getEngineRecord() { return this.controller.getManager().getEngineRecord(); }
  validateForSupervisorSync() { const state = this.getState(), score = state.latestReport?.validation.decision === "fail" ? 40 : state.latestReport?.validation.decision === "partial" ? 70 : 100; return { valid: state.health.status !== "failed", health: score >= 75 ? "healthy" as const : score >= 50 ? "degraded" as const : "blocked" as const, readinessScore: score, notes: [`Engine status: ${state.status}`, `Resilience records: ${state.health.totalResilienceRecords}`, ...state.health.notes] }; }
  getCockpitSnapshot(): EmpireResilienceCockpitSnapshot { const state = this.getState(), record = state.engineRecord; return { engineStatus: state.status, healthStatus: state.health.status, operationalState: record?.currentOperationalState ?? null, lastDecision: state.latestReport?.validation.decision ?? null, totalResilienceRecords: state.health.totalResilienceRecords, frameworkRegistered: Boolean(record?.frameworkModuleId), dependenciesConnected: Number(Boolean(record?.dependencyPresence.empireIntelligenceFramework)) + Number(Boolean(record?.dependencyPresence.empireMemoryEngine)) + Number(Boolean(record?.dependencyPresence.empireKnowledgeEngine)), recentLogs: [] }; }
}
export function createEmpireResilienceEngine(bootstrap: EmpireBootstrapContext, dependencies: EmpireResilienceDependencies = {}, options?: EmpireResilienceEngineOptions) { return new EmpireResilienceEngine(bootstrap, dependencies, options); } export function resetEmpireResilienceEngineForTesting() {}
