import { readFileSync } from "node:fs"; import { join } from "node:path";
import type { EmpireBootstrapContext } from "../bootstrap/types.js"; import { buildWorkflowBuilderWorkerConfiguration } from "./configuration.js"; import { WORKFLOW_BUILDER_WORKER_SYSTEM_PATH,WBW_INTEGRATION_TARGETS } from "./paths.js"; import type { ApprovalGate,DecisionNode,FailureRecoveryPath,RetryPolicy,StepHandler,WorkflowBuildReport,WorkflowBuilderWorkerConfiguration,WorkflowBuilderWorkerDependencies,WorkflowBuilderWorkerState,WorkflowDefinition,WorkflowStep } from "./types.js"; import { WorkflowStore } from "./workflow-store.js"; import { TemplateStore } from "./template-store.js"; import { RunStore } from "./run-store.js"; import { BuildStore } from "./build-store.js"; import { WorkflowAudit } from "./workflow-audit.js"; import { WorkflowValidatorEngine } from "./workflow-validator-engine.js"; import { InMemoryStepHandler } from "./handlers.js";
const id=(p:string)=>`${p}-${crypto.randomUUID()}`,now=()=>new Date().toISOString();
export class WorkflowBuilderWorkerEngine {
 private initializedAt:string|null=null; private deps:WorkflowBuilderWorkerDependencies={}; private handler:StepHandler=new InMemoryStepHandler(); private requirementsReportId?:string;private architectureReportId?:string;
 readonly workflows=new WorkflowStore();readonly templates=new TemplateStore();readonly runs=new RunStore();readonly builds=new BuildStore();readonly audit=new WorkflowAudit();readonly validator=new WorkflowValidatorEngine();
 readonly config:WorkflowBuilderWorkerConfiguration;
 constructor(private bootstrap:{repositoryRoot:string}|EmpireBootstrapContext,options:{configuration?:Partial<WorkflowBuilderWorkerConfiguration>}={}){this.config=buildWorkflowBuilderWorkerConfiguration(bootstrap.repositoryRoot,options.configuration)}
 async initialize(){let doc="";try{doc=readFileSync(join(this.bootstrap.repositoryRoot,WORKFLOW_BUILDER_WORKER_SYSTEM_PATH),"utf8")}catch{throw new Error(`${WORKFLOW_BUILDER_WORKER_SYSTEM_PATH} missing`)}if(!doc.includes("Workflow Builder Worker"))throw new Error("Workflow Builder Worker governance document is invalid");this.initializedAt=now();this.audit.append("initialized",{doctrine:"PILLOW-WBW-001"});return this.getState()}
 bindIntegrations(deps:WorkflowBuilderWorkerDependencies={}){this.deps={...this.deps,...deps};return this.deps} connect(deps:WorkflowBuilderWorkerDependencies={}){return this.bindIntegrations(deps)}
 getState():WorkflowBuilderWorkerState {return {engineVersion:"PILLOW-WBW-001",missionId:"Q6-11",status:this.initializedAt?"ready":"idle",initializedAt:this.initializedAt,configuration:this.config,latestReport:this.builds.latest()}}
 validate(input:Record<string,unknown>={}){const forbidden=["replaceWorkerBusinessLogic","replaceRuntimeScheduling","replaceApprovalGovernance","fabricateWorkflowExecution","implementQ612OrLater","overridePillow","overrideGrandKing","overrideApprovedArchitecture"];const issues=forbidden.filter(k=>input[k]===true).map(k=>`Forbidden input: ${k}`);if(input.missionId!==undefined&&input.missionId!=="Q6-11")issues.push("missionId must be Q6-11");return {valid:!issues.length,issues}}
 diagnostics(){return {valid:this.validate().valid,workflows:this.workflows.list().length,runs:this.runs.list().length,targets:[...WBW_INTEGRATION_TARGETS]}}
 getCockpitSnapshot(){return {missionId:"Q6-11",status:this.getState().status,workerId:"wkr-workflow-builder-01",workflows:this.workflows.list().length,runs:this.runs.list().length,neverFabricateSuccessfulWorkflowExecution:true,neverImplementQ612OrLater:true}}
 validateForSupervisorSync(){return {valid:!!this.initializedAt,health:this.initializedAt?"healthy":"blocked",readinessScore:this.initializedAt?100:0,notes:[`Q6-11 ${this.getState().status}`]}}
 receiveApprovedRequirementsReports(input:Record<string,unknown>={}){if(!this.validate(input).valid)throw new Error(this.validate(input).issues.join("; "));this.requirementsReportId=String(input.reportId??id("wbw-bld"));return {buildId:id("wbw-bld"),requirementsReportId:this.requirementsReportId}} receiveApprovedRequirementsReport(input:Record<string,unknown>={}){return this.receiveApprovedRequirementsReports(input)}
 receiveApprovedArchitectureReports(input:Record<string,unknown>={}){if(!this.validate(input).valid)throw new Error(this.validate(input).issues.join("; "));this.architectureReportId=String(input.reportId??id("wbw-bld"));return {buildId:id("wbw-bld"),architectureReportId:this.architectureReportId}} receiveApprovedArchitectureReport(input:Record<string,unknown>={}){return this.receiveApprovedArchitectureReports(input)}
 createWorkflow({name,version="1.0.0",platformId,validated=false}:{name:string;version?:string;platformId?:string;validated?:boolean}){const t=now(),w:WorkflowDefinition={workflowId:id("wbw-wf"),name,version,platformId,steps:[],decisionNodes:[],approvalGates:[],retryPolicies:[],failureRecoveryPaths:[],automationRules:[],entryStepId:"",scheduleHook:null,status:validated?"validated":"draft",createdAt:t,updatedAt:t};return this.workflows.save(w)}
 private w(workflowId:string){const w=this.workflows.get(workflowId);if(!w)throw new Error("Workflow not found");return w} private save(w:WorkflowDefinition){w.updatedAt=now();return this.workflows.save(w)}
 addStep({workflowId,step}:{workflowId:string;step:WorkflowStep}){const w=this.w(workflowId);if(w.steps.some(s=>s.stepId===step.stepId))throw new Error("Duplicate step");w.steps.push(step);return this.save(w)}
 addDecisionNode({workflowId,decision}:{workflowId:string;decision:DecisionNode}){const w=this.w(workflowId);w.decisionNodes.push(decision);return this.save(w)} addApprovalGate({workflowId,gate}:{workflowId:string;gate:ApprovalGate}){const w=this.w(workflowId);w.approvalGates.push(gate);return this.save(w)} addRetryPolicy({workflowId,policy}:{workflowId:string;policy:RetryPolicy}){const w=this.w(workflowId);w.retryPolicies.push(policy);return this.save(w)} addFailureRecoveryPath({workflowId,path}:{workflowId:string;path:FailureRecoveryPath}){const w=this.w(workflowId);w.failureRecoveryPaths.push(path);return this.save(w)}
 setEntryStep({workflowId,entryStepId}:{workflowId:string;entryStepId:string}){const w=this.w(workflowId);w.entryStepId=entryStepId;return this.save(w)} setScheduleHook({workflowId,cron,eventType}:{workflowId:string;cron?:string;eventType?:string}){const w=this.w(workflowId);w.scheduleHook={cron,eventType};return this.save(w)}
 validateWorkflow({workflowId}:{workflowId:string}){const w=this.w(workflowId),r=this.validator.validate(w);if(r.valid)w.status="validated";this.save(w);return r} publishWorkflow({workflowId}:{workflowId:string}){const w=this.w(workflowId);if(w.status!=="validated"||!this.validator.validate(w).valid)throw new Error("Workflow must be validated before publishing");w.status="ready";return this.save(w)}
 saveTemplate({templateId,name,workflowId}:{templateId?:string;name:string;workflowId:string}){const w=this.w(workflowId);return this.templates.save({templateId:templateId??id("wbw-tpl"),name,workflow:structuredClone(w),createdAt:now()})} createFromTemplate({templateId,name}:{templateId:string;name?:string}){const t=this.templates.get(templateId);if(!t)throw new Error("Template not found");const w=structuredClone(t.workflow);w.workflowId=id("wbw-wf");w.name=name??w.name;w.status="draft";w.createdAt=w.updatedAt=now();return this.workflows.save(w)} setStepHandler(handler:StepHandler){this.handler=handler}
 startWorkflowRun({workflowId,context={}}:{workflowId:string;context?:Record<string,unknown>}){const w=this.w(workflowId);if(w.status!=="ready")throw new Error("Workflow must be ready");const r={runId:id("wbw-run"),workflowId,status:"running" as const,context,currentStepIds:[w.entryStepId],completedStepIds:[],attempts:{},createdAt:now(),updatedAt:now()};this.runs.save(r);return r}
 private rec(runId:string,stepId:string,status:"succeeded"|"failed"|"paused"|"scheduled"|"skipped",attempt:number,outcome?:unknown){return this.runs.record({recordId:id("wbw-step"),runId,stepId,status,attempt,timestamp:now(),outcome})}
 private enqueue(run:any,step:WorkflowStep,next:string[]){run.completedStepIds.push(step.stepId);run.currentStepIds=run.currentStepIds.filter((x:string)=>x!==step.stepId);for(const n of next)if(!run.completedStepIds.includes(n)&&!run.currentStepIds.includes(n))run.currentStepIds.push(n)}
 async executeRun({runId,maxSteps=100}:{runId:string;maxSteps?:number}){const run=this.runs.get(runId);if(!run)throw new Error("Run not found");if(run.status!=="running")return run;const w=this.w(run.workflowId);for(let i=0;i<maxSteps&&run.status==="running"&&run.currentStepIds.length;i++){const sid=run.currentStepIds[0];if(!sid)break;const s=w.steps.find(x=>x.stepId===sid);if(!s){run.status="failed";break}if(s.type==="parallel_join"){const incoming=w.steps.filter(x=>x.nextStepIds?.includes(sid)).map(x=>x.stepId);if(!incoming.every(x=>run.completedStepIds.includes(x))){const queued=run.currentStepIds.shift();if(queued)run.currentStepIds.push(queued);continue}}if(s.type==="approval"){this.rec(runId,sid,"paused",0);run.status="paused";break}if(s.type==="decision"){const d=w.decisionNodes.find(x=>x.stepId===sid);if(!d){this.rec(runId,sid,"failed",0,{error:"Missing decision"});run.status="failed";break}const value=run.context[d.expression]??run.context.branch;const next=value===true?d.trueNextStepId:d.falseNextStepId;this.rec(runId,sid,"succeeded",0,{selected:next});this.enqueue(run,s,[next]);continue}if(s.type==="delay"){this.rec(runId,sid,"scheduled",0,{delayMs:s.delayMs??0});this.enqueue(run,s,s.nextStepIds??[]);continue}if(s.type==="end"){this.rec(runId,sid,"succeeded",0);this.enqueue(run,s,[]);run.status="completed";break}if(["task","worker_invoke","api_invoke"].includes(s.type)){const attempt=(run.attempts[sid]??0)+1;run.attempts[sid]=attempt;const outcome=await this.handler.execute(s,run.context);if(outcome.success){this.rec(runId,sid,"succeeded",attempt,outcome);this.enqueue(run,s,s.nextStepIds??[]);continue}this.rec(runId,sid,"failed",attempt,outcome);const p=w.retryPolicies.find(x=>x.policyId===s.retryPolicyId);if(p&&attempt<=p.maxRetries)continue;const recovery=w.failureRecoveryPaths.find(x=>x.pathId===s.recoveryPathId||x.fromStepId===sid);if(recovery&&recovery.strategy!=="abort"){this.enqueue(run,s,[recovery.toStepId]);continue}run.status="failed";break}this.rec(runId,sid,"succeeded",0);this.enqueue(run,s,s.nextStepIds??[])}if(run.status==="running"&&!run.currentStepIds.length)run.status="completed";run.updatedAt=now();this.runs.save(run);return run}
 approveGate({runId,gateId,stepId,decision}:{runId:string;gateId?:string;stepId?:string;decision:"approved"|"rejected"}){const run=this.runs.get(runId);if(!run)throw new Error("Run not found");const w=this.w(run.workflowId),s=w.steps.find(x=>x.stepId===(stepId??run.currentStepIds[0]));const g=w.approvalGates.find(x=>(gateId&&x.gateId===gateId)||(!gateId&&x.stepId===s?.stepId));if(!s||!g)throw new Error("Approval gate not found");g.status=decision;if(decision==="rejected"){this.rec(runId,s.stepId,"failed",0,{decision});run.status="failed"}else{this.rec(runId,s.stepId,"succeeded",0,{decision});this.enqueue(run,s,s.nextStepIds??[]);run.status="running"}this.save(w);this.runs.save(run);return run}
 getWorkflows(){return this.workflows.list()}getTemplates(){return this.templates.list()}getRuns(){return this.runs.list()}getStepRecords(runId?:string){return this.runs.getRecords(runId)}getAuditEvents({limit=50}:{limit?:number}={}){return this.audit.list(limit)}
 buildMultiStepOperationalWorkflows(){return {stage:"multi_step_operational_workflows"}} createAutomationPipelines(){return {stage:"automation_pipelines"}}supportSequentialExecution(){return {stage:"sequential"}}supportParallelExecution(){return {stage:"parallel"}}supportConditionalBranching(){return {stage:"conditional"}}supportApprovalCheckpoints(){return {stage:"approval"}}supportRetryAndRecoveryPaths(){return {stage:"retry_recovery"}}supportReusableWorkflowTemplates(){return {stage:"templates"}}produceExecutionReadyWorkflowDefinitions(){return this.getWorkflows()}
 produceWorkflowBuildReport(input:{workflowId?:string;platformName?:string}={}){const w=input.workflowId?this.w(input.workflowId):this.workflows.list().at(-1);const r:WorkflowBuildReport={buildId:id("wbw-bld"),timestamp:now(),platformId:w?.platformId,platformName:input.platformName??"EmpireAI",workflowName:w?.name??"No workflow",workflowVersion:w?.version??"0.0.0",stepsDefined:w?.steps.length??0,decisionNodes:w?.decisionNodes??[],automationRules:w?.automationRules??[],approvalGates:w?.approvalGates??[],retryPolicies:w?.retryPolicies??[],failureRecoveryPaths:w?.failureRecoveryPaths??[],executionStatus:"definitions_ready",validationStatus:w?.status??"draft",outstandingIssues:[],confidenceScore:w?.status==="ready"?1:0.5,metadataVersion:"WBW-001-v1",buildStatus:"complete",neverReplaceWorkerBusinessLogic:true,neverReplaceRuntimeScheduling:true,neverReplaceApprovalGovernance:true,neverFabricateSuccessfulWorkflowExecution:true,neverImplementQ612OrLater:true,neverOverridePillowGrandKingApprovedArchitecture:true,followApprovedRequirementsAndArchitecture:true,preserveCompleteTraceability:true,preserveAuditHistory:true,reuseExistingRuntimeOrchestrationWhereAvailable:true,requirementsReportId:this.requirementsReportId,architectureReportId:this.architectureReportId,factoryMissionId:"Q6-11",buildSteps:["validated boundaries","preserved approval governance"],selfReview:"Execution success is solely based on recorded handler outcomes.",workerId:"wkr-workflow-builder-01",reportVersion:"WBW-RPT-v1",traceabilityRefs:[w?.workflowId??"none"],submittedToExecutiveReporting:false};return this.builds.save(r)}
 submitReport(input:{workflowId?:string;platformName?:string}={}){const report=this.produceWorkflowBuildReport(input);const runtime=this.deps.executiveReportingRuntime as {submitWorkerReport?:(i:Record<string,unknown>)=>unknown}|undefined;const result=runtime?.submitWorkerReport?.({missionId:"Q6-11",report});const candidate=(result as {records?:Array<{reportId?:string}>}|undefined)?.records?.[0]?.reportId??null;report.submittedToExecutiveReporting=Boolean(candidate);report.executiveReportId=candidate??undefined;this.builds.save(report);return report}
 list(){return this.builds.list()}
 getBuildReports(){return this.builds.list()}
}
export { WorkflowBuilderWorkerEngine as WorkflowBuilderWorker };
export const createWorkflowBuilderWorker=(bootstrap:EmpireBootstrapContext,options?:{configuration?:Partial<WorkflowBuilderWorkerConfiguration>;dependencies?:WorkflowBuilderWorkerDependencies})=>{const engine=new WorkflowBuilderWorkerEngine(bootstrap,options);if(options?.dependencies)engine.bindIntegrations(options.dependencies);return engine};
export const resetWorkflowBuilderWorkerForTesting=()=>{/* stores are per-instance */};
