import type { NODE_TYPES } from "./paths.js";
export type StepType = (typeof NODE_TYPES)[number]; export type WorkflowStatus="draft"|"validated"|"ready"|"archived"; export type RunStatus="running"|"paused"|"completed"|"failed";
export type WorkflowStep={stepId:string;type:StepType;name:string;nextStepIds?:string[];workerId?:string;condition?:string;parallelGroup?:string;approvalGateId?:string;retryPolicyId?:string;recoveryPathId?:string;delayMs?:number;metadata?:Record<string,unknown>};
export type DecisionNode={decisionId:string;stepId:string;expression:string;trueNextStepId:string;falseNextStepId:string};
export type ApprovalGate={gateId:string;stepId:string;requiredApproverRole:string;status:"pending"|"approved"|"rejected"};
export type RetryPolicy={policyId:string;maxRetries:number;backoffMs:number};
export type FailureRecoveryPath={pathId:string;fromStepId:string;toStepId:string;strategy:"retry"|"skip"|"abort"|"compensate"};
export type WorkflowDefinition={workflowId:string;name:string;version:string;platformId?:string;steps:WorkflowStep[];decisionNodes:DecisionNode[];approvalGates:ApprovalGate[];retryPolicies:RetryPolicy[];failureRecoveryPaths:FailureRecoveryPath[];automationRules:string[];entryStepId:string;scheduleHook?:{cron?:string;eventType?:string}|null;status:WorkflowStatus;createdAt:string;updatedAt:string};
export type WorkflowTemplate={templateId:string;name:string;workflow:WorkflowDefinition;createdAt:string};
export type StepExecutionRecord={recordId:string;runId:string;stepId:string;status:"succeeded"|"failed"|"paused"|"scheduled"|"skipped";attempt:number;timestamp:string;outcome?:unknown};
export type WorkflowRun={runId:string;workflowId:string;status:RunStatus;context:Record<string,unknown>;currentStepIds:string[];completedStepIds:string[];attempts:Record<string,number>;createdAt:string;updatedAt:string};
export type StepOutcome={success:boolean;output?:unknown;error?:string}; export interface StepHandler {execute(step:WorkflowStep,context:Record<string,unknown>):Promise<StepOutcome>|StepOutcome}
export type WorkflowBuildReport={buildId:string;timestamp:string;platformId?:string;platformName:string;workflowName:string;workflowVersion:string;stepsDefined:number|unknown[];decisionNodes:DecisionNode[];automationRules:string[];approvalGates:ApprovalGate[];retryPolicies:RetryPolicy[];failureRecoveryPaths:FailureRecoveryPath[];executionStatus:string;validationStatus:string;outstandingIssues:string[];confidenceScore:number;metadataVersion:"WBW-001-v1";buildStatus:"draft"|"in_progress"|"complete"|"failed";neverReplaceWorkerBusinessLogic:true;neverReplaceRuntimeScheduling:true;neverReplaceApprovalGovernance:true;neverFabricateSuccessfulWorkflowExecution:true;neverImplementQ612OrLater:true;neverOverridePillowGrandKingApprovedArchitecture:true;followApprovedRequirementsAndArchitecture:boolean;preserveCompleteTraceability:boolean;preserveAuditHistory:boolean;reuseExistingRuntimeOrchestrationWhereAvailable:true;requirementsReportId?:string;architectureReportId?:string;factoryMissionId?:string;businessId?:string;businessObjective?:string;buildSteps:string[];selfReview:string;workerId:"wkr-workflow-builder-01";reportVersion:"WBW-RPT-v1";traceabilityRefs:string[];submittedToExecutiveReporting:boolean;executiveReportId?:string};
export type WorkflowBuilderWorkerConfiguration={enabled:boolean;timeoutMs:number;neverReplaceWorkerBusinessLogic:true;neverReplaceRuntimeScheduling:true;neverReplaceApprovalGovernance:true;neverFabricateSuccessfulWorkflowExecution:true;neverImplementQ612OrLater:true;neverOverridePillowGrandKingApprovedArchitecture:true};
export type WorkflowBuilderWorkerState={engineVersion:"PILLOW-WBW-001";missionId:"Q6-11";status:string;initializedAt:string|null;configuration:WorkflowBuilderWorkerConfiguration;latestReport:WorkflowBuildReport|null};
export type WorkflowBuilderWorkerDependencies=Record<string,unknown>;
