import { useCallback, useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { EmpirePageShell } from "@/components/empire/EmpirePageShell";
import { ErrorState, LoadingState } from "@/components/ui/PageStates";
import { StatusBadge } from "@/components/ui/StatusBadge";
import {
  fetchBusinessOpportunities,
  generateBusinessPreview,
  getBusinessPreview,
  listBusinessPreviews,
} from "@/api/business";
import { paths } from "@/routes/paths";
import styles from "./BusinessPreviewPage.module.css";
import "@/styles/app.css";

function record(value: unknown): Record<string, unknown> | null {
  return value && typeof value === "object" ? (value as Record<string, unknown>) : null;
}

function str(value: unknown, fallback = ""): string {
  return typeof value === "string" ? value : fallback;
}

function arr(value: unknown): string[] {
  return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : [];
}

export function BusinessPreviewPage() {
  const { opportunityId } = useParams<{ opportunityId: string }>();
  const [preview, setPreview] = useState<Record<string, unknown> | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const previews = await listBusinessPreviews();
      const list = Array.isArray(previews) ? previews : [];
      let match = list.find(
        (item) => str(record(item)?.businessOpportunityId) === opportunityId,
      );

      if (!match && opportunityId) {
        const { opportunities } = await fetchBusinessOpportunities();
        const approved = opportunities.find((o) => str(o.businessOpportunityId) === opportunityId);
        if (approved && str(approved.status) === "APPROVED") {
          match = await generateBusinessPreview(opportunityId);
        }
      }

      if (match) {
        const previewId = str(record(match)?.previewId);
        setPreview(previewId ? await getBusinessPreview(previewId) : record(match));
      } else {
        setPreview(null);
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load preview");
    } finally {
      setLoading(false);
    }
  }, [opportunityId]);

  useEffect(() => {
    void load();
  }, [load]);

  async function handleGenerate() {
    if (!opportunityId) return;
    setBusy(true);
    try {
      const generated = await generateBusinessPreview(opportunityId);
      setPreview(record(generated));
    } finally {
      setBusy(false);
    }
  }

  if (loading) return <LoadingState message="Loading business preview…" />;
  if (error) return <ErrorState message={error} onRetry={() => void load()} />;

  if (!preview) {
    return (
      <EmpirePageShell eyebrow="Brand Workspace" title="Business Preview" description="Generate a visual preview for this business.">
        <p className="empireCardBody">No preview exists yet for this opportunity.</p>
        <div className="empireToolbar">
          <button type="button" className="empireBtnPrimary" disabled={busy} onClick={() => void handleGenerate()}>
            {busy ? "Generating…" : "Generate Preview"}
          </button>
          <Link className="empireBtnSecondary" to={paths.dashboard.brands}>
            Back to brands
          </Link>
        </div>
      </EmpirePageShell>
    );
  }

  const brand = record(preview.brandPreview);
  const product = record(preview.productPreview);
  const marketplace = record(preview.marketplacePreview);
  const palette = record(brand?.colourPalette);

  return (
    <EmpirePageShell
      eyebrow="Brand Workspace"
      title={str(preview.businessName, "Business Preview")}
      description="Brand, product assets, and marketplace previews — generated by Business Preview Studio."
    >
      <div className="empireToolbar">
        <StatusBadge status={str(preview.status, "GENERATED")} />
        <button type="button" className="empireBtnSecondary" disabled={busy} onClick={() => void handleGenerate()}>
          Regenerate
        </button>
        <Link className="empireBtnSecondary" to={paths.dashboard.launch}>
          Launch Mission
        </Link>
      </div>

      <section className={`panel ${styles.brandPanel}`}>
        <h2 className="panelTitle">Brand</h2>
        <div className={styles.brandRow}>
          <div className={styles.logoPreview} style={{ background: str(palette?.primary, "#6366f1") }}>
            {str(brand?.logo, "Logo").slice(0, 2).toUpperCase()}
          </div>
          <div>
            <h3>{str(brand?.brand)}</h3>
            <p>{str(brand?.brandStory)}</p>
            <div className={styles.swatches}>
              {palette &&
                Object.entries(palette).map(([key, color]) => (
                  <span key={key} className={styles.swatch} style={{ background: str(color) }} title={key} />
                ))}
            </div>
          </div>
        </div>
      </section>

      <div className="gridCards">
        <section className="panel">
          <h2 className="panelTitle">Product</h2>
          <h3>{str(product?.productTitle)}</h3>
          <p>{str(product?.productDescription)}</p>
          <p className="cardMeta">SEO: {str(product?.seoTitle)}</p>
          <ul className="panelList">
            {arr(product?.productImages).slice(0, 4).map((image) => (
              <li key={image}>{image}</li>
            ))}
          </ul>
        </section>

        <section className="panel">
          <h2 className="panelTitle">Marketplace Previews</h2>
          <ul className="panelList">
            <li>Homepage: {str(marketplace?.homepagePreview)}</li>
            <li>Amazon: {str(marketplace?.amazonListingPreview)}</li>
            <li>TikTok Shop: {str(marketplace?.tiktokShopPreview)}</li>
            <li>eBay: {str(marketplace?.ebayPreview)}</li>
            <li>Shopify: {str(marketplace?.shopifyProductPagePreview)}</li>
            <li>Google Merchant: {str(marketplace?.googleMerchantPreview)}</li>
          </ul>
        </section>

        <section className="panel">
          <h2 className="panelTitle">Gallery & Storyboard</h2>
          <ul className="panelList">
            {arr(product?.productGallery).map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
          <h3>Video storyboard</h3>
          <ul className="panelList">
            {arr(product?.productVideoStoryboard).map((frame) => (
              <li key={frame}>{frame}</li>
            ))}
          </ul>
        </section>
      </div>
    </EmpirePageShell>
  );
}
