import type { AuthenticationWorkerConfiguration } from "./configuration.js";
import { AuthenticationManager } from "./authentication-manager.js";
import type { AuthenticationWorkerDependencies } from "./integrations.js";
import type { AuthenticationWorkerInput } from "./types.js";
export class AuthenticationWorkerController {
  private status = "idle"; private latest: ReturnType<AuthenticationManager["list"]> | null = null;
  constructor(readonly manager: AuthenticationManager, readonly configuration: AuthenticationWorkerConfiguration) {}
  initialize() { this.status = "active"; } bindIntegrations(dependencies?: AuthenticationWorkerDependencies) { this.manager.bindIntegrations(dependencies); }
  connect() { this.status = "connecting"; return this.finish(this.manager.connect() as never); }
  receiveApprovedRequirementsReports(input?: AuthenticationWorkerInput) { return this.finish(this.manager.receiveApprovedRequirementsReports(input)); } receiveApprovedRequirementsReport(input?: AuthenticationWorkerInput) { return this.receiveApprovedRequirementsReports(input); }
  receiveApprovedArchitectureReports(input?: AuthenticationWorkerInput) { return this.finish(this.manager.receiveApprovedArchitectureReports(input)); } receiveApprovedArchitectureReport(input?: AuthenticationWorkerInput) { return this.receiveApprovedArchitectureReports(input); }
  createAndManageUserAccounts(input?: AuthenticationWorkerInput) { return this.finish(this.manager.stage("createAndManageUserAccounts", input)); } implementAccountRegistration(input?: AuthenticationWorkerInput) { return this.finish(this.manager.stage("implementAccountRegistration", input)); } implementSecureLoginAndLogout(input?: AuthenticationWorkerInput) { return this.finish(this.manager.stage("implementSecureLoginAndLogout", input)); } implementSessionLifecycle(input?: AuthenticationWorkerInput) { return this.finish(this.manager.stage("implementSessionLifecycle", input)); } implementSecurePasswordStorageAndCredentialValidation(input?: AuthenticationWorkerInput) { return this.finish(this.manager.stage("implementSecurePasswordStorageAndCredentialValidation", input)); } implementForgottenPasswordAndPasswordReset(input?: AuthenticationWorkerInput) { return this.finish(this.manager.stage("implementForgottenPasswordAndPasswordReset", input)); } implementAccountVerification(input?: AuthenticationWorkerInput) { return this.finish(this.manager.stage("implementAccountVerification", input)); } implementAuthenticationFailureHandlingAndSecurityProtections(input?: AuthenticationWorkerInput) { return this.finish(this.manager.stage("implementAuthenticationFailureHandlingAndSecurityProtections", input)); }
  produceAuthenticationBuildReport(input?: AuthenticationWorkerInput) { return this.finish(this.manager.produceAuthenticationBuildReport(input)); } submitReport(input?: AuthenticationWorkerInput) { return this.finish(this.manager.submitReport(input)); } list() { return this.finish(this.manager.list()); } validate(input?: AuthenticationWorkerInput) { return this.finish(this.manager.validate(input)); } diagnostics() { return this.finish(this.manager.diagnostics()); }
  private finish(result: any) { this.latest = result; this.status = result.validation?.decision === "fail" ? "failed" : "active"; return result; } getLatest() { return this.latest; } getStatus() { return this.status; }
}
