import type { EmpireBootstrapContext } from "../bootstrap/types.js";
import { RepositoryReader } from "../bootstrap/repository-reader.js";
import { resetAtwLogsForTesting } from "./atw-logging.js";
import { AuthenticationManager } from "./authentication-manager.js";
import { AuthenticationWorkerController } from "./authentication-worker-controller.js";
import { buildAuthenticationWorkerConfiguration, type AuthenticationWorkerConfiguration } from "./configuration.js";
import type { AuthenticationWorkerDependencies } from "./integrations.js";
import { AUTHENTICATION_WORKER_SYSTEM_PATH } from "./paths.js";
import type { AuthenticationWorkerInput, LoginInput, RegisterInput, ResetInput } from "./types.js";
export interface AuthenticationWorkerOptions { configuration?: Partial<AuthenticationWorkerConfiguration>; dependencies?: AuthenticationWorkerDependencies; }
export class AuthenticationWorker {
  private initializedAt: string | null = null; private readonly controller: AuthenticationWorkerController;
  constructor(private readonly bootstrap: EmpireBootstrapContext, options: AuthenticationWorkerOptions = {}) { const config = buildAuthenticationWorkerConfiguration(bootstrap.repositoryRoot, options.configuration); const manager = new AuthenticationManager(config); if (options.dependencies) manager.bindIntegrations(options.dependencies); this.controller = new AuthenticationWorkerController(manager, config); }
  async initialize() { const document = await new RepositoryReader(this.bootstrap.repositoryRoot).readText(AUTHENTICATION_WORKER_SYSTEM_PATH); if (!document?.includes("Authentication Worker")) throw new Error(`${AUTHENTICATION_WORKER_SYSTEM_PATH} missing — Q6-07 system doc required.`); this.controller.initialize(); this.initializedAt = new Date().toISOString(); return this.getState(); }
  bindIntegrations(dependencies?: AuthenticationWorkerDependencies) { this.controller.bindIntegrations(dependencies); } getState() { if (!this.initializedAt) throw new Error("Authentication Worker not initialized. Call initialize() first."); const report = this.controller.getLatest()?.latestAuthenticationBuildReport ?? null; return { engineVersion: "PILLOW-ATW-001", missionId: "Q6-07", status: this.controller.getStatus(), initializedAt: this.initializedAt, configuration: this.controller.configuration, latestReport: report, health: { status: report?.buildStatus === "failed" ? "failed" : "healthy", totalAuthenticationBuildReports: this.getAuthenticationBuildReports().length } }; }
  connect() { return this.controller.connect(); } receiveApprovedRequirementsReports(input?: AuthenticationWorkerInput) { return this.controller.receiveApprovedRequirementsReports(input); } receiveApprovedRequirementsReport(input?: AuthenticationWorkerInput) { return this.controller.receiveApprovedRequirementsReport(input); } receiveApprovedArchitectureReports(input?: AuthenticationWorkerInput) { return this.controller.receiveApprovedArchitectureReports(input); } receiveApprovedArchitectureReport(input?: AuthenticationWorkerInput) { return this.controller.receiveApprovedArchitectureReport(input); }
  createAndManageUserAccounts(input?: AuthenticationWorkerInput) { return this.controller.createAndManageUserAccounts(input); } implementAccountRegistration(input?: AuthenticationWorkerInput) { return this.controller.implementAccountRegistration(input); } implementSecureLoginAndLogout(input?: AuthenticationWorkerInput) { return this.controller.implementSecureLoginAndLogout(input); } implementSessionLifecycle(input?: AuthenticationWorkerInput) { return this.controller.implementSessionLifecycle(input); } implementSecurePasswordStorageAndCredentialValidation(input?: AuthenticationWorkerInput) { return this.controller.implementSecurePasswordStorageAndCredentialValidation(input); } implementForgottenPasswordAndPasswordReset(input?: AuthenticationWorkerInput) { return this.controller.implementForgottenPasswordAndPasswordReset(input); } implementAccountVerification(input?: AuthenticationWorkerInput) { return this.controller.implementAccountVerification(input); } implementAuthenticationFailureHandlingAndSecurityProtections(input?: AuthenticationWorkerInput) { return this.controller.implementAuthenticationFailureHandlingAndSecurityProtections(input); } produceAuthenticationBuildReport(input?: AuthenticationWorkerInput) { return this.controller.produceAuthenticationBuildReport(input); }
  submitReport(input?: AuthenticationWorkerInput) { return this.controller.submitReport(input); } list() { return this.controller.list(); } validate(input?: AuthenticationWorkerInput) { return this.controller.validate(input); } diagnostics() { return this.controller.diagnostics(); }
  registerAccount(input: RegisterInput) { return this.controller.manager.runtime.registerAccount(input); } login(input: LoginInput) { return this.controller.manager.runtime.login(input); } logout(input: { sessionToken: string }) { return this.controller.manager.runtime.logout(input.sessionToken); } validateSession(input: { sessionToken: string }) { return this.controller.manager.runtime.validateSession(input.sessionToken); } renewSession(input: { sessionToken: string }) { return this.controller.manager.runtime.renewSession(input.sessionToken); } revokeAllSessions(input: { userId: string }) { return this.controller.manager.runtime.revokeAllSessions(input.userId); } requestPasswordReset(input: { loginIdentifier: string }) { return this.controller.manager.runtime.requestPasswordReset(input.loginIdentifier); } resetPassword(input: ResetInput) { return this.controller.manager.runtime.resetPassword(input); } verifyAccount(input: { userId?: string; verificationToken: string }) { return this.controller.manager.runtime.verifyAccount(input); } getPublicUser(input: { userId: string }) { return this.controller.manager.runtime.getPublicUser(input.userId); } getAuthAuditEvents(input: { limit?: number } = {}) { return this.controller.manager.runtime.getAuthAuditEvents(input.limit); }
  getAuthenticationBuildReports() { return this.controller.manager.getReports(); } getCatalog() { return { workerId: this.controller.configuration.workerId, authenticationBuildReports: this.getAuthenticationBuildReports(), neverDefineRoles: true, neverDefinePermissions: true, neverBuildPolicyBasedAccessControl: true }; } getAuditTrail() { return this.controller.manager.getAuditTrail(); } getIntegrations() { return this.controller.manager.getIntegrations(); } getCockpitSnapshot() { const state = this.getState(); return { missionId: "Q6-07", status: state.status, healthStatus: state.health.status, totalAuthenticationBuildReports: state.health.totalAuthenticationBuildReports, workerId: state.configuration.workerId, neverDefineRoles: true, neverDefinePermissions: true, neverBuildPolicyBasedAccessControl: true, neverImplementQ608OrLater: true }; } validateForSupervisorSync() { const validation = this.validate({ validated: true }).validation; return { valid: validation.decision !== "fail", health: validation.decision === "pass" ? "healthy" : "degraded", readinessScore: validation.decision === "pass" ? 100 : 60, notes: validation.errors }; }
}
export const createAuthenticationWorker = (bootstrap: EmpireBootstrapContext, options?: AuthenticationWorkerOptions) => new AuthenticationWorker(bootstrap, options);
export const resetAuthenticationWorkerForTesting = () => resetAtwLogsForTesting();
