/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectAccountingWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    ledgerRulesEnabled: true,
    executiveReportingEnabled: true,
    requireGrandKingApproval: true,
    requirePillowCommandConfirmation: true,
    neverFabricateAccountingRecords: true,
    neverForecastFinances: true,
    neverApproveInvestments: true,
    neverReplaceBudgetPlanningWorker: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ903OrLater: true,
    preserveCompleteTraceability: true,
    preserveImmutableAccountingHistory: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q9-02",
    live: false,
    engine: {
      engineVersion: "PILLOW-ACCW-001",
      missionId: "Q9-02",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalEntries: 0,
        totalAccounts: 0,
        lastReportId: null,
        lastLedgerBalanced: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q9-02",
      status: "idle",
      healthStatus: "standby",
      totalEntries: 0,
      totalAccounts: 0,
      lastLedgerBalanced: null,
      latestCapitalBusinessId: null,
      neverFabricateAccountingRecords: true,
      neverForecastFinances: true,
      neverApproveInvestments: true,
      neverReplaceBudgetPlanningWorker: true,
      neverBypassGrandKingApproval: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverImplementQ903OrLater: true,
      consumableByQ903: true,
    },
    catalog: null,
    accounts: [],
    entries: [],
    reports: [],
  };
}
