/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectAdaptiveWorkforceOptimizerSnapshot() {
  const configuration = {
    enabled: true,
    analysisRulesEnabled: true,
    detectionRulesEnabled: true,
    recommendationRulesEnabled: true,
    neverExecuteWorkerTasks: true,
    neverModifyWorkersAutomatically: true,
    neverReplacePillow: true,
    neverOverrideGrandKing: true,
    neverPerformStrategicPlanning: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q0-17",
    live: false,
    engine: {
      engineVersion: "PILLOW-AWO-001",
      missionId: "Q0-17",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalOptimizationRecords: 0,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q0-17",
      status: "idle",
      healthStatus: "standby",
      totalOptimizationRecords: 0,
      latestOptimizationId: null,
      lastConfidenceScore: null,
      neverExecuteWorkerTasks: true,
      neverModifyWorkersAutomatically: true,
      neverReplacePillow: true,
      neverOverrideGrandKing: true,
      neverPerformStrategicPlanning: true,
    },
    latestRecord: null,
    records: [],
  };
}
