/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectAffiliateComplianceWorkerSnapshot() {
  const configuration = {
    enabled: true,
    complianceRulesEnabled: true,
    validationRulesEnabled: true,
    executiveReportingEnabled: true,
    neverFabricateComplianceResults: true,
    neverProvideUnverifiedLegalConclusions: true,
    neverPublishAffiliateContent: true,
    neverReplaceLegalProfessionals: true,
    neverOverrideProgrammeRequirements: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ809OrLater: true,
    preserveCompleteTraceability: true,
    preserveComplianceAuditHistory: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q8-08",
    live: false,
    engine: {
      engineVersion: "PILLOW-ACW-001",
      missionId: "Q8-08",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        totalHistoryEntries: 0,
        lastReportId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q8-08",
      status: "idle",
      healthStatus: "standby",
      totalReports: 0,
      totalHistoryEntries: 0,
      latestReportId: null,
      neverFabricateComplianceResults: true,
      neverProvideUnverifiedLegalConclusions: true,
      neverPublishAffiliateContent: true,
      neverReplaceLegalProfessionals: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverBypassGrandKingApproval: true,
      neverImplementQ809OrLater: true,
      consumableByQ809: true,
    },
    catalog: null,
    reports: [],
    history: [],
  };
}
