/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectAffiliateCertificationSnapshot() {
  const configuration = {
    enabled: true,
    evidenceScanEnabled: true,
    runtimeProbingEnabled: true,
    executiveReportingEnabled: true,
    neverFabricateVerificationResults: true,
    neverCertifyUnsupportedFunctionality: true,
    neverImplementMissingFunctionality: true,
    neverAutoCorrectFailedImplementations: true,
    neverOverrideGovernance: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ901OrLater: true,
    preserveCompleteTraceability: true,
    preserveCertificationAuditHistory: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q8-09",
    live: false,
    engine: {
      engineVersion: "PILLOW-AFCRT-001",
      missionId: "Q8-09",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        lastReportId: null,
        lastCertificationDecision: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q8-09",
      status: "idle",
      healthStatus: "standby",
      totalReports: 0,
      latestReportId: null,
      lastCertificationDecision: null,
      lastConfidenceScore: null,
      workerId: "wkr-affiliate-certification-01",
      componentStatusOptions: [
        "Completed",
        "Partially Implemented",
        "Missing",
        "Broken / Deviating",
        "Intentionally Deferred",
      ],
      neverFabricateVerificationResults: true,
      neverCertifyUnsupportedFunctionality: true,
      neverImplementMissingFunctionality: true,
      neverAutoCorrectFailedImplementations: true,
      neverOverrideGovernance: true,
      neverOverrideApprovedArchitecture: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverBypassGrandKingApproval: true,
      neverImplementQ901OrLater: true,
      finalQ8Gate: true,
    },
    catalog: null,
    reports: [],
  };
}
