/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectAffiliateFactoryCoreSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    projectRulesEnabled: true,
    lifecycleRulesEnabled: true,
    executiveReportingEnabled: true,
    requireGrandKingApproval: true,
    requirePillowCommandConfirmation: true,
    neverDiscoverAffiliateProgrammes: true,
    neverGenerateAffiliateContent: true,
    neverLaunchBusinessesAutomatically: true,
    neverFabricateWorkerStatus: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ802OrLater: true,
    preserveCompleteTraceability: true,
    preserveFactoryAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q8-01",
    live: false,
    engine: {
      engineVersion: "PILLOW-AFC-001",
      missionId: "Q8-01",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalProjects: 0,
        lastProjectId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q8-01",
      status: "idle",
      healthStatus: "standby",
      totalProjects: 0,
      latestAffiliateBusinessId: null,
      neverDiscoverAffiliateProgrammes: true,
      neverGenerateAffiliateContent: true,
      neverLaunchBusinessesAutomatically: true,
      neverFabricateWorkerStatus: true,
      neverBypassGrandKingApproval: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverImplementQ802OrLater: true,
    },
    catalog: null,
    projects: [],
    reports: [],
  };
}
