/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectAffiliateOpportunityWorkerSnapshot() {
  const configuration = {
    enabled: true,
    opportunityRulesEnabled: true,
    validationRulesEnabled: true,
    executiveReportingEnabled: true,
    neverFabricateCommissionOrDemandData: true,
    neverCreateAffiliateContent: true,
    neverPublishWebsites: true,
    neverJoinAffiliateProgrammesAutomatically: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ803OrLater: true,
    preserveCompleteTraceability: true,
    preserveResearchEvidence: true,
    preserveAuditHistory: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q8-02",
    live: false,
    engine: {
      engineVersion: "PILLOW-AOW-001",
      missionId: "Q8-02",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        totalOpportunities: 0,
        lastReportId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q8-02",
      status: "idle",
      healthStatus: "standby",
      totalReports: 0,
      totalOpportunities: 0,
      latestReportId: null,
      neverFabricateCommissionOrDemandData: true,
      neverCreateAffiliateContent: true,
      neverPublishWebsites: true,
      neverJoinAffiliateProgrammesAutomatically: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverBypassGrandKingApproval: true,
      neverImplementQ803OrLater: true,
      consumableByQ803: true,
    },
    catalog: null,
    reports: [],
    opportunities: [],
  };
}
