/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectAnalyticsWorkerSnapshot() {
  const configuration = {
    enabled: true,
    analyticsRulesEnabled: true,
    validationRulesEnabled: true,
    executiveReportingEnabled: true,
    neverFabricateAnalyticsOrPerformanceResults: true,
    neverModifyCampaignsAutomatically: true,
    neverManipulateAnalytics: true,
    neverReplaceAffiliateComplianceWorker: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ808OrLater: true,
    preserveCompleteTraceability: true,
    preserveAnalyticsHistory: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q8-07",
    live: false,
    engine: {
      engineVersion: "PILLOW-ANW-001",
      missionId: "Q8-07",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        totalHistoryEntries: 0,
        lastReportId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q8-07",
      status: "idle",
      healthStatus: "standby",
      totalReports: 0,
      totalHistoryEntries: 0,
      latestReportId: null,
      neverFabricateAnalyticsOrPerformanceResults: true,
      neverModifyCampaignsAutomatically: true,
      neverManipulateAnalytics: true,
      neverReplaceAffiliateComplianceWorker: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverBypassGrandKingApproval: true,
      neverImplementQ808OrLater: true,
      consumableByQ808: true,
    },
    catalog: null,
    reports: [],
    history: [],
  };
}
