/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectApiRuntimeSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    apiRulesEnabled: true,
    executiveReportingEnabled: true,
    neverExposeSecrets: true,
    neverExposeCredentials: true,
    neverFabricateApiResponses: true,
    neverBypassPillowGovernance: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ1007OrLater: true,
    preserveCompleteTraceability: true,
    preserveApiInteractionHistory: true,
    preserveAuditHistory: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
    deterministicRoutingOnly: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q10-06",
    live: false,
    engine: {
      engineVersion: "PILLOW-APIRT-001",
      missionId: "Q10-06",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalProviders: 0,
        totalTraces: 0,
        lastReportId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q10-06",
      status: "idle",
      healthStatus: "standby",
      totalProviders: 0,
      totalTraces: 0,
      latestReportId: null,
      lastConfidenceScore: null,
      workerId: "wkr-api-runtime-01",
      neverExposeSecrets: true,
      neverExposeCredentials: true,
      neverFabricateApiResponses: true,
      neverBypassPillowGovernance: true,
      neverBypassGrandKingApproval: true,
      neverImplementQ1007OrLater: true,
      structuralSignalOnly: true,
    },
    history: null,
    reports: [],
    q1007Contract: null,
  };
}
