/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectApprovalRuntimeSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    approvalRulesEnabled: true,
    executiveReportingEnabled: true,
    neverBypassPillowGovernance: true,
    neverBypassGrandKingApproval: true,
    neverFabricateApprovalDecisions: true,
    neverAutoApproveRestrictedActions: true,
    neverImplementQ1010OrLater: true,
    neverReplaceBusinessLogic: true,
    neverReplaceWorkerImplementations: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    preserveCompleteTraceability: true,
    preserveApprovalHistory: true,
    preserveAuditHistory: true,
    preventUnauthorizedExecution: true,
    deterministicApprovalRouting: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q10-09",
    live: false,
    engine: {
      engineVersion: "PILLOW-APVRT-001",
      missionId: "Q10-09",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalPolicies: 0,
        totalRequests: 0,
        lastReportId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q10-09",
      status: "idle",
      healthStatus: "standby",
      totalPolicies: 0,
      totalRequests: 0,
      latestReportId: null,
      lastConfidenceScore: null,
      workerId: "wkr-approval-runtime-01",
      neverBypassPillowGovernance: true,
      neverBypassGrandKingApproval: true,
      neverFabricateApprovalDecisions: true,
      neverAutoApproveRestrictedActions: true,
      neverImplementQ1010OrLater: true,
      structuralSignalOnly: true,
    },
    history: null,
    reports: [],
    q1010Contract: null,
  };
}
