/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectArchitectureWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    architectureRulesEnabled: true,
    executiveReportingEnabled: true,
    requireQualityReview: true,
    neverWriteFrontendCode: true,
    neverWriteBackendCode: true,
    neverDeployApplications: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementApplicationLogic: true,
    neverImplementQ604OrLater: true,
    followApprovedRequirements: true,
    preserveCompleteTraceability: true,
    separateArchitecturalDecisionsFromAssumptions: true,
    validateArchitecturalConsistency: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q6-03",
    live: false,
    engine: {
      engineVersion: "PILLOW-ARW-001",
      missionId: "Q6-03",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalArchitectureReports: 0,
        lastArchitectureReportId: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q6-03",
      status: "idle",
      healthStatus: "standby",
      totalArchitectureReports: 0,
      latestArchitectureReportId: null,
      neverWriteFrontendCode: true,
      neverWriteBackendCode: true,
      neverDeployApplications: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverImplementApplicationLogic: true,
      neverImplementQ604OrLater: true,
    },
    catalog: null,
    architectureReports: [],
  };
}
