/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectAuditRuntimeSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    auditRulesEnabled: true,
    executiveReportingEnabled: true,
    neverFabricateAuditEvidence: true,
    neverDeleteAuditRecords: true,
    neverExecuteBusinessLogic: true,
    neverModifyOperationalData: true,
    neverBypassPillowGovernance: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ1014OrLater: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    preserveCompleteTraceability: true,
    preserveImmutableAuditHistory: true,
    preserveAuditHistory: true,
    deterministicAuditRecording: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q10-13",
    live: false,
    engine: {
      engineVersion: "PILLOW-AUDRT-001",
      missionId: "Q10-13",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalAuditRecords: 0,
        lastReportId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q10-13",
      status: "idle",
      healthStatus: "standby",
      totalAuditRecords: 0,
      latestReportId: null,
      lastConfidenceScore: null,
      workerId: "wkr-audit-runtime-01",
      neverFabricateAuditEvidence: true,
      neverDeleteAuditRecords: true,
      neverExecuteBusinessLogic: true,
      neverModifyOperationalData: true,
      neverBypassPillowGovernance: true,
      neverBypassGrandKingApproval: true,
      neverImplementQ1014OrLater: true,
      structuralSignalOnly: true,
    },
    history: null,
    reports: [],
    q1014Contract: null,
  };
}
