/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectAuthorityMatrixSnapshot() {
  const configuration = {
    enabled: true,
    definitionRulesEnabled: true,
    registrationRulesEnabled: true,
    derivationRulesEnabled: true,
    workerAuthorityRulesEnabled: true,
    pillowAuthorityRulesEnabled: true,
    grandKingAuthorityRulesEnabled: true,
    approvalRoutingRulesEnabled: true,
    validationRulesEnabled: true,
    neverExecuteWorkerTasks: true,
    neverReplaceApprovalRouter: true,
    neverReplaceOrganizationCharter: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q1-05",
    live: false,
    engine: {
      engineVersion: "PILLOW-AMX-001",
      missionId: "Q1-05",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        matrixVersion: "AMX-MATRIX-v1",
        totalRules: 0,
        totalBindings: 0,
        authorityLevelCount: 0,
        decisionCategoryCount: 0,
        lastMatrixDecision: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q1-05",
      status: "idle",
      healthStatus: "standby",
      matrixVersion: "AMX-MATRIX-v1",
      totalRules: 0,
      authorityLevelCount: 0,
      decisionCategoryCount: 0,
      latestBindingId: null,
      neverExecuteWorkerTasks: true,
      neverReplaceApprovalRouter: true,
      neverReplaceOrganizationCharter: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    rules: [],
    latestBinding: null,
    bindings: [],
  };
}
