/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectBookingWorkerSnapshot() {
  const configuration = {
    enabled: true,
    bookingRulesEnabled: true,
    validationRulesEnabled: true,
    executiveReportingEnabled: true,
    neverPerformTheService: true,
    neverProcessPayments: true,
    neverReplaceCrm: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverFabricateBookingConfirmations: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ705OrLater: true,
    preserveCompleteTraceability: true,
    preserveBookingAuditHistory: true,
    neverExposeCredentials: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q7-04",
    live: false,
    engine: {
      engineVersion: "PILLOW-BKW-001",
      missionId: "Q7-04",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        totalBookings: 0,
        lastReportId: null,
        lastBookingId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q7-04",
      status: "idle",
      healthStatus: "standby",
      totalReports: 0,
      totalBookings: 0,
      latestReportId: null,
      neverPerformTheService: true,
      neverProcessPayments: true,
      neverReplaceCrm: true,
      neverFabricateBookingConfirmations: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverBypassGrandKingApproval: true,
      neverImplementQ705OrLater: true,
      consumableByQ705: true,
    },
    catalog: null,
    bookings: [],
    reports: [],
  };
}
