/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectBudgetPlanningWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    budgetRulesEnabled: true,
    executiveReportingEnabled: true,
    requireGrandKingApproval: true,
    requirePillowCommandConfirmation: true,
    neverFabricateBudgetValuesOrSpendingData: true,
    neverApproveExpenditure: true,
    neverExecutePayments: true,
    neverForecastRevenue: true,
    neverReplaceProfitabilityWorker: true,
    neverModifyAccountingRecords: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ905OrLater: true,
    preserveCompleteTraceability: true,
    preserveHistoricalBudgetRevisions: true,
    neverExposeCredentials: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q9-04",
    live: false,
    engine: {
      engineVersion: "PILLOW-BPW-001",
      missionId: "Q9-04",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalBudgets: 0,
        totalVariances: 0,
        lastReportId: null,
        lastApprovalStatus: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q9-04",
      status: "idle",
      healthStatus: "standby",
      totalBudgets: 0,
      totalVariances: 0,
      lastApprovalStatus: null,
      latestCapitalBusinessId: null,
      neverFabricateBudgetValuesOrSpendingData: true,
      neverApproveExpenditure: true,
      neverExecutePayments: true,
      neverForecastRevenue: true,
      neverReplaceProfitabilityWorker: true,
      neverBypassGrandKingApproval: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverImplementQ905OrLater: true,
      consumableByQ905: true,
    },
    catalog: null,
    budgets: [],
    variances: [],
    recommendations: [],
    reports: [],
  };
}
