/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectBusinessIdeaInterpreterSnapshot() {
  const configuration = {
    enabled: true,
    interpretationRulesEnabled: true,
    missingInformationRulesEnabled: true,
    validationRulesEnabled: true,
    neverGenerateBusinessModels: true,
    neverResearchMarkets: true,
    neverBuildBusinesses: true,
    neverAssignWorkers: true,
    neverExecuteAnything: true,
    neverImplementQ203OrLater: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    preserveOriginalCommandTraceability: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q2-02",
    live: false,
    engine: {
      engineVersion: "PILLOW-BII-001",
      missionId: "Q2-02",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalIntents: 0,
        lastIntentId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q2-02",
      status: "idle",
      healthStatus: "standby",
      totalIntents: 0,
      latestIntentId: null,
      neverGenerateBusinessModels: true,
      neverResearchMarkets: true,
      neverBuildBusinesses: true,
      neverAssignWorkers: true,
      neverExecuteAnything: true,
      neverImplementQ203OrLater: true,
    },
    catalog: null,
    intents: [],
  };
}
