/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectBusinessBlueprintWorkerSnapshot() {
  const configuration = {
    enabled: true,
    blueprintRulesEnabled: true,
    validationRulesEnabled: true,
    executiveReportingEnabled: true,
    requireProceedRecommendation: true,
    neverExecuteBusiness: true,
    neverLaunchProducts: true,
    neverCreateBranding: true,
    neverBuildWebsites: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ207OrLater: true,
    preserveCompleteTraceability: true,
    preserveAuditHistory: true,
    produceSingleCanonicalBlueprint: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q2-06",
    live: false,
    engine: {
      engineVersion: "PILLOW-BBW-001",
      missionId: "Q2-06",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalBlueprints: 0,
        lastBlueprintId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q2-06",
      status: "idle",
      healthStatus: "standby",
      totalBlueprints: 0,
      latestBlueprintId: null,
      workerId: "wkr-business-blueprint-01",
      neverExecuteBusiness: true,
      neverLaunchProducts: true,
      neverCreateBranding: true,
      neverBuildWebsites: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    blueprints: [],
    integrations: [],
  };
}
