/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectBusinessFactoryAuditSnapshot() {
  const configuration = {
    enabled: true,
    discoveryEnabled: true,
    workflowProbingEnabled: true,
    executiveReportingEnabled: true,
    neverFabricateAuditEvidence: true,
    neverCertifyIncompleteWorkflows: true,
    neverCertifyMissingIntegrations: true,
    neverAssumeImplementation: true,
    neverModifyFactoryImplementations: true,
    neverRepairFailedFactories: true,
    neverBypassPillowGovernance: true,
    neverBypassGrandKingApproval: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ1105OrLater: true,
    preserveCompleteTraceability: true,
    preserveImmutableAuditHistory: true,
    preserveAuditHistory: true,
    deterministicAuditBehaviour: true,
    structuralSignalOnly: true,
    evidenceBasedOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q11-04",
    live: false,
    engine: {
      engineVersion: "PILLOW-BFART-001",
      missionId: "Q11-04",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        lastReportId: null,
        lastDecision: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q11-04",
      status: "idle",
      healthStatus: "standby",
      totalReports: 0,
      latestReportId: null,
      lastDecision: null,
      lastConfidenceScore: null,
      workerId: "wkr-business-factory-audit-01",
      readinessClassificationOptions: [
        "certified",
        "partially_certified",
        "failed",
        "missing",
        "blocked",
        "deferred",
      ],
      neverFabricateAuditEvidence: true,
      neverCertifyIncompleteWorkflows: true,
      neverCertifyMissingIntegrations: true,
      neverAssumeImplementation: true,
      neverModifyFactoryImplementations: true,
      neverRepairFailedFactories: true,
      neverBypassPillowGovernance: true,
      neverBypassGrandKingApproval: true,
      neverOverrideApprovedArchitecture: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverImplementQ1105OrLater: true,
      fourthQ11Gate: true,
    },
    catalog: null,
    reports: [],
    q1105Contract: null,
  };
}
