/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectBusinessRiskWorkerSnapshot() {
  const configuration = {
    enabled: true,
    assessmentRulesEnabled: true,
    validationRulesEnabled: true,
    executiveReportingEnabled: true,
    neverRemoveRisksAutomatically: true,
    neverApproveBusiness: true,
    neverRejectBusiness: true,
    neverLaunchBusiness: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ209OrLater: true,
    requireEvidenceBasedFindings: true,
    preserveCompleteTraceability: true,
    preserveAuditHistory: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q2-08",
    live: false,
    engine: {
      engineVersion: "PILLOW-BRW-001",
      missionId: "Q2-08",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalRiskReports: 0,
        lastRiskReportId: null,
        lastPortfolioRiskRating: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q2-08",
      status: "idle",
      healthStatus: "standby",
      totalRiskReports: 0,
      latestRiskReportId: null,
      lastPortfolioRiskRating: null,
      workerId: "wkr-business-risk-01",
      neverRemoveRisksAutomatically: true,
      neverApproveBusiness: true,
      neverRejectBusiness: true,
      neverLaunchBusiness: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    riskReports: [],
    integrations: [],
  };
}
