/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectBusinessApprovalPackWorkerSnapshot() {
  const configuration = {
    enabled: true,
    consolidationRulesEnabled: true,
    validationRulesEnabled: true,
    executiveReportingEnabled: true,
    neverApproveBusiness: true,
    neverLaunchBusiness: true,
    neverModifyPreviousReports: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ210OrLater: true,
    preserveCompleteTraceability: true,
    preserveAuditHistory: true,
    distinguishFactsFromRecommendations: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q2-09",
    live: false,
    engine: {
      engineVersion: "PILLOW-BAP-001",
      missionId: "Q2-09",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalApprovalPacks: 0,
        lastApprovalPackId: null,
        lastRecommendation: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q2-09",
      status: "idle",
      healthStatus: "standby",
      totalApprovalPacks: 0,
      latestApprovalPackId: null,
      lastRecommendation: null,
      workerId: "wkr-business-approval-pack-01",
      neverApproveBusiness: true,
      neverLaunchBusiness: true,
      neverModifyPreviousReports: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    approvalPacks: [],
    integrations: [],
  };
}
