/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectCapitalRiskWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    capitalRiskRulesEnabled: true,
    executiveReportingEnabled: true,
    requireGrandKingApproval: true,
    requirePillowCommandConfirmation: true,
    neverApproveFinancialDecisions: true,
    neverExecuteInvestments: true,
    neverMoveCapital: true,
    neverModifyAccountingRecords: true,
    neverFabricateRisksOrEvidence: true,
    neverAutomaticallyExecuteMitigation: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ911OrLater: true,
    preserveCompleteTraceability: true,
    preserveRiskHistory: true,
    neverExposeCredentials: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
    observedRisksDistinctFromPredictions: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q9-10",
    live: false,
    engine: {
      engineVersion: "PILLOW-CAPRW-001",
      missionId: "Q9-10",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalRisks: 0,
        totalReports: 0,
        totalDashboards: 0,
        lastBusinessId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q9-10",
      status: "idle",
      healthStatus: "standby",
      totalRisks: 0,
      totalReports: 0,
      totalDashboards: 0,
      latestCapitalBusinessId: null,
      neverApproveFinancialDecisions: true,
      neverExecuteInvestments: true,
      neverMoveCapital: true,
      neverFabricateRisksOrEvidence: true,
      neverAutomaticallyExecuteMitigation: true,
      neverBypassGrandKingApproval: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverImplementQ911OrLater: true,
      consumableByQ911: true,
    },
    catalog: null,
    dashboards: [],
    reports: [],
  };
}
