/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectCapitalFactoryCertificationSnapshot() {
  const configuration = {
    enabled: true,
    evidenceScanEnabled: true,
    runtimeProbingEnabled: true,
    executiveReportingEnabled: true,
    neverFabricateSuccessfulTests: true,
    neverAssumeImplementation: true,
    neverImplementMissingWorkers: true,
    neverModifyFinancialRecords: true,
    neverAutomaticallyFixFailures: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ10OrLater: true,
    preserveCompleteTraceability: true,
    preserveCertificationHistory: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    structuralSignalOnly: true,
    evidenceBasedOnly: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q9-11",
    live: false,
    engine: {
      engineVersion: "PILLOW-CAPCRT-001",
      missionId: "Q9-11",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        lastReportId: null,
        lastCertificationDecision: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q9-11",
      status: "idle",
      healthStatus: "standby",
      totalReports: 0,
      latestReportId: null,
      lastCertificationDecision: null,
      lastConfidenceScore: null,
      workerId: "wkr-capital-factory-certification-01",
      workerCertificationStatusOptions: [
        "Certified",
        "Partially Certified",
        "Failed Certification",
        "Blocked",
        "Deferred",
      ],
      neverFabricateSuccessfulTests: true,
      neverAssumeImplementation: true,
      neverImplementMissingWorkers: true,
      neverModifyFinancialRecords: true,
      neverAutomaticallyFixFailures: true,
      neverOverrideApprovedArchitecture: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverBypassGrandKingApproval: true,
      neverImplementQ10OrLater: true,
      finalQ9Gate: true,
    },
    catalog: null,
    reports: [],
  };
}
