/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectCashflowWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    cashflowRulesEnabled: true,
    executiveReportingEnabled: true,
    requireGrandKingApproval: true,
    requirePillowCommandConfirmation: true,
    neverFabricateBalancesOrFlows: true,
    neverCreateBudgets: true,
    neverForecastFutureCashflow: true,
    neverCalculateCompleteBusinessProfitability: true,
    neverApproveSpending: true,
    neverMoveMoney: true,
    neverModifyVerifiedAccountingRecords: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ904OrLater: true,
    preserveCompleteTraceability: true,
    preserveHistoricalReports: true,
    neverExposeCredentials: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q9-03",
    live: false,
    engine: {
      engineVersion: "PILLOW-CFW-001",
      missionId: "Q9-03",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalMovements: 0,
        totalViews: 0,
        lastReportId: null,
        lastReconciliationStatus: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q9-03",
      status: "idle",
      healthStatus: "standby",
      totalMovements: 0,
      totalViews: 0,
      lastReconciliationStatus: null,
      latestCapitalBusinessId: null,
      neverFabricateBalancesOrFlows: true,
      neverCreateBudgets: true,
      neverForecastFutureCashflow: true,
      neverMoveMoney: true,
      neverBypassGrandKingApproval: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverImplementQ904OrLater: true,
      consumableByQ904: true,
    },
    catalog: null,
    movements: [],
    views: [],
    reports: [],
  };
}
