/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectChannelRecommendationWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    recommendationRulesEnabled: true,
    executiveReportingEnabled: true,
    neverCreateChannels: true,
    neverConfigurePlatformAccounts: true,
    neverPublishContent: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ418OrLater: true,
    neverCreateChannelsAutomatically: true,
    baseRecommendationsOnEvidence: true,
    preserveCompleteSourceTraceability: true,
    distinguishFactsFromAssumptions: true,
    explainEveryRecommendation: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q4-17",
    live: false,
    engine: {
      engineVersion: "PILLOW-CRW-001",
      missionId: "Q4-17",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalRecommendationReports: 0,
        lastRecommendationId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q4-17",
      status: "idle",
      healthStatus: "standby",
      totalRecommendationReports: 0,
      latestRecommendationId: null,
      neverCreateChannels: true,
      neverCreateChannelsAutomatically: true,
      neverPublishContent: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverImplementQ418OrLater: true,
    },
    catalog: null,
    reports: [],
  };
}
