/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectCheckoutWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    checkoutRulesEnabled: true,
    executiveReportingEnabled: true,
    requireQualityReview: true,
    defaultCurrency: "USD",
    defaultCheckoutFlow: "one_time_purchase",
    neverChargeCustomers: true,
    neverExecutePaymentTransactions: true,
    neverDeliverProducts: true,
    neverPublishStorefronts: true,
    neverStoreSensitivePaymentCredentials: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ510OrLater: true,
    followApprovedProductInformation: true,
    preserveCompleteTraceability: true,
    validateCheckoutIntegrityBeforeSubmission: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q5-09",
    live: false,
    engine: {
      engineVersion: "PILLOW-CKW-001",
      missionId: "Q5-09",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalCheckouts: 0,
        lastCheckoutId: null,
        lastCheckoutFlowType: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q5-09",
      status: "idle",
      healthStatus: "standby",
      totalCheckouts: 0,
      latestCheckoutId: null,
      neverChargeCustomers: true,
      neverExecutePaymentTransactions: true,
      neverDeliverProducts: true,
      neverPublishStorefronts: true,
      neverStoreSensitivePaymentCredentials: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    checkouts: [],
  };
}
