/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectCommerceFactoryCoreSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    missionRulesEnabled: true,
    classificationRulesEnabled: true,
    executiveReportingEnabled: true,
    missionCoordinationEnabled: true,
    requireGrandKingApproval: true,
    requireProceedRecommendation: true,
    neverBuildStores: true,
    neverImportProducts: true,
    neverConfigureMarketplaces: true,
    neverExecuteCommerceImplementation: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ302OrLater: true,
    preserveCompleteTraceability: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q3-01",
    live: false,
    engine: {
      engineVersion: "PILLOW-CMF-001",
      missionId: "Q3-01",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalMissions: 0,
        lastMissionId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q3-01",
      status: "idle",
      healthStatus: "standby",
      totalMissions: 0,
      latestMissionId: null,
      neverBuildStores: true,
      neverImportProducts: true,
      neverConfigureMarketplaces: true,
      neverExecuteCommerceImplementation: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    missions: [],
  };
}
