/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectCommunicationRuntimeSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    communicationRulesEnabled: true,
    executiveReportingEnabled: true,
    neverFabricateMessages: true,
    neverLoseAcknowledgedMessages: true,
    neverBypassPillowGovernance: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ1009OrLater: true,
    neverExecuteBusinessLogic: true,
    neverReplaceWorkerImplementations: true,
    neverReplaceOrchestrationLogic: true,
    preserveCompleteTraceability: true,
    preserveCommunicationHistory: true,
    preserveAuditHistory: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
    deterministicMessageRouting: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q10-08",
    live: false,
    engine: {
      engineVersion: "PILLOW-COMRT-001",
      missionId: "Q10-08",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalChannels: 0,
        totalMessages: 0,
        lastReportId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q10-08",
      status: "idle",
      healthStatus: "standby",
      totalChannels: 0,
      totalMessages: 0,
      latestReportId: null,
      lastConfidenceScore: null,
      workerId: "wkr-communication-runtime-01",
      neverFabricateMessages: true,
      neverLoseAcknowledgedMessages: true,
      neverBypassPillowGovernance: true,
      neverBypassGrandKingApproval: true,
      neverImplementQ1009OrLater: true,
      structuralSignalOnly: true,
    },
    history: null,
    reports: [],
    q1009Contract: null,
  };
}
