/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectCommerceAnalyticsWorkerSnapshot() {
  const configuration = {
    enabled: true,
    analyticsRulesEnabled: true,
    validationRulesEnabled: true,
    executiveReportingEnabled: true,
    highConversionThreshold: 0.08,
    lowConversionThreshold: 0.02,
    highMarginThreshold: 20,
    lowMarginThreshold: 10,
    lowRefundThreshold: 0.05,
    highRefundThreshold: 0.15,
    significantChangePercent: 0.2,
    neverModifyProducts: true,
    neverModifyPricing: true,
    neverModifySuppliers: true,
    neverExecuteOptimizations: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ314OrLater: true,
    neverModifyOperationalData: true,
    preserveCompleteTraceability: true,
    preserveHistoricalAnalytics: true,
    distinguishMeasuredFromEstimates: true,
    highlightSignificantChanges: true,
    preserveAuditHistory: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q3-13",
    live: false,
    engine: {
      engineVersion: "PILLOW-CAW-001",
      missionId: "Q3-13",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalAnalyticsReports: 0,
        lastAnalyticsReportId: null,
        lastProductPerformanceClassification: null,
        lastConfidenceScore: null,
        lastOpportunityCount: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q3-13",
      status: "idle",
      healthStatus: "standby",
      totalAnalyticsReports: 0,
      latestAnalyticsReportId: null,
      lastProductPerformanceClassification: null,
      lastConfidenceScore: null,
      lastOpportunityCount: null,
      neverModifyProducts: true,
      neverModifyPricing: true,
      neverModifySuppliers: true,
      neverExecuteOptimizations: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverModifyOperationalData: true,
    },
    catalog: null,
    analyticsReports: [],
  };
}
