/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectCommerceCertificationSnapshot() {
  const configuration = {
    enabled: true,
    certificationRulesEnabled: true,
    componentRulesEnabled: true,
    integrationRulesEnabled: true,
    governanceRulesEnabled: true,
    readinessRulesEnabled: true,
    validationRulesEnabled: true,
    neverOperateLiveCommerceBusiness: true,
    neverModifyCommerceFactoryComponents: true,
    neverRepairFailuresAutomatically: true,
    neverBeginQ4Implementation: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    preserveCertificationTraceability: true,
    preserveAuditability: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q3-14",
    live: false,
    engine: {
      engineVersion: "PILLOW-CMC-001",
      missionId: "Q3-14",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalCertificationReports: 0,
        certifiedCount: 0,
        failedCount: 0,
        lastFinalResult: null,
        q3ProductionReady: false,
        q4ReadinessConfirmed: false,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q3-14",
      status: "idle",
      healthStatus: "standby",
      totalCertificationReports: 0,
      latestCertificationId: null,
      q3ProductionReady: false,
      q4ReadinessConfirmed: false,
      neverOperateLiveCommerceBusiness: true,
      neverModifyCommerceFactoryComponents: true,
      neverRepairFailuresAutomatically: true,
      neverBeginQ4Implementation: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    reports: [],
  };
}
