/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectComparisonSiteWorkerSnapshot() {
  const configuration = {
    enabled: true,
    comparisonRulesEnabled: true,
    validationRulesEnabled: true,
    executiveReportingEnabled: true,
    neverFabricateRankingsOrProductInformation: true,
    neverPublishWebsites: true,
    neverManipulateRankingsWithoutEvidence: true,
    neverReplaceReviewContentWorker: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ804OrLater: true,
    preserveCompleteTraceability: true,
    preserveAuditHistory: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q8-03",
    live: false,
    engine: {
      engineVersion: "PILLOW-CSW-001",
      missionId: "Q8-03",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        totalPages: 0,
        lastReportId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q8-03",
      status: "idle",
      healthStatus: "standby",
      totalReports: 0,
      totalPages: 0,
      latestReportId: null,
      neverFabricateRankingsOrProductInformation: true,
      neverPublishWebsites: true,
      neverManipulateRankingsWithoutEvidence: true,
      neverReplaceReviewContentWorker: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverBypassGrandKingApproval: true,
      neverImplementQ804OrLater: true,
      consumableByQ804: true,
    },
    catalog: null,
    reports: [],
  };
}
