/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectCourseBuilderWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    courseRulesEnabled: true,
    executiveReportingEnabled: true,
    requireInstructionalFlowValidation: true,
    neverBuildSalesPages: true,
    neverProcessPayments: true,
    neverDeliverCoursesToCustomers: true,
    neverPublishCoursesDirectly: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ506OrLater: true,
    followApprovedProductResearch: true,
    followApprovedProductIntent: true,
    produceOriginalCourseMaterial: true,
    preserveCompleteTraceability: true,
    validateEducationalQuality: true,
    performSelfReviewBeforeSubmission: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q5-05",
    live: false,
    engine: {
      engineVersion: "PILLOW-CBW-001",
      missionId: "Q5-05",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalCourses: 0,
        lastCourseId: null,
        lastProductType: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q5-05",
      status: "idle",
      healthStatus: "standby",
      totalCourses: 0,
      latestCourseId: null,
      neverBuildSalesPages: true,
      neverProcessPayments: true,
      neverDeliverCoursesToCustomers: true,
      neverPublishCoursesDirectly: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    courses: [],
  };
}
