/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectCrmWorkerSnapshot() {
  const configuration = {
    enabled: true,
    crmRulesEnabled: true,
    validationRulesEnabled: true,
    executiveReportingEnabled: true,
    neverExecuteMarketingCampaigns: true,
    neverDeliverCustomerJobs: true,
    neverReplaceBookingFunctionality: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverFabricateCustomerInteractions: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ706OrLater: true,
    preserveCompleteCustomerHistory: true,
    preserveCompleteTraceability: true,
    preserveCrmAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeProhibitedPersonalData: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q7-05",
    live: false,
    engine: {
      engineVersion: "PILLOW-CRMW-001",
      missionId: "Q7-05",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        totalCustomers: 0,
        totalLeads: 0,
        lastReportId: null,
        lastCustomerId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q7-05",
      status: "idle",
      healthStatus: "standby",
      totalReports: 0,
      totalCustomers: 0,
      totalLeads: 0,
      latestReportId: null,
      neverExecuteMarketingCampaigns: true,
      neverDeliverCustomerJobs: true,
      neverReplaceBookingFunctionality: true,
      neverFabricateCustomerInteractions: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverBypassGrandKingApproval: true,
      neverImplementQ706OrLater: true,
      consumableByQ706: true,
    },
    catalog: null,
    customers: [],
    leads: [],
    reports: [],
  };
}
