/** Safe offline snapshot; live operations are supplied by the Pillow host. */

export function collectCursorSpecificationGeneratorSnapshot() {
  const configuration = {
    enabled: true,
    executiveReportingEnabled: true,
    neverImplementCode: true,
    neverExecuteCursorMissions: true,
    neverFabricateRepositoryFindings: true,
    neverInventMissions: true,
    neverImplementQ1305OrLater: true,
    neverSelfApprove: true,
    neverBypassGovernance: true,
    specificationOnly: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q13-04",
    live: false,
    engine: {
      engineVersion: "PILLOW-CSGEN-001",
      missionId: "Q13-04",
      status: "standby",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      latestSpecification: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 0,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        totalSpecifications: 0,
        lastReportId: null,
        lastSpecificationId: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot; specification generation withheld"],
      },
    },
    cockpit: {
      missionId: "Q13-04",
      status: "standby",
      healthStatus: "standby",
      totalReports: 0,
      totalSpecifications: 0,
      latestReportId: null,
      latestSpecificationId: null,
      workerId: "wkr-cursor-specification-generator-01",
      neverImplementCode: true,
      neverExecuteCursorMissions: true,
      neverImplementQ1305OrLater: true,
      neverSelfApprove: true,
      neverBypassGovernance: true,
    },
    catalog: null,
    reports: [],
    specifications: [],
    q1305Contract: null,
    specificationHistory: [],
  };
}
