/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectDecisionMemorySnapshot() {
  const configuration = {
    enabled: true,
    recordingRulesEnabled: true,
    lookupRulesEnabled: true,
    neverMakeDecisions: true,
    neverExecuteWork: true,
    neverReplaceExecutionMemory: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q0-16",
    live: false,
    engine: {
      engineVersion: "PILLOW-DMEM-001",
      missionId: "Q0-16",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalDecisionRecords: 0,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q0-16",
      status: "idle",
      healthStatus: "standby",
      totalDecisionRecords: 0,
      latestDecisionId: null,
      lastConfidenceScore: null,
      neverMakeDecisions: true,
      neverExecuteWork: true,
      neverReplaceExecutionMemory: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    latestRecord: null,
    records: [],
  };
}
