/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectDesignWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    designRulesEnabled: true,
    executiveReportingEnabled: true,
    requireQualityReview: true,
    neverBuildSalesPages: true,
    neverProcessPayments: true,
    neverDeliverProducts: true,
    neverPublishAssetsDirectly: true,
    neverPublishProductsDirectly: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ508OrLater: true,
    followApprovedProductIntent: true,
    produceOriginalVisualAssets: true,
    maintainConsistentBranding: true,
    preserveCompleteTraceability: true,
    performQualityReviewBeforeSubmission: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q5-07",
    live: false,
    engine: {
      engineVersion: "PILLOW-DW-001",
      missionId: "Q5-07",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalDesignReports: 0,
        lastDesignReportId: null,
        lastProductType: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q5-07",
      status: "idle",
      healthStatus: "standby",
      totalDesignReports: 0,
      latestDesignReportId: null,
      neverBuildSalesPages: true,
      neverProcessPayments: true,
      neverDeliverProducts: true,
      neverPublishAssetsDirectly: true,
      neverPublishProductsDirectly: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    designReports: [],
  };
}
