/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectDigitalProductAnalyticsWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    analyticsRulesEnabled: true,
    executiveReportingEnabled: true,
    requireQualityReview: true,
    defaultAnalyticsType: "sales_performance",
    neverEditProducts: true,
    neverProcessPayments: true,
    neverDeliverProducts: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ512OrLater: true,
    neverModifyProductsWithoutPillowApproval: true,
    neverFabricateMetrics: true,
    preserveCompleteDataTraceability: true,
    distinguishMeasuredDataFromRecommendations: true,
    preserveHistoricalAnalytics: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q5-11",
    live: false,
    engine: {
      engineVersion: "PILLOW-DPA-001",
      missionId: "Q5-11",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalAnalyticsReports: 0,
        lastAnalyticsReportId: null,
        lastAnalyticsType: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q5-11",
      status: "idle",
      healthStatus: "standby",
      totalAnalyticsReports: 0,
      latestAnalyticsReportId: null,
      neverEditProducts: true,
      neverProcessPayments: true,
      neverDeliverProducts: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverImplementQ512OrLater: true,
      neverFabricateMetrics: true,
    },
    catalog: null,
    analyticsReports: [],
  };
}
