/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectDigitalProductResearchWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    researchRulesEnabled: true,
    executiveReportingEnabled: true,
    useApprovedResearchSourcesOnly: true,
    neverCreateDigitalProducts: true,
    neverCreateSalesPages: true,
    neverProcessPayments: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverInventUnsupportedMarketEvidence: true,
    neverImplementQ503OrLater: true,
    distinguishFactsFromAssumptions: true,
    preserveCompleteSourceTraceability: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q5-02",
    live: false,
    engine: {
      engineVersion: "PILLOW-DPR-001",
      missionId: "Q5-02",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalResearchReports: 0,
        lastResearchReportId: null,
        lastOpportunityScore: null,
        lastConfidenceScore: null,
        lastRecommendedPriority: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q5-02",
      status: "idle",
      healthStatus: "standby",
      totalResearchReports: 0,
      latestResearchReportId: null,
      neverCreateDigitalProducts: true,
      neverCreateSalesPages: true,
      neverProcessPayments: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    reports: [],
  };
}
