/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectDigitalProductsCertificationSnapshot() {
  const configuration = {
    enabled: true,
    certificationRulesEnabled: true,
    componentRulesEnabled: true,
    integrationRulesEnabled: true,
    governanceRulesEnabled: true,
    readinessRulesEnabled: true,
    validationRulesEnabled: true,
    neverAutomaticallyFixFailures: true,
    neverAutomaticallyCertifyIncompleteWork: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverBeginQ6Implementation: true,
    neverAssumeImplementation: true,
    preserveCompleteTraceability: true,
    preserveAuditHistory: true,
    reportEveryDeviationHonestly: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q5-12",
    live: false,
    engine: {
      engineVersion: "PILLOW-DPC-001",
      missionId: "Q5-12",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalCertificationReports: 0,
        certifiedCount: 0,
        failedCount: 0,
        lastCertificationStatus: null,
        q5ProductionReady: false,
        q6ReadinessConfirmed: false,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q5-12",
      status: "idle",
      healthStatus: "standby",
      totalCertificationReports: 0,
      latestCertificationId: null,
      q5ProductionReady: false,
      q6ReadinessConfirmed: false,
      neverAutomaticallyFixFailures: true,
      neverAutomaticallyCertifyIncompleteWork: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverBeginQ6Implementation: true,
    },
    reports: [],
  };
}
