/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectDigitalDeliveryWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    deliveryRulesEnabled: true,
    executiveReportingEnabled: true,
    requireQualityReview: true,
    defaultDeliveryMethod: "secure_file_download",
    neverProcessPayments: true,
    neverCreateProducts: true,
    neverPublishStorefronts: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ511OrLater: true,
    neverExposeUnauthorizedAccess: true,
    deliverOnlyVerifiedPurchases: true,
    protectCustomerAccess: true,
    preserveCompleteFulfilmentTraceability: true,
    validateSuccessfulDelivery: true,
    preserveAuditHistory: true,
    neverBypassPillowGovernance: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q5-10",
    live: false,
    engine: {
      engineVersion: "PILLOW-DDW-001",
      missionId: "Q5-10",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalDeliveries: 0,
        lastDeliveryId: null,
        lastDeliveryType: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q5-10",
      status: "idle",
      healthStatus: "standby",
      totalDeliveries: 0,
      latestDeliveryId: null,
      neverProcessPayments: true,
      neverCreateProducts: true,
      neverPublishStorefronts: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverImplementQ511OrLater: true,
      neverExposeUnauthorizedAccess: true,
    },
    catalog: null,
    deliveries: [],
  };
}
