/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectDigitalProductsFactoryCoreSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    missionRulesEnabled: true,
    lifecycleRulesEnabled: true,
    executiveReportingEnabled: true,
    missionCoordinationEnabled: true,
    requireGrandKingApproval: true,
    requirePillowCommandConfirmation: true,
    neverCreateEbooks: true,
    neverCreateCourses: true,
    neverBuildSalesPages: true,
    neverProcessPayments: true,
    neverBypassApproval: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ502OrLater: true,
    preserveCompleteTraceability: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q5-01",
    live: false,
    engine: {
      engineVersion: "PILLOW-DPF-001",
      missionId: "Q5-01",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalMissions: 0,
        lastMissionId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q5-01",
      status: "idle",
      healthStatus: "standby",
      totalMissions: 0,
      latestMissionId: null,
      neverCreateEbooks: true,
      neverCreateCourses: true,
      neverBuildSalesPages: true,
      neverProcessPayments: true,
      neverBypassApproval: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    missions: [],
    reports: [],
  };
}
