/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectEbookWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    ebookRulesEnabled: true,
    executiveReportingEnabled: true,
    requireSelfReview: true,
    neverBuildSalesPages: true,
    neverProcessPayments: true,
    neverDeliverProductsToCustomers: true,
    neverPublishProductsDirectly: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ504OrLater: true,
    followApprovedProductResearch: true,
    followApprovedProductIntent: true,
    produceOriginalContent: true,
    preserveCompleteTraceability: true,
    performSelfReviewBeforeSubmission: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q5-03",
    live: false,
    engine: {
      engineVersion: "PILLOW-EBW-001",
      missionId: "Q5-03",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalEbooks: 0,
        lastEbookId: null,
        lastProductType: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q5-03",
      status: "idle",
      healthStatus: "standby",
      totalEbooks: 0,
      latestEbookId: null,
      neverBuildSalesPages: true,
      neverProcessPayments: true,
      neverDeliverProductsToCustomers: true,
      neverPublishProductsDirectly: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    ebooks: [],
  };
}
