/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectEditorInChiefWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    editorialRulesEnabled: true,
    executiveReportingEnabled: true,
    requirePillowGovernance: true,
    neverWriteScripts: true,
    neverCreateThumbnails: true,
    neverAssembleVideos: true,
    neverPublishContent: true,
    neverBypassPillowGovernance: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ403OrLater: true,
    preserveEditorialConsistency: true,
    preserveChannelIdentity: true,
    preserveAudienceAlignment: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q4-02",
    live: false,
    engine: {
      engineVersion: "PILLOW-ECW-001",
      missionId: "Q4-02",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalEditorialReports: 0,
        lastEditorialReportId: null,
        lastReviewOutcome: null,
        lastApprovalStatus: null,
        lastBrandConsistencyStatus: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q4-02",
      status: "idle",
      healthStatus: "standby",
      totalEditorialReports: 0,
      latestEditorialReportId: null,
      neverWriteScripts: true,
      neverCreateThumbnails: true,
      neverAssembleVideos: true,
      neverPublishContent: true,
      neverBypassPillowGovernance: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    reports: [],
  };
}
