/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectEmpireBuilderFactoryCoreSnapshot() {
  const configuration = {
    enabled: true,
    acceptanceRulesEnabled: true,
    classificationRulesEnabled: true,
    preparationRulesEnabled: true,
    validationRulesEnabled: true,
    neverInterpretDetailedBusinessStrategy: true,
    neverGenerateBusinessModels: true,
    neverResearchMarkets: true,
    neverAssignWorkers: true,
    neverExecuteBusinesses: true,
    neverLaunchBusinesses: true,
    neverImplementQ202OrLater: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    preserveTraceability: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q2-01",
    live: false,
    engine: {
      engineVersion: "PILLOW-EBF-001",
      missionId: "Q2-01",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalMissions: 0,
        lastMissionId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q2-01",
      status: "idle",
      healthStatus: "standby",
      totalMissions: 0,
      latestMissionId: null,
      neverInterpretDetailedBusinessStrategy: true,
      neverGenerateBusinessModels: true,
      neverResearchMarkets: true,
      neverAssignWorkers: true,
      neverExecuteBusinesses: true,
      neverLaunchBusinesses: true,
      neverImplementQ202OrLater: true,
    },
    catalog: null,
    missions: [],
  };
}
