/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectEmpireBuilderModelGeneratorSnapshot() {
  const configuration = {
    enabled: true,
    generationRulesEnabled: true,
    validationRulesEnabled: true,
    neverValidateDemand: true,
    neverPerformMarketResearch: true,
    neverBuildBranding: true,
    neverAssignWorkers: true,
    neverLaunchBusiness: true,
    neverImplementQ204OrLater: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    preserveIntentTraceability: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q2-03",
    live: false,
    engine: {
      engineVersion: "PILLOW-EMG-001",
      missionId: "Q2-03",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalModels: 0,
        lastBusinessModelId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q2-03",
      status: "idle",
      healthStatus: "standby",
      totalModels: 0,
      latestBusinessModelId: null,
      neverValidateDemand: true,
      neverPerformMarketResearch: true,
      neverBuildBranding: true,
      neverAssignWorkers: true,
      neverLaunchBusiness: true,
      neverImplementQ204OrLater: true,
    },
    catalog: null,
    models: [],
  };
}
