/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectEnterpriseExecutiveSituationalAwarenessEngineSnapshot() {
  const configuration = {
    enabled: true,
    executiveReportingEnabled: true,
    neverFabricateMetrics: true,
    neverSilentDeterioration: true,
    neverAutoModifyProduction: true,
    neverBypassGovernance: true,
    preserveAwarenessHistory: true,
    preserveAuditHistory: true,
    constitutionalDutyActive: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "EESAE-01",
    live: false,
    engine: {
      engineVersion: "PILLOW-EESAE-001",
      missionId: "EESAE-01",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      latestAwarenessState: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 35,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        openFindings: 0,
        openEscalations: 0,
        lastReportId: null,
        lastStateId: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "EESAE-01",
      status: "idle",
      healthStatus: "standby",
      totalReports: 0,
      openFindings: 0,
      openEscalations: 0,
      latestReportId: null,
      lastStateId: null,
      workerId: "wkr-enterprise-executive-situational-awareness-01",
      briefingPreview: null,
      neverFabricateMetrics: true,
      neverSilentDeterioration: true,
      neverAutoModifyProduction: true,
      neverBypassGovernance: true,
      constitutionalDutyActive: true,
    },
    reports: [],
    awarenessStates: [],
    briefing: null,
  };
}
