/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectEscalationFrameworkSnapshot() {
  const configuration = {
    enabled: true,
    detectionRulesEnabled: true,
    routingRulesEnabled: true,
    trackingRulesEnabled: true,
    validationRulesEnabled: true,
    neverExecuteWorkerTasks: true,
    neverResolveBusinessDisputes: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverReplaceExecutiveJudgement: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q0-22",
    live: false,
    engine: {
      engineVersion: "PILLOW-ESF-001",
      missionId: "Q0-22",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalEscalationRecords: 0,
        openEscalations: 0,
        lastPriority: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q0-22",
      status: "idle",
      healthStatus: "standby",
      totalEscalationRecords: 0,
      latestEscalationId: null,
      openEscalations: 0,
      neverExecuteWorkerTasks: true,
      neverResolveBusinessDisputes: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverReplaceExecutiveJudgement: true,
    },
    latestRecord: null,
    records: [],
  };
}
