/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectExecutiveAuditEngineSnapshot() {
  const configuration = {
    enabled: true,
    inspectionRulesEnabled: true,
    validationRulesEnabled: true,
    reportingRulesEnabled: true,
    neverExecuteCorrections: true,
    neverApproveMissions: true,
    neverAssignWorkers: true,
    neverModifyBusinessState: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q0-08",
    live: false,
    engine: {
      engineVersion: "PILLOW-EXA-001",
      missionId: "Q0-08",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalAudits: 0,
        violationCount: 0,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q0-08",
      status: "idle",
      healthStatus: "standby",
      totalAudits: 0,
      violationCount: 0,
      latestAuditId: null,
      neverExecuteCorrections: true,
      neverApproveMissions: true,
      neverAssignWorkers: true,
      neverModifyBusinessState: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    latestAuditReport: null,
    reports: [],
  };
}
