/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectExecutiveAcceptancePackSnapshot() {
  const configuration = {
    enabled: true,
    aggregationEnabled: true,
    executiveReportingEnabled: true,
    neverFabricateAcceptanceEvidence: true,
    neverHideFailedAudits: true,
    neverApproveProductionDeployment: true,
    neverOverrideFailedCertifications: true,
    neverBypassPillowGovernance: true,
    neverBypassGrandKingApproval: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ1110OrLater: true,
    preserveCompleteTraceability: true,
    preserveImmutablePackHistory: true,
    preserveAuditHistory: true,
    deterministicPackBehaviour: true,
    structuralSignalOnly: true,
    evidenceBasedOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q11-09",
    live: false,
    engine: {
      engineVersion: "PILLOW-EAPRT-001",
      missionId: "Q11-09",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        lastReportId: null,
        lastDecision: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q11-09",
      status: "idle",
      healthStatus: "standby",
      totalReports: 0,
      latestReportId: null,
      lastDecision: null,
      lastConfidenceScore: null,
      workerId: "wkr-executive-acceptance-pack-01",
      readinessClassificationOptions: [
        "certified",
        "partially_certified",
        "failed",
        "missing",
        "blocked",
        "deferred",
      ],
      neverFabricateAcceptanceEvidence: true,
      neverHideFailedAudits: true,
      neverApproveProductionDeployment: true,
      neverOverrideFailedCertifications: true,
      neverBypassPillowGovernance: true,
      neverBypassGrandKingApproval: true,
      neverOverrideApprovedArchitecture: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverImplementQ1110OrLater: true,
      ninthQ11Gate: true,
    },
    catalog: null,
    reports: [],
    q1110Contract: null,
  };
}
