/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectExecutiveReportingRuntimeSnapshot() {
  const configuration = {
    enabled: true,
    workerReportingEnabled: true,
    departmentReportingEnabled: true,
    factoryReportingEnabled: true,
    executiveReportingEnabled: true,
    aggregationRulesEnabled: true,
    summaryRulesEnabled: true,
    neverExecuteWorkerLogic: true,
    neverReplaceMonitoringRuntime: true,
    neverReplaceMissionCoordination: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q0-26",
    live: false,
    engine: {
      engineVersion: "PILLOW-ERT-001",
      missionId: "Q0-26",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReportRecords: 0,
        openBlockerCount: 0,
        averageProgress: 0,
        lastReportType: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q0-26",
      status: "idle",
      healthStatus: "standby",
      totalReportRecords: 0,
      latestReportId: null,
      openBlockerCount: 0,
      neverExecuteWorkerLogic: true,
      neverReplaceMonitoringRuntime: true,
      neverReplaceMissionCoordination: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    latestRecord: null,
    latestSummary: null,
    records: [],
  };
}
