/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectExperienceReplayEngineSnapshot() {
  const configuration = {
    enabled: true,
    learningRulesEnabled: true,
    neverExecuteWork: true,
    neverReplaceExecutionMemory: true,
    neverReplaceDecisionEngine: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q0-14",
    live: false,
    engine: {
      engineVersion: "PILLOW-XPL-001",
      missionId: "Q0-14",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalExperienceRecords: 0,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q0-14",
      status: "idle",
      healthStatus: "standby",
      totalExperienceRecords: 0,
      latestExperienceId: null,
      lastConfidenceScore: null,
      neverExecuteWork: true,
      neverReplaceExecutionMemory: true,
      neverReplaceDecisionEngine: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    latestRecord: null,
    lessons: [],
    repeatedMistakes: [],
    history: [],
    records: [],
  };
}
