/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectFinancialReportingWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    financialReportingRulesEnabled: true,
    executiveReportingEnabled: true,
    requireGrandKingApproval: true,
    requirePillowCommandConfirmation: true,
    neverExecuteFinancialTransactions: true,
    neverApproveFinancialDecisions: true,
    neverModifyAccountingRecords: true,
    neverFabricateFinancialFigures: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ910OrLater: true,
    preserveCompleteTraceability: true,
    preserveReportHistory: true,
    neverExposeCredentials: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
    measuredDataDistinctFromProjections: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q9-09",
    live: false,
    engine: {
      engineVersion: "PILLOW-FRW-001",
      missionId: "Q9-09",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        totalDashboards: 0,
        lastReportId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q9-09",
      status: "idle",
      healthStatus: "standby",
      totalReports: 0,
      totalDashboards: 0,
      latestCapitalBusinessId: null,
      neverExecuteFinancialTransactions: true,
      neverApproveFinancialDecisions: true,
      neverModifyAccountingRecords: true,
      neverFabricateFinancialFigures: true,
      neverBypassGrandKingApproval: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverImplementQ910OrLater: true,
      consumableByQ910: true,
    },
    catalog: null,
    dashboards: [],
    reports: [],
  };
}
