/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectFinancialReadinessAuditSnapshot() {
  const configuration = {
    enabled: true,
    discoveryEnabled: true,
    capabilityProbingEnabled: true,
    executiveReportingEnabled: true,
    neverFabricateFinancialEvidence: true,
    neverCertifyUnverifiedFinancialCapability: true,
    neverExecuteFinancialTransactions: true,
    neverModifyAccountingRecords: true,
    neverAssumeImplementation: true,
    neverRepairFailedFinancialComponents: true,
    neverBypassPillowGovernance: true,
    neverBypassGrandKingApproval: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ1109OrLater: true,
    preserveCompleteTraceability: true,
    preserveImmutableFinancialHistory: true,
    preserveAuditHistory: true,
    deterministicAuditBehaviour: true,
    structuralSignalOnly: true,
    evidenceBasedOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q11-08",
    live: false,
    engine: {
      engineVersion: "PILLOW-FINART-001",
      missionId: "Q11-08",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        lastReportId: null,
        lastDecision: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q11-08",
      status: "idle",
      healthStatus: "standby",
      totalReports: 0,
      latestReportId: null,
      lastDecision: null,
      lastConfidenceScore: null,
      workerId: "wkr-financial-readiness-audit-01",
      readinessClassificationOptions: [
        "certified",
        "partially_certified",
        "failed",
        "missing",
        "blocked",
        "deferred",
      ],
      neverFabricateFinancialEvidence: true,
      neverCertifyUnverifiedFinancialCapability: true,
      neverExecuteFinancialTransactions: true,
      neverModifyAccountingRecords: true,
      neverAssumeImplementation: true,
      neverRepairFailedFinancialComponents: true,
      neverBypassPillowGovernance: true,
      neverBypassGrandKingApproval: true,
      neverOverrideApprovedArchitecture: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverImplementQ1109OrLater: true,
      eighthQ11Gate: true,
    },
    catalog: null,
    reports: [],
    q1109Contract: null,
  };
}
