/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectForecastingWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    forecastingRulesEnabled: true,
    executiveReportingEnabled: true,
    requireGrandKingApproval: true,
    requirePillowCommandConfirmation: true,
    neverFabricateHistoricalFinancialData: true,
    neverPresentForecastsAsGuaranteedOutcomes: true,
    neverExecuteInvestments: true,
    neverApproveBudgets: true,
    neverReplaceInvestmentPlanningWorker: true,
    neverModifyAccountingRecords: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ907OrLater: true,
    preserveCompleteTraceability: true,
    preserveForecastHistory: true,
    neverExposeCredentials: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q9-06",
    live: false,
    engine: {
      engineVersion: "PILLOW-FRCW-001",
      missionId: "Q9-06",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalForecasts: 0,
        totalRunwayEstimates: 0,
        lastReportId: null,
        lastScenario: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q9-06",
      status: "idle",
      healthStatus: "standby",
      totalForecasts: 0,
      totalRunwayEstimates: 0,
      lastScenario: null,
      latestCapitalBusinessId: null,
      neverFabricateHistoricalFinancialData: true,
      neverPresentForecastsAsGuaranteedOutcomes: true,
      neverExecuteInvestments: true,
      neverApproveBudgets: true,
      neverReplaceInvestmentPlanningWorker: true,
      neverBypassGrandKingApproval: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverImplementQ907OrLater: true,
      consumableByQ907: true,
    },
    catalog: null,
    forecasts: [],
    runwayEstimates: [],
    reinvestmentOptions: [],
    scenarios: [],
    reports: [],
  };
}
