/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectHookWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    hookRulesEnabled: true,
    executiveReportingEnabled: true,
    neverRewriteCompleteScript: true,
    neverGenerateThumbnails: true,
    neverGenerateVideos: true,
    neverPublishContent: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ407OrLater: true,
    neverUseMisleadingOrDeceptiveHooks: true,
    preserveApprovedScriptIntent: true,
    generateOriginalHooks: true,
    preserveCompleteTraceability: true,
    performSelfReviewBeforeSubmission: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q4-06",
    live: false,
    engine: {
      engineVersion: "PILLOW-HKW-001",
      missionId: "Q4-06",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalHookReports: 0,
        lastHookReportId: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q4-06",
      status: "idle",
      healthStatus: "standby",
      totalHookReports: 0,
      latestHookReportId: null,
      neverRewriteCompleteScript: true,
      neverGenerateThumbnails: true,
      neverGenerateVideos: true,
      neverPublishContent: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverUseMisleadingOrDeceptiveHooks: true,
    },
    catalog: null,
    reports: [],
  };
}
