/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectImageCreativeWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    creativeRulesEnabled: true,
    executiveReportingEnabled: true,
    neverAssembleVideos: true,
    neverGenerateVoiceovers: true,
    neverPublishMedia: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ410OrLater: true,
    preserveCompleteAssetTraceability: true,
    respectCopyrightAndLicensing: true,
    preserveOriginalAssets: true,
    recordAllEditsPerformed: true,
    produceMultipleVariantsWhenAppropriate: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q4-09",
    live: false,
    engine: {
      engineVersion: "PILLOW-ICW-001",
      missionId: "Q4-09",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalCreativeAssetReports: 0,
        lastCreativeAssetId: null,
        lastQualityStatus: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q4-09",
      status: "idle",
      healthStatus: "standby",
      totalCreativeAssetReports: 0,
      latestCreativeAssetId: null,
      neverAssembleVideos: true,
      neverGenerateVoiceovers: true,
      neverPublishMedia: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    reports: [],
  };
}
