/** Safe offline snapshot; live operations are supplied by the Pillow host. */

export function collectImplementationSpecificationEngineSnapshot() {
  const configuration = {
    enabled: true,
    executiveReportingEnabled: true,
    neverFabricateRepositoryState: true,
    neverOverwriteVerifiedImplementations: true,
    neverExecuteImplementations: true,
    neverAutoDeploy: true,
    neverBypassGovernance: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ1302OrLater: true,
    preserveCompleteTraceability: true,
    preserveSpecificationHistory: true,
    preserveAuditHistory: true,
    deterministicSpecificationBehaviour: true,
    evidenceBasedOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q13-01",
    live: false,
    engine: {
      engineVersion: "PILLOW-ISENG-001",
      missionId: "Q13-01",
      status: "standby",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 0,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        totalSpecifications: 0,
        lastReportId: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot; specifications withheld"],
      },
    },
    cockpit: {
      missionId: "Q13-01",
      status: "standby",
      healthStatus: "standby",
      totalReports: 0,
      totalSpecifications: 0,
      latestReportId: null,
      workerId: "wkr-implementation-specification-engine-01",
      neverFabricateRepositoryState: true,
      neverExecuteImplementations: true,
      neverAutoDeploy: true,
      neverBypassGovernance: true,
      neverImplementQ1302OrLater: true,
    },
    catalog: null,
    reports: [],
    q1302Contract: null,
    specificationHistory: [],
  };
}
