/** Safe offline snapshot; live operations are supplied by the Pillow host. */

export function collectImplementationRecoveryPlannerSnapshot() {
  const configuration = {
    enabled: true,
    executiveReportingEnabled: true,
    neverExecuteRecovery: true,
    neverModifyRepository: true,
    neverFabricateRepositoryFindings: true,
    neverOverwriteVerifiedImplementations: true,
    neverDeleteProductionCodeWithoutEvidence: true,
    neverRestartCompletedWorkUnnecessarily: true,
    neverImplementQ1306OrLater: true,
    neverBypassGovernance: true,
    recoveryPlanningOnly: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q13-05",
    live: false,
    engine: {
      engineVersion: "PILLOW-IRPLN-001",
      missionId: "Q13-05",
      status: "standby",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      latestPlan: null,
      latestRecoverySpecification: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 0,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        totalPlans: 0,
        lastReportId: null,
        lastRecoveryId: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot; recovery planning withheld"],
      },
    },
    cockpit: {
      missionId: "Q13-05",
      status: "standby",
      healthStatus: "standby",
      totalReports: 0,
      totalPlans: 0,
      latestReportId: null,
      latestRecoveryId: null,
      workerId: "wkr-implementation-recovery-planner-01",
      neverExecuteRecovery: true,
      neverModifyRepository: true,
      neverImplementQ1306OrLater: true,
      neverOverwriteVerifiedImplementations: true,
      neverBypassGovernance: true,
    },
    catalog: null,
    reports: [],
    plans: [],
    q1306Contract: null,
    recoveryHistory: [],
  };
}
