/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectInterWorkerMessagingSnapshot() {
  const configuration = {
    enabled: true,
    routingRulesEnabled: true,
    deliveryTrackingEnabled: true,
    historyRulesEnabled: true,
    broadcastRulesEnabled: true,
    priorityRulesEnabled: true,
    neverExecuteWorkerLogic: true,
    neverModifyWorkerDecisions: true,
    neverReplaceWorkforceOrchestrator: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q0-24",
    live: false,
    engine: {
      engineVersion: "PILLOW-IWM-001",
      missionId: "Q0-24",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalMessageRecords: 0,
        deliveredCount: 0,
        failedCount: 0,
        conversationCount: 0,
        lastMessageType: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q0-24",
      status: "idle",
      healthStatus: "standby",
      totalMessageRecords: 0,
      latestMessageId: null,
      conversationCount: 0,
      neverExecuteWorkerLogic: true,
      neverModifyWorkerDecisions: true,
      neverReplaceWorkforceOrchestrator: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    latestRecord: null,
    records: [],
  };
}
