/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectInventoryWorkerSnapshot() {
  const configuration = {
    enabled: true,
    inventoryRulesEnabled: true,
    validationRulesEnabled: true,
    executiveReportingEnabled: true,
    defaultLeadTimeDays: 14,
    defaultDailyDemand: 5,
    defaultSafetyStockDays: 3,
    abnormalChangePercent: 0.5,
    abnormalAbsoluteDrop: 50,
    neverPurchaseInventory: true,
    neverModifySupplierStock: true,
    neverPlaceSupplierOrders: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ311OrLater: true,
    neverModifySupplierInventoryDirectly: true,
    preserveInventoryTraceability: true,
    preserveSupplierReferences: true,
    preserveInventoryHistory: true,
    generateAlertsForCriticalEvents: true,
    preserveAuditHistory: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q3-10",
    live: false,
    engine: {
      engineVersion: "PILLOW-INW-001",
      missionId: "Q3-10",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalInventoryReports: 0,
        lastInventoryReportId: null,
        lastStockStatus: null,
        lastReorderPoint: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q3-10",
      status: "idle",
      healthStatus: "standby",
      totalInventoryReports: 0,
      latestInventoryReportId: null,
      lastStockStatus: null,
      lastReorderPoint: null,
      lastConfidenceScore: null,
      neverPurchaseInventory: true,
      neverModifySupplierStock: true,
      neverPlaceSupplierOrders: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverModifySupplierInventoryDirectly: true,
    },
    catalog: null,
    inventoryReports: [],
  };
}
