/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectInvestmentPlanningWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    investmentPlanningRulesEnabled: true,
    executiveReportingEnabled: true,
    requireGrandKingApproval: true,
    requirePillowCommandConfirmation: true,
    neverExecuteInvestments: true,
    neverApproveInvestments: true,
    neverMoveOrAllocateCapital: true,
    neverModifyAccountingRecords: true,
    neverFabricateRoiOrPaybackOrRecommendations: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ909OrLater: true,
    preserveCompleteTraceability: true,
    preserveInvestmentHistory: true,
    neverExposeCredentials: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
    measuredDataDistinctFromProjections: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q9-08",
    live: false,
    engine: {
      engineVersion: "PILLOW-IPW-001",
      missionId: "Q9-08",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalOpportunities: 0,
        totalReports: 0,
        totalRecommendations: 0,
        lastReportId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q9-08",
      status: "idle",
      healthStatus: "standby",
      totalOpportunities: 0,
      totalReports: 0,
      totalRecommendations: 0,
      latestCapitalBusinessId: null,
      neverExecuteInvestments: true,
      neverApproveInvestments: true,
      neverMoveOrAllocateCapital: true,
      neverModifyAccountingRecords: true,
      neverFabricateRoiOrPaybackOrRecommendations: true,
      neverBypassGrandKingApproval: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverImplementQ909OrLater: true,
      consumableByQ909: true,
    },
    catalog: null,
    opportunities: [],
    rankings: [],
    recommendations: [],
    reports: [],
  };
}
