/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectKnowledgeSharingBusSnapshot() {
  const configuration = {
    enabled: true,
    submissionRulesEnabled: true,
    classificationRulesEnabled: true,
    publicationRulesEnabled: true,
    subscriptionRulesEnabled: true,
    versioningRulesEnabled: true,
    archivalRulesEnabled: true,
    neverExecuteWorkerTasks: true,
    neverReplaceExecutionMemory: true,
    neverReplaceDecisionMemory: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q0-23",
    live: false,
    engine: {
      engineVersion: "PILLOW-KSB-001",
      missionId: "Q0-23",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalKnowledgeRecords: 0,
        publishedCount: 0,
        archivedCount: 0,
        subscriptionCount: 0,
        lastCategory: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q0-23",
      status: "idle",
      healthStatus: "standby",
      totalKnowledgeRecords: 0,
      latestKnowledgeId: null,
      publishedCount: 0,
      neverExecuteWorkerTasks: true,
      neverReplaceExecutionMemory: true,
      neverReplaceDecisionMemory: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    latestRecord: null,
    records: [],
    subscriptions: [],
  };
}
