/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectLaunchPlanWorkerSnapshot() {
  const configuration = {
    enabled: true,
    planningRulesEnabled: true,
    validationRulesEnabled: true,
    executiveReportingEnabled: true,
    requireApprovedBlueprint: true,
    neverExecuteLaunchTasks: true,
    neverAssignWorkersDirectly: true,
    neverCreateBusinessAssets: true,
    neverConnectExternalAccounts: true,
    neverLaunchBusiness: true,
    neverApproveLaunch: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ208OrLater: true,
    preserveCompleteTraceability: true,
    preserveAuditHistory: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q2-07",
    live: false,
    engine: {
      engineVersion: "PILLOW-LPW-001",
      missionId: "Q2-07",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalLaunchPlans: 0,
        lastLaunchPlanId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q2-07",
      status: "idle",
      healthStatus: "standby",
      totalLaunchPlans: 0,
      latestLaunchPlanId: null,
      workerId: "wkr-launch-plan-01",
      neverExecuteLaunchTasks: true,
      neverAssignWorkersDirectly: true,
      neverCreateBusinessAssets: true,
      neverConnectExternalAccounts: true,
      neverLaunchBusiness: true,
      neverApproveLaunch: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    launchPlans: [],
    integrations: [],
  };
}
