/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectLeadGenerationWorkerSnapshot() {
  const configuration = {
    enabled: true,
    leadRulesEnabled: true,
    validationRulesEnabled: true,
    executiveReportingEnabled: true,
    neverExecuteAdvertisingCampaigns: true,
    neverReplaceCrm: true,
    neverReplaceBookingWorker: true,
    neverDeliverCustomerJobs: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverFabricateLeadOrConversionResults: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ709OrLater: true,
    preserveCompleteLeadTraceability: true,
    preserveFunnelAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeProhibitedPersonalData: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q7-08",
    live: false,
    engine: {
      engineVersion: "PILLOW-LGW-001",
      missionId: "Q7-08",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        totalFunnels: 0,
        totalLeads: 0,
        lastReportId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q7-08",
      status: "idle",
      healthStatus: "standby",
      totalReports: 0,
      totalFunnels: 0,
      totalLeads: 0,
      latestReportId: null,
      neverExecuteAdvertisingCampaigns: true,
      neverReplaceCrm: true,
      neverReplaceBookingWorker: true,
      neverDeliverCustomerJobs: true,
      neverFabricateLeadOrConversionResults: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverBypassGrandKingApproval: true,
      neverImplementQ709OrLater: true,
      consumableByQ709: true,
    },
    catalog: null,
    funnels: [],
    forms: [],
    leads: [],
    reports: [],
  };
}
