/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectLocalBusinessFactoryCoreSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    missionRulesEnabled: true,
    lifecycleRulesEnabled: true,
    executiveReportingEnabled: true,
    missionCoordinationEnabled: true,
    requireGrandKingApproval: true,
    requirePillowCommandConfirmation: true,
    neverPerformSpecialistWorkerFunctions: true,
    neverReplaceQ7Workers: true,
    neverModifyUnrelatedFactories: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverFabricateOperationalStatus: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ702OrLater: true,
    preserveCompleteTraceability: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q7-01",
    live: false,
    engine: {
      engineVersion: "PILLOW-LBFC-001",
      missionId: "Q7-01",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalProjects: 0,
        lastProjectId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q7-01",
      status: "idle",
      healthStatus: "standby",
      totalProjects: 0,
      latestProjectId: null,
      neverPerformSpecialistWorkerFunctions: true,
      neverReplaceQ7Workers: true,
      neverBypassGrandKingApproval: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverFabricateOperationalStatus: true,
      neverImplementQ702OrLater: true,
    },
    catalog: null,
    projects: [],
    reports: [],
  };
}
