/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectLocalSeoWorkerSnapshot() {
  const configuration = {
    enabled: true,
    seoRulesEnabled: true,
    validationRulesEnabled: true,
    executiveReportingEnabled: true,
    neverPublishWebsites: true,
    neverPurchaseBacklinks: true,
    neverManipulateSearchRankings: true,
    neverModifyLiveGoogleBusinessProfilesAutomatically: true,
    neverModifyUnrelatedPlatformComponents: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverFabricateSeoPerformanceResults: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ708OrLater: true,
    preserveCompleteTraceability: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q7-07",
    live: false,
    engine: {
      engineVersion: "PILLOW-LSEO-001",
      missionId: "Q7-07",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        totalSessions: 0,
        lastReportId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q7-07",
      status: "idle",
      healthStatus: "standby",
      totalReports: 0,
      totalSessions: 0,
      latestReportId: null,
      neverPublishWebsites: true,
      neverPurchaseBacklinks: true,
      neverManipulateSearchRankings: true,
      neverModifyLiveGoogleBusinessProfilesAutomatically: true,
      neverFabricateSeoPerformanceResults: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverBypassGrandKingApproval: true,
      neverImplementQ708OrLater: true,
      consumableByQ708: true,
    },
    catalog: null,
    sessions: [],
    reports: [],
    landingPages: [],
  };
}
