/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectLocalMarketResearchWorkerSnapshot() {
  const configuration = {
    enabled: true,
    researchRulesEnabled: true,
    validationRulesEnabled: true,
    executiveReportingEnabled: true,
    neverFinalizeServicePackages: true,
    neverSetFinalPrices: true,
    neverMakeLaunchDecisions: true,
    neverBuildBookingSystems: true,
    neverBuildWebsites: true,
    neverContactCustomersOrCompetitorsWithoutApproval: true,
    neverPurchaseDataOrAdvertisingWithoutApproval: true,
    neverFabricateDemandPricingOrCompetitorData: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ703OrLater: true,
    preserveCompleteTraceability: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeProhibitedPersonalData: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q7-02",
    live: false,
    engine: {
      engineVersion: "PILLOW-LMRW-001",
      missionId: "Q7-02",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        totalSessions: 0,
        lastResearchId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q7-02",
      status: "idle",
      healthStatus: "standby",
      totalReports: 0,
      totalSessions: 0,
      latestResearchId: null,
      neverFinalizeServicePackages: true,
      neverSetFinalPrices: true,
      neverMakeLaunchDecisions: true,
      neverFabricateDemandPricingOrCompetitorData: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverBypassGrandKingApproval: true,
      neverImplementQ703OrLater: true,
      consumableByQ703: true,
    },
    catalog: null,
    sessions: [],
    reports: [],
  };
}
