/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectLocalBusinessLaunchPackSnapshot() {
  const configuration = {
    enabled: true,
    assemblyRulesEnabled: true,
    validationRulesEnabled: true,
    executiveReportingEnabled: true,
    neverLaunchBusinessAutomatically: true,
    neverOverrideGovernance: true,
    neverReplaceCertification: true,
    neverClaimReadinessWithoutEvidence: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ711OrLater: true,
    preserveCompleteTraceability: true,
    preserveAuditHistory: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q7-10",
    live: false,
    engine: {
      engineVersion: "PILLOW-LBLP-001",
      missionId: "Q7-10",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalPackages: 0,
        totalReports: 0,
        lastPackageId: null,
        lastReportId: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q7-10",
      status: "idle",
      healthStatus: "standby",
      totalPackages: 0,
      totalReports: 0,
      latestReportId: null,
      lastConfidenceScore: null,
      workerId: "wkr-local-business-launch-pack-01",
      neverLaunchBusinessAutomatically: true,
      neverOverrideGovernance: true,
      neverReplaceCertification: true,
      neverClaimReadinessWithoutEvidence: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverBypassGrandKingApproval: true,
      neverImplementQ711OrLater: true,
      consumableByQ711: true,
    },
    catalog: null,
    packages: [],
    reports: [],
  };
}
