/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectMarketResearchWorkerSnapshot() {
  const configuration = {
    enabled: true,
    researchRulesEnabled: true,
    validationRulesEnabled: true,
    executiveReportingEnabled: true,
    neverDecideWhetherToBuild: true,
    neverGenerateBranding: true,
    neverBuildMarketingPlans: true,
    neverLaunchBusiness: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ205OrLater: true,
    requireEvidenceBasedFindings: true,
    preserveAuditHistory: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q2-04",
    live: false,
    engine: {
      engineVersion: "PILLOW-MRW-001",
      missionId: "Q2-04",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        lastReportId: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q2-04",
      status: "idle",
      healthStatus: "standby",
      totalReports: 0,
      latestReportId: null,
      lastConfidenceScore: null,
      workerId: "wkr-market-research-01",
      neverDecideWhetherToBuild: true,
      neverGenerateBranding: true,
      neverBuildMarketingPlans: true,
      neverLaunchBusiness: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    reports: [],
    integrations: [],
  };
}
