/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectMediaLearningWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    learningRulesEnabled: true,
    executiveReportingEnabled: true,
    neverRewriteExistingContent: true,
    neverModifyPublishedVideos: true,
    neverChangeEditorialPolicyDirectly: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ417OrLater: true,
    neverOverwriteHistoricalLearning: true,
    learnOnlyFromVerifiedAnalytics: true,
    preserveCompleteTraceability: true,
    preserveHistoricalLearningRecords: true,
    distinguishMeasuredOutcomesFromAssumptions: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q4-16",
    live: false,
    engine: {
      engineVersion: "PILLOW-MLW-001",
      missionId: "Q4-16",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalLearningReports: 0,
        lastLearningReportId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q4-16",
      status: "idle",
      healthStatus: "standby",
      totalLearningReports: 0,
      latestLearningReportId: null,
      neverRewriteExistingContent: true,
      neverModifyPublishedVideos: true,
      neverOverwriteHistoricalLearning: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverImplementQ417OrLater: true,
    },
    catalog: null,
    reports: [],
  };
}
