/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectMediaExecutiveReviewWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    reviewRulesEnabled: true,
    executiveReportingEnabled: true,
    neverPublishMedia: true,
    neverRewriteScripts: true,
    neverEditMediaAssets: true,
    neverModifyApprovedAssets: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ419OrLater: true,
    neverBypassPillowGovernance: true,
    verifyAllPrerequisiteWorkersCompletedSuccessfully: true,
    preserveCompleteTraceability: true,
    distinguishVerifiedFindingsFromRecommendations: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q4-18",
    live: false,
    engine: {
      engineVersion: "PILLOW-MER-001",
      missionId: "Q4-18",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReviewReports: 0,
        lastReviewId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q4-18",
      status: "idle",
      healthStatus: "standby",
      totalReviewReports: 0,
      latestReviewId: null,
      neverPublishMedia: true,
      neverModifyApprovedAssets: true,
      neverBypassPillowGovernance: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverImplementQ419OrLater: true,
    },
    catalog: null,
    reports: [],
  };
}
