/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectMediaAnalyticsWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    analyticsRulesEnabled: true,
    executiveReportingEnabled: true,
    neverRewriteContent: true,
    neverChangePublishingSchedules: true,
    neverModifyChannelStrategy: true,
    neverExecuteOptimizations: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ416OrLater: true,
    neverAlterSourceAnalyticsData: true,
    preserveCompleteMetricTraceability: true,
    preserveHistoricalPerformanceRecords: true,
    distinguishPlatformReportedFromEstimates: true,
    detectMeaningfulPerformanceChanges: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q4-15",
    live: false,
    engine: {
      engineVersion: "PILLOW-MAW-001",
      missionId: "Q4-15",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalAnalyticsReports: 0,
        lastAnalyticsReportId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q4-15",
      status: "idle",
      healthStatus: "standby",
      totalAnalyticsReports: 0,
      latestAnalyticsReportId: null,
      neverRewriteContent: true,
      neverExecuteOptimizations: true,
      neverAlterSourceAnalyticsData: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverImplementQ416OrLater: true,
    },
    catalog: null,
    reports: [],
  };
}
