/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectMediaFactoryCoreSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    missionRulesEnabled: true,
    lifecycleRulesEnabled: true,
    executiveReportingEnabled: true,
    missionCoordinationEnabled: true,
    requireGrandKingApproval: true,
    requirePillowCommandConfirmation: true,
    neverWriteScripts: true,
    neverGenerateImages: true,
    neverGenerateVideos: true,
    neverPublishDirectly: true,
    neverBypassApproval: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ402OrLater: true,
    preserveCompleteTraceability: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q4-01",
    live: false,
    engine: {
      engineVersion: "PILLOW-MFC-001",
      missionId: "Q4-01",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalMissions: 0,
        lastMissionId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q4-01",
      status: "idle",
      healthStatus: "standby",
      totalMissions: 0,
      latestMissionId: null,
      neverWriteScripts: true,
      neverGenerateImages: true,
      neverGenerateVideos: true,
      neverPublishDirectly: true,
      neverBypassApproval: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    missions: [],
    reports: [],
  };
}
