/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectMemoryRuntimeSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    memoryRulesEnabled: true,
    executiveReportingEnabled: true,
    neverReplaceEkls: true,
    neverReplaceApplicationDatabases: true,
    neverModifyHistoricalRecords: true,
    neverFabricateMemory: true,
    neverSilentlyOverwriteHistoricalDecisions: true,
    neverBypassPillowGovernance: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ1006OrLater: true,
    preserveCompleteTraceability: true,
    preserveHistoricalMemory: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
    deterministicRetrievalOnly: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q10-05",
    live: false,
    engine: {
      engineVersion: "PILLOW-MEMRT-001",
      missionId: "Q10-05",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalEntries: 0,
        totalVersions: 0,
        lastReportId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q10-05",
      status: "idle",
      healthStatus: "standby",
      totalEntries: 0,
      totalVersions: 0,
      latestReportId: null,
      lastConfidenceScore: null,
      workerId: "wkr-memory-runtime-01",
      neverReplaceEkls: true,
      neverReplaceApplicationDatabases: true,
      neverModifyHistoricalRecords: true,
      neverFabricateMemory: true,
      neverSilentlyOverwriteHistoricalDecisions: true,
      neverBypassPillowGovernance: true,
      neverBypassGrandKingApproval: true,
      neverImplementQ1006OrLater: true,
      structuralSignalOnly: true,
    },
    history: null,
    reports: [],
    q1006Contract: null,
  };
}
