/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectMissionCoordinationEngineSnapshot() {
  const configuration = {
    enabled: true,
    planningRulesEnabled: true,
    phaseRulesEnabled: true,
    dependencyRulesEnabled: true,
    approvalRulesEnabled: true,
    stallDetectionEnabled: true,
    blockageDetectionEnabled: true,
    closureRulesEnabled: true,
    neverExecuteWorkerLogic: true,
    neverReplaceWorkforceOrchestrator: true,
    neverReplaceExecutivePlanner: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q0-25",
    live: false,
    engine: {
      engineVersion: "PILLOW-MCE-001",
      missionId: "Q0-25",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalMissionRecords: 0,
        activeMissions: 0,
        blockedMissions: 0,
        completedMissions: 0,
        lastPhase: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q0-25",
      status: "idle",
      healthStatus: "standby",
      totalMissionRecords: 0,
      latestMissionId: null,
      activeMissions: 0,
      neverExecuteWorkerLogic: true,
      neverReplaceWorkforceOrchestrator: true,
      neverReplaceExecutivePlanner: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    latestRecord: null,
    records: [],
  };
}
