/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectMissionRuntimeSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    lifecycleRulesEnabled: true,
    executiveReportingEnabled: true,
    neverReplaceWorkerLogic: true,
    neverReplaceOrchestrationLogic: true,
    neverExecuteUnauthorisedMissions: true,
    neverFabricateMissionState: true,
    neverBypassPillowGovernance: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ1004OrLater: true,
    preserveCompleteTraceability: true,
    preserveMissionHistory: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
    deterministicTransitionsOnly: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q10-03",
    live: false,
    engine: {
      engineVersion: "PILLOW-MSR-001",
      missionId: "Q10-03",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalMissions: 0,
        lastReportId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q10-03",
      status: "idle",
      healthStatus: "standby",
      totalMissions: 0,
      latestReportId: null,
      lastConfidenceScore: null,
      workerId: "wkr-mission-runtime-01",
      neverReplaceWorkerLogic: true,
      neverReplaceOrchestrationLogic: true,
      neverExecuteUnauthorisedMissions: true,
      neverFabricateMissionState: true,
      neverBypassPillowGovernance: true,
      neverBypassGrandKingApproval: true,
      neverImplementQ1004OrLater: true,
      structuralSignalOnly: true,
    },
    history: null,
    reports: [],
    q1004Contract: null,
  };
}
