/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectMonitoringRuntimeSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    monitoringRulesEnabled: true,
    executiveReportingEnabled: true,
    neverFabricateHealthInformation: true,
    neverSuppressCriticalAlerts: true,
    neverReplaceRecoverySystems: true,
    neverAutomaticallyRepairFailures: true,
    neverBypassPillowGovernance: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ1011OrLater: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverExecuteBusinessLogic: true,
    preserveCompleteTraceability: true,
    preserveMonitoringHistory: true,
    preserveAuditHistory: true,
    deterministicHealthCalculations: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q10-10",
    live: false,
    engine: {
      engineVersion: "PILLOW-MONRT-001",
      missionId: "Q10-10",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalComponents: 0,
        totalAlerts: 0,
        lastReportId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q10-10",
      status: "idle",
      healthStatus: "standby",
      totalComponents: 0,
      totalAlerts: 0,
      latestReportId: null,
      lastConfidenceScore: null,
      workerId: "wkr-monitoring-runtime-01",
      neverFabricateHealthInformation: true,
      neverSuppressCriticalAlerts: true,
      neverReplaceRecoverySystems: true,
      neverAutomaticallyRepairFailures: true,
      neverBypassPillowGovernance: true,
      neverBypassGrandKingApproval: true,
      neverImplementQ1011OrLater: true,
      structuralSignalOnly: true,
    },
    history: null,
    reports: [],
    dashboard: null,
    q1011Contract: null,
  };
}
