/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectMusicSoundWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    audioRulesEnabled: true,
    executiveReportingEnabled: true,
    neverAssembleVideos: true,
    neverPublishMedia: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ414OrLater: true,
    neverUseUnapprovedCopyrightedAssets: true,
    preserveCompleteAssetTraceability: true,
    preserveLicensingInformation: true,
    preserveTimelineSynchronization: true,
    validateCopyrightCompliance: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q4-13",
    live: false,
    engine: {
      engineVersion: "PILLOW-MSW-001",
      missionId: "Q4-13",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalAudioReports: 0,
        lastAudioReportId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q4-13",
      status: "idle",
      healthStatus: "standby",
      totalAudioReports: 0,
      latestAudioReportId: null,
      neverAssembleVideos: true,
      neverPublishMedia: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverUseUnapprovedCopyrightedAssets: true,
    },
    catalog: null,
    reports: [],
  };
}
