/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectOperationsWorkerSnapshot() {
  const configuration = {
    enabled: true,
    operationsRulesEnabled: true,
    validationRulesEnabled: true,
    executiveReportingEnabled: true,
    neverFabricateOperationalEvidence: true,
    neverPerformCustomerServices: true,
    neverReplaceBookingWorker: true,
    neverReplaceCrmWorker: true,
    neverReplaceLeadGenerationWorker: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ710OrLater: true,
    preserveCompleteOperationalTraceability: true,
    preserveWorkflowAuditHistory: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q7-09",
    live: false,
    engine: {
      engineVersion: "PILLOW-OPSW-001",
      missionId: "Q7-09",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        totalWorkflows: 0,
        lastReportId: null,
        lastWorkflowId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q7-09",
      status: "idle",
      healthStatus: "standby",
      totalReports: 0,
      totalWorkflows: 0,
      latestReportId: null,
      neverFabricateOperationalEvidence: true,
      neverPerformCustomerServices: true,
      neverReplaceBookingWorker: true,
      neverReplaceCrmWorker: true,
      neverReplaceLeadGenerationWorker: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverBypassGrandKingApproval: true,
      neverImplementQ710OrLater: true,
      consumableByQ710: true,
    },
    catalog: null,
    workflows: [],
    reports: [],
  };
}
