/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectOperationalPlaybookEngineSnapshot() {
  const configuration = {
    enabled: true,
    playbookRulesEnabled: true,
    neverExecuteWorkerTasks: true,
    neverReplaceWorkers: true,
    neverReplaceWorkforceOrchestrator: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q0-15",
    live: false,
    engine: {
      engineVersion: "PILLOW-OPBK-001",
      missionId: "Q0-15",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalPlaybooks: 0,
        totalExecutionRecords: 0,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q0-15",
      status: "idle",
      healthStatus: "standby",
      totalPlaybooks: 0,
      totalExecutionRecords: 0,
      latestExecutionId: null,
      lastConfidenceScore: null,
      neverExecuteWorkerTasks: true,
      neverReplaceWorkers: true,
      neverReplaceWorkforceOrchestrator: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    latestExecution: null,
    playbooks: [],
    executions: [],
  };
}
