/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectOrderWorkerSnapshot() {
  const configuration = {
    enabled: true,
    orderRulesEnabled: true,
    validationRulesEnabled: true,
    executiveReportingEnabled: true,
    defaultDelayDaysThreshold: 7,
    defaultExpectedShipDays: 5,
    neverProcessPayments: true,
    neverIssueRefunds: true,
    neverModifyInventoryDirectly: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ312OrLater: true,
    neverAlterFinancialRecords: true,
    preserveOrderTraceability: true,
    preserveFulfilmentHistory: true,
    preserveSupplierReferences: true,
    detectOperationalExceptions: true,
    preserveAuditHistory: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q3-11",
    live: false,
    engine: {
      engineVersion: "PILLOW-ORW-001",
      missionId: "Q3-11",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalOrderReports: 0,
        lastOrderReportId: null,
        lastOrderStatus: null,
        lastFulfilmentStatus: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q3-11",
      status: "idle",
      healthStatus: "standby",
      totalOrderReports: 0,
      latestOrderReportId: null,
      lastOrderStatus: null,
      lastFulfilmentStatus: null,
      lastConfidenceScore: null,
      neverProcessPayments: true,
      neverIssueRefunds: true,
      neverModifyInventoryDirectly: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverAlterFinancialRecords: true,
    },
    catalog: null,
    orderReports: [],
  };
}
