/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectOrganizationCharterSnapshot() {
  const configuration = {
    enabled: true,
    definitionRulesEnabled: true,
    registrationRulesEnabled: true,
    reportingRulesEnabled: true,
    escalationRulesEnabled: true,
    validationRulesEnabled: true,
    neverExecuteWorkerTasks: true,
    neverReplaceWorkforceOperatingSystem: true,
    neverReplaceWorkforceOrchestrator: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q1-02",
    live: false,
    engine: {
      engineVersion: "PILLOW-OCH-001",
      missionId: "Q1-02",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        charterVersion: "OCH-CHARTER-v1",
        totalStructureRecords: 0,
        factoryCount: 0,
        departmentCount: 0,
        workerCount: 0,
        lastStructureDecision: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q1-02",
      status: "idle",
      healthStatus: "standby",
      charterVersion: "OCH-CHARTER-v1",
      factoryCount: 0,
      departmentCount: 0,
      workerCount: 0,
      latestStructureRecordId: null,
      neverExecuteWorkerTasks: true,
      neverReplaceWorkforceOperatingSystem: true,
      neverReplaceWorkforceOrchestrator: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    charter: null,
    latestRecord: null,
    records: [],
  };
}
