/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectPeerReviewRuntimeSnapshot() {
  const configuration = {
    enabled: true,
    reviewRulesEnabled: true,
    selectionRulesEnabled: true,
    comparisonRulesEnabled: true,
    escalationRulesEnabled: true,
    neverReplaceWorkers: true,
    neverRewriteCompletedWork: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverExecuteBusinessTasks: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q0-21",
    live: false,
    engine: {
      engineVersion: "PILLOW-PRR-001",
      missionId: "Q0-21",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReviewRecords: 0,
        lastOutcome: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q0-21",
      status: "idle",
      healthStatus: "standby",
      totalReviewRecords: 0,
      latestReviewId: null,
      lastOutcome: null,
      neverReplaceWorkers: true,
      neverRewriteCompletedWork: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverExecuteBusinessTasks: true,
    },
    latestRecord: null,
    records: [],
  };
}
