/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectPerformanceAuditSnapshot() {
  const configuration = {
    enabled: true,
    discoveryEnabled: true,
    benchmarkProbingEnabled: true,
    executiveReportingEnabled: true,
    neverFabricatePerformanceEvidence: true,
    neverCertifyUntestedPerformance: true,
    neverOptimizeOrModifyProductionSystems: true,
    neverAssumeImplementation: true,
    neverModifyPerformanceImplementations: true,
    neverRepairFailedPerformanceComponents: true,
    neverBypassPillowGovernance: true,
    neverBypassGrandKingApproval: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ1107OrLater: true,
    preserveCompleteTraceability: true,
    preserveImmutableBenchmarkHistory: true,
    preserveAuditHistory: true,
    deterministicAuditBehaviour: true,
    structuralSignalOnly: true,
    evidenceBasedOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q11-06",
    live: false,
    engine: {
      engineVersion: "PILLOW-PERFART-001",
      missionId: "Q11-06",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        lastReportId: null,
        lastDecision: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q11-06",
      status: "idle",
      healthStatus: "standby",
      totalReports: 0,
      latestReportId: null,
      lastDecision: null,
      lastConfidenceScore: null,
      workerId: "wkr-performance-audit-01",
      readinessClassificationOptions: [
        "certified",
        "partially_certified",
        "failed",
        "missing",
        "blocked",
        "deferred",
      ],
      neverFabricatePerformanceEvidence: true,
      neverCertifyUntestedPerformance: true,
      neverOptimizeOrModifyProductionSystems: true,
      neverAssumeImplementation: true,
      neverModifyPerformanceImplementations: true,
      neverRepairFailedPerformanceComponents: true,
      neverBypassPillowGovernance: true,
      neverBypassGrandKingApproval: true,
      neverOverrideApprovedArchitecture: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverImplementQ1107OrLater: true,
      sixthQ11Gate: true,
    },
    catalog: null,
    reports: [],
    q1107Contract: null,
  };
}
