/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectPillowOrchestrationRuntimeSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    orchestrationRulesEnabled: true,
    executiveReportingEnabled: true,
    neverReplaceWorkerImplementations: true,
    neverReplaceToolImplementations: true,
    neverExecuteUnauthorisedActions: true,
    neverFabricateExecutionResults: true,
    neverBypassApprovalRuntime: true,
    neverBypassPillowGovernance: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ1003OrLater: true,
    preserveCompleteTraceability: true,
    preserveOrchestrationHistory: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q10-02",
    live: false,
    engine: {
      engineVersion: "PILLOW-POR-001",
      missionId: "Q10-02",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalSessions: 0,
        totalInvocations: 0,
        lastReportId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q10-02",
      status: "idle",
      healthStatus: "standby",
      totalSessions: 0,
      totalInvocations: 0,
      latestReportId: null,
      lastConfidenceScore: null,
      workerId: "wkr-pillow-orchestration-runtime-01",
      neverReplaceWorkerImplementations: true,
      neverReplaceToolImplementations: true,
      neverExecuteUnauthorisedActions: true,
      neverFabricateExecutionResults: true,
      neverBypassApprovalRuntime: true,
      neverBypassPillowGovernance: true,
      neverBypassGrandKingApproval: true,
      neverImplementQ1003OrLater: true,
      structuralSignalOnly: true,
    },
    history: null,
    reports: [],
    q1003Contract: null,
  };
}
