/** Safe offline snapshot; live operations are supplied by the Pillow host. */

export function collectPostLaunchMonitoringSnapshot() {
  const configuration = {
    enabled: true,
    executiveReportingEnabled: true,
    neverFabricateProductionEvidence: true,
    neverSuppressCriticalIncidents: true,
    neverHideFailures: true,
    neverAutoModifyProduction: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ1112OrLater: true,
    preserveCompleteTraceability: true,
    preserveMonitoringHistory: true,
    preserveAuditHistory: true,
    deterministicMonitoringBehaviour: true,
    structuralSignalOnly: true,
    evidenceBasedOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q11-11",
    live: false,
    engine: {
      engineVersion: "PILLOW-PLMRT-001",
      missionId: "Q11-11",
      status: "standby",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      grandKingAcceptanceGranted: false,
      productionActiveMonitoring: false,
      health: {
        status: "standby",
        healthScore: 0,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        lastReportId: null,
        lastProductionActiveMonitoring: false,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot; production-active monitoring blocked"],
      },
    },
    cockpit: {
      missionId: "Q11-11",
      status: "standby",
      healthStatus: "standby",
      totalReports: 0,
      latestReportId: null,
      grandKingAcceptanceGranted: false,
      productionActiveMonitoring: false,
      workerId: "wkr-post-launch-monitoring-01",
      neverFabricateProductionEvidence: true,
      neverSuppressCriticalIncidents: true,
      neverHideFailures: true,
      neverAutoModifyProduction: true,
      neverImplementQ1112OrLater: true,
    },
    catalog: null,
    reports: [],
    q1112Contract: null,
    monitoringHistory: [],
  };
}
