/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectPricingWorkerSnapshot() {
  const configuration = {
    enabled: true,
    pricingRulesEnabled: true,
    validationRulesEnabled: true,
    executiveReportingEnabled: true,
    defaultTargetMarginPercent: 35,
    defaultMarketplaceFeePercent: 15,
    defaultPaymentFeePercent: 2.9,
    defaultAdvertisingPercent: 10,
    defaultShippingCost: 4.5,
    currency: "USD",
    neverPublishListings: true,
    neverModifySupplierCosts: true,
    neverExecutePromotions: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ310OrLater: true,
    neverPublishPricingAutomatically: true,
    preservePricingTraceability: true,
    separateActualFromEstimatedCosts: true,
    explainPricingRationale: true,
    preserveAuditHistory: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q3-09",
    live: false,
    engine: {
      engineVersion: "PILLOW-PRW-001",
      missionId: "Q3-09",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalPricingReports: 0,
        lastPricingId: null,
        lastRecommendedPrice: null,
        lastTargetMargin: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q3-09",
      status: "idle",
      healthStatus: "standby",
      totalPricingReports: 0,
      latestPricingId: null,
      lastRecommendedPrice: null,
      lastTargetMargin: null,
      lastConfidenceScore: null,
      neverPublishListings: true,
      neverModifySupplierCosts: true,
      neverExecutePromotions: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverPublishPricingAutomatically: true,
    },
    catalog: null,
    pricingReports: [],
  };
}
