/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectProductionCertificationCoreSnapshot() {
  const configuration = {
    enabled: true,
    evidenceScanEnabled: true,
    runtimeProbingEnabled: true,
    executiveReportingEnabled: true,
    neverFabricateCertificationEvidence: true,
    neverCertifyMissingCapabilities: true,
    neverAssumeImplementation: true,
    neverImplementMissingCapabilities: true,
    neverModifyProductionLogic: true,
    neverReplaceIndividualAuditProgrammes: true,
    neverBypassPillowGovernance: true,
    neverBypassGrandKingApproval: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ1102OrLater: true,
    preserveCompleteTraceability: true,
    preserveImmutableCertificationHistory: true,
    preserveCertificationHistory: true,
    preserveAuditHistory: true,
    deterministicCertification: true,
    structuralSignalOnly: true,
    evidenceBasedOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q11-01",
    live: false,
    engine: {
      engineVersion: "PILLOW-PCCRT-001",
      missionId: "Q11-01",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        lastReportId: null,
        lastCertificationDecision: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q11-01",
      status: "idle",
      healthStatus: "standby",
      totalReports: 0,
      latestReportId: null,
      lastCertificationDecision: null,
      lastConfidenceScore: null,
      workerId: "wkr-production-certification-core-01",
      certificationStatusOptions: [
        "Certified",
        "Partially Certified",
        "Failed Certification",
        "Blocked",
        "Deferred",
        "Registered",
        "Discovered",
        "Pending",
      ],
      neverFabricateCertificationEvidence: true,
      neverCertifyMissingCapabilities: true,
      neverAssumeImplementation: true,
      neverImplementMissingCapabilities: true,
      neverModifyProductionLogic: true,
      neverReplaceIndividualAuditProgrammes: true,
      neverBypassPillowGovernance: true,
      neverBypassGrandKingApproval: true,
      neverOverrideApprovedArchitecture: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverImplementQ1102OrLater: true,
      firstQ11Gate: true,
    },
    catalog: null,
    reports: [],
    q1102Contract: null,
  };
}
