/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectProductListingWorkerSnapshot() {
  const configuration = {
    enabled: true,
    listingRulesEnabled: true,
    validationRulesEnabled: true,
    executiveReportingEnabled: true,
    maxTitleLength: 200,
    maxBulletPoints: 5,
    neverPublishListings: true,
    neverModifySupplierInformation: true,
    neverModifyPricing: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ309OrLater: true,
    preserveProductTraceability: true,
    preserveSupplierReferences: true,
    validateRequiredMarketplaceFields: true,
    preserveAuditHistory: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q3-08",
    live: false,
    engine: {
      engineVersion: "PILLOW-PLW-001",
      missionId: "Q3-08",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalListings: 0,
        lastListingId: null,
        lastListingValidationStatus: null,
        lastMarketplace: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q3-08",
      status: "idle",
      healthStatus: "standby",
      totalListings: 0,
      latestListingId: null,
      lastListingValidationStatus: null,
      lastMarketplace: null,
      lastConfidenceScore: null,
      neverPublishListings: true,
      neverModifySupplierInformation: true,
      neverModifyPricing: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    listings: [],
  };
}
