/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectProductImageWorkerSnapshot() {
  const configuration = {
    enabled: true,
    imageRulesEnabled: true,
    validationRulesEnabled: true,
    executiveReportingEnabled: true,
    minWidthPx: 1000,
    minHeightPx: 1000,
    neverPublishListings: true,
    neverGenerateAdvertisements: true,
    neverContactSuppliers: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ308OrLater: true,
    neverOverwriteOriginalSourceAssets: true,
    preserveOriginalSupplierAssets: true,
    maintainSupplierTraceability: true,
    validateMarketplaceCompliance: true,
    preserveAuditHistory: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q3-07",
    live: false,
    engine: {
      engineVersion: "PILLOW-PIW-001",
      missionId: "Q3-07",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalImageReports: 0,
        lastImageReportId: null,
        lastImageQualityStatus: null,
        lastComplianceStatus: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q3-07",
      status: "idle",
      healthStatus: "standby",
      totalImageReports: 0,
      latestImageReportId: null,
      lastImageQualityStatus: null,
      lastComplianceStatus: null,
      lastConfidenceScore: null,
      neverPublishListings: true,
      neverGenerateAdvertisements: true,
      neverContactSuppliers: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverOverwriteOriginalSourceAssets: true,
    },
    catalog: null,
    imageReports: [],
  };
}
