/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectProductDiscoveryWorkerSnapshot() {
  const configuration = {
    enabled: true,
    discoveryRulesEnabled: true,
    validationRulesEnabled: true,
    executiveReportingEnabled: true,
    neverEvaluateProducts: true,
    neverRankProducts: true,
    neverSelectSuppliers: true,
    neverBuildListings: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ303OrLater: true,
    useOnlyApprovedDiscoverySources: true,
    preserveSourceTraceability: true,
    preserveAuditHistory: true,
    distinguishFactsFromAssumptions: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q3-02",
    live: false,
    engine: {
      engineVersion: "PILLOW-PDW-001",
      missionId: "Q3-02",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalDiscoveries: 0,
        lastDiscoveryId: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q3-02",
      status: "idle",
      healthStatus: "standby",
      totalDiscoveries: 0,
      latestDiscoveryId: null,
      lastConfidenceScore: null,
      neverEvaluateProducts: true,
      neverRankProducts: true,
      neverSelectSuppliers: true,
      neverBuildListings: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    discoveries: [],
  };
}
