/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectProfitabilityWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    profitabilityRulesEnabled: true,
    executiveReportingEnabled: true,
    requireGrandKingApproval: true,
    requirePillowCommandConfirmation: true,
    neverFabricateRevenueCostFeeRefundOrProfitabilityFigures: true,
    neverForecastFutureProfitability: true,
    neverApproveSpending: true,
    neverExecuteFinancialTransactions: true,
    neverReplaceForecastingWorker: true,
    neverModifyAccountingRecords: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ906OrLater: true,
    preserveCompleteTraceability: true,
    preserveHistoricalProfitabilityReports: true,
    neverExposeCredentials: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q9-05",
    live: false,
    engine: {
      engineVersion: "PILLOW-PRFW-001",
      missionId: "Q9-05",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalAnalyses: 0,
        totalRankings: 0,
        lastReportId: null,
        lastScope: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q9-05",
      status: "idle",
      healthStatus: "standby",
      totalAnalyses: 0,
      totalRankings: 0,
      lastScope: null,
      latestCapitalBusinessId: null,
      neverFabricateRevenueCostFeeRefundOrProfitabilityFigures: true,
      neverForecastFutureProfitability: true,
      neverApproveSpending: true,
      neverExecuteFinancialTransactions: true,
      neverReplaceForecastingWorker: true,
      neverBypassGrandKingApproval: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverImplementQ906OrLater: true,
      consumableByQ906: true,
    },
    catalog: null,
    analyses: [],
    rankings: [],
    reports: [],
  };
}
