/** Safe offline snapshot; live operations are supplied by the Pillow host. */

export function collectProgrammeCertificationFactorySnapshot() {
  const configuration = {
    enabled: true,
    executiveReportingEnabled: true,
    neverFabricateFindings: true,
    neverAutoModifyProduction: true,
    neverCertifyFromClaimsAlone: true,
    neverImplementFutureProgramme: true,
    neverImplementQ1307OrLater: true,
    neverBypassGovernance: true,
    programmeCertificationOnly: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q13-06",
    live: false,
    engine: {
      engineVersion: "PILLOW-PCFCT-001",
      missionId: "Q13-06",
      status: "standby",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      latestFinalCertification: null,
      discoveredProgrammes: [],
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 0,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        totalCertifications: 0,
        lastReportId: null,
        lastCertificationId: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot; programme certification withheld"],
      },
    },
    cockpit: {
      missionId: "Q13-06",
      status: "standby",
      healthStatus: "standby",
      totalReports: 0,
      totalCertifications: 0,
      latestReportId: null,
      latestCertificationId: null,
      workerId: "wkr-programme-certification-factory-01",
      programmesDiscovered: 0,
      programmesCertified: 0,
      neverFabricateFindings: true,
      neverAutoModifyProduction: true,
      neverCertifyFromClaimsAlone: true,
      neverImplementFutureProgramme: true,
      neverImplementQ1307OrLater: true,
      neverBypassGovernance: true,
      finalQSeriesMission: true,
    },
    catalog: null,
    reports: [],
    certifications: [],
    qSeriesCompletionContract: null,
    certificationHistory: [],
  };
}
