/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectPromptProductWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    promptRulesEnabled: true,
    executiveReportingEnabled: true,
    requireConsistencyValidation: true,
    neverBuildSalesPages: true,
    neverProcessCustomerPayments: true,
    neverDeliverProducts: true,
    neverPublishProductsDirectly: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ505OrLater: true,
    followApprovedProductResearch: true,
    produceOriginalPromptProducts: true,
    preserveCompleteTraceability: true,
    validatePromptQuality: true,
    includeUserDocumentation: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q5-04",
    live: false,
    engine: {
      engineVersion: "PILLOW-PPW-001",
      missionId: "Q5-04",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalPromptProducts: 0,
        lastPromptProductId: null,
        lastProductType: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q5-04",
      status: "idle",
      healthStatus: "standby",
      totalPromptProducts: 0,
      latestPromptProductId: null,
      neverBuildSalesPages: true,
      neverProcessCustomerPayments: true,
      neverDeliverProducts: true,
      neverPublishProductsDirectly: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    promptProducts: [],
  };
}
