/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectPublishingWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    publishingRulesEnabled: true,
    executiveReportingEnabled: true,
    neverAutomaticallyPublishContent: true,
    neverModifyApprovedMediaAssets: true,
    neverOverrideApprovalWorkflows: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ415OrLater: true,
    preserveCompleteAssetTraceability: true,
    preservePublishingMetadataHistory: true,
    validatePlatformRequirements: true,
    validateApprovalStatusBeforePublication: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q4-14",
    live: false,
    engine: {
      engineVersion: "PILLOW-PBW-001",
      missionId: "Q4-14",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalPublishingReports: 0,
        lastPublishingReportId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q4-14",
      status: "idle",
      healthStatus: "standby",
      totalPublishingReports: 0,
      latestPublishingReportId: null,
      neverAutomaticallyPublishContent: true,
      neverModifyApprovedMediaAssets: true,
      neverOverrideApprovalWorkflows: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverImplementQ415OrLater: true,
    },
    catalog: null,
    reports: [],
  };
}
