/** Safe offline snapshot; live operations are supplied by the Pillow host. */

export function collectQSeriesCertificationSnapshot() {
  const configuration = {
    enabled: true,
    executiveReportingEnabled: true,
    neverFabricateCertificationEvidence: true,
    neverCertifyMissingFunctionality: true,
    neverBypassGovernance: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ1113OrLater: true,
    preserveCompleteTraceability: true,
    preserveCertificationHistory: true,
    preserveAuditHistory: true,
    deterministicCertificationBehaviour: true,
    structuralSignalOnly: true,
    evidenceBasedOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q11-12",
    live: false,
    engine: {
      engineVersion: "PILLOW-QSCRT-001",
      missionId: "Q11-12",
      status: "standby",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 0,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        lastReportId: null,
        lastCertificationDecision: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot; certification withheld"],
      },
    },
    cockpit: {
      missionId: "Q11-12",
      status: "standby",
      healthStatus: "standby",
      totalReports: 0,
      latestReportId: null,
      lastCertificationDecision: null,
      workerId: "wkr-q-series-certification-01",
      neverFabricateCertificationEvidence: true,
      neverCertifyMissingFunctionality: true,
      neverBypassGovernance: true,
      neverImplementQ1113OrLater: true,
    },
    catalog: null,
    reports: [],
    q1113Contract: null,
    certificationHistory: [],
  };
}
