/** Safe offline snapshot; live operations are supplied by the Pillow host. */

export function collectQSeriesCompletionSnapshot() {
  const configuration = {
    enabled: true,
    executiveReportingEnabled: true,
    neverFabricateCompletionEvidence: true,
    neverMarkCompleteWhenUnmet: true,
    neverBypassGovernance: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ1201OrLater: true,
    preserveCompleteTraceability: true,
    preserveCompletionHistory: true,
    preserveAuditHistory: true,
    deterministicCompletionBehaviour: true,
    structuralSignalOnly: true,
    evidenceBasedOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q11-13",
    live: false,
    engine: {
      engineVersion: "PILLOW-QSCPT-001",
      missionId: "Q11-13",
      status: "standby",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 0,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        lastReportId: null,
        lastCompletionDecision: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot; completion withheld"],
      },
    },
    cockpit: {
      missionId: "Q11-13",
      status: "standby",
      healthStatus: "standby",
      totalReports: 0,
      latestReportId: null,
      lastCompletionDecision: null,
      workerId: "wkr-q-series-completion-01",
      neverFabricateCompletionEvidence: true,
      neverMarkCompleteWhenUnmet: true,
      neverBypassGovernance: true,
      neverImplementQ1201OrLater: true,
    },
    catalog: null,
    reports: [],
    q1201Contract: null,
    completionHistory: [],
  };
}
