/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectQueueRuntimeSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    queueRulesEnabled: true,
    executiveReportingEnabled: true,
    neverReplaceWorkerLogic: true,
    neverReplaceMissionLogic: true,
    neverExecuteBusinessSpecificWork: true,
    neverFabricateQueueState: true,
    neverBypassPillowGovernance: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ1005OrLater: true,
    preserveCompleteTraceability: true,
    preserveExecutionHistory: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
    deterministicQueueOrdering: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q10-04",
    live: false,
    engine: {
      engineVersion: "PILLOW-QRT-001",
      missionId: "Q10-04",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalQueues: 0,
        totalJobs: 0,
        lastReportId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q10-04",
      status: "idle",
      healthStatus: "standby",
      totalQueues: 0,
      totalJobs: 0,
      latestReportId: null,
      lastConfidenceScore: null,
      workerId: "wkr-queue-runtime-01",
      neverReplaceWorkerLogic: true,
      neverReplaceMissionLogic: true,
      neverExecuteBusinessSpecificWork: true,
      neverFabricateQueueState: true,
      neverBypassPillowGovernance: true,
      neverBypassGrandKingApproval: true,
      neverImplementQ1005OrLater: true,
      structuralSignalOnly: true,
    },
    history: null,
    reports: [],
    q1005Contract: null,
  };
}
