/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectRecoveryRuntimeSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    recoveryRulesEnabled: true,
    executiveReportingEnabled: true,
    neverFabricateRecoverySuccess: true,
    neverLoseRecoverableExecutionState: true,
    neverBypassPillowGovernance: true,
    neverBypassGrandKingApproval: true,
    neverModifyValidatedBusinessData: true,
    neverReplaceBusinessLogic: true,
    neverImplementQ1012OrLater: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    preserveCompleteTraceability: true,
    preserveRecoveryHistory: true,
    preserveAuditHistory: true,
    deterministicRecoveryBehaviour: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q10-11",
    live: false,
    engine: {
      engineVersion: "PILLOW-RECRT-001",
      missionId: "Q10-11",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalFailures: 0,
        totalRecoveries: 0,
        lastReportId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q10-11",
      status: "idle",
      healthStatus: "standby",
      totalFailures: 0,
      totalRecoveries: 0,
      activeRecoveries: 0,
      completedRecoveries: 0,
      failedRecoveries: 0,
      latestReportId: null,
      lastConfidenceScore: null,
      workerId: "wkr-recovery-runtime-01",
      neverFabricateRecoverySuccess: true,
      neverLoseRecoverableExecutionState: true,
      neverBypassPillowGovernance: true,
      neverBypassGrandKingApproval: true,
      neverModifyValidatedBusinessData: true,
      neverReplaceBusinessLogic: true,
      neverImplementQ1012OrLater: true,
      structuralSignalOnly: true,
    },
    history: null,
    reports: [],
    q1012Contract: null,
  };
}
