/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectRecoveryAuditSnapshot() {
  const configuration = {
    enabled: true,
    discoveryEnabled: true,
    capabilityProbingEnabled: true,
    executiveReportingEnabled: true,
    neverFabricateRecoveryEvidence: true,
    neverCertifyUntestedRecovery: true,
    neverMutateProductionViaRecoveryCalls: true,
    neverAssumeImplementation: true,
    neverModifyRecoveryImplementations: true,
    neverRepairFailedRecoveryComponents: true,
    neverBypassPillowGovernance: true,
    neverBypassGrandKingApproval: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ1108OrLater: true,
    preserveCompleteTraceability: true,
    preserveImmutableRecoveryHistory: true,
    preserveAuditHistory: true,
    deterministicAuditBehaviour: true,
    structuralSignalOnly: true,
    evidenceBasedOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q11-07",
    live: false,
    engine: {
      engineVersion: "PILLOW-RECART-001",
      missionId: "Q11-07",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        lastReportId: null,
        lastDecision: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q11-07",
      status: "idle",
      healthStatus: "standby",
      totalReports: 0,
      latestReportId: null,
      lastDecision: null,
      lastConfidenceScore: null,
      workerId: "wkr-recovery-audit-01",
      readinessClassificationOptions: [
        "certified",
        "partially_certified",
        "failed",
        "missing",
        "blocked",
        "deferred",
      ],
      neverFabricateRecoveryEvidence: true,
      neverCertifyUntestedRecovery: true,
      neverMutateProductionViaRecoveryCalls: true,
      neverAssumeImplementation: true,
      neverModifyRecoveryImplementations: true,
      neverRepairFailedRecoveryComponents: true,
      neverBypassPillowGovernance: true,
      neverBypassGrandKingApproval: true,
      neverOverrideApprovedArchitecture: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverImplementQ1108OrLater: true,
      seventhQ11Gate: true,
    },
    catalog: null,
    reports: [],
    q1108Contract: null,
  };
}
