/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectRefundDisputeWorkerSnapshot() {
  const configuration = {
    enabled: true,
    caseRulesEnabled: true,
    validationRulesEnabled: true,
    executiveReportingEnabled: true,
    maxDelegatedRefundAmount: 100,
    defaultReturnWindowDays: 30,
    neverModifyFinancialLedgersDirectly: true,
    neverOverrideMarketplacePolicies: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ313OrLater: true,
    neverAuthorizeOutsideAuthorityMatrix: true,
    followApprovedPolicies: true,
    preserveCaseTraceability: true,
    preserveSupplierReferences: true,
    preserveCustomerCommunicationHistory: true,
    preserveAuditHistory: true,
    escalateBeyondDelegatedAuthority: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q3-12",
    live: false,
    engine: {
      engineVersion: "PILLOW-RDW-001",
      missionId: "Q3-12",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalCases: 0,
        lastCaseId: null,
        lastCaseType: null,
        lastCaseStatus: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q3-12",
      status: "idle",
      healthStatus: "standby",
      totalCases: 0,
      latestCaseId: null,
      lastCaseType: null,
      lastCaseStatus: null,
      lastConfidenceScore: null,
      neverModifyFinancialLedgersDirectly: true,
      neverOverrideMarketplacePolicies: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverAuthorizeOutsideAuthorityMatrix: true,
    },
    catalog: null,
    cases: [],
  };
}
