/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectRequirementsWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    requirementsRulesEnabled: true,
    executiveReportingEnabled: true,
    requireQualityReview: true,
    neverDesignArchitecture: true,
    neverWriteApplicationCode: true,
    neverDeploySoftware: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverInventUnsupportedBusinessRequirements: true,
    neverImplementQ603OrLater: true,
    followApprovedBusinessIntent: true,
    preserveCompleteTraceability: true,
    distinguishRequirementsFromAssumptions: true,
    validateCompletenessBeforeSubmission: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q6-02",
    live: false,
    engine: {
      engineVersion: "PILLOW-RQW-001",
      missionId: "Q6-02",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalRequirementsReports: 0,
        lastRequirementsId: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q6-02",
      status: "idle",
      healthStatus: "standby",
      totalRequirementsReports: 0,
      latestRequirementsId: null,
      neverDesignArchitecture: true,
      neverWriteApplicationCode: true,
      neverDeploySoftware: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverInventUnsupportedBusinessRequirements: true,
      neverImplementQ603OrLater: true,
    },
    catalog: null,
    requirementsReports: [],
  };
}
