/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectResponsibilityMatrixSnapshot() {
  const configuration = {
    enabled: true,
    definitionRulesEnabled: true,
    registrationRulesEnabled: true,
    derivationRulesEnabled: true,
    ownershipRulesEnabled: true,
    inputsOutputsRulesEnabled: true,
    dependencyRulesEnabled: true,
    approvalRulesEnabled: true,
    validationRulesEnabled: true,
    neverExecuteWorkerTasks: true,
    neverReplaceAuthorityMatrix: true,
    neverReplaceOrganizationCharter: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q1-06",
    live: false,
    engine: {
      engineVersion: "PILLOW-RMX-001",
      missionId: "Q1-06",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        matrixVersion: "RMX-MATRIX-v1",
        totalResponsibilities: 0,
        totalBindings: 0,
        ownerCount: 0,
        lastMatrixDecision: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q1-06",
      status: "idle",
      healthStatus: "standby",
      matrixVersion: "RMX-MATRIX-v1",
      totalResponsibilities: 0,
      ownerCount: 0,
      latestBindingId: null,
      neverExecuteWorkerTasks: true,
      neverReplaceAuthorityMatrix: true,
      neverReplaceOrganizationCharter: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    responsibilities: [],
    latestBinding: null,
    bindings: [],
  };
}
