/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectReviewContentWorkerSnapshot() {
  const configuration = {
    enabled: true,
    reviewRulesEnabled: true,
    validationRulesEnabled: true,
    executiveReportingEnabled: true,
    neverFabricateReviewsRatingsOrProductInformation: true,
    neverPublishWebsites: true,
    neverManipulateRatings: true,
    neverReplaceComparisonSiteWorker: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ805OrLater: true,
    preserveCompleteTraceability: true,
    preserveAuditHistory: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q8-04",
    live: false,
    engine: {
      engineVersion: "PILLOW-RCW-001",
      missionId: "Q8-04",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        totalReviews: 0,
        lastReportId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q8-04",
      status: "idle",
      healthStatus: "standby",
      totalReports: 0,
      totalReviews: 0,
      latestReportId: null,
      neverFabricateReviewsRatingsOrProductInformation: true,
      neverPublishWebsites: true,
      neverManipulateRatings: true,
      neverReplaceComparisonSiteWorker: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverBypassGrandKingApproval: true,
      neverImplementQ805OrLater: true,
      consumableByQ805: true,
    },
    catalog: null,
    reports: [],
  };
}
