/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectRoleTaxonomySnapshot() {
  const configuration = {
    enabled: true,
    definitionRulesEnabled: true,
    registrationRulesEnabled: true,
    inheritanceRulesEnabled: true,
    reportingRulesEnabled: true,
    validationRulesEnabled: true,
    neverExecuteWorkerTasks: true,
    neverReplaceOrganizationCharter: true,
    neverReplaceWorkerConstitution: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q1-03",
    live: false,
    engine: {
      engineVersion: "PILLOW-RTX-001",
      missionId: "Q1-03",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        taxonomyVersion: "RTX-TAX-v1",
        totalRoles: 0,
        totalInheritanceRecords: 0,
        categoryCount: 0,
        lastTaxonomyDecision: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q1-03",
      status: "idle",
      healthStatus: "standby",
      taxonomyVersion: "RTX-TAX-v1",
      totalRoles: 0,
      categoryCount: 0,
      latestInheritanceId: null,
      neverExecuteWorkerTasks: true,
      neverReplaceOrganizationCharter: true,
      neverReplaceWorkerConstitution: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    roles: [],
    latestRecord: null,
    records: [],
  };
}
