/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectSalesPageWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    salesPageRulesEnabled: true,
    executiveReportingEnabled: true,
    requireQualityReview: true,
    neverProcessPayments: true,
    neverDeliverProducts: true,
    neverPublishWebsites: true,
    neverPublishPagesDirectly: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ509OrLater: true,
    neverFabricateTestimonials: true,
    followApprovedProductInformation: true,
    produceOriginalSalesCopy: true,
    preserveCompleteTraceability: true,
    maintainEmpireAiBrandingStandards: true,
    performQualityReviewBeforeSubmission: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q5-08",
    live: false,
    engine: {
      engineVersion: "PILLOW-SPW-001",
      missionId: "Q5-08",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalSalesPages: 0,
        lastSalesPageId: null,
        lastPageType: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q5-08",
      status: "idle",
      healthStatus: "standby",
      totalSalesPages: 0,
      latestSalesPageId: null,
      neverProcessPayments: true,
      neverDeliverProducts: true,
      neverPublishWebsites: true,
      neverPublishPagesDirectly: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverFabricateTestimonials: true,
    },
    catalog: null,
    salesPages: [],
  };
}
