/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectSchedulingRuntimeSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    schedulingRulesEnabled: true,
    executiveReportingEnabled: true,
    neverFabricateExecutionTimes: true,
    neverBypassPillowGovernance: true,
    neverBypassGrandKingApproval: true,
    neverReplaceQueueRuntime: true,
    neverReplaceMissionRuntime: true,
    neverExecuteUnauthorizedWork: true,
    neverImplementQ1013OrLater: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    preserveCompleteTraceability: true,
    preserveSchedulingHistory: true,
    preserveAuditHistory: true,
    deterministicSchedulingBehaviour: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q10-12",
    live: false,
    engine: {
      engineVersion: "PILLOW-SCHRT-001",
      missionId: "Q10-12",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalSchedules: 0,
        totalExecutions: 0,
        lastReportId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q10-12",
      status: "idle",
      healthStatus: "standby",
      totalSchedules: 0,
      totalExecutions: 0,
      activeSchedules: 0,
      latestReportId: null,
      lastConfidenceScore: null,
      workerId: "wkr-scheduling-runtime-01",
      neverFabricateExecutionTimes: true,
      neverBypassPillowGovernance: true,
      neverBypassGrandKingApproval: true,
      neverReplaceQueueRuntime: true,
      neverReplaceMissionRuntime: true,
      neverImplementQ1013OrLater: true,
      structuralSignalOnly: true,
    },
    history: null,
    reports: [],
    q1013Contract: null,
  };
}
