/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectScriptWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    scriptRulesEnabled: true,
    executiveReportingEnabled: true,
    requireSelfReview: true,
    neverGenerateVisuals: true,
    neverGenerateVoiceovers: true,
    neverAssembleVideos: true,
    neverPublishContent: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ406OrLater: true,
    followApprovedTopicPlan: true,
    followEditorInChiefStrategy: true,
    produceOriginalContent: true,
    preserveScriptTraceability: true,
    performSelfReviewBeforeSubmission: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q4-05",
    live: false,
    engine: {
      engineVersion: "PILLOW-SCW-001",
      missionId: "Q4-05",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalScripts: 0,
        lastScriptId: null,
        lastContentFormat: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q4-05",
      status: "idle",
      healthStatus: "standby",
      totalScripts: 0,
      latestScriptId: null,
      neverGenerateVisuals: true,
      neverGenerateVoiceovers: true,
      neverAssembleVideos: true,
      neverPublishContent: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    scripts: [],
  };
}
