/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectSecurityAuditSnapshot() {
  const configuration = {
    enabled: true,
    discoveryEnabled: true,
    secretProbingEnabled: true,
    executiveReportingEnabled: true,
    neverFabricateSecurityEvidence: true,
    neverCertifyInsecureImplementations: true,
    neverExposeSecretsDuringAuditing: true,
    neverAssumeImplementation: true,
    neverModifySecurityImplementations: true,
    neverRepairFailedSecurityComponents: true,
    neverBypassPillowGovernance: true,
    neverBypassGrandKingApproval: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ1106OrLater: true,
    preserveCompleteTraceability: true,
    preserveImmutableAuditHistory: true,
    preserveAuditHistory: true,
    deterministicAuditBehaviour: true,
    structuralSignalOnly: true,
    evidenceBasedOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q11-05",
    live: false,
    engine: {
      engineVersion: "PILLOW-SECART-001",
      missionId: "Q11-05",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        lastReportId: null,
        lastDecision: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q11-05",
      status: "idle",
      healthStatus: "standby",
      totalReports: 0,
      latestReportId: null,
      lastDecision: null,
      lastConfidenceScore: null,
      workerId: "wkr-security-audit-01",
      readinessClassificationOptions: [
        "certified",
        "partially_certified",
        "failed",
        "missing",
        "blocked",
        "deferred",
      ],
      neverFabricateSecurityEvidence: true,
      neverCertifyInsecureImplementations: true,
      neverExposeSecretsDuringAuditing: true,
      neverAssumeImplementation: true,
      neverModifySecurityImplementations: true,
      neverRepairFailedSecurityComponents: true,
      neverBypassPillowGovernance: true,
      neverBypassGrandKingApproval: true,
      neverOverrideApprovedArchitecture: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverImplementQ1106OrLater: true,
      fifthQ11Gate: true,
    },
    catalog: null,
    reports: [],
    q1106Contract: null,
  };
}
