/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectSeoContentWorkerSnapshot() {
  const configuration = {
    enabled: true,
    seoRulesEnabled: true,
    validationRulesEnabled: true,
    executiveReportingEnabled: true,
    neverFabricateSeoPerformanceClaims: true,
    neverPublishArticles: true,
    neverManipulateSearchRankings: true,
    neverReplaceAnalyticsWorker: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ806OrLater: true,
    preserveCompleteTraceability: true,
    preserveAuditHistory: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q8-05",
    live: false,
    engine: {
      engineVersion: "PILLOW-SEOW-001",
      missionId: "Q8-05",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        totalArticles: 0,
        lastReportId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q8-05",
      status: "idle",
      healthStatus: "standby",
      totalReports: 0,
      totalArticles: 0,
      latestReportId: null,
      neverFabricateSeoPerformanceClaims: true,
      neverPublishArticles: true,
      neverManipulateSearchRankings: true,
      neverReplaceAnalyticsWorker: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverBypassGrandKingApproval: true,
      neverImplementQ806OrLater: true,
      consumableByQ806: true,
    },
    catalog: null,
    reports: [],
  };
}
