/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectServiceOfferWorkerSnapshot() {
  const configuration = {
    enabled: true,
    offerRulesEnabled: true,
    validationRulesEnabled: true,
    executiveReportingEnabled: true,
    neverBuildBookingSystems: true,
    neverBuildCrm: true,
    neverExecuteCustomerJobs: true,
    neverLaunchBusiness: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverFabricatePricingEvidence: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ704OrLater: true,
    preserveCompleteTraceability: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q7-03",
    live: false,
    engine: {
      engineVersion: "PILLOW-SOW-001",
      missionId: "Q7-03",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        totalSessions: 0,
        lastReportId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q7-03",
      status: "idle",
      healthStatus: "standby",
      totalReports: 0,
      totalSessions: 0,
      latestReportId: null,
      neverBuildBookingSystems: true,
      neverBuildCrm: true,
      neverExecuteCustomerJobs: true,
      neverLaunchBusiness: true,
      neverFabricatePricingEvidence: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverBypassGrandKingApproval: true,
      neverImplementQ704OrLater: true,
      consumableByQ704: true,
    },
    catalog: null,
    sessions: [],
    reports: [],
  };
}
