/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectSharedRuntimeCertificationSnapshot() {
  const configuration = {
    enabled: true,
    evidenceScanEnabled: true,
    runtimeProbingEnabled: true,
    executiveReportingEnabled: true,
    neverFabricateCertificationEvidence: true,
    neverCertifyMissingFunctionality: true,
    neverAssumeImplementation: true,
    neverImplementMissingRuntimes: true,
    neverModifyRuntimeBehaviour: true,
    neverBypassPillowGovernance: true,
    neverBypassGrandKingApproval: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ1101OrLater: true,
    preserveCompleteTraceability: true,
    preserveImmutableCertificationHistory: true,
    preserveCertificationHistory: true,
    preserveAuditHistory: true,
    deterministicCertification: true,
    structuralSignalOnly: true,
    evidenceBasedOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q10-14",
    live: false,
    engine: {
      engineVersion: "PILLOW-SRCRT-001",
      missionId: "Q10-14",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        lastReportId: null,
        lastCertificationDecision: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q10-14",
      status: "idle",
      healthStatus: "standby",
      totalReports: 0,
      latestReportId: null,
      lastCertificationDecision: null,
      lastConfidenceScore: null,
      workerId: "wkr-shared-runtime-certification-01",
      runtimeCertificationStatusOptions: [
        "Certified",
        "Partially Certified",
        "Failed Certification",
        "Blocked",
        "Deferred",
      ],
      neverFabricateCertificationEvidence: true,
      neverCertifyMissingFunctionality: true,
      neverAssumeImplementation: true,
      neverImplementMissingRuntimes: true,
      neverModifyRuntimeBehaviour: true,
      neverBypassPillowGovernance: true,
      neverBypassGrandKingApproval: true,
      neverOverrideApprovedArchitecture: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverImplementQ1101OrLater: true,
      finalQ10Gate: true,
    },
    catalog: null,
    reports: [],
    q1101Contract: null,
  };
}
