/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectSharedRuntimeCoreSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    registryRulesEnabled: true,
    routingRulesEnabled: true,
    executiveReportingEnabled: true,
    neverReplaceFactoryLogic: true,
    neverReplaceWorkerLogic: true,
    neverExecuteBusinessSpecificDecisions: true,
    neverFabricateRuntimeState: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ1002OrLater: true,
    preserveCompleteTraceability: true,
    preserveRuntimeHistory: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q10-01",
    live: false,
    engine: {
      engineVersion: "PILLOW-SRTC-001",
      missionId: "Q10-01",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalFactories: 0,
        totalWorkers: 0,
        lastReportId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q10-01",
      status: "idle",
      healthStatus: "standby",
      totalFactories: 0,
      totalWorkers: 0,
      totalServices: 0,
      latestReportId: null,
      lastConfidenceScore: null,
      workerId: "wkr-shared-runtime-core-01",
      neverReplaceFactoryLogic: true,
      neverReplaceWorkerLogic: true,
      neverExecuteBusinessSpecificDecisions: true,
      neverFabricateRuntimeState: true,
      neverOverrideApprovedArchitecture: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverBypassGrandKingApproval: true,
      neverImplementQ1002OrLater: true,
      structuralSignalOnly: true,
    },
    catalog: null,
    reports: [],
    topology: null,
    q1002Contract: null,
  };
}
