/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectSkillTaxonomySnapshot() {
  const configuration = {
    enabled: true,
    definitionRulesEnabled: true,
    registrationRulesEnabled: true,
    derivationRulesEnabled: true,
    hierarchyRulesEnabled: true,
    proficiencyRulesEnabled: true,
    validationRulesEnabled: true,
    neverExecuteWorkerTasks: true,
    neverReplaceRoleTaxonomy: true,
    neverReplaceWorkforceCapabilityRegistry: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q1-04",
    live: false,
    engine: {
      engineVersion: "PILLOW-STX-001",
      missionId: "Q1-04",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        taxonomyVersion: "STX-TAX-v1",
        totalSkills: 0,
        totalDerivationRecords: 0,
        categoryCount: 0,
        proficiencyLevelCount: 0,
        lastTaxonomyDecision: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q1-04",
      status: "idle",
      healthStatus: "standby",
      taxonomyVersion: "STX-TAX-v1",
      totalSkills: 0,
      categoryCount: 0,
      proficiencyLevelCount: 0,
      latestDerivationId: null,
      neverExecuteWorkerTasks: true,
      neverReplaceRoleTaxonomy: true,
      neverReplaceWorkforceCapabilityRegistry: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    skills: [],
    latestRecord: null,
    records: [],
  };
}
