/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectStrategicRecommendationEngineSnapshot() {
  const configuration = {
    enabled: true,
    analysisRulesEnabled: true,
    generationRulesEnabled: true,
    rankingRulesEnabled: true,
    neverExecuteRecommendations: true,
    neverAssignWorkers: true,
    neverApproveActions: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q0-07",
    live: false,
    engine: {
      engineVersion: "PILLOW-REC-001",
      missionId: "Q0-07",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalRecommendations: 0,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q0-07",
      status: "idle",
      healthStatus: "standby",
      totalRecommendations: 0,
      latestRecommendationId: null,
      lastAnalysisId: null,
      neverExecuteRecommendations: true,
      neverAssignWorkers: true,
      neverApproveActions: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    latestAnalysis: null,
    recommendations: [],
  };
}
