/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectSubtitleWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    subtitleRulesEnabled: true,
    executiveReportingEnabled: true,
    neverRewriteScripts: true,
    neverAssembleVideos: true,
    neverPublishContent: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ413OrLater: true,
    neverModifyApprovedScripts: true,
    preserveScriptTraceability: true,
    preserveSubtitleSynchronization: true,
    preserveTranscriptHistory: true,
    validateSubtitleQuality: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q4-12",
    live: false,
    engine: {
      engineVersion: "PILLOW-STW-001",
      missionId: "Q4-12",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastReminderAt: null,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalSubtitleReports: 0,
        lastSubtitleReportId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q4-12",
      status: "idle",
      healthStatus: "standby",
      totalSubtitleReports: 0,
      latestSubtitleReportId: null,
      neverRewriteScripts: true,
      neverAssembleVideos: true,
      neverPublishContent: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    reports: [],
  };
}
