/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectSupplierNegotiationWorkerSnapshot() {
  const configuration = {
    enabled: true,
    negotiationRulesEnabled: true,
    validationRulesEnabled: true,
    executiveReportingEnabled: true,
    preferThreshold: 70,
    reviewThreshold: 45,
    neverContactSuppliers: true,
    neverCommitAgreements: true,
    neverPlaceOrders: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ307OrLater: true,
    preserveSupplierTraceability: true,
    baseOnEvaluationResults: true,
    produceProfessionalCommunication: true,
    preserveAuditHistory: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q3-06",
    live: false,
    engine: {
      engineVersion: "PILLOW-SNW-001",
      missionId: "Q3-06",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalNegotiations: 0,
        lastNegotiationId: null,
        lastPreferredSupplierId: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q3-06",
      status: "idle",
      healthStatus: "standby",
      totalNegotiations: 0,
      latestNegotiationId: null,
      lastPreferredSupplierId: null,
      lastConfidenceScore: null,
      neverContactSuppliers: true,
      neverCommitAgreements: true,
      neverPlaceOrders: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    negotiations: [],
  };
}
