/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectSupplierDiscoveryWorkerSnapshot() {
  const configuration = {
    enabled: true,
    discoveryRulesEnabled: true,
    validationRulesEnabled: true,
    executiveReportingEnabled: true,
    neverEvaluateSuppliers: true,
    neverNegotiateSuppliers: true,
    neverSelectSuppliers: true,
    neverPlaceOrders: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ305OrLater: true,
    useOnlyApprovedSupplierPlatformsAndApis: true,
    neverModifySupplierData: true,
    preserveSupplierTraceability: true,
    preserveAuditHistory: true,
    distinguishUnavailableFromMissing: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q3-04",
    live: false,
    engine: {
      engineVersion: "PILLOW-SDW-001",
      missionId: "Q3-04",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalDiscoveries: 0,
        lastDiscoveryId: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q3-04",
      status: "idle",
      healthStatus: "standby",
      totalDiscoveries: 0,
      latestDiscoveryId: null,
      lastConfidenceScore: null,
      neverEvaluateSuppliers: true,
      neverNegotiateSuppliers: true,
      neverSelectSuppliers: true,
      neverPlaceOrders: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    discoveries: [],
  };
}
