/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectTaskNegotiationProtocolSnapshot() {
  const configuration = {
    enabled: true,
    negotiationRulesEnabled: true,
    conflictRulesEnabled: true,
    escalationRulesEnabled: true,
    neverExecuteWorkerTasks: true,
    neverReplaceWorkforceOrchestrator: true,
    neverReplacePillow: true,
    neverOverrideGrandKing: true,
    neverPerformStrategicPlanning: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q0-20",
    live: false,
    engine: {
      engineVersion: "PILLOW-TNP-001",
      missionId: "Q0-20",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalNegotiationRecords: 0,
        lastOutcome: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q0-20",
      status: "idle",
      healthStatus: "standby",
      totalNegotiationRecords: 0,
      latestNegotiationId: null,
      lastOutcome: null,
      neverExecuteWorkerTasks: true,
      neverReplaceWorkforceOrchestrator: true,
      neverReplacePillow: true,
      neverOverrideGrandKing: true,
      neverPerformStrategicPlanning: true,
    },
    latestRecord: null,
    records: [],
  };
}
