/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectTaxSupportWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    taxSupportRulesEnabled: true,
    executiveReportingEnabled: true,
    requireGrandKingApproval: true,
    requirePillowCommandConfirmation: true,
    neverProvideLegalOrTaxAdvice: true,
    neverFabricateTaxCalculationsOrObligations: true,
    neverSubmitFilingsAutomatically: true,
    neverReplaceAccountantsOrTaxProfessionals: true,
    neverModifyAccountingRecords: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ908OrLater: true,
    preserveCompleteTraceability: true,
    preserveTaxSupportHistory: true,
    neverExposeCredentials: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
    factualRecordsDistinctFromReminders: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q9-07",
    live: false,
    engine: {
      engineVersion: "PILLOW-TSW-001",
      missionId: "Q9-07",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalRecords: 0,
        totalReminders: 0,
        totalMissingDocs: 0,
        lastReportId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q9-07",
      status: "idle",
      healthStatus: "standby",
      totalRecords: 0,
      totalReminders: 0,
      totalMissingDocs: 0,
      latestCapitalBusinessId: null,
      neverProvideLegalOrTaxAdvice: true,
      neverFabricateTaxCalculationsOrObligations: true,
      neverSubmitFilingsAutomatically: true,
      neverReplaceAccountantsOrTaxProfessionals: true,
      neverBypassGrandKingApproval: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverImplementQ908OrLater: true,
      consumableByQ908: true,
    },
    catalog: null,
    records: [],
    reminders: [],
    missingDocumentation: [],
    professionalReviewFlags: [],
    reports: [],
  };
}
