/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectTemplateBuilderWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    templateRulesEnabled: true,
    executiveReportingEnabled: true,
    requireUsabilityValidation: true,
    neverBuildSalesPages: true,
    neverProcessPayments: true,
    neverDeliverProductsToCustomers: true,
    neverPublishProductsDirectly: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ507OrLater: true,
    followApprovedProductResearch: true,
    followApprovedProductIntent: true,
    produceOriginalReusableAssets: true,
    preserveCompleteTraceability: true,
    validateUsabilityBeforeSubmission: true,
    performSelfReview: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q5-06",
    live: false,
    engine: {
      engineVersion: "PILLOW-TBW-001",
      missionId: "Q5-06",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalTemplateProducts: 0,
        lastTemplateProductId: null,
        lastProductType: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q5-06",
      status: "idle",
      healthStatus: "standby",
      totalTemplateProducts: 0,
      latestTemplateProductId: null,
      neverBuildSalesPages: true,
      neverProcessPayments: true,
      neverDeliverProductsToCustomers: true,
      neverPublishProductsDirectly: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    templateProducts: [],
  };
}
