/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectThumbnailWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    thumbnailRulesEnabled: true,
    executiveReportingEnabled: true,
    neverGenerateFinalArtwork: true,
    neverEditImagesDirectly: true,
    neverPublishThumbnails: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ408OrLater: true,
    neverUseMisleadingOrDeceptiveThumbnails: true,
    followEditorInChiefStrategy: true,
    remainConsistentWithApprovedScript: true,
    produceMultipleDesignAlternatives: true,
    preserveCompleteTraceability: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q4-07",
    live: false,
    engine: {
      engineVersion: "PILLOW-THW-001",
      missionId: "Q4-07",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalThumbnailReports: 0,
        lastThumbnailReportId: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q4-07",
      status: "idle",
      healthStatus: "standby",
      totalThumbnailReports: 0,
      latestThumbnailReportId: null,
      neverGenerateFinalArtwork: true,
      neverEditImagesDirectly: true,
      neverPublishThumbnails: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverUseMisleadingOrDeceptiveThumbnails: true,
    },
    catalog: null,
    reports: [],
  };
}
