/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectToolRuntimeSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    toolRulesEnabled: true,
    executiveReportingEnabled: true,
    neverExposeSecrets: true,
    neverExposeCredentials: true,
    neverFabricateExecutionResults: true,
    neverInvokeUnauthorizedTools: true,
    neverBypassPillowGovernance: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ1008OrLater: true,
    preserveCompleteTraceability: true,
    preserveInvocationHistory: true,
    preserveAuditHistory: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
    deterministicToolRoutingOnly: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q10-07",
    live: false,
    engine: {
      engineVersion: "PILLOW-TOOLRT-001",
      missionId: "Q10-07",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalTools: 0,
        totalInvocations: 0,
        lastReportId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q10-07",
      status: "idle",
      healthStatus: "standby",
      totalTools: 0,
      totalInvocations: 0,
      latestReportId: null,
      lastConfidenceScore: null,
      workerId: "wkr-tool-runtime-01",
      neverExposeSecrets: true,
      neverExposeCredentials: true,
      neverFabricateExecutionResults: true,
      neverInvokeUnauthorizedTools: true,
      neverBypassPillowGovernance: true,
      neverBypassGrandKingApproval: true,
      neverImplementQ1008OrLater: true,
      structuralSignalOnly: true,
    },
    history: null,
    reports: [],
    q1008Contract: null,
  };
}
