/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectTopicPlannerWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    planningRulesEnabled: true,
    executiveReportingEnabled: true,
    requirePillowGovernance: true,
    neverWriteScripts: true,
    neverGenerateVisuals: true,
    neverProduceVideos: true,
    neverPublishContent: true,
    neverBypassPillowGovernance: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ405OrLater: true,
    neverRequireGrandKingDailyPrompts: true,
    followEditorInChiefStrategy: true,
    useTrendResearchEvidence: true,
    preserveCompletePlanningTraceability: true,
    avoidDuplicateOrConflictingTopics: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q4-04",
    live: false,
    engine: {
      engineVersion: "PILLOW-TPW-001",
      missionId: "Q4-04",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalTopicPlans: 0,
        lastTopicPlanId: null,
        lastCadenceStatus: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q4-04",
      status: "idle",
      healthStatus: "standby",
      totalTopicPlans: 0,
      latestTopicPlanId: null,
      neverWriteScripts: true,
      neverGenerateVisuals: true,
      neverProduceVideos: true,
      neverPublishContent: true,
      neverBypassPillowGovernance: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverRequireGrandKingDailyPrompts: true,
    },
    catalog: null,
    plans: [],
  };
}
