/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectTrendResearchWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    researchRulesEnabled: true,
    executiveReportingEnabled: true,
    useApprovedResearchSourcesOnly: true,
    neverSelectPublishingTopics: true,
    neverWriteScripts: true,
    neverGenerateThumbnails: true,
    neverPublishContent: true,
    neverGenerateContentDirectly: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ404OrLater: true,
    preserveCompleteSourceTraceability: true,
    preserveHistoricalTrendRecords: true,
    distinguishFactsFromAssumptions: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q4-03",
    live: false,
    engine: {
      engineVersion: "PILLOW-TRW-001",
      missionId: "Q4-03",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalTrendReports: 0,
        lastTrendReportId: null,
        lastTrendDirection: null,
        lastConfidenceScore: null,
        lastRecommendedPriority: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q4-03",
      status: "idle",
      healthStatus: "standby",
      totalTrendReports: 0,
      latestTrendReportId: null,
      neverSelectPublishingTopics: true,
      neverWriteScripts: true,
      neverGenerateThumbnails: true,
      neverPublishContent: true,
      neverGenerateContentDirectly: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    reports: [],
  };
}
