/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectUnifiedWorkforceCertificationSnapshot() {
  const configuration = {
    enabled: true,
    certificationRulesEnabled: true,
    componentRulesEnabled: true,
    integrationRulesEnabled: true,
    readinessRulesEnabled: true,
    validationRulesEnabled: true,
    neverExecuteWorkerTasks: true,
    neverModifyExecutiveComponents: true,
    neverRepairFailuresAutomatically: true,
    neverBeginQ1Implementation: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q0-30",
    live: false,
    engine: {
      engineVersion: "PILLOW-UWC-001",
      missionId: "Q0-30",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalCertificationReports: 0,
        certifiedCount: 0,
        failedCount: 0,
        lastFinalResult: null,
        q0ProductionReady: false,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q0-30",
      status: "idle",
      healthStatus: "standby",
      totalCertificationReports: 0,
      latestCertificationId: null,
      q0ProductionReady: false,
      neverExecuteWorkerTasks: true,
      neverModifyExecutiveComponents: true,
      neverRepairFailuresAutomatically: true,
      neverBeginQ1Implementation: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    latestCertificationReport: null,
    reports: [],
  };
}
