/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectVideoAssemblyWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    assemblyRulesEnabled: true,
    executiveReportingEnabled: true,
    neverWriteScripts: true,
    neverGenerateVoiceovers: true,
    neverGenerateThumbnails: true,
    neverPublishMedia: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ412OrLater: true,
    preserveCompleteAssetTraceability: true,
    preserveSynchronizationBetweenMediaAssets: true,
    validateRenderingQuality: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q4-11",
    live: false,
    engine: {
      engineVersion: "PILLOW-VAW-001",
      missionId: "Q4-11",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalAssemblyReports: 0,
        lastAssemblyId: null,
        lastQualityStatus: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q4-11",
      status: "idle",
      healthStatus: "standby",
      totalAssemblyReports: 0,
      latestAssemblyId: null,
      neverWriteScripts: true,
      neverGenerateVoiceovers: true,
      neverGenerateThumbnails: true,
      neverPublishMedia: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    reports: [],
  };
}
