/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectVisualResearchWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    researchRulesEnabled: true,
    executiveReportingEnabled: true,
    neverGenerateFinalCreativeAssets: true,
    neverEditImages: true,
    neverAssembleVideos: true,
    neverPublishContent: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ409OrLater: true,
    useOnlyApprovedVisualSources: true,
    preserveCompleteAssetTraceability: true,
    preserveCopyrightInformation: true,
    identifyLicensingRestrictions: true,
    detectMissingVisualAssets: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q4-08",
    live: false,
    engine: {
      engineVersion: "PILLOW-VRW-001",
      missionId: "Q4-08",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalVisualResearchReports: 0,
        lastVisualResearchId: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q4-08",
      status: "idle",
      healthStatus: "standby",
      totalVisualResearchReports: 0,
      latestVisualResearchId: null,
      neverGenerateFinalCreativeAssets: true,
      neverEditImages: true,
      neverAssembleVideos: true,
      neverPublishContent: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      useOnlyApprovedVisualSources: true,
    },
    catalog: null,
    reports: [],
  };
}
