/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectVoiceWorkerSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    voiceRulesEnabled: true,
    executiveReportingEnabled: true,
    neverRewriteScripts: true,
    neverAssembleVideos: true,
    neverPublishMedia: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ411OrLater: true,
    preserveScriptTraceability: true,
    preserveGeneratedVoiceAssetReferences: true,
    preserveVoiceConfigurationHistory: true,
    validateOutputQuality: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q4-10",
    live: false,
    engine: {
      engineVersion: "PILLOW-VOW-001",
      missionId: "Q4-10",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalVoiceReports: 0,
        lastVoiceReportId: null,
        lastQualityStatus: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q4-10",
      status: "idle",
      healthStatus: "standby",
      totalVoiceReports: 0,
      latestVoiceReportId: null,
      neverRewriteScripts: true,
      neverAssembleVideos: true,
      neverPublishMedia: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    reports: [],
  };
}
