/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectWhatsAppWorkerSnapshot() {
  const configuration = {
    enabled: true,
    whatsappRulesEnabled: true,
    validationRulesEnabled: true,
    executiveReportingEnabled: true,
    neverReplaceCrm: true,
    neverReplaceBookingWorker: true,
    neverReplaceOperationsWorker: true,
    neverModifyUnrelatedPlatformComponents: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverFabricateMessageDeliveryResults: true,
    neverBypassGrandKingApproval: true,
    neverImplementQ707OrLater: true,
    preserveCompleteTraceability: true,
    preserveConversationHistory: true,
    preserveAuditHistory: true,
    neverExposeCredentials: true,
    neverExposeProhibitedPersonalData: true,
    structuralSignalOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q7-06",
    live: false,
    engine: {
      engineVersion: "PILLOW-WAW-001",
      missionId: "Q7-06",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        totalConversations: 0,
        totalMessages: 0,
        lastReportId: null,
        lastConversationId: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q7-06",
      status: "idle",
      healthStatus: "standby",
      totalReports: 0,
      totalConversations: 0,
      totalMessages: 0,
      latestReportId: null,
      neverReplaceCrm: true,
      neverReplaceBookingWorker: true,
      neverReplaceOperationsWorker: true,
      neverFabricateMessageDeliveryResults: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverBypassGrandKingApproval: true,
      neverImplementQ707OrLater: true,
      consumableByQ707: true,
    },
    catalog: null,
    conversations: [],
    messages: [],
    reports: [],
  };
}
