/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectWorkerSelfCritiqueProtocolSnapshot() {
  const configuration = {
    enabled: true,
    critiqueRulesEnabled: true,
    completenessRulesEnabled: true,
    consistencyRulesEnabled: true,
    evidenceRulesEnabled: true,
    confidenceRulesEnabled: true,
    decisionRulesEnabled: true,
    validationRulesEnabled: true,
    neverReplacePeerReviewRuntime: true,
    neverReplaceWorkerQualityStandard: true,
    neverExecuteWorkerTasks: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q0-28",
    live: false,
    engine: {
      engineVersion: "PILLOW-WSCP-001",
      missionId: "Q0-28",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalCritiqueRecords: 0,
        reviseCount: 0,
        submitCount: 0,
        averageRevisedConfidence: 0,
        lastDecision: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q0-28",
      status: "idle",
      healthStatus: "standby",
      totalCritiqueRecords: 0,
      latestSelfCritiqueId: null,
      reviseCount: 0,
      neverReplacePeerReviewRuntime: true,
      neverReplaceWorkerQualityStandard: true,
      neverExecuteWorkerTasks: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    latestRecord: null,
    records: [],
  };
}
