/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectWorkerQualityStandardSnapshot() {
  const configuration = {
    enabled: true,
    validationRulesEnabled: true,
    confidenceRulesEnabled: true,
    evidenceRulesEnabled: true,
    assumptionRulesEnabled: true,
    limitationRulesEnabled: true,
    governanceRulesEnabled: true,
    neverExecuteWorkerTasks: true,
    neverReplaceWorkerImplementations: true,
    neverReplacePeerReviewRuntime: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q0-27",
    live: false,
    engine: {
      engineVersion: "PILLOW-WQS-001",
      missionId: "Q0-27",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalQualityRecords: 0,
        compliantCount: 0,
        nonCompliantCount: 0,
        averageConfidence: 0,
        lastDecision: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q0-27",
      status: "idle",
      healthStatus: "standby",
      totalQualityRecords: 0,
      latestQualityRecordId: null,
      compliantCount: 0,
      neverExecuteWorkerTasks: true,
      neverReplaceWorkerImplementations: true,
      neverReplacePeerReviewRuntime: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    latestRecord: null,
    records: [],
  };
}
