/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectWorkforceFactoryCertificationSnapshot() {
  const configuration = {
    enabled: true,
    certificationRulesEnabled: true,
    componentRulesEnabled: true,
    integrationRulesEnabled: true,
    governanceRulesEnabled: true,
    readinessRulesEnabled: true,
    validationRulesEnabled: true,
    neverExecuteWorkerTasks: true,
    neverModifyWorkforceComponents: true,
    neverRepairFailuresAutomatically: true,
    neverBeginQ2Implementation: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    preserveCertificationTraceability: true,
    preserveAuditability: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q1-13",
    live: false,
    engine: {
      engineVersion: "PILLOW-WFC-001",
      missionId: "Q1-13",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalCertificationReports: 0,
        certifiedCount: 0,
        failedCount: 0,
        lastFinalResult: null,
        q1ProductionReady: false,
        q2ReadinessConfirmed: false,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q1-13",
      status: "idle",
      healthStatus: "standby",
      totalCertificationReports: 0,
      latestCertificationId: null,
      q1ProductionReady: false,
      q2ReadinessConfirmed: false,
      neverExecuteWorkerTasks: true,
      neverModifyWorkforceComponents: true,
      neverRepairFailuresAutomatically: true,
      neverBeginQ2Implementation: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    reports: [],
    latestCertificationReport: null,
  };
}
