/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectWorkforceCertificationMonitorSnapshot() {
  const configuration = {
    enabled: true,
    monitoringRulesEnabled: true,
    availabilityRulesEnabled: true,
    reachabilityRulesEnabled: true,
    capabilityRulesEnabled: true,
    toolAccessRulesEnabled: true,
    governanceRulesEnabled: true,
    qualityRulesEnabled: true,
    selfCritiqueRulesEnabled: true,
    dependencyRulesEnabled: true,
    validationRulesEnabled: true,
    neverExecuteWorkerTasks: true,
    neverRepairWorkersAutomatically: true,
    neverReplaceWorkerQualityStandard: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q0-29",
    live: false,
    engine: {
      engineVersion: "PILLOW-WCM-001",
      missionId: "Q0-29",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalCertificationRecords: 0,
        certifiedCount: 0,
        decertifiedCount: 0,
        failureCount: 0,
        lastMonitorCycleAt: null,
        lastStatus: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q0-29",
      status: "idle",
      healthStatus: "standby",
      totalCertificationRecords: 0,
      latestCertificationId: null,
      certifiedCount: 0,
      neverExecuteWorkerTasks: true,
      neverRepairWorkersAutomatically: true,
      neverReplaceWorkerQualityStandard: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    latestRecord: null,
    records: [],
  };
}
