/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectWorkerRecoverySystemSnapshot() {
  const configuration = {
    enabled: true,
    detectionRulesEnabled: true,
    recoveryRulesEnabled: true,
    escalationRulesEnabled: true,
    validationRulesEnabled: true,
    neverExecuteWorkerBusinessLogic: true,
    neverReplaceWorkerMonitoring: true,
    neverReplaceWorkforceOrchestrator: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    respectAuthorityMatrix: true,
    respectWorkerLifecycle: true,
    respectMissionCoordinationEngine: true,
    preserveMissionIntegrity: true,
    preserveAuditHistory: true,
    preserveExecutionHistory: true,
    preventDuplicateExecution: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q1-12",
    live: false,
    engine: {
      engineVersion: "PILLOW-WRS-001",
      missionId: "Q1-12",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalWorkers: 0,
        totalRecords: 0,
        totalEscalations: 0,
        lastRecoveryDecision: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q1-12",
      status: "idle",
      healthStatus: "standby",
      totalWorkers: 0,
      totalRecords: 0,
      totalEscalations: 0,
      latestRecoveryId: null,
      neverExecuteWorkerBusinessLogic: true,
      neverReplaceWorkerMonitoring: true,
      neverReplaceWorkforceOrchestrator: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    workers: [],
    records: [],
  };
}
