/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectWorkforceOperatingSystemSnapshot() {
  const configuration = {
    enabled: true,
    registrationRulesEnabled: true,
    sessionRulesEnabled: true,
    communicationRulesEnabled: true,
    synchronizationRulesEnabled: true,
    monitoringRulesEnabled: true,
    recoveryRulesEnabled: true,
    neverReplacePillow: true,
    neverReplaceWorkforceOrchestrator: true,
    neverExecuteWorkerTasks: true,
    neverMakeStrategicDecisions: true,
    neverOverrideGrandKing: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q0-19",
    live: false,
    engine: {
      engineVersion: "PILLOW-WFOS-001",
      missionId: "Q0-19",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalRuntimeRecords: 0,
        organizationState: "forming",
        activeWorkerCount: 0,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q0-19",
      status: "idle",
      healthStatus: "standby",
      totalRuntimeRecords: 0,
      latestRuntimeId: null,
      organizationState: "forming",
      activeWorkerCount: 0,
      neverReplacePillow: true,
      neverReplaceWorkforceOrchestrator: true,
      neverExecuteWorkerTasks: true,
      neverMakeStrategicDecisions: true,
      neverOverrideGrandKing: true,
    },
    latestRecord: null,
    records: [],
  };
}
