/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectWorkerMonitoringSnapshot() {
  const configuration = {
    enabled: true,
    observationRulesEnabled: true,
    anomalyRulesEnabled: true,
    alertRulesEnabled: true,
    validationRulesEnabled: true,
    neverExecuteWorkerTasks: true,
    neverRestartWorkersAutomatically: true,
    neverReplaceWorkforceCertificationMonitor: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    preserveMonitoringHistory: true,
    supportsExecutiveReportingRuntime: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q1-10",
    live: false,
    engine: {
      engineVersion: "PILLOW-WMO-001",
      missionId: "Q1-10",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalWorkers: 0,
        totalRecords: 0,
        totalAlerts: 0,
        lastMonitoringDecision: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q1-10",
      status: "idle",
      healthStatus: "standby",
      totalWorkers: 0,
      totalRecords: 0,
      totalAlerts: 0,
      latestMonitoringId: null,
      neverExecuteWorkerTasks: true,
      neverRestartWorkersAutomatically: true,
      neverReplaceWorkforceCertificationMonitor: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    workers: [],
    records: [],
    alerts: [],
  };
}
