/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectWorkforceCapabilityRegistrySnapshot() {
  const configuration = {
    enabled: true,
    registrationRulesEnabled: true,
    lookupRulesEnabled: true,
    neverExecuteWork: true,
    neverAssignWorkers: true,
    neverOrchestrateWorkers: true,
    neverApproveActions: true,
    neverReplacePillow: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q0-10",
    live: false,
    engine: {
      engineVersion: "PILLOW-WCR-001",
      missionId: "Q0-10",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalWorkers: 0,
        totalDepartments: 0,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q0-10",
      status: "idle",
      healthStatus: "standby",
      totalWorkers: 0,
      totalDepartments: 0,
      totalCapabilities: 0,
      totalTools: 0,
      totalSkills: 0,
      latestRegistryId: null,
      neverExecuteWork: true,
      neverAssignWorkers: true,
      neverOrchestrateWorkers: true,
      neverApproveActions: true,
      neverReplacePillow: true,
    },
    latestRecord: null,
    records: [],
    departments: [],
    capabilities: [],
    tools: [],
    skills: [],
  };
}
