/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectWorkforceOrchestratorSnapshot() {
  const configuration = {
    enabled: true,
    discoveryRulesEnabled: true,
    selectionRulesEnabled: true,
    coordinationRulesEnabled: true,
    neverPerformWorkerTasks: true,
    neverReplaceWorkerLogic: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverPerformStrategicPlanning: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q0-09",
    live: false,
    engine: {
      engineVersion: "PILLOW-PWO-001",
      missionId: "Q0-09",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalOrchestrations: 0,
        activeWorkers: 0,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q0-09",
      status: "idle",
      healthStatus: "standby",
      totalOrchestrations: 0,
      activeWorkers: 0,
      latestOrchestrationId: null,
      neverPerformWorkerTasks: true,
      neverReplaceWorkerLogic: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverPerformStrategicPlanning: true,
    },
    latestRecord: null,
    discoveredWorkers: [],
    records: [],
  };
}
