/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectWorkerRegistrySnapshot() {
  const configuration = {
    enabled: true,
    registrationRulesEnabled: true,
    queryRulesEnabled: true,
    reportingRulesEnabled: true,
    statusRulesEnabled: true,
    validationRulesEnabled: true,
    neverExecuteWorkerTasks: true,
    neverReplaceWorkforceCapabilityRegistry: true,
    neverReplaceOrganizationCharter: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q1-07",
    live: false,
    engine: {
      engineVersion: "PILLOW-WRG-001",
      missionId: "Q1-07",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        registryVersion: "WRG-REG-v1",
        totalWorkers: 0,
        departmentCount: 0,
        factoryCount: 0,
        lastRegistryDecision: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q1-07",
      status: "idle",
      healthStatus: "standby",
      registryVersion: "WRG-REG-v1",
      totalWorkers: 0,
      departmentCount: 0,
      factoryCount: 0,
      latestWorkerId: null,
      neverExecuteWorkerTasks: true,
      neverReplaceWorkforceCapabilityRegistry: true,
      neverReplaceOrganizationCharter: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    workers: [],
  };
}
