/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectWorkforceAccessManagerSnapshot() {
  const configuration = {
    enabled: true,
    accessRulesEnabled: true,
    neverExecuteWorkerLogic: true,
    neverReplaceWorkerImplementations: true,
    neverPerformOrchestration: true,
    neverMakeStrategicDecisions: true,
    neverOverrideGrandKing: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q0-11",
    live: false,
    engine: {
      engineVersion: "PILLOW-WAM-001",
      missionId: "Q0-11",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalAccessRecords: 0,
        connectedWorkers: 0,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q0-11",
      status: "idle",
      healthStatus: "standby",
      totalAccessRecords: 0,
      connectedWorkers: 0,
      latestAccessId: null,
      neverExecuteWorkerLogic: true,
      neverReplaceWorkerImplementations: true,
      neverPerformOrchestration: true,
      neverMakeStrategicDecisions: true,
      neverOverrideGrandKing: true,
    },
    latestRecord: null,
    workers: [],
    records: [],
  };
}
