/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectWorkerLifecycleSnapshot() {
  const configuration = {
    enabled: true,
    transitionRulesEnabled: true,
    auditRulesEnabled: true,
    restorationRulesEnabled: true,
    validationRulesEnabled: true,
    neverExecuteWorkerTasks: true,
    neverReplaceWorkerRegistry: true,
    neverReplaceWorkforceCertificationMonitor: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverPermanentlyDeleted: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q1-08",
    live: false,
    engine: {
      engineVersion: "PILLOW-WLC-001",
      missionId: "Q1-08",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalWorkers: 0,
        totalRecords: 0,
        lastLifecycleDecision: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q1-08",
      status: "idle",
      healthStatus: "standby",
      totalWorkers: 0,
      totalRecords: 0,
      latestLifecycleId: null,
      neverExecuteWorkerTasks: true,
      neverReplaceWorkerRegistry: true,
      neverReplaceWorkforceCertificationMonitor: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverPermanentlyDeleted: true,
    },
    catalog: null,
    profiles: [],
    records: [],
  };
}
