/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectWorkerPerformanceReviewSnapshot() {
  const configuration = {
    enabled: true,
    reviewRulesEnabled: true,
    trendRulesEnabled: true,
    recommendationRulesEnabled: true,
    validationRulesEnabled: true,
    neverExecuteWorkerTasks: true,
    neverReplaceWorkerMonitoring: true,
    neverReplaceWorkforceCertificationMonitor: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    integratesWithWorkerAssignmentEngine: true,
    integratesWithWorkforceCertificationMonitor: true,
    integratesWithAdaptiveWorkforceOptimizer: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    preserveHistoricalPerformance: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q1-11",
    live: false,
    engine: {
      engineVersion: "PILLOW-WPR-001",
      missionId: "Q1-11",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalWorkers: 0,
        totalRecords: 0,
        lastPerformanceDecision: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q1-11",
      status: "idle",
      healthStatus: "standby",
      totalWorkers: 0,
      totalRecords: 0,
      latestPerformanceReviewId: null,
      neverExecuteWorkerTasks: true,
      neverReplaceWorkerMonitoring: true,
      neverReplaceWorkforceCertificationMonitor: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    workers: [],
    records: [],
    executiveReport: null,
  };
}
