/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectWorkerReadinessAuditSnapshot() {
  const configuration = {
    enabled: true,
    evidenceScanEnabled: true,
    runtimeProbingEnabled: true,
    executiveReportingEnabled: true,
    neverFabricateAuditEvidence: true,
    neverCertifyMissingWorkers: true,
    neverCertifyUnreachableWorkers: true,
    neverAssumeImplementation: true,
    neverModifyWorkerImplementations: true,
    neverRepairFailedWorkers: true,
    neverBypassPillowGovernance: true,
    neverBypassGrandKingApproval: true,
    neverOverrideApprovedArchitecture: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverImplementQ1103OrLater: true,
    preserveCompleteTraceability: true,
    preserveImmutableAuditHistory: true,
    preserveAuditHistory: true,
    deterministicAuditBehaviour: true,
    structuralSignalOnly: true,
    evidenceBasedOnly: true,
    maskSensitiveValues: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q11-02",
    live: false,
    engine: {
      engineVersion: "PILLOW-WRART-001",
      missionId: "Q11-02",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalReports: 0,
        lastReportId: null,
        lastReadinessDecision: null,
        lastConfidenceScore: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q11-02",
      status: "idle",
      healthStatus: "standby",
      totalReports: 0,
      latestReportId: null,
      lastReadinessDecision: null,
      lastConfidenceScore: null,
      workerId: "wkr-worker-readiness-audit-01",
      readinessClassificationOptions: [
        "Ready",
        "Partially Ready",
        "Failed",
        "Missing",
        "Blocked",
        "Deferred",
      ],
      neverFabricateAuditEvidence: true,
      neverCertifyMissingWorkers: true,
      neverCertifyUnreachableWorkers: true,
      neverAssumeImplementation: true,
      neverModifyWorkerImplementations: true,
      neverRepairFailedWorkers: true,
      neverBypassPillowGovernance: true,
      neverBypassGrandKingApproval: true,
      neverOverrideApprovedArchitecture: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
      neverImplementQ1103OrLater: true,
      secondQ11Gate: true,
    },
    catalog: null,
    reports: [],
    q1103Contract: null,
  };
}
