/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectWorkerConstitutionSnapshot() {
  const configuration = {
    enabled: true,
    definitionRulesEnabled: true,
    inheritanceRulesEnabled: true,
    complianceRulesEnabled: true,
    validationRulesEnabled: true,
    neverExecuteWorkerTasks: true,
    neverReplaceWorkerQualityStandard: true,
    neverReplaceGovernance: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q1-01",
    live: false,
    engine: {
      engineVersion: "PILLOW-WCT-001",
      missionId: "Q1-01",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        constitutionVersion: "WCT-CONST-v1",
        totalInheritanceRecords: 0,
        compliantCount: 0,
        nonCompliantCount: 0,
        lastComplianceDecision: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q1-01",
      status: "idle",
      healthStatus: "standby",
      constitutionVersion: "WCT-CONST-v1",
      totalInheritanceRecords: 0,
      latestInheritanceId: null,
      neverExecuteWorkerTasks: true,
      neverReplaceWorkerQualityStandard: true,
      neverReplaceGovernance: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    constitution: null,
    latestRecord: null,
    records: [],
  };
}
