/** Safe offline snapshot; live operations are supplied by the Pillow host. */
export function collectWorkerAssignmentEngineSnapshot() {
  const configuration = {
    enabled: true,
    discoveryRulesEnabled: true,
    evaluationRulesEnabled: true,
    recommendationRulesEnabled: true,
    validationRulesEnabled: true,
    neverExecuteWorkerTasks: true,
    neverReplaceWorkforceOrchestrator: true,
    neverReplaceTaskNegotiationProtocol: true,
    neverOverridePillow: true,
    neverOverrideGrandKing: true,
    neverExposeCredentials: true,
    neverExposeAuthenticationTokens: true,
    structuralSignalsOnly: true,
    maskSensitiveValues: true,
    neverLogSensitiveEnterpriseInformation: true,
  };
  return {
    computedAt: new Date().toISOString(),
    missionId: "Q1-09",
    live: false,
    engine: {
      engineVersion: "PILLOW-WAE-001",
      missionId: "Q1-09",
      status: "idle",
      initializedAt: new Date().toISOString(),
      configuration,
      latestReport: null,
      engineRecord: null,
      health: {
        status: "standby",
        healthScore: 50,
        engineEnabled: true,
        lastOperationAt: null,
        lastValidationDecision: null,
        totalWorkers: 0,
        totalRecords: 0,
        lastAssignmentDecision: null,
        notes: ["Pillow session unavailable — offline snapshot"],
      },
    },
    cockpit: {
      missionId: "Q1-09",
      status: "idle",
      healthStatus: "standby",
      totalWorkers: 0,
      totalRecords: 0,
      latestAssignmentId: null,
      neverExecuteWorkerTasks: true,
      neverReplaceWorkforceOrchestrator: true,
      neverReplaceTaskNegotiationProtocol: true,
      neverOverridePillow: true,
      neverOverrideGrandKing: true,
    },
    catalog: null,
    workers: [],
    records: [],
  };
}
