'use client';
import {useState} from 'react';
import type {AssuranceEvidence,EngineeringCommand,ClosureEvidence} from '@/lib/owner/assurance-contract';
type WithoutId=EngineeringCommand extends infer C?C extends {id:string}?Omit<C,'id'>:never:never;
const button='min-h-11 rounded-lg border border-amber-300/40 px-4 py-2 text-sm text-amber-100 disabled:opacity-40 disabled:cursor-not-allowed';
export function AssuranceRelease({data,disabled,send}:{data:AssuranceEvidence|null;disabled:boolean;send:(c:WithoutId)=>void}){
 const [mission,setMission]=useState('advanced-autonomous-assurance'),[state,setState]=useState<'IN_PROGRESS'|'BLOCKED'|'ACCEPTANCE_PENDING'>('IN_PROGRESS'),[evidence,setEvidence]=useState('');
 const [closureState,setClosureState]=useState<'COMPLETE'|'INCOMPLETE'|'BLOCKED_EXTERNAL'|'OWNER_ACTION_REQUIRED'>('INCOMPLETE'),[closure,setClosure]=useState<Record<string,string>>({}),[attested,setAttested]=useState(false);
 const [confirm,setConfirm]=useState<'AUTOMATIC'|'API_ADVISOR'|'OWNER_APPROVAL'|'MONITOR_FAILURE'|'DEPLOYMENT_COLLISION'|null>(null);
 const cp=data?.controlPlane;const digest=data?.reconciliation?.derivedSha256;const canAccept=!!cp&&!cp.activeAcceptance&&typeof digest==='string'&&/^[a-f0-9]{64}$/.test(digest);
 const completed=(mode:string)=>cp?.acceptances?.some(a=>a.mode===mode&&a.completed)??false;
 const references=evidence.split('\n').map(x=>x.trim()).filter(Boolean);
 return <details className="rounded-xl border border-white/15 bg-white/[0.03] p-4 sm:p-6"><summary className="min-h-11 cursor-pointer py-2 text-lg font-semibold">Release verification</summary>
  <p className="mt-2 text-slate-300">Engineering acceptance for this authorised Assurance mission. These controls use recorded revision, scoped authority and durable receipts. They do not grant commerce authority.</p>
  <div className="mt-3 flex flex-wrap gap-3"><a className={button} href="/cockpit/assurance/mobile-acceptance">Open live mobile viewport</a><button className={button} disabled={disabled} onClick={()=>send({type:'record_handover'})}>Preserve Work 1 strategic handover</button></div><p className="mt-2 text-sm">Preserves the complete owner mandate for the Work 1 audit and Work 8 certification. It does not start either Work.</p>
  <h3 className="mt-5 font-semibold">Bounded operational acceptance</h3><p className="mt-2 text-sm">A scenario interrupts only the derived operational evidence view; canonical records stay preserved. Independent monitoring must detect the interruption and verify restoration. A recorded success must not be repeated.</p>
  <div className="mt-3 flex flex-wrap gap-3"><button className={button} disabled={disabled||!canAccept||completed('AUTOMATIC')} onClick={()=>setConfirm('AUTOMATIC')}>Verify automatic recovery</button><button className={button} disabled={disabled||!canAccept||completed('API_ADVISOR')} onClick={()=>setConfirm('API_ADVISOR')}>Verify bounded API Advisor action</button><button className={button} disabled={disabled||!canAccept||completed('OWNER_APPROVAL')} onClick={()=>setConfirm('OWNER_APPROVAL')}>Prepare owner approval scenario</button><button className={button} disabled={disabled||!canAccept||completed('MONITOR_FAILURE')} onClick={()=>setConfirm('MONITOR_FAILURE')}>Verify monitoring failure detection</button><button className={button} disabled={disabled||!canAccept||completed('DEPLOYMENT_COLLISION')} onClick={()=>setConfirm('DEPLOYMENT_COLLISION')}>Verify deployment collision</button></div>
  {!canAccept&&<p className="mt-2 text-sm text-amber-200">Current revision and derived-view digest are required, with no other acceptance in progress.</p>}
  {cp?.activeAcceptance&&<p className="mt-3 break-all text-amber-200">Acceptance in progress: {cp.activeAcceptance}</p>}
  {cp?.acceptances?.map(a=><article key={a.id} className="mt-3 rounded border border-white/15 p-3 text-sm"><p className="font-semibold">{a.mode.replaceAll('_',' ').toLowerCase()} · {a.completed?'verified acceptance recorded':'acceptance pending'}</p><p className="mt-1 break-all text-xs text-slate-400">Receipt {a.id} · Incident {a.incidentId??a.monitorIncidentId??'pending'} · Recovery {a.recoveryId??'pending'}</p>{a.preservation&&<p className="mt-2">Protected-record preservation: {a.preservation.verified?'verified':'unverified'} · {a.preservation.originalCount} originals · {a.preservation.addedCount} additions</p>}<p className="mt-1 break-all text-xs text-slate-400">Preservation digest: {a.preservation?.manifestSha256??a.preservationManifestSha256??'not established'}</p></article>)}
  {confirm&&<div className="mt-4 rounded border border-amber-300/50 p-4"><h4 className="font-semibold">Confirm {confirm.toLowerCase().replaceAll('_',' ')} acceptance</h4><p className="mt-2">{confirm==='API_ADVISOR'?'This admits one bounded, accounted paid API Advisor model request. Do not repeat a successful acceptance.':'This is a deterministic acceptance scenario; it does not commission a new commercial investigation.'}</p><p className="mt-2">{confirm==='MONITOR_FAILURE'?'Pause the primary monitoring timer for a fixed 120 seconds. Independent supervision must detect degradation; the timer resumes automatically.':confirm==='DEPLOYMENT_COLLISION'?'Create a controlled Work deployment lease and interrupt the derived view. Recovery must defer. Finish the lease after independent platform readback. This is a simulated coordinated lease, not an actual rollout.':confirm==='OWNER_APPROVAL'?'The exact remedy will require approval in Owner action before execution.':'The monitoring and recovery system must complete the restoration without manual repair.'}</p><div className="mt-3 flex flex-wrap gap-3"><button className={button} disabled={disabled||!canAccept} onClick={()=>{if(cp&&typeof digest==='string')send({type:'acceptance_admit',mode:confirm,expectedRevision:cp.revision,expectedSha256:digest});setConfirm(null);}}>Admit scoped scenario</button><button className={button} onClick={()=>setConfirm(null)}>Cancel</button></div></div>}
  <h3 className="mt-6 font-semibold">Production change ownership</h3><p className="mt-2 text-sm">A lease reserves backend and frontend production change ownership for one hour. Conflicting recovery stays deferred; monitoring continues. Finish only after the authorised release has been reconciled.</p>
  <div className="mt-3 flex flex-wrap gap-3"><button className={button} disabled={disabled||!cp||cp.lease?.status==='ACTIVE'} onClick={()=>cp&&send({type:'lease_begin',expectedRevision:cp.revision,scope:['backend','frontend'],ttlMs:3600000})}>Begin coordinated release</button><button className={button} disabled={disabled||cp?.lease?.status!=='ACTIVE'} onClick={()=>cp?.lease&&send({type:'lease_finish',leaseId:cp.lease.id,fence:cp.lease.fence})}>Finish recorded release lease</button></div>
  <h3 className="mt-6 font-semibold">Durable mission checkpoint</h3><form className="mt-3 space-y-3" onSubmit={e=>{e.preventDefault();send({type:'checkpoint',missionId:mission,state,evidence:references});}}><label className="block text-sm">Mission identity<input className="mt-1 block min-h-11 w-full rounded border border-white/20 bg-[#071014] p-3" value={mission} onChange={e=>setMission(e.target.value)} pattern="[A-Za-z0-9_.:\-]{1,160}" required/></label><label className="block text-sm">Checkpoint state<select className="mt-1 block min-h-11 w-full rounded border border-white/20 bg-[#071014] p-3" value={state} onChange={e=>setState(e.target.value as typeof state)}><option value="IN_PROGRESS">In progress</option><option value="BLOCKED">Blocked</option><option value="ACCEPTANCE_PENDING">Acceptance pending</option></select></label><label className="block text-sm">Evidence references — one per line<textarea rows={4} className="mt-1 block w-full rounded border border-white/20 bg-[#071014] p-3" value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="Exact durable receipt, deployment or CI references" required/></label><button className={button} disabled={disabled||!references.length||references.length>30||references.some(r=>r.length>500)}>Save checkpoint</button></form><p className="mt-2 text-sm text-slate-400">A checkpoint records progress. It cannot declare the mission complete.</p>
  <h3 className="mt-6 font-semibold">Record mission outcome</h3><p className="mt-2 text-sm">Submit only verified evidence references. External platform and browser evidence is recorded as authenticated owner attestation; the backend independently checks its operational acceptance receipts before accepting COMPLETE. Independent Advisor readback is still required afterward.</p>
  <form className="mt-3 space-y-3" onSubmit={e=>{e.preventDefault();send({type:'mission_close',missionId:mission,state:closureState,externalEvidence:{...closure,backendSha:cp?.revision??'',ciRunIds:(closure.ciRunIds??'').split('\n').map(s=>s.trim()).filter(Boolean)} as ClosureEvidence});}}>
   <p className="text-sm">Mission: {mission} · Backend revision: <span className="break-all">{cp?.revision??'Unknown'}</span></p>
   <label className="block text-sm">Mission outcome<select className="mt-1 block min-h-11 w-full rounded border border-white/20 bg-[#071014] p-3" value={closureState} onChange={e=>setClosureState(e.target.value as typeof closureState)}><option value="INCOMPLETE">Incomplete</option><option value="BLOCKED_EXTERNAL">Blocked by external platform</option><option value="OWNER_ACTION_REQUIRED">Owner action required</option><option value="COMPLETE">Complete — all mandatory acceptance passed</option></select></label>
   {([['frontendSha','Frontend SHA (40 characters)'],['backendDeploymentId','Railway deployment ID'],['frontendDeploymentId','Vercel deployment ID'],['preservationDigest','Protected-record preservation digest (64 characters)'],['ciRunIds','Hosted CI run IDs — one per line'],['readbackProof','Independent Advisor readback evidence'],['desktopProof','Desktop interaction evidence'],['mobileProof','Mobile interaction evidence'],['collisionProof','Deployment collision evidence'],['selfFailureProof','Assurance self-failure evidence']] as const).map(([key,name])=><label className="block text-sm" key={key}>{name}<textarea rows={key.endsWith('Proof')?3:2} required minLength={key.endsWith('Proof')?10:1} maxLength={key.endsWith('Proof')?2000:2000} className="mt-1 block w-full rounded border border-white/20 bg-[#071014] p-3" value={closure[key]??''} onChange={e=>setClosure({...closure,[key]:e.target.value})}/></label>)}
   <label className="flex min-h-11 items-start gap-3 text-sm"><input type="checkbox" className="mt-1 h-5 w-5" checked={attested} onChange={e=>setAttested(e.target.checked)}/>These references identify actual verified results. Limitations are reflected in the selected outcome.</label><button className={button} disabled={disabled||!attested}>Record verified mission outcome</button>
  </form>
 </details>;
}
