import type {AssuranceEvidence} from '@/lib/owner/assurance-contract';
const object=(v:unknown):Record<string,unknown>=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{};
const text=(v:unknown,fallback='Unverified')=>typeof v==='string'?v:fallback;
export function AssuranceReconciliation({data}:{data:AssuranceEvidence|null}){
 const r=data?.reconciliation;const investigations=Array.isArray(r?.investigations)?r.investigations.map(object):[],conflicts=Array.isArray(r?.conflicts)?r.conflicts.map(object):[];
 return <section className="rounded-xl border border-white/15 bg-white/[0.03] p-4 sm:p-6"><h2 className="text-xl font-semibold">Evidence reconciliation</h2><p className="mt-2">Derived view: {text(r?.indexStatus,text(r?.status))} · {conflicts.length} recorded conflicts</p><p className="mt-2 text-sm text-slate-300">Commercial evidence, technical completion, saved responses, independent readback, internal usage and settled invoices remain separate facts. Earlier observations are preserved.</p>
  {!investigations.length&&<p className="mt-3">No source-qualified investigation is available in this snapshot.</p>}
  {conflicts.map((c,index)=><p className="mt-3 text-amber-200" key={text(c.id,String(index))}>{text(c.code)} · Mission {text(c.missionId)}</p>)}
  {investigations.map((i,index)=><details className="mt-4 rounded border border-white/15 p-3" key={text(i.missionId,String(index))}><summary className="min-h-11 cursor-pointer py-2">{text(i.missionId)} · {text(object(i.commercial).status)}</summary><p className="mt-2 text-sm">{text(i.historicalQualification,'Historical evidence qualification unavailable.')}</p><dl className="mt-3 grid gap-3 sm:grid-cols-2">{[['Commercial assessment','commercial'],['Technical workflow','technicalWorkflow'],['Durable response','durableResponse'],['Independent readback','independentReadback'],['Internal accounting','internalAccounting'],['Provider invoices','providerInvoices']].map(([name,key])=><div key={key}><dt className="text-sm text-slate-400">{name}</dt><dd className="mt-1 break-words">{text(object(i[key]).status)}</dd></div>)}</dl><p className="mt-3 text-sm text-slate-300">{text(object(i.independentReadback).scope,'No independent readback provenance available.')}</p><p className="mt-2 break-all text-xs text-slate-400">Request {text(i.requestId)} · Assessment digest {text(object(i.commercial).assessmentSha256)}</p><p className="mt-2 text-sm">{text(object(i.providerInvoices).reason,'Invoice evidence unavailable.')}</p></details>)}
 </section>;
}
