'use client';
import {useCallback,useEffect,useState} from 'react';
type Row=Record<string,unknown>;
type Mission={id:string;missionId:string;version:number;at:string;digest:string;state:{phase:string;candidate:Row;candidateDigest:string;qualification:{qualified:boolean;reasons:string[];score:number;exposure:number;economics:Row};listing?:Row;approval?:Row;orders:Record<string,Row>;outcomes:Row[];reversed:string[];decisions:{actions:string[];evidenceIds:string[]}[]}};
type Snapshot={at:string;revision:string;birth:string;commerce:string;missions:Mission[];tasks:{id:string;status:string;cursor:number;stepCount:number;error:string|null}[];providers:Row[];providerEvidence:Row[];limitations:string[]};
const button='min-h-11 rounded border border-amber-300/50 px-4 py-2 text-amber-200 disabled:opacity-40';
const input='min-h-11 w-full rounded border border-white/25 bg-slate-950 p-2 text-slate-100';
const card='min-w-0 rounded border border-white/20 p-4';
const show=(v:unknown)=>v===null||v===undefined?'Unknown':typeof v==='object'?JSON.stringify(v):String(v);
function Evidence({value,label}:{value:unknown;label:string}){return <details className={card}><summary className="cursor-pointer break-words">{label}</summary><pre className="mt-3 whitespace-pre-wrap break-all text-xs leading-5">{JSON.stringify(value,null,2)}</pre></details>;}
export function GovernedCommerce(){
 const [data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('Pipeline'),[selected,setSelected]=useState(''),[payload,setPayload]=useState(''),[receipt,setReceipt]=useState<unknown>(null),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false);
 const load=useCallback(async()=>{const r=await fetch('/api/owner/commerce',{cache:'no-store'});const value=await r.json();if(!r.ok)throw Error(value.error??'Commerce state unavailable');setData(value);},[]);
 useEffect(()=>{let active=true;const refresh=()=>load().catch(e=>{if(active)setError(e instanceof Error?e.message:'Read failed');});void refresh();const timer=setInterval(refresh,15000);return()=>{active=false;clearInterval(timer);};},[load]);
 const post=async(body:unknown)=>{setBusy(true);setError('');try{const r=await fetch('/api/owner/commerce',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const value=await r.json();if(!r.ok)throw Error(value.error??'Action not confirmed');setReceipt(value);await load();}catch(e){setError(e instanceof Error?e.message:'Action unconfirmed. Refresh before retrying the same ID.');}finally{setBusy(false);}};
 const mission=data?.missions.find(m=>m.missionId===selected)??data?.missions.at(-1);
 const command=(value:unknown)=>{if(!mission)return;return post({action:'command',input:{id:crypto.randomUUID(),missionId:mission.missionId,expectedVersion:mission.version,command:value}});};
 const tabs=['Pipeline','Suppliers','Listings','Economics','Orders & tracking','Returns & exceptions','Approvals','Providers','Autonomy','Audit'];
 return <div className="min-w-0 space-y-5"><header><p className="text-sm text-amber-200">GOVERNED COMMERCE · PRE-BIRTH</p><h1 className="mt-2 text-3xl font-semibold">Commerce execution</h1><p className="mt-2 text-slate-300">Research, prepare and inspect the complete lifecycle. Synthetic execution is isolated; real commerce remains locked.</p><p className="mt-2 text-sm">NOT_BORN · LOCKED · no external effects</p></header>
 <div className="flex flex-wrap gap-2"><button className={button} disabled={busy} onClick={()=>void load().catch(e=>setError(e.message))}>Refresh evidence</button><button className={button} disabled={busy} onClick={()=>void post({action:'scenario',id:'owner-scenario-'+crypto.randomUUID()})}>Run isolated lifecycle</button><button className={button} disabled title="Commerce remains LOCKED until separately authorised Birth">Live execution locked</button></div>
 <p className="text-sm text-slate-400">Run isolated lifecycle authorises hypothetical approval within the synthetic scenario only. It makes no provider request, purchase, refund or inference call.</p>
 {error&&<p role="alert" className="rounded border border-red-300/50 p-3">{error}</p>}{!data&&!error&&<p role="status">Loading governed evidence…</p>}
 {data&&<><p className="break-all text-xs text-slate-400">Read at {data.at} · backend {data.revision}</p><nav aria-label="Commerce views" className="flex flex-wrap gap-2">{tabs.map(t=><button key={t} className={button+(tab===t?' bg-amber-300/10':'')} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</nav>
 <label className="block">Mission<select className={input+' mt-1'} value={mission?.missionId??''} onChange={e=>setSelected(e.target.value)}><option value="">Select evidence</option>{data.missions.map(m=><option key={m.missionId} value={m.missionId}>{m.missionId} · {m.state.phase}</option>)}</select></label>
 {!data.missions.length&&<p className={card}>No governed lifecycle recorded. Run an isolated scenario or import a validated synthetic command below.</p>}
 {tab==='Pipeline'&&<section className="grid gap-3 sm:grid-cols-2">{data.missions.map(m=><article key={m.missionId} className={card}><h2 className="break-words font-semibold">{show(m.state.candidate.title)}</h2><p className="mt-2">SYNTHETIC · {m.state.phase}</p><p>Evidence score: {m.state.qualification.score.toFixed(0)}</p><p>Qualification: {m.state.qualification.qualified?'Passed isolated gates':m.state.qualification.reasons.join(', ')}</p><p>Orders: {Object.keys(m.state.orders).length} · version {m.version}</p></article>)}</section>}
 {mission&&tab==='Suppliers'&&<section className="space-y-3"><h2 className="text-xl font-semibold">Exact supplier identity</h2><p>Product, SKU, variant, warehouse and destination must match. A catalogue read alone does not establish fulfilment readiness.</p><Evidence value={mission.state.candidate.offer} label="Supplier offer, inventory freshness and freight"/></section>}
 {mission&&tab==='Listings'&&<section className="space-y-3"><h2 className="text-xl font-semibold">Listing review</h2><p>{mission.state.listing?'PREPARED · version-bound content and media manifest':'BLOCKED · listing evidence missing'}</p><p>{show(mission.state.listing?.title)}</p><p>{show(mission.state.listing?.description)}</p><Evidence value={mission.state.listing} label="Claims, attributes, variants, image rights and provenance"/><p>Changing a package invalidates its review and owner approval. Publication remains disabled.</p></section>}
 {mission&&tab==='Economics'&&<section className="space-y-3"><h2 className="text-xl font-semibold">Work 5 economics</h2><div className="grid gap-3 sm:grid-cols-3">{['contribution','net','minimumViablePrice'].map(k=><article key={k} className={card}><h3>{k==='minimumViablePrice'?'Minimum price':k}</h3><p className="text-xl">SGD {show(mission.state.qualification.economics[k])}</p><p className="text-xs">Synthetic scenario; not actual profit</p></article>)}</div><p>Capital exposure per unit: SGD {mission.state.qualification.exposure}. Actual journal entries are never created by this scenario.</p><Evidence value={mission.state.candidate.cash} label="Cash, liability, budget and FX assumptions"/></section>}
 {mission&&tab==='Orders & tracking'&&<section className="space-y-3"><h2 className="text-xl font-semibold">Synthetic orders</h2>{Object.entries(mission.state.orders).map(([id,o])=><article key={id} className={card}><h3>{id} · {show(o.outcome)}</h3><p>Accepted {show(o.accepted)} · shipped {show(o.shipped)} · delivered {show(o.delivered)}</p><p className="break-all">Provider interception ID: {show(o.providerId)}</p><Evidence value={o} label="Order, tracking and source receipts"/></article>)}</section>}
 {mission&&tab==='Returns & exceptions'&&<section className="space-y-3"><h2 className="text-xl font-semibold">Remedies and exception exposure</h2>{Object.entries(mission.state.orders).map(([id,o])=><Evidence key={id} value={o.remedies} label={id+' · isolated returns, replacements and refund intents'}/>)}{data.tasks.filter(t=>t.error).map(t=><p role="alert" key={t.id}>{t.id}: {t.error}</p>)}<p>All amounts remain SYNTHETIC_EXCLUDED_FROM_ACTUALS. No customer message or payment is sent.</p></section>}
 {mission&&tab==='Approvals'&&<section className="space-y-3"><h2 className="text-xl font-semibold">Digest-bound owner decision</h2><p className="break-all text-xs">Intent {mission.state.candidateDigest}</p><p>Approval is hypothetical and expires within one hour. Proposer, independent policy reviewer, owner and executor are separate identities.</p><Evidence value={mission.state.approval} label="Current approval and revocation"/><label className="block">Review reason<input className={input} value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="flex items-start gap-3"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed this synthetic listing, source evidence and financial exposure.</label><div className="flex flex-wrap gap-2"><button className={button} disabled={busy||!confirmed||mission.state.phase!=='REVIEWED'} onClick={()=>void command({type:'approve',digest:mission.state.candidateDigest,expiresAt:new Date(Date.now()+3600000).toISOString(),maxExposure:mission.state.qualification.exposure})}>Approve isolated preparation</button><button className={button} disabled={busy||reason.length<3||!['QUALIFIED','REVIEWED'].includes(mission.state.phase)} onClick={()=>void command({type:'review',digest:mission.state.candidateDigest,decision:'REJECT',reason})}>Reject package</button><button className={button} disabled={busy||reason.length<3||!mission.state.approval} onClick={()=>void command({type:'revoke',reason})}>Revoke approval</button></div></section>}
 {tab==='Providers'&&<section className="space-y-3"><h2 className="text-xl font-semibold">Provider capability coverage</h2><p>REAL_READ_ONLY evidence is separate from synthetic adapter acceptance. Uncommissioned or permission-denied capabilities grant no execution authority.</p>{data.providers.filter(p=>['Amazon','CJ'].includes(show(p.provider))).map(p=><article className={card} key={show(p.id)}><h3>{show(p.id)} · {show(p.availability)}</h3><p>{show(p.purpose)}</p><p className="text-sm">Last verified read: {show(p.lastVerifiedRead)}</p></article>)}<Evidence value={data.providerEvidence} label="Saved provider evidence IDs and freshness"/></section>}
 {tab==='Autonomy'&&<section className="space-y-3"><h2 className="text-xl font-semibold">Bounded Pillow commerce tasks</h2>{data.tasks.map(t=><article className={card} key={t.id}><h3 className="break-all">{t.id}</h3><p>{t.status} · {t.cursor}/{t.stepCount} durable steps · inference calls 0</p>{t.error&&<p>{t.error}</p>}<button className={button+' mt-2'} disabled={busy||['COMPLETE','BLOCKED'].includes(t.status)} onClick={()=>void post({action:'advance',id:t.id})}>Resume four bounded steps</button></article>)}{mission?.state.decisions.map((d,i)=><article key={i} className={card}><h3>Strategic reassessment {i+1}</h3><ul className="list-inside list-disc">{d.actions.map(a=><li key={a}>{a.replaceAll('_',' ')}</li>)}</ul><p className="text-sm">Active verified outcomes: {d.evidenceIds.join(', ')||'None'}</p></article>)}</section>}
 {tab==='Audit'&&<section className="space-y-3"><h2 className="text-xl font-semibold">Immutable evidence and limits</h2>{data.limitations.map(l=><p key={l}>{l}</p>)}{mission&&<Evidence value={mission} label="Latest chained execution receipt"/>}</section>}
 <details className={card}><summary className="cursor-pointer">Validated evidence command</summary><p className="my-2 text-sm">Import a typed synthetic command or an existing Four Eyes read job. Unknown fields and unauthorised effects are rejected. Retain the same command ID after an uncertain response.</p><form onSubmit={e=>{e.preventDefault();try{void post(JSON.parse(payload));}catch{setError('Invalid JSON evidence command');}}}><label>Evidence command<textarea className={input+' mt-2 min-h-40 font-mono text-xs'} value={payload} onChange={e=>setPayload(e.target.value)} required/></label><button className={button+' mt-2'} disabled={busy}>Submit governed command</button></form></details>
 </>}{receipt!==null&&<section role="status"><Evidence value={receipt} label="Durable action receipt"/></section>}</div>;
}
