'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {IntelligenceTrace} from './work7/IntelligenceTrace';
type Entry=Record<string,unknown>;
type Capability={id:string;eye:string;purpose:string;availability:string;configurationState:string;credentialPresent:boolean|null;authenticationState:string;readState:string;lastVerifiedRead:string|null;verifiedEndpoint:string|null;currentFailure:string|null;cost:Entry;limitations:string[];technicalWriteCapability:string};
type Snapshot={investigations?:Entry[];at:string;scheduler:{status:string;fresh:boolean;disabled:boolean};eyes:{eye:string;available:number;total:number;lastGoodAt:string|null}[];arsenal:Capability[];schedules:{id:string;enabled:boolean;nextAt:string}[];opportunities:Entry[];exceptions:Entry[];resources:Entry[];jobs:Entry[];evidence:Entry[];rankGrowth:Entry[];costs:Entry;pillow:Entry};
const button='min-h-11 rounded-lg border border-blue-200 bg-blue-50 px-4 py-2 text-sm text-blue-800 disabled:opacity-40';
const card='rounded-2xl border border-blue-100 bg-white p-4 text-slate-700';
function time(v:unknown){return typeof v==='string'&&!Number.isNaN(Date.parse(v))?new Intl.DateTimeFormat('en-SG',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Singapore'}).format(new Date(v))+' SGT':'Not verified';}
function Detail({value}:{value:unknown}){if(value===null||value===undefined)return <p className="mt-2 text-sm">Not recorded</p>;if(Array.isArray(value))return <div className="space-y-2">{value.map((v,i)=><details key={i} className="mt-2 rounded border border-blue-100 p-3"><summary>Record {i+1}</summary><Detail value={v}/></details>)}</div>;if(typeof value==='object')return <dl className="mt-3 grid gap-3 text-sm sm:grid-cols-2">{Object.entries(value).map(([k,v])=><div key={k} className="min-w-0 break-words"><dt className="text-xs text-slate-500">{k.replace(/([a-z])([A-Z])/g,'$1 $2')}</dt><dd>{typeof v==='object'&&v!==null?<details><summary>Inspect {k}</summary><Detail value={v}/></details>:String(v??'Unknown')}</dd></div>)}</dl>;return <p className="break-words text-sm">{String(value)}</p>;}
async function command(body:unknown){const r=await fetch('/api/owner/advisor/intelligence',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error??'Request refused');return d;}
export function OwnerEyes(){
 const [view,setView]=useState('Discoveries');
 const [missionId,setMissionId]=useState(''),[instruction,setInstruction]=useState(''),[predecessors,setPredecessors]=useState('');
 const [diagnostic,setDiagnostic]=useState<string|null>(null);
 async function readDiagnostic(){try{const r=await fetch('/api/pillow/status',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error('Status unavailable');setDiagnostic(typeof d.status?.lastError==='string'?d.status.lastError.slice(0,4000):'No current Pillow error recorded.');}catch{setDiagnostic('Pillow status unavailable; no healthy state is assumed.');}}
 const [data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[query,setQuery]=useState('desk organizer'),[eye,setEye]=useState('amazon.catalog');
 const load=useCallback(async()=>{try{const r=await fetch('/api/owner/advisor/read?domain=intelligence',{cache:'no-store'});const d=await r.json();if(!r.ok||!d.data)throw Error(d.reason??d.error??'Intelligence evidence unavailable');setData(d.data);setError('');}catch(e){setError(e instanceof Error?e.message:'Read unavailable');}},[]);
 useEffect(()=>{let active=true;fetch('/api/owner/advisor/read?domain=intelligence',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok||!d.data)throw Error(d.reason??'Intelligence unavailable');if(active)setData(d.data);}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Read unavailable');});const timer=setInterval(()=>void load(),60000);return()=>{active=false;clearInterval(timer);};},[load]);
 async function act(body:unknown){setBusy(true);setNotice('');try{await command(body);setNotice('Recorded. A queued investigation is not a completed finding.');await load();}catch(e){setNotice(e instanceof Error?e.message:'Request refused');}finally{setBusy(false);}}
 return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-widest text-blue-700">Commercial intelligence</p><h1 className="mt-2 text-3xl font-semibold">Intelligence</h1><p className="mt-2 max-w-2xl text-sm text-slate-600">What we can see, what changed, and what still needs evidence.</p></div><button className={button} onClick={()=>void load()}>Refresh stored view</button></div>
 <div className="flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-amber-300/10 px-3 py-2 text-blue-700">NOT_BORN · Commerce LOCKED</span><span className="rounded-full bg-white/5 px-3 py-2">Reads and collection do not call Pillow inference</span></div>

 {error&&<p role="alert" className="rounded border border-red-400/50 p-4 text-red-700">{error}. {data?'The view below is the last loaded snapshot.':'No healthy state is assumed.'}</p>}
 {!data&&!error&&<p role="status">Loading stored intelligence…</p>}
 {data&&<><p className="text-xs text-slate-500">Snapshot {time(data.at)} · Scheduler {data.scheduler.status}{data.scheduler.disabled?' · Paused':''}</p>
<nav aria-label="Intelligence views" className="flex flex-wrap gap-2">{['Discoveries','Investigations & controls','Sources & diagnostics'].map(v=><button key={v} className={button} aria-pressed={view===v} onClick={()=>setView(v)}>{v}</button>)}</nav>{view==='Discoveries'&&<IntelligenceTrace evidence={data.evidence} opportunities={data.opportunities}/>}{view==='Sources & diagnostics'&&<> <details className={card}><summary className="min-h-11 cursor-pointer py-3">Pillow investigation diagnostics</summary><p className="text-sm text-slate-600">Read the current host error without starting inference. This is a process diagnostic, not a completed assessment or mission closure.</p><button className={button+' mt-3'} onClick={()=>void readDiagnostic()}>Read current Pillow diagnostic</button>{diagnostic!==null&&<pre className="mt-3 whitespace-pre-wrap break-words text-sm" role="status">{diagnostic}</pre>}</details><section aria-label="Four Eyes health" className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{data.eyes.map(e=><div key={e.eye} className={card}><h2 className="font-semibold capitalize">{e.eye.toLowerCase()} Eye</h2><p className={'mt-3 text-lg '+(e.available?'text-emerald-700':'text-blue-700')}>{e.available} verified and fresh</p><p className="mt-1 text-xs text-slate-500">of {e.total} declared capabilities</p><p className="mt-3 text-xs">Last good: {time(e.lastGoodAt)}</p></div>)}</section></>}
{view==='Discoveries'&& <section className={card}><h2 className="text-lg font-semibold">What matters now</h2><p className="mt-2 text-sm text-slate-600">{data.opportunities.length} candidate investigations · {data.exceptions.filter(e=>e.status==='OPEN').length} open gaps or exceptions. Candidates are not approved products.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{data.opportunities.map((o)=><details key={String(o.id)} className="rounded border border-blue-100 p-3"><summary className="cursor-pointer text-sm">{String(o.status)} · Evidence {String(o.evidenceCompleteness)} · {String((o.subject as Entry)?.id??o.id)}</summary><p className="mt-2 text-sm text-blue-800">Missing: {Array.isArray(o.missing)?o.missing.join(', '):'Not evaluated'}</p><Detail value={o}/></details>)}</div>{!data.opportunities.length&&<p className="mt-3 text-sm text-slate-500">No qualified candidate yet. Collector output and gaps remain visible below.</p>}<details className="mt-4"><summary className="cursor-pointer text-sm">Exceptions and missing evidence</summary><Detail value={data.exceptions}/></details></section>}
{view==='Investigations & controls'&&<> <section className={card}><h2 className="text-lg font-semibold">Pillow and investigations</h2><p className="mt-2 text-sm text-slate-600">Collectors gather evidence. Pillow’s actual requests and completed research are shown separately; a job receipt does not imply a CEO recommendation.</p><form className="mt-4 flex flex-wrap items-end gap-3" onSubmit={e=>{e.preventDefault();void act({action:'job',job:{id:'owner_'+crypto.randomUUID(),objective:'Investigate '+query,capabilities:[eye],subject:{id:'research',query,marketplace:'US'},requestLimit:4}});}}><label className="grid gap-2 text-sm">Source<select className="min-h-11 rounded bg-blue-50 p-2" value={eye} onChange={e=>setEye(e.target.value)}><option value="amazon.catalog">Amazon market</option><option value="cj.catalog">CJ sourcing</option><option value="internet.safety">US product safety</option></select></label><label className="grid min-w-0 flex-1 gap-2 text-sm">Research topic<input className="min-h-11 min-w-0 rounded bg-blue-50 p-2" maxLength={120} minLength={2} required value={query} onChange={e=>setQuery(e.target.value)}/></label><button disabled={busy} className={button}>Queue bounded read</button></form><p role="status" className="mt-3 text-sm text-blue-700">{notice}</p><div className="mt-3 space-y-2">{data.jobs.map(j=><details key={String(j.id)} className="border-b border-blue-100 py-2"><summary className="cursor-pointer text-sm">{String(j.status)} · {String(j.objective)} <span className="text-slate-500">· {String(j.requester)}</span></summary><Detail value={j}/></details>)}</div><details className="mt-4"><summary className="cursor-pointer text-sm">Actual Pillow commissioning activity</summary><Detail value={data.pillow}/></details><Link href="/cockpit/development/pillow" className="mt-4 inline-block min-h-11 py-3 text-sm text-blue-700 underline">Discuss the evidence with Pillow</Link></section>
 <section className={card}><h2 className="text-lg font-semibold">Authorise Pillow investigation</h2><p className="mt-2 text-sm text-slate-600">Authorise one instruction, then send that exact instruction to Pillow. It can collect evidence in two bounded rounds: up to eight jobs, 24 provider requests and three accounted AI calls. No new subscriptions or commerce actions. The authorisation cannot be reused.</p><form className="mt-4 grid gap-3" onSubmit={e=>{e.preventDefault();void act({action:'investigation',grant:{id:missionId,instruction,predecessors:predecessors.split(',').map(v=>v.trim()).filter(Boolean)}});}}><label className="grid gap-2 text-sm">Investigation reference<input required pattern="[A-Za-z0-9_.:-]+" maxLength={160} value={missionId} onChange={e=>setMissionId(e.target.value)} className="min-h-11 rounded bg-blue-50 p-2"/></label><label className="grid gap-2 text-sm">Pillow instruction<textarea required minLength={40} maxLength={8000} rows={6} value={instruction} onChange={e=>setInstruction(e.target.value)} className="rounded bg-blue-50 p-2"/></label><label className="grid gap-2 text-sm">Historical request references, separated by commas<input value={predecessors} onChange={e=>setPredecessors(e.target.value)} className="min-h-11 rounded bg-blue-50 p-2"/></label><button disabled={busy} className={button}>Authorise this investigation</button></form><p className="mt-3 text-sm" role="status">{notice}</p>{data.investigations?.map(r=><div key={String(r.id)} className="mt-4 border-t border-blue-100 pt-3"><p>{String(r.id)} · {String(r.status)}</p><details><summary className="min-h-11 cursor-pointer py-3">Investigation receipt</summary><Detail value={r}/></details>{r.status==='ASSESSED_PENDING_ACCEPTANCE'&&<button disabled={busy} className={button} onClick={()=>void act({action:'close_investigation',id:r.id,advisorRequestId:(r.assessment as Entry).requestId,assessmentHash:(r.assessment as Entry).sha256})}>Record acceptance after independent Advisor readback</button>}</div>)}</section></>}
{view==='Sources & diagnostics'&&<> <section className={card}><h2 className="text-lg font-semibold">Intelligence Arsenal</h2><div className="mt-4 space-y-3">{data.arsenal.map(c=><details key={c.id} className="rounded border border-blue-100 p-3"><summary className="cursor-pointer text-sm"><span className="font-medium">{c.id}</span><span className="ml-3 text-blue-700">{c.availability}</span><p className="mt-1 text-slate-600">{c.purpose}</p></summary><dl className="mt-3 grid gap-2 text-xs sm:grid-cols-2"><div>Configuration: {c.configurationState}</div><div>Credential present: {c.credentialPresent===null?'Not required':c.credentialPresent?'Yes':'No'}</div><div>Authentication: {c.authenticationState}</div><div>Read: {c.readState}</div><div>Last good: {time(c.lastVerifiedRead)}</div><div>Verified endpoint: {c.verifiedEndpoint??'None'}</div><div>Write capability: {c.technicalWriteCapability}</div><div>Authority: Read only</div></dl><Detail value={{cost:c.cost,limitations:c.limitations,currentFailure:c.currentFailure}}/></details>)}</div></section>
 <section className={card}><h2 className="text-lg font-semibold">Owner attention · resources</h2><p className="mt-2 text-sm text-slate-600">No new subscription has been purchased. Unknown prices remain unknown. Approval here records a preference and never purchases a service.</p>{data.resources.map(r=><div key={String(r.id)} className="mt-4 rounded border border-blue-100 p-3"><p className="font-medium">{String(r.gap)}</p><p className="mt-2 text-sm">{String(r.proposal)}</p><p className="mt-2 text-xs text-blue-700">{String(r.decision)} · Monthly estimate: {r.estimatedMonthlyUsd===null?'Unverified':String(r.estimatedMonthlyUsd)+' USD'}</p><details className="mt-2"><summary className="cursor-pointer text-sm">Reason, alternatives and expected value</summary><Detail value={r}/></details><button className={button+' mt-3'} disabled={busy||r.decision==='REJECTED'} onClick={()=>void act({action:'resource',resource:{id:r.id,gap:r.gap,existingConsidered:r.existingConsidered,insufficiency:r.insufficiency,proposal:r.proposal,alternatives:r.alternatives,estimatedMonthlyUsd:r.estimatedMonthlyUsd,expectedValue:r.expectedValue,decision:'REJECTED'}})}>Defer this resource</button></div>)}</section>
 <section className={card}><h2 className="text-lg font-semibold">Rank and growth</h2><p className="mt-2 text-sm text-slate-600">Visibility → clicks → carts → purchases. Organic and paid evidence stay distinct. No real EmpireAI conversion or profitability is claimed before Birth.</p>{data.rankGrowth.length?<Detail value={data.rankGrowth}/>:<p className="mt-3 text-sm text-blue-700">Awaiting eligible first-party funnel evidence. Catalog sales rank is a proxy, not an exact keyword position.</p>}</section>
 <section className={card}><h2 className="text-lg font-semibold">Sources, cadence and cost</h2><div className="mt-3 space-y-3">{data.schedules.map(s=><div key={s.id} className="flex flex-wrap items-center justify-between gap-3 border-b border-blue-100 py-2"><div className="text-sm">{s.id}<p className="text-xs text-slate-500">Next eligible cycle {time(s.nextAt)}</p></div><button className={button} disabled={busy} onClick={()=>void act({action:'schedule',id:s.id,enabled:!s.enabled})}>{s.enabled?'Pause':'Resume'}</button></div>)}</div><details className="mt-4"><summary className="cursor-pointer text-sm">Cost and bounds</summary><Detail value={data.costs}/></details><details className="mt-4"><summary className="cursor-pointer text-sm">Recent evidence · provenance and freshness</summary>{data.evidence.map(e=><details key={String(e.id)} className="mt-3 border-b border-blue-100 pb-3"><summary className="cursor-pointer text-xs">{String(e.capabilityId)} · {String(e.authenticity)} · {time(e.observedAt)}</summary><Detail value={e}/></details>)}</details></section></>}
 </>}</div>;
}
