'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
type Entry=Record<string,unknown>;
type Capability={id:string;eye:string;purpose:string;availability:string;configurationState:string;credentialPresent:boolean|null;authenticationState:string;readState:string;lastVerifiedRead:string|null;verifiedEndpoint:string|null;currentFailure:string|null;cost:Entry;limitations:string[];technicalWriteCapability:string};
type Snapshot={at:string;scheduler:{status:string;fresh:boolean;disabled:boolean};eyes:{eye:string;available:number;total:number;lastGoodAt:string|null}[];arsenal:Capability[];schedules:{id:string;enabled:boolean;nextAt:string}[];opportunities:Entry[];exceptions:Entry[];resources:Entry[];jobs:Entry[];evidence:Entry[];rankGrowth:Entry[];costs:Entry;pillow:Entry};
const button='min-h-11 rounded-lg border border-amber-300/40 px-4 py-2 text-sm text-amber-100 disabled:opacity-40';
const card='rounded-xl border border-white/10 bg-[#0d2027] p-4';
function time(v:unknown){return typeof v==='string'&&!Number.isNaN(Date.parse(v))?new Intl.DateTimeFormat('en-SG',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Singapore'}).format(new Date(v))+' SGT':'Not verified';}
function Detail({value}:{value:unknown}){return <pre className="mt-3 max-h-96 overflow-auto whitespace-pre-wrap break-words rounded bg-black/20 p-3 text-xs text-slate-300">{JSON.stringify(value,null,2)}</pre>;}
async function command(body:unknown){const r=await fetch('/api/owner/advisor/intelligence',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error??'Request refused');return d;}
export function OwnerEyes(){
 const [data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[query,setQuery]=useState('desk organizer'),[eye,setEye]=useState('amazon.catalog');
 const load=useCallback(async()=>{try{const r=await fetch('/api/owner/advisor/read?domain=intelligence',{cache:'no-store'});const d=await r.json();if(!r.ok||!d.data)throw Error(d.reason??d.error??'Intelligence evidence unavailable');setData(d.data);setError('');}catch(e){setError(e instanceof Error?e.message:'Read unavailable');}},[]);
 useEffect(()=>{let active=true;fetch('/api/owner/advisor/read?domain=intelligence',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok||!d.data)throw Error(d.reason??'Intelligence unavailable');if(active)setData(d.data);}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Read unavailable');});const timer=setInterval(()=>void load(),60000);return()=>{active=false;clearInterval(timer);};},[load]);
 async function act(body:unknown){setBusy(true);setNotice('');try{await command(body);setNotice('Recorded. A queued investigation is not a completed finding.');await load();}catch(e){setNotice(e instanceof Error?e.message:'Request refused');}finally{setBusy(false);}}
 return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-widest text-amber-300">Commercial intelligence</p><h1 className="mt-2 text-3xl font-semibold">Four Eyes</h1><p className="mt-2 max-w-2xl text-sm text-slate-300">What we can see, what changed, and what still needs evidence.</p></div><button className={button} onClick={()=>void load()}>Refresh stored view</button></div>
 <div className="flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-amber-300/10 px-3 py-2 text-amber-200">NOT_BORN · Commerce LOCKED</span><span className="rounded-full bg-white/5 px-3 py-2">Reads and collection do not call Pillow inference</span></div>
 {error&&<p role="alert" className="rounded border border-red-400/50 p-4 text-red-200">{error}. {data?'The view below is the last loaded snapshot.':'No healthy state is assumed.'}</p>}
 {!data&&!error&&<p role="status">Loading stored intelligence…</p>}
 {data&&<><p className="text-xs text-slate-400">Snapshot {time(data.at)} · Scheduler {data.scheduler.status}{data.scheduler.disabled?' · Paused':''}</p>
 <section aria-label="Four Eyes health" className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{data.eyes.map(e=><div key={e.eye} className={card}><h2 className="font-semibold capitalize">{e.eye.toLowerCase()} Eye</h2><p className={'mt-3 text-lg '+(e.available?'text-emerald-300':'text-amber-200')}>{e.available} verified and fresh</p><p className="mt-1 text-xs text-slate-400">of {e.total} declared capabilities</p><p className="mt-3 text-xs">Last good: {time(e.lastGoodAt)}</p></div>)}</section>
 <section className={card}><h2 className="text-lg font-semibold">What matters now</h2><p className="mt-2 text-sm text-slate-300">{data.opportunities.length} candidate investigations · {data.exceptions.filter(e=>e.status==='OPEN').length} open gaps or exceptions. Candidates are not approved products.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{data.opportunities.map((o)=><details key={String(o.id)} className="rounded border border-white/10 p-3"><summary className="cursor-pointer text-sm">{String(o.status)} · Evidence {String(o.evidenceCompleteness)} · {String((o.subject as Entry)?.id??o.id)}</summary><p className="mt-2 text-sm text-amber-100">Missing: {Array.isArray(o.missing)?o.missing.join(', '):'Not evaluated'}</p><Detail value={o}/></details>)}</div>{!data.opportunities.length&&<p className="mt-3 text-sm text-slate-400">No qualified candidate yet. Collector output and gaps remain visible below.</p>}<details className="mt-4"><summary className="cursor-pointer text-sm">Exceptions and missing evidence</summary><Detail value={data.exceptions}/></details></section>
 <section className={card}><h2 className="text-lg font-semibold">Pillow and investigations</h2><p className="mt-2 text-sm text-slate-300">Collectors gather evidence. Pillow’s actual requests and completed research are shown separately; a job receipt does not imply a CEO recommendation.</p><form className="mt-4 flex flex-wrap items-end gap-3" onSubmit={e=>{e.preventDefault();void act({action:'job',job:{id:'owner_'+crypto.randomUUID(),objective:'Investigate '+query,capabilities:[eye],subject:{id:'research',query,marketplace:'US'},requestLimit:4}});}}><label className="grid gap-2 text-sm">Source<select className="min-h-11 rounded bg-[#142e37] p-2" value={eye} onChange={e=>setEye(e.target.value)}><option value="amazon.catalog">Amazon market</option><option value="cj.catalog">CJ sourcing</option><option value="internet.safety">US product safety</option></select></label><label className="grid min-w-0 flex-1 gap-2 text-sm">Research topic<input className="min-h-11 min-w-0 rounded bg-[#142e37] p-2" maxLength={120} minLength={2} required value={query} onChange={e=>setQuery(e.target.value)}/></label><button disabled={busy} className={button}>Queue bounded read</button></form><p role="status" className="mt-3 text-sm text-amber-200">{notice}</p><div className="mt-3 space-y-2">{data.jobs.map(j=><details key={String(j.id)} className="border-b border-white/10 py-2"><summary className="cursor-pointer text-sm">{String(j.status)} · {String(j.objective)} <span className="text-slate-400">· {String(j.requester)}</span></summary><Detail value={j}/></details>)}</div><details className="mt-4"><summary className="cursor-pointer text-sm">Actual Pillow commissioning activity</summary><Detail value={data.pillow}/></details><Link href="/cockpit/development/pillow" className="mt-4 inline-block min-h-11 py-3 text-sm text-amber-200 underline">Discuss the evidence with Pillow</Link></section>
 <section className={card}><h2 className="text-lg font-semibold">Intelligence Arsenal</h2><div className="mt-4 space-y-3">{data.arsenal.map(c=><details key={c.id} className="rounded border border-white/10 p-3"><summary className="cursor-pointer text-sm"><span className="font-medium">{c.id}</span><span className="ml-3 text-amber-200">{c.availability}</span><p className="mt-1 text-slate-300">{c.purpose}</p></summary><dl className="mt-3 grid gap-2 text-xs sm:grid-cols-2"><div>Configuration: {c.configurationState}</div><div>Credential present: {c.credentialPresent===null?'Not required':c.credentialPresent?'Yes':'No'}</div><div>Authentication: {c.authenticationState}</div><div>Read: {c.readState}</div><div>Last good: {time(c.lastVerifiedRead)}</div><div>Verified endpoint: {c.verifiedEndpoint??'None'}</div><div>Write capability: {c.technicalWriteCapability}</div><div>Authority: Read only</div></dl><Detail value={{cost:c.cost,limitations:c.limitations,currentFailure:c.currentFailure}}/></details>)}</div></section>
 <section className={card}><h2 className="text-lg font-semibold">Owner attention · resources</h2><p className="mt-2 text-sm text-slate-300">No new subscription has been purchased. Unknown prices remain unknown. Approval here records a preference and never purchases a service.</p>{data.resources.map(r=><div key={String(r.id)} className="mt-4 rounded border border-white/10 p-3"><p className="font-medium">{String(r.gap)}</p><p className="mt-2 text-sm">{String(r.proposal)}</p><p className="mt-2 text-xs text-amber-200">{String(r.decision)} · Monthly estimate: {r.estimatedMonthlyUsd===null?'Unverified':String(r.estimatedMonthlyUsd)+' USD'}</p><details className="mt-2"><summary className="cursor-pointer text-sm">Reason, alternatives and expected value</summary><Detail value={r}/></details><button className={button+' mt-3'} disabled={busy||r.decision==='REJECTED'} onClick={()=>void act({action:'resource',resource:{id:r.id,gap:r.gap,existingConsidered:r.existingConsidered,insufficiency:r.insufficiency,proposal:r.proposal,alternatives:r.alternatives,estimatedMonthlyUsd:r.estimatedMonthlyUsd,expectedValue:r.expectedValue,decision:'REJECTED'}})}>Defer this resource</button></div>)}</section>
 <section className={card}><h2 className="text-lg font-semibold">Rank and growth</h2><p className="mt-2 text-sm text-slate-300">Visibility → clicks → carts → purchases. Organic and paid evidence stay distinct. No real EmpireAI conversion or profitability is claimed before Birth.</p>{data.rankGrowth.length?<Detail value={data.rankGrowth}/>:<p className="mt-3 text-sm text-amber-200">Awaiting eligible first-party funnel evidence. Catalog sales rank is a proxy, not an exact keyword position.</p>}</section>
 <section className={card}><h2 className="text-lg font-semibold">Sources, cadence and cost</h2><div className="mt-3 space-y-3">{data.schedules.map(s=><div key={s.id} className="flex flex-wrap items-center justify-between gap-3 border-b border-white/10 py-2"><div className="text-sm">{s.id}<p className="text-xs text-slate-400">Next eligible cycle {time(s.nextAt)}</p></div><button className={button} disabled={busy} onClick={()=>void act({action:'schedule',id:s.id,enabled:!s.enabled})}>{s.enabled?'Pause':'Resume'}</button></div>)}</div><details className="mt-4"><summary className="cursor-pointer text-sm">Cost and bounds</summary><Detail value={data.costs}/></details><details className="mt-4"><summary className="cursor-pointer text-sm">Recent evidence · provenance and freshness</summary>{data.evidence.map(e=><details key={String(e.id)} className="mt-3 border-b border-white/10 pb-3"><summary className="cursor-pointer text-xs">{String(e.capabilityId)} · {String(e.authenticity)} · {time(e.observedAt)}</summary><Detail value={e}/></details>)}</details></section>
 </>}</div>;
}
