'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
type Package={id:string;type:string;domain:string;requestedOutcome:string;requestedHandler:string;effectIntent:string;rationale:string;payload:{text:string};assets:unknown[];synthetic:boolean};
type Preview={valid:boolean;package:Package;route:{handler:string;status:string;code:string}};
type Item={id:string;handler:string;status:string;result:string};
const button='min-h-11 rounded border border-amber-300/40 px-4 py-2 text-amber-100 disabled:opacity-40';
async function api(path:string,body?:unknown){const r=await fetch('/api/owner/advisor/'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?undefined:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});const data=await r.json();if(!r.ok)throw Error(data.error??data.code??'Service unavailable');return data;}
export function OwnerAdvisor(){
 const [preview,setPreview]=useState<Preview|null>(null),[items,setItems]=useState<Item[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[result,setResult]=useState<unknown>(null),[consent,setConsent]=useState<Record<string,string>|null>(null);
 async function reload(){try{const data=await api('read?domain=communications');if(data.status==='UNAVAILABLE')throw Error('Stored communications unavailable');setItems(data.data??[]);}catch(error){setMessage(String(error));}}
 useEffect(()=>{const search=new URLSearchParams(window.location.search);if(search.has('client_id'))setConsent(Object.fromEntries(search));void reload();},[]);
 async function upload(file:File|undefined){setPreview(null);setResult(null);if(!file)return;if(file.size>96000||!file.name.toLowerCase().endsWith('.json')){setMessage('Choose one JSON communication package, no larger than 96 KB.');return;}setBusy(true);try{setPreview(await api('validate',JSON.parse(await file.text())));setMessage('Package validated. Review it before importing.');}catch(error){setMessage(String(error));}finally{setBusy(false);}}
 async function confirm(){if(!preview)return;setBusy(true);try{const data=await api('import',preview.package);setResult(data);setPreview(null);setMessage(data.receipt.code==='ALREADY_IMPORTED'?'Already imported; no duplicate work was created.':'Imported. This does not grant approval or execution authority.');await reload();}catch(error){setMessage(String(error));}finally{setBusy(false);}}
 async function authorize(){if(!consent)return;setBusy(true);try{const data=await api('consent',consent);const target=new URL(data.redirect);if(target.origin!=='https://chatgpt.com'||target.pathname!=='/connector_platform_oauth_redirect')throw Error('Invalid connection response');window.location.assign(target.href);}catch(error){setMessage(String(error));setBusy(false);}}
 return <div className="max-w-4xl space-y-6"><Link href="/cockpit" className="text-amber-200">← Executive Home</Link><h1 className="text-3xl font-semibold">King&apos;s Advisor</h1><p>Independent advice and evidence. Pillow remains EmpireAI&apos;s CEO. Imported advice is not owner approval. NOT_BORN · Commerce locked.</p>
 {consent&&<section className="rounded-xl border p-5"><h2 className="text-xl">Connect read-only access</h2><p className="my-3">Allow this ChatGPT connection to read private EmpireAI business evidence, Pillow conversations, accounting and communications. It cannot import, approve or execute actions. Access expires after 30 days and can be revoked here.</p><button className={button} disabled={busy} onClick={authorize}>Authorize read-only connection</button></section>}
 <section className="space-y-4 rounded-xl border border-white/20 p-5"><h2 className="text-xl">Import King&apos;s Advisor communication</h2><p>Select the single JSON package supplied by your Advisor. Text assets are accepted; executable files and archives are not supported.</p><label className="block">Communication package<input type="file" accept=".json,application/json" disabled={busy} className="mt-2 block max-w-full" onChange={e=>void upload(e.target.files?.[0])}/></label>
 {preview&&<div className="space-y-3 break-words"><h3 className="font-semibold">Review before import</h3><p>{preview.package.type} · {preview.package.domain}</p><p>{preview.package.requestedOutcome}</p><p>Handler: {preview.route.handler} · Expected status: {preview.route.status}</p><p>Effect intent: {preview.package.effectIntent} · Assets: {preview.package.assets.length} · {preview.package.synthetic?'Synthetic test evidence':'Advisor evidence'}</p><p className="whitespace-pre-wrap">{preview.package.payload.text}</p><p>No authority is granted by importing. A real CEO-review request may use paid Pillow inference under existing accounting controls.</p><button className={button} disabled={busy} onClick={confirm}>Confirm import</button></div>}</section>
 <p role="status" className="break-words">{message}</p><section className="space-y-3"><h2 className="text-xl">Communications and results</h2><button className={button} disabled={busy} onClick={()=>void reload()}>Refresh status</button>{items.map(item=><article className="rounded border border-white/15 p-4" key={item.id}><p className="break-all">{item.id}</p><p>{item.handler} · {item.status}</p><button className={button} onClick={()=>void api('result/'+encodeURIComponent(item.id)).then(setResult).catch(e=>setMessage(String(e)))}>Inspect result</button></article>)}{items.length===0&&<p>No communications loaded.</p>}</section>
 {result!==null&&<details open className="rounded border p-4"><summary>Recorded result and provenance</summary><pre className="mt-3 max-h-96 overflow-auto whitespace-pre-wrap break-words text-sm">{JSON.stringify(result,null,2)}</pre></details>}
 <section className="space-y-3 rounded-xl border p-5"><h2 className="text-xl">Read bridge connection</h2><p>Connect a custom MCP server in ChatGPT using OAuth and this endpoint:</p><code className="block break-all text-sm">https://empireai-locked-runtime-production.up.railway.app/advisor/mcp</code><p>Reconnect through ChatGPT when access expires. Connection identity is an owner-authorized client; EmpireAI cannot prove the exact ChatGPT conversation.</p><button className={button} disabled={busy} onClick={()=>{setBusy(true);void api('revoke',{}).then(()=>setMessage('All Advisor read connections revoked. Pillow and owner access remain available.')).catch(e=>setMessage(String(e))).finally(()=>setBusy(false));}}>Revoke all Advisor read connections</button></section></div>;
}
