'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {AssuranceAlert} from './AssuranceAlert';
import type snapshot from '@/lib/owner/evidence.snapshot.json';
type Snapshot=typeof snapshot;
function useEvidence(){
 const [data,setData]=useState<Snapshot|null>(null);const [error,setError]=useState(false);const [attempt,setAttempt]=useState(0);
 useEffect(()=>{const controller=new AbortController();const timeout=setTimeout(()=>{setError(true);controller.abort();},12000);
 fetch('/api/owner/overview',{cache:'no-store',signal:controller.signal}).then(async r=>{if(!r.ok)throw Error('Unavailable');return r.json();}).then(setData).catch(()=>{if(!controller.signal.aborted)setError(true);else if(controller.signal.reason?.name==='TimeoutError')setError(true);}).finally(()=>clearTimeout(timeout));
 return()=>{clearTimeout(timeout);controller.abort();};},[attempt]);
 return {data,error,retry:()=>{setError(false);setAttempt(x=>x+1);}};
}
function Loading({error,retry}:{error:boolean;retry:()=>void}){return <section role="status"><h1 className="text-2xl font-semibold">Owner workspace</h1><p className="mt-4">{error?'Saved evidence is unavailable. No business decision should rely on this page until it loads.':'Loading your saved evidence…'}</p>{error&&<button className="mt-4 rounded border p-3" onClick={retry}>Try again</button>}</section>;}
const panel='rounded-xl border border-white/15 bg-white/[0.03] p-4 sm:p-6';
const link='inline-flex min-h-11 items-center rounded-lg border border-amber-300/40 px-4 py-2 text-amber-200';
function DateNote({at}:{at:string}){return <p className="text-sm text-slate-400">Saved observation: {new Date(at).toISOString().replace('T',' ').replace('.000','')} · Historical, not live; stale for a purchase decision · Stock and prices must be checked again before trading.</p>;}
function LiveRuntime(){
 const [state,setState]=useState<{transportReady:boolean;birth:string;commerce:string;backendRevision:string;checkedAt:string}|null>(null);
 const [failed,setFailed]=useState(false);
 useEffect(()=>{const controller=new AbortController();fetch('/api/owner/runtime',{cache:'no-store',signal:controller.signal}).then(async r=>{if(!r.ok)throw Error('Unavailable');return r.json();}).then(setState).catch(()=>{if(!controller.signal.aborted)setFailed(true);});return()=>controller.abort();},[]);
 return <div className="mt-4 rounded border border-white/15 p-3" role="status"><strong>Live runtime</strong>{state?<><p>Transport and storage: {state.transportReady?'ready':'not ready'} · {state.birth} · {state.commerce}</p><p>Business operation is not authorised.</p><p className="break-all text-sm text-slate-400">Backend {state.backendRevision} · Checked {state.checkedAt}</p></>:<p>{failed?'Live identity unavailable. Current readiness is unknown.':'Checking current runtime…'}</p>}</div>;
}
export function OwnerHome(){const {data,error,retry}=useEvidence();if(!data)return <div className="space-y-6"><AssuranceAlert/><Loading error={error} retry={retry}/></div>;const selected=data.candidates.find(c=>c.selected);return <div className="space-y-6">
 <div><p className="text-sm text-amber-200">Your business, at a glance</p><h1 className="mt-1 text-3xl font-semibold">Executive Home</h1><p className="mt-3 text-slate-300">Trading is paused. Pillow is not yet certified to run the business.</p></div>
 <AssuranceAlert/><section className={panel} aria-labelledby="attention"><h2 id="attention" className="text-xl font-semibold">Today / attention</h2><p className="mt-3">No products are ready for your approval.</p><ul className="my-4 list-disc space-y-2 pl-5 text-slate-300"><li>Two supplier-shipped products were rejected. Their reported stock does not meet our CJ-controlled fulfilment requirement.</li><li>One earlier product was rejected because CJ warehouse stock was zero.</li><li>The backend recovery gate is complete. Trading remains locked pending separate certification and your trading authorisation.</li></ul><div className="flex flex-wrap gap-3"><Link className={link} href="/cockpit/products">Review products</Link><Link className={link} href="/cockpit/commerce/transactions">Inspect transactions</Link></div></section>
 <section className={panel}><h2 className="text-xl font-semibold">Latest product decision</h2><p className="mt-3">{selected?.name}</p><p className="my-3 text-slate-300">Rejected: the supplier manages and ships this mirror. Its inventory count does not establish CJ-controlled fulfilment. We are moving on, not repeating this investigation.</p>{selected&&<Link className={link} href={'/cockpit/products/'+selected.id}>Understand this candidate</Link>}<p className="mt-4 text-sm text-slate-300">Decision recorded {data.decisionsAt}. {data.screeningStatus}</p><div className="mt-4"><DateNote at={data.snapshotAt}/></div><p className="mt-2 text-sm text-slate-400">Latest saved checkpoint, not a complete activity feed since your last visit.</p></section>
 <section className={panel}><h2 className="text-xl font-semibold">Pillow</h2><p className="mt-3">Not born · Commerce locked</p><p className="mt-2 text-slate-300">Saved recommendation: reject these three products under the launch rules. Live activity and unattended operation are not verified here. This is a recorded screening decision, not a claim that Pillow is running the business.</p><Link className={link} href="/cockpit/development/pillow">Open Pillow</Link></section>
 <section id="health" className={panel}><h2 className="text-xl font-semibold">Empire health</h2><LiveRuntime/><Link className={link} href="/cockpit/assurance">Inspect live Assurance and accounting</Link><ul className="mt-4 space-y-4"><li><strong className="text-amber-200">CJ — saved read succeeded</strong><p>Observed {data.snapshotAt}. Not a live connection check.</p></li><li><strong className="text-amber-200">Amazon — qualification incomplete</strong><p>{data.amazon.status} Observed {data.amazon.observedAt}.</p></li><li><strong className="text-red-300">Production — historical checkpoint</strong><p>{data.production.status} Last saved runtime check {data.production.observedAt}.</p></li><li><strong className="text-slate-300">Other services — unknown</strong><p>Current hosting, database, queue, recovery and backup health are not measured by this view.</p></li></ul><p className="mt-4 text-sm text-amber-200">The production checkpoint above is historical. It does not describe the current deployment. Transport availability does not establish business readiness: Pillow remains NOT_BORN and commerce remains LOCKED.</p></section>
 <section className={panel}><h2 className="text-xl font-semibold">Money / cost control</h2><p className="mt-3">Sales, settled profit, platform bills and AI usage are not reconciled in this view. Unknown does not mean zero.</p><p className="mt-2 text-slate-300">No candidate has a verified profit projection. The transaction demonstration separates projected costs from actual accounting; it is not proof of live business revenue.</p></section>
 <section className={panel}><h2 className="text-xl font-semibold">Owner controls</h2><Link className={link} href="/cockpit/advisor">King’s Advisor communications</Link><p className="my-3">Approval and starting new trade are unavailable until product evidence, certification and your separate trading authorisation are complete.</p><button disabled className="min-h-11 rounded border px-4 opacity-50">Trading locked</button><p className="mt-3 text-sm text-slate-400">This read-only view cannot pause or stop a running process. It does not claim to be an emergency stop.</p></section>
 </div>;}
export function OwnerProducts(){const {data,error,retry}=useEvidence();const [filter,setFilter]=useState("all");if(!data)return <Loading error={error} retry={retry}/>;return <div className="space-y-5"><h1 className="text-3xl font-semibold">Products</h1><p className="text-slate-300">{data.candidates.filter(c=>c.qualified).length} qualified · {data.candidates.filter(c=>c.decision==='INVESTIGATE').length} investigating · {data.candidates.filter(c=>c.decision==='REJECT').length} rejected in this saved review. No purchases or listings are authorised.</p><section className={panel}><h2 className="font-semibold">Product pipeline</h2><p className="my-3">{data.candidates.length} discovered → screened. No approval candidate. Published listings and live inventory are not verified by this review.</p><label className="text-sm" htmlFor="product-stage">Show stage</label><select id="product-stage" className="ml-3 min-h-11 rounded border border-white/20 bg-[#071014] px-3" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All reviewed</option><option value="REJECT">Rejected</option><option value="INVESTIGATE">Investigating</option><option value="qualified">Qualified</option></select></section><DateNote at={data.snapshotAt}/>{data.candidates.filter(c=>filter==='all'||(filter==='qualified'?c.qualified:c.decision===filter)).length===0&&<p role="status">No products in this stage.</p>}{[...data.candidates].filter(c=>filter==='all'||(filter==='qualified'?c.qualified:c.decision===filter)).sort((a,b)=>Number(b.selected)-Number(a.selected)).map(c=><article key={c.id} className={panel}><p className="text-sm text-amber-200">{c.decision==='REJECT'?'Rejected':'Needs investigation'}</p><h2 className="my-2 text-xl font-semibold">{c.name}</h2><p className="text-slate-300">{c.recommendation}</p><p className="my-3">Supplier quote: {c.fields.find(f=>f.label==='Supplier price')?.value} · Profit: unknown</p><Link className={link} href={'/cockpit/products/'+c.id}>Review {c.selected?'mirror':c.decision==='REJECT'?'rejected product':'storage tower'}</Link></article>)}</div>;}
export function OwnerCandidate({id}:{id:string}){const {data,error,retry}=useEvidence();if(!data)return <Loading error={error} retry={retry}/>;const c=data.candidates.find(x=>x.id===id);if(!c)return <div><h1 className="text-2xl">Product not found</h1><Link className={link} href="/cockpit/products">Back to products</Link></div>;return <div className="space-y-5"><Link href="/cockpit/products" className="text-amber-200">← Products</Link><h1 className="break-words text-2xl font-semibold">{c.name}</h1><section className={panel}><h2 className="text-xl font-semibold">{c.decision==='REJECT'?'Pillow: reject':'Pillow: do not approve yet'}</h2><p className="mt-3">{c.recommendation}</p><p className="mt-3 text-amber-200">{c.warning}</p><p className="mt-3 text-sm text-slate-400">{c.recommendationSource}</p><p className="mt-4">King: {c.kingDecision}</p><button disabled aria-describedby="approval-reason" className="mt-3 min-h-11 rounded border px-4 opacity-50">Approve — locked</button><p id="approval-reason" className="mt-2 text-sm text-slate-400">No approval is recorded. This read-only page cannot authorise trade.</p></section><DateNote at={c.observedAt}/><section className={panel}><h2 className="text-xl font-semibold">Product and economics</h2><dl className="mt-4 divide-y divide-white/10">{c.fields.map(f=><div key={f.label} className="py-3"><dt className="text-sm text-slate-300">{f.label}</dt><dd className="mt-1 break-words font-medium">{f.value}</dd><dd className="mt-1 text-xs uppercase tracking-wide text-amber-200">{f.kind}</dd><dd className="mt-1 text-sm text-slate-400">{f.note}</dd><dd className="mt-1 text-xs text-slate-500">Source: {f.source} · {f.kind==='provider-observed'?c.observedAt:'Based on this saved assessment'}</dd></div>)}</dl></section><details className={panel}><summary className="cursor-pointer py-2 font-semibold">Inspect evidence</summary><p className="my-3 text-sm text-slate-300">Saved authenticated CJ observations. Opening this section makes no provider call. Provider statements are evidence, not guarantees of fulfilment or profit.</p>{c.sources.map((s,i)=><div key={s.hash} className="my-4 border-t border-white/10 pt-3 text-sm"><p>Receipt {i+1} · {s.at}</p><p className="mt-2 break-all text-slate-400">{s.request}</p><p className="mt-2 break-all text-slate-400">Provider receipt: {s.requestId}</p><p className="mt-2 break-all text-slate-500">SHA-256: {s.hash}</p></div>)}</details></div>;}
