'use client';
import {useState} from 'react';
import Link from 'next/link';
import {AssuranceRelease} from './AssuranceRelease';
import {AssuranceReconciliation} from './AssuranceReconciliation';
import {useAssurance} from '@/lib/owner/useAssurance';
import {activeIncident,type OwnerCommand,type Approval} from '@/lib/owner/assurance-contract';
const panel='rounded-xl border border-white/15 bg-white/[0.03] p-4 sm:p-6';
const button='inline-flex min-h-11 items-center justify-center rounded-lg border border-amber-300/50 px-4 py-2 text-sm font-medium text-amber-100 disabled:cursor-not-allowed disabled:opacity-40';
const at=(v:number|undefined|null)=>v?new Date(v).toLocaleString():'Not established';
const label=(s:string)=>s.replaceAll('_',' ').toLowerCase();
const text=(v:unknown,fallback='Not established')=>typeof v==='string'?v:fallback;
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:6}).format(n/1e6);
function Status({value}:{value:string}){return <strong className={'inline-block rounded-full border px-3 py-1 text-sm '+(['HEALTHY','VERIFIED','RECOVERED','AVAILABLE'].includes(value)?'border-emerald-300/40 text-emerald-200':'border-amber-300/40 text-amber-200')}>{label(value)}</strong>;}
function ApprovalCard({approval,summary,attempts,disabled,onAction}:{approval:Approval;summary:string;attempts:number;disabled:boolean;onAction:(type:OwnerCommand['type'],ids:{approvalId:string})=>void}){
 const [reviewing,setReviewing]=useState(false);
 const complete=!!approval.proposedAction&&!!approval.approvalReason&&!!approval.consequences?.approve;
 return <article className="mt-4 rounded-lg border border-amber-300/40 p-4"><h3 className="text-lg font-semibold">{approval.title??'Recovery decision required'}</h3><p className="mt-2">{summary}</p>
  <dl className="mt-3 space-y-3"><div><dt className="text-sm text-slate-400">Impact</dt><dd>{approval.impact??summary}</dd></div><div><dt className="text-sm text-slate-400">Already attempted</dt><dd>{approval.alreadyDone??`${attempts} recovery attempts recorded.`}</dd></div><div><dt className="text-sm text-slate-400">Proposed remedy</dt><dd>{approval.proposedAction??'Proposal details unavailable; approval is disabled.'}</dd></div><div><dt className="text-sm text-slate-400">Why your approval is needed</dt><dd>{approval.approvalReason??'Authority requirement not established.'}</dd></div><div><dt className="text-sm text-slate-400">If approved</dt><dd>{approval.consequences?.approve??'Consequences not established.'}</dd></div><div><dt className="text-sm text-slate-400">If no decision is made</dt><dd>{approval.consequences?.inaction??'The requested recovery remains awaiting authority.'}</dd></div></dl>
  <p className="mt-3 text-sm text-slate-300">Proposal expires {at(approval.expiresAt)}. Approval applies once to this recorded remedy and revision.</p>
  {reviewing?<div className="mt-4 rounded border border-amber-200 p-3"><p className="font-semibold">Approve this exact recovery?</p><p className="my-2">{approval.proposedAction}</p><div className="flex flex-wrap gap-3"><button className={button} disabled={disabled||!complete} onClick={()=>{onAction('approve',{approvalId:approval.id});setReviewing(false);}}>Confirm approval</button><button className={button} onClick={()=>setReviewing(false)}>Cancel</button></div></div>:<div className="mt-4 flex flex-wrap gap-3"><button className={button} disabled={disabled||!complete} onClick={()=>setReviewing(true)}>Review approval</button><button className={button} disabled={disabled} onClick={()=>onAction('reject',{approvalId:approval.id})}>Reject remedy</button><button className={button} disabled={disabled} onClick={()=>onAction('defer',{approvalId:approval.id})}>Defer decision</button></div>}
  <p className="mt-3 text-sm text-slate-400">Reject: {approval.consequences?.reject??'No approval is granted.'} Defer: {approval.consequences?.defer??'Recovery remains blocked pending a new decision.'}</p><details className="mt-3 text-xs text-slate-400"><summary className="cursor-pointer py-2">Proposal identity</summary><p className="break-all">{approval.id} · {approval.runbookId} / {approval.runbookVersion} · {approval.revision}</p></details>
 </article>;
}
export function OwnerAssurance(){
 const {data,error,now,fresh,refresh,act,engineering,busy,pending,receipt,message,reconcile}=useAssurance();
 const [filter,setFilter]=useState('active');const cp=data?.controlPlane;
 const disabled=!fresh||busy||!!pending;
 const incidents=cp?.incidents??[],approvals=cp?.approvals.filter(a=>a.decision==='PENDING'&&!a.consumed)??[];
 const advisor=data?.advisor;const tasks=Array.isArray(advisor?.tasks)?advisor.tasks.filter(t=>!!t&&typeof t==='object') as Record<string,unknown>[]:[];
 return <div className="space-y-5 break-words"><Link className="inline-flex min-h-11 items-center text-amber-200" href="/cockpit">← Executive Home</Link>
  <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-amber-200">EmpireAI operations</p><h1 className="text-3xl font-semibold">Assurance</h1></div><Status value={fresh?cp!.status:'UNVERIFIED'}/></div>
  <section className={panel} aria-label="Operational summary"><h2 className="text-xl font-semibold">{!fresh?'Current health is not established':cp!.summary.ownerActionRequired?'Your decision is needed':cp!.summary.activeIncidents?'Recovery and investigation in progress':'Monitoring your operations'}</h2>
   <p className="mt-2 text-slate-300">{!fresh?(error?'Evidence refresh failed. Saved observations remain below and may be out of date.':'Monitoring is overdue or the operational control plane is unavailable. Saved observations are not current health.'):'Assurance detects operational faults, applies authorised remedies and verifies restoration.'}</p>
   <div className="mt-4 grid grid-cols-2 gap-4 sm:grid-cols-4">{[['Active incidents',cp?.summary.activeIncidents],['Verified automatic recoveries',cp?.summary.automaticallyRecovered],['Owner decisions',cp?.summary.ownerActionRequired],['Monitoring',cp?.monitor.fresh?'Fresh':'Unverified']].map(([name,value])=><div key={name}><p className="text-sm text-slate-400">{name}</p><p className="mt-1 text-xl font-semibold">{value??'Unknown'}</p></div>)}</div>
   <p className="mt-4 text-sm text-slate-400">Observed {at(cp?.observedAt??data?.observedAt)} · Monitor heartbeat {at(cp?.monitor.heartbeat?.at)} · Updates every 15 seconds. Viewing this page does not start paid inference.</p>
   <div className="mt-4 flex flex-wrap gap-3"><button className={button} onClick={()=>void refresh()}>Refresh view</button><button className={button} disabled={disabled} onClick={()=>act('health_check')}>Run health check</button><button className={button} disabled={disabled} onClick={()=>act(cp?.paused.paused?'resume':'pause')}>{cp?.paused.paused?'Resume safe recovery':'Pause safe recovery'}</button></div>
   <p className="mt-2 text-sm text-slate-300">{cp?.paused.paused?'Safe recovery is paused.':'Eligible safe recovery is enabled when authority permits.'} Monitoring and constitutional safety remain active. These controls cannot grant Birth or unlock commerce.</p>
  </section>
  {(message||receipt||pending)&&<section className={panel} aria-label="Action receipt"><p role="status">{message}</p>{pending&&<><p className="mt-2 break-all text-sm">Pending receipt: {pending.id}. A lost response does not establish failure.</p><button className={button+' mt-3'} disabled={busy||!fresh} onClick={reconcile}>Reconcile same action</button></>}{receipt&&<p className="mt-2 break-all text-sm text-slate-300">{label(receipt.status)} · {at(receipt.at)} · Receipt {receipt.id}</p>}</section>}
  <section id="owner-actions" className={approvals.length?panel+' border-amber-300/60 bg-amber-300/10':panel} aria-labelledby="owner-actions-heading"><h2 id="owner-actions-heading" className="text-xl font-semibold">Owner action {approvals.length?`· ${approvals.length} pending`:''}</h2>
   {!approvals.length?<p className="mt-2">{fresh?'No pending approvals in this snapshot. Unresolved incidents are listed below.':'Pending owner actions are not currently verified.'}</p>:approvals.map(a=><ApprovalCard key={a.id} approval={a} summary={incidents.find(i=>i.id===a.incidentId)?.summary??'Incident evidence unavailable'} attempts={incidents.find(i=>i.id===a.incidentId)?.attempts??0} disabled={disabled||a.expiresAt<=now||a.revision!==cp?.revision} onAction={act}/>)}
  </section>
  <section className={panel}><h2 className="text-xl font-semibold">Functional health</h2><p className="mt-2 text-slate-300">Each status reflects its recorded probe. Missing or stale checks do not establish readiness.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{(cp?.components??[]).map(c=><article className="rounded-lg border border-white/15 p-4" key={c.id}><h3 className="font-semibold">{label(c.capability)}</h3><div className="mt-2"><Status value={fresh?c.status:'UNVERIFIED'}/></div><p className="mt-2 text-sm">{c.summary}</p><p className="mt-2 text-xs text-slate-400">Observed {at(c.observedAt)}</p></article>)}{!cp?.components.length&&<p>No current functional probe evidence available.</p>}</div></section>
  <section className={panel}><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-semibold">Incidents and recovery</h2><label className="text-sm">Show <select className="ml-2 min-h-11 rounded border border-white/20 bg-[#071014] px-3" value={filter} onChange={e=>setFilter(e.target.value)}><option value="active">Active incidents</option><option value="all">All recorded incidents</option></select></label></div>
   {incidents.filter(i=>filter==='all'||activeIncident(i)).length===0&&<p className="mt-3">No incidents in this view. This is not a claim of complete monitoring coverage.</p>}
   {incidents.filter(i=>filter==='all'||activeIncident(i)).map(i=><article className="mt-4 rounded-lg border border-white/15 p-4" key={i.id}><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">{label(i.capability)} · {label(i.severity)}</h3><Status value={i.status}/></div><p className="mt-3">{i.summary}</p><p className="mt-2 text-sm text-slate-300">Diagnosis: {label(i.classification)} · {i.attempts} recovery attempts · {i.recurrence} observations</p>{i.limitation&&<p className="mt-2 text-amber-200">{i.limitation}</p>}<p className="mt-2 text-sm text-slate-400">First detected {at(i.firstAt)} · Latest {at(i.lastAt)} · Function verified {at(i.verifiedAt)}</p>
    {activeIncident(i)&&i.runbookId&&<button className={button+' mt-3'} disabled={disabled} onClick={()=>act('retry',{incidentId:i.id})}>Request eligible recovery</button>}
    <details className="mt-3"><summary className="min-h-11 cursor-pointer py-3 text-sm">Recovery receipts and original identity</summary><p className="break-all text-xs text-slate-400">Incident {i.id} · Revision {i.revision}</p>{cp?.recoveries.filter(r=>r.incidentId===i.id).map(r=><div className="mt-3 border-t border-white/10 pt-3" key={r.id}><Status value={r.status}/><p className="mt-2 text-sm">{label(r.runbookId)} · Actor {r.actor} · Started {at(r.startedAt)} · Completed {at(r.completedAt)}</p>{r.error&&<p className="text-amber-200">{label(r.error)}</p>}<p className="mt-2 break-all text-xs text-slate-400">Receipt {r.id}</p></div>)}</details>
   </article>)}
  </section>
  <section className={panel}><h2 className="text-xl font-semibold">Deployment coordination</h2>{cp?.lease?<><p className="mt-3"><Status value={cp.lease.status}/></p><p className="mt-2">Change owner: {cp.lease.ownerId}. {cp.lease.status==='ACTIVE'?'Conflicting recovery is deferred while production ownership is active.':'The recorded deployment lease is no longer active.'}</p><p className="mt-2 text-sm">Scope: {cp.lease.scope.join(', ')} · Expires {at(cp.lease.expiresAt)}</p><p className="mt-2 break-all text-xs text-slate-400">{cp.lease.id} · {cp.lease.revision}</p></>:<p className="mt-2">{fresh?'No deployment lease recorded in this snapshot.':'Deployment ownership is not currently verified.'}</p>}</section>
  <section className={panel}><h2 className="text-xl font-semibold">King’s Advisor collaboration</h2><p className="mt-2">Invocation: {text(advisor?.mechanism)} · {text(advisor?.invocation,'Unavailable or unverified')}</p><p className="mt-2 text-sm text-slate-300">Interactive ChatGPT wake-up: {text(advisor?.directInteractiveWakeup,'Unverified')}. An API Advisor is a separate execution path. Configuration availability does not prove a completed action.</p><p className="mt-2">Read bridge: {text(advisor?.readBridge)} · Durable result return: {text(advisor?.writeback)}</p>{tasks.map(t=><div className="mt-3 rounded border border-white/15 p-3" key={text(t.id)}><p>{text(t.status)} · {text(t.stage)}</p><p className="mt-1 break-all text-xs text-slate-400">Task {text(t.id)} · Incident {text(t.incidentId)}</p>{typeof t.error==='string'&&<p className="mt-2 text-amber-200">{t.error}</p>}</div>)}</section>
  <AssuranceReconciliation data={data}/>
  {data?.accounting&&<section className={panel}><h2 className="text-xl font-semibold">Inference accounting</h2><dl className="mt-4 grid gap-4 sm:grid-cols-3">{[['Held reservations',money(data.accounting.heldMicroUsd)],['Recorded usage estimates',money(data.accounting.recordedEstimateMicroUsd)],['Provider invoices',data.accounting.invoiceActualMicroUsd===null?`Unknown · ${data.accounting.invoiceUnknownCount} unreconciled`:money(data.accounting.invoiceActualMicroUsd)]].map(([name,value])=><div key={name}><dt className="text-sm text-slate-400">{name}</dt><dd className="mt-1">{value}</dd></div>)}</dl><p className="mt-3 text-sm text-slate-300">Reservations and estimates are not settled invoices. This view does not replace the future Cost Centre.</p></section>}
  <AssuranceRelease data={data} disabled={disabled} send={engineering}/>
  <details className={panel}><summary className="min-h-11 cursor-pointer py-2 text-lg font-semibold">Coverage and durable history</summary><div className="mt-3 space-y-3">{data?.coverage?.map(c=><div className="border-t border-white/10 pt-3" key={c.source}><p>{label(c.source)} · {c.status}</p><p className="text-sm text-slate-300">{c.reason}</p><p className="break-all text-xs text-slate-400">{c.evidenceReference??'No evidence reference'}</p></div>)}</div><h3 className="mt-5 font-semibold">Recent operational events</h3><ol className="mt-3 space-y-2">{cp?.events.map(e=><li className="text-sm" key={e.seq}>{at(e.at)} · {label(e.type)} · #{e.seq}</li>)}</ol><h3 className="mt-5 font-semibold">Mission checkpoints</h3>{cp?.checkpoints.map(c=><p className="mt-2 break-all text-sm" key={c.id}>{c.id} · {c.state} · {at(c.at)}</p>)}</details>
 </div>;
}
