'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {parseAccounting,type Accounting} from '@/lib/owner/accounting-evidence';
const money=(v:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:6}).format(v/1e6);
export function OwnerMoney(){
 const [accounting,setAccounting]=useState<Accounting|null>(null),[failed,setFailed]=useState(false);
 useEffect(()=>{let active=true;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);
 void fetch('/api/owner/assurance',{cache:'no-store',signal:controller.signal}).then(async r=>{if(!r.ok)throw Error();return parseAccounting((await r.json()).accounting);}).then(a=>{if(active)setAccounting(a);}).catch(()=>{if(active)setFailed(true);}).finally(()=>clearTimeout(timer));
 return()=>{active=false;controller.abort();clearTimeout(timer);};},[]);
 const panel='rounded-xl border border-white/15 bg-white/[0.02] p-5';
 return <div className="space-y-5"><h1 className="text-3xl font-semibold">Cost Centre</h1><p>Infrastructure and AI expenditure are separate from transaction profit. Unknown amounts are not zero. All views are read-only.</p>
 <section className={panel}><h2 className="text-xl font-semibold">Operating expenditure</h2><p className="mt-2 text-slate-300">Verified bills and a complete dated expense ledger are not connected to this view. MTD means the current calendar month; YTD means the current calendar year. Neither period can be inferred from the commissioning allowance.</p>
 <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><caption className="sr-only">Month-to-date and year-to-date expenditure availability</caption><thead><tr><th className="py-2">Cost category</th><th>MTD</th><th>YTD</th></tr></thead><tbody>{['Infrastructure / hosting / storage','Fixed subscriptions and plans','Variable usage outside AI','AI provider charges'].map(label=><tr key={label} className="border-t border-white/10"><th className="py-3 pr-3 font-normal">{label}</th><td className="pr-3">Unknown</td><td>Unknown</td></tr>)}</tbody></table></div><p className="text-sm text-slate-400">Categories require invoice attribution before aggregation; infrastructure plans can include fixed and variable charges. No total is claimed.</p></section>
 <section className={panel}><h2 className="text-xl font-semibold">AI commissioning allowance</h2><p className="mt-2">Latest retained internal accounting observation. This is a bounded commissioning ledger, not complete provider billing or MTD/YTD expenditure.</p><div aria-live="polite">{failed?<p className="mt-3" role="alert">Accounting evidence unavailable. Allowance and spending are unknown.</p>:!accounting?<p className="mt-3">Reading accounting evidence…</p>:<dl className="mt-4 grid gap-3 sm:grid-cols-2">{[['Ceiling',money(accounting.ceilingMicroUsd)],['Held reservations',money(accounting.heldMicroUsd)],['Remaining allowance',money(accounting.remainingMicroUsd)],['Recorded estimates',money(accounting.recordedEstimateMicroUsd)],['Invoice actual',accounting.invoiceActualMicroUsd===null?'Unknown':money(accounting.invoiceActualMicroUsd)],['Unreconciled invoices',String(accounting.invoiceUnknownCount)],['Observed at',accounting.observedAt]].map(([label,value])=><div key={label}><dt className="text-slate-400">{label}</dt><dd className="break-words">{value}</dd></div>)}</dl>}</div><p className="mt-3 text-sm text-slate-300">Held reservations and recorded estimates are not settled invoices. This observation grants no additional spending authority.</p><Link href="/cockpit/assurance" className="mt-3 inline-flex min-h-11 items-center text-amber-200">Inspect accounting Assurance</Link></section>
 <section className={panel}><h2 className="text-xl font-semibold">Operational P&amp;L</h2><p className="mt-2 text-slate-300">Authoritative order, supplier, refund and settlement records are not yet reconciled. Delivery alone does not establish settled profit. These transaction values exclude infrastructure spending.</p><dl className="mt-4 divide-y divide-white/10">{['Revenue / marketplace settlements','Supplier cost','Shipping','Tax / duty','Marketplace fees','Supplier / payment / currency fees','Refunds / returns','Realised contribution / profit'].map(label=><div key={label} className="flex flex-wrap justify-between gap-3 py-3"><dt>{label}</dt><dd>Unknown</dd></div>)}</dl><Link href="/cockpit/commerce/transactions" className="mt-3 inline-flex min-h-11 items-center text-amber-200">Inspect stored orders and money status</Link></section>
 </div>;
}
