'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {summarizeAssuranceCoverage,displayAssuranceCheck} from '@/lib/owner/assurance-coverage';
type Check={source:string;classification:string;status:string;reason?:string;observedAt?:number;evidenceReference:string|null;missing?:number;mismatched?:number};
type Evidence={demonstration?:{scope:string;history:{status:string;observedAt:number;sourceChangedAt:number}[]};observedAt:number;status:string;scope:string;nextCycleAt:number;dueAt:number|null;lastCompletedAt:number|null;lastSuccessfulAt:number|null;watchdog:{fresh:boolean;observedAt:number|null};coverage:Check[];findings:{id:string;source:string;severity:string;status:string;first_at:number;last_at:number;resolved_at:number|null;detail:string}[];cycles:{id:string;scheduledAt:number;completedAt:number|null}[];accounting:{ceilingMicroUsd:number;heldMicroUsd:number;remainingMicroUsd:number;recordedEstimateMicroUsd:number;invoiceActualMicroUsd:number|null;invoiceUnknownCount:number;observedAt:string}};
const at=(v:number|null|undefined)=>v?new Date(v).toLocaleString():'Not established';
const usd=(v:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:6}).format(v/1e6);
export function OwnerAssurance(){
 const [demoMessage,setDemoMessage]=useState(''),[busy,setBusy]=useState(false);
 async function demo(action:string){setBusy(true);try{const r=await fetch('/api/owner/assurance-demo/'+action,{method:'POST'});if(!r.ok)throw Error();setDemoMessage('Change recorded. Awaiting the independent inspector and next refresh (up to one minute).');}catch{setDemoMessage('Demonstration unavailable; no success is claimed.');}finally{setBusy(false);}}
 const [data,setData]=useState<Evidence|null>(null),[error,setError]=useState(false),[now,setNow]=useState(0);
 useEffect(()=>{let stopped=false;let controller:AbortController;
  const refresh=async()=>{controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);try{const r=await fetch('/api/owner/assurance',{cache:'no-store',signal:controller.signal});if(!r.ok)throw Error();const value=await r.json();if(!stopped){setData(value);setError(false);}}catch{if(!stopped)setError(true);}finally{clearTimeout(timer);}};
  void refresh();const poll=setInterval(()=>void refresh(),30000),clock=setInterval(()=>setNow(Date.now()),1000);return()=>{stopped=true;controller?.abort();clearInterval(poll);clearInterval(clock);};
 },[]);
 const stale=!!data&&(!Number.isFinite(data.observedAt)||(now>0&&(data.observedAt>now||now-data.observedAt>90000)));
 const coverage=summarizeAssuranceCoverage(data?.coverage,!!data&&now>0&&!error&&!stale&&data.watchdog.fresh);
 const openFindings=data?.findings.filter(f=>f.status==='OPEN')??[];
 const state=error||stale?'UNKNOWN — evidence refresh unavailable':data?.status??'Checking durable evidence…';
 const panel='rounded-xl border border-white/15 bg-white/[0.03] p-4 sm:p-6';
 return <div className="space-y-5 break-words"><Link className="inline-flex min-h-11 items-center text-amber-200" href="/cockpit">← Executive Home</Link><h1 className="text-3xl font-semibold">Independent Assurance</h1>
 <section className={panel} aria-live="polite"><h2 className="text-xl font-semibold">{state}</h2><p className="mt-3 text-lg font-medium">{coverage.current?`${coverage.passed}/${coverage.required} independent domains passed`:'Current coverage unknown'}</p>{coverage.current&&<p className="mt-1 text-sm text-slate-300">{coverage.failed} failed · {coverage.unverified} unverified. This is Assurance coverage, not Birth readiness.</p>}{data&&<p className="mt-2 text-sm text-slate-300">{openFindings.length} open findings · {openFindings.filter(f=>f.severity==='CRITICAL').length} critical in this bounded view.</p>}<p className="mt-2">{data?.scope??'Current coverage is unknown until evidence loads.'}</p><p className="mt-2 text-slate-300">Read-only owner view. No trading or inference is triggered. Updates every 30 seconds.</p>{data&&<dl className="mt-4 grid gap-3 sm:grid-cols-2">{[['Evidence read',at(data.observedAt)],['Latest completed cycle',at(data.lastCompletedAt)],['Previous completed cycle',at(data.cycles.filter(c=>c.completedAt!==null)[1]?.completedAt)],['Latest fully successful cycle',at(data.lastSuccessfulAt)],['Next scheduled cycle',at(data.nextCycleAt)],['Due cycle',at(data.dueAt)],['Independent watchdog',`${data.watchdog.fresh?'Fresh':'Overdue / unknown'} · ${at(data.watchdog.observedAt)}`]].map(([label,value])=><div key={label}><dt className="text-sm text-slate-400">{label}</dt><dd>{value}</dd></div>)}</dl>}</section>
 {data&&<><details className={panel}><summary className="min-h-11 cursor-pointer text-lg font-semibold">Isolated verification demonstration</summary><p className="mt-2">This changes only a dedicated test record. It never changes orders, saved conversations, accounting or authority. The permanent inspector records the result independently of Pillow.</p><p className="mt-3 font-semibold">{error||stale||!data.watchdog.fresh?'UNKNOWN — independent observation overdue':data.demonstration?.history[0]?.status??'Not yet observed'}</p><div className="mt-3 flex flex-wrap gap-3"><button disabled={busy} className="min-h-11 rounded border border-amber-300/40 px-4 py-2 disabled:opacity-50" onClick={()=>void demo('inject')}>Introduce test discrepancy</button><button disabled={busy} className="min-h-11 rounded border border-white/30 px-4 py-2 disabled:opacity-50" onClick={()=>void demo('correct')}>Correct test discrepancy</button></div><p role="status" className="mt-3">{demoMessage}</p><ul className="mt-3 space-y-2">{data.demonstration?.history.map(h=><li key={h.observedAt}>{h.status} · Independently observed {at(h.observedAt)}</li>)}</ul><p className="mt-3 text-sm text-slate-400">{data.demonstration?.scope} · Overall Assurance coverage is shown separately above.</p></details><section className={panel}><h2 className="text-xl font-semibold">Findings requiring attention</h2><p className="mt-2">Repair status is reported by retained findings: OPEN needs investigation; RESOLVED records recovery, not proof of complete coverage.</p><p className="mt-2">{data.findings.filter(f=>f.status==='OPEN').length} open in this bounded view. Findings remain recorded after recovery.</p>{data.findings.length===0?<p className="mt-3">No findings recorded. Unchecked sources remain unverified.</p>:data.findings.map(f=><details key={f.id} className="mt-3 border-t border-white/15 pt-3"><summary className="cursor-pointer py-2">{f.severity} · {f.status} · {f.source}</summary><p className="my-2">Observed {at(f.first_at)} · Latest {at(f.last_at)} · Resolved {at(f.resolved_at)}</p><pre className="whitespace-pre-wrap break-all text-sm">{f.detail}</pre><p className="mt-2 break-all text-xs text-slate-400">Evidence: {f.id}</p></details>)}</section>
 <section className={panel}><h2 className="text-xl font-semibold">Source coverage and evidence</h2><p className="mt-2 text-slate-300">A passing internal check does not certify a live marketplace integration. No external source is marked verified here.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{data.coverage.map(c=><details className="rounded border border-white/15 p-3" key={c.source}><summary className="cursor-pointer py-2">{c.source}<br/><strong>{displayAssuranceCheck(c.status,coverage.current)}</strong></summary><p className="mt-2">Integration: {c.classification}</p><p>Observed: {at(c.observedAt)}</p><p>Age: {c.observedAt?Math.max(0,Math.floor(((now||data.observedAt)-c.observedAt)/1000))+' seconds':'Unknown'}</p><p>{c.reason??'Comparison receipt available in the recorded cycle.'}</p>{c.missing!==undefined&&<p>Missing: {c.missing} · Mismatched: {c.mismatched??0}</p>}<p className="mt-2 break-all text-xs text-slate-400">Evidence: {c.evidenceReference??'None'}</p></details>)}</div></section>
 <section className={panel}><h2 className="text-xl font-semibold">Commissioning money</h2><dl className="mt-4 grid gap-3 sm:grid-cols-2">{[['Ceiling',usd(data.accounting.ceilingMicroUsd)],['Held reservations',usd(data.accounting.heldMicroUsd)],['Remaining allowance',usd(data.accounting.remainingMicroUsd)],['Recorded estimates',usd(data.accounting.recordedEstimateMicroUsd)],['Invoice actual',data.accounting.invoiceActualMicroUsd===null?`Unknown (${data.accounting.invoiceUnknownCount} unreconciled)`:usd(data.accounting.invoiceActualMicroUsd)],['Accounting read',data.accounting.observedAt]].map(([k,v])=><div key={k}><dt className="text-slate-400">{k}</dt><dd>{v}</dd></div>)}</dl><p className="mt-4">Reservations and estimates are not settled invoices. Commercial authority is not increased by this view.</p></section>
 <section className={panel}><h2 className="text-xl font-semibold">Recent cycle history</h2><ul className="mt-3 space-y-3">{data.cycles.map(c=><li className="border-t border-white/10 pt-3" key={c.id}>Scheduled {at(c.scheduledAt)}<br/>Completed {at(c.completedAt)}<br/><span className="break-all text-xs text-slate-400">{c.id}</span></li>)}</ul></section></>}
 </div>;
}
