'use client';
import {useEffect,useState} from 'react';
import {parseStoredOrders,type StoredOrders as Evidence} from '@/lib/owner/stored-orders';
export function StoredOrders({refresh=0}:{refresh?:number}){
 const [data,setData]=useState<Evidence|null>(null),[error,setError]=useState(false);
 useEffect(()=>{let active=true;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);
 void fetch('/api/owner/orders',{cache:'no-store',signal:controller.signal}).then(async r=>{if(!r.ok)throw Error();return parseStoredOrders(await r.json());}).then(value=>{if(active){setData(value);setError(false);}}).catch(()=>{if(active)setError(true);}).finally(()=>clearTimeout(timer));
 return()=>{active=false;controller.abort();clearTimeout(timer);};},[refresh]);
 return <section className="space-y-3 rounded-xl border border-white/15 p-4" aria-live="polite"><h2 className="text-lg font-semibold">Stored Amazon orders</h2><p className="text-sm text-stone-300">Read-only provider snapshots, up to 100 stored orders. Opening this view does not sync Amazon or authorise fulfilment. Goods status and money reconciliation are separate.</p>
 {error?<p role="alert">Order evidence unavailable. Order count and financial totals are unknown.</p>:!data?<p>Reading stored orders…</p>:<><p>Import: {data.importStatus?.status??'Unknown — no import receipt'} · Completed: {data.importStatus?.lastCompletedAt??'Not established'} · More pages: {data.importStatus===null?'Unknown':data.importStatus.pagesPending?'Yes':'No'}</p>{data.orders.length===0?<p>No stored order snapshots. This does not establish zero marketplace orders or zero revenue.</p>:data.orders.map(r=><article key={r.orderId} className="space-y-2 rounded border border-white/10 p-3"><h3 className="break-all font-medium">{r.orderId}</h3><p>Goods: {r.fulfillmentStatus??'Unknown'} · Money: unreconciled</p><p>Provider order total: {r.grandTotalCents===null?'Unknown':r.marketplaceId==='ATVPDKIKX0DER'?'US$'+(r.grandTotalCents/100).toFixed(2):'Unknown currency — amount withheld'}. This is not settled revenue.</p><p>Provider updated: {r.lastUpdatedTime} · Historical snapshot; current provider state not verified.</p><details><summary className="min-h-11 cursor-pointer">Source evidence</summary><p className="break-all">Marketplace: {r.marketplaceId}<br/>SHA-256: {r.sourceSha256}</p></details></article>)}</>}
 <p className="text-sm text-amber-200">Operational P&amp;L remains unknown: revenue, supplier cost, shipping, tax, marketplace/supplier fees, refunds/returns and realised contribution require authoritative linked settlement evidence. Infrastructure expenditure is separate.</p></section>;
}
