/** PILLOW-SRCRT-001 — Shared Runtime Certification (Q10-14). Final Q10 acceptance gate. */
export const SHARED_RUNTIME_CERTIFICATION_SYSTEM_PATH =
  "docs/governance/EMPIREAI_SHARED_RUNTIME_CERTIFICATION_SYSTEM.md" as const;
export const SHARED_RUNTIME_CERTIFICATION_ID = "shared-runtime-certification" as const;
export const SRCRT_METADATA_VERSION = "SRCRT-001-v1" as const;
export const SHARED_RUNTIME_CERTIFICATION_REPORT_VERSION = "SRCRT-RPT-v1" as const;
export const SRCRT_MISSION_ID = "Q10-14" as const;
export const SHARED_RUNTIME_CERTIFICATION_RUNTIME_VERSION = "Q10-SRCRT-v1" as const;

export const SHARED_RUNTIME_CERTIFICATION_IDENTITY = {
  workerId: "wkr-shared-runtime-certification-01",
  workerName: "Shared Runtime Certification",
  workerType: "certifier",
  department: "runtime",
  factory: "pillow-shared-runtime-cert",
  role: "role-certifier-shared-runtime-certification",
  reportingLine: ["wkr-shared-runtime-certification-01", "pillow"] as string[],
  skillProfile: [
    "skill-repository-evidence-collection",
    "skill-runtime-worker-probing",
    "skill-integration-verification",
    "skill-production-readiness-assessment",
    "skill-governance-compliance-verification",
    "skill-monitoring-verification",
    "skill-recovery-verification",
    "skill-auditability-verification",
    "skill-certification-decision-gating",
    "skill-shared-runtime-certification-reporting",
  ],
  approvedTools: ["repository_evidence_scanner", "structured_reporting"],
  authorityLevel: "autonomous_worker_decision",
} as const;

export const ENGINE_STATUSES = [
  "idle",
  "connecting",
  "active",
  "collecting_evidence",
  "probing_runtime",
  "verifying_integrations",
  "assessing_readiness",
  "certifying",
  "reporting",
  "validating",
  "failed",
] as const;

export const OPERATIONAL_STATES = ["disconnected", "connected", "active", "failed"] as const;
export const VALIDATION_STATUSES = ["pending", "passed", "partial", "failed"] as const;
export const ENGINE_HEALTH_STATUSES = ["healthy", "degraded", "failed", "standby"] as const;

/** Per-runtime certification statuses — derived strictly from observed evidence. */
export const RUNTIME_CERTIFICATION_STATUSES = [
  "Certified",
  "Partially Certified",
  "Failed Certification",
  "Blocked",
  "Deferred",
] as const;

export const CERTIFICATION_DECISIONS = [
  "Certified",
  "Conditionally_Certified",
  "Not_Certified",
  "Failed",
  "Deferred",
] as const;

export const AUDIT_STATUSES = [
  "draft",
  "evidence_collected",
  "integrations_verified",
  "readiness_assessed",
  "certified",
  "conditionally_certified",
  "not_certified",
  "failed",
  "deferred",
  "submitted",
  "rejected",
  "unknown",
] as const;

/**
 * Q10-01..Q10-13 — the complete Shared Runtime pipeline this mission
 * certifies. Every field is used as repository/runtime evidence; nothing here
 * is invented per-run.
 */
export const Q10_RUNTIME_CATALOG = [
  {
    missionId: "Q10-01",
    runtimeName: "shared-runtime-core",
    subsystemId: "shared-runtime-core",
    modulePath: "pillow/src/shared-runtime-core/",
    enginePath: "pillow/src/shared-runtime-core/engine.ts",
    auditPath: "docs/audits/pillow/q10-01-shared-runtime-core/",
    configPath: "config/shared-runtime-core.config.json",
    governancePath: "docs/governance/EMPIREAI_SHARED_RUNTIME_CORE_SYSTEM.md",
    bridgePath: "backend/src/orchestration/pillow-host/shared-runtime-core-bridge.ts",
    testPath: "pillow/src/validation/tests/shared-runtime-core.test.ts",
    dependencyKey: "sharedRuntimeCore",
    engineVersion: "PILLOW-SRTC-001",
    consumableContractMethod: "getQ1002ConsumableContract",
    expectedDeliverable:
      "Factory/worker registration, shared execution context, cross-factory routing, and Q1002 consumable contract for Q10-02",
  },
  {
    missionId: "Q10-02",
    runtimeName: "pillow-orchestration-runtime",
    subsystemId: "pillow-orchestration-runtime",
    modulePath: "pillow/src/pillow-orchestration-runtime/",
    enginePath: "pillow/src/pillow-orchestration-runtime/engine.ts",
    auditPath: "docs/audits/pillow/q10-02-pillow-orchestration-runtime/",
    configPath: "config/pillow-orchestration-runtime.config.json",
    governancePath: "docs/governance/EMPIREAI_PILLOW_ORCHESTRATION_RUNTIME_SYSTEM.md",
    bridgePath: "backend/src/orchestration/pillow-host/pillow-orchestration-runtime-bridge.ts",
    testPath: "pillow/src/validation/tests/pillow-orchestration-runtime.test.ts",
    dependencyKey: "pillowOrchestrationRuntime",
    /** Corrected from PILLOW-PORT-001 after verifying pillow-orchestration-runtime/engine.ts. */
    engineVersion: "PILLOW-POR-001",
    consumableContractMethod: "getQ1003ConsumableContract",
    expectedDeliverable: "Worker/tool execution orchestration and Q1003 consumable contract for Q10-03",
  },
  {
    missionId: "Q10-03",
    runtimeName: "mission-runtime",
    subsystemId: "mission-runtime",
    modulePath: "pillow/src/mission-runtime/",
    enginePath: "pillow/src/mission-runtime/engine.ts",
    auditPath: "docs/audits/pillow/q10-03-mission-runtime/",
    configPath: "config/mission-runtime.config.json",
    governancePath: "docs/governance/EMPIREAI_MISSION_RUNTIME_SYSTEM.md",
    bridgePath: "backend/src/orchestration/pillow-host/mission-runtime-bridge.ts",
    testPath: "pillow/src/validation/tests/mission-runtime.test.ts",
    dependencyKey: "missionRuntime",
    /** Corrected from PILLOW-MISRT-001 after verifying mission-runtime/engine.ts. */
    engineVersion: "PILLOW-MSR-001",
    consumableContractMethod: "getQ1004ConsumableContract",
    expectedDeliverable: "Mission lifecycle/state tracking and Q1004 consumable contract for Q10-04",
  },
  {
    missionId: "Q10-04",
    runtimeName: "queue-runtime",
    subsystemId: "queue-runtime",
    modulePath: "pillow/src/queue-runtime/",
    enginePath: "pillow/src/queue-runtime/engine.ts",
    auditPath: "docs/audits/pillow/q10-04-queue-runtime/",
    configPath: "config/queue-runtime.config.json",
    governancePath: "docs/governance/EMPIREAI_QUEUE_RUNTIME_SYSTEM.md",
    bridgePath: "backend/src/orchestration/pillow-host/queue-runtime-bridge.ts",
    testPath: "pillow/src/validation/tests/queue-runtime.test.ts",
    dependencyKey: "queueRuntime",
    /** Corrected from PILLOW-QUERT-001 after verifying queue-runtime/engine.ts. */
    engineVersion: "PILLOW-QRT-001",
    consumableContractMethod: "getQ1005ConsumableContract",
    expectedDeliverable: "Work queue lifecycle and Q1005 consumable contract for Q10-05",
  },
  {
    missionId: "Q10-05",
    runtimeName: "memory-runtime",
    subsystemId: "memory-runtime",
    modulePath: "pillow/src/memory-runtime/",
    enginePath: "pillow/src/memory-runtime/engine.ts",
    auditPath: "docs/audits/pillow/q10-05-memory-runtime/",
    configPath: "config/memory-runtime.config.json",
    governancePath: "docs/governance/EMPIREAI_MEMORY_RUNTIME_SYSTEM.md",
    bridgePath: "backend/src/orchestration/pillow-host/memory-runtime-bridge.ts",
    testPath: "pillow/src/validation/tests/memory-runtime.test.ts",
    dependencyKey: "memoryRuntime",
    engineVersion: "PILLOW-MEMRT-001",
    consumableContractMethod: "getQ1006ConsumableContract",
    expectedDeliverable: "Shared memory/context retrieval and Q1006 consumable contract for Q10-06",
  },
  {
    missionId: "Q10-06",
    runtimeName: "api-runtime",
    subsystemId: "api-runtime",
    modulePath: "pillow/src/api-runtime/",
    enginePath: "pillow/src/api-runtime/engine.ts",
    auditPath: "docs/audits/pillow/q10-06-api-runtime/",
    configPath: "config/api-runtime.config.json",
    governancePath: "docs/governance/EMPIREAI_API_RUNTIME_SYSTEM.md",
    bridgePath: "backend/src/orchestration/pillow-host/api-runtime-bridge.ts",
    testPath: "pillow/src/validation/tests/api-runtime.test.ts",
    dependencyKey: "apiRuntime",
    engineVersion: "PILLOW-APIRT-001",
    consumableContractMethod: "getQ1007ConsumableContract",
    expectedDeliverable: "API request lifecycle handling and Q1007 consumable contract for Q10-07",
  },
  {
    missionId: "Q10-07",
    runtimeName: "tool-runtime",
    subsystemId: "tool-runtime",
    modulePath: "pillow/src/tool-runtime/",
    enginePath: "pillow/src/tool-runtime/engine.ts",
    auditPath: "docs/audits/pillow/q10-07-tool-runtime/",
    configPath: "config/tool-runtime.config.json",
    governancePath: "docs/governance/EMPIREAI_TOOL_RUNTIME_SYSTEM.md",
    bridgePath: "backend/src/orchestration/pillow-host/tool-runtime-bridge.ts",
    testPath: "pillow/src/validation/tests/tool-runtime.test.ts",
    dependencyKey: "toolRuntime",
    engineVersion: "PILLOW-TOOLRT-001",
    consumableContractMethod: "getQ1008ConsumableContract",
    expectedDeliverable: "Tool invocation lifecycle and Q1008 consumable contract for Q10-08",
  },
  {
    missionId: "Q10-08",
    runtimeName: "communication-runtime",
    subsystemId: "communication-runtime",
    modulePath: "pillow/src/communication-runtime/",
    enginePath: "pillow/src/communication-runtime/engine.ts",
    auditPath: "docs/audits/pillow/q10-08-communication-runtime/",
    configPath: "config/communication-runtime.config.json",
    governancePath: "docs/governance/EMPIREAI_COMMUNICATION_RUNTIME_SYSTEM.md",
    bridgePath: "backend/src/orchestration/pillow-host/communication-runtime-bridge.ts",
    testPath: "pillow/src/validation/tests/communication-runtime.test.ts",
    dependencyKey: "communicationRuntime",
    engineVersion: "PILLOW-COMRT-001",
    consumableContractMethod: "getQ1009ConsumableContract",
    expectedDeliverable: "Worker-to-worker communication/collaboration and Q1009 consumable contract for Q10-09",
  },
  {
    missionId: "Q10-09",
    runtimeName: "approval-runtime",
    subsystemId: "approval-runtime",
    modulePath: "pillow/src/approval-runtime/",
    enginePath: "pillow/src/approval-runtime/engine.ts",
    auditPath: "docs/audits/pillow/q10-09-approval-runtime/",
    configPath: "config/approval-runtime.config.json",
    governancePath: "docs/governance/EMPIREAI_APPROVAL_RUNTIME_SYSTEM.md",
    bridgePath: "backend/src/orchestration/pillow-host/approval-runtime-bridge.ts",
    testPath: "pillow/src/validation/tests/approval-runtime.test.ts",
    dependencyKey: "approvalRuntime",
    engineVersion: "PILLOW-APVRT-001",
    consumableContractMethod: "getQ1010ConsumableContract",
    expectedDeliverable: "Deterministic approval routing and Q1010 consumable contract for Q10-10",
  },
  {
    missionId: "Q10-10",
    runtimeName: "monitoring-runtime",
    subsystemId: "monitoring-runtime",
    modulePath: "pillow/src/monitoring-runtime/",
    enginePath: "pillow/src/monitoring-runtime/engine.ts",
    auditPath: "docs/audits/pillow/q10-10-monitoring-runtime/",
    configPath: "config/monitoring-runtime.config.json",
    governancePath: "docs/governance/EMPIREAI_MONITORING_RUNTIME_SYSTEM.md",
    bridgePath: "backend/src/orchestration/pillow-host/monitoring-runtime-bridge.ts",
    testPath: "pillow/src/validation/tests/monitoring-runtime.test.ts",
    dependencyKey: "monitoringRuntime",
    engineVersion: "PILLOW-MONRT-001",
    consumableContractMethod: "getQ1011ConsumableContract",
    expectedDeliverable: "Health dashboards/monitoring and Q1011 consumable contract for Q10-11",
  },
  {
    missionId: "Q10-11",
    runtimeName: "recovery-runtime",
    subsystemId: "recovery-runtime",
    modulePath: "pillow/src/recovery-runtime/",
    enginePath: "pillow/src/recovery-runtime/engine.ts",
    auditPath: "docs/audits/pillow/q10-11-recovery-runtime/",
    configPath: "config/recovery-runtime.config.json",
    governancePath: "docs/governance/EMPIREAI_RECOVERY_RUNTIME_SYSTEM.md",
    bridgePath: "backend/src/orchestration/pillow-host/recovery-runtime-bridge.ts",
    testPath: "pillow/src/validation/tests/recovery-runtime.test.ts",
    dependencyKey: "recoveryRuntime",
    engineVersion: "PILLOW-RECRT-001",
    consumableContractMethod: "getQ1012ConsumableContract",
    expectedDeliverable: "Failure detection/recovery workflows and Q1012 consumable contract for Q10-12",
  },
  {
    missionId: "Q10-12",
    runtimeName: "scheduling-runtime",
    subsystemId: "scheduling-runtime",
    modulePath: "pillow/src/scheduling-runtime/",
    enginePath: "pillow/src/scheduling-runtime/engine.ts",
    auditPath: "docs/audits/pillow/q10-12-scheduling-runtime/",
    configPath: "config/scheduling-runtime.config.json",
    governancePath: "docs/governance/EMPIREAI_SCHEDULING_RUNTIME_SYSTEM.md",
    bridgePath: "backend/src/orchestration/pillow-host/scheduling-runtime-bridge.ts",
    testPath: "pillow/src/validation/tests/scheduling-runtime.test.ts",
    dependencyKey: "schedulingRuntime",
    engineVersion: "PILLOW-SCHRT-001",
    consumableContractMethod: "getQ1013ConsumableContract",
    expectedDeliverable: "Recurring/deferred schedule execution and Q1013 consumable contract for Q10-13",
  },
  {
    missionId: "Q10-13",
    runtimeName: "audit-runtime",
    subsystemId: "audit-runtime",
    modulePath: "pillow/src/audit-runtime/",
    enginePath: "pillow/src/audit-runtime/engine.ts",
    auditPath: "docs/audits/pillow/q10-13-audit-runtime/",
    configPath: "config/audit-runtime.config.json",
    governancePath: "docs/governance/EMPIREAI_AUDIT_RUNTIME_SYSTEM.md",
    bridgePath: "backend/src/orchestration/pillow-host/audit-runtime-bridge.ts",
    testPath: "pillow/src/validation/tests/audit-runtime.test.ts",
    dependencyKey: "auditRuntime",
    engineVersion: "PILLOW-AUDRT-001",
    consumableContractMethod: "getQ1014ConsumableContract",
    expectedDeliverable:
      "Immutable append-only audit trail and Q1014 consumable contract for Q10-14 (Shared Runtime Certification)",
  },
] as const;

export const CRITICAL_RUNTIME_IDS = Q10_RUNTIME_CATALOG.map((m) => m.missionId);

export const INTEGRATION_TARGETS = [
  ...Q10_RUNTIME_CATALOG.map((m) => m.subsystemId),
  "worker_registry",
  "worker_lifecycle",
  "executive_reporting_runtime",
  "worker_recovery_system",
] as const;

export const SRCRT_CAPABILITIES = [
  "collect_repository_evidence",
  "probe_runtime_workers",
  "classify_runtime_certification_status",
  "verify_integrations",
  "verify_production_readiness",
  "verify_governance_compliance",
  "verify_monitoring_coverage",
  "verify_recovery_coverage",
  "verify_auditability",
  "verify_executive_reporting",
  "produce_certification_findings",
  "produce_shared_runtime_certification_reports",
  "submit_reports_through_executive_reporting_runtime",
  "expose_q1101_consumable_contract",
  "preserve_complete_traceability",
  "preserve_certification_audit_history",
  "never_fabricate_certification_evidence",
  "never_certify_missing_functionality",
  "never_assume_implementation",
  "never_implement_missing_runtimes",
  "never_modify_runtime_behaviour",
  "never_automatically_fix_failures",
  "never_override_governance",
  "never_override_approved_architecture",
  "never_override_pillow",
  "never_override_grand_king",
  "never_bypass_grand_king_approval",
  "never_implement_q1101_or_later",
  "integrate_shared_runtime_core",
  "integrate_pillow_orchestration_runtime",
  "integrate_mission_runtime",
  "integrate_queue_runtime",
  "integrate_memory_runtime",
  "integrate_api_runtime",
  "integrate_tool_runtime",
  "integrate_communication_runtime",
  "integrate_approval_runtime",
  "integrate_monitoring_runtime",
  "integrate_recovery_runtime",
  "integrate_scheduling_runtime",
  "integrate_audit_runtime",
  "integrate_worker_registry",
  "integrate_worker_lifecycle",
  "integrate_executive_reporting_runtime",
  "integrate_worker_recovery_system",
  "shared_runtime_certification_validation",
  "health_monitoring",
  "recovery_management",
  "final_q10_gate",
] as const;
