/** Work5 evidence subledger: canonical legacy events and inference calls remain immutable sources.
 * This journal records evidence/reconciliation, not payments or a second copy of their totals. */
import {DatabaseSync} from 'node:sqlite';
import {createHash} from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import {z} from 'zod';
const id=z.string().regex(/^[A-Za-z0-9_.:-]{1,160}$/);
const money=z.number().int().nonnegative().max(1e12); // original currency micro-units
const date=z.string().datetime();
const evidence=z.object({kind:z.enum(['INVOICE','PAYMENT','USAGE','BANK','CONTRACT','QUOTE','OUTCOME','OTHER']),reference:z.string().min(3).max(500),sha256:z.string().regex(/^[a-f0-9]{64}$/),observedAt:date,content:z.string().max(24000).optional()}).strict();
const attribution=z.object({project:z.string().max(100),environment:z.string().max(50),workload:z.string().max(100),purpose:z.string().max(300),productId:id.optional(),orderId:id.optional(),supplierId:id.optional(),channel:z.string().max(80).optional(),country:z.string().length(2).optional(),allocationBps:z.number().int().min(0).max(10000).default(10000),allocationReason:z.string().max(300).default('Direct')}).strict();
export const costSchema=z.object({entityId:id,provider:id,service:z.string().min(1).max(120),category:z.enum(['TECHNOLOGY','COGS','ADVERTISING','FEES','REFUNDS','TAX','REVENUE','CAPITAL','LIABILITY','RECEIVABLE']),classification:z.enum(['FIXED','VARIABLE']),stage:z.enum(['ESTIMATED','ACCRUED_UNBILLED','INVOICED','SETTLED','COMMITTED']),amountMicro:money,currency:z.string().regex(/^[A-Z]{3}$/),taxMicro:money.default(0),creditMicro:money.default(0),periodStart:date,periodEnd:date,paymentDate:date.optional(),renewalDate:date.optional(),dueDate:date.optional(),invoiceNumber:z.string().max(120).optional(),quantity:z.number().nonnegative().max(1e12).optional(),unitRateMicro:money.optional(),replaces:id.optional(),sourceIds:z.array(id).max(100).default([]),authenticity:z.enum(['REAL','DEMO','SYNTHETIC','HISTORICAL_FIXTURE']),evidence:z.array(evidence).min(1).max(8),fx:z.object({sgdPerUnit:z.number().positive().max(10000),observedAt:date,reference:z.string().min(3).max(500)}).strict().optional(),attribution}).strict();
const providerSchema=z.object({id,name:z.string().min(1).max(100),category:z.string().max(100),commissioned:z.enum(['YES','NO','UNKNOWN']),mandatory:z.boolean(),billingAccess:z.enum(['AVAILABLE','UNAVAILABLE','MANUAL']),note:z.string().max(500)}).strict();
const budgetSchema=z.object({provider:id,monthlySgdMicro:money,warningPercent:z.number().min(1).max(100),reason:z.string().min(3).max(500)}).strict();
const cashSchema=z.object({account:id,balanceMicro:money,currency:z.string().regex(/^[A-Z]{3}$/),asOf:date,evidence:evidence,fx:costSchema.shape.fx}).strict();
const scalar=z.number().finite().min(0).max(1e9);
export const economicsSchema=z.object({productId:id,orderId:id.optional(),supplierId:id,channel:z.string().min(1).max(80),country:z.string().length(2),currency:z.literal('SGD'),sellingPrice:scalar,productCost:scalar,freight:scalar,fulfilment:scalar,feePercent:z.number().min(0).max(99),paymentPercent:z.number().min(0).max(99),advertising:scalar,refundRate:z.number().min(0).max(1),refundLoss:scalar,duties:scalar,tax:scalar,overhead:scalar,complete:z.boolean(),evidenceRefs:z.array(z.string().min(1).max(200)).max(30),assumptions:z.string().min(3).max(2000)}).strict();
export const forecastSchema=z.object({monthlyFixed:scalar,monthlyApi:scalar,units:scalar,economics:economicsSchema,cash:scalar.nullable(),liabilities:scalar,receivables:scalar,committed:scalar,providerIncrease:z.number().min(0).max(5),supplierIncrease:z.number().min(0).max(5),fxIncrease:z.number().min(0).max(5),advertisingIncrease:z.number().min(0).max(5),refundIncrease:z.number().min(0).max(1),assumptions:z.string().min(3).max(3000),observedAt:date}).strict();
const outcomeSchema=z.object({forecastId:id,actualProfitSgdMicro:z.number().int().min(-1e12).max(1e12),evidence:evidence,lesson:z.string().min(3).max(2000),nextAssumption:z.string().min(3).max(1000)}).strict();
export const commandSchema=z.discriminatedUnion('type',[
 z.object({id,type:z.literal('cost'),data:costSchema}),z.object({id,type:z.literal('provider'),data:providerSchema}),z.object({id,type:z.literal('budget'),data:budgetSchema}),z.object({id,type:z.literal('cash'),data:cashSchema}),z.object({id,type:z.literal('forecast'),data:forecastSchema}),z.object({id,type:z.literal('outcome'),data:outcomeSchema}),
 z.object({id,type:z.literal('provider_limit'),data:z.object({provider:z.enum(['openai','anthropic','gemini']),monthlyMicroUsd:money,reason:z.string().min(3).max(1000)}).strict()}),
 z.object({id,type:z.literal('coverage'),data:z.object({accounts:z.array(id).min(1).max(50),liabilitiesComplete:z.boolean(),commitmentsComplete:z.boolean(),reason:z.string().min(3).max(1000),evidence}).strict()}),
 z.object({id,type:z.literal('review'),data:z.object({target:id,decision:z.enum(['APPROVE','REJECT']),reason:z.string().min(3).max(1000),evidenceConfirmed:z.literal(true)}).strict()}),
 z.object({id,type:z.literal('reversal'),data:z.object({target:id,reason:z.string().min(3).max(1000)}).strict()})
]);
type Command=z.infer<typeof commandSchema>;
export type Entry=Command & {workspace:string;actor:string;at:string;digest:string};
export const defaultProviders=[
 ['chatgpt','ChatGPT development subscription','AI/development','YES'],['openai','OpenAI / Pillow','AI inference','YES'],['anthropic','Anthropic','AI inference','YES'],['gemini','Gemini','AI inference','YES'],['railway','Railway compute, Redis, storage','Infrastructure','YES'],['vercel','Vercel hosting and builds','Infrastructure','YES'],['domains','Domains / DNS / email','Infrastructure','YES'],['backups','Backups and recovery','Infrastructure','UNKNOWN'],['monitoring','Monitoring / security / logging','Infrastructure','UNKNOWN'],['amazon','Amazon seller / platform technology','Commerce technology','YES'],['cj','CJ API / service costs','Commerce technology','YES'],['keepa','Keepa','Research','NO'],['canva','Canva','Creative technology','UNKNOWN'],['tinyfish','TinyFish','Automation','UNKNOWN'],['browser','Browser automation','Automation','UNKNOWN'],['plugins','Plugins / connectors / workflow SaaS','Automation','UNKNOWN'],['development','Other development / testing tools','Development','UNKNOWN']
].map(([id,name,category,commissioned])=>({id,name,category,commissioned,mandatory:commissioned==='YES',billingAccess:'UNAVAILABLE',note:commissioned==='NO'?'Not commissioned; not required for completion':'Cost unknown until evidence is imported; bundled services must not be double counted'}));
export function hash(value:unknown){return createHash('sha256').update(JSON.stringify(value)).digest('hex');}
const iso=()=>new Date().toISOString();
function sum(values:number[]){const n=values.reduce((a,b)=>a+b,0);if(!Number.isSafeInteger(n))throw Error('FINANCIAL_OVERFLOW');return n;}
function chronology(value:unknown,now:number){if(!value||typeof value!=='object')return;for(const [k,v] of Object.entries(value)){if(['observedAt','asOf','paymentDate'].includes(k)&&typeof v==='string'&&Date.parse(v)>now)throw Error('FUTURE_EVIDENCE');if(k==='content'&&typeof v==='string'&&'sha256' in value&&createHash('sha256').update(v).digest('hex')!==(value as {sha256:string}).sha256)throw Error('EVIDENCE_HASH_MISMATCH');if(typeof v==='object')chronology(v,now);}}
export class FinancialCentre {
 db:DatabaseSync;
 constructor(filename:string){if(filename!==':memory:'){fs.mkdirSync(path.dirname(filename),{recursive:true,mode:0o700});if(fs.existsSync(filename)&&(!fs.lstatSync(filename).isFile()||fs.realpathSync(filename)!==filename))throw Error('UNSAFE_FINANCE_PATH');}
 if(filename!==':memory:'&&fs.existsSync(filename+'.initialized')&&!fs.existsSync(filename))throw Error('FINANCE_JOURNAL_MISSING');
 this.db=new DatabaseSync(filename,{allowExtension:false,timeout:1000});this.db.exec('PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; PRAGMA trusted_schema=OFF; CREATE TABLE IF NOT EXISTS financial_evidence (workspace TEXT NOT NULL,id TEXT NOT NULL,digest TEXT NOT NULL,record TEXT NOT NULL,PRIMARY KEY(workspace,id));');if(filename!==':memory:'){fs.chmodSync(filename,0o600);if(!fs.existsSync(filename+'.initialized')){const seal=fs.openSync(filename+'.initialized','wx',0o600);try{fs.writeSync(seal,'Work5 durable evidence journal; never reset');fs.fsyncSync(seal);}finally{fs.closeSync(seal);}}}}
 close(){this.db.close();}
 entries(workspace:string):Entry[]{return this.db.prepare('SELECT record FROM financial_evidence WHERE workspace=? ORDER BY rowid').all(workspace).map(r=>JSON.parse(String(r.record)) as Entry);}
 append(workspace:string,actor:string,input:unknown):Entry{const c=commandSchema.parse(input);chronology(c,Date.now());const digest=hash(c);this.db.exec('BEGIN IMMEDIATE');try{const entries=this.entries(workspace);const prior=entries.find(x=>x.id===c.id);if(prior){if(prior.digest!==digest)throw Error('IDEMPOTENCY_CONFLICT');this.db.exec('COMMIT');return prior;}
 if(c.type==='cost'){const d=c.data;const converted=(d.amountMicro+d.taxMicro-d.creditMicro)*(d.currency==='SGD'?1:d.fx?.sgdPerUnit??1);if(!Number.isSafeInteger(Math.round(converted)))throw Error('FINANCIAL_OVERFLOW');if(Date.parse(d.periodEnd)<=Date.parse(d.periodStart))throw Error('INVALID_BILLING_PERIOD');if(d.creditMicro>d.amountMicro+d.taxMicro)throw Error('CREDIT_EXCEEDS_CHARGE');if(d.stage==='INVOICED'||d.stage==='SETTLED'){if(!d.invoiceNumber||!d.evidence.some(e=>e.kind==='INVOICE'))throw Error('INVOICE_EVIDENCE_REQUIRED');}if(d.stage==='SETTLED'&&(!d.paymentDate||!d.evidence.some(e=>e.kind==='PAYMENT')))throw Error('PAYMENT_EVIDENCE_REQUIRED');
 const chain=entries.filter(e=>e.type==='cost'&&e.data.entityId===d.entityId);if(chain.length&&!d.replaces)throw Error('EXPLICIT_REPLACEMENT_REQUIRED');if(d.replaces){const old=entries.find(e=>e.id===d.replaces);if(!old||old.type!=='cost'||old.data.entityId!==d.entityId||old.data.provider!==d.provider||old.data.currency!==d.currency||old.data.periodStart!==d.periodStart||old.data.periodEnd!==d.periodEnd||old.data.authenticity!==d.authenticity||old.data.category!==d.category||chain.at(-1)?.id!==old.id)throw Error('INVALID_RECONCILIATION_LINK');}
 if(d.invoiceNumber&&entries.some(e=>e.type==='cost'&&e.data.provider===d.provider&&e.data.invoiceNumber===d.invoiceNumber&&e.data.entityId!==d.entityId))throw Error('DUPLICATE_INVOICE');if(d.sourceIds.some(source=>entries.some(e=>e.type==='cost'&&e.data.entityId!==d.entityId&&e.data.sourceIds.includes(source))))throw Error('DUPLICATE_SOURCE');
 }
 if(c.type==='review'||c.type==='reversal'){const target=entries.find(e=>e.id===c.data.target);if(!target||!['cost','cash','forecast','outcome','coverage'].includes(target.type))throw Error('REVIEW_TARGET_INVALID');if(entries.some(e=>e.type===c.type&&e.data.target===c.data.target))throw Error('ALREADY_DECIDED');if(c.type==='review'&&c.data.decision==='APPROVE'&&target.type==='cost'&&target.data.authenticity!=='REAL')throw Error('NON_REAL_APPROVAL_DENIED');}
 if(c.type==='cash'&&!Number.isSafeInteger(Math.round(c.data.balanceMicro*(c.data.currency==='SGD'?1:c.data.fx?.sgdPerUnit??1))))throw Error('FINANCIAL_OVERFLOW');
 if(c.type==='cash'&&c.data.evidence.kind!=='BANK')throw Error('BANK_EVIDENCE_REQUIRED');
 if(c.type==='outcome'&&c.data.evidence.kind!=='OUTCOME')throw Error('OUTCOME_EVIDENCE_REQUIRED');
 if(c.type==='outcome'&&!entries.some(e=>e.id===c.data.forecastId&&e.type==='forecast'))throw Error('FORECAST_LINK_REQUIRED');
 const entry={...c,workspace,actor,at:iso(),digest} as Entry;this.db.prepare('INSERT INTO financial_evidence VALUES(?,?,?,?)').run(workspace,c.id,digest,JSON.stringify(entry));this.db.exec('COMMIT');return entry;
 }catch(e){if(this.db.isTransaction)this.db.exec('ROLLBACK');throw e;}}
 snapshot(workspace:string,from='0000',to='9999',provider=''){const entries=this.entries(workspace);const reviewed=(id:string)=>entries.some(e=>e.type==='review'&&e.data.target===id&&e.data.decision==='APPROVE');const reversed=(id:string)=>entries.some(e=>e.type==='reversal'&&e.data.target===id);const active=new Map<string,Entry&{type:'cost'}>();for(const e of entries)if(e.type==='cost'&&reviewed(e.id)&&e.data.authenticity==='REAL'){if(reversed(e.id))active.delete(e.data.entityId);else active.set(e.data.entityId,e);}
 const costs=[...active.values()].filter(e=>e.data.periodStart<to&&e.data.periodEnd>from&&(!provider||e.data.provider===provider)).map(e=>{const d=e.data;const originalMicro=d.amountMicro+d.taxMicro-d.creditMicro;const sgdMicro=d.currency==='SGD'?Math.round(originalMicro*d.attribution.allocationBps/10000):d.fx?Math.round(originalMicro*d.fx.sgdPerUnit*d.attribution.allocationBps/10000):null;return {...e,originalMicro,sgdMicro,status:d.stage==='SETTLED'?'VERIFIED_SETTLED':d.stage==='INVOICED'?'VERIFIED_INVOICED':d.stage,verification:'OWNER_EVIDENCE_REVIEW',stale:d.evidence.some(v=>Date.now()-Date.parse(v.observedAt)>30*86400000),fxStale:d.fx?Date.now()-Date.parse(d.fx.observedAt)>30*86400000:false};});
 const grouped=Object.fromEntries(['SETTLED','INVOICED','ACCRUED_UNBILLED','ESTIMATED','COMMITTED'].map(stage=>[stage,{sgdMicro:sum(costs.filter(c=>c.data.stage===stage&&['TECHNOLOGY','COGS','ADVERTISING','FEES','REFUNDS','TAX'].includes(c.data.category)&&c.sgdMicro!==null).map(c=>c.sgdMicro!)),unknownFx:costs.filter(c=>c.data.stage===stage&&c.sgdMicro===null).length}])) as Record<'SETTLED'|'INVOICED'|'ACCRUED_UNBILLED'|'ESTIMATED'|'COMMITTED',{sgdMicro:number;unknownFx:number}>;
 const providers=new Map(defaultProviders.map(p=>[p.id,p]));for(const e of entries)if(e.type==='provider')providers.set(e.data.id,e.data);
 const budgets=new Map<string,z.infer<typeof budgetSchema>>();for(const e of entries)if(e.type==='budget')budgets.set(e.data.provider,e.data);
 const cash=new Map<string,Entry&{type:'cash'}>();for(const e of entries)if(e.type==='cash'&&reviewed(e.id)&&(!cash.has(e.data.account)||e.data.asOf>cash.get(e.data.account)!.data.asOf))cash.set(e.data.account,e);
 const cashEntries=[...cash.values()].filter(e=>!reversed(e.id)).map(e=>({...e,sgdMicro:e.data.currency==='SGD'?e.data.balanceMicro:e.data.fx?Math.round(e.data.balanceMicro*e.data.fx.sgdPerUnit):null,stale:Date.now()-Date.parse(e.data.asOf)>86400000||(e.data.fx?Date.now()-Date.parse(e.data.fx.observedAt)>30*86400000:false)}));
 const coverage=entries.filter(e=>e.type==='coverage'&&reviewed(e.id)&&!reversed(e.id)).at(-1);
 const cashKnown=cashEntries.length>0&&cashEntries.every(c=>c.sgdMicro!==null&&!c.stale);
 const obligationsKnown=costs.every(c=>!['INVOICED','COMMITTED','ACCRUED_UNBILLED'].includes(c.data.stage)||['REVENUE','CAPITAL','RECEIVABLE'].includes(c.data.category)||(c.sgdMicro!==null&&!c.stale&&!c.fxStale));
 const completeCashPosition=obligationsKnown&&!provider&&from==='0000'&&to==='9999'&&cashKnown&&coverage?.type==='coverage'&&coverage.data.liabilitiesComplete&&coverage.data.commitmentsComplete&&coverage.data.accounts.every(a=>cashEntries.some(c=>c.data.account===a))&&cashEntries.every(c=>coverage.data.accounts.includes(c.data.account))&&Date.now()-Date.parse(coverage.data.evidence.observedAt)<86400000;const total=(category:string,stages:string[])=>sum(costs.filter(c=>c.data.category===category&&stages.includes(c.data.stage)&&c.sgdMicro!==null).map(c=>c.sgdMicro!));
 const actualStages=['SETTLED','INVOICED'];const revenue=total('REVENUE',actualStages),technology=total('TECHNOLOGY',actualStages),cogs=total('COGS',actualStages),other=sum(['ADVERTISING','FEES','REFUNDS','TAX'].map(c=>total(c,actualStages)));
 const pending=entries.filter(e=>['cost','cash','outcome','coverage'].includes(e.type)&&!entries.some(r=>r.type==='review'&&r.data.target===e.id)&&!reversed(e.id));
 const alerts:Array<{code:string;detail:string;refs:string[]}>=[];for(const c of costs){if(c.sgdMicro===null)alerts.push({code:'FX_UNAVAILABLE',detail:'SGD total excludes an unconverted amount',refs:[c.id]});if(c.stale||c.fxStale)alerts.push({code:'STALE_EVIDENCE',detail:'Refresh financial evidence before a decision',refs:[c.id]});if(c.data.renewalDate&&Date.parse(c.data.renewalDate)-Date.now()<7*86400000)alerts.push({code:'RENEWAL_DUE',detail:c.data.provider+' renewal due',refs:[c.id]});if(c.data.stage==='ACCRUED_UNBILLED'&&Date.parse(c.data.periodEnd)<Date.now())alerts.push({code:'MISSING_INVOICE',detail:'Closed usage period has no matched invoice',refs:[c.id]});}
 for(const b of budgets.values()){const start=new Date().toISOString().slice(0,7);const used=sum(costs.filter(c=>c.data.provider===b.provider&&c.data.periodStart.startsWith(start)&&c.sgdMicro!==null&&c.data.stage!=='COMMITTED').map(c=>c.sgdMicro!));if(used>=b.monthlySgdMicro*b.warningPercent/100)alerts.push({code:'BUDGET_ALERT',detail:b.provider+' known costs exceed configured threshold; this control does not authorize spending',refs:[]});}
 if(!cashKnown)alerts.push({code:'CASH_UNVERIFIED',detail:'Current complete bank/payment-account evidence is unavailable; runway is unknown',refs:cashEntries.map(c=>c.id)});
 const recommendations:Array<{topic:string;text:string}>=[];
 for(const p of providers.values()){const byMonth=new Map<string,number>();for(const c of costs)if(c.data.provider===p.id&&c.sgdMicro!==null&&c.data.stage!=='COMMITTED')byMonth.set(c.data.periodStart.slice(0,7),(byMonth.get(c.data.periodStart.slice(0,7))??0)+c.sgdMicro);const months=[...byMonth].sort(([a],[b])=>a.localeCompare(b));if(months.length>=2){const a=months.at(-2)!,b=months.at(-1)!;if(b[1]>a[1]*1.2){alerts.push({code:'COST_INCREASE',detail:p.name+' known period costs rose more than20%; compare complete periods before concluding an anomaly',refs:costs.filter(c=>c.data.provider===p.id).map(c=>c.id)});recommendations.push({topic:'Review '+p.name,text:'Compare usage, duplicated service coverage and rate changes before renewing; incomplete periods are not directly comparable.'});}}}
 if(revenue-cogs-other<0)recommendations.push({topic:'Negative known contribution',text:'Recheck supplier, freight, fees, advertising and returns; do not scale a negative contribution product.'});
 for(const o of entries)if(o.type==='outcome'&&reviewed(o.id)){const f=entries.find(x=>x.id===o.data.forecastId);if(f?.type==='forecast'){const predicted=forecast(f.data).scenarios[0]!.monthlyProfit;recommendations.push({topic:'Outcome calibration '+o.id,text:'Realised-minus-predicted SGD '+(o.data.actualProfitSgdMicro/1e6-predicted).toFixed(2)+'. Reviewed lesson: '+o.data.lesson+'; next assumption: '+o.data.nextAssumption});}}
 return {schema:'work5-finance-v1',observedAt:iso(),currency:'SGD',scope:{from,to,provider},source:'Append-only evidence journal linked to canonical legacy ledger and inference accounting',noExecutionAuthority:true,entries,entryDigest:hash(entries),costs,pending,providers:[...providers.values()],budgets:[...budgets.values()],cash:cashEntries,knownCashSgdMicro:cashKnown?sum(cashEntries.map(c=>c.sgdMicro!)):null,completeCashPosition:!!completeCashPosition,availableCashSgdMicro:completeCashPosition?sum(cashEntries.map(c=>c.sgdMicro!))-sum(costs.filter(c=>['INVOICED','ACCRUED_UNBILLED'].includes(c.data.stage)&&!['REVENUE','CAPITAL','RECEIVABLE'].includes(c.data.category)&&c.sgdMicro!==null).map(c=>c.sgdMicro!))-grouped.COMMITTED.sgdMicro:null,runway:null,totals:grouped,kpis:{verifiedRevenueSgdMicro:revenue,knownTechnologySgdMicro:technology,knownCogsSgdMicro:cogs,knownGrossProfitSgdMicro:revenue-cogs,knownContributionSgdMicro:revenue-cogs-other,knownNetSgdMicro:revenue-cogs-other-technology,complete:false,qualification:'PARTIAL_KNOWN_AMOUNTS_NOT_CERTIFIED_PROFIT'},position:{capitalSgdMicro:total('CAPITAL',['SETTLED']),payableSgdMicro:sum(costs.filter(c=>['INVOICED','ACCRUED_UNBILLED'].includes(c.data.stage)&&!['REVENUE','CAPITAL','RECEIVABLE'].includes(c.data.category)&&c.sgdMicro!==null).map(c=>c.sgdMicro!)),receivableSgdMicro:total('RECEIVABLE',actualStages),commitmentsSgdMicro:grouped.COMMITTED.sgdMicro},alerts,recommendations:[...recommendations,{topic:'Capital allocation',text:'Preserve capital until complete cash, liabilities and unit economics are verified; no spending approval is implied.'},{topic:'Cost efficiency',text:'Review renewals and compare equivalent service coverage before recommending cancellation; imported usage and invoice lineage remain distinct.'}],outcomes:entries.filter(e=>e.type==='outcome').map(e=>({...e,verified:reviewed(e.id)})),learningStatus:'OUTCOME_LINKED_CAPABILITY; COMPOUNDED_IMPROVEMENT_UNPROVEN'};}
}
export function economics(raw:unknown){const d=economicsSchema.parse(raw);const landed=d.productCost+d.freight+d.fulfilment+d.duties;const percentage=(d.feePercent+d.paymentPercent)/100;if(percentage>=1)throw Error('FEES_EXCEED_PRICE');const gross=d.sellingPrice-landed;const contribution=gross-d.sellingPrice*percentage-d.advertising-d.refundRate*d.refundLoss-d.tax;const net=contribution-d.overhead;const breakEven=(landed+d.advertising+d.refundRate*d.refundLoss+d.tax+d.overhead)/(1-percentage);return {input:d,gross,contribution,net,breakEven,minimumViablePrice:breakEven,marginPercent:d.sellingPrice?net/d.sellingPrice*100:null,status:d.complete&&d.evidenceRefs.length?'EVIDENCED_SCENARIO_NOT_ACTUAL':'INCOMPLETE_ESTIMATE',genuinelyProfitable:false};}
export function forecast(raw:unknown){const d=forecastSchema.parse(raw);chronology(d,Date.now());const scenario=(name:string,units:number,shock:boolean)=>{const e=economics({...d.economics,productCost:d.economics.productCost*(shock?1+d.supplierIncrease:1)*(shock?1+d.fxIncrease:1),freight:d.economics.freight*(shock?1+d.fxIncrease:1),advertising:d.economics.advertising*(shock?1+d.advertisingIncrease:1),refundRate:Math.min(1,d.economics.refundRate+(shock?d.refundIncrease:0))});const overhead=d.monthlyFixed+d.monthlyApi*(shock?1+d.providerIncrease:1);const profit=e.net*units-overhead;const available=d.cash===null?null:d.cash-d.liabilities-d.committed;return {name,units,monthlyInfrastructure:overhead,annualInfrastructure:overhead*12,revenue:d.economics.sellingPrice*units,monthlyProfit:profit,annualProfit:profit*12,breakEvenUnits:e.net>0?Math.ceil(overhead/e.net):null,runwayMonths:available===null?null:profit<0?Math.max(0,available)/-profit:null,capitalRequired:available===null?null:Math.max(0,-available-profit*3),unit:e};};return {assumptions:d.assumptions,observedAt:d.observedAt,stale:Date.now()-Date.parse(d.observedAt)>30*86400000,status:'SCENARIO_NOT_ACTUAL',scenarios:[scenario('Base',d.units,false),scenario('Optimistic',d.units*1.2,false),scenario('Downside',d.units*0.5,true)],zeroSales:[30,60,90].map(days=>({days,cashRequired:(d.monthlyFixed+d.monthlyApi*(1+d.providerIncrease))*days/30+d.liabilities+d.committed,cashRemaining:d.cash===null?null:d.cash-(d.monthlyFixed+d.monthlyApi*(1+d.providerIncrease))*days/30-d.liabilities-d.committed,recommendation:'Review discretionary renewals, pause unapproved expansion and re-evaluate verified demand and contribution before allocating capital.'})),paidInference:false};}
let instance:FinancialCentre|undefined;
export function productionFinance(){const root=process.env.RAILWAY_VOLUME_MOUNT_PATH;if(!root||!path.isAbsolute(root)||fs.realpathSync(root)!==root)throw Error('FINANCE_VOLUME_UNAVAILABLE');return instance??=new FinancialCentre(path.join(root,'finance','evidence.sqlite'));}

export function ownerProviderLimit(provider:string):number|null {const root=process.env.RAILWAY_VOLUME_MOUNT_PATH;if(!root)return null;const file=path.join(root,'finance','evidence.sqlite');if(!fs.existsSync(file)){if(fs.existsSync(file+'.initialized'))throw Error('FINANCE_JOURNAL_MISSING');return null;}const entries=productionFinance().entries('ws_empire_1');const limit=entries.filter(e=>e.type==='provider_limit'&&e.data.provider===provider).at(-1);return limit?.type==='provider_limit'?limit.data.monthlyMicroUsd:null;}
