/** Contract-defined Pillow implementation sequence (Part 7). */
export interface PillowSequenceEntry {
  id: string;
  title: string;
  missionType: string;
  authority: string;
  objective: string;
  prerequisites: string[];
  implementationRules: string[];
  acceptanceCriteria: string[];
  validation: string[];
  executiveAudit: string[];
  stopRule: string;
}

export const PILLOW_IMPLEMENTATION_SEQUENCE: PillowSequenceEntry[] = [
  {
    id: "PILLOW-002",
    title: "Repository Bootstrap Engine",
    missionType: "Core Architecture Implementation",
    authority: "PILLOW_ARCHITECTURE_CONTRACT.md Part 4.1",
    objective:
      "Initialize Pillow sessions with read-only repository discovery and Failure Mode gate.",
    prerequisites: [],
    implementationRules: ["Read-only", "Mandatory first process"],
    acceptanceCriteria: ["Bootstrap succeeds on valid repository"],
    validation: ["bootstrap.test.ts"],
    executiveAudit: ["Pre-implementation review", "Validation results"],
    stopRule: "Stop after Executive Audit.",
  },
  {
    id: "PILLOW-003",
    title: "Repository Intelligence Engine",
    missionType: "Core Architecture Implementation",
    authority: "PILLOW_ARCHITECTURE_CONTRACT.md Part 4.14 · ADR-029",
    objective:
      "Transform Bootstrap discovery into classified operational knowledge with graphs and health.",
    prerequisites: ["PILLOW-002"],
    implementationRules: ["Read-only", "Chains after Bootstrap"],
    acceptanceCriteria: ["Intelligence context produced"],
    validation: ["intelligence.test.ts"],
    executiveAudit: ["Architecture review", "Validation results"],
    stopRule: "Stop after Executive Audit.",
  },
  {
    id: "PILLOW-004",
    title: "Context Builder",
    missionType: "Core Architecture Implementation",
    authority: "PILLOW_ARCHITECTURE_CONTRACT.md Part 4.2 · ADR-032",
    objective:
      "Assemble minimum operational context per request from Intelligence output.",
    prerequisites: ["PILLOW-002", "PILLOW-003"],
    implementationRules: ["Read-only", "Task profiles", "Ephemeral cache"],
    acceptanceCriteria: ["Context manifest with provenance"],
    validation: ["context.test.ts"],
    executiveAudit: ["Context architecture", "Validation results"],
    stopRule: "Stop after Executive Audit.",
  },
  {
    id: "PILLOW-005",
    title: "Repository Memory Engine",
    missionType: "Core Architecture Implementation",
    authority: "PILLOW_ARCHITECTURE_CONTRACT.md Part 4.15 · ADR-033",
    objective:
      "Maintain long-term operational memory derived from repository truth.",
    prerequisites: ["PILLOW-002", "PILLOW-003"],
    implementationRules: ["Read-only", "Provenance on all domains"],
    acceptanceCriteria: ["Memory refreshes on fingerprint change"],
    validation: ["memory.test.ts"],
    executiveAudit: ["Memory domains", "Integrity verification"],
    stopRule: "Stop after Executive Audit.",
  },
  {
    id: "PILLOW-006",
    title: "Mission Planner",
    missionType: "Core Architecture Implementation",
    authority: "PILLOW_ARCHITECTURE_CONTRACT.md Part 4.16 · ADR-034",
    objective:
      "Determine the correct next engineering, governance, or operational mission from repository state.",
    prerequisites: ["PILLOW-002", "PILLOW-003", "PILLOW-004", "PILLOW-005"],
    implementationRules: [
      "Never depend on conversation history",
      "Never modify repository files",
      "Generate missions only — execution belongs to Cursor",
    ],
    acceptanceCriteria: [
      "Next mission determined from repository",
      "Dependencies validated",
      "Cursor-ready mission generated",
    ],
    validation: ["planner.test.ts"],
    executiveAudit: [
      "Mission Planner architecture",
      "Sequencing engine",
      "Priority engine",
      "Dependency validation",
    ],
    stopRule: "Stop after Executive Audit. Do not begin PILLOW-007.",
  },
  {
    id: "PILLOW-007",
    title: "Cursor Supervisor",
    missionType: "Core Architecture Implementation",
    authority:
      "PILLOW_ARCHITECTURE_CONTRACT.md Part 4.17 · EMPIREAI_CURSOR_RECOVERY_DOCTRINE.md · ADR-035",
    objective:
      "Supervise Cursor engineering missions — launch, monitor, detect stalls, coordinate Recovery Mode.",
    prerequisites: [
      "PILLOW-002",
      "PILLOW-003",
      "PILLOW-004",
      "PILLOW-005",
      "PILLOW-006",
    ],
    implementationRules: [
      "Conform to Cursor Recovery Doctrine",
      "Supervision only — never modify repository",
      "Never approve implementations",
    ],
    acceptanceCriteria: [
      "Mission lifecycle tracked",
      "Stall and dead agent detection operational",
      "Recovery Manager invoked on qualifying stalls",
      "Executive Audit supervision verified",
    ],
    validation: ["supervisor.test.ts"],
    executiveAudit: [
      "Cursor Supervisor architecture",
      "Heartbeat verification",
      "Recovery coordination",
    ],
    stopRule: "Stop after Executive Audit. Do not begin PILLOW-008.",
  },
  {
    id: "PILLOW-008",
    title: "Recovery Manager",
    missionType: "Core Architecture Implementation",
    authority:
      "PILLOW_ARCHITECTURE_CONTRACT.md Part 4.18 · EMPIREAI_CURSOR_RECOVERY_DOCTRINE.md · ADR-036",
    objective:
      "Autonomous engineering recovery — preserve work, resume missions, execute doctrine validation cycle.",
    prerequisites: [
      "PILLOW-002",
      "PILLOW-003",
      "PILLOW-004",
      "PILLOW-005",
      "PILLOW-006",
      "PILLOW-007",
    ],
    implementationRules: [
      "Implement Cursor Recovery Doctrine exactly",
      "Recovery resumes — never restarts completed work",
      "Invoked only by Cursor Supervisor",
      "Never modify Journey or BL",
    ],
    acceptanceCriteria: [
      "Recovery resumes interrupted missions",
      "Outcomes recorded",
      "Validation cycle once only",
      "Repository preservation verified",
    ],
    validation: ["recovery.test.ts"],
    executiveAudit: [
      "Recovery procedure verification",
      "Repository preservation",
      "Mission continuity",
    ],
    stopRule: "Stop after Executive Audit. Do not begin PILLOW-009.",
  },
  {
    id: "PILLOW-009",
    title: "Executive Audit Reviewer",
    missionType: "Core Architecture Implementation",
    authority:
      "PILLOW_ARCHITECTURE_CONTRACT.md Part 4.19 · EMPIREAI_EXECUTIVE_AUDIT_STANDARD.md · ADR-037",
    objective:
      "Mandatory quality gate — independently evaluate every completed engineering mission before acceptance.",
    prerequisites: [
      "PILLOW-002",
      "PILLOW-003",
      "PILLOW-004",
      "PILLOW-005",
      "PILLOW-006",
      "PILLOW-007",
      "PILLOW-008",
    ],
    implementationRules: [
      "Completion does not equal acceptance",
      "Evaluate only — never modify repository",
      "Reports to Cursor Supervisor",
      "Mandatory corrections prevent approval",
    ],
    acceptanceCriteria: [
      "Executive Audits evaluated correctly",
      "Acceptance criteria verified individually",
      "Architecture and repository integrity verified",
      "Approval decision produced with reasoning",
      "Recommendations categorized correctly",
    ],
    validation: ["audit-reviewer.test.ts"],
    executiveAudit: [
      "Review engine verification",
      "Decision engine verification",
      "Recommendation engine verification",
    ],
    stopRule: "Stop after Executive Audit. Do not begin PILLOW-010.",
  },
  {
    id: "PILLOW-010",
    title: "Repository Synchronizer",
    missionType: "Core Architecture Implementation",
    authority:
      "PILLOW_ARCHITECTURE_CONTRACT.md Part 4.20 · EMPIREAI_JOURNEY_FIRST_DOCTRINE.md · EMPIREAI_REPOSITORY_FIRST_DOCTRINE.md · ADR-038",
    objective:
      "Repository maintenance engine — keep canonical artifacts synchronized after approved engineering work.",
    prerequisites: [
      "PILLOW-002",
      "PILLOW-003",
      "PILLOW-004",
      "PILLOW-005",
      "PILLOW-006",
      "PILLOW-007",
      "PILLOW-008",
      "PILLOW-009",
    ],
    implementationRules: [
      "Preview Mode always first — no writes during preview",
      "Grand King approval required before any canonical write",
      "Never invent repository information — derive from verified evidence",
      "Never bypass Preview Mode or approval",
    ],
    acceptanceCriteria: [
      "Change detection operational",
      "Preview Mode generated",
      "Approval gate enforced",
      "Synchronization verification completed",
      "History recorded",
      "Repository integrity preserved",
    ],
    validation: ["synchronizer.test.ts"],
    executiveAudit: [
      "Change detection verification",
      "Preview verification",
      "Approval workflow verification",
      "Synchronization verification",
    ],
    stopRule: "Stop after Executive Audit. Do not begin PILLOW-011.",
  },
  {
    id: "PILLOW-011",
    title: "Continuous Due Diligence Engine",
    missionType: "Core Architecture Implementation",
    authority:
      "PILLOW_ARCHITECTURE_CONTRACT.md Part 4.21 · EMPIREAI_BL_C_CONTINUOUS_IMPROVEMENT_CONSTITUTION.md · ADR-039",
    objective:
      "Permanent self-initiated analysis — continuously investigate and improve EmpireAI without waiting for user instructions.",
    prerequisites: [
      "PILLOW-002",
      "PILLOW-003",
      "PILLOW-004",
      "PILLOW-005",
      "PILLOW-006",
      "PILLOW-007",
      "PILLOW-008",
      "PILLOW-009",
      "PILLOW-010",
    ],
    implementationRules: [
      "Pillow shall never become passive",
      "Read-only — never modify repository without Grand King approval",
      "Grand King commands always take priority over idle analysis",
      "All recommendations require Grand King approval before execution",
    ],
    acceptanceCriteria: [
      "Continuous analysis operational",
      "Recommendations categorized by priority",
      "Review categories supported",
      "No unauthorized repository modification",
      "Grand King interruption immediate",
    ],
    validation: ["due-diligence.test.ts"],
    executiveAudit: [
      "Continuous analysis verification",
      "Recommendation engine verification",
      "Priority engine verification",
    ],
    stopRule: "Stop after Executive Audit. Do not begin PILLOW-012.",
  },
  {
    id: "PILLOW-012",
    title: "Autonomous Improvement Engine",
    missionType: "Core Architecture Implementation",
    authority:
      "PILLOW_ARCHITECTURE_CONTRACT.md Part 4.22 · EMPIREAI_BL_C_CONTINUOUS_IMPROVEMENT_CONSTITUTION.md · ADR-040",
    objective:
      "Convert Due Diligence observations into structured engineering proposals and implementation plans — evidence-driven, Grand King approval required.",
    prerequisites: [
      "PILLOW-002",
      "PILLOW-003",
      "PILLOW-004",
      "PILLOW-005",
      "PILLOW-006",
      "PILLOW-007",
      "PILLOW-008",
      "PILLOW-009",
      "PILLOW-010",
      "PILLOW-011",
    ],
    implementationRules: [
      "Observation alone creates no value — proposals must be executable missions",
      "Read-only — never modify repository without Grand King approval",
      "Never execute engineering work or launch Cursor directly",
      "Every proposal requires Grand King approval before mission generation",
    ],
    acceptanceCriteria: [
      "Improvement opportunities generated correctly",
      "Repository evidence attached",
      "Dependencies verified",
      "Implementation proposals produced",
      "Mission readiness determined",
      "Approval workflow enforced",
      "Repository remains unchanged",
    ],
    validation: ["improvement.test.ts"],
    executiveAudit: [
      "Proposal engine verification",
      "Dependency verification",
      "Mission readiness verification",
      "Approval workflow verification",
    ],
    stopRule: "Stop after Executive Audit. Do not begin PILLOW-013.",
  },
  {
    id: "PILLOW-013",
    title: "EmpireAI Orchestrator",
    missionType: "Core Architecture Implementation",
    authority:
      "PILLOW_ARCHITECTURE_CONTRACT.md Part 4.23 · ADR-041",
    objective:
      "Central coordination layer — coordinate every Pillow subsystem, engineering worker, and governance workflow without performing engineering work.",
    prerequisites: [
      "PILLOW-002",
      "PILLOW-003",
      "PILLOW-004",
      "PILLOW-005",
      "PILLOW-006",
      "PILLOW-007",
      "PILLOW-008",
      "PILLOW-009",
      "PILLOW-010",
      "PILLOW-011",
      "PILLOW-012",
    ],
    implementationRules: [
      "Orchestrator coordinates — never replaces specialized modules",
      "Never modify repository files or approve engineering work directly",
      "Grand King commands always override autonomous workflows",
      "Failure coordination must preserve repository integrity",
    ],
    acceptanceCriteria: [
      "Subsystem registry operational",
      "Worker registry operational",
      "Workflow coordination operational",
      "Execution pipeline coordinated successfully",
      "Scheduling engine operational",
      "Failure coordination operational",
      "Grand King priority enforced",
      "Repository integrity preserved",
    ],
    validation: ["orchestrator.test.ts"],
    executiveAudit: [
      "Subsystem registry verification",
      "Worker registry verification",
      "Workflow coordination verification",
      "Scheduling verification",
    ],
    stopRule: "Stop after Executive Audit. Do not begin PILLOW-014.",
  },
  {
    id: "PILLOW-014",
    title: "Live Repository Watcher",
    missionType: "Core Architecture Implementation",
    authority: "PILLOW_ARCHITECTURE_CONTRACT.md Part 4.24 · ADR-042",
    objective:
      "Continuous repository sensing — detect changes, classify events, notify subscribers, detect drift — read-only observation only.",
    prerequisites: [
      "PILLOW-002",
      "PILLOW-003",
      "PILLOW-004",
      "PILLOW-005",
      "PILLOW-006",
      "PILLOW-007",
      "PILLOW-008",
      "PILLOW-009",
      "PILLOW-010",
      "PILLOW-011",
      "PILLOW-012",
      "PILLOW-013",
    ],
    implementationRules: [
      "Pillow shall never assume repository state remains unchanged",
      "Read-only — never modify repository or repair issues",
      "Subscribers determine how to respond to events",
      "Minimize duplicate notifications and batch related events",
    ],
    acceptanceCriteria: [
      "Repository changes detected automatically",
      "Repository events generated correctly",
      "Subscribers notified correctly",
      "Repository drift detected",
      "Repository scanning optimized",
      "Repository remains unchanged",
    ],
    validation: ["watcher.test.ts"],
    executiveAudit: [
      "Observation verification",
      "Event system verification",
      "Subscriber verification",
      "Repository drift verification",
    ],
    stopRule: "Stop after Executive Audit. Do not begin PILLOW-015.",
  },
  {
    id: "PILLOW-015",
    title: "Grand King Command Interface",
    missionType: "Core Architecture Implementation",
    authority: "PILLOW_ARCHITECTURE_CONTRACT.md Part 4.25 · ADR-043",
    objective:
      "Natural-language executive console — interpret Grand King intent, load repository context, coordinate Pillow modules read-only.",
    prerequisites: [
      "PILLOW-002",
      "PILLOW-003",
      "PILLOW-004",
      "PILLOW-005",
      "PILLOW-006",
      "PILLOW-007",
      "PILLOW-008",
      "PILLOW-009",
      "PILLOW-010",
      "PILLOW-011",
      "PILLOW-012",
      "PILLOW-013",
      "PILLOW-014",
    ],
    implementationRules: [
      "Grand King issues objectives — Pillow determines execution",
      "Repository truth overrides conversational assumptions",
      "Never modify repository files or bypass governance",
      "Grand King commands always receive highest priority",
    ],
    acceptanceCriteria: [
      "Natural language commands interpreted correctly",
      "Repository context resolved automatically",
      "Execution plans generated correctly",
      "Relevant Pillow modules coordinated automatically",
      "Grand King priority enforced",
      "Conversation continuity preserved through repository intelligence",
      "Repository integrity maintained",
    ],
    validation: ["command.test.ts"],
    executiveAudit: [
      "Intent resolution verification",
      "Execution coordination verification",
      "Conversation continuity verification",
      "PILLOW Master Executive Audit",
    ],
    stopRule: "Stop after PILLOW Master Executive Audit. No post-Pillow implementation without Grand King approval.",
  },
  {
    id: "PILLOW-016",
    title: "OpenAI API Integration Layer",
    missionType: "Core Architecture Implementation",
    authority: "PILLOW_ARCHITECTURE_CONTRACT.md Part 4 · ADR-030",
    objective:
      "Route LLM requests with Context Builder and Memory payloads — deferred post-Pillow V1.",
    prerequisites: ["PILLOW-015"],
    implementationRules: [
      "Consume OperationalContext manifests only",
      "Never transmit unnecessary artifacts",
    ],
    acceptanceCriteria: ["LLM integration with context payloads"],
    validation: ["openai integration tests"],
    executiveAudit: ["Integration architecture", "Validation results"],
    stopRule: "Deferred — requires Grand King approval post-Pillow V1.",
  },
  {
    id: "PILLOW-017",
    title: "Approval Gate + Cursor Bridge",
    missionType: "Core Architecture Implementation",
    authority: "PILLOW_ARCHITECTURE_CONTRACT.md Part 4.9 · 4.11",
    objective:
      "Gate repository mutations behind Grand King approval — deferred post-Pillow V1.",
    prerequisites: ["PILLOW-015", "PILLOW-016"],
    implementationRules: [
      "No repository mutation without approval",
      "Cursor Bridge handoff only",
    ],
    acceptanceCriteria: ["Approval flow operational"],
    validation: ["approval gate tests"],
    executiveAudit: ["Governance flow", "Validation results"],
    stopRule: "Deferred — requires Grand King approval post-Pillow V1.",
  },
  {
    id: "PILLOW-018",
    title: "Pillow Chat UI",
    missionType: "Core Architecture Implementation",
    authority: "PILLOW_ARCHITECTURE_CONTRACT.md Part 4.12",
    objective: "Single continuous conversation surface — deferred post-Pillow V1.",
    prerequisites: ["PILLOW-016", "PILLOW-017"],
    implementationRules: ["Session state ephemeral only"],
    acceptanceCriteria: ["Chat UI wired to Pillow backend"],
    validation: ["UI integration tests"],
    executiveAudit: ["UX architecture", "Validation results"],
    stopRule: "Deferred — requires Grand King approval post-Pillow V1.",
  },
  {
    id: "PILLOW-019",
    title: "Empire Recovery Assessment",
    missionType: "Core Architecture Implementation",
    authority:
      "PILLOW_ARCHITECTURE_CONTRACT.md · EMPIREAI_EMPIRE_RECOVERY_DOCTRINE.md",
    objective: "Recovery session runtime per BL-B doctrine — deferred post-Pillow V1.",
    prerequisites: ["PILLOW-002", "PILLOW-005", "PILLOW-007", "PILLOW-008"],
    implementationRules: ["Read-only assessment", "Gated report writes"],
    acceptanceCriteria: ["Recovery checklist domains operational"],
    validation: ["recovery tests"],
    executiveAudit: ["Recovery architecture", "Validation results"],
    stopRule: "Deferred — requires Grand King approval post-Pillow V1.",
  },
];

export const COMMERCIAL_BLOCKER_MISSIONS = [
  {
    id: "REAL-002B",
    title: "Connect Amazon SP-API + first VERIFIED live credentials",
    category: "commercial_intelligence" as const,
    objective:
      "Unblock PROOF-001 and MS-A by establishing first verified live commercial credentials.",
    authority: "EMPIREAI_STATUS.md · PROGRAM_CATALOG operational-access",
    prerequisites: ["REAL-002"],
  },
];
