import { AuthorizationBuilder } from "./authorization-builder.js";
import type { AuthorizationWorkerConfiguration } from "./configuration.js";
import { IntegrationCoordinator, type AuthorizationWorkerDependencies } from "./integrations.js";
import { AuthorizationRuntime } from "./authorization-runtime.js";
import { AuthorizationStore } from "./authorization-store.js";
import { AuthorizationValidator } from "./authorization-validator.js";
import type { AuthorizationBuildReport, AuthorizationWorkerInput } from "./types.js";
export class AuthorizationManager {
  private readonly store = new AuthorizationStore(); private readonly builder = new AuthorizationBuilder(); private readonly validator = new AuthorizationValidator(); private readonly integrations = new IntegrationCoordinator(); readonly runtime = new AuthorizationRuntime(this.integrations);
  constructor(readonly configuration: AuthorizationWorkerConfiguration) {}
  bindIntegrations(dependencies: AuthorizationWorkerDependencies = {}) { this.integrations.bind(dependencies); }
  connect() { this.integrations.connect(); return this.run("connect", this.store.latest(), this.validator.validate(this.store.list(), { validated: true })); }
  private pipeline(action: string, input: AuthorizationWorkerInput = {}, complete = false) { const enriched = this.integrations.enrich(input); const check = this.validator.validate(null, enriched); if (check.decision === "fail") return this.run(action, null, check); let report = this.store.latest() ?? this.builder.create(enriched); if (action.startsWith("receiveApproved")) report = this.builder.create(enriched); this.builder.stage(report, action); if (action === "produceAuthorizationBuildReport") { this.builder.populate(report, this.runtime.roles.list().map((item) => item.roleId), this.runtime.permissions.list().map((item) => item.permissionId), this.runtime.policies.list().map((item) => item.policyId), []); this.builder.complete(report); } const validation = this.validator.validate([report], enriched, complete || action === "produceAuthorizationBuildReport"); this.store.save(report, action); return this.run(action, report, validation); }
  receiveApprovedRequirementsReports(input?: AuthorizationWorkerInput) { return this.pipeline("receiveApprovedRequirementsReports", input); } receiveApprovedArchitectureReports(input?: AuthorizationWorkerInput) { return this.pipeline("receiveApprovedArchitectureReports", input); } stage(action: string, input?: AuthorizationWorkerInput) { return this.pipeline(action, input); } produceAuthorizationBuildReport(input?: AuthorizationWorkerInput) { return this.pipeline("produceAuthorizationBuildReport", input, true); }
  submitReport(input: AuthorizationWorkerInput = {}) { const result = this.produceAuthorizationBuildReport(input); const report = result.latestAuthorizationBuildReport; if (report && result.validation.decision !== "fail") { report.executiveReportId = this.integrations.submit(report); report.submittedToExecutiveReporting = Boolean(report.executiveReportId); this.store.save(report, "submitReport"); } return this.run("submitReport", report, result.validation); }
  list() { return this.run("list", this.store.latest(), this.validator.validate(this.store.list(), { validated: true })); } validate(input?: AuthorizationWorkerInput) { return this.run("validate", this.store.latest(), this.validator.validate(this.store.list(), input)); } diagnostics() { return this.list(); } getReports() { return this.store.list(); } getAuditTrail() { return this.store.trail(); } getIntegrations() { return this.integrations.connect(); }
  private run(action: string, report: AuthorizationBuildReport | null, validation: ReturnType<AuthorizationValidator["validate"]>) { return { authorizationRunReportId: `azw-run-${Date.now()}`, action, timestamp: new Date().toISOString(), latestAuthorizationBuildReport: report ? structuredClone(report) : null, authorizationBuildReports: report ? [structuredClone(report)] : [], validation, durationMs: 0 }; }
}
