import type { AuthorizationWorkerConfiguration } from "./configuration.js";
import type { AuthorizationWorkerDependencies } from "./integrations.js";
import { AuthorizationManager } from "./authorization-manager.js";
import type { AuthorizationWorkerInput } from "./types.js";
export class AuthorizationWorkerController {
  private status = "idle"; private latest: ReturnType<AuthorizationManager["list"]> | null = null;
  constructor(readonly manager: AuthorizationManager, readonly configuration: AuthorizationWorkerConfiguration) {}
  initialize() { this.status = "active"; } bindIntegrations(dependencies?: AuthorizationWorkerDependencies) { this.manager.bindIntegrations(dependencies); } connect() { this.status = "connecting"; return this.finish(this.manager.connect() as never); }
  receiveApprovedRequirementsReports(input?: AuthorizationWorkerInput) { return this.finish(this.manager.receiveApprovedRequirementsReports(input)); } receiveApprovedRequirementsReport(input?: AuthorizationWorkerInput) { return this.receiveApprovedRequirementsReports(input); } receiveApprovedArchitectureReports(input?: AuthorizationWorkerInput) { return this.finish(this.manager.receiveApprovedArchitectureReports(input)); } receiveApprovedArchitectureReport(input?: AuthorizationWorkerInput) { return this.receiveApprovedArchitectureReports(input); }
  buildRoleManagement(input?: AuthorizationWorkerInput) { return this.finish(this.manager.stage("buildRoleManagement", input)); } buildPermissionManagement(input?: AuthorizationWorkerInput) { return this.finish(this.manager.stage("buildPermissionManagement", input)); } buildPolicyBasedAuthorization(input?: AuthorizationWorkerInput) { return this.finish(this.manager.stage("buildPolicyBasedAuthorization", input)); } buildResourceLevelAuthorization(input?: AuthorizationWorkerInput) { return this.finish(this.manager.stage("buildResourceLevelAuthorization", input)); } buildActionLevelAuthorization(input?: AuthorizationWorkerInput) { return this.finish(this.manager.stage("buildActionLevelAuthorization", input)); } supportInheritanceWhereDefined(input?: AuthorizationWorkerInput) { return this.finish(this.manager.stage("supportInheritanceWhereDefined", input)); } evaluateAuthorizationDecisions(input?: AuthorizationWorkerInput) { return this.finish(this.manager.stage("evaluateAuthorizationDecisions", input)); } recordAuthorizationAuditEvents(input?: AuthorizationWorkerInput) { return this.finish(this.manager.stage("recordAuthorizationAuditEvents", input)); }
  produceAuthorizationBuildReport(input?: AuthorizationWorkerInput) { return this.finish(this.manager.produceAuthorizationBuildReport(input)); } submitReport(input?: AuthorizationWorkerInput) { return this.finish(this.manager.submitReport(input)); } list() { return this.finish(this.manager.list()); } validate(input?: AuthorizationWorkerInput) { return this.finish(this.manager.validate(input)); } diagnostics() { return this.finish(this.manager.diagnostics()); }
  private finish(result: any) { this.latest = result; this.status = result.validation?.decision === "fail" ? "failed" : "active"; return result; } getLatest() { return this.latest; } getStatus() { return this.status; }
}
