import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { AUTHORIZATION_WORKER_IDENTITY, INTEGRATION_TARGETS } from "./paths.js";
export type AuthorizationWorkerConfiguration = { enabled: boolean; timeoutMs: number; integrationTargets: string[]; workerId: string; workerName: string; factory: string; department: string; role: string; defaultDeny: true; leastPrivilege: true; neverAuthenticateUsers: true; neverReplaceAuthenticationWorker: true; neverImplementQ609OrLater: true; neverOverrideApprovedArchitecture: true; neverOverridePillow: true; neverOverrideGrandKing: true; preventPrivilegeEscalation: true; preserveAuditHistory: true; maskSensitiveValues: true; };
export const DEFAULT_AUTHORIZATION_WORKER_CONFIGURATION: AuthorizationWorkerConfiguration = { enabled: true, timeoutMs: 5000, integrationTargets: [...INTEGRATION_TARGETS], workerId: AUTHORIZATION_WORKER_IDENTITY.workerId, workerName: AUTHORIZATION_WORKER_IDENTITY.workerName, factory: AUTHORIZATION_WORKER_IDENTITY.factory, department: AUTHORIZATION_WORKER_IDENTITY.department, role: AUTHORIZATION_WORKER_IDENTITY.role, defaultDeny: true, leastPrivilege: true, neverAuthenticateUsers: true, neverReplaceAuthenticationWorker: true, neverImplementQ609OrLater: true, neverOverrideApprovedArchitecture: true, neverOverridePillow: true, neverOverrideGrandKing: true, preventPrivilegeEscalation: true, preserveAuditHistory: true, maskSensitiveValues: true };
export function buildAuthorizationWorkerConfiguration(repositoryRoot?: string, overrides: Partial<AuthorizationWorkerConfiguration> = {}): AuthorizationWorkerConfiguration {
  let file: Partial<AuthorizationWorkerConfiguration> = {}; const configPath = repositoryRoot ? join(repositoryRoot, "config", "authorization-worker.config.json") : "";
  if (configPath && existsSync(configPath)) try { file = JSON.parse(readFileSync(configPath, "utf8")); } catch { /* locked defaults are authoritative */ }
  const env = Number.parseInt(process.env.AUTHORIZATION_WORKER_TIMEOUT_MS ?? "", 10);
  return { ...DEFAULT_AUTHORIZATION_WORKER_CONFIGURATION, ...file, ...overrides, timeoutMs: Number.isFinite(env) && env > 0 ? env : Number(overrides.timeoutMs ?? file.timeoutMs ?? 5000), integrationTargets: [...new Set([...INTEGRATION_TARGETS, ...(file.integrationTargets ?? []), ...(overrides.integrationTargets ?? [])])], defaultDeny: true, leastPrivilege: true, neverAuthenticateUsers: true, neverReplaceAuthenticationWorker: true, neverImplementQ609OrLater: true, neverOverrideApprovedArchitecture: true, neverOverridePillow: true, neverOverrideGrandKing: true, preventPrivilegeEscalation: true, preserveAuditHistory: true, maskSensitiveValues: true };
}
