import type { EmpireBootstrapContext } from "../bootstrap/types.js";
import { RepositoryReader } from "../bootstrap/repository-reader.js";
import { resetAzwLogsForTesting } from "./azw-logging.js";
import { AuthorizationManager } from "./authorization-manager.js";
import { AuthorizationWorkerController } from "./authorization-worker-controller.js";
import { buildAuthorizationWorkerConfiguration, type AuthorizationWorkerConfiguration } from "./configuration.js";
import type { AuthorizationWorkerDependencies } from "./integrations.js";
import { AUTHORIZATION_WORKER_SYSTEM_PATH } from "./paths.js";
import type { AssignPermissionInput, AssignRoleInput, AuthorizationWorkerInput, CreatePermissionInput, CreatePolicyInput, CreateRoleInput, EvaluateAccessInput } from "./types.js";
export interface AuthorizationWorkerOptions { configuration?: Partial<AuthorizationWorkerConfiguration>; dependencies?: AuthorizationWorkerDependencies; }
export class AuthorizationWorker {
  private initializedAt: string | null = null; private readonly controller: AuthorizationWorkerController;
  constructor(private readonly bootstrap: EmpireBootstrapContext, options: AuthorizationWorkerOptions = {}) { const config = buildAuthorizationWorkerConfiguration(bootstrap.repositoryRoot, options.configuration); const manager = new AuthorizationManager(config); if (options.dependencies) manager.bindIntegrations(options.dependencies); this.controller = new AuthorizationWorkerController(manager, config); }
  async initialize() { const document = await new RepositoryReader(this.bootstrap.repositoryRoot).readText(AUTHORIZATION_WORKER_SYSTEM_PATH); if (!document?.includes("Authorization Worker")) throw new Error(`${AUTHORIZATION_WORKER_SYSTEM_PATH} missing — Q6-08 system doc required.`); this.controller.initialize(); this.initializedAt = new Date().toISOString(); return this.getState(); }
  bindIntegrations(dependencies?: AuthorizationWorkerDependencies) { this.controller.bindIntegrations(dependencies); } getState() { if (!this.initializedAt) throw new Error("Authorization Worker not initialized. Call initialize() first."); const report = this.controller.getLatest()?.latestAuthorizationBuildReport ?? null; return { engineVersion: "PILLOW-AZW-001", missionId: "Q6-08", status: this.controller.getStatus(), initializedAt: this.initializedAt, configuration: this.controller.configuration, latestReport: report, health: { status: report?.buildStatus === "failed" ? "failed" : "healthy", totalAuthorizationBuildReports: this.getAuthorizationBuildReports().length } }; }
  connect() { return this.controller.connect(); } receiveApprovedRequirementsReports(input?: AuthorizationWorkerInput) { return this.controller.receiveApprovedRequirementsReports(input); } receiveApprovedRequirementsReport(input?: AuthorizationWorkerInput) { return this.controller.receiveApprovedRequirementsReport(input); } receiveApprovedArchitectureReports(input?: AuthorizationWorkerInput) { return this.controller.receiveApprovedArchitectureReports(input); } receiveApprovedArchitectureReport(input?: AuthorizationWorkerInput) { return this.controller.receiveApprovedArchitectureReport(input); }
  buildRoleManagement(input?: AuthorizationWorkerInput) { return this.controller.buildRoleManagement(input); } buildPermissionManagement(input?: AuthorizationWorkerInput) { return this.controller.buildPermissionManagement(input); } buildPolicyBasedAuthorization(input?: AuthorizationWorkerInput) { return this.controller.buildPolicyBasedAuthorization(input); } buildResourceLevelAuthorization(input?: AuthorizationWorkerInput) { return this.controller.buildResourceLevelAuthorization(input); } buildActionLevelAuthorization(input?: AuthorizationWorkerInput) { return this.controller.buildActionLevelAuthorization(input); } supportInheritanceWhereDefined(input?: AuthorizationWorkerInput) { return this.controller.supportInheritanceWhereDefined(input); } evaluateAuthorizationDecisions(input?: AuthorizationWorkerInput) { return this.controller.evaluateAuthorizationDecisions(input); } recordAuthorizationAuditEvents(input?: AuthorizationWorkerInput) { return this.controller.recordAuthorizationAuditEvents(input); } produceAuthorizationBuildReport(input?: AuthorizationWorkerInput) { return this.controller.produceAuthorizationBuildReport(input); } submitReport(input?: AuthorizationWorkerInput) { return this.controller.submitReport(input); } list() { return this.controller.list(); } validate(input?: AuthorizationWorkerInput) { return this.controller.validate(input); } diagnostics() { return this.controller.diagnostics(); }
  createRole(input: CreateRoleInput) { return this.controller.manager.runtime.createRole(input); } createPermission(input: CreatePermissionInput) { return this.controller.manager.runtime.createPermission(input); } createPolicy(input: CreatePolicyInput) { return this.controller.manager.runtime.createPolicy(input); } assignRole(input: AssignRoleInput) { return this.controller.manager.runtime.assignRole(input); } assignPermission(input: AssignPermissionInput) { return this.controller.manager.runtime.assignPermission(input); } evaluateAccess(input: EvaluateAccessInput) { return this.controller.manager.runtime.evaluateAccess(input); } consumeAuthenticatedIdentity(input: { sessionToken: string }) { return this.controller.manager.runtime.consumeAuthenticatedIdentity(input); }
  getRoles() { return this.controller.manager.runtime.roles.list(); } getPermissions() { return this.controller.manager.runtime.permissions.list(); } getPolicies() { return this.controller.manager.runtime.policies.list(); } getAssignments(principalId?: string) { return this.controller.manager.runtime.assignments.list(principalId); } getAuthorizationAuditEvents(input: { limit?: number } = {}) { return this.controller.manager.runtime.audit.list(input.limit); } getAuthorizationBuildReports() { return this.controller.manager.getReports(); } getAuditTrail() { return this.controller.manager.getAuditTrail(); } getIntegrations() { return this.controller.manager.getIntegrations(); }
  getCockpitSnapshot() { const state = this.getState(); return { missionId: "Q6-08", status: state.status, healthStatus: state.health.status, totalAuthorizationBuildReports: state.health.totalAuthorizationBuildReports, workerId: state.configuration.workerId, defaultDeny: true, leastPrivilege: true, neverAuthenticateUsers: true, neverImplementQ609OrLater: true }; } validateForSupervisorSync() { const validation = this.validate({ validated: true }).validation; return { valid: validation.decision !== "fail", health: validation.decision === "pass" ? "healthy" : "degraded", readinessScore: validation.decision === "pass" ? 100 : 60, notes: validation.errors }; }
}
export const createAuthorizationWorker = (bootstrap: EmpireBootstrapContext, options?: AuthorizationWorkerOptions) => new AuthorizationWorker(bootstrap, options);
export const resetAuthorizationWorkerForTesting = () => resetAzwLogsForTesting();
