import type { ProgramRecord } from "./master-completion-ledger.js";

export type ProgramCatalogEntry = Omit<ProgramRecord, "completionPercent" | "status" | "blockers"> & {
  baseCompletionPercent: number;
};

/** MCL-001 — Static program catalog (metadata); completion computed at runtime. */
export const PROGRAM_CATALOG: ProgramCatalogEntry[] = [
  {
    programId: "foundation",
    name: "Foundation",
    baseCompletionPercent: 88,
    blocksUsd100k: false,
    remainingPackages: ["FOUNDATION-HARDENING"],
    nextCursorMission: "FOUNDATION-001 — Production env vars on Vercel",
    ownerModules: ["soul-runtime", "empire-governance", "doctrine-engine", "policy-engine", "empire-self-inspection"],
    dashboardSurface: "Mission Home · ESIS · Empire Command Center",
    operationalAccessNeeded: [],
    realWorldDependencies: ["Vercel SESSION_SECRET", "Production database persistence"],
  },
  {
    programId: "operational-access",
    name: "Operational Access",
    baseCompletionPercent: 100,
    blocksUsd100k: true,
    remainingPackages: ["REAL-002B"],
    nextCursorMission: "REAL-002B — Connect Amazon SP-API + first VERIFIED credentials (live)",
    ownerModules: ["operational-access", "reality-integration", "account-infrastructure-engine"],
    dashboardSurface: "Mission Home · Executive HQ · Operational Access (OAR-001–OAR-010)",
    operationalAccessNeeded: ["amazon-seller", "stripe", "cj-dropshipping"],
    realWorldDependencies: ["Amazon Seller Central approval", "Stripe business verification", "CJ API key"],
  },
  {
    programId: "commerce-execution",
    name: "Commerce Execution",
    baseCompletionPercent: 72,
    blocksUsd100k: true,
    remainingPackages: ["CRT-002", "PPE-LIVE-001", "REAL-LIVE-001"],
    nextCursorMission: "CRT-002 — Unblock commerce runtime publish path after activation gates",
    ownerModules: [
      "commerce-runtime",
      "product-publishing-engine",
      "order-execution-bridge",
      "marketplace-publishing",
      "listing-intelligence",
      "product-media",
      "commerce-execution-pipeline",
      "executive-visual-debate",
    ],
    dashboardSurface: "Mission Home · Commerce Runtime · Executive Visual Debate (REAL-003–REAL-007)",
    operationalAccessNeeded: ["shopify", "amazon-seller"],
    realWorldDependencies: ["Runtime plugin activation", "Founder approve activate_runtime", "Grand King listing approval"],
  },
  {
    programId: "supplier-intelligence",
    name: "Supplier Intelligence",
    baseCompletionPercent: 85,
    blocksUsd100k: true,
    remainingPackages: ["SUP-LIVE-001"],
    nextCursorMission: "SUP-LIVE-001 — CJ live catalog sync + fulfillment attach",
    ownerModules: ["supplier-intelligence", "live-cj-fulfillment", "reality-integration"],
    dashboardSurface: "Mission Home · Executive HQ · Supplier Intelligence (SUP-001–SUP-015)",
    operationalAccessNeeded: ["cj-dropshipping"],
    realWorldDependencies: ["CJ Dropshipping subscription + API production key"],
  },
  {
    programId: "product-intelligence",
    name: "Product Intelligence",
    baseCompletionPercent: 62,
    blocksUsd100k: false,
    remainingPackages: ["PI-LIVE-001"],
    nextCursorMission: "PI-LIVE-001 — Wire Eye Series signals into GKR product candidates",
    ownerModules: ["eye-series", "product-discovery-opportunity-engine", "commerce-intelligence-studio"],
    dashboardSurface: "Business Intelligence · CIS",
    operationalAccessNeeded: [],
    realWorldDependencies: ["Live marketplace catalog data for scoring calibration"],
  },
  {
    programId: "marketplace-intelligence",
    name: "Marketplace Intelligence",
    baseCompletionPercent: 58,
    blocksUsd100k: true,
    remainingPackages: ["AMZ-RS-002"],
    nextCursorMission: "AMZ-RS-002 — Amazon listing readiness with live account",
    ownerModules: ["amazon-global-seller", "commerce-intelligence-studio", "reality-integration"],
    dashboardSurface: "Mission Home · Amazon Global Seller",
    operationalAccessNeeded: ["amazon-seller"],
    realWorldDependencies: ["Amazon SP-API credentials", "Seller account health metrics"],
  },
  {
    programId: "global-expansion",
    name: "Global Expansion",
    baseCompletionPercent: 78,
    blocksUsd100k: false,
    remainingPackages: ["GCI-002", "GC-002", "REAL-LIVE-002"],
    nextCursorMission: "GCI-002 — First non-US country marketplace attach",
    ownerModules: [
      "global-commerce",
      "global-commerce-infrastructure",
      "global-commerce-intelligence",
      "global-marketplace-operations",
    ],
    dashboardSurface: "Executive HQ · Global Marketplace Operations (REAL-008–REAL-012)",
    operationalAccessNeeded: ["shopee", "lazada"],
    realWorldDependencies: ["Regional seller accounts", "Cross-border logistics partners"],
  },
  {
    programId: "live-commerce-intelligence",
    name: "Live Commerce Intelligence",
    baseCompletionPercent: 82,
    blocksUsd100k: true,
    remainingPackages: ["REAL-LIVE-003", "PROOF-001"],
    nextCursorMission: "PROOF-001 — First LIVE product with verified net profit tracking toward USD 100K",
    ownerModules: [
      "live-product-intelligence",
      "executive-product-optimization",
      "supplier-intelligence-loop",
      "global-opportunity-engine",
      "revenue-improvement-engine",
      "global-command-center",
    ],
    dashboardSurface: "Mission Home · Global Command Center (REAL-013→REAL-018)",
    operationalAccessNeeded: ["amazon-seller", "cj-dropshipping", "stripe"],
    realWorldDependencies: ["Live product metrics feed", "Grand King approval on improvement queue"],
  },
  {
    programId: "empire-economics",
    name: "Empire Economics",
    baseCompletionPercent: 85,
    blocksUsd100k: true,
    remainingPackages: ["ECON-LIVE-001"],
    nextCursorMission: "ECON-LIVE-001 — Attach live Stripe + supplier COGS to REAL-019",
    ownerModules: ["empire-economics", "grand-king-financial-command-center", "kpi-engine", "financial-forecast-intelligence"],
    dashboardSurface: "Mission Home · Grand King Financial Command Center (REAL-019→REAL-020)",
    operationalAccessNeeded: ["stripe"],
    realWorldDependencies: ["Real revenue and COGS data", "Accounting export integration"],
  },
  {
    programId: "version-1-completion",
    name: "Version 1 Completion",
    baseCompletionPercent: 88,
    blocksUsd100k: true,
    remainingPackages: ["PROOF-001", "REAL-002B"],
    nextCursorMission: "PROOF-001 — First LIVE product with verified net profit toward USD 100K",
    ownerModules: [
      "founder-platform-preparation",
      "ai-self-improvement-engine",
      "version-2-backlog-engine",
      "version-1-readiness-audit",
      "version-1-lockdown",
    ],
    dashboardSurface: "Mission Home · Version 1 Readiness + Lockdown (REAL-021→REAL-025)",
    operationalAccessNeeded: ["amazon-seller", "stripe", "cj-dropshipping"],
    realWorldDependencies: ["Live credentials", "Version 1 baseline lock approval"],
  },
  {
    programId: "commercial-operating-system",
    name: "Commercial Operating System",
    baseCompletionPercent: 90,
    blocksUsd100k: true,
    remainingPackages: ["PROOF-001", "REAL-002B", "ECON-LIVE-001"],
    nextCursorMission: "PROOF-001 — First LIVE product with verified net profit toward USD 100K",
    ownerModules: [
      "customer-intelligence",
      "competitor-intelligence",
      "customer-psychology-engine",
      "global-category-expansion-engine",
      "global-revenue-simulation",
      "ai-chief-of-commerce",
      "ai-chief-of-growth",
      "ai-chief-of-customer",
      "global-strategy-engine",
      "success-001-command-center",
    ],
    dashboardSurface: "Mission Home · SUCCESS-001 Command Center (REAL-026→REAL-035)",
    operationalAccessNeeded: ["amazon-seller", "stripe", "cj-dropshipping"],
    realWorldDependencies: ["Live customer data", "Verified net profit", "Grand King launch approval"],
  },
  {
    programId: "v1-production-go-live",
    name: "V1 Production + Grand King Go-Live",
    baseCompletionPercent: 92,
    blocksUsd100k: true,
    remainingPackages: ["PROOF-001", "REAL-002B", "GK-GOLIVE-APPROVAL"],
    nextCursorMission: "PROOF-001 — First verified net profit + Grand King go-live approval",
    ownerModules: [
      "grand-king-live-operations-mode",
      "global-operational-command-center",
      "global-advertising-intelligence",
      "first-order-operations",
      "global-order-intelligence",
      "post-purchase-intelligence",
      "global-knowledge-evolution",
      "ai-strategic-memory",
      "empire-playbook-engine",
      "global-risk-command",
      "founder-platform-readiness",
      "production-hardening",
      "version-1-acceptance-test",
      "grand-king-go-live-checklist",
      "version-1-gold-master",
    ],
    dashboardSurface: "Mission Home · Empire Headquarters (REAL-036→REAL-050)",
    operationalAccessNeeded: ["amazon-seller", "stripe", "cj-dropshipping"],
    realWorldDependencies: ["Grand King go-live approval", "Live operations mode PRODUCTION", "Verified net profit"],
  },
  {
    programId: "executive-intelligence",
    name: "Executive Intelligence",
    baseCompletionPercent: 76,
    blocksUsd100k: false,
    remainingPackages: ["EC-011"],
    nextCursorMission: "EC-011 — King approval workflow UI for pipeline products",
    ownerModules: ["executive-council", "executive-surveillance", "commerce-intelligence-studio"],
    dashboardSurface: "Mission Home · Executive Council · ESS",
    operationalAccessNeeded: [],
    realWorldDependencies: ["Founder decision latency for KING_APPROVAL products"],
  },
  {
    programId: "frontend-ux",
    name: "Frontend / UX Experience",
    baseCompletionPercent: 71,
    blocksUsd100k: false,
    remainingPackages: ["UX-001"],
    nextCursorMission: "UX-001 — King approval + operational access detail pages",
    ownerModules: ["frontend"],
    dashboardSurface: "Mission Home · 12 routed dashboard pages",
    operationalAccessNeeded: [],
    realWorldDependencies: ["OAuth callback routes for provider connect flows"],
  },
  {
    programId: "autonomy-heartbeat",
    name: "Autonomy / Heartbeat",
    baseCompletionPercent: 48,
    blocksUsd100k: false,
    remainingPackages: ["AUTO-001"],
    nextCursorMission: "AUTO-001 — Grand King scheduler with live connector heartbeat",
    ownerModules: ["founder-automation", "grand-king", "scheduler-workers"],
    dashboardSurface: "Mission Home · Founder Automation",
    operationalAccessNeeded: [],
    realWorldDependencies: ["Production cron / worker runtime on Vercel or external scheduler"],
  },
  {
    programId: "proof-of-money",
    name: "Proof of Money",
    baseCompletionPercent: 38,
    blocksUsd100k: true,
    remainingPackages: ["GKR-011", "PROOF-001"],
    nextCursorMission: "PROOF-001 — First LIVE product with verified net profit tracking toward USD 100K",
    ownerModules: ["grand-king-revenue-pipeline", "operation-first-dollar", "first-revenue-validation"],
    dashboardSurface: "Mission Home · GKR · Operation First Dollar",
    operationalAccessNeeded: ["stripe", "amazon-seller", "cj-dropshipping"],
    realWorldDependencies: ["Live sale", "Fulfillment", "Net profit accounting to SUCCESS-001 target"],
  },
  {
    programId: "v1-absolute-completion",
    name: "V1 Absolute Completion (Grand King Live Commerce)",
    baseCompletionPercent: 98,
    blocksUsd100k: true,
    remainingPackages: ["PROOF-001", "REAL-002B", "GK-GOLIVE-APPROVAL"],
    nextCursorMission: "REAL-099 — Version 1 go-live approval recommendation after live credentials",
    ownerModules: [
      "global-supplier-market",
      "global-marketplace-adapter-framework",
      "marketplace-difference-engine",
      "country-difference-engine",
      "global-price-intelligence",
      "shipping-intelligence",
      "product-launch-commander",
      "post-launch-commander",
      "product-scale-engine",
      "product-retirement-engine",
      "empire-revenue-forecast",
      "empire-cashflow-engine",
      "empire-investment-engine",
      "global-opportunity-board",
      "executive-strategy-room",
      "king-decision-history",
      "soul-learning-review",
      "empire-pattern-library",
      "global-expansion-score",
      "empire-priority-engine",
      "command-center-polish",
      "ux-review-preparation",
      "performance-review",
      "security-review",
      "architecture-review",
      "commercial-review",
      "version-1-freeze-review",
      "version-1-release-candidate",
      "version-1-go-live-approval",
      "version-1-completion",
    ],
    dashboardSurface: "Mission Home · Global Opportunity Board (REAL-084) · V1 Completion (REAL-100)",
    operationalAccessNeeded: ["amazon-seller", "stripe", "cj-dropshipping"],
    realWorldDependencies: ["PROOF-001 verified net profit", "Grand King go-live sign-off", "Live marketplace credentials"],
  },
  {
    programId: "core-constitution",
    name: "Core Constitution (CTD)",
    baseCompletionPercent: 100,
    blocksUsd100k: false,
    remainingPackages: [],
    nextCursorMission: "Empire Review validates CTD compliance on every review cycle",
    ownerModules: ["empire-constitution", "doctrine-engine", "empire-governance"],
    dashboardSurface: "Foundation · GET /empire-constitution/dashboard · ESIS review package",
    operationalAccessNeeded: [],
    realWorldDependencies: [],
  },
  {
    programId: "core-governance-doctrine",
    name: "Governance Doctrine (GVD)",
    baseCompletionPercent: 100,
    blocksUsd100k: false,
    remainingPackages: [],
    nextCursorMission: "Empire Review validates GVD compliance — violations fail review per GVD-029",
    ownerModules: ["empire-governance-doctrine", "empire-governance", "grand-king"],
    dashboardSurface: "Foundation · GET /empire-governance-doctrine/dashboard · ESIS review package",
    operationalAccessNeeded: [],
    realWorldDependencies: [],
  },
  {
    programId: "core-architecture-constraints",
    name: "Architecture Constraints (ACD)",
    baseCompletionPercent: 100,
    blocksUsd100k: false,
    remainingPackages: [],
    nextCursorMission: "Empire Review validates ACD compliance — violations fail review per ACD-030",
    ownerModules: ["empire-architecture-constraints", "empire-self-inspection", "architecture-review"],
    dashboardSurface: "Foundation · GET /empire-architecture-constraints/dashboard · ESIS review package",
    operationalAccessNeeded: [],
    realWorldDependencies: [],
  },
  {
    programId: "core-ux-identity-doctrine",
    name: "UX & Identity Doctrine (UID)",
    baseCompletionPercent: 100,
    blocksUsd100k: false,
    remainingPackages: [],
    nextCursorMission: "Empire Review validates UID compliance — identity + navigation on every review",
    ownerModules: ["empire-ux-identity-doctrine", "mission-home", "success-001"],
    dashboardSurface: "Foundation · GET /empire-ux-identity-doctrine/dashboard · Mission Home",
    operationalAccessNeeded: [],
    realWorldDependencies: [],
  },
  {
    programId: "core-commercial-business-doctrine",
    name: "Commercial Business Doctrine (CBD)",
    baseCompletionPercent: 100,
    blocksUsd100k: false,
    remainingPackages: [],
    nextCursorMission: "Empire Review validates CBD compliance — commercial integrity on every review",
    ownerModules: ["empire-commercial-business-doctrine", "empire-economics", "supplier-intelligence"],
    dashboardSurface: "Foundation · GET /empire-commercial-business-doctrine/dashboard · SUCCESS-001",
    operationalAccessNeeded: [],
    realWorldDependencies: ["PROOF-001 verified net profit toward USD 100K"],
  },
];
