import type { EmpireIntelligenceFrameworkEngine } from "../empire-intelligence-framework/engine.js";
import type { EmpireKnowledgeEngine } from "../empire-knowledge-engine/engine.js";
import type { EmpireMemoryEngine } from "../empire-memory-engine/engine.js";
import type { EmpireSelfImprovementEngineConfiguration } from "./configuration.js";
import { EMPIRE_SELF_IMPROVEMENT_ENGINE_ID, ESI_CAPABILITIES, ESI_METADATA_VERSION } from "./paths.js";
import type { EmpireSelfImprovementEngineRecord, EmpireSelfImprovementInput, EmpireSelfImprovementRunReport, SelfImprovementRecommendation, SelfImprovementRecord, SelfImprovementValidationReport } from "./types.js";
export type EmpireSelfImprovementDependencies = { empireIntelligenceFramework?: EmpireIntelligenceFrameworkEngine | null; empireMemoryEngine?: EmpireMemoryEngine | null; empireKnowledgeEngine?: EmpireKnowledgeEngine | null };
export class EmpireSelfImprovementManager {
  private engineRecord: EmpireSelfImprovementEngineRecord | null = null; private records: SelfImprovementRecord[] = []; private recommendations: SelfImprovementRecommendation[] = [];
  constructor(private readonly dependencies: EmpireSelfImprovementDependencies = {}) {}
  getEngineRecord() { return this.engineRecord ? { ...this.engineRecord, dependencyPresence: { ...this.engineRecord.dependencyPresence } } : null; }
  getSelfImprovementRecords() { return this.records.map((r) => ({ ...r })); } getRecommendations() { return this.recommendations.map((r) => ({ ...r })); }
  private validation(input: EmpireSelfImprovementInput): SelfImprovementValidationReport { const validated = input.validated === true; return { validationReportId: `esi-val-${Date.now()}`, validationTimestamp: new Date().toISOString(), decision: validated ? "pass" : "partial", errors: [], warnings: validated ? [] : ["Structural signal is not independently validated; governance-approved architecture remains unchanged."], durationMs: 0, metadataVersion: ESI_METADATA_VERSION }; }
  private report(action: string, records: SelfImprovementRecord[], validation: SelfImprovementValidationReport): EmpireSelfImprovementRunReport { return { selfImprovementRunReportId: `esi-run-${Date.now()}`, runTimestamp: new Date().toISOString(), action, engineRecord: this.engineRecord!, selfImprovementRecords: records, recommendations: this.getRecommendations(), validation, durationMs: 0, metadataVersion: ESI_METADATA_VERSION }; }
  connect(_input: Record<string, unknown>, _config: EmpireSelfImprovementEngineConfiguration): EmpireSelfImprovementRunReport {
    const framework = this.dependencies.empireIntelligenceFramework; let frameworkModuleId: string | null = null;
    if (framework) { const registration = framework.registerEmpireIntelligenceModule({ definition: { intelligenceModuleIdentifier: EMPIRE_SELF_IMPROVEMENT_ENGINE_ID, moduleVersion: "PILLOW-ESI-001", moduleType: "intelligence", supportedCapabilities: ["health_monitoring"] }, forceRegister: true }); frameworkModuleId = registration.records[0]?.frameworkId ?? null; if (registration.validation.decision !== "fail") framework.manageEnterpriseIntelligenceLifecycle(EMPIRE_SELF_IMPROVEMENT_ENGINE_ID, "start"); }
    this.engineRecord = { engineRecordId: `esi-eng-${Date.now()}`, timestamp: new Date().toISOString(), engineId: EMPIRE_SELF_IMPROVEMENT_ENGINE_ID, engineVersion: "PILLOW-ESI-001", currentOperationalState: "connected", healthStatus: framework ? "healthy" : "degraded", validationStatus: framework ? "passed" : "partial", supportedCapabilities: [...ESI_CAPABILITIES], frameworkModuleId, dependencyPresence: { empireIntelligenceFramework: Boolean(framework), empireMemoryEngine: Boolean(this.dependencies.empireMemoryEngine), empireKnowledgeEngine: Boolean(this.dependencies.empireKnowledgeEngine) }, metadataVersion: ESI_METADATA_VERSION };
    return this.report("connect", [], this.validation({ validated: Boolean(framework) }));
  }
  run(action: string, input: EmpireSelfImprovementInput, config: EmpireSelfImprovementEngineConfiguration): EmpireSelfImprovementRunReport {
    if (!this.engineRecord) throw new Error("Empire Self-Improvement Engine not connected — call connectEmpireSelfImprovementEngine first");
    if (action === "recommend") { this.recommendations = this.records.filter((r) => r.priorityScore >= config.recommendationThreshold).map((r) => ({ recommendationId: `esi-rec-${r.selfImprovementId}`, timestamp: new Date().toISOString(), selfImprovementId: r.selfImprovementId, recommendationSummary: r.recommendationSummary, priorityScore: r.priorityScore, structuralSignalOnly: true, neverModifyGovernanceApprovedArchitectureAutomatically: true, neverBypassConstitutionalGovernance: true, approvedForArchitectureModification: false })); return this.report(action, [], this.validation({ validated: true })); }
    const validation = this.validation(input), currentPerformance = Math.max(0, Math.min(100, input.currentPerformance ?? 50)), expectedImprovement = Math.max(0, Math.min(100, input.expectedImprovement ?? 10)), priorityScore = Math.max(0, Math.min(100, input.priorityScore ?? 50));
    const record: SelfImprovementRecord = { selfImprovementId: `esi-${Date.now()}-${this.records.length}`, timestamp: new Date().toISOString(), companyReference: input.companyReference?.trim() || "unspecified enterprise", improvementCategory: input.improvementCategory?.trim() || action.replaceAll("_", " "), currentPerformance, expectedImprovement, priorityScore, recommendationSummary: input.recommendationSummary?.trim() || `Review improvement signal for ${input.companyReference?.trim() || "enterprise"}`, validationStatus: validation.decision === "pass" ? "passed" : "partial", metadataVersion: ESI_METADATA_VERSION, structuralSignalOnly: true, neverModifyGovernanceApprovedArchitectureAutomatically: true, neverBypassConstitutionalGovernance: true, preserveImprovementTraceability: true, preserveAuditability: true, preserveEnterpriseIntegrity: true, improvementTraceId: `esi-trace-${Date.now()}-${this.records.length}`, approvedForArchitectureModification: false, maskSensitiveValues: true };
    this.records.push(record); this.engineRecord.currentOperationalState = "active"; this.engineRecord.timestamp = record.timestamp; return this.report(action, [record], validation);
  }
  diagnostics(config: EmpireSelfImprovementEngineConfiguration) { return this.engineRecord ? this.report("diagnostics", this.records, { ...this.validation({ validated: config.enabled }), decision: config.enabled ? "pass" : "fail", errors: config.enabled ? [] : ["Engine disabled"] }) : this.connect({}, config); }
}
