import type { EmpireBootstrapContext } from "../bootstrap/types.js";
import { RepositoryReader } from "../bootstrap/repository-reader.js";
import { buildEmpireSelfImprovementEngineConfiguration, type EmpireSelfImprovementEngineConfiguration } from "./configuration.js";
import { EmpireSelfImprovementController } from "./empire-self-improvement-controller.js";
import { EmpireSelfImprovementManager, type EmpireSelfImprovementDependencies } from "./empire-self-improvement-manager.js";
import { EMPIRE_SELF_IMPROVEMENT_ENGINE_SYSTEM_PATH } from "./paths.js";
import type { EmpireSelfImprovementCockpitSnapshot, EmpireSelfImprovementInput, EmpireSelfImprovementState } from "./types.js";
export type { EmpireSelfImprovementDependencies }; export interface EmpireSelfImprovementEngineOptions { configuration?: Partial<EmpireSelfImprovementEngineConfiguration>; }
export class EmpireSelfImprovementEngine {
  private initializedAt: string | null = null; private readonly controller: EmpireSelfImprovementController;
  constructor(private readonly bootstrap: EmpireBootstrapContext, dependencies: EmpireSelfImprovementDependencies = {}, options: EmpireSelfImprovementEngineOptions = {}) { this.controller = new EmpireSelfImprovementController(new EmpireSelfImprovementManager(dependencies), buildEmpireSelfImprovementEngineConfiguration(bootstrap.repositoryRoot, options.configuration)); }
  async initialize() { const doc = await new RepositoryReader(this.bootstrap.repositoryRoot).readText(EMPIRE_SELF_IMPROVEMENT_ENGINE_SYSTEM_PATH); if (!doc?.includes("Empire Self-Improvement Engine")) throw new Error(`${EMPIRE_SELF_IMPROVEMENT_ENGINE_SYSTEM_PATH} missing — X5-09 system doc required.`); this.controller.initialize(); this.initializedAt = new Date().toISOString(); return this.getState(); }
  getState(): EmpireSelfImprovementState { if (!this.initializedAt) throw new Error("Empire Self-Improvement Engine not initialized. Call initialize() first."); const configuration = this.controller.getConfiguration(), engineRecord = this.controller.getManager().getEngineRecord(), latestReport = this.controller.getLatestReport(), count = this.getSelfImprovementRecords().length; return { engineVersion: "PILLOW-ESI-001", missionId: "X5-09", status: this.controller.getStatus(), initializedAt: this.initializedAt, configuration, latestReport, engineRecord, health: { status: engineRecord?.healthStatus ?? "standby", healthScore: engineRecord?.healthStatus === "healthy" ? 100 : engineRecord ? 70 : 50, engineEnabled: configuration.enabled, lastOperationAt: latestReport?.runTimestamp ?? null, lastValidationDecision: latestReport?.validation.decision ?? null, totalSelfImprovementRecords: count, notes: ["Structural signals and recommendations only; governance-approved architecture is never modified automatically."] } }; }
  connectEmpireSelfImprovementEngine(input: Record<string, unknown> = {}) { return this.controller.connect(input); }
  monitorEnterprisePerformance(input: EmpireSelfImprovementInput = {}) { return this.controller.run("monitor_enterprise_performance", input); } monitorOperationalEfficiency(input: EmpireSelfImprovementInput = {}) { return this.controller.run("monitor_operational_efficiency", input); } identifyImprovementOpportunities(input: EmpireSelfImprovementInput = {}) { return this.controller.run("identify_improvement_opportunities", input); } evaluateImprovementProposals(input: EmpireSelfImprovementInput = {}) { return this.controller.run("evaluate_improvement_proposals", input); } measureImprovementOutcomes(input: EmpireSelfImprovementInput = {}) { return this.controller.run("measure_improvement_outcomes", input); } learnFromPreviousImprovements(input: EmpireSelfImprovementInput = {}) { return this.controller.run("learn_from_previous_improvements", input); } rankImprovementPriorities(input: EmpireSelfImprovementInput = {}) { return this.controller.run("rank_improvement_priorities", input); } recommendSelfImprovements(input: EmpireSelfImprovementInput = {}) { return this.controller.run("recommend", input); } trackContinuousEvolution(input: EmpireSelfImprovementInput = {}) { return this.controller.run("track_continuous_evolution", input); }
  runDiagnostics() { return this.controller.diagnostics(); } getSelfImprovementRecords() { return this.controller.getManager().getSelfImprovementRecords(); } getRecommendations() { return this.controller.getManager().getRecommendations(); } getEngineRecord() { return this.controller.getManager().getEngineRecord(); }
  validateForSupervisorSync() { const state = this.getState(), score = state.latestReport?.validation.decision === "fail" ? 40 : state.latestReport?.validation.decision === "partial" ? 70 : 100; return { valid: state.health.status !== "failed", health: score >= 75 ? "healthy" as const : score >= 50 ? "degraded" as const : "blocked" as const, readinessScore: score, notes: [`Engine status: ${state.status}`, `Self-improvement records: ${state.health.totalSelfImprovementRecords}`, ...state.health.notes] }; }
  getCockpitSnapshot(): EmpireSelfImprovementCockpitSnapshot { const state = this.getState(), record = state.engineRecord; return { engineStatus: state.status, healthStatus: state.health.status, operationalState: record?.currentOperationalState ?? null, lastDecision: state.latestReport?.validation.decision ?? null, totalSelfImprovementRecords: state.health.totalSelfImprovementRecords, frameworkRegistered: Boolean(record?.frameworkModuleId), dependenciesConnected: Number(Boolean(record?.dependencyPresence.empireIntelligenceFramework)) + Number(Boolean(record?.dependencyPresence.empireMemoryEngine)) + Number(Boolean(record?.dependencyPresence.empireKnowledgeEngine)), recentLogs: [] }; }
}
export function createEmpireSelfImprovementEngine(bootstrap: EmpireBootstrapContext, dependencies: EmpireSelfImprovementDependencies = {}, options?: EmpireSelfImprovementEngineOptions) { return new EmpireSelfImprovementEngine(bootstrap, dependencies, options); } export function resetEmpireSelfImprovementEngineForTesting() {}
