import type { EmpireSelfImprovementEngineConfiguration } from "./configuration.js";
import type { ESI_CAPABILITIES, ENGINE_STATUSES, HEALTH_STATUSES, OPERATIONAL_STATES, VALIDATION_STATUSES } from "./paths.js";
export type EngineStatus = (typeof ENGINE_STATUSES)[number]; export type OperationalState = (typeof OPERATIONAL_STATES)[number];
export type ValidationStatus = (typeof VALIDATION_STATUSES)[number]; export type HealthStatus = (typeof HEALTH_STATUSES)[number];
export type EmpireSelfImprovementCapability = (typeof ESI_CAPABILITIES)[number];
export type EmpireSelfImprovementInput = { companyReference?: string; improvementCategory?: string; currentPerformance?: number; expectedImprovement?: number; priorityScore?: number; recommendationSummary?: string; validated?: boolean; approvedForArchitectureModification?: boolean; };
export type SelfImprovementRecord = {
  selfImprovementId: string; timestamp: string; companyReference: string; improvementCategory: string; currentPerformance: number; expectedImprovement: number; priorityScore: number; recommendationSummary: string; validationStatus: ValidationStatus; metadataVersion: string;
  structuralSignalOnly: true; neverModifyGovernanceApprovedArchitectureAutomatically: true; neverBypassConstitutionalGovernance: true; preserveImprovementTraceability: true; preserveAuditability: true; preserveEnterpriseIntegrity: true; improvementTraceId: string; approvedForArchitectureModification: false; maskSensitiveValues: true;
};
export type SelfImprovementRecommendation = { recommendationId: string; timestamp: string; selfImprovementId: string; recommendationSummary: string; priorityScore: number; structuralSignalOnly: true; neverModifyGovernanceApprovedArchitectureAutomatically: true; neverBypassConstitutionalGovernance: true; approvedForArchitectureModification: false; };
export type SelfImprovementValidationReport = { validationReportId: string; validationTimestamp: string; decision: "pass" | "partial" | "fail"; errors: string[]; warnings: string[]; durationMs: number; metadataVersion: string; };
export type EmpireSelfImprovementEngineRecord = { engineRecordId: string; timestamp: string; engineId: string; engineVersion: "PILLOW-ESI-001"; currentOperationalState: OperationalState; healthStatus: HealthStatus; validationStatus: ValidationStatus; supportedCapabilities: EmpireSelfImprovementCapability[]; frameworkModuleId: string | null; dependencyPresence: { empireIntelligenceFramework: boolean; empireMemoryEngine: boolean; empireKnowledgeEngine: boolean }; metadataVersion: string; };
export type EmpireSelfImprovementRunReport = { selfImprovementRunReportId: string; runTimestamp: string; action: string; engineRecord: EmpireSelfImprovementEngineRecord; selfImprovementRecords: SelfImprovementRecord[]; recommendations: SelfImprovementRecommendation[]; validation: SelfImprovementValidationReport; durationMs: number; metadataVersion: string; };
export type EmpireSelfImprovementState = { engineVersion: "PILLOW-ESI-001"; missionId: "X5-09"; status: EngineStatus; initializedAt: string; configuration: EmpireSelfImprovementEngineConfiguration; latestReport: EmpireSelfImprovementRunReport | null; engineRecord: EmpireSelfImprovementEngineRecord | null; health: { status: HealthStatus; healthScore: number; engineEnabled: boolean; lastOperationAt: string | null; lastValidationDecision: SelfImprovementValidationReport["decision"] | null; totalSelfImprovementRecords: number; notes: string[] }; };
export type EmpireSelfImprovementCockpitSnapshot = { engineStatus: EngineStatus; healthStatus: HealthStatus; operationalState: OperationalState | null; lastDecision: SelfImprovementValidationReport["decision"] | null; totalSelfImprovementRecords: number; frameworkRegistered: boolean; dependenciesConnected: number; recentLogs: string[]; };
