import type { RegisteredTool } from "../../brain/types.js";
import {
  loadAdminView,
  loadAdsView,
  loadAiCeoView,
  loadDashboardView,
  loadFinanceView,
  loadIntegrationsView,
  loadIntelligenceView,
  loadMarketingView,
  loadOrdersView,
  loadSettingsView,
  loadStoreView,
  loadSuppliersView,
  loadSupportView,
} from "../../domain/services/module-views.js";

export const moduleLoadTools: RegisteredTool[] = [
  {
    name: "dashboard.load_view",
    description: "Load founder dashboard view data from domain store",
    module: "dashboard",
    authorityLevel: "L0",
    parameters: {
      type: "object",
      properties: { workspaceId: { type: "string" } },
      required: ["workspaceId"],
    },
    handler: async (_args, context) => loadDashboardView(context.workspaceId),
  },
  {
    name: "ai-ceo.load_view",
    description: "Load AI CEO briefing view data",
    module: "ai-ceo",
    authorityLevel: "L0",
    parameters: {
      type: "object",
      properties: { workspaceId: { type: "string" } },
      required: ["workspaceId"],
    },
    handler: async (_args, context) => loadAiCeoView(context.workspaceId),
  },
  {
    name: "intelligence.load_view",
    description: "Load product intelligence view data",
    module: "intelligence",
    authorityLevel: "L0",
    parameters: { type: "object", properties: {} },
    handler: async (_args, context) => loadIntelligenceView(context.workspaceId),
  },
  {
    name: "suppliers.load_view",
    description: "Load supplier network view data",
    module: "suppliers",
    authorityLevel: "L0",
    parameters: { type: "object", properties: {} },
    handler: async (_args, context) => loadSuppliersView(context.workspaceId),
  },
  {
    name: "store.load_view",
    description: "Load store builder view data",
    module: "store",
    authorityLevel: "L0",
    parameters: { type: "object", properties: {} },
    handler: async (_args, context) => loadStoreView(context.workspaceId),
  },
  {
    name: "marketing.load_view",
    description: "Load marketing AI view data",
    module: "marketing",
    authorityLevel: "L0",
    parameters: { type: "object", properties: {} },
    handler: async (_args, context) => loadMarketingView(context.workspaceId),
  },
  {
    name: "ads.load_view",
    description: "Load ad manager view data",
    module: "ads",
    authorityLevel: "L0",
    parameters: { type: "object", properties: {} },
    handler: async (_args, context) => loadAdsView(context.workspaceId),
  },
  {
    name: "finance.load_view",
    description: "Load finance view data",
    module: "finance",
    authorityLevel: "L0",
    parameters: { type: "object", properties: {} },
    handler: async (_args, context) => loadFinanceView(context.workspaceId),
  },
  {
    name: "orders.load_view",
    description: "Load orders view data",
    module: "orders",
    authorityLevel: "L0",
    parameters: { type: "object", properties: {} },
    handler: async (_args, context) => loadOrdersView(context.workspaceId),
  },
  {
    name: "support.load_view",
    description: "Load support view data",
    module: "support",
    authorityLevel: "L0",
    parameters: { type: "object", properties: {} },
    handler: async (_args, context) => loadSupportView(context.workspaceId),
  },
  {
    name: "settings.load_view",
    description: "Load settings view data",
    module: "settings",
    authorityLevel: "L0",
    parameters: { type: "object", properties: {} },
    handler: async (_args, context) => loadSettingsView(context.workspaceId),
  },
  {
    name: "admin.load_view",
    description: "Load admin console view data",
    module: "admin",
    authorityLevel: "L0",
    parameters: { type: "object", properties: {} },
    handler: async () => loadAdminView(),
  },
  {
    name: "integrations.load_view",
    description: "Load integrations grid with live connector truth",
    module: "integrations",
    authorityLevel: "L0",
    parameters: { type: "object", properties: {} },
    handler: async (_args, context) => loadIntegrationsView(context.workspaceId),
  },
];
