/**
 * G7 — Grand King operational Brain tool routes (Pillow Completion STEP 4).
 * Exposes existing G7 tools without rewriting handlers.
 */

import type { ModuleRoute } from "../../brain/orchestrator.js";

function toolRoutes(
  module: string,
  tools: Array<{ action: string; toolName: string }>,
): ModuleRoute[] {
  return tools.map(({ action, toolName }) => ({ module, action, toolName }));
}

export const g7ModuleRoutes: ModuleRoute[] = [
  ...toolRoutes("grand-king-live-operations", [
    { action: "overview", toolName: "live_operations_overview" },
    { action: "status", toolName: "live_operation_status" },
    { action: "start", toolName: "start_live_operation" },
    { action: "pause", toolName: "pause_live_operation" },
    { action: "resume", toolName: "resume_live_operation" },
    { action: "block", toolName: "block_live_operation" },
    { action: "evidence", toolName: "live_operation_evidence" },
    { action: "risks", toolName: "live_operation_risks" },
    { action: "next_action", toolName: "live_operation_next_action" },
    { action: "launch_status", toolName: "live_launch_status" },
    { action: "run_certification", toolName: "run_live_launch_certification" },
    { action: "launch_readiness", toolName: "grand_king_launch_readiness" },
    { action: "launch_operation_health", toolName: "live_operation_health" },
    { action: "launch_blockers", toolName: "launch_blockers" },
    { action: "launch_conditions", toolName: "launch_conditions" },
    { action: "launch_risk_register", toolName: "launch_risk_register" },
    { action: "version1_launch_summary", toolName: "version1_launch_summary" },
  ]),
  ...toolRoutes("grand-king-production-workspace", [
    { action: "overview", toolName: "workspace_overview" },
    { action: "status", toolName: "workspace_status" },
    { action: "health", toolName: "workspace_health" },
    { action: "readiness", toolName: "workspace_readiness" },
    { action: "configuration", toolName: "workspace_configuration" },
    { action: "dependencies", toolName: "workspace_dependencies" },
    { action: "summary", toolName: "workspace_summary" },
    { action: "create", toolName: "create_grand_king_production_workspace" },
    { action: "activate", toolName: "activate_grand_king_production_workspace" },
  ]),
  ...toolRoutes("grand-king-commerce-operations", [
    { action: "overview", toolName: "commerce_operations_overview" },
    { action: "status", toolName: "commerce_operation_status" },
    { action: "start", toolName: "start_commerce_operation" },
    { action: "pause", toolName: "pause_commerce_operation" },
    { action: "resume", toolName: "resume_commerce_operation" },
    { action: "stop", toolName: "stop_commerce_operation" },
    { action: "health", toolName: "commerce_operation_health" },
    { action: "dependencies", toolName: "commerce_operation_dependencies" },
    { action: "summary", toolName: "commerce_operation_summary" },
    { action: "initialize", toolName: "initialize_grand_king_commerce_operations" },
  ]),
  ...toolRoutes("grand-king-business-automation-operations", [
    { action: "overview", toolName: "automation_operations_overview" },
    { action: "status", toolName: "automation_operation_status" },
    { action: "start", toolName: "start_automation_operation" },
    { action: "pause", toolName: "pause_automation_operation" },
    { action: "resume", toolName: "resume_automation_operation" },
    { action: "cancel", toolName: "cancel_automation_operation" },
    { action: "health", toolName: "automation_operation_health" },
    { action: "dependencies", toolName: "automation_operation_dependencies" },
    { action: "summary", toolName: "automation_operation_summary" },
    { action: "initialize", toolName: "initialize_grand_king_automation_operations" },
  ]),
  ...toolRoutes("grand-king-executive-decision-centre", [
    { action: "overview", toolName: "executive_overview" },
    { action: "health", toolName: "executive_health" },
    { action: "decisions", toolName: "executive_decisions" },
    { action: "recommendations", toolName: "executive_recommendations" },
    { action: "blockers", toolName: "executive_blockers" },
    { action: "opportunities", toolName: "executive_opportunities" },
    { action: "notifications", toolName: "executive_notifications" },
    { action: "timeline", toolName: "executive_timeline" },
    { action: "summary", toolName: "executive_summary" },
    { action: "execute_decision", toolName: "execute_executive_decision" },
    { action: "initialize", toolName: "initialize_grand_king_executive_decision_centre" },
    { action: "dependencies", toolName: "executive_dependencies" },
  ]),
  ...toolRoutes("grand-king-revenue-financial-operations", [
    { action: "overview", toolName: "financial_overview" },
    { action: "summary", toolName: "financial_summary" },
    { action: "dashboard", toolName: "financial_dashboard" },
    { action: "profitability", toolName: "profitability_report" },
    { action: "cash_position", toolName: "cash_position" },
    { action: "advertising_roi", toolName: "advertising_roi" },
    { action: "subscription_metrics", toolName: "subscription_metrics" },
    { action: "risk_register", toolName: "financial_risk_register" },
    { action: "status", toolName: "financial_status" },
    { action: "initialize", toolName: "initialize_grand_king_revenue_financial_operations" },
    { action: "dependencies", toolName: "financial_dependencies" },
    { action: "health", toolName: "financial_health" },
    { action: "records", toolName: "financial_records" },
    { action: "payouts", toolName: "financial_payouts" },
  ]),
  ...toolRoutes("grand-king-continuous-intelligence-optimization", [
    { action: "overview", toolName: "optimization_overview" },
    { action: "opportunities", toolName: "optimization_opportunities" },
    { action: "recommendations", toolName: "optimization_recommendations" },
    { action: "priority_queue", toolName: "optimization_priority_queue" },
    { action: "roi", toolName: "optimization_roi" },
    { action: "status", toolName: "optimization_status" },
    { action: "history", toolName: "optimization_history" },
    { action: "summary", toolName: "optimization_summary" },
    { action: "initialize", toolName: "initialize_grand_king_continuous_intelligence_optimization" },
    { action: "dependencies", toolName: "optimization_dependencies" },
    { action: "approve", toolName: "approve_optimization" },
    { action: "execute", toolName: "execute_optimization" },
  ]),
  ...toolRoutes("grand-king-autonomous-operations", [
    { action: "overview", toolName: "autonomous_operations_overview" },
    { action: "status", toolName: "autonomous_operation_status" },
    { action: "queue", toolName: "autonomous_operation_queue" },
    { action: "history", toolName: "autonomous_operation_history" },
    { action: "health", toolName: "autonomous_operation_health" },
    { action: "pause", toolName: "autonomous_operation_pause" },
    { action: "resume", toolName: "autonomous_operation_resume" },
    { action: "cancel", toolName: "autonomous_operation_cancel" },
    { action: "summary", toolName: "autonomous_operation_summary" },
    { action: "initialize", toolName: "initialize_grand_king_autonomous_operations" },
    { action: "dependencies", toolName: "autonomous_operation_dependencies" },
    { action: "recommendations", toolName: "autonomous_operation_recommendations" },
  ]),
  ...toolRoutes("grand-king-self-healing-operations", [
    { action: "overview", toolName: "self_healing_overview" },
    { action: "status", toolName: "self_healing_status" },
    { action: "history", toolName: "self_healing_history" },
    { action: "recommendations", toolName: "self_healing_recommendations" },
    { action: "execute", toolName: "self_healing_execute" },
    { action: "pause", toolName: "self_healing_pause" },
    { action: "statistics", toolName: "self_healing_statistics" },
    { action: "summary", toolName: "self_healing_summary" },
    { action: "initialize", toolName: "initialize_grand_king_self_healing_operations" },
    { action: "dependencies", toolName: "self_healing_dependencies" },
  ]),
  ...toolRoutes("grand-king-operational-intelligence-executive-insights", [
    { action: "intelligence", toolName: "executive_intelligence" },
    { action: "insights", toolName: "executive_insights" },
    { action: "predictions", toolName: "executive_predictions" },
    { action: "trends", toolName: "executive_trends" },
    { action: "opportunities", toolName: "executive_opportunities" },
    { action: "risks", toolName: "executive_risks" },
    { action: "briefing", toolName: "executive_briefing" },
    { action: "empire_health", toolName: "empire_health_score" },
    { action: "initialize", toolName: "initialize_grand_king_operational_intelligence" },
    { action: "status", toolName: "executive_intelligence_status" },
    { action: "recommendations", toolName: "executive_recommendations" },
    { action: "dependencies", toolName: "operational_intelligence_dependencies" },
  ]),
  ...toolRoutes("business-automation", [
    { action: "get_learning", toolName: "business_automation.get_learning" },
    { action: "search_learning", toolName: "business_automation.search_learning" },
    { action: "related_executions", toolName: "business_automation.related_executions" },
    { action: "outcome_policy_preview", toolName: "business_automation.outcome_policy_preview" },
  ]),
];
