import type { ModuleRoute } from "../../brain/orchestrator.js";

export const moduleRoutes: ModuleRoute[] = [
  { module: "dashboard", action: "load", toolName: "dashboard.load_view" },
  { module: "dashboard", action: "summarize", agentId: "founder-dashboard" },
  { module: "ai-ceo", action: "load", toolName: "ai-ceo.load_view" },
  { module: "ai-ceo", action: "approve", toolName: "ai-ceo.approve_decision" },
  { module: "ai-ceo", action: "approve_all", toolName: "ai-ceo.approve_all" },
  { module: "ai-ceo", action: "brief", agentId: "ai-ceo" },
  { module: "ai-ceo", action: "daily_review", workflowId: "daily-portfolio-review", async: true },
  { module: "intelligence", action: "load", toolName: "intelligence.load_view" },
  { module: "intelligence", action: "scan", agentId: "product-intelligence" },
  { module: "product-scout", action: "evaluate", toolName: "product-scout.evaluate" },
  { module: "product-scout", action: "scan", toolName: "product-scout.scan_portfolio" },
  { module: "product-scout", action: "recommend", toolName: "product-scout.recommend" },
  { module: "suppliers", action: "load", toolName: "suppliers.load_view" },
  { module: "suppliers", action: "health_check", agentId: "supplier-network" },
  { module: "supplier-intelligence", action: "discover", toolName: "supplier-intelligence.discover" },
  { module: "supplier-intelligence", action: "evaluate", toolName: "supplier-intelligence.evaluate" },
  { module: "supplier-intelligence", action: "compare", toolName: "supplier-intelligence.compare" },
  { module: "store", action: "load", toolName: "store.load_view" },
  { module: "store", action: "create", toolName: "company.create" },
  { module: "store", action: "build", agentId: "store-builder" },
  { module: "store", action: "manufacture", workflowId: "manufacture-company", async: true },
  { module: "marketing", action: "load", toolName: "marketing.load_view" },
  { module: "marketing", action: "campaign", agentId: "marketing-ai" },
  { module: "ads", action: "load", toolName: "ads.load_view" },
  { module: "ads", action: "optimize", agentId: "ad-manager" },
  { module: "finance", action: "load", toolName: "finance.load_view" },
  { module: "finance", action: "report", agentId: "finance-analyst" },
  { module: "orders", action: "load", toolName: "orders.load_view" },
  { module: "orders", action: "review", agentId: "order-ops" },
  { module: "support", action: "load", toolName: "support.load_view" },
  { module: "support", action: "resolve", agentId: "support-ai" },
  { module: "settings", action: "load", toolName: "settings.load_view" },
  { module: "admin", action: "load", toolName: "admin.load_view" },
  { module: "admin", action: "health", agentId: "admin-console" },
];
