import { randomUUID } from "node:crypto";

import { getGlobalAssistantRepository } from "../repositories/sqlite-global-assistant-repository.js";
import { buildAssistantContextBundle } from "./context-service.js";
import { gatherAllEvidence } from "./evidence-service.js";
import { generateAssistantMissions } from "./mission-service.js";

/** GC-05 — Generate Executive Audit markdown from live context. */
export function generateExecutiveAuditArtifact(
  workspaceId: string,
  companyId: string,
  screenPath: string,
  missionId = "GC-05",
) {
  const context = buildAssistantContextBundle(workspaceId, companyId, screenPath);
  const evidence = gatherAllEvidence(workspaceId, companyId, screenPath);
  const missions = generateAssistantMissions(workspaceId, companyId);
  const artifactId = randomUUID();
  const date = new Date().toISOString().slice(0, 10);

  const content = `# Executive Audit — ${missionId} Global AI Assistant

> **Mission:** ${missionId} · **Screen:** ${context.screen.screenTitle}  
> **Date:** ${date}  
> **Verdict:** **GENERATED** — Live evidence from chiefs, council, and ESS.

---

## 1. Context

| Field | Value |
|---|---|
| Screen | ${context.screen.screenTitle} (${context.screen.uxId ?? "—"}) |
| Path | ${context.screen.screenPath} |
| Journey markers | ${(context.screen.journeyMarkers ?? []).join(", ") || "—"} |

## 2. Live evidence (${evidence.length} items)

${evidence
  .slice(0, 12)
  .map((e) => `- **[${e.source}]** ${e.title}: ${e.summary}`)
  .join("\n")}

## 3. Mission proposals (${missions.missionCount})

${missions.missions
  .slice(0, 5)
  .map((m) => `- **${m.title}** — ROI ${m.expectedRoi}x · confidence ${m.confidence}% · approval required`)
  .join("\n")}

## 4. Journey alignment

${context.journey.rows.map((r) => `- ${r.id}: ${r.status}`).join("\n") || "No journey rows matched."}

---

*Generated by GC-05 Global AI Assistant · recommend-only · King decides.*
`;

  getGlobalAssistantRepository().saveAuditArtifact(artifactId, workspaceId, missionId, content);

  return {
    artifactId,
    missionId,
    content,
    evidenceCount: evidence.length,
    missionCount: missions.missionCount,
    requiresApproval: true,
    computedAt: new Date().toISOString(),
  };
}

export function getExecutiveAuditArtifact(artifactId: string) {
  return getGlobalAssistantRepository().getAuditArtifact(artifactId);
}
