import { z } from "zod";

/** IH-001 — Integrations Hub category taxonomy (Version 1). */
export const INTEGRATIONS_HUB_CATEGORIES = [
  "marketplaces",
  "suppliers",
  "ecommerce",
  "payments",
  "advertising",
  "analytics",
  "communication",
  "ai_providers",
] as const;

export type IntegrationsHubCategory = (typeof INTEGRATIONS_HUB_CATEGORIES)[number];

export const INTEGRATIONS_HUB_DISPLAY_STATUSES = [
  "connected",
  "not_connected",
  "needs_reauth",
  "disabled",
  "error",
] as const;

export type IntegrationsHubDisplayStatus = (typeof INTEGRATIONS_HUB_DISPLAY_STATUSES)[number];

export const integrationsHubDefinitionSchema = z.object({
  integrationId: z.string().min(1),
  displayName: z.string().min(1),
  category: z.enum(INTEGRATIONS_HUB_CATEGORIES),
  purpose: z.string().min(1),
  whyEmpireNeedsIt: z.string().min(1),
  oneTimeSetup: z.literal(true),
  /** OAR platform id when tracked in empire-platform-catalog */
  platformId: z.string().optional(),
  /** marketplace-infrastructure-engine id for connect flow */
  marketplaceInfrastructureId: z.string().optional(),
  /** reality-integration provider id for vault connect */
  realityProviderId: z.string().optional(),
  connectKind: z.enum(["marketplace", "reality", "env", "future"]),
  documentationUrl: z.string().url().optional(),
  future: z.boolean().default(false),
});

export type IntegrationsHubDefinition = z.input<typeof integrationsHubDefinitionSchema>;

/** IH-001 — Canonical Integrations Hub catalog (REAL-051A · Version 1). */
export const INTEGRATIONS_HUB_CATALOG: IntegrationsHubDefinition[] = [
  // Marketplaces
  {
    integrationId: "amazon",
    displayName: "Amazon",
    category: "marketplaces",
    purpose: "Sell on Amazon Seller Central — listings, orders, inventory sync.",
    whyEmpireNeedsIt: "Primary Version 1 production marketplace per REAL-051A; EmpireAI executes publish and order routing after one-time onboarding.",
    oneTimeSetup: true,
    platformId: "amazon-seller",
    marketplaceInfrastructureId: "amazon",
    realityProviderId: "amazon-seller",
    connectKind: "reality",
    documentationUrl: "https://developer.amazonservices.com",
  },
  {
    integrationId: "walmart",
    displayName: "Walmart",
    category: "marketplaces",
    purpose: "Walmart Marketplace listings and order fulfilment.",
    whyEmpireNeedsIt: "US marketplace expansion for common-product catalog publishing.",
    oneTimeSetup: true,
    platformId: "walmart",
    marketplaceInfrastructureId: "walmart",
    connectKind: "future",
    future: true,
    documentationUrl: "https://developer.walmart.com",
  },
  {
    integrationId: "ebay",
    displayName: "eBay",
    category: "marketplaces",
    purpose: "eBay marketplace listings and auction/fixed-price sales.",
    whyEmpireNeedsIt: "Secondary marketplace channel for catalog scale.",
    oneTimeSetup: true,
    platformId: "ebay",
    connectKind: "future",
    future: true,
    documentationUrl: "https://developer.ebay.com",
  },
  {
    integrationId: "etsy",
    displayName: "Etsy",
    category: "marketplaces",
    purpose: "Handmade and creative product marketplace.",
    whyEmpireNeedsIt: "Niche catalog channel for differentiated products.",
    oneTimeSetup: true,
    platformId: "etsy",
    connectKind: "future",
    future: true,
    documentationUrl: "https://developers.etsy.com",
  },
  {
    integrationId: "tiktok-shop",
    displayName: "TikTok Shop",
    category: "marketplaces",
    purpose: "Social commerce storefront on TikTok.",
    whyEmpireNeedsIt: "Social discovery channel for trend-aligned products.",
    oneTimeSetup: true,
    platformId: "tiktok-shop",
    marketplaceInfrastructureId: "tiktok-shop",
    connectKind: "future",
    future: true,
    documentationUrl: "https://partner.tiktokshop.com",
  },
  {
    integrationId: "shopee",
    displayName: "Shopee",
    category: "marketplaces",
    purpose: "Southeast Asia marketplace operations.",
    whyEmpireNeedsIt: "Regional expansion per CBD-014 commercial comparison.",
    oneTimeSetup: true,
    platformId: "shopee",
    connectKind: "future",
    future: true,
    documentationUrl: "https://open.shopee.com",
  },
  {
    integrationId: "lazada",
    displayName: "Lazada",
    category: "marketplaces",
    purpose: "Southeast Asia marketplace operations.",
    whyEmpireNeedsIt: "Regional marketplace parity with Shopee.",
    oneTimeSetup: true,
    platformId: "lazada",
    connectKind: "future",
    future: true,
    documentationUrl: "https://open.lazada.com",
  },
  // Suppliers
  {
    integrationId: "cj-dropshipping",
    displayName: "CJ Dropshipping",
    category: "suppliers",
    purpose: "Primary dropship supplier — catalog, cost, fulfilment dispatch.",
    whyEmpireNeedsIt: "Version 1 fulfilment path; EmpireAI routes orders after credential vault storage (CBD-006).",
    oneTimeSetup: true,
    platformId: "cj-dropshipping",
    realityProviderId: "cj-dropshipping",
    connectKind: "reality",
    documentationUrl: "https://developers.cjdropshipping.com",
  },
  {
    integrationId: "autods",
    displayName: "AutoDS",
    category: "suppliers",
    purpose: "Automated dropshipping supplier aggregation.",
    whyEmpireNeedsIt: "Future supplier diversification beyond CJ.",
    oneTimeSetup: true,
    connectKind: "future",
    future: true,
  },
  {
    integrationId: "zendrop",
    displayName: "Zendrop",
    category: "suppliers",
    purpose: "US-focused dropshipping supplier.",
    whyEmpireNeedsIt: "Faster shipping supplier option for US customers.",
    oneTimeSetup: true,
    connectKind: "future",
    future: true,
  },
  {
    integrationId: "spocket",
    displayName: "Spocket",
    category: "suppliers",
    purpose: "US/EU supplier marketplace.",
    whyEmpireNeedsIt: "Premium supplier sourcing for branded products.",
    oneTimeSetup: true,
    connectKind: "future",
    future: true,
  },
  {
    integrationId: "aliexpress",
    displayName: "AliExpress",
    category: "suppliers",
    purpose: "Global supplier catalog sourcing.",
    whyEmpireNeedsIt: "Cost-competitive sourcing for common products.",
    oneTimeSetup: true,
    connectKind: "future",
    future: true,
  },
  // Ecommerce
  {
    integrationId: "shopify",
    displayName: "Shopify",
    category: "ecommerce",
    purpose: "Dedicated branded storefront — premium product path per REAL-051A.",
    whyEmpireNeedsIt: "EmpireAI auto-generates and operates Shopify stores for premium/branded products.",
    oneTimeSetup: true,
    marketplaceInfrastructureId: "shopify",
    connectKind: "marketplace",
    documentationUrl: "https://shopify.dev",
  },
  {
    integrationId: "woocommerce",
    displayName: "WooCommerce",
    category: "ecommerce",
    purpose: "Self-hosted WordPress commerce storefront.",
    whyEmpireNeedsIt: "Alternative owned-store channel for branded catalog.",
    oneTimeSetup: true,
    connectKind: "future",
    future: true,
    documentationUrl: "https://woocommerce.com/document/woocommerce-rest-api",
  },
  // Payments
  {
    integrationId: "stripe",
    displayName: "Stripe",
    category: "payments",
    purpose: "Payment capture, checkout, and payout reconciliation.",
    whyEmpireNeedsIt: "Live payment engine and revenue loop (Mission 103).",
    oneTimeSetup: true,
    platformId: "stripe",
    realityProviderId: "stripe",
    connectKind: "reality",
    documentationUrl: "https://stripe.com/docs/api",
  },
  {
    integrationId: "paypal",
    displayName: "PayPal",
    category: "payments",
    purpose: "Alternative payment processor and checkout.",
    whyEmpireNeedsIt: "Customer payment preference coverage.",
    oneTimeSetup: true,
    platformId: "paypal",
    connectKind: "future",
    future: true,
    documentationUrl: "https://developer.paypal.com",
  },
  // Advertising
  {
    integrationId: "meta-ads",
    displayName: "Meta Ads",
    category: "advertising",
    purpose: "Facebook and Instagram paid campaigns.",
    whyEmpireNeedsIt: "Paid traffic for product launches (REAL-038; recommendations until live credentials).",
    oneTimeSetup: true,
    platformId: "meta-ads",
    realityProviderId: "meta-ads",
    connectKind: "reality",
    documentationUrl: "https://developers.facebook.com/docs/marketing-apis",
  },
  {
    integrationId: "google-ads",
    displayName: "Google Ads",
    category: "advertising",
    purpose: "Search and display advertising.",
    whyEmpireNeedsIt: "Intent-based traffic acquisition.",
    oneTimeSetup: true,
    connectKind: "future",
    future: true,
    documentationUrl: "https://developers.google.com/google-ads/api",
  },
  {
    integrationId: "tiktok-ads",
    displayName: "TikTok Ads",
    category: "advertising",
    purpose: "TikTok paid social campaigns.",
    whyEmpireNeedsIt: "Social ad channel aligned with TikTok Shop.",
    oneTimeSetup: true,
    connectKind: "future",
    future: true,
  },
  // Analytics
  {
    integrationId: "google-analytics",
    displayName: "Google Analytics",
    category: "analytics",
    purpose: "Web and conversion analytics (GA4).",
    whyEmpireNeedsIt: "Conversion tracking and funnel intelligence (Mission 106).",
    oneTimeSetup: true,
    platformId: "ga4",
    realityProviderId: "ga4",
    connectKind: "reality",
    documentationUrl: "https://developers.google.com/analytics",
  },
  {
    integrationId: "google-search-console",
    displayName: "Google Search Console",
    category: "analytics",
    purpose: "Organic search performance and indexing.",
    whyEmpireNeedsIt: "SEO intelligence and listing visibility.",
    oneTimeSetup: true,
    connectKind: "future",
    future: true,
    documentationUrl: "https://developers.google.com/webmaster-tools",
  },
  {
    integrationId: "microsoft-clarity",
    displayName: "Microsoft Clarity",
    category: "analytics",
    purpose: "Session replay and heatmap analytics.",
    whyEmpireNeedsIt: "UX conversion diagnostics on storefronts.",
    oneTimeSetup: true,
    connectKind: "future",
    future: true,
    documentationUrl: "https://clarity.microsoft.com",
  },
  // Communication
  {
    integrationId: "gmail",
    displayName: "Gmail",
    category: "communication",
    purpose: "Transactional and support email via Google.",
    whyEmpireNeedsIt: "Customer communication and order notifications.",
    oneTimeSetup: true,
    connectKind: "future",
    future: true,
  },
  {
    integrationId: "sendgrid",
    displayName: "SendGrid",
    category: "communication",
    purpose: "Transactional email delivery at scale.",
    whyEmpireNeedsIt: "Reliable order and marketing email dispatch.",
    oneTimeSetup: true,
    connectKind: "future",
    future: true,
    documentationUrl: "https://docs.sendgrid.com",
  },
  {
    integrationId: "twilio",
    displayName: "Twilio",
    category: "communication",
    purpose: "SMS and voice customer notifications.",
    whyEmpireNeedsIt: "Mobile messaging for order updates.",
    oneTimeSetup: true,
    connectKind: "future",
    future: true,
    documentationUrl: "https://www.twilio.com/docs",
  },
  // AI Providers
  {
    integrationId: "openai",
    displayName: "OpenAI",
    category: "ai_providers",
    purpose: "LLM inference for Brain, Pillow, and agents.",
    whyEmpireNeedsIt: "Core intelligence routing — default LLM provider.",
    oneTimeSetup: true,
    platformId: "openai",
    realityProviderId: "openai",
    connectKind: "env",
    documentationUrl: "https://platform.openai.com/docs",
  },
  {
    integrationId: "anthropic",
    displayName: "Anthropic",
    category: "ai_providers",
    purpose: "Claude models for Brain and executive reasoning.",
    whyEmpireNeedsIt: "Alternative LLM provider for governance and quality.",
    oneTimeSetup: true,
    platformId: "anthropic",
    connectKind: "env",
    documentationUrl: "https://docs.anthropic.com",
  },
  {
    integrationId: "gemini",
    displayName: "Gemini",
    category: "ai_providers",
    purpose: "Google Gemini models for Brain routing.",
    whyEmpireNeedsIt: "Multi-provider LLM resilience.",
    oneTimeSetup: true,
    platformId: "google-ai",
    connectKind: "env",
    documentationUrl: "https://ai.google.dev",
  },
];

export function getIntegrationsHubDefinition(integrationId: string): IntegrationsHubDefinition | undefined {
  return INTEGRATIONS_HUB_CATALOG.find((d) => d.integrationId === integrationId);
}

export const integrationsHubItemSchema = z.object({
  integrationId: z.string(),
  displayName: z.string(),
  category: z.enum(INTEGRATIONS_HUB_CATEGORIES),
  purpose: z.string(),
  whyEmpireNeedsIt: z.string(),
  oneTimeSetup: z.literal(true),
  displayStatus: z.enum(INTEGRATIONS_HUB_DISPLAY_STATUSES),
  productionStatus: z.enum(["production", "sandbox", "architecture_only", "not_configured"]),
  lastVerification: z.string().datetime({ offset: true }).nullable(),
  connectKind: z.enum(["marketplace", "reality", "env", "future"]),
  canConnect: z.boolean(),
  canReconnect: z.boolean(),
  future: z.boolean(),
  documentationUrl: z.string().url().optional(),
  oarAccessState: z.string().optional(),
  restrictions: z.array(z.string()),
});

export type IntegrationsHubItem = z.infer<typeof integrationsHubItemSchema>;

export const integrationsHubDashboardSchema = z.object({
  moduleId: z.literal("integrations-hub"),
  missionId: z.literal("IH-001"),
  doctrineRef: z.literal("REAL-051A"),
  workspaceId: z.string(),
  categories: z.array(
    z.object({
      category: z.enum(INTEGRATIONS_HUB_CATEGORIES),
      label: z.string(),
      integrations: z.array(integrationsHubItemSchema),
    }),
  ),
  summary: z.object({
    total: z.number().int(),
    connected: z.number().int(),
    notConnected: z.number().int(),
    needsReauth: z.number().int(),
    disabled: z.number().int(),
    error: z.number().int(),
  }),
  computedAt: z.string().datetime({ offset: true }),
});

export type IntegrationsHubDashboard = z.infer<typeof integrationsHubDashboardSchema>;

export const INTEGRATIONS_HUB_CATEGORY_LABELS: Record<IntegrationsHubCategory, string> = {
  marketplaces: "Marketplaces",
  suppliers: "Suppliers",
  ecommerce: "Ecommerce",
  payments: "Payments",
  advertising: "Advertising",
  analytics: "Analytics",
  communication: "Communication",
  ai_providers: "AI Providers",
};
