import { AccountStore } from "./account-store.js"; import { PlanStore } from "./plan-store.js"; import { SubscriptionStore } from "./subscription-store.js"; import { InvoiceStore } from "./invoice-store.js"; import { TransactionStore } from "./transaction-store.js"; import { RefundStore } from "./refund-store.js"; import { BillingAudit } from "./billing-audit.js";
import type { BillingAccount, BillingTransaction, CreditNote, Invoice, RefundRecord, Subscription, SubscriptionPlan } from "./types.js";
const id=(prefix:string)=>`${prefix}-${crypto.randomUUID()}`;
export class BillingRuntime {
 readonly accounts=new AccountStore(); readonly plans=new PlanStore(); readonly subscriptions=new SubscriptionStore(); readonly invoices=new InvoiceStore(); readonly transactions=new TransactionStore(); readonly refunds=new RefundStore(); readonly audit=new BillingAudit();
 createBillingAccount(input:{accountId?:string;customerId?:string;email?:string;displayName?:string;currency?:string}){const value:BillingAccount={accountId:input.accountId??id("blw-acct"),customerId:input.customerId??id("customer"),email:input.email??null,displayName:input.displayName??null,currency:input.currency??"USD",createdAt:new Date().toISOString()};this.accounts.add(value);this.audit.record("account_created",value.accountId);return value;}
 createSubscriptionPlan(input:{planId?:string;name:string;interval:"monthly"|"annual"|"one_time";amountCents:number;currency:string;trialDays?:number}){if(input.amountCents<0) throw new Error("amountCents must be non-negative");const value:SubscriptionPlan={...input,planId:input.planId??id("blw-plan"),trialDays:input.trialDays??0,createdAt:new Date().toISOString()};this.plans.add(value);this.audit.record("plan_created",value.planId);return value;}
 createSubscription(input:{subscriptionId?:string;accountId:string;planId:string;startAt?:string}){const plan=this.plans.get(input.planId);if(!this.accounts.get(input.accountId)||!plan)throw new Error("Billing account and subscription plan are required");const startAt=input.startAt??new Date().toISOString();const status=plan.trialDays>0?"trialing" as const:"active" as const;const next=new Date(startAt);if(plan.interval==="monthly")next.setUTCMonth(next.getUTCMonth()+1);else if(plan.interval==="annual")next.setUTCFullYear(next.getUTCFullYear()+1);const value:Subscription={subscriptionId:input.subscriptionId??id("blw-sub"),accountId:input.accountId,planId:input.planId,status,startAt,nextBillingAt:plan.interval==="one_time"?null:next.toISOString(),createdAt:new Date().toISOString()};this.subscriptions.add(value);this.audit.record("subscription_created",value.subscriptionId);return value;}
 generateInvoice(input:{accountId:string;subscriptionId?:string;lineItems?:Array<{description:string;amountCents:number}>}){const account=this.accounts.get(input.accountId);if(!account)throw new Error("Billing account not found");if(input.subscriptionId&&!this.subscriptions.get(input.subscriptionId))throw new Error("Subscription not found");const items=input.lineItems??[];if(items.some(x=>x.amountCents<0))throw new Error("Invoice line amounts must be non-negative");const value:Invoice={invoiceId:id("blw-inv"),invoiceNumber:this.invoices.nextNumber(),accountId:account.accountId,subscriptionId:input.subscriptionId??null,lineItems:items.map(x=>({...x})),amountCents:items.reduce((n,x)=>n+x.amountCents,0),currency:account.currency,status:"draft",createdAt:new Date().toISOString(),issuedAt:null,paidAt:null};this.invoices.add(value);this.audit.record("invoice_generated",value.invoiceId);return value;}
 issueInvoice(input:{invoiceId:string}){const invoice=this.requireInvoice(input.invoiceId);if(invoice.status!=="draft")throw new Error("Only draft invoices can be issued");invoice.status="issued";invoice.issuedAt=new Date().toISOString();this.audit.record("invoice_issued",invoice.invoiceId);return invoice;}
 recordPaymentProviderResult(input:{invoiceId?:string;transactionId?:string;status:"pending"|"processing"|"succeeded"|"failed";providerRef?:string;amountCents?:number}){if(input.invoiceId)this.requireInvoice(input.invoiceId);const value:BillingTransaction={transactionId:input.transactionId??id("blw-txn"),invoiceId:input.invoiceId??null,status:input.status,providerRef:input.providerRef??null,amountCents:input.amountCents??null,recordedAt:new Date().toISOString()};this.transactions.add(value);this.audit.record("provider_result_recorded",value.transactionId,{status:value.status});return value;}
 markInvoicePaid(input:{invoiceId:string;transactionId?:string}){const invoice=this.requireInvoice(input.invoiceId);const payment=input.transactionId?this.transactions.get(input.transactionId):this.transactions.forInvoice(invoice.invoiceId).find(x=>x.status==="succeeded");if(!payment||payment.invoiceId!==invoice.invoiceId||payment.status!=="succeeded")throw new Error("A recorded succeeded payment transaction is required");invoice.status="paid";invoice.paidAt=new Date().toISOString();this.audit.record("invoice_paid",invoice.invoiceId,{transactionId:payment.transactionId});return invoice;}
 recordRefund(input:{invoiceId:string;amountCents:number;reason?:string}){const invoice=this.requireInvoice(input.invoiceId);if(input.amountCents<=0||input.amountCents>invoice.amountCents)throw new Error("Refund amount must be positive and not exceed invoice");const prior=this.refunds.listRefunds().filter(x=>x.invoiceId===invoice.invoiceId).reduce((n,x)=>n+x.amountCents,0);if(prior+input.amountCents>invoice.amountCents)throw new Error("Refund exceeds invoice total");const value:RefundRecord={refundId:id("blw-ref"),invoiceId:invoice.invoiceId,amountCents:input.amountCents,reason:input.reason??null,recordedAt:new Date().toISOString()};this.refunds.addRefund(value);invoice.status=prior+input.amountCents===invoice.amountCents?"refunded":"partially_refunded";this.audit.record("refund_recorded",value.refundId);return value;}
 createCreditNote(input:{accountId:string;amountCents:number;reason?:string;invoiceId?:string}){if(!this.accounts.get(input.accountId)||input.amountCents<=0)throw new Error("Valid account and positive credit amount required");if(input.invoiceId)this.requireInvoice(input.invoiceId);const value:CreditNote={creditNoteId:id("blw-crd"),accountId:input.accountId,invoiceId:input.invoiceId??null,amountCents:input.amountCents,reason:input.reason??null,createdAt:new Date().toISOString()};this.refunds.addCreditNote(value);this.audit.record("credit_note_created",value.creditNoteId);return value;}
 getBillingHistory(accountId:string){return {account:this.accounts.get(accountId),subscriptions:this.subscriptions.list().filter(x=>x.accountId===accountId),invoices:this.invoices.list().filter(x=>x.accountId===accountId),refunds:this.refunds.listRefunds().filter(x=>this.invoices.get(x.invoiceId)?.accountId===accountId),creditNotes:this.refunds.listCreditNotes().filter(x=>x.accountId===accountId),auditEvents:this.audit.list().filter(x=>x.entityId===accountId||this.invoices.list().some(i=>i.accountId===accountId&&i.invoiceId===x.entityId))};}
 private requireInvoice(id:string){const invoice=this.invoices.get(id);if(!invoice)throw new Error("Invoice not found");return invoice;}
}
