import type { EmpireBootstrapContext } from "../bootstrap/types.js";
import { RepositoryReader } from "../bootstrap/repository-reader.js";
import { buildInternationalExecutiveCockpitConfiguration, type InternationalExecutiveCockpitConfiguration } from "./configuration.js";
import { InternationalExecutiveCockpitManager, type InternationalExecutiveCockpitDependencies } from "./international-executive-cockpit-manager.js";
import { IEC_METADATA_VERSION, INTERNATIONAL_EXECUTIVE_COCKPIT_SYSTEM_PATH } from "./paths.js";
import type { InternationalExecutiveCockpitInput, InternationalExecutiveCockpitState } from "./types.js";
export type { InternationalExecutiveCockpitDependencies };
export interface InternationalExecutiveCockpitOptions { configuration?: Partial<InternationalExecutiveCockpitConfiguration>; }
export class InternationalExecutiveCockpit {
  private initializedAt: string | null = null; private status: InternationalExecutiveCockpitState["status"] = "idle"; private latestReport: ReturnType<InternationalExecutiveCockpitManager["run"]> | null = null; private readonly manager: InternationalExecutiveCockpitManager; private readonly configuration: InternationalExecutiveCockpitConfiguration; private readonly reader: RepositoryReader;
  constructor(bootstrap: EmpireBootstrapContext, dependencies: InternationalExecutiveCockpitDependencies = {}, options: InternationalExecutiveCockpitOptions = {}) { this.manager = new InternationalExecutiveCockpitManager(dependencies); this.configuration = buildInternationalExecutiveCockpitConfiguration(bootstrap.repositoryRoot, options.configuration); this.reader = new RepositoryReader(bootstrap.repositoryRoot); }
  async initialize() { const doc = await this.reader.readText(INTERNATIONAL_EXECUTIVE_COCKPIT_SYSTEM_PATH); if (!doc?.includes("International Executive Cockpit")) throw new Error(`${INTERNATIONAL_EXECUTIVE_COCKPIT_SYSTEM_PATH} missing — X4-18 system doc required.`); this.initializedAt = new Date().toISOString(); this.status = "active"; return this.getState(); }
  getState(): InternationalExecutiveCockpitState { if (!this.initializedAt) throw new Error("International Executive Cockpit not initialized. Call initialize() first."); const engineRecord = this.manager.getEngineRecord(), count = this.manager.getCockpitRecords().length; return { engineVersion: "PILLOW-IEC-001", missionId: "X4-18", status: this.status, initializedAt: this.initializedAt, configuration: this.configuration, latestReport: this.latestReport, engineRecord, health: { status: engineRecord?.healthStatus ?? "standby", healthScore: engineRecord?.healthStatus === "healthy" ? 100 : engineRecord ? 70 : 50, totalCockpitRecords: count, notes: ["Structural executive signals only; sensitive enterprise information remains masked."] } }; }
  connectInternationalExecutiveCockpit(input: Record<string, unknown> = {}) { this.status = "connecting"; return this.finish(this.manager.connect(input, this.configuration)); }
  displayWorldwideExecutiveKpis(input: InternationalExecutiveCockpitInput = {}) { return this.run("worldwide_kpis", input); } aggregateWorldwideExecutiveKpis(input: InternationalExecutiveCockpitInput = {}) { return this.displayWorldwideExecutiveKpis(input); }
  displayRegionalPerformance(input: InternationalExecutiveCockpitInput = {}) { return this.run("regional_performance", input); } displayCountryExpansionStatus(input: InternationalExecutiveCockpitInput = {}) { return this.run("country_expansion_status", input); } displayGlobalOperationalHealth(input: InternationalExecutiveCockpitInput = {}) { return this.run("global_operational_health", input); } displayWorldwideRisks(input: InternationalExecutiveCockpitInput = {}) { return this.run("worldwide_risks", input); } displayStrategicOpportunities(input: InternationalExecutiveCockpitInput = {}) { return this.run("strategic_opportunities", input); } displayExecutiveRecommendations(input: InternationalExecutiveCockpitInput = {}) { return this.run("executive_recommendations", input); } supportExecutiveDrillDown(input: InternationalExecutiveCockpitInput = {}) { return this.run("executive_drill_down", input); } refreshCockpitSnapshot(input: InternationalExecutiveCockpitInput = {}) { return this.run("refresh_cockpit_snapshot", input); } buildCockpitSnapshot(input: InternationalExecutiveCockpitInput = {}) { return this.refreshCockpitSnapshot(input); }
  runDiagnostics() { return this.finish(this.manager.diagnostics(this.configuration)); } getCockpitRecords() { return this.manager.getCockpitRecords(); } getRecommendations() { return this.manager.getRecommendations(); } getEngineRecord() { return this.manager.getEngineRecord(); }
  getCockpitSnapshot() { const state = this.getState(), latest = state.latestReport?.cockpitRecord; return latest ?? { cockpitId: null, timestamp: null, companyReference: null, worldwideKpiSummary: {}, regionalSummary: {}, countrySummary: {}, strategicOpportunitySummary: {}, globalRiskSummary: {}, executiveRecommendations: [], validationStatus: "partial", metadataVersion: IEC_METADATA_VERSION, structuralSignalOnly: true, neverExposeRestrictedEnterpriseInformationToUnauthorizedUsers: true, preserveExecutiveTraceability: true, preserveAuditability: true, unvalidatedClaim: "none", cockpitTraceId: null }; }
  validateForSupervisorSync() { const state = this.getState(); return { valid: state.health.status !== "standby", health: state.health.status, readinessScore: state.health.healthScore, notes: state.health.notes }; }
  private run(action: string, input: InternationalExecutiveCockpitInput) { this.status = "refreshing"; return this.finish(this.manager.run(action, input)); } private finish(report: ReturnType<InternationalExecutiveCockpitManager["run"]>) { this.latestReport = report; this.status = "active"; return report; }
}
export function createInternationalExecutiveCockpit(bootstrap: EmpireBootstrapContext, dependencies: InternationalExecutiveCockpitDependencies = {}, options?: InternationalExecutiveCockpitOptions) { return new InternationalExecutiveCockpit(bootstrap, dependencies, options); }
export function resetInternationalExecutiveCockpitForTesting() {}
