import type { GlobalExpansionFrameworkEngine } from "../global-expansion-framework/engine.js";
import type { InternationalExecutiveCockpitConfiguration } from "./configuration.js";
import { IEC_CAPABILITIES, IEC_METADATA_VERSION, INTERNATIONAL_EXECUTIVE_COCKPIT_ID } from "./paths.js";
import type { ExecutiveRecommendation, IecRunReport, InternationalExecutiveCockpitInput, InternationalExecutiveCockpitRecord } from "./types.js";
export type InternationalExecutiveCockpitDependencies = { globalExpansionFramework?: GlobalExpansionFrameworkEngine | null };
export class InternationalExecutiveCockpitManager {
  private record: InternationalExecutiveCockpitRecord | null = null; private records: InternationalExecutiveCockpitRecord[] = []; private recommendations: ExecutiveRecommendation[] = []; private engineRecord: { engineId: string; healthStatus: "healthy" | "degraded" | "standby"; frameworkModuleId: string | null; supportedCapabilities: typeof IEC_CAPABILITIES[number][] } | null = null;
  constructor(private readonly dependencies: InternationalExecutiveCockpitDependencies = {}) {}
  getCockpitRecords() { return this.records.map((item) => ({ ...item })); } getRecommendations() { return this.recommendations.map((item) => ({ ...item })); } getEngineRecord() { return this.engineRecord ? { ...this.engineRecord } : null; }
  connect(_input: Record<string, unknown>, config: InternationalExecutiveCockpitConfiguration) { const gef = this.dependencies.globalExpansionFramework; let frameworkModuleId: string | null = null; if (gef) { const registration = gef.registerExpansionModule({ definition: { expansionModuleIdentifier: INTERNATIONAL_EXECUTIVE_COCKPIT_ID, moduleVersion: IEC_METADATA_VERSION, moduleType: "integration", integrationMissionId: "X4-18", eventRoutingConfig: { enabled: true, topics: ["international.executive.cockpit.snapshot"], maxEventsPerMinute: 60, windowMs: 60000 }, retryConfig: { enabled: true, maxAttempts: 3, delayMs: config.dashboardRefreshFrequencyMs, backoffMultiplier: 2 }, supportedCapabilities: ["global_expansion_module_registration", "regional_data_abstraction", "global_expansion_validation", "diagnostics"] }, forceRegister: true }); frameworkModuleId = registration.records[0]?.expansionFrameworkId ?? null; if (registration.validation.decision !== "fail") gef.activateExpansionModule(INTERNATIONAL_EXECUTIVE_COCKPIT_ID); } this.engineRecord = { engineId: INTERNATIONAL_EXECUTIVE_COCKPIT_ID, healthStatus: gef ? "healthy" : "degraded", frameworkModuleId, supportedCapabilities: [...IEC_CAPABILITIES] }; return this.build("connect", {}, true); }
  run(action: string, input: InternationalExecutiveCockpitInput = {}) { if (!this.engineRecord) throw new Error("International Executive Cockpit not connected — call connectInternationalExecutiveCockpit first"); return this.build(action, input, input.validated === true); }
  diagnostics(config: InternationalExecutiveCockpitConfiguration) { return this.engineRecord ? this.build("diagnostics", {}, config.enabled) : this.connect({}, config); }
  private build(action: string, input: InternationalExecutiveCockpitInput, validated: boolean): IecRunReport { const now = new Date().toISOString(), region = (input.region ?? "GLOBAL").toUpperCase(), country = (input.country ?? "GLOBAL").toUpperCase(), kpi = Math.max(0, Math.min(100, input.kpiHint ?? (validated ? 80 : 50))), risk = Math.max(0, Math.min(100, input.riskHint ?? (validated ? 20 : 50))), opportunity = Math.max(0, Math.min(100, input.opportunityHint ?? (validated ? 75 : 50))); const recommendation: ExecutiveRecommendation = { recommendationId: `iec-rec-${Date.now()}`, timestamp: now, recommendationSummary: validated ? `Review structural executive signal for ${region}/${country}; authorization and source validation remain required.` : "Unvalidated structural cockpit signal; enterprise action is blocked.", priority: risk > 60 ? "high" : opportunity > 70 ? "medium" : "low", structuralSignalOnly: true, unvalidatedClaim: "none" }; this.recommendations = [recommendation]; const record: InternationalExecutiveCockpitRecord = { cockpitId: `iec-${Date.now()}`, timestamp: now, companyReference: input.companyReference ?? "enterprise", worldwideKpiSummary: { executiveKpiScore: kpi }, regionalSummary: { region, performanceScore: kpi }, countrySummary: { country, expansionStatus: validated ? "validated_structural_signal" : "unvalidated_structural_signal" }, strategicOpportunitySummary: { opportunityScore: opportunity }, globalRiskSummary: { riskScore: risk }, executiveRecommendations: this.recommendations, validationStatus: validated ? "passed" : "partial", metadataVersion: IEC_METADATA_VERSION, structuralSignalOnly: true, neverExposeRestrictedEnterpriseInformationToUnauthorizedUsers: true, preserveExecutiveTraceability: true, preserveAuditability: true, unvalidatedClaim: "none", cockpitTraceId: `iec-trace-${Date.now()}` }; this.record = record; this.records.push(record); return { cockpitRunReportId: `iec-run-${Date.now()}`, runTimestamp: now, action, cockpitRecord: record, recommendations: this.recommendations, validation: { decision: validated ? "pass" : "partial", errors: [], warnings: validated ? [] : ["Cockpit data is structural and unvalidated; enterprise action is blocked."], metadataVersion: IEC_METADATA_VERSION }, metadataVersion: IEC_METADATA_VERSION }; }
}
