import type { BackendWorkerConfiguration } from "./configuration.js";
import type { BackendWorkerDependencies } from "./integrations.js";
import { BackendManager } from "./backend-manager.js";
import type { BackendWorkerInput, BackendWorkerRunReport, BewEngineStatus } from "./types.js";
export class BackendWorkerController {
  private status: BewEngineStatus = "idle"; private latest: BackendWorkerRunReport | null = null;
  constructor(private readonly manager: BackendManager, private readonly config: BackendWorkerConfiguration) {}
  initialize() { this.manager.ensureSeeded(this.config); this.status = "active"; } bindIntegrations(deps: BackendWorkerDependencies = {}) { this.manager.bindIntegrations(deps); }
  getStatus() { return this.status; } getManager() { return this.manager; } getConfiguration() { return structuredClone(this.config); } getLatestReport() { return this.latest; }
  connect(input: Record<string, unknown> = {}) { this.status = "connecting"; return this.finish(this.manager.connect(input, this.config)); }
  receiveApprovedRequirementsReports(input: BackendWorkerInput = {}) { this.status = "receiving_requirements"; return this.finish(this.manager.receiveApprovedRequirementsReports(input, this.config)); } receiveApprovedRequirementsReport(input: BackendWorkerInput = {}) { return this.receiveApprovedRequirementsReports(input); }
  receiveApprovedArchitectureReports(input: BackendWorkerInput = {}) { this.status = "receiving_architecture"; return this.finish(this.manager.receiveApprovedArchitectureReports(input, this.config)); } receiveApprovedArchitectureReport(input: BackendWorkerInput = {}) { return this.receiveApprovedArchitectureReports(input); }
  buildRestAndGraphqlApis(input: BackendWorkerInput = {}) { return this.finish(this.manager.buildRestAndGraphqlApis(input, this.config)); } implementBusinessLogic(input: BackendWorkerInput = {}) { return this.finish(this.manager.implementBusinessLogic(input, this.config)); } implementAuthenticationAndAuthorization(input: BackendWorkerInput = {}) { return this.finish(this.manager.implementAuthenticationAndAuthorization(input, this.config)); } implementExternalApiIntegrations(input: BackendWorkerInput = {}) { return this.finish(this.manager.implementExternalApiIntegrations(input, this.config)); } implementBackgroundWorkersAndScheduledJobs(input: BackendWorkerInput = {}) { return this.finish(this.manager.implementBackgroundWorkersAndScheduledJobs(input, this.config)); } implementValidationAndErrorHandling(input: BackendWorkerInput = {}) { return this.finish(this.manager.implementValidationAndErrorHandling(input, this.config)); } produceSecureMaintainableBackendModules(input: BackendWorkerInput = {}) { return this.finish(this.manager.produceSecureMaintainableBackendModules(input, this.config)); } produceModularBackendServices(input: BackendWorkerInput = {}) { return this.produceSecureMaintainableBackendModules(input); } produceBackendBuildReport(input: BackendWorkerInput = {}) { return this.finish(this.manager.produceBackendBuildReport(input, this.config)); } submitReport(input: BackendWorkerInput = {}) { return this.finish(this.manager.submitReport(input, this.config)); } list() { return this.finish(this.manager.list(this.config)); } validate(input: BackendWorkerInput = {}) { return this.finish(this.manager.validate(input, this.config)); } diagnostics() { return this.finish(this.manager.diagnostics(this.config)); }
  private finish(report: BackendWorkerRunReport) { this.latest = report; this.status = report.validation.decision === "fail" ? "failed" : "active"; return report; }
}
