import { BACKEND_WORKER_REPORT_VERSION, BEW_METADATA_VERSION } from "./paths.js";
import type { BackendBuildReport, BackendWorkerInput, BuildEntry, ReviewFinding } from "./types.js";
import type { BackendWorkerConfiguration } from "./configuration.js";
let sequence = 0;
const now = () => new Date().toISOString();
const entry = (prefix: string, name: string, description: string, extra: Partial<BuildEntry> = {}): BuildEntry => ({ id: `${prefix}${Date.now()}-${sequence}`, name, description, ...extra });
export class BackendBuilder {
  createShell(input: BackendWorkerInput, config: BackendWorkerConfiguration): BackendBuildReport {
    sequence += 1; const requirementsReportId = input.requirementsReportId?.trim() ?? "";
    return this.lockReport({ buildId: input.buildId?.trim() || `bew-bld-${Date.now()}-${sequence}`, timestamp: now(), platformId: input.platformId?.trim() || `bew-plt-${sequence}`, platformName: input.platformName?.trim() || "Platform from approved requirements", servicesImplemented: [], apisImplemented: [], authenticationStatus: "pending", integrationsCompleted: [], backgroundJobs: [], errorHandlingStatus: "pending", testCoverageSummary: "Structural backend coverage pending approved architecture", buildStatus: requirementsReportId ? "in_progress" : "draft", confidenceScore: requirementsReportId ? 35 : 20, metadataVersion: BEW_METADATA_VERSION, requirementsReportId, architectureReportId: input.architectureReportId?.trim() ?? "", factoryMissionId: input.factoryMissionId?.trim() || `bew-msn-${sequence}`, businessId: input.businessId?.trim() || `bew-biz-${sequence}`, businessObjective: input.businessObjective?.trim() || "Build secure backend aligned to approved requirements and architecture", authorizationStatus: "pending", middleware: [], validationRules: [], loggingConfigured: false, configurationManagement: "pending", webhooks: [], apiClients: [], businessLogicModules: [], buildSteps: [this.step("receive_requirements", "Receive approved requirements", 1, requirementsReportId ? "Requirements recorded" : "Awaiting requirements")], selfReviewPassed: false, selfReviewFindings: [], selfReviewSummary: "Backend shell created", qualityReview: "", complianceReview: "", backendCompliance: requirementsReportId ? "partial" : "non_compliant", backendComplianceNotes: "Pending backend build stages", workerId: config.workerId, reportVersion: BACKEND_WORKER_REPORT_VERSION, traceabilityRefs: [requirementsReportId || "requirements:missing"], preservedDecisions: [], submittedToExecutiveReporting: false, executiveReportId: null });
  }
  addApis(r: BackendBuildReport, apis: Array<{ apiId?: string; name?: string; protocol?: string }>) { const source = apis.length ? apis : [{ apiId: "approved-api", name: "Approved Platform API", protocol: "REST" }]; const mapped = source.flatMap((api) => [entry("bew-api-", `${api.name || "Platform"} REST API`, `REST API from ${api.apiId || "approved architecture"}`, { source: api.apiId }), entry("bew-api-", `${api.name || "Platform"} GraphQL API`, `GraphQL API from ${api.apiId || "approved architecture"}`, { source: api.apiId })]); return this.update(r, { apisImplemented: mapped }, "build_apis", "Build REST and GraphQL APIs"); }
  addBusinessLogic(r: BackendBuildReport) { const modules = [entry("bew-svc-", "Platform domain service", "Modular business service"), entry("bew-svc-", "Workflow policy service", "Reusable policy service")]; return this.update(r, { servicesImplemented: modules, businessLogicModules: modules }, "implement_business_logic", "Implement business logic"); }
  addAuth(r: BackendBuildReport) { return this.update(r, { authenticationStatus: "configured", authorizationStatus: "configured", servicesImplemented: [...r.servicesImplemented, entry("bew-auth-", "Authentication service", "Token authentication and authorization policy")] }, "implement_authentication", "Implement authentication and authorization"); }
  addIntegrations(r: BackendBuildReport) { return this.update(r, { integrationsCompleted: [entry("bew-int-", "External API integration", "Bound external API client")], apiClients: [entry("bew-int-", "Approved API client", "Resilient API client")], webhooks: [entry("bew-int-", "Lifecycle webhook", "Verified webhook integration")] }, "implement_integrations", "Implement external API integrations"); }
  addJobs(r: BackendBuildReport) { return this.update(r, { backgroundJobs: [entry("bew-job-", "Reconciliation job", "Scheduled resilient background processing")] }, "implement_jobs", "Implement background workers and scheduled jobs"); }
  addValidation(r: BackendBuildReport) { return this.update(r, { errorHandlingStatus: "configured", validationRules: [entry("bew-val-", "Input validation", "Validated inputs and safe failure handling")], middleware: [entry("bew-mw-", "Error handling middleware", "Structured error handling and audit logging")], loggingConfigured: true }, "implement_validation", "Implement validation and error handling"); }
  addModularServices(r: BackendBuildReport) { const services = r.servicesImplemented.length ? r.servicesImplemented : [entry("bew-svc-", "Core backend service", "Reusable modular backend service")]; return this.update(r, { servicesImplemented: services, configurationManagement: "configured", testCoverageSummary: "Structural coverage: API, service, authorization, integration, job, validation, and error paths reviewed" }, "produce_modular_services", "Produce secure maintainable backend modules"); }
  complete(r: BackendBuildReport) { let result = r; if (!result.apisImplemented.length) result = this.addApis(result, []); if (!result.businessLogicModules.length) result = this.addBusinessLogic(result); if (result.authenticationStatus !== "configured") result = this.addAuth(result); if (!result.integrationsCompleted.length) result = this.addIntegrations(result); if (!result.backgroundJobs.length) result = this.addJobs(result); if (result.errorHandlingStatus !== "configured") result = this.addValidation(result); if (result.configurationManagement !== "configured") result = this.addModularServices(result); const findings: ReviewFinding[] = []; if (!result.requirementsReportId) findings.push({ findingId: "bew-val-requirements", category: "requirements", severity: "error", message: "Approved requirements ID is required" }); if (!result.architectureReportId) findings.push({ findingId: "bew-val-architecture", category: "architecture", severity: "error", message: "Approved architecture ID is required" }); const passed = findings.length === 0; return this.lockReport({ ...result, timestamp: now(), buildStatus: passed ? "complete" : "in_progress", confidenceScore: passed ? 95 : 65, selfReviewPassed: passed, selfReviewFindings: findings, selfReviewSummary: passed ? "Self-review passed: secure traceable modular backend build" : "Self-review requires approved architecture", qualityReview: passed ? "APIs, services, authorization, integrations, jobs, validation, and error handling complete" : "Incomplete dependency context", complianceReview: "No frontend UI, new requirements, architecture override, authority override, or Q6-06 work performed", backendCompliance: passed ? "compliant" : "partial", backendComplianceNotes: passed ? "Approved requirements and architecture preserved" : "Architecture report required", buildSteps: [...result.buildSteps, this.step("produce_report", "Produce backend build report", result.buildSteps.length + 1, "Build report assembled")] }); }
  private update(r: BackendBuildReport, fields: Partial<BackendBuildReport>, type: string, title: string) { return this.lockReport({ ...r, ...fields, timestamp: now(), buildStatus: "in_progress", confidenceScore: Math.max(r.confidenceScore, 55), buildSteps: [...r.buildSteps, this.step(type, title, r.buildSteps.length + 1, `${title} completed`)] }); }
  private step(stepType: string, title: string, order: number, summary: string) { return { stepId: `bew-step-${stepType}-${order}`, stepType, title, order, summary }; }
  lockReport(report: Omit<BackendBuildReport, keyof BoundaryFlags> & Partial<BoundaryFlags>): BackendBuildReport { return { ...report, metadataVersion: BEW_METADATA_VERSION, neverBuildFrontendUi: true, neverDesignNewRequirements: true, neverOverrideApprovedArchitecture: true, neverOverridePillow: true, neverOverrideGrandKing: true, neverImplementQ606OrLater: true, followApprovedRequirementsAndArchitecture: true, preserveCompleteTraceability: true, produceModularReusableServices: true, validateInputsAndHandleFailuresSafely: true, preserveAuditHistory: true, structuralSignalOnly: true, maskSensitiveValues: true } as BackendBuildReport; }
}
type BoundaryFlags = Pick<BackendBuildReport, "neverBuildFrontendUi" | "neverDesignNewRequirements" | "neverOverrideApprovedArchitecture" | "neverOverridePillow" | "neverOverrideGrandKing" | "neverImplementQ606OrLater" | "followApprovedRequirementsAndArchitecture" | "preserveCompleteTraceability" | "produceModularReusableServices" | "validateInputsAndHandleFailuresSafely" | "preserveAuditHistory" | "structuralSignalOnly" | "maskSensitiveValues">;
export function resetBackendSequenceForTesting() { sequence = 0; }
