import { BACKEND_WORKER_ID, BEW_CAPABILITIES, BEW_METADATA_VERSION, INTEGRATION_TARGETS } from "./paths.js";
import { BackendBuilder } from "./backend-builder.js"; import { BackendStore } from "./backend-store.js"; import { BackendValidator, HealthMonitor, RecoveryManager } from "./backend-validator.js"; import { IntegrationCoordinator, type BackendWorkerDependencies } from "./integrations.js"; import { appendBewLog } from "./bew-logging.js";
import type { BackendBuildReport, BackendWorkerCatalog, BackendWorkerEngineRecord, BackendWorkerInput, BackendWorkerRunReport, IntegrationHandshake } from "./types.js"; import type { BackendWorkerConfiguration } from "./configuration.js";
export class BackendManager {
  private readonly store = new BackendStore(); private readonly builder = new BackendBuilder(); private readonly validator = new BackendValidator(); private readonly health = new HealthMonitor(); private readonly recovery = new RecoveryManager(); private readonly integrations = new IntegrationCoordinator(); private engineRecord: BackendWorkerEngineRecord | null = null; private seeded = false; private handshakes: IntegrationHandshake[] = [];
  bindIntegrations(deps: BackendWorkerDependencies = {}) { this.integrations.bind(deps); }
  ensureSeeded(config: BackendWorkerConfiguration) { if (!this.seeded) { this.store.seed(config.seedBackendBuildReports); this.seeded = true; this.record("connected", config, "pass"); } }
  connect(_: Record<string, unknown>, config: BackendWorkerConfiguration) { this.ensureSeeded(config); this.handshakes = this.integrations.connect(config.workerId); this.record("connected", config, "pass"); return this.report("connect", [], null, this.validator.finalize("pass", [], [], Date.now()), Date.now()); }
  receiveApprovedRequirementsReports(input: BackendWorkerInput, config: BackendWorkerConfiguration) { return this.stage("receive_approved_requirements_reports", input, config, (report) => report, true, true); }
  receiveApprovedArchitectureReports(input: BackendWorkerInput, config: BackendWorkerConfiguration) { return this.stage("receive_approved_architecture_reports", input, config, (report, architecture) => this.builder.lockReport({ ...report, architectureReportId: architecture?.architectureId ?? input.architectureReportId ?? report.architectureReportId, confidenceScore: Math.max(report.confidenceScore, 50), buildSteps: [...report.buildSteps, { stepId: `bew-step-receive-architecture-${report.buildSteps.length + 1}`, stepType: "receive_architecture", title: "Receive approved architecture", order: report.buildSteps.length + 1, summary: "Architecture and API plan recorded" }], traceabilityRefs: [...new Set([...report.traceabilityRefs, architecture?.architectureId ?? input.architectureReportId ?? "architecture:missing"])] }), true); }
  buildRestAndGraphqlApis(input: BackendWorkerInput, config: BackendWorkerConfiguration) { return this.stage("build_rest_and_graphql_apis", input, config, (report, architecture) => this.builder.addApis(report, architecture?.apiArchitecture ?? [])); }
  implementBusinessLogic(input: BackendWorkerInput, config: BackendWorkerConfiguration) { return this.stage("implement_business_logic", input, config, (report) => this.builder.addBusinessLogic(report)); }
  implementAuthenticationAndAuthorization(input: BackendWorkerInput, config: BackendWorkerConfiguration) { return this.stage("implement_authentication_and_authorization", input, config, (report) => this.builder.addAuth(report)); }
  implementExternalApiIntegrations(input: BackendWorkerInput, config: BackendWorkerConfiguration) { return this.stage("implement_external_api_integrations", input, config, (report) => this.builder.addIntegrations(report)); }
  implementBackgroundWorkersAndScheduledJobs(input: BackendWorkerInput, config: BackendWorkerConfiguration) { return this.stage("implement_background_workers_and_scheduled_jobs", input, config, (report) => this.builder.addJobs(report)); }
  implementValidationAndErrorHandling(input: BackendWorkerInput, config: BackendWorkerConfiguration) { return this.stage("implement_validation_and_error_handling", input, config, (report) => this.builder.addValidation(report)); }
  produceSecureMaintainableBackendModules(input: BackendWorkerInput, config: BackendWorkerConfiguration) { return this.stage("produce_secure_maintainable_backend_modules", input, config, (report) => this.builder.addModularServices(report)); }
  produceModularBackendServices(input: BackendWorkerInput, config: BackendWorkerConfiguration) { return this.produceSecureMaintainableBackendModules(input, config); }
  produceBackendBuildReport(input: BackendWorkerInput, config: BackendWorkerConfiguration) { return this.stage("produce_backend_build_report", input, config, (report) => this.builder.complete(report), false); }
  submitReport(input: BackendWorkerInput, config: BackendWorkerConfiguration) { const started = Date.now(); const produced = this.produceBackendBuildReport(input, config); const latest = produced.latestBackendBuildReport; if (!latest || produced.validation.decision === "fail") return produced; const submission = this.integrations.submitReport(latest); const saved = submission.submitted ? this.store.markSubmitted(latest.buildId, submission.executiveReportId!)! : latest; return this.finish("submit_report", [saved], saved, this.validator.validateBackendBuildReports([saved], input, started), started, config); }
  list(config: BackendWorkerConfiguration) { this.ensureSeeded(config); const reports = this.store.list(); return this.finish("list", reports, reports.at(-1) ?? null, this.validator.validateBackendBuildReports(reports.length ? reports : null, { validated: true }, Date.now(), true), Date.now(), config); }
  validate(input: BackendWorkerInput, config: BackendWorkerConfiguration) { const reports = this.store.list(); return this.finish("validate", reports, reports.at(-1) ?? null, this.validator.validateBackendBuildReports(reports.length ? reports : null, input, Date.now()), Date.now(), config); }
  diagnostics(config: BackendWorkerConfiguration) { return this.list(config); }
  getBackendBuildReports() { return this.store.list(); } getLatestBackendBuildReportId() { return this.store.getLatestBackendBuildReportId(); } getAuditTrail() { return this.store.getAuditTrail(); } getIntegrations() { return this.handshakes.map((item) => ({ ...item })); } getEngineRecord() { return this.engineRecord ? structuredClone(this.engineRecord) : null; }
  getCatalog(): BackendWorkerCatalog { return { reportVersion: "BEW-RPT-v1", workerId: this.engineRecord?.workerId ?? "wkr-backend-01", backendBuildReports: this.store.list(), integrations: this.getIntegrations(), metadataVersion: BEW_METADATA_VERSION, executiveAuthority: "pillow", neverBuildFrontendUi: true, neverDesignNewRequirements: true, neverOverrideApprovedArchitecture: true, neverOverridePillow: true, neverOverrideGrandKing: true, neverImplementQ606OrLater: true }; }
  private stage(action: string, input: BackendWorkerInput, config: BackendWorkerConfiguration, mutate: (report: BackendBuildReport, architecture?: ReturnType<IntegrationCoordinator["enrich"]>["architecture"]) => BackendBuildReport, incomplete = true, newShell = false) { const started = Date.now(); this.ensureSeeded(config); const enriched = this.integrations.enrich(input); const violations = this.validator.validateBackendBuildReports(null, enriched.input, started); if (violations.decision === "fail") return this.finish(action, [], null, violations, started, config); let report = !newShell ? this.store.list().at(-1) : null; if (!report) report = this.builder.createShell(enriched.input, config); report = mutate(report, enriched.architecture); this.store.save(report, action); return this.finish(action, [report], report, this.validator.validateBackendBuildReports([report], enriched.input, started, incomplete), started, config); }
  private finish(action: string, reports: BackendBuildReport[], latest: BackendBuildReport | null, validation: BackendWorkerRunReport["validation"], started: number, config: BackendWorkerConfiguration) { if (validation.decision === "fail") this.recovery.recordFailure(); else this.recovery.reset(); this.record(validation.decision === "fail" ? "failed" : "active", config, validation.decision, latest); appendBewLog({ event: action, details: `build=${latest?.buildId ?? "none"}` }); return this.report(action, reports, latest, validation, started); }
  private record(state: string, config: BackendWorkerConfiguration, validation: "pass" | "partial" | "fail", latest: BackendBuildReport | null = null) { const report = latest ?? this.store.list().at(-1) ?? null; this.engineRecord = { engineRecordId: this.engineRecord?.engineRecordId ?? `bew-eng-${Date.now()}`, timestamp: new Date().toISOString(), engineId: BACKEND_WORKER_ID, engineVersion: "PILLOW-BEW-001", currentOperationalState: state, healthStatus: this.health.status(validation, config.enabled), validationStatus: validation === "pass" ? "passed" : validation === "fail" ? "failed" : "partial", supportedCapabilities: [...BEW_CAPABILITIES], totalBackendBuildReports: this.store.count(), lastBackendBuildReportId: report?.buildId ?? null, lastConfidenceScore: report?.confidenceScore ?? null, workerId: config.workerId, integrationTargets: [...INTEGRATION_TARGETS], metadataVersion: BEW_METADATA_VERSION }; }
  private report(action: string, reports: BackendBuildReport[], latest: BackendBuildReport | null, validation: BackendWorkerRunReport["validation"], started: number): BackendWorkerRunReport { return { backendRunReportId: `bew-run-${Date.now()}`, runTimestamp: new Date().toISOString(), action, engineRecord: this.engineRecord!, catalog: this.getCatalog(), backendBuildReports: reports, latestBackendBuildReport: latest, integrations: this.getIntegrations(), validation, durationMs: Date.now() - started, metadataVersion: BEW_METADATA_VERSION }; }
}
