import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { BACKEND_COMPONENTS, BACKEND_WORKER_IDENTITY, INTEGRATION_TARGETS } from "./paths.js";
import type { BackendBuildReport } from "./types.js";
export type BackendWorkerConfiguration = { enabled: boolean; backendRulesEnabled: boolean; validationRulesEnabled: boolean; executiveReportingEnabled: boolean; integrationTargets: string[]; supportedBackendComponents: string[]; workerId: string; workerName: string; factory: string; department: string; role: string; reportingLine: string[]; seedBackendBuildReports: BackendBuildReport[]; timeoutMs: number; loggingLevel: "error" | "warn" | "info" | "debug"; neverBuildFrontendUi: true; neverDesignNewRequirements: true; neverOverrideApprovedArchitecture: true; neverOverridePillow: true; neverOverrideGrandKing: true; neverImplementQ606OrLater: true; followApprovedRequirementsAndArchitecture: true; preserveCompleteTraceability: true; produceModularReusableServices: true; validateInputsAndHandleFailuresSafely: true; preserveAuditHistory: true; structuralSignalOnly: true; maskSensitiveValues: true };
export const DEFAULT_BACKEND_WORKER_CONFIGURATION: BackendWorkerConfiguration = { enabled: true, backendRulesEnabled: true, validationRulesEnabled: true, executiveReportingEnabled: true, integrationTargets: [...INTEGRATION_TARGETS], supportedBackendComponents: [...BACKEND_COMPONENTS], workerId: BACKEND_WORKER_IDENTITY.workerId, workerName: BACKEND_WORKER_IDENTITY.workerName, factory: BACKEND_WORKER_IDENTITY.factory, department: BACKEND_WORKER_IDENTITY.department, role: BACKEND_WORKER_IDENTITY.role, reportingLine: [...BACKEND_WORKER_IDENTITY.reportingLine], seedBackendBuildReports: [], timeoutMs: 5000, loggingLevel: "info", neverBuildFrontendUi: true, neverDesignNewRequirements: true, neverOverrideApprovedArchitecture: true, neverOverridePillow: true, neverOverrideGrandKing: true, neverImplementQ606OrLater: true, followApprovedRequirementsAndArchitecture: true, preserveCompleteTraceability: true, produceModularReusableServices: true, validateInputsAndHandleFailuresSafely: true, preserveAuditHistory: true, structuralSignalOnly: true, maskSensitiveValues: true };
export function buildBackendWorkerConfiguration(repositoryRoot?: string, overrides: Partial<BackendWorkerConfiguration> = {}): BackendWorkerConfiguration {
  let file: Partial<BackendWorkerConfiguration> = {}; const candidate = repositoryRoot ? join(repositoryRoot, "config", "backend-worker.config.json") : "";
  if (candidate && existsSync(candidate)) try { file = JSON.parse(readFileSync(candidate, "utf8")); } catch { /* use defaults */ }
  const timeout = Number.parseInt(process.env.BACKEND_WORKER_TIMEOUT_MS ?? "", 10);
  return { ...DEFAULT_BACKEND_WORKER_CONFIGURATION, ...file, ...overrides, integrationTargets: [...new Set([...INTEGRATION_TARGETS, ...(file.integrationTargets ?? []), ...(overrides.integrationTargets ?? [])])], supportedBackendComponents: [...new Set([...BACKEND_COMPONENTS, ...(file.supportedBackendComponents ?? []), ...(overrides.supportedBackendComponents ?? [])])], reportingLine: [...(overrides.reportingLine ?? file.reportingLine ?? DEFAULT_BACKEND_WORKER_CONFIGURATION.reportingLine)], seedBackendBuildReports: [...(overrides.seedBackendBuildReports ?? file.seedBackendBuildReports ?? [])], ...(Number.isFinite(timeout) ? { timeoutMs: timeout } : {}), neverBuildFrontendUi: true, neverDesignNewRequirements: true, neverOverrideApprovedArchitecture: true, neverOverridePillow: true, neverOverrideGrandKing: true, neverImplementQ606OrLater: true, followApprovedRequirementsAndArchitecture: true, preserveCompleteTraceability: true, produceModularReusableServices: true, validateInputsAndHandleFailuresSafely: true, preserveAuditHistory: true, structuralSignalOnly: true, maskSensitiveValues: true };
}
