import type { EmpireBootstrapContext } from "../bootstrap/types.js";
import { RepositoryReader } from "../bootstrap/repository-reader.js";
import { buildBackendWorkerConfiguration, type BackendWorkerConfiguration } from "./configuration.js";
import { BackendWorkerController } from "./backend-worker-controller.js";
import { BackendManager } from "./backend-manager.js";
import type { BackendWorkerDependencies } from "./integrations.js";
import { resetBewLogsForTesting } from "./bew-logging.js";
import { resetBackendSequenceForTesting } from "./backend-builder.js";
import { BACKEND_WORKER_SYSTEM_PATH } from "./paths.js";
import type { BackendWorkerCockpitSnapshot, BackendWorkerInput, BackendWorkerState } from "./types.js";
export interface BackendWorkerOptions { configuration?: Partial<BackendWorkerConfiguration>; dependencies?: BackendWorkerDependencies; }
export class BackendWorker {
  private initializedAt: string | null = null; private readonly controller: BackendWorkerController;
  constructor(private readonly bootstrap: EmpireBootstrapContext, options: BackendWorkerOptions = {}) { const manager = new BackendManager(); if (options.dependencies) manager.bindIntegrations(options.dependencies); this.controller = new BackendWorkerController(manager, buildBackendWorkerConfiguration(bootstrap.repositoryRoot, options.configuration)); }
  async initialize() { const document = await new RepositoryReader(this.bootstrap.repositoryRoot).readText(BACKEND_WORKER_SYSTEM_PATH); if (!document?.includes("Backend Worker")) throw new Error(`${BACKEND_WORKER_SYSTEM_PATH} missing — Q6-05 system doc required.`); this.controller.initialize(); this.initializedAt = new Date().toISOString(); return this.getState(); }
  bindIntegrations(deps: BackendWorkerDependencies = {}) { this.controller.bindIntegrations(deps); }
  getState(): BackendWorkerState { if (!this.initializedAt) throw new Error("Backend Worker not initialized. Call initialize() first."); const configuration = this.controller.getConfiguration(); const engineRecord = this.controller.getManager().getEngineRecord(); const latestReport = this.controller.getLatestReport(); return { engineVersion: "PILLOW-BEW-001", missionId: "Q6-05", status: this.controller.getStatus(), initializedAt: this.initializedAt, configuration, latestReport, engineRecord, health: { status: engineRecord?.healthStatus ?? "standby", healthScore: engineRecord?.healthStatus === "healthy" ? 100 : engineRecord ? 70 : 50, engineEnabled: configuration.enabled, lastOperationAt: latestReport?.runTimestamp ?? null, lastValidationDecision: latestReport?.validation.decision ?? null, totalBackendBuildReports: engineRecord?.totalBackendBuildReports ?? 0, lastBackendBuildReportId: engineRecord?.lastBackendBuildReportId ?? null, lastConfidenceScore: engineRecord?.lastConfidenceScore ?? null, notes: ["Backend Worker builds secure modular backend signals from approved requirements and architecture; it does not build frontend UI, design requirements, override approved architecture or authority, or implement Q6-06 or later."] } }; }
  connect(input: Record<string, unknown> = {}) { return this.controller.connect(input); } receiveApprovedRequirementsReports(input: BackendWorkerInput = {}) { return this.controller.receiveApprovedRequirementsReports(input); } receiveApprovedRequirementsReport(input: BackendWorkerInput = {}) { return this.controller.receiveApprovedRequirementsReport(input); } receiveApprovedArchitectureReports(input: BackendWorkerInput = {}) { return this.controller.receiveApprovedArchitectureReports(input); } receiveApprovedArchitectureReport(input: BackendWorkerInput = {}) { return this.controller.receiveApprovedArchitectureReport(input); } buildRestAndGraphqlApis(input: BackendWorkerInput = {}) { return this.controller.buildRestAndGraphqlApis(input); } implementBusinessLogic(input: BackendWorkerInput = {}) { return this.controller.implementBusinessLogic(input); } implementAuthenticationAndAuthorization(input: BackendWorkerInput = {}) { return this.controller.implementAuthenticationAndAuthorization(input); } implementExternalApiIntegrations(input: BackendWorkerInput = {}) { return this.controller.implementExternalApiIntegrations(input); } implementBackgroundWorkersAndScheduledJobs(input: BackendWorkerInput = {}) { return this.controller.implementBackgroundWorkersAndScheduledJobs(input); } implementValidationAndErrorHandling(input: BackendWorkerInput = {}) { return this.controller.implementValidationAndErrorHandling(input); } produceSecureMaintainableBackendModules(input: BackendWorkerInput = {}) { return this.controller.produceSecureMaintainableBackendModules(input); } produceModularBackendServices(input: BackendWorkerInput = {}) { return this.controller.produceModularBackendServices(input); } produceBackendBuildReport(input: BackendWorkerInput = {}) { return this.controller.produceBackendBuildReport(input); } submitReport(input: BackendWorkerInput = {}) { return this.controller.submitReport(input); } list() { return this.controller.list(); } validate(input: BackendWorkerInput = {}) { return this.controller.validate(input); } diagnostics() { return this.controller.diagnostics(); }
  getBackendBuildReports() { return this.controller.getManager().getBackendBuildReports(); } getCatalog() { return this.controller.getManager().getCatalog(); } getEngineRecord() { return this.controller.getManager().getEngineRecord(); } getLatestBackendBuildReportId() { return this.controller.getManager().getLatestBackendBuildReportId(); } getAuditTrail() { return this.controller.getManager().getAuditTrail(); } getIntegrations() { return this.controller.getManager().getIntegrations(); }
  validateForSupervisorSync() { const state = this.getState(); const score = state.latestReport?.validation.decision === "fail" ? 40 : state.latestReport?.validation.decision === "partial" ? 70 : 100; return { valid: state.health.status !== "failed", health: score >= 75 ? "healthy" as const : score >= 50 ? "degraded" as const : "blocked" as const, readinessScore: score, notes: state.health.notes }; }
  getCockpitSnapshot(): BackendWorkerCockpitSnapshot { const state = this.getState(); return { missionId: "Q6-05", status: state.status, healthStatus: state.health.status, totalBackendBuildReports: state.health.totalBackendBuildReports, latestBackendBuildReportId: this.getLatestBackendBuildReportId(), lastConfidenceScore: state.health.lastConfidenceScore, workerId: state.configuration.workerId, neverBuildFrontendUi: true, neverDesignNewRequirements: true, neverOverrideApprovedArchitecture: true, neverImplementQ606OrLater: true }; }
}
export const createBackendWorker = (bootstrap: EmpireBootstrapContext, options?: BackendWorkerOptions) => new BackendWorker(bootstrap, options);
export function resetBackendWorkerForTesting() { resetBewLogsForTesting(); resetBackendSequenceForTesting(); }
