import type { BackendBuildReport, BackendWorkerInput, BewIntegrationTarget, IntegrationHandshake } from "./types.js";
import { BACKEND_WORKER_IDENTITY, INTEGRATION_TARGETS } from "./paths.js";
import { appendBewLog } from "./bew-logging.js";
export type RequirementsWorker = { getRequirementsReports?: () => Array<{ requirementsId?: string; platformId?: string; platformName?: string; businessId?: string; factoryMissionId?: string; businessObjective?: string }>; getLatestRequirementsReportId?: () => string | null };
export type ArchitectureWorkerSurface = { getArchitectureReports?: () => Array<{ architectureId?: string; platformId?: string; platformName?: string; businessId?: string; factoryMissionId?: string; businessObjective?: string; requirementsReportId?: string; apiArchitecture?: Array<{ apiId?: string; name?: string; protocol?: string; endpoints?: string[]; direction?: string }> }>; getLatestArchitectureReportId?: () => string | null };
export type BackendWorkerDependencies = {
  workerRegistry?: { registerWorker: (input: Record<string, unknown>) => unknown } | null;
  workerLifecycle?: { createWorker: (input: Record<string, unknown>) => unknown; activateWorker: (input: Record<string, unknown>) => unknown } | null;
  workerAssignmentEngine?: { discoverEligibleWorkers: (input: Record<string, unknown>) => unknown } | null;
  enterprisePlatformFactoryCore?: { getMissions?: () => Array<{ factoryMissionId?: string; platformId?: string; platformName?: string; businessId?: string; businessObjective?: string }>; getLatestMissionId?: () => string | null } | null;
  requirementsWorker?: RequirementsWorker | null; architectureWorker?: ArchitectureWorkerSurface | null;
  frontendWorker?: { getFrontendBuildReports?: () => Array<{ buildId?: string; platformId?: string; architectureReportId?: string; requirementsReportId?: string }>; getLatestFrontendBuildReportId?: () => string | null } | null;
  executiveReportingRuntime?: { submitWorkerReport: (input: Record<string, unknown>) => { records?: Array<{ reportId?: string }> } } | null;
  workerPerformanceReview?: { registerPerformanceWorker: (input: Record<string, unknown>) => unknown } | null;
  workerRecoverySystem?: { registerRecoverableWorker: (input: Record<string, unknown>) => unknown } | null;
};
export class IntegrationCoordinator {
  private deps: BackendWorkerDependencies = {}; private handshakes: IntegrationHandshake[] = [];
  bind(deps: BackendWorkerDependencies = {}) { this.deps = { ...deps }; }
  connect(workerId: string) { const timestamp = new Date().toISOString(); this.handshakes = INTEGRATION_TARGETS.map((target) => { const status = this.bound(target) ? "bound" : "ready"; appendBewLog({ event: "integration_handshake", details: `${target}:${status}` }); return { target, status, details: `Backend Worker ${workerId} ↔ ${target} (${status})`, timestamp }; }); this.provision(workerId); return this.getHandshakes(); }
  getHandshakes() { return this.handshakes.map((handshake) => ({ ...handshake })); }
  enrich(input: BackendWorkerInput) {
    const reqs = this.deps.requirementsWorker?.getRequirementsReports?.() ?? []; const req = reqs.find((r) => r.requirementsId === input.requirementsReportId) ?? reqs.at(-1);
    const architectures = this.deps.architectureWorker?.getArchitectureReports?.() ?? []; const architecture = architectures.find((r) => r.architectureId === input.architectureReportId || r.platformId === input.platformId || r.businessId === input.businessId) ?? architectures.at(-1);
    const missions = this.deps.enterprisePlatformFactoryCore?.getMissions?.() ?? []; const mission = missions.find((m) => m.factoryMissionId === input.factoryMissionId || m.platformId === input.platformId || m.businessId === input.businessId) ?? missions.at(-1);
    const frontend = this.deps.frontendWorker?.getFrontendBuildReports?.().at(-1);
    return { input: { ...input, requirementsReportId: input.requirementsReportId ?? req?.requirementsId ?? frontend?.requirementsReportId ?? this.deps.requirementsWorker?.getLatestRequirementsReportId?.() ?? null, architectureReportId: input.architectureReportId ?? architecture?.architectureId ?? frontend?.architectureReportId ?? this.deps.architectureWorker?.getLatestArchitectureReportId?.() ?? null, platformId: input.platformId ?? architecture?.platformId ?? req?.platformId ?? frontend?.platformId ?? mission?.platformId ?? null, platformName: input.platformName ?? architecture?.platformName ?? req?.platformName ?? mission?.platformName ?? null, businessId: input.businessId ?? architecture?.businessId ?? req?.businessId ?? mission?.businessId ?? null, factoryMissionId: input.factoryMissionId ?? architecture?.factoryMissionId ?? req?.factoryMissionId ?? mission?.factoryMissionId ?? this.deps.enterprisePlatformFactoryCore?.getLatestMissionId?.() ?? null, businessObjective: input.businessObjective ?? architecture?.businessObjective ?? req?.businessObjective ?? mission?.businessObjective ?? null }, architecture };
  }
  submitReport(report: BackendBuildReport) {
    const runtime = this.deps.executiveReportingRuntime; if (!runtime?.submitWorkerReport) return { submitted: false, executiveReportId: null, details: "executive_reporting_runtime_unavailable" };
    const result = runtime.submitWorkerReport({ reportingEntity: report.workerId, entityType: "worker", businessId: report.businessId, missionId: "Q6-05", currentStatus: "backend_build_report_prepared", progress: Math.round(report.confidenceScore), blockers: report.selfReviewPassed ? [] : [`self_review_blocker:${report.buildId}`], evidence: [`requirements:${report.requirementsReportId}`, `architecture:${report.architectureReportId}`, `apis:${report.apisImplemented.length}`, `services:${report.servicesImplemented.length}`], nextAction: "awaiting_pillow_review_of_backend_build_no_frontend_ui", completionStatus: "completed", reportType: "worker", validated: true, neverBuiltFrontendUi: true, neverDesignedNewRequirements: true, neverOverrodeApprovedArchitecture: true });
    const executiveReportId = result?.records?.find((record) => record.reportId)?.reportId ?? `ert-bew-${Date.now()}`; appendBewLog({ event: "submit_report", details: `build=${report.buildId} executive=${executiveReportId}` }); return { submitted: true, executiveReportId, details: "submitted_to_executive_reporting_runtime" };
  }
  private provision(workerId: string) { const identity = { workerId, workerName: BACKEND_WORKER_IDENTITY.workerName, workerType: BACKEND_WORKER_IDENTITY.workerType, department: BACKEND_WORKER_IDENTITY.department, factory: BACKEND_WORKER_IDENTITY.factory, role: BACKEND_WORKER_IDENTITY.role, reportingLine: [...BACKEND_WORKER_IDENTITY.reportingLine], certificationStatus: "certified", operationalStatus: "active", validated: true }; try { this.deps.workerRegistry?.registerWorker?.(identity); this.deps.workerLifecycle?.createWorker?.(identity); this.deps.workerLifecycle?.activateWorker?.({ workerId, validated: true }); this.deps.workerAssignmentEngine?.discoverEligibleWorkers?.({ missionId: "Q6-05", validated: true }); this.deps.workerPerformanceReview?.registerPerformanceWorker?.({ workerId, validated: true }); this.deps.workerRecoverySystem?.registerRecoverableWorker?.({ workerId, validated: true }); } catch { /* optional integrations */ } }
  private bound(target: BewIntegrationTarget) { const d = this.deps; switch (target) { case "worker_registry": return Boolean(d.workerRegistry?.registerWorker); case "worker_lifecycle": return Boolean(d.workerLifecycle?.createWorker); case "worker_assignment_engine": return Boolean(d.workerAssignmentEngine?.discoverEligibleWorkers); case "enterprise_platform_factory_core": return Boolean(d.enterprisePlatformFactoryCore?.getMissions); case "requirements_worker": return Boolean(d.requirementsWorker?.getRequirementsReports); case "architecture_worker": return Boolean(d.architectureWorker?.getArchitectureReports); case "frontend_worker": return Boolean(d.frontendWorker?.getFrontendBuildReports); case "executive_reporting_runtime": return Boolean(d.executiveReportingRuntime?.submitWorkerReport); case "worker_performance_review": return Boolean(d.workerPerformanceReview?.registerPerformanceWorker); case "worker_recovery_system": return Boolean(d.workerRecoverySystem?.registerRecoverableWorker); } }
}
