import type { BACKEND_COMPONENTS, BEW_CAPABILITIES, ENGINE_STATUSES, INTEGRATION_TARGETS } from "./paths.js";
import type { BackendWorkerConfiguration } from "./configuration.js";
export type BewEngineStatus = (typeof ENGINE_STATUSES)[number];
export type BackendComponent = (typeof BACKEND_COMPONENTS)[number];
export type BewIntegrationTarget = (typeof INTEGRATION_TARGETS)[number];
export type BackendWorkerCapability = (typeof BEW_CAPABILITIES)[number];
export type BuildStatus = "draft" | "in_progress" | "complete" | "failed";
export type BuildEntry = { id: string; name: string; description: string; source?: string; fields?: string[]; validationRules?: string[] };
export type BuildStep = { stepId: string; stepType: string; title: string; order: number; summary: string };
export type ReviewFinding = { findingId: string; category: string; severity: "info" | "warning" | "error"; message: string };
export type PreservedDecision = { decisionId: string; topic: string; decision: string; recordedAt: string };
export type BackendBuildReport = {
  buildId: string; timestamp: string; platformId: string; platformName: string; servicesImplemented: BuildEntry[]; apisImplemented: BuildEntry[];
  authenticationStatus: "configured" | "partial" | "pending"; integrationsCompleted: BuildEntry[]; backgroundJobs: BuildEntry[];
  errorHandlingStatus: "configured" | "partial" | "pending"; testCoverageSummary: string; buildStatus: BuildStatus; confidenceScore: number; metadataVersion: string;
  requirementsReportId: string; architectureReportId: string; factoryMissionId: string; businessId: string; businessObjective: string;
  authorizationStatus: "configured" | "partial" | "pending"; middleware: BuildEntry[]; validationRules: BuildEntry[]; loggingConfigured: boolean; configurationManagement: string;
  webhooks: BuildEntry[]; apiClients: BuildEntry[]; businessLogicModules: BuildEntry[]; buildSteps: BuildStep[]; selfReviewPassed: boolean;
  selfReviewFindings: ReviewFinding[]; selfReviewSummary: string; qualityReview: string; complianceReview: string; backendCompliance: "compliant" | "partial" | "non_compliant";
  backendComplianceNotes: string; workerId: string; reportVersion: string; traceabilityRefs: string[]; preservedDecisions: PreservedDecision[];
  submittedToExecutiveReporting: boolean; executiveReportId: string | null;
  neverBuildFrontendUi: true; neverDesignNewRequirements: true; neverOverrideApprovedArchitecture: true; neverOverridePillow: true; neverOverrideGrandKing: true; neverImplementQ606OrLater: true;
  followApprovedRequirementsAndArchitecture: true; preserveCompleteTraceability: true; produceModularReusableServices: true; validateInputsAndHandleFailuresSafely: true; preserveAuditHistory: true; structuralSignalOnly: true; maskSensitiveValues: true;
};
export type BackendWorkerInput = { buildId?: string | null; requirementsReportId?: string | null; architectureReportId?: string | null; platformId?: string | null; platformName?: string | null; businessId?: string | null; factoryMissionId?: string | null; businessObjective?: string | null; validated?: boolean; buildFrontendUi?: boolean; designNewRequirements?: boolean; overrideApprovedArchitecture?: boolean; overridePillow?: boolean; overrideGrandKing?: boolean; implementQ606OrLater?: boolean };
export type IntegrationHandshake = { target: BewIntegrationTarget; status: "ready" | "bound" | "unavailable"; details: string; timestamp: string };
export type BackendWorkerValidationReport = { validationReportId: string; validationTimestamp: string; decision: "pass" | "partial" | "fail"; errors: string[]; warnings: string[]; durationMs: number; metadataVersion: string };
export type BackendWorkerEngineRecord = { engineRecordId: string; timestamp: string; engineId: string; engineVersion: "PILLOW-BEW-001"; currentOperationalState: string; healthStatus: "healthy" | "degraded" | "failed" | "standby"; validationStatus: string; supportedCapabilities: BackendWorkerCapability[]; totalBackendBuildReports: number; lastBackendBuildReportId: string | null; lastConfidenceScore: number | null; workerId: string; integrationTargets: BewIntegrationTarget[]; metadataVersion: string };
export type BackendWorkerCatalog = { reportVersion: string; workerId: string; backendBuildReports: BackendBuildReport[]; integrations: IntegrationHandshake[]; metadataVersion: string; executiveAuthority: "pillow"; neverBuildFrontendUi: true; neverDesignNewRequirements: true; neverOverrideApprovedArchitecture: true; neverOverridePillow: true; neverOverrideGrandKing: true; neverImplementQ606OrLater: true };
export type BackendWorkerRunReport = { backendRunReportId: string; runTimestamp: string; action: string; engineRecord: BackendWorkerEngineRecord; catalog: BackendWorkerCatalog | null; backendBuildReports: BackendBuildReport[]; latestBackendBuildReport: BackendBuildReport | null; integrations: IntegrationHandshake[]; validation: BackendWorkerValidationReport; durationMs: number; metadataVersion: string };
export type BackendWorkerState = { engineVersion: "PILLOW-BEW-001"; missionId: "Q6-05"; status: BewEngineStatus; initializedAt: string; configuration: BackendWorkerConfiguration; latestReport: BackendWorkerRunReport | null; engineRecord: BackendWorkerEngineRecord | null; health: { status: "healthy" | "degraded" | "failed" | "standby"; healthScore: number; engineEnabled: boolean; lastOperationAt: string | null; lastValidationDecision: "pass" | "partial" | "fail" | null; totalBackendBuildReports: number; lastBackendBuildReportId: string | null; lastConfidenceScore: number | null; notes: string[] } };
export type BackendWorkerCockpitSnapshot = { missionId: "Q6-05"; status: BewEngineStatus; healthStatus: "healthy" | "degraded" | "failed" | "standby"; totalBackendBuildReports: number; latestBackendBuildReportId: string | null; lastConfidenceScore: number | null; workerId: string; neverBuildFrontendUi: true; neverDesignNewRequirements: true; neverOverrideApprovedArchitecture: true; neverImplementQ606OrLater: true };
