import type { CockpitDepartmentId } from "@/lib/cockpit/navigation";
import type { CockpitScreenId } from "@/lib/cockpit/types";
import type { CockpitDataMode } from "@/lib/cockpit/kpis/registry";

export type CockpitWidgetDefinition = {
  id: string;
  label: string;
  /** Component export name in components/cockpit/widgets. */
  component: string;
  dataMode: CockpitDataMode;
  screens: readonly CockpitScreenId[];
  department: CockpitDepartmentId | "executive" | "command" | "missions";
  placeholder: boolean;
};

/** Canonical widget catalogue — REAL-079 IDs mapped to G4-02 live wiring status. */
export const cockpitWidgetRegistry: readonly CockpitWidgetDefinition[] = [
  {
    id: "W-E-001",
    label: "Grand King Greeting",
    component: "ExecutiveHomeGreetingLive",
    dataMode: "live",
    screens: ["SCR-001"],
    department: "executive",
    placeholder: false,
  },
  {
    id: "W-E-002",
    label: "Command Snapshot",
    component: "CommandSnapshotLive",
    dataMode: "live",
    screens: ["SCR-001", "SCR-010"],
    department: "command",
    placeholder: false,
  },
  {
    id: "W-E-003",
    label: "Mission Queue Preview",
    component: "MissionQueuePreviewLive",
    dataMode: "live",
    screens: ["SCR-001", "SCR-020"],
    department: "missions",
    placeholder: false,
  },
  {
    id: "W-E-004",
    label: "Portfolio Pulse",
    component: "PortfolioPulseLive",
    dataMode: "live",
    screens: ["SCR-001", "SCR-010"],
    department: "command",
    placeholder: false,
  },
  {
    id: "W-E-005",
    label: "Department Health Row",
    component: "DepartmentHealthRowLive",
    dataMode: "live",
    screens: ["SCR-001"],
    department: "executive",
    placeholder: false,
  },
  {
    id: "W-E-006",
    label: "AI CEO Briefing",
    component: "AiCeoBriefingLive",
    dataMode: "live",
    screens: ["SCR-010"],
    department: "command",
    placeholder: false,
  },
  {
    id: "W-E-007",
    label: "Pending Decisions",
    component: "PendingDecisionsLive",
    dataMode: "live",
    screens: ["SCR-010", "SCR-020"],
    department: "command",
    placeholder: false,
  },
  {
    id: "W-E-008",
    label: "Company Portfolio Table",
    component: "PortfolioOverviewLive",
    dataMode: "live",
    screens: ["SCR-010"],
    department: "command",
    placeholder: false,
  },
  {
    id: "W-E-009",
    label: "Activity Feed",
    component: "AgentActivityLive",
    dataMode: "live",
    screens: ["SCR-001", "SCR-010"],
    department: "command",
    placeholder: false,
  },
  {
    id: "W-E-010",
    label: "Mission Blocker Strip",
    component: "MissionBlockerStripLive",
    dataMode: "live",
    screens: ["SCR-020"],
    department: "missions",
    placeholder: false,
  },
  {
    id: "W-E-011",
    label: "Mission Approval Triage",
    component: "MissionApprovalTriageLive",
    dataMode: "live",
    screens: ["SCR-020"],
    department: "missions",
    placeholder: false,
  },
  {
    id: "W-E-012",
    label: "Mission Queue Full",
    component: "MissionQueueFullLive",
    dataMode: "live",
    screens: ["SCR-020"],
    department: "missions",
    placeholder: false,
  },
  {
    id: "W-E-013",
    label: "KPI Strip",
    component: "KpiStrip",
    dataMode: "live",
    screens: ["SCR-001", "SCR-010"],
    department: "executive",
    placeholder: false,
  },
  {
    id: "W-E-014",
    label: "Executive Summary Cards",
    component: "ExecutiveSummaryCardGrid",
    dataMode: "live",
    screens: ["SCR-001"],
    department: "executive",
    placeholder: false,
  },
  {
    id: "W-E-015",
    label: "Executive Attention Strip",
    component: "ExecutiveAttentionStrip",
    dataMode: "live",
    screens: ["SCR-001"],
    department: "executive",
    placeholder: false,
  },
  {
    id: "W-E-016",
    label: "Executive Next Action",
    component: "ExecutiveNextActionStrip",
    dataMode: "live",
    screens: ["SCR-001"],
    department: "executive",
    placeholder: false,
  },
  {
    id: "W-E-017",
    label: "Executive Engine Health Strip",
    component: "ExecutiveEngineHealthStrip",
    dataMode: "live",
    screens: ["SCR-001"],
    department: "executive",
    placeholder: false,
  },
  {
    id: "W-E-018",
    label: "Executive Home Sync Bar",
    component: "ExecutiveHomeSyncBar",
    dataMode: "live",
    screens: ["SCR-001"],
    department: "executive",
    placeholder: false,
  },
  {
    id: "W-E-019",
    label: "Executive Priority Widget Grid",
    component: "ExecutivePriorityWidgetGrid",
    dataMode: "live",
    screens: ["SCR-001"],
    department: "executive",
    placeholder: false,
  },
  {
    id: "W-E-020",
    label: "Executive Alerts Panel",
    component: "ExecutiveAlertsPanel",
    dataMode: "live",
    screens: ["SCR-001"],
    department: "executive",
    placeholder: false,
  },
  {
    id: "W-E-021",
    label: "Executive Timeline Panel",
    component: "ExecutiveTimelinePanel",
    dataMode: "live",
    screens: ["SCR-001"],
    department: "executive",
    placeholder: false,
  },
  {
    id: "W-G-007",
    label: "AI Interaction Drawer",
    component: "CockpitInteractionDrawer",
    dataMode: "live",
    screens: ["SCR-001", "SCR-010", "SCR-020", "SCR-100", "SCR-110", "SCR-200", "SCR-400", "SCR-800"],
    department: "executive",
    placeholder: false,
  },
  {
    id: "W-G-008",
    label: "Engine Center AI Insight",
    component: "EngineCenterAiInsightPanel",
    dataMode: "live",
    screens: ["SCR-110", "SCR-111", "SCR-112", "SCR-200", "SCR-202", "SCR-301", "SCR-400", "SCR-401", "SCR-800"],
    department: "executive",
    placeholder: false,
  },
  {
    id: "W-G-009",
    label: "Executive Relationship Graph",
    component: "ExecutiveRelationshipGraphPanel",
    dataMode: "live",
    screens: ["SCR-015"],
    department: "executive",
    placeholder: false,
  },
  {
    id: "W-G-010",
    label: "Global AI Assistant",
    component: "GlobalAiAssistantPanel",
    dataMode: "live",
    screens: ["SCR-001", "SCR-010", "SCR-015", "SCR-020"],
    department: "executive",
    placeholder: false,
  },
  {
    id: "W-C-001",
    label: "Commerce Marketing Panel",
    component: "CommerceMarketingPanel",
    dataMode: "live",
    screens: ["SCR-202"],
    department: "commerce",
    placeholder: false,
  },
  {
    id: "W-C-002",
    label: "Commerce Ads Panel",
    component: "CommerceAdsPanel",
    dataMode: "live",
    screens: ["SCR-203"],
    department: "commerce",
    placeholder: false,
  },
  {
    id: "W-C-003",
    label: "Commerce Workspace Panel",
    component: "CommerceWorkspacePanel",
    dataMode: "live",
    screens: ["SCR-204"],
    department: "commerce",
    placeholder: false,
  },
  {
    id: "W-I-001",
    label: "Intelligence Overview Panel",
    component: "IntelligenceOverviewPanel",
    dataMode: "live",
    screens: ["SCR-100"],
    department: "intelligence",
    placeholder: false,
  },
  {
    id: "W-O-001",
    label: "Operations Orders Panel",
    component: "OperationsOrdersPanel",
    dataMode: "sandbox",
    screens: ["SCR-300"],
    department: "operations",
    placeholder: false,
  },
  {
    id: "W-F-001",
    label: "Finance Dashboard Panel",
    component: "FinanceDashboardPanel",
    dataMode: "live",
    screens: ["SCR-400"],
    department: "finance",
    placeholder: false,
  },
  {
    id: "W-W-001",
    label: "Workforce Agents Panel",
    component: "WorkforceAgentsPanel",
    dataMode: "demo",
    screens: ["SCR-500"],
    department: "workforce",
    placeholder: true,
  },
  {
    id: "W-N-001",
    label: "Infrastructure Integrations Panel",
    component: "InfrastructureIntegrationsPanel",
    dataMode: "live",
    screens: ["SCR-600"],
    department: "infrastructure",
    placeholder: false,
  },
  {
    id: "W-G-001",
    label: "Governance Policies Panel",
    component: "GovernancePoliciesPanel",
    dataMode: "demo",
    screens: ["SCR-700"],
    department: "governance",
    placeholder: true,
  },
  {
    id: "W-D-001",
    label: "Development Pillow Panel",
    component: "DevelopmentPillowPanel",
    dataMode: "live",
    screens: ["SCR-800"],
    department: "development",
    placeholder: false,
  },
] as const;

const widgetById = new Map(cockpitWidgetRegistry.map((widget) => [widget.id, widget]));

export function getCockpitWidget(id: string) {
  return widgetById.get(id);
}

export function getCockpitWidgetsForScreen(screenId: CockpitScreenId) {
  return cockpitWidgetRegistry.filter((widget) => widget.screens.includes(screenId));
}

export function getCockpitWidgetsByComponent(component: string) {
  return cockpitWidgetRegistry.filter((widget) => widget.component === component);
}
