import type { MonitoredComponentRecord } from "./types.js";

/** Canonical monitored component registry (P5-04). */
export const MONITORED_COMPONENT_REGISTRY: MonitoredComponentRecord[] = [
  {
    id: "GM-BRAIN-RT",
    domain: "brain_runtime",
    name: "Brain Runtime",
    purpose: "Event loop · memory · responsiveness under load",
    healthStatus: "healthy",
    metricsCollected: ["eventLoopLagMs", "heapUsedMb", "apiHealthy"],
    alertThresholds: "Lag ≥200ms degraded · ≥500ms critical",
    probeSource: "brain-runtime-bridge · PILLOW-BR-001",
    owner: "Brain Runtime · P5-01",
    dependencies: ["Pillow session"],
    knownDegradations: ["200+ tool boot", "Sequential startPillow()"],
    futureEvolution: "Live CPU profiling bridge",
  },
  {
    id: "GM-PILLOW",
    domain: "pillow",
    name: "Pillow COI",
    purpose: "Executive intelligence runtime health",
    healthStatus: "healthy",
    metricsCollected: ["pillowHostRunning", "coiRuntimeReady"],
    alertThresholds: "Host not running → degraded",
    probeSource: "pillow-host lifecycle",
    owner: "Pillow · PILLOW-001",
    dependencies: ["Brain LLM", "startPillow()"],
    knownDegradations: ["Lazy boot in production", "First panel 503 during boot"],
    futureEvolution: "Warm-start metrics",
  },
  {
    id: "GM-BUILDER",
    domain: "builder",
    name: "Builder (Cursor Bridge)",
    purpose: "Mission assembly and dispatch health",
    healthStatus: "healthy",
    metricsCollected: ["builderGateStatus", "dispatchMode"],
    alertThresholds: "Gate refused → warning",
    probeSource: "cursor-bridge engine",
    owner: "PILLOW-CB-001",
    dependencies: ["Supervisor", "Cursor Protocol"],
    knownDegradations: ["SDK unavailable → artifact mode"],
    futureEvolution: "Dispatch latency metrics",
  },
  {
    id: "GM-SUPERVISOR",
    domain: "supervisor",
    name: "Supervisor",
    purpose: "Mission launch · heartbeat · recovery orchestration",
    healthStatus: "healthy",
    metricsCollected: ["activeMissions", "heartbeatStatus"],
    alertThresholds: "Stale heartbeat → degraded",
    probeSource: "supervisor registry",
    owner: "PILLOW-007",
    dependencies: ["Pillow session"],
    knownDegradations: ["In-memory mission registry"],
    futureEvolution: "Persistent mission checkpoint metrics",
  },
  {
    id: "GM-COCKPIT",
    domain: "cockpit",
    name: "Executive Cockpit",
    purpose: "Grand King operational surface availability",
    healthStatus: "healthy",
    metricsCollected: ["bffProxyHealth", "authStatus"],
    alertThresholds: "Auth 401 → critical for user",
    probeSource: "empireai-web BFF",
    owner: "Cockpit · P2",
    dependencies: ["Vercel", "Backend BFF"],
    knownDegradations: ["ADR-CON-001 dual frontend"],
    futureEvolution: "Synthetic journey probes",
  },
  {
    id: "GM-JOURNEY",
    domain: "journey",
    name: "Journey System",
    purpose: "Execution history completeness",
    healthStatus: "healthy",
    metricsCollected: ["journeyEventsAvailable", "traceabilityComplete"],
    alertThresholds: "Missing evidence → warning",
    probeSource: "PILLOW-JR-001",
    owner: "Journey · P4-08",
    dependencies: ["JOURNEY.md"],
    knownDegradations: ["In-session store before synchronizer write"],
    futureEvolution: "Journey drift score",
  },
  {
    id: "GM-AUTH",
    domain: "authentication",
    name: "Authentication",
    purpose: "Login session health and token validity",
    healthStatus: "healthy",
    metricsCollected: ["authStoreMode", "sessionCount"],
    alertThresholds: "In-memory in production → high",
    probeSource: "backend/src/auth/session-store.ts",
    owner: "Brain Auth",
    dependencies: ["Redis or in-memory fallback"],
    knownDegradations: ["In-memory fallback loses sessions on restart"],
    futureEvolution: "Mandatory Redis policy enforcement",
  },
  {
    id: "GM-SESSIONS",
    domain: "sessions",
    name: "Durable Sessions",
    purpose: "Session continuity across refresh and restart",
    healthStatus: "healthy",
    metricsCollected: ["sessionCount", "recoverySuccess"],
    alertThresholds: "Integrity invalid → degraded",
    probeSource: "PILLOW-DS-001",
    owner: "Sessions · P5-03",
    dependencies: ["Redis", "localStorage"],
    knownDegradations: ["Pillow host chat ephemeral"],
    futureEvolution: "Session durability score",
  },
  {
    id: "GM-REDIS",
    domain: "redis",
    name: "Redis",
    purpose: "Auth sessions · BullMQ queue · EventBus",
    healthStatus: "healthy",
    metricsCollected: ["redisConnected", "redisMode"],
    alertThresholds: "Disconnected → degraded queue and auth",
    probeSource: "Redis probe at Brain boot",
    owner: "Infrastructure",
    dependencies: ["REDIS_URL"],
    knownDegradations: ["DegradedTaskQueue no-op without Redis"],
    futureEvolution: "Production mandatory Redis policy",
  },
  {
    id: "GM-DB",
    domain: "database",
    name: "SQLite Database",
    purpose: "Brain persistence · users · audit · guardian snapshots",
    healthStatus: "healthy",
    metricsCollected: ["sqliteHealthy", "integrityCheck"],
    alertThresholds: "Integrity failed → critical",
    probeSource: "DatabaseGuardian · guardian/health",
    owner: "Brain Database",
    dependencies: ["SQLite volume"],
    knownDegradations: ["Single-writer", "Sync cold load"],
    futureEvolution: "PostgreSQL HA",
  },
  {
    id: "GM-QUEUES",
    domain: "queues",
    name: "Task Queue (BullMQ)",
    purpose: "Background job queue depth and health",
    healthStatus: "healthy",
    metricsCollected: ["queueDepth", "redisMode"],
    alertThresholds: "Depth >100 → warning · degraded mode → high",
    probeSource: "task-queue.ts",
    owner: "Brain Runtime",
    dependencies: ["Redis", "worker.ts"],
    knownDegradations: ["Degraded no-op without Redis"],
    futureEvolution: "Queue lag SLA metrics",
  },
  {
    id: "GM-WORKERS",
    domain: "workers",
    name: "BullMQ Workers",
    purpose: "Background task processing availability",
    healthStatus: "healthy",
    metricsCollected: ["workersActive"],
    alertThresholds: "Inactive in prod API → expected · no worker process → warning",
    probeSource: "worker.ts process",
    owner: "Brain Runtime",
    dependencies: ["Redis"],
    knownDegradations: ["Separate worker process required in production"],
    futureEvolution: "Managed worker service metrics",
  },
  {
    id: "GM-MEMORY",
    domain: "memory",
    name: "Process Memory",
    purpose: "Heap and RSS usage monitoring",
    healthStatus: "healthy",
    metricsCollected: ["heapUsedMb", "rssMb"],
    alertThresholds: "Heap >80% total → warning",
    probeSource: "process.memoryUsage()",
    owner: "Brain Runtime",
    dependencies: [],
    knownDegradations: ["200+ tool registration at boot"],
    futureEvolution: "Memory leak detection",
  },
  {
    id: "GM-CPU",
    domain: "cpu",
    name: "CPU / Event Loop",
    purpose: "Event loop lag as CPU pressure proxy",
    healthStatus: "healthy",
    metricsCollected: ["eventLoopLagMs"],
    alertThresholds: "≥200ms degraded · ≥500ms critical",
    probeSource: "event-loop-cooperative.ts",
    owner: "Brain Runtime",
    dependencies: [],
    knownDegradations: ["Sequential Pillow boot chain"],
    futureEvolution: "OS-level CPU metrics bridge",
  },
  {
    id: "GM-STORAGE",
    domain: "storage",
    name: "Storage",
    purpose: "SQLite volume and artifact storage health",
    healthStatus: "healthy",
    metricsCollected: ["databaseIntegrity"],
    alertThresholds: "Integrity failed → critical",
    probeSource: "DatabaseGuardian",
    owner: "Infrastructure",
    dependencies: ["Railway volume"],
    knownDegradations: ["SQLite single-writer"],
    futureEvolution: "Disk usage metrics",
  },
  {
    id: "GM-NETWORK",
    domain: "network",
    name: "Network Latency",
    purpose: "API and external service latency",
    healthStatus: "healthy",
    metricsCollected: ["apiLatencyMs", "networkLatencyMs"],
    alertThresholds: "API >1000ms → degraded",
    probeSource: "Health probe latency",
    owner: "Infrastructure Commander",
    dependencies: ["Railway", "Vercel", "Upstash"],
    knownDegradations: [],
    futureEvolution: "Synthetic external probes",
  },
  {
    id: "GM-API",
    domain: "api",
    name: "Brain API",
    purpose: "HTTP API responsiveness and error rate",
    healthStatus: "healthy",
    metricsCollected: ["apiHealthy", "apiLatencyMs"],
    alertThresholds: "Unresponsive → critical",
    probeSource: "/health/live · brain-runtime bridge",
    owner: "Brain API",
    dependencies: ["Fastify"],
    knownDegradations: ["/brain/dispatch long path"],
    futureEvolution: "Per-route latency histogram",
  },
  {
    id: "GM-BUSINESS",
    domain: "business_engines",
    name: "Business Engines (REAL)",
    purpose: "Deferred module health when enabled",
    healthStatus: "maintenance",
    metricsCollected: ["extensionRoutesEnabled"],
    alertThresholds: "Off by default — informational",
    probeSource: "Production Mode registry",
    owner: "Programme REAL",
    dependencies: ["EMPIRE_ENABLE_EXTENSION_ROUTES"],
    knownDegradations: ["Not mounted in production by default"],
    futureEvolution: "Per-module health probes",
  },
  {
    id: "GM-COMMERCE",
    domain: "commerce",
    name: "Commerce Intelligence",
    purpose: "Live commerce integration health",
    healthStatus: "healthy",
    metricsCollected: ["liveCommerceMode"],
    alertThresholds: "Sandbox in production → informational",
    probeSource: "LIVE_COMMERCE_INTEGRATION_MODE",
    owner: "Commerce · PILLOW-CI-001",
    dependencies: ["Credentials"],
    knownDegradations: ["Fail-closed without credentials"],
    futureEvolution: "Marketplace probe metrics",
  },
  {
    id: "GM-PROD",
    domain: "production_services",
    name: "Production Services",
    purpose: "V1 split stack operational health",
    healthStatus: "healthy",
    metricsCollected: ["operationalReadyFlag", "deploymentHealth"],
    alertThresholds: "EMPIRE_V1_OPERATIONAL_READY false → limited",
    probeSource: "Production Mode · version-1-activation",
    owner: "Production Mode · P5-02",
    dependencies: ["Railway", "Vercel"],
    knownDegradations: ["Pillow limited until operational ready"],
    futureEvolution: "Multi-region health aggregation",
  },
];

export function getComponentsByHealth(
  status: import("./types.js").HealthClassification,
): MonitoredComponentRecord[] {
  return MONITORED_COMPONENT_REGISTRY.filter((c) => c.healthStatus === status);
}

export function getMonitoredComponent(id: string): MonitoredComponentRecord | undefined {
  return MONITORED_COMPONENT_REGISTRY.find((c) => c.id === id);
}
