import type { SupplierCatalogRecord } from "./types.js";

/** Extended mock supplier catalog — includes verified and suspicious suppliers for fake detection tests. */
export const SIE_MOCK_CATALOG: SupplierCatalogRecord[] = [
  {
    id: "sup-cj-001",
    name: "CJDropshipping",
    region: "CN",
    connectorId: "cj-dropshipping",
    productCount: 420,
    avgUnitCostCents: 850,
    avgShipDays: 12,
    reliabilityScore: 82,
    status: "active",
    qualityIndex: 78,
    defectRatePct: 3.2,
    verified: true,
    yearsActive: 6,
    benchmarkUnitCostCents: 900,
  },
  {
    id: "sup-spocket-001",
    name: "Spocket US/EU",
    region: "US",
    connectorId: "spocket",
    productCount: 180,
    avgUnitCostCents: 1200,
    avgShipDays: 5,
    reliabilityScore: 91,
    status: "active",
    qualityIndex: 88,
    defectRatePct: 2.1,
    verified: true,
    yearsActive: 5,
    benchmarkUnitCostCents: 1250,
  },
  {
    id: "sup-zendrop-001",
    name: "Zendrop Premium",
    region: "US",
    connectorId: "zendrop",
    productCount: 95,
    avgUnitCostCents: 1450,
    avgShipDays: 6,
    reliabilityScore: 88,
    status: "active",
    qualityIndex: 85,
    defectRatePct: 2.8,
    verified: true,
    yearsActive: 4,
    benchmarkUnitCostCents: 1500,
  },
  {
    id: "sup-ali-001",
    name: "AliExpress Direct",
    region: "CN",
    connectorId: "aliexpress",
    productCount: 1200,
    avgUnitCostCents: 620,
    avgShipDays: 18,
    reliabilityScore: 71,
    status: "active",
    qualityIndex: 65,
    defectRatePct: 6.5,
    verified: true,
    yearsActive: 8,
    benchmarkUnitCostCents: 700,
  },
  {
    id: "sup-fake-001",
    name: "Guaranteed Wholesale Direct 99",
    region: "CN",
    connectorId: "unknown-marketplace",
    productCount: 12,
    avgUnitCostCents: 180,
    avgShipDays: 25,
    reliabilityScore: 42,
    status: "active",
    qualityIndex: 28,
    defectRatePct: 18,
    verified: false,
    yearsActive: 0,
    suspiciousNamePattern: true,
    benchmarkUnitCostCents: 850,
  },
  {
    id: "sup-fraud-002",
    name: "EliteDrop VIP Factory Outlet",
    region: "XX",
    connectorId: "",
    productCount: 3,
    avgUnitCostCents: 95,
    avgShipDays: 30,
    reliabilityScore: 35,
    status: "active",
    qualityIndex: 22,
    defectRatePct: 22,
    verified: false,
    yearsActive: 0,
    suspiciousNamePattern: true,
    benchmarkUnitCostCents: 900,
  },
];

export function listMockCatalog(): SupplierCatalogRecord[] {
  return [...SIE_MOCK_CATALOG];
}

export function getMockSupplier(supplierId: string): SupplierCatalogRecord | undefined {
  return SIE_MOCK_CATALOG.find((s) => s.id === supplierId);
}
