import type { MarketProfile } from "./types.js";

export const MARKET_CATALOG: MarketProfile[] = [
  {
    id: "MKT-US",
    name: "United States",
    country: "US",
    language: "en",
    currency: "USD",
    marketSizeUsd: 5_800_000_000_000,
    growthPercent: 3.2,
    saturation: "high",
    demandScore: 90,
    shippingFeasible: true,
  },
  {
    id: "MKT-UK",
    name: "United Kingdom",
    country: "GB",
    language: "en",
    currency: "GBP",
    marketSizeUsd: 680_000_000_000,
    growthPercent: 2.1,
    saturation: "medium",
    demandScore: 82,
    shippingFeasible: true,
  },
  {
    id: "MKT-EU",
    name: "European Union (DE focus)",
    country: "DE",
    language: "de",
    currency: "EUR",
    marketSizeUsd: 4_200_000_000_000,
    growthPercent: 1.8,
    saturation: "medium",
    demandScore: 78,
    shippingFeasible: true,
  },
  {
    id: "MKT-SG",
    name: "Singapore / SEA hub",
    country: "SG",
    language: "en",
    currency: "SGD",
    marketSizeUsd: 420_000_000_000,
    growthPercent: 4.5,
    saturation: "low",
    demandScore: 75,
    shippingFeasible: true,
  },
];
