import type { ProductOpportunity } from "./types.js";

/** Canonical product discovery catalog — aligned with EmpireAI commerce intelligence stack. */
export const PRODUCT_CATALOG: ProductOpportunity[] = [
  {
    id: "PROD-001",
    name: "Portable Neck Massager",
    category: "Health & Wellness",
    supplierId: "SUP-CJ-001",
    marketIds: ["MKT-US", "MKT-UK"],
    costUsd: 18,
    suggestedPriceUsd: 49.99,
    profitMarginPercent: 58,
    competitionLevel: "medium",
    demandScore: 82,
    seasonality: "Year-round peak Q4 gifting",
    growthTrend: "rising",
    advertisingPotential: 78,
    customerInterest: 85,
  },
  {
    id: "PROD-002",
    name: "LED Desk Lamp with USB-C",
    category: "Home Office",
    supplierId: "SUP-CJ-002",
    marketIds: ["MKT-US", "MKT-SG"],
    costUsd: 22,
    suggestedPriceUsd: 54.99,
    profitMarginPercent: 52,
    competitionLevel: "high",
    demandScore: 74,
    seasonality: "Stable; back-to-school bump",
    growthTrend: "stable",
    advertisingPotential: 65,
    customerInterest: 70,
  },
  {
    id: "PROD-003",
    name: "Eco Bamboo Cutlery Set",
    category: "Sustainable Home",
    supplierId: "SUP-CJ-003",
    marketIds: ["MKT-UK", "MKT-EU"],
    costUsd: 8,
    suggestedPriceUsd: 24.99,
    profitMarginPercent: 62,
    competitionLevel: "low",
    demandScore: 76,
    seasonality: "Summer picnic season",
    growthTrend: "rising",
    advertisingPotential: 72,
    customerInterest: 80,
  },
  {
    id: "PROD-004",
    name: "Pet Grooming Glove",
    category: "Pet Supplies",
    supplierId: "SUP-CJ-001",
    marketIds: ["MKT-US"],
    costUsd: 5,
    suggestedPriceUsd: 19.99,
    profitMarginPercent: 68,
    competitionLevel: "medium",
    demandScore: 88,
    seasonality: "Year-round",
    growthTrend: "rising",
    advertisingPotential: 85,
    customerInterest: 90,
  },
  {
    id: "PROD-005",
    name: "Magnetic Phone Car Mount",
    category: "Auto Accessories",
    supplierId: "SUP-CJ-004",
    marketIds: ["MKT-US", "MKT-UK"],
    costUsd: 6,
    suggestedPriceUsd: 22.99,
    profitMarginPercent: 65,
    competitionLevel: "high",
    demandScore: 68,
    seasonality: "Holiday travel peak",
    growthTrend: "declining",
    advertisingPotential: 55,
    customerInterest: 62,
  },
  {
    id: "PROD-006",
    name: "Silicone Kitchen Utensil Set",
    category: "Kitchen",
    supplierId: "SUP-CJ-002",
    marketIds: ["MKT-US", "MKT-EU"],
    costUsd: 14,
    suggestedPriceUsd: 39.99,
    profitMarginPercent: 56,
    competitionLevel: "medium",
    demandScore: 79,
    seasonality: "Q4 gifting + wedding season",
    growthTrend: "stable",
    advertisingPotential: 70,
    customerInterest: 77,
  },
  {
    id: "PROD-007",
    name: "Resistance Bands Set (5-pack)",
    category: "Fitness",
    supplierId: "SUP-CJ-005",
    marketIds: ["MKT-US", "MKT-UK", "MKT-SG"],
    costUsd: 9,
    suggestedPriceUsd: 29.99,
    profitMarginPercent: 64,
    competitionLevel: "low",
    demandScore: 86,
    seasonality: "Jan fitness resolution peak",
    growthTrend: "rising",
    advertisingPotential: 88,
    customerInterest: 84,
  },
  {
    id: "PROD-008",
    name: "Wireless Earbuds Case Cover",
    category: "Electronics Accessories",
    supplierId: "SUP-CJ-004",
    marketIds: ["MKT-SG"],
    costUsd: 3,
    suggestedPriceUsd: 12.99,
    profitMarginPercent: 70,
    competitionLevel: "high",
    demandScore: 60,
    seasonality: "Device launch cycles",
    growthTrend: "stable",
    advertisingPotential: 50,
    customerInterest: 55,
  },
];
