import type { SupplierProfile } from "./types.js";

export const SUPPLIER_CATALOG: SupplierProfile[] = [
  {
    id: "SUP-CJ-001",
    name: "CJ Dropshipping — Wellness Tier",
    country: "CN",
    reliabilityScore: 88,
    shippingDaysAvg: 12,
    costIndex: 72,
    qualityScore: 85,
    returnRatePercent: 4.2,
    communicationScore: 82,
    capacityScore: 90,
    stabilityScore: 86,
  },
  {
    id: "SUP-CJ-002",
    name: "CJ Dropshipping — Home Tier",
    country: "CN",
    reliabilityScore: 84,
    shippingDaysAvg: 14,
    costIndex: 68,
    qualityScore: 80,
    returnRatePercent: 5.1,
    communicationScore: 78,
    capacityScore: 85,
    stabilityScore: 82,
  },
  {
    id: "SUP-CJ-003",
    name: "CJ Dropshipping — Eco Tier",
    country: "CN",
    reliabilityScore: 91,
    shippingDaysAvg: 11,
    costIndex: 75,
    qualityScore: 88,
    returnRatePercent: 3.5,
    communicationScore: 85,
    capacityScore: 78,
    stabilityScore: 89,
  },
  {
    id: "SUP-CJ-004",
    name: "CJ Dropshipping — Electronics Tier",
    country: "CN",
    reliabilityScore: 79,
    shippingDaysAvg: 16,
    costIndex: 65,
    qualityScore: 74,
    returnRatePercent: 6.8,
    communicationScore: 75,
    capacityScore: 88,
    stabilityScore: 76,
  },
  {
    id: "SUP-CJ-005",
    name: "CJ Dropshipping — Fitness Tier",
    country: "CN",
    reliabilityScore: 92,
    shippingDaysAvg: 10,
    costIndex: 78,
    qualityScore: 90,
    returnRatePercent: 2.9,
    communicationScore: 88,
    capacityScore: 82,
    stabilityScore: 91,
  },
];
