export * from "./types.js";
export * from "./pie-engine.js";
export * from "./pie-samples.js";
export * from "./supplier-types.js";
export * from "./supplier-intelligence.js";
export * from "./product-scout/index.js";

export {
  evaluateProduct,
  productIntelligenceEvaluationEngine,
  ProductIntelligenceEvaluationEngine,
  PIE_MOCK_EVALUATIONS,
  buildMockEvaluationInput,
  listMockEvaluationCatalog,
  productIntelligenceService,
  productIntelligenceCatalogRepository,
  registerProductIntelligenceRoutes,
} from "./product-intelligence-engine/index.js";
export * from "./product-intelligence-engine/types.js";
export * from "./product-intelligence-engine/recommendation-engine.js";
export * from "./connectors/index.js";

export {
  compareSuppliers,
  discoverSuppliers,
  evaluateSupplier,
  supplierIntelligenceEvaluationEngine,
  SupplierIntelligenceEvaluationEngine,
  registerSupplierIntelligenceModule,
  supplierIntelligenceModule,
  SupplierIntelligenceModule,
} from "./supplier-intelligence-engine/index.js";
export * from "./supplier-intelligence-engine/types.js";
export * from "./supplier-intelligence-engine/mock-catalog.js";
export * from "./supplier-intelligence-engine/recommendation-engine.js";
export * from "./supplier-intelligence-engine/supplier-guard.js";

export {
  scoreProductSignal,
  rankProducts,
  selectTopOpportunities,
  formatEmpireScoreExplanation,
  computeEmpireScore,
  resolveWeightConfig,
  scoreAllDimensions,
  computeScoringConfidence,
  aggregateReasons,
  DEFAULT_SCORING_WEIGHTS,
  SCORING_DIMENSIONS,
  scoreDemand,
  scoreCompetition,
  scoreMargin,
  scoreSupplierTrust,
  scoreShipping,
  scoreBrandability,
  scoreAdvertisementPotential,
  scoreTrendMomentum,
  scoreRisk,
} from "./product-scoring-engine/index.js";
export type {
  ProductScore,
  ProductSignalReference,
  DimensionScoreResult,
  ScoringDimension,
  ScoringWeightConfig,
  ScoringWeightOverrides,
  ScoreProductSignalOptions,
  ProductRankingOptions,
  TopOpportunityThresholds,
} from "./product-scoring-engine/index.js";

export {
  BUYER_INTELLIGENCE_MODULE_ID,
  BUYER_INTELLIGENCE_MODULE_VERSION,
  BUYER_INTELLIGENCE_CAPABILITIES,
  BUYER_INTELLIGENCE_REQUIRED_INPUTS,
  BUYER_INTELLIGENCE_PRODUCED_OUTPUTS,
  BUYER_INTELLIGENCE_CATALOG_ENTRY,
  BUYER_INTELLIGENCE_TABLES,
  BUYER_INTELLIGENCE_INDEXES,
  BUYER_INTELLIGENCE_FOREIGN_KEYS,
  BUYER_INTELLIGENCE_OBSERVATION_DOMAINS,
  BUYER_INTELLIGENCE_SCHEMA_SQL_SKETCH,
  buyerPersonaSchema,
  buyerIntentSchema,
  needCategorySchema,
  purchaseTriggerSchema,
  audienceSegmentSchema,
  segmentMembershipSchema,
  validateBuyerPersona,
  validateBuyerIntent,
  validateNeedCategory,
  validatePurchaseTrigger,
  validateAudienceSegment,
  validateSegmentMembership,
  normalizeBuyerPersonaSlug,
  isPurchaseReadyIntent,
  urgencyWeight,
  needCategoryMatchesDomain,
  isPurchaseTriggerActiveAt,
  isActiveAudienceSegment,
  BUYER_INTENT_STAGES,
  BUYER_INTENT_URGENCY_LEVELS,
  NEED_CATEGORY_PRIORITIES,
  PURCHASE_TRIGGER_TYPES,
  AUDIENCE_SEGMENT_STATUSES,
  InMemoryBuyerPersonaRepository,
  createInMemoryBuyerPersonaRepository,
  buyerSignalSchema,
  validateBuyerSignal,
  buyerSignalFromProductSignal,
  BUYER_PERSONA_SPENDING_POWERS,
  BUYER_PERSONA_URGENCY_LEVELS,
  buyerPersonaProfileSchema,
  validateBuyerPersonaProfile,
  buyerIntentContractSchema,
  validateBuyerIntentContract,
  BuyerPersonaMapper,
  defaultBuyerPersonaMapper,
} from "./buyer-intelligence/index.js";
export type {
  BuyerIntelligenceModuleId,
  BuyerIntelligenceCapability,
  BuyerIntelligenceInputSpec,
  BuyerIntelligenceOutputSpec,
  BuyerIntelligenceTask,
  BuyerIntelligenceValidationResult,
  BuyerIntelligenceHealthStatus,
  BuyerIntelligenceHealthReport,
  BuyerIntelligenceObservation,
  BuyerIntelligenceRecommendation,
  BuyerIntelligenceExecutionResult,
  BuyerIntelligenceModuleContract,
  BuyerIntelligenceCatalogEntry,
  BuyerPersona,
  BuyerPersonaId,
  BuyerDemographics,
  BuyerPsychographics,
  BuyerPersonaCreateInput,
  BuyerPersonaUpdateInput,
  BuyerIntent,
  BuyerIntentId,
  BuyerIntentStage,
  BuyerIntentUrgency,
  BuyerIntentSignal,
  BuyerIntentCreateInput,
  BuyerIntentUpdateInput,
  NeedCategory,
  NeedCategoryId,
  NeedCategoryPriority,
  NeedCategoryCreateInput,
  NeedCategoryUpdateInput,
  PurchaseTrigger,
  PurchaseTriggerId,
  PurchaseTriggerType,
  PurchaseTriggerCondition,
  PurchaseTriggerCreateInput,
  PurchaseTriggerUpdateInput,
  AudienceSegment,
  AudienceSegmentId,
  AudienceSegmentStatus,
  SegmentRule,
  SegmentRuleOperator,
  AudienceSizeEstimate,
  SegmentMembership,
  SegmentMembershipId,
  AudienceSegmentCreateInput,
  AudienceSegmentUpdateInput,
  BuyerIntelligenceListQuery,
  BuyerPersonaQuery,
  BuyerIntentQuery,
  NeedCategoryQuery,
  PurchaseTriggerQuery,
  AudienceSegmentQuery,
  SegmentMembershipQuery,
  BuyerPersonaRepository,
  BuyerIntentRepository,
  NeedCategoryRepository,
  PurchaseTriggerRepository,
  AudienceSegmentRepository,
  SegmentMembershipRepository,
  BuyerIntelligenceRepository,
  BuyerIntelligenceTableName,
  BiBuyerPersonaRow,
  BiBuyerIntentRow,
  BiNeedCategoryRow,
  BiPurchaseTriggerRow,
  BiAudienceSegmentRow,
  BiSegmentMembershipRow,
  BuyerIntelligenceIndexSpec,
  BuyerIntelligenceForeignKey,
  BuyerSignal,
  BuyerPersonaProfile,
  BuyerPersonaSpendingPower,
  BuyerPersonaUrgencyLevel,
  BuyerIntentContract,
} from "./buyer-intelligence/index.js";

export {
  KNOWLEDGE_GRAPH_MODULE_ID,
  KNOWLEDGE_GRAPH_MODULE_VERSION,
  KNOWLEDGE_GRAPH_CAPABILITIES,
  KNOWLEDGE_GRAPH_MODULE_CONTRACT,
  productEntitySchema,
  productAliasSchema,
  productRelationshipSchema,
  productCategorySchema,
  validateProductEntity,
  validateProductAlias,
  validateProductRelationship,
  validateProductCategory,
  normalizeProductAlias,
  tokenizeProductAlias,
  aliasTokensToSlug,
  normalizeProductCategorySlug,
  PRODUCT_RELATIONSHIP_TYPES,
  InMemoryKnowledgeGraphRepository,
  createInMemoryKnowledgeGraphRepository,
  KnowledgeGraphMapper,
  defaultKnowledgeGraphMapper,
  KnowledgeGraphModule,
  createKnowledgeGraphModule,
  knowledgeGraphModule,
} from "./product-knowledge-graph/index.js";
export type {
  ProductEntity,
  ProductEntityId,
  ProductEntityCreateInput,
  ProductEntityUpdateInput,
  ProductSupplierRef,
  ProductAlias,
  ProductAliasId,
  ProductAliasCreateInput,
  ProductRelationship,
  ProductRelationshipId,
  ProductRelationshipType,
  ProductRelationshipCreateInput,
  ProductCategory,
  ProductCategoryId,
  ProductCategoryCreateInput,
  ProductCategoryUpdateInput,
  KnowledgeGraphListQuery,
  ProductEntityQuery,
  ProductAliasQuery,
  ProductRelationshipQuery,
  ProductCategoryQuery,
  ProductEntityRepository,
  ProductAliasRepository,
  ProductRelationshipRepository,
  ProductCategoryRepository,
  KnowledgeGraphRepository,
  CanonicalProductResolution,
  RegisterProductAliasesInput,
  KnowledgeGraphModuleId,
  KnowledgeGraphCapability,
  KnowledgeGraphModuleContract,
  ResolveProductByAliasResult,
  RegisterProductResult,
} from "./product-knowledge-graph/index.js";
