import fs from "node:fs";

import { GOVERNANCE_AUTHORITY_MATRIX } from "../../../foundation/empire-governance-doctrine/catalog/gvd-catalog.js";
import type { EsisInspectionReport } from "../models/esis-inspection.js";
import { REVIEW_PACKAGE_PATH } from "./repo-scanner.js";
import { serializeVisualMapsMarkdown } from "./visual-map-generator.js";

function section(title: string, body: string): string {
  return `## ${title}\n\n${body.trim()}\n`;
}

function table(headers: string[], rows: string[][]): string {
  const lines = [
    `| ${headers.join(" | ")} |`,
    `| ${headers.map(() => "---").join(" | ")} |`,
    ...rows.map((row) => `| ${row.join(" | ")} |`),
  ];
  return lines.join("\n");
}

export function writeReviewPackage(report: EsisInspectionReport, outputPath = REVIEW_PACKAGE_PATH): string {
  const sections: string[] = [
    "# EMPIREAI REVIEW PACKAGE",
    "",
    "> Generated by Empire Self-Inspection System (ESIS) — S001",
    `> Report ID: \`${report.reportId}\``,
    `> Deterministic Hash: \`${report.deterministicHash}\``,
    `> Generated: ${report.generatedAt}`,
    `> Workspace: ${report.workspaceId} | Company: ${report.companyId}`,
    "",
    section("Executive Summary", report.executiveSummary),
    section("Frontend Summary", report.frontend.summary),
    section(
      "Current Screens",
      table(
        ["Route", "Page", "Purpose", "Nav"],
        report.frontend.pages.map((p) => [p.route, p.pageComponent, p.purpose, p.navigationSection]),
      ),
    ),
    section(
      "Frontend Page Details",
      report.frontend.pages
        .map(
          (p) =>
            `### ${p.title} (\`${p.route}\`)\n- Purpose: ${p.purpose}\n- APIs: ${p.boundApis.join(", ") || "none"}\n- Missing: ${p.missingImplementation.join("; ") || "none"}`,
        )
        .join("\n\n"),
    ),
    section("Backend Summary", report.backend.summary),
    section(
      "Current Modules",
      table(
        ["Module", "Category", "Health", "Routes", "Tools"],
        report.backend.modules.map((m) => [
          m.moduleId,
          m.category,
          m.health,
          String(m.routes.length),
          String(m.brainTools.length),
        ]),
      ),
    ),
    section(
      "Current Routes",
      report.backend.modules
        .flatMap((m) => m.routes.map((r) => `- \`${r}\` (${m.moduleId})`))
        .sort()
        .join("\n") || "No routes discovered",
    ),
    section(
      "Current APIs",
      `Total REST routes scanned: **${report.backend.routeCount}**`,
    ),
    section(
      "Current Database",
      `Total tables: **${report.backend.tableCount}**`,
    ),
    section("Commerce Summary", report.commerce.summary),
    section(
      "Commerce Pipeline",
      table(
        ["Stage", "Module", "Status", "Canon Phase", "Blockers"],
        report.commerce.stages.map((s) => [
          s.stage,
          s.module,
          s.status,
          s.canonPhase ?? "—",
          s.blockers.join("; ") || "—",
        ]),
      ),
    ),
    section("Connector Summary", report.connectors.summary),
    section(
      "Connectors",
      table(
        ["Provider", "Connection", "Health", "Execution", "Blocked", "Reason"],
        report.connectors.entries.map((c) => [
          c.displayName,
          c.connection,
          c.health,
          c.executionStatus,
          String(c.blocked),
          c.blockedReason ?? "—",
        ]),
      ),
    ),
    section(
      "Current Validation",
      `- Typecheck: **${report.production.typecheck.status}**${report.production.typecheck.detail ? ` — ${report.production.typecheck.detail}` : ""}
- Tests: **${report.production.tests.status}**${report.production.tests.detail ? ` — ${report.production.tests.detail}` : ""}
- Build: **${report.production.build.status}**${report.production.build.detail ? ` — ${report.production.build.detail}` : ""}
- Coverage: **${report.production.coverage.status}**`,
    ),
    section(
      "Current Risks",
      report.risks.map((r) => `- ${r}`).join("\n") || "No risks identified",
    ),
    section(
      "Current Technical Debt",
      report.production.technicalDebt.map((d) => `- ${d}`).join("\n") || "None catalogued",
    ),
    section(
      "Current Commercial Readiness",
      `- Commercial blockers: ${report.production.commercialBlockers.length}
${report.production.commercialBlockers.map((b) => `- ${b}`).join("\n")}
- First Dollar blockers:
${report.production.firstDollarBlockers.map((b) => `- ${b}`).join("\n")}
- Canon: ${report.commerce.canonCompliance}
- State machine: ${report.commerce.stateMachineCompliance}`,
    ),
    section(
      "Current Production Readiness",
      `- Production blockers: ${report.production.productionBlockers.length}
${report.production.productionBlockers.map((b) => `- ${b}`).join("\n") || "- None"}
- Security blockers:
${report.production.securityBlockers.map((b) => `- ${b}`).join("\n") || "- None"}`,
    ),
    section(
      "Core Constitution (CTD-001 → CTD-040)",
      `${report.constitution.summary}

| Metric | Value |
|--------|-------|
| Articles | ${report.constitution.articleCount} |
| Coverage | ${report.constitution.coveragePercent}% |
| Compliant checks | ${report.constitution.compliantCount} |
| Partial | ${report.constitution.partialCount} |
| Violations | ${report.constitution.violationCount} |

${report.constitution.violations.length > 0 ? report.constitution.violations.map((v) => `- ${v}`).join("\n") : "No constitution violations detected."}`,
    ),
    section(
      "Governance Doctrine (GVD-001 → GVD-030)",
      `${report.governance.summary}

| Metric | Value |
|--------|-------|
| Doctrines | ${report.governance.doctrineCount} |
| Authority matrix modules | ${report.governance.authorityMatrixCount} |
| Coverage | ${report.governance.coveragePercent}% |
| Compliant checks | ${report.governance.compliantCount} |
| Partial | ${report.governance.partialCount} |
| Violations | ${report.governance.violationCount} |
| Review passed | ${report.governance.reviewPassed ? "YES" : "NO — GVD-029"} |

${report.governance.violations.length > 0 ? report.governance.violations.map((v) => `- ${v}`).join("\n") : "No governance violations detected."}

### Authority Matrix

${table(
  ["Module", "Role", "Execute", "Decide", "Recommend", "Escalation", "GVD"],
  GOVERNANCE_AUTHORITY_MATRIX.map((e) => [
    e.moduleId,
    e.role,
    e.mayExecute ? "yes" : "no",
    e.mayDecide ? "yes" : "no",
    e.mayRecommend ? "yes" : "no",
    e.escalationTarget ?? "—",
    e.gvdArticles.join(", "),
  ]),
)}`,
    ),
    section(
      "Architecture Constraints (ACD-001 → ACD-030)",
      `${report.architecture.summary}

| Metric | Value |
|--------|-------|
| Constraints | ${report.architecture.constraintCount} |
| Dependency edges reviewed | ${report.architecture.dependencyReviewCount} |
| Coverage | ${report.architecture.coveragePercent}% |
| Compliant checks | ${report.architecture.compliantCount} |
| Partial | ${report.architecture.partialCount} |
| Violations | ${report.architecture.violationCount} |
| Review passed | ${report.architecture.reviewPassed ? "YES" : "NO — ACD-030"} |

${report.architecture.violations.length > 0 ? report.architecture.violations.map((v) => `- ${v}`).join("\n") : "No architecture constraint violations detected."}

### Dependency Review

${table(
  ["From", "To", "Relationship", "Status", "ACD", "Note"],
  report.architecture.dependencyReview.map((d) => [
    d.fromModule,
    d.toModule,
    d.relationship,
    d.status,
    d.acdArticle,
    d.note,
  ]),
)}`,
    ),
    section(
      "UX & Identity Doctrine (UID-001 → UID-020)",
      `${report.uxIdentity.summary}

| Metric | Value |
|--------|-------|
| Doctrines | ${report.uxIdentity.doctrineCount} |
| Identity coverage | ${report.uxIdentity.identityCoverageCount} |
| UX coverage | ${report.uxIdentity.uxCoverageCount} |
| Navigation routes reviewed | ${report.uxIdentity.navigationReviewCount} |
| Coverage | ${report.uxIdentity.coveragePercent}% |
| Compliant checks | ${report.uxIdentity.compliantCount} |
| Partial | ${report.uxIdentity.partialCount} |
| Violations | ${report.uxIdentity.violationCount} |
| Review passed | ${report.uxIdentity.reviewPassed ? "YES" : "NO"} |

${report.uxIdentity.violations.length > 0 ? report.uxIdentity.violations.map((v) => `- ${v}`).join("\n") : "No UX & identity violations detected."}

### Navigation Review

${table(
  ["Path", "Label", "Role", "Purpose", "Status", "UID"],
  report.uxIdentity.navigationReview.map((n) => [
    n.path,
    n.label,
    n.role,
    n.purpose,
    n.status,
    n.uidArticles.join(", "),
  ]),
)}`,
    ),
    section(
      "Commercial Business Doctrine (CBD-001 → CBD-020)",
      `${report.commercial.summary}

| Metric | Value |
|--------|-------|
| Doctrines | ${report.commercial.doctrineCount} |
| Business rules covered | ${report.commercial.businessRuleCount} |
| Integrity rules reviewed | ${report.commercial.integrityReviewCount} |
| Coverage | ${report.commercial.coveragePercent}% |
| Compliant checks | ${report.commercial.compliantCount} |
| Partial | ${report.commercial.partialCount} |
| Violations | ${report.commercial.violationCount} |
| Review passed | ${report.commercial.reviewPassed ? "YES" : "NO"} |

${report.commercial.violations.length > 0 ? report.commercial.violations.map((v) => `- ${v}`).join("\n") : "No commercial doctrine violations detected."}

### Business Rule Coverage

${report.commercial.businessRuleCoverage.map((r) => `- ${r}`).join("\n")}

### Commercial Integrity Review

${table(
  ["Domain", "Rule", "Status", "CBD", "Evidence"],
  report.commercial.commercialIntegrityReview.map((i) => [
    i.domain,
    i.rule,
    i.status,
    i.cbdArticle,
    i.evidence,
  ]),
)}`,
    ),
    serializeVisualMapsMarkdown(report.visualMaps),
    "",
    section("Recommended Next Priority", report.recommendedNextPriority),
    "",
    "---",
    "*End of Empire Review Package*",
  ];

  const content = sections.join("\n");
  fs.writeFileSync(outputPath, content, "utf8");
  return outputPath;
}
