/** PILLOW-CAPCRT-001 — Capital Factory Certification (Q9-11). Final Q9 acceptance gate. */
export const CAPITAL_FACTORY_CERTIFICATION_SYSTEM_PATH =
  "docs/governance/EMPIREAI_CAPITAL_FACTORY_CERTIFICATION_SYSTEM.md" as const;
export const CAPITAL_FACTORY_CERTIFICATION_ID = "capital-factory-certification" as const;
export const CAPCRT_METADATA_VERSION = "CAPCRT-001-v1" as const;
export const CAPITAL_FACTORY_CERTIFICATION_REPORT_VERSION = "CAPCRT-RPT-v1" as const;
export const CAPCRT_MISSION_ID = "Q9-11" as const;
export const CAPITAL_FACTORY_VERSION = "Q9-CAPFC-v1" as const;

export const CAPITAL_FACTORY_CERTIFICATION_IDENTITY = {
  workerId: "wkr-capital-factory-certification-01",
  workerName: "Capital Factory Certification",
  workerType: "certifier",
  department: "capital",
  factory: "capital-factory",
  role: "role-certifier-capital-factory-certification",
  reportingLine: ["wkr-capital-factory-certification-01", "pillow"] as string[],
  skillProfile: [
    "skill-repository-evidence-collection",
    "skill-runtime-worker-probing",
    "skill-integration-verification",
    "skill-production-readiness-assessment",
    "skill-governance-compliance-verification",
    "skill-financial-traceability-verification",
    "skill-end-to-end-workflow-verification",
    "skill-certification-decision-gating",
    "skill-capital-certification-reporting",
  ],
  approvedTools: ["repository_evidence_scanner", "structured_reporting"],
  authorityLevel: "autonomous_worker_decision",
} as const;

export const ENGINE_STATUSES = [
  "idle",
  "connecting",
  "active",
  "collecting_evidence",
  "probing_runtime",
  "verifying_integrations",
  "assessing_readiness",
  "certifying",
  "reporting",
  "validating",
  "failed",
] as const;

export const OPERATIONAL_STATES = ["disconnected", "connected", "active", "failed"] as const;
export const VALIDATION_STATUSES = ["pending", "passed", "partial", "failed"] as const;
export const ENGINE_HEALTH_STATUSES = ["healthy", "degraded", "failed", "standby"] as const;

/** Per-worker certification statuses — derived strictly from observed evidence. */
export const WORKER_CERTIFICATION_STATUSES = [
  "Certified",
  "Partially Certified",
  "Failed Certification",
  "Blocked",
  "Deferred",
] as const;

export const CERTIFICATION_DECISIONS = [
  "Certified",
  "Conditionally_Certified",
  "Not_Certified",
  "Failed",
  "Deferred",
] as const;

export const AUDIT_STATUSES = [
  "draft",
  "evidence_collected",
  "integrations_verified",
  "readiness_assessed",
  "certified",
  "conditionally_certified",
  "not_certified",
  "failed",
  "deferred",
  "submitted",
  "rejected",
  "unknown",
] as const;

/**
 * Q9-01..Q9-10 — the complete Capital Factory worker pipeline this mission
 * certifies. Every field is used as repository/runtime evidence; nothing here
 * is invented per-run.
 */
export const Q9_MISSION_CATALOG = [
  {
    missionId: "Q9-01",
    missionName: "capital-factory-core",
    subsystemId: "capital-factory-core",
    modulePath: "pillow/src/capital-factory-core/",
    enginePath: "pillow/src/capital-factory-core/engine.ts",
    auditPath: "docs/audits/pillow/q9-01-capital-factory-core/",
    configPath: "config/capital-factory-core.config.json",
    governancePath: "docs/governance/EMPIREAI_CAPITAL_FACTORY_CORE_SYSTEM.md",
    bridgePath: "backend/src/orchestration/pillow-host/capital-factory-core-bridge.ts",
    testPath: "pillow/src/validation/tests/capital-factory-core.test.ts",
    dependencyKey: "capitalFactoryCore",
    engineVersion: "PILLOW-CAPFC-001",
    systemDocPath: "docs/governance/EMPIREAI_CAPITAL_FACTORY_CORE_SYSTEM.md",
    expectedDeliverable:
      "Capital Factory Core registration, capital project lifecycle, and Q9 worker coordination",
  },
  {
    missionId: "Q9-02",
    missionName: "accounting-worker",
    subsystemId: "accounting-worker",
    modulePath: "pillow/src/accounting-worker/",
    enginePath: "pillow/src/accounting-worker/engine.ts",
    auditPath: "docs/audits/pillow/q9-02-accounting-worker/",
    configPath: "config/accounting-worker.config.json",
    governancePath: "docs/governance/EMPIREAI_ACCOUNTING_WORKER_SYSTEM.md",
    bridgePath: "backend/src/orchestration/pillow-host/accounting-worker-bridge.ts",
    testPath: "pillow/src/validation/tests/accounting-worker.test.ts",
    dependencyKey: "accountingWorker",
    engineVersion: "PILLOW-ACCW-001",
    systemDocPath: "docs/governance/EMPIREAI_ACCOUNTING_WORKER_SYSTEM.md",
    expectedDeliverable: "Ledger posting, chart of accounts, and Accounting Reports",
  },
  {
    missionId: "Q9-03",
    missionName: "cashflow-worker",
    subsystemId: "cashflow-worker",
    modulePath: "pillow/src/cashflow-worker/",
    enginePath: "pillow/src/cashflow-worker/engine.ts",
    auditPath: "docs/audits/pillow/q9-03-cashflow-worker/",
    configPath: "config/cashflow-worker.config.json",
    governancePath: "docs/governance/EMPIREAI_CASHFLOW_WORKER_SYSTEM.md",
    bridgePath: "backend/src/orchestration/pillow-host/cashflow-worker-bridge.ts",
    testPath: "pillow/src/validation/tests/cashflow-worker.test.ts",
    dependencyKey: "cashflowWorker",
    engineVersion: "PILLOW-CFW-001",
    systemDocPath: "docs/governance/EMPIREAI_CASHFLOW_WORKER_SYSTEM.md",
    expectedDeliverable: "Cashflow views, runway analysis, and Cashflow Reports",
  },
  {
    missionId: "Q9-04",
    missionName: "budget-planning-worker",
    subsystemId: "budget-planning-worker",
    modulePath: "pillow/src/budget-planning-worker/",
    enginePath: "pillow/src/budget-planning-worker/engine.ts",
    auditPath: "docs/audits/pillow/q9-04-budget-planning-worker/",
    configPath: "config/budget-planning-worker.config.json",
    governancePath: "docs/governance/EMPIREAI_BUDGET_PLANNING_WORKER_SYSTEM.md",
    bridgePath: "backend/src/orchestration/pillow-host/budget-planning-worker-bridge.ts",
    testPath: "pillow/src/validation/tests/budget-planning-worker.test.ts",
    dependencyKey: "budgetPlanningWorker",
    engineVersion: "PILLOW-BPW-001",
    systemDocPath: "docs/governance/EMPIREAI_BUDGET_PLANNING_WORKER_SYSTEM.md",
    expectedDeliverable: "Budget plans, variance analysis, and Budget Planning Reports",
  },
  {
    missionId: "Q9-05",
    missionName: "profitability-worker",
    subsystemId: "profitability-worker",
    modulePath: "pillow/src/profitability-worker/",
    enginePath: "pillow/src/profitability-worker/engine.ts",
    auditPath: "docs/audits/pillow/q9-05-profitability-worker/",
    configPath: "config/profitability-worker.config.json",
    governancePath: "docs/governance/EMPIREAI_PROFITABILITY_WORKER_SYSTEM.md",
    bridgePath: "backend/src/orchestration/pillow-host/profitability-worker-bridge.ts",
    testPath: "pillow/src/validation/tests/profitability-worker.test.ts",
    dependencyKey: "profitabilityWorker",
    engineVersion: "PILLOW-PRFW-001",
    systemDocPath: "docs/governance/EMPIREAI_PROFITABILITY_WORKER_SYSTEM.md",
    expectedDeliverable: "Profitability analysis and Profitability Reports",
  },
  {
    missionId: "Q9-06",
    missionName: "forecasting-worker",
    subsystemId: "forecasting-worker",
    modulePath: "pillow/src/forecasting-worker/",
    enginePath: "pillow/src/forecasting-worker/engine.ts",
    auditPath: "docs/audits/pillow/q9-06-forecasting-worker/",
    configPath: "config/forecasting-worker.config.json",
    governancePath: "docs/governance/EMPIREAI_FORECASTING_WORKER_SYSTEM.md",
    bridgePath: "backend/src/orchestration/pillow-host/forecasting-worker-bridge.ts",
    testPath: "pillow/src/validation/tests/forecasting-worker.test.ts",
    dependencyKey: "forecastingWorker",
    engineVersion: "PILLOW-FRCW-001",
    systemDocPath: "docs/governance/EMPIREAI_FORECASTING_WORKER_SYSTEM.md",
    expectedDeliverable: "Revenue/cash forecasts and Forecasting Reports",
  },
  {
    missionId: "Q9-07",
    missionName: "tax-support-worker",
    subsystemId: "tax-support-worker",
    modulePath: "pillow/src/tax-support-worker/",
    enginePath: "pillow/src/tax-support-worker/engine.ts",
    auditPath: "docs/audits/pillow/q9-07-tax-support-worker/",
    configPath: "config/tax-support-worker.config.json",
    governancePath: "docs/governance/EMPIREAI_TAX_SUPPORT_WORKER_SYSTEM.md",
    bridgePath: "backend/src/orchestration/pillow-host/tax-support-worker-bridge.ts",
    testPath: "pillow/src/validation/tests/tax-support-worker.test.ts",
    dependencyKey: "taxSupportWorker",
    engineVersion: "PILLOW-TSW-001",
    systemDocPath: "docs/governance/EMPIREAI_TAX_SUPPORT_WORKER_SYSTEM.md",
    expectedDeliverable: "Tax support schedules, filing reminders, and Tax Support Reports",
  },
  {
    missionId: "Q9-08",
    missionName: "investment-planning-worker",
    subsystemId: "investment-planning-worker",
    modulePath: "pillow/src/investment-planning-worker/",
    enginePath: "pillow/src/investment-planning-worker/engine.ts",
    auditPath: "docs/audits/pillow/q9-08-investment-planning-worker/",
    configPath: "config/investment-planning-worker.config.json",
    governancePath: "docs/governance/EMPIREAI_INVESTMENT_PLANNING_WORKER_SYSTEM.md",
    bridgePath: "backend/src/orchestration/pillow-host/investment-planning-worker-bridge.ts",
    testPath: "pillow/src/validation/tests/investment-planning-worker.test.ts",
    dependencyKey: "investmentPlanningWorker",
    engineVersion: "PILLOW-IPW-001",
    systemDocPath: "docs/governance/EMPIREAI_INVESTMENT_PLANNING_WORKER_SYSTEM.md",
    expectedDeliverable: "Investment opportunity evaluation and Investment Planning Reports",
  },
  {
    missionId: "Q9-09",
    missionName: "financial-reporting-worker",
    subsystemId: "financial-reporting-worker",
    modulePath: "pillow/src/financial-reporting-worker/",
    enginePath: "pillow/src/financial-reporting-worker/engine.ts",
    auditPath: "docs/audits/pillow/q9-09-financial-reporting-worker/",
    configPath: "config/financial-reporting-worker.config.json",
    governancePath: "docs/governance/EMPIREAI_FINANCIAL_REPORTING_WORKER_SYSTEM.md",
    bridgePath: "backend/src/orchestration/pillow-host/financial-reporting-worker-bridge.ts",
    testPath: "pillow/src/validation/tests/financial-reporting-worker.test.ts",
    dependencyKey: "financialReportingWorker",
    engineVersion: "PILLOW-FRW-001",
    systemDocPath: "docs/governance/EMPIREAI_FINANCIAL_REPORTING_WORKER_SYSTEM.md",
    expectedDeliverable: "Consolidated financial reports and executive dashboards",
  },
  {
    missionId: "Q9-10",
    missionName: "capital-risk-worker",
    subsystemId: "capital-risk-worker",
    modulePath: "pillow/src/capital-risk-worker/",
    enginePath: "pillow/src/capital-risk-worker/engine.ts",
    auditPath: "docs/audits/pillow/q9-10-capital-risk-worker/",
    configPath: "config/capital-risk-worker.config.json",
    governancePath: "docs/governance/EMPIREAI_CAPITAL_RISK_WORKER_SYSTEM.md",
    bridgePath: "backend/src/orchestration/pillow-host/capital-risk-worker-bridge.ts",
    testPath: "pillow/src/validation/tests/capital-risk-worker.test.ts",
    dependencyKey: "capitalRiskWorker",
    engineVersion: "PILLOW-CAPRW-001",
    systemDocPath: "docs/governance/EMPIREAI_CAPITAL_RISK_WORKER_SYSTEM.md",
    expectedDeliverable: "Capital risk detection and Q911 consumable contract for Q9-11",
  },
] as const;

export const CRITICAL_MISSION_IDS = Q9_MISSION_CATALOG.map((m) => m.missionId);

export const INTEGRATION_TARGETS = [
  ...Q9_MISSION_CATALOG.map((m) => m.subsystemId),
  "worker_registry",
  "worker_lifecycle",
  "executive_reporting_runtime",
  "worker_recovery_system",
  "audit_runtime",
] as const;

export const CAPCRT_CAPABILITIES = [
  "collect_repository_evidence",
  "probe_runtime_workers",
  "classify_worker_certification_status",
  "verify_integrations",
  "verify_end_to_end_workflow",
  "verify_production_readiness",
  "verify_governance_compliance",
  "verify_financial_traceability",
  "verify_executive_reporting",
  "produce_certification_findings",
  "produce_capital_certification_reports",
  "submit_reports_through_executive_reporting_runtime",
  "preserve_complete_traceability",
  "preserve_certification_audit_history",
  "never_fabricate_successful_tests",
  "never_assume_implementation",
  "never_implement_missing_workers",
  "never_modify_financial_records",
  "never_automatically_fix_failures",
  "never_override_governance",
  "never_override_approved_architecture",
  "never_override_pillow",
  "never_override_grand_king",
  "never_bypass_grand_king_approval",
  "never_implement_q10_or_later",
  "integrate_capital_factory_core",
  "integrate_accounting_worker",
  "integrate_cashflow_worker",
  "integrate_budget_planning_worker",
  "integrate_profitability_worker",
  "integrate_forecasting_worker",
  "integrate_tax_support_worker",
  "integrate_investment_planning_worker",
  "integrate_financial_reporting_worker",
  "integrate_capital_risk_worker",
  "integrate_worker_registry",
  "integrate_worker_lifecycle",
  "integrate_executive_reporting_runtime",
  "integrate_worker_recovery_system",
  "integrate_audit_runtime",
  "capital_factory_certification_validation",
  "health_monitoring",
  "recovery_management",
  "final_q9_gate",
] as const;
