/** T2-01 — Built-in default UX governance rules. */

import { RULE_METADATA_VERSION } from "./paths.js";
import type { UxRule } from "./types.js";

const now = "2026-06-21T00:00:00.000Z";

export const DEFAULT_UX_RULES: UxRule[] = [
  {
    ruleId: "ux-gov-001",
    ruleName: "UI state must have screen identifier",
    category: "governance",
    description: "Every UI state model must include a valid screen identifier.",
    severity: "error",
    status: "enabled",
    version: "1.0.0",
    targetType: "ui_state",
    evaluationLogic: { evaluator: "ui_state_has_screen_id", parameters: {} },
    ruleConfiguration: {},
    createdTimestamp: now,
    updatedTimestamp: now,
    metadataVersion: RULE_METADATA_VERSION,
  },
  {
    ruleId: "ux-gov-002",
    ruleName: "UI state must contain visible regions",
    category: "hierarchy",
    description: "UI states should expose at least one visible region for structure validation.",
    severity: "warning",
    status: "enabled",
    version: "1.0.0",
    targetType: "ui_state",
    evaluationLogic: {
      evaluator: "ui_state_has_regions",
      parameters: { minRegions: 1 },
    },
    ruleConfiguration: {},
    createdTimestamp: now,
    updatedTimestamp: now,
    metadataVersion: RULE_METADATA_VERSION,
  },
  {
    ruleId: "ux-gov-003",
    ruleName: "Minimum viewport dimensions",
    category: "responsiveness",
    description: "Viewport dimensions must meet minimum governance thresholds.",
    severity: "warning",
    status: "enabled",
    version: "1.0.0",
    targetType: "ui_state",
    evaluationLogic: {
      evaluator: "ui_state_min_viewport",
      parameters: { minWidth: 320, minHeight: 240 },
    },
    ruleConfiguration: {},
    createdTimestamp: now,
    updatedTimestamp: now,
    metadataVersion: RULE_METADATA_VERSION,
  },
  {
    ruleId: "ux-gov-004",
    ruleName: "Components must be detected",
    category: "clarity",
    description: "Component recognition must identify at least one UI component.",
    severity: "error",
    status: "enabled",
    version: "1.0.0",
    targetType: "component",
    evaluationLogic: {
      evaluator: "component_min_count",
      parameters: { minCount: 1 },
    },
    ruleConfiguration: {},
    createdTimestamp: now,
    updatedTimestamp: now,
    metadataVersion: RULE_METADATA_VERSION,
  },
  {
    ruleId: "ux-gov-005",
    ruleName: "Interactive components should have labels",
    category: "readability",
    description: "Button and link components should expose accessible labels.",
    severity: "warning",
    status: "enabled",
    version: "1.0.0",
    targetType: "component",
    evaluationLogic: {
      evaluator: "component_has_labels",
      parameters: { requiredTypes: ["button", "link"] },
    },
    ruleConfiguration: {},
    createdTimestamp: now,
    updatedTimestamp: now,
    metadataVersion: RULE_METADATA_VERSION,
  },
  {
    ruleId: "ux-gov-006",
    ruleName: "Component detection confidence threshold",
    category: "safety",
    description: "Detected components must meet minimum confidence for governance.",
    severity: "warning",
    status: "enabled",
    version: "1.0.0",
    targetType: "component",
    evaluationLogic: {
      evaluator: "component_min_confidence",
      parameters: { minConfidence: 0.3 },
    },
    ruleConfiguration: {},
    createdTimestamp: now,
    updatedTimestamp: now,
    metadataVersion: RULE_METADATA_VERSION,
  },
  {
    ruleId: "ux-gov-007",
    ruleName: "Layout must define structural regions",
    category: "hierarchy",
    description: "Layout models must contain structural regions for governance.",
    severity: "error",
    status: "enabled",
    version: "1.0.0",
    targetType: "layout",
    evaluationLogic: {
      evaluator: "layout_min_regions",
      parameters: { minRegions: 1 },
    },
    ruleConfiguration: {},
    createdTimestamp: now,
    updatedTimestamp: now,
    metadataVersion: RULE_METADATA_VERSION,
  },
  {
    ruleId: "ux-gov-008",
    ruleName: "Layout must have region hierarchy",
    category: "alignment",
    description: "Layout models should define a region hierarchy for spatial governance.",
    severity: "warning",
    status: "enabled",
    version: "1.0.0",
    targetType: "layout",
    evaluationLogic: { evaluator: "layout_has_structure", parameters: {} },
    ruleConfiguration: {},
    createdTimestamp: now,
    updatedTimestamp: now,
    metadataVersion: RULE_METADATA_VERSION,
  },
  {
    ruleId: "ux-gov-009",
    ruleName: "Navigation graph must contain nodes",
    category: "navigation",
    description: "Navigation structures must expose at least one node.",
    severity: "error",
    status: "enabled",
    version: "1.0.0",
    targetType: "navigation",
    evaluationLogic: {
      evaluator: "navigation_min_nodes",
      parameters: { minNodes: 1 },
    },
    ruleConfiguration: {},
    createdTimestamp: now,
    updatedTimestamp: now,
    metadataVersion: RULE_METADATA_VERSION,
  },
  {
    ruleId: "ux-gov-010",
    ruleName: "Navigation must define entry points",
    category: "navigation",
    description: "Navigation graphs should declare entry points for workflow governance.",
    severity: "warning",
    status: "enabled",
    version: "1.0.0",
    targetType: "navigation",
    evaluationLogic: { evaluator: "navigation_has_entry", parameters: {} },
    ruleConfiguration: {},
    createdTimestamp: now,
    updatedTimestamp: now,
    metadataVersion: RULE_METADATA_VERSION,
  },
];
