import type {InstitutionalMemory} from './store.js';
import type {Receipt} from '../runtime/commerce-runtime/governed/store.js';
import type {CommerceState} from '../runtime/commerce-runtime/governed/engine.js';
export const safetyPaths={supplierPurchases:['/api/orders','/api/owner/commerce/execute'],listingPublication:['/api/listings/publish'],priceInventory:['/api/inventory']} as const;
export function controlledSafetyState(policy:any){return {version:policy?.version??0,limits:policy?.limits??{currency:'SGD',perOrder:null,daily:null,aggregate:null},desiredPauses:policy?.breakers??{supplierPurchases:false,listingPublication:false,priceInventory:false},effectivePauses:{supplierPurchases:true,listingPublication:true,priceInventory:true},spendBasis:'CONSERVATIVE_COMMITMENTS_CARRIED_FORWARD_UNTIL_VERIFIED_SETTLEMENT',globalLock:'NOT_BORN_COMMERCE_LOCKED',scope:safetyPaths,receiptId:policy?.id??null,receiptHref:policy?'/cockpit/advisor?record='+encodeURIComponent('memory:'+policy.id):null,receiptHash:policy?.receiptHash??null,verifiedReadback:!!policy,reason:'All supported write paths remain denied by locked-runtime enforcement. Clearing an owner pause cannot activate commerce.'};}
const definitions=[['duplicate-orders','Duplicate-order guard'],['order-reconciliation','Order reconciliation'],['stock','Stock guard'],['profitability','Profitability guard'],['capital','Capital guard'],['delivery','Delivery guard'],['compliance','Compliance guard'],['supplier-reliability','Supplier reliability'],['durability','Durability guard'],['safe-retry','Safe retry'],['financial-reconciliation','Financial reconciliation'],['monitoring','Operational monitoring'],['circuit-breakers','Circuit breakers'],['owner-authority','Owner authority'],['disaster-recovery','Disaster recovery']] as const;
type Inputs={missions?:Receipt[];commerceAvailable:boolean;finance?:any;assurance?:any;providers?:any[];tasks?:any[];sourceErrors?:string[]};
/** A bounded projection of canonical evidence, not a new safety engine or certification. */
export function readSafety(memory:InstitutionalMemory,workspace:string,sources:Inputs){
 const policy=memory.safetyPolicy(workspace),controls=controlledSafetyState(policy),missions=sources.missions??[];
 const isolated=missions.filter(r=>r.classification==='SYNTHETIC').map(r=>{const s=r.state as unknown as CommerceState;return {missionId:r.missionId,receiptId:r.id,digest:r.digest,at:r.at,classification:r.classification,productId:s.candidate.productId,sku:s.candidate.offer.sku,source:s.candidate.offer.provenance,qualification:s.qualification,approval:s.approval??null,orders:Object.entries(s.orders).map(([id,o])=>({id,canonicalOrderId:o.order.orderId,supplierReceiptId:o.providerId??null,intentId:o.intentId??null,outcome:o.outcome,unknownOutcome:['UNKNOWN','RECONCILIATION_REQUIRED'].includes(o.outcome),accepted:o.accepted,shipped:o.shipped,delivered:o.delivered,quantity:o.order.items.reduce((n,i)=>n+i.quantity,0),shipments:o.shipments,tracking:o.tracking,remedies:o.remedies,exposure:{amount:o.order.estimatedCost,currency:o.order.currency,classification:'SYNTHETIC_ESTIMATE_EXCLUDED_FROM_ACTUALS'}})),decisions:s.decisions,href:'/cockpit/commerce/governed?mission='+encodeURIComponent(r.missionId)};});
 const orders=isolated.flatMap(m=>m.orders.map(o=>({...o,missionId:m.missionId,href:m.href}))),unknown=orders.filter(o=>o.unknownOutcome),failures=orders.filter(o=>['REJECTED','PARTIAL','RECONCILIATION_REQUIRED','UNKNOWN'].includes(o.outcome));
 const finance=sources.finance,assurance=sources.assurance;const incidentList=assurance?.controlPlane?.incidents??[];
 const guards=definitions.map(([id,title])=>({id,title,status:'UNKNOWN' as 'VERIFIED'|'AT_RISK'|'TRIPPED'|'UNKNOWN',lastEvidenceAt:null as string|null,affectedOrders:[] as string[],affectedProducts:[] as string[],financialExposure:{amount:null as number|null,currency:'SGD',classification:'UNKNOWN'},detectionReason:'No verified actual operational evidence establishes this guard. Pre-Birth synthetic evidence is listed separately.',actionTaken:'Live effects blocked by NOT_BORN and commerce LOCKED',recoveryEvidence:[] as unknown[],kingMustAct:true,drilldown:'/cockpit/assurance?guard='+id,evidence:[] as unknown[],classification:'ACTUAL_CAPABILITY_UNVERIFIED',limitations:['Work 8 independent failure/load certification not performed by this projection']}));
 const guard=(id:string)=>guards.find(g=>g.id===id)!;
 guard('duplicate-orders').detectionReason='Canonical order IDs, immutable intent IDs and idempotent receipts are available in isolated evidence; no actual Amazon/CJ order reconciliation has been certified.';
 guard('order-reconciliation').detectionReason='No complete actual Amazon, CJ and EmpireAI order sets with matching reconciliation timestamp are available.';
 guard('stock').detectionReason='Stock authority requires current SKU, variant, warehouse and destination evidence; unknown or stale inventory cannot establish buyability.';
 guard('profitability').detectionReason='Saved scenario gross/contribution/floor calculations are estimates, not actual margins; no override grants live authority.';
 guard('capital').detectionReason=policy?'Owner ceilings persisted; actual available supplier capital and complete committed exposure remain unverified.':'Owner per-order, daily and aggregate supplier limits are not configured.';
 guard('capital').lastEvidenceAt=policy?.recordedAt??null;guard('capital').evidence=policy?[{id:policy.id,hash:policy.receiptHash,limits:policy.limits}]:[];
 guard('delivery').detectionReason='No actual carrier-confirmed promised/actual delivery comparison or certified transit confidence is available; package-level isolated evidence remains separate.';
 guard('compliance').detectionReason='Publication requires current category eligibility, claim evidence, media rights and seller-of-record review. Prepared content is not marketplace acceptance.';
 guard('supplier-reliability').detectionReason='No verified actual fulfilment history establishes supplier lateness, stock stability, freight drift or recovery from quarantine.';
 guard('durability').detectionReason=sources.commerceAvailable?'Selected canonical receipt chains verified during read; this bounded read does not certify full-store replay or disaster recovery.':'Canonical commerce journal unavailable; integrity cannot be certified.';
 guard('durability').evidence=isolated.map(m=>({id:m.receiptId,digest:m.digest,classification:m.classification}));
 guard('safe-retry').detectionReason='Unknown external submission outcome requires reconciliation, never blind retry. Isolated unknown outcomes are shown separately; no real purchase retry is permitted.';
 guard('financial-reconciliation').detectionReason=finance?'Work5 ledger is readable; complete actual marketplace/CJ settlement and bank reconciliation remains unverified.':'Financial source unavailable; payout discrepancy/exposure remains unknown.';
 guard('financial-reconciliation').evidence=finance?[{journalDigest:finance.entryDigest,alerts:finance.alerts??[],position:finance.position??null,kpis:finance.kpis??null}]:[];
 guard('monitoring').detectionReason='Worker queues and provider errors below are stored observations, not proof of complete autonomous operational monitoring.';guard('monitoring').evidence=[{tasks:sources.tasks??[],providers:sources.providers??[],incidents:incidentList}];
 guard('circuit-breakers').status=policy&&Object.values(policy.breakers).some(Boolean)?'TRIPPED':'UNKNOWN';guard('circuit-breakers').lastEvidenceAt=policy?.recordedAt??null;guard('circuit-breakers').kingMustAct=!policy;guard('circuit-breakers').detectionReason=policy?'Owner pause policy read back; live effects remain globally locked. Resume cannot bypass Birth/commerce authority.':'No owner circuit-breaker policy recorded; global commerce lock continues to deny writes.';guard('circuit-breakers').evidence=[controls];
 guard('owner-authority').detectionReason='Founder authentication and version fences govern policy changes. Existing Four Eyes content-bound approval, expiry and revocation are required independently; saved approval is not external completion.';guard('owner-authority').evidence=policy?[{id:policy.id,version:policy.version,origin:policy.origin,hash:policy.receiptHash}]:[];
 guard('disaster-recovery').detectionReason='No source-backed backup freshness, recovery objective or completed restore-test evidence was found in these stores. Owner review required; Work 8 certification outstanding.';
 return {at:new Date().toISOString(),birth:'NOT_BORN',commerce:'LOCKED',controls,guards,isolatedEvidence:{classification:'SYNTHETIC_EXCLUDED_FROM_ACTUALS',missions:isolated,unknownOutcomes:unknown,failedOrPartialOrders:failures},sourceErrors:sources.sourceErrors??[],coverage:{missionLimit:200,mayBeTruncated:missions.length>=200,independentOperationalCertification:false},inferenceCalls:0,externalEffects:0};
}
