'use client';
import {useState} from 'react';
import {CostCategoryManager} from './CostCategoryManager';
import {Audit,Pager} from './BusinessViews';
import {records,object,text,sgd,sourceMoney,plainStatus,providerAmounts,periodBounds,sumKnown,type BusinessRow} from '@/lib/owner/business-view';
import {costCategories,infrastructureSummary,isArchived,archivedNote,providerCommand} from '@/lib/owner/cost-centre';
import s from './business.module.css';

export function InfrastructureCosts({data,now,bounds,period,refresh}:{data:BusinessRow;now:Date;bounds:{from:string;to:string};period:string;refresh:()=>void}) {
 const [provider,setProvider]=useState(''),[search,setSearch]=useState(''),[category,setCategory]=useState(''),[sort,setSort]=useState('name'),[page,setPage]=useState(1),[archived,setArchived]=useState(false);
 const [edit,setEdit]=useState<BusinessRow|null>(null),[notice,setNotice]=useState(''),[pending,setPending]=useState<ReturnType<typeof providerCommand>|null>(null),[busy,setBusy]=useState(false);
 const directory=object(data.costDirectory),savedCategories=records(directory.categories),savedMappings=records(directory.mappings);
 const allProviders:BusinessRow[]=records(data.providers).map(p=>{const mapping=savedMappings.find(m=>m.provider===p.id),mapped=savedCategories.find(c=>c.id===mapping?.categoryId);return {...p,directoryCategory:mapped?text(mapped.name)+(mapped.archived?' · Archived':''):p.category};}),overview=infrastructureSummary(data.costs,now,provider),all=overview.all;
 const providers=allProviders.filter(p=>(!provider||p.id===provider)&&(!category||p.directoryCategory===category)&&(archived||!isArchived(p))&&text(p.name).toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==='mtd'?(providerAmounts(all,text(b.id),periodBounds('MTD',now)).amount??-Infinity)-(providerAmounts(all,text(a.id),periodBounds('MTD',now)).amount??-Infinity):text(a.name).localeCompare(text(b.name)));
 const currentPage=Math.min(page,Math.max(1,Math.ceil(providers.length/10)));
 const categories=[...new Set([...costCategories,...allProviders.map(p=>text(p.directoryCategory,'')).filter(Boolean)])].sort();
 const extraPeriod=!['MTD','YTD'].includes(period);
 async function save(command:ReturnType<typeof providerCommand>){setBusy(true);setPending(command);setNotice('');try{const r=await fetch('/api/owner/finance',{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify(command)});const receipt=await r.json();if(!r.ok)throw Error(receipt.error||'Mapping not confirmed');setNotice('Directory mapping recorded. Billing, subscriptions and spending authority are unchanged.');setPending(null);setEdit(null);refresh();}catch(e){setNotice((e instanceof Error?e.message:'Result unconfirmed')+'. Retry uses the same record identity.');}finally{setBusy(false);}}
 return <>
 <div className={s.metrics}>{[['Confirmed MTD',overview.mtd],['Confirmed YTD',overview.ytd],['Outstanding invoices',overview.payable],['Accrued unbilled',overview.accrued],['Estimates',overview.estimated],['Commitments',overview.committed]].map(([name,v])=><article key={String(name)}><h2>{name}</h2><strong>{sgd(v)}</strong><small>{v===null?'Amount unknown / no complete recorded total':'Recorded infrastructure only · SGD'}</small></article>)}</div>
 <p className={s.note}>Confirmed totals combine reviewed invoices and settlements once. Missing bills and unallocated shared-team usage are not zero. MTD/YTD are calendar totals; obligations and commitments cover all retained periods.</p>
 <details><summary>AI usage estimates and reserved limits</summary><p>Internal metering estimate: {sourceMoney(object(data.accounting).recordedEstimateMicroUsd,'USD')} · {text(object(data.accounting).recordCount)} accounting records · {text(object(data.accounting).estimateUnknownCount)} estimates unknown.</p><p>Held spending reservations: {sourceMoney(object(data.accounting).heldMicroUsd,'USD')}. Reservations are limits held for requests, not settled charges or supplier commitments.</p><p>Provider invoice actual: {sourceMoney(object(data.accounting).invoiceActualMicroUsd,'USD')}. These internal estimates are not invoices, payments or additions to confirmed totals.</p><Audit label="AI accounting provenance" value={data.accounting}/></details><details><summary>Upcoming bills, annual outlook and budget</summary><div className={s.metrics}>{[7,30,90].map(days=>{const upcoming=overview.future.filter(c=>Date.parse(c.nextDate)<=now.getTime()+days*86400000);return <article key={days}><h2>Next {days} days</h2><strong>{upcoming.length?upcoming.length:'—'}</strong><small>{upcoming.length?'Recorded due/renewal dates; overlapping windows':'No verified dates recorded'}</small></article>;})}</div>
 <p>Annual run rate: not established. Complete recurring charges and billing intervals must be verified before projecting a yearly obligation.</p>
 {overview.future.length>0&&<ul>{overview.future.slice(0,20).map(c=><li key={text(c.id)}>{text(object(c.data).provider)} · {c.nextDate} · {plainStatus(object(c.data).stage)} · {sourceMoney(c.originalMicro,object(c.data).currency)}<small>Renewal price is not assumed from a previous charge.</small></li>)}</ul>}
 {records(data.budgets).filter(b=>!provider||b.provider===provider).length?records(data.budgets).filter(b=>!provider||b.provider===provider).map(b=>{const actual=providerAmounts(all,text(b.provider),periodBounds('MTD',now)).amount;return <p key={text(b.provider)}>{text(b.provider)}: monthly budget {sgd(b.monthlySgdMicro)} · confirmed MTD {sgd(actual)} · remaining {sgd(typeof b.monthlySgdMicro==='number'&&actual!==null?b.monthlySgdMicro-actual:null)}. Unbilled amounts remain separate.</p>}):<p>No provider budget is recorded for this selection.</p>}
 <Audit label="Budget and tariff evidence" value={{budgets:data.budgets,pricing:data.pricing}}/></details>
 <div className={s.toolbar}><label>Provider<select aria-label="Provider" value={provider} onChange={e=>{setProvider(e.target.value);setPage(1);}}><option value="">All providers</option>{allProviders.map(p=><option key={text(p.id)} value={text(p.id)}>{text(p.name)}</option>)}</select></label><label>Search providers<input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></label><label>Cost category<select value={category} onChange={e=>{setCategory(e.target.value);setPage(1);}}><option value="">All categories</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Sort providers<select value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Provider name</option><option value="mtd">Confirmed MTD, highest first</option></select></label><label><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/>Show archived mappings</label></div>
 <div className={s.tableScroll} tabIndex={0} role="region" aria-label="Infrastructure expenses"><table><thead><tr>{['Provider / service','MTD · SGD','YTD · SGD',...(extraPeriod?[period+' · SGD']:[]),'Billing status','Bills / ownership / action'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{providers.slice((currentPage-1)*10,currentPage*10).map(p=>{const id=text(p.id),v=providerAmounts(all,id,bounds),monthly=providerAmounts(all,id,periodBounds('MTD',now)),yearly=providerAmounts(all,id,periodBounds('YTD',now));return <tr key={id}><th scope="row">{text(p.name)}<small>{text(p.directoryCategory)}</small><small>{[...new Set(v.entries.map(c=>text(object(c.data).service)))].join(', ')||'No bills recorded for selected period'}</small>{isArchived(p)&&<small>Archived directory mapping; charges retained</small>}</th><td>{sgd(monthly.amount)}</td><td>{sgd(yearly.amount)}</td>{extraPeriod&&<td>{sgd(v.amount)}</td>}<td>{v.stages}{v.entries.filter(c=>!['INVOICED','SETTLED'].includes(text(object(c.data).stage))).map(c=><small key={text(c.id)}>{plainStatus(object(c.data).stage)}: {sourceMoney(c.originalMicro??object(c.data).amountMicro,object(c.data).currency)}{object(object(c.data).attribution).project==='TEAM_SHARED_UNALLOCATED'?' · Shared team usage; EmpireAI share unknown':''}</small>)}<small>{p.commissioned==='NO'?'Not commissioned':p.commissioned==='UNKNOWN'?'Connection not confirmed':'Recorded connection; invoice coverage still required'}</small></td><td><details><summary>Bills and usage · {text(p.name)}</summary>{v.entries.length?v.entries.map(c=>{const d=object(c.data),a=object(d.attribution);return <section key={text(c.id)}><h3>{text(d.service)}</h3><p>{plainStatus(d.stage)} · {sourceMoney(c.originalMicro,d.currency)} · SGD {sgd(c.sgdMicro)}</p><p>Billing period: {text(d.periodStart)} to {text(d.periodEnd)}</p><p>Payment: {text(d.paymentDate,'Not recorded')} · Due: {text(d.dueDate,'Unknown')} · Renewal: {text(d.renewalDate,'Unknown')}</p><p>Service allocation: {text(a.project)} · {text(a.environment)}. Account owner: not established by allocation.</p><Audit value={c}/></section>}):<p>No bills recorded. This does not establish zero spend.</p>}<Audit value={p} label="Vendor mapping and billing access"/></details>{v.entries.some(c=>c.sgdMicro===null)&&<p role="alert">Currency conversion missing</p>}{v.entries.some(c=>c.stale||c.fxStale)&&<p role="alert">Billing evidence needs review</p>}<button onClick={()=>{setEdit({...p});setNotice('');}}>Edit mapping</button></td></tr>;})}</tbody></table></div><Pager page={currentPage} total={providers.length} setPage={setPage}/>
 <p><strong>Confirmed infrastructure charges · {period}: {sgd(sumKnown(all.filter(c=>['INVOICED','SETTLED'].includes(text(object(c.data).stage))&&object(c.data).periodStart!==undefined&&String(object(c.data).periodStart)<bounds.to&&String(object(c.data).periodEnd)>bounds.from)))}</strong></p>
 <CostCategoryManager data={data} refresh={refresh}/><details><summary>Potential cost categories and vendor mapping</summary><p>Categories below are a coverage checklist, not active bills. Add or change a category when mapping a vendor. Archiving a mapping never cancels a service or removes historical charges.</p><ul className={s.categoryList}>{categories.map(c=><li key={c}>{c}</li>)}</ul><p>Examples include ChatGPT, model APIs, Railway, Vercel, GitHub, Amazon SP-API, CJ, Shopify, Shopee, Keepa, TinyFish, Canva and other evidenced services. No subscription or charge is inferred.</p><button onClick={()=>{setEdit({id:'',name:'',category:costCategories[0],commissioned:'UNKNOWN',mandatory:false,billingAccess:'UNAVAILABLE',note:''});setNotice('');}}>Add vendor / category mapping</button></details>
 {edit&&<section aria-label="Edit cost directory" className={s.empty}><h2>Owner cost directory</h2><p>Metadata only. This does not purchase, approve or cancel a service.</p><form onSubmit={e=>{e.preventDefault();void save(providerCommand(edit,{},'cost-directory-'+crypto.randomUUID()));}}><div className={s.toolbar}><label>Vendor ID<input required maxLength={160} pattern="[A-Za-z0-9_.:-]+" disabled={allProviders.some(p=>p.id===edit.id)} value={text(edit.id,'')} onChange={e=>setEdit({...edit,id:e.target.value})}/></label><label>Vendor name<input required maxLength={100} value={text(edit.name,'')} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><label>Category<input required list="cost-categories" maxLength={100} value={text(edit.category,'')} onChange={e=>setEdit({...edit,category:e.target.value})}/><datalist id="cost-categories">{categories.map(c=><option key={c} value={c}/>)}</datalist></label><label>Directory note<input maxLength={450} value={text(edit.note,'').replace(archivedNote,'')} onChange={e=>setEdit({...edit,note:(isArchived(edit)?archivedNote:'')+e.target.value})}/></label><label><input type="checkbox" checked={isArchived(edit)} onChange={e=>setEdit({...edit,note:(e.target.checked?archivedNote:'')+text(edit.note,'').replace(archivedNote,'')})}/>Archive this directory mapping</label></div><button disabled={busy||pending!==null}>Save mapping</button><button type="button" disabled={busy} onClick={()=>setEdit(null)}>Cancel</button></form></section>}
 {notice&&<p role="status">{notice}</p>}{pending&&!busy&&<button onClick={()=>void save(pending)}>Retry same directory record</button>}
 <details><summary>Significant changes and cost-saving review</summary>{records(data.recommendations).filter(r=>/cost|renew|service|usage/i.test(text(r.topic)+' '+text(r.text))).map((r,i)=><p key={i}><strong>{text(r.topic)}</strong> · {text(r.text)}</p>)}<p>Compare equivalent coverage and complete billing periods before cancelling or buying services. Recorded suggestions do not authorise spending.</p></details>
 </>;
}
