'use client';
import {useState} from 'react';
import Link from 'next/link';
import {useBusinessRead,BusinessStatus,Audit,Pager} from './BusinessViews';
import {object,records,text,plainStatus,evidenceMatches} from '@/lib/owner/business-view';
import s from './business.module.css';
export function IntelligenceTrace({evidence,opportunities}:{evidence:Record<string,unknown>[];opportunities:Record<string,unknown>[]}) {
 const executive=useBusinessRead('/api/owner/advisor/executive');
 const [range,setRange]=useState('7'),[eye,setEye]=useState('ALL'),[page,setPage]=useState(1),[selected,setSelected]=useState('');
 const [now]=useState(()=>Date.now());
 const shown=evidence.filter(e=>{const at=Date.parse(text(e.observedAt));return (eye==='ALL'||e.eye===eye)&&(range==='all'||Number.isFinite(at)&&at<=now&&now-at<=Number(range)*86400000);});
 return <section className={s.page} aria-label="Intelligence to action"><div className={s.toolbar}><label>Discovery period<select value={range} onChange={e=>{setRange(e.target.value);setPage(1);}}>{[['1','Last 24 hours'],['7','7 days'],['30','30 days'],['90','Last 90 days'],['365','Last 365 days'],['all','All loaded findings']].map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label>Intelligence eye<select value={eye} onChange={e=>{setEye(e.target.value);setPage(1);}}>{['ALL','MARKET','SUPPLIER','INTERNET','EMPIRE'].map(v=><option key={v}>{v}</option>)}</select></label></div>
 <p>{shown.length} loaded findings in this view. A discovery becomes a recommendation only when a saved Pillow assessment links to it.</p><BusinessStatus {...executive}/>
 {!shown.length?<p className={s.empty}>No discoveries in this period. Older findings remain available in All loaded findings.</p>:<div className={s.tableScroll} tabIndex={0} role="region" aria-label="Research findings"><table><thead><tr><th>What was discovered</th><th>Why it matters</th><th>Pillow assessment</th><th>Next step</th></tr></thead><tbody>{shown.slice((page-1)*10,page*10).map(e=>{const linked=records(executive.data?.recommendations).filter(r=>evidenceMatches(e,r)),op=opportunities.filter(o=>Array.isArray(o.evidenceRefs)&&o.evidenceRefs.includes(e.id));const stale=typeof e.staleAfter!=='string'||!Number.isFinite(Date.parse(e.staleAfter))||Date.parse(e.staleAfter)<=now;return <tr key={text(e.id)} data-testid="intelligence-trace"><th scope="row">{text(object(e.subject).query??object(e.subject).id)}<small>{plainStatus(e.eye)} Eye · {text(e.provider)}</small>{e.authenticity==='SYNTHETIC'&&<small>Test example</small>}<small>{stale?'Evidence needs refreshing':'Within recorded freshness window'}</small></th><td>{op.length?op.map(o=>Array.isArray(o.missing)?o.missing.join(', '):plainStatus(o.status)).join('; '):'Commercial significance not assessed'}</td><td>{linked.length?linked.map(r=><p key={text(r.id)}>{text(r.title)}</p>):'No linked assessment in the loaded decision page'}</td><td><button aria-expanded={selected===e.id} onClick={()=>setSelected(selected===e.id?'':text(e.id))}>Inspect finding</button>{selected===e.id&&<div><Audit label="Discovery facts and original source" value={e}/>{linked.map(r=><section key={text(r.id)}><h3>What Pillow thinks</h3><p>{text(r.rationale)}</p><p>Owner decision: {text(object(r.ownerDecision).decision,'Not recorded')}</p><p>Execution: {text(r.executionStatus)}. Outcome: {text(object(r.outcome).status,'Not measured')}.</p><p>Receipt reference: {text(object(r.outcome).executionRef,'No execution receipt reference')}. Requires independent verification.</p><Audit label="Full assessment and outcome" value={r}/><Link href={'/cockpit/ceo#'+encodeURIComponent(text(r.id))}>Inspect this Pillow decision</Link><br/><Link href={text(r.evidenceHref,'/cockpit/advisor')}>Inspect source and receipt</Link></section>)}<Audit label="Linked candidate qualification" value={op}/></div>}</td></tr>;})}</tbody></table></div>}
 <Pager page={page} total={shown.length} setPage={setPage}/><p className={s.note}>Loaded records only; not a complete discovery or decision count. Source identity is retained. Missing matches do not prove that no historical assessment exists.</p>
 </section>;
}
