'use client';
import {useEffect,useState,type ReactNode} from 'react';
import Link from 'next/link';
import {ChartNoAxesCombined,Target,Package,ShoppingCart,Clock3,Sparkles,ShieldCheck,Crown,ArrowRight,Landmark,Lightbulb} from 'lucide-react';
import {useAssurance} from '@/lib/owner/useAssurance';
import s from './home.module.css';
type Row=Record<string,unknown>;
const obj=(x:unknown):Row=>x&&typeof x==='object'&&!Array.isArray(x)?x as Row:{};
const arr=(x:unknown):Row[]=>Array.isArray(x)?x.map(obj):[];
const text=(x:unknown,f='Not measured')=>typeof x==='string'||typeof x==='number'?String(x):f;
const money=(v:unknown)=>typeof v==='number'?new Intl.NumberFormat('en-SG',{style:'currency',currency:'SGD',maximumFractionDigits:2}).format(v/1e6):'Unknown';
function useRead(url:string){const [data,setData]=useState<Row|null>(null),[error,setError]=useState('');useEffect(()=>{const c=new AbortController();fetch(url,{cache:'no-store',signal:c.signal}).then(async r=>{if(!r.ok)throw Error(`Source unavailable (${r.status})`);return r.json();}).then(setData).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[url]);return {data,error};}
function Card({title,href,icon,children,className=''}:{title:string;href:string;icon:ReactNode;children:ReactNode;className?:string}){return <section className={`${s.card} ${className}`}><header><h2>{icon}{title}</h2><Link href={href} aria-label={`View ${title}`}>View all <ArrowRight size={12}/></Link></header>{children}</section>;}
export function PremiumHome(){
 const finance=useRead('/api/owner/finance'),portfolio=useRead('/api/owner/commerce/portfolio?pageSize=10&classification=REAL_READ_ONLY'),executive=useRead('/api/owner/advisor/executive');
 const {data:assurance,fresh}=useAssurance();const cp=assurance?.controlPlane;
 const kpi=obj(finance.data?.kpis),exec=obj(executive.data?.data??executive.data),recommendations=arr(exec.recommendations),timeline=arr(exec.timeline).slice(0,6);const [filter,setFilter]=useState('All');
 const visible=recommendations.filter(r=>filter==='All'||text(r.category??r.domain).toLowerCase().includes(filter.toLowerCase())).slice(0,5);
 return <div className={s.home}><div className={s.hero} role="img" aria-label="King, My Happiness, Mum — My Strength, and brown poodles Pillow — Love Forever and Pancake, building a happier tomorrow together"/><h1 className={s.srOnly}>EmpireAI Home</h1>
 <div className={s.dashboard}><div className={s.firstRow}><section className={s.glance}><h2>Empire at a Glance</h2><div className={s.metrics}>
 {[[Landmark,'Realised profit','Not certified','/cockpit/finance','Reviewed totals below'],[ChartNoAxesCombined,'Unsettled contribution','Unknown','/cockpit/finance','Requires settlement evidence'],[Target,'Annual KPI progress',text(obj(exec.annualCommitment).amount,'NOT SET'),'/cockpit/ceo','Owner-reviewed plan'],[Package,'Product evidence',portfolio.data?text(portfolio.data.total):'—','/cockpit/products','Real read-only records'],[ShoppingCart,'Live orders','Not established','/cockpit/orders','Commerce remains locked']].map(([Icon,label,value,href,note])=>{const I=Icon as typeof Target;return <Link href={String(href)} key={String(label)} className={s.metric}><I aria-hidden="true"/><div><strong>{String(value)}</strong><span>{String(label)}</span></div><small>{String(note)}</small></Link>;})}</div></section>
 <Card title="Pillow’s Message" href="/cockpit/ceo" icon={<Crown/>}><h3>Good day, King!</h3><p className={s.authority}>NOT_BORN · Commerce LOCKED</p><p>{fresh&&cp?`${cp.summary.ownerActionRequired} incidents need your decision. ${cp.summary.automaticallyRecovered} automatic recoveries verified.`:'Current operational attention is not yet verified.'}</p><Link className={`${s.briefLink} ${s.messageAction}`} href="/cockpit/ceo#recommendations">Review today’s evidence and decisions <ArrowRight size={15}/></Link></Card></div>
 <div className={s.middleRow}><Card title="Today’s Timeline" href="/cockpit/ceo#clock" icon={<Clock3/>}><p className={s.note}>Actual retained activity · inspect dates and classification</p>{timeline.length?<ol className={s.timeline}>{timeline.map((r,i)=><li key={text(r.id,String(i))}><time>{r.at?new Date(String(r.at)).toLocaleTimeString('en-SG',{timeZone:'Asia/Singapore',hour:'2-digit',minute:'2-digit'}):'Not recorded'} SGT</time><span>{text(r.summary??r.title??r.status,'Recorded decision')}<small>{text(r.classification,'Source evidence')}</small></span></li>)}</ol>:<div className={s.empty}><Clock3/><p>{executive.error||'No completed activity established in this view.'}</p><Link href="/cockpit/ceo#clock">Inspect the 24-hour schedule →</Link></div>}</Card>
 <Card title="Pillow’s Recommendations" href="/cockpit/ceo#recommendations" icon={<Sparkles/>}><div className={s.filters}>{['All','Opportunity','Risk','Information'].map(f=><button key={f} aria-pressed={f===filter} onClick={()=>setFilter(f)}>{f}</button>)}</div>{visible.length?<ul className={s.recs}>{visible.map((r,i)=><li key={text(r.id,String(i))}><Lightbulb/><Link href={`/cockpit/ceo#${encodeURIComponent(text(r.id,'recommendations'))}`}><strong>{text(r.title??r.summary,'Review retained recommendation')}</strong><small>{text(r.classification,'Unknown classification')+' · '+text(r.status??r.category,'Evidence review required')}</small></Link></li>)}</ul>:<div className={s.empty}><Sparkles/><p>{executive.error||'No source-backed recommendation in this category.'}</p><Link href="/cockpit/ceo#recommendations">Open the decision centre →</Link></div>}</Card>
 <Card title="Latest Highlights" href="/cockpit/assurance" icon={<ShieldCheck/>}><ul className={s.highlights}><li><ShieldCheck/><div><strong>{fresh?'Current monitoring evidence':'Monitoring freshness unverified'}</strong><small>{fresh&&cp?`${cp.summary.activeIncidents} active incidents`:'Open Assurance for the last known state'}</small></div></li><li><Package/><div><strong>{portfolio.data?`${text(portfolio.data.total)} product evidence records`:'Product source awaiting read'}</strong><small>Not a claim of buyable listings</small></div></li><li><Landmark/><div><strong>Financial coverage remains explicit</strong><small>Actual, estimated and synthetic stay separate</small></div></li></ul></Card></div>
 <div className={s.bottomRow}><Card title="Top Performing Products" href="/cockpit/products" icon={<Package/>}>{arr(portfolio.data?.items).length?<ul className={s.products}>{arr(portfolio.data?.items).slice(0,5).map((p,i)=><li key={text(p.missionId,String(i))}><Package/><Link href="/cockpit/products"><strong>{text(p.title)}</strong><small>{text(p.sku)} · {text(p.phase)}</small></Link></li>)}</ul>:<div className={s.empty}><Package/><p>{portfolio.error||'No current source-backed product records.'}</p><p>Performance ranking awaits actual sales evidence.</p><Link href="/cockpit/products">Inspect portfolio and saved evidence →</Link></div>}</Card>
 <Card title="Recent Orders" href="/cockpit/orders" icon={<ShoppingCart/>}><div className={s.empty}><ShoppingCart/><p>Live orders are not established.</p><p>Inspect isolated saved order lifecycles separately from real commerce.</p><Link href="/cockpit/orders">Open order command →</Link></div></Card>
 <Card title="Live Cost Centre" href="/cockpit/cost-centre" icon={<ChartNoAxesCombined/>}><dl className={s.costs}><div><dt>Known technology expense</dt><dd>{money(kpi.knownTechnologySgdMicro)}</dd></div><div><dt>Known commerce COGS</dt><dd>{money(kpi.knownCogsSgdMicro)}</dd></div><div><dt>Known net subtotal</dt><dd>{money(kpi.knownNetSgdMicro)}</dd></div></dl><p className={s.note}>All-history reviewed subtotal · incomplete coverage. Not certified profit or available cash.</p>{finance.error&&<p role="alert" className={s.note}>{finance.error}</p>}<Link className={s.briefLink} href="/cockpit/finance">Reconcile source records →</Link></Card></div></div>
 <div className={s.landscape} aria-hidden="true"/></div>;
}
