'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import s from './journeys.module.css';
type Row=Record<string,unknown>;
const obj=(x:unknown):Row=>x&&typeof x==='object'&&!Array.isArray(x)?x as Row:{};
const rows=(x:unknown):Row[]=>Array.isArray(x)?x.map(obj):[];
const txt=(x:unknown,f='Unknown'):string=>typeof x==='string'||typeof x==='number'?String(x):f;
const labels={supplierPurchases:'Supplier purchases',listingPublication:'Listing publication',priceInventory:'Price / inventory writes'};
const pendingKey='empireai.work7.safety.pending.v1';
type Breakers=Record<keyof typeof labels,boolean>;
function Facts({value}:{value:unknown}){return <dl className={s.facts}>{Object.entries(obj(value)).map(([k,v])=><div key={k}><dt>{k.replace(/([A-Z])/g,' $1')}</dt><dd>{v===null||v===undefined?'Unknown':Array.isArray(v)?v.length?v.map((a,i)=><details key={i}><summary>Evidence {i+1}</summary>{typeof a==='object'?<Facts value={a}/>:txt(a)}</details>):'None recorded':typeof v==='object'?<Facts value={v}/>:String(v)}</dd></div>)}</dl>;}
export function SafetyCommand(){
 const [data,setData]=useState<Row|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('ALL'),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[notice,setNotice]=useState(''),[receipt,setReceipt]=useState<Row|null>(null),[pending,setPending]=useState<Row|null>(null);
 const [limits,setLimits]=useState({perOrder:'',daily:'',aggregate:''}),[breakers,setBreakers]=useState<Breakers>({supplierPurchases:false,listingPublication:false,priceInventory:false});
 const load=useCallback(async()=>{const r=await fetch('/api/owner/advisor/safety',{cache:'no-store'});const d=await r.json();if(!r.ok||!Array.isArray(d.guards)||typeof d.controls?.version!=='number')throw Error(d.error||'Safety evidence unavailable');setData(d);setError('');const c=obj(d.controls),l=obj(c.limits),b=obj(c.desiredPauses);setLimits({perOrder:txt(l.perOrder,''),daily:txt(l.daily,''),aggregate:txt(l.aggregate,'')});setBreakers({supplierPurchases:b.supplierPurchases===true,listingPublication:b.listingPublication===true,priceInventory:b.priceInventory===true});return d as Row;},[]);
 useEffect(()=>{const t=setTimeout(()=>{try{const raw=sessionStorage.getItem(pendingKey);if(raw){const saved=JSON.parse(raw);if(saved.action==='safety_policy'&&typeof saved.id==='string'&&saved.id.startsWith('safety_'))setPending(saved);}}catch{}void load().catch(e=>setError(e.message));},0);return()=>clearTimeout(t);},[load]);
 const controls=obj(data?.controls),guards=rows(data?.guards),isolated=obj(data?.isolatedEvidence);

 useEffect(()=>{if(!data)return;const hash=location.hash.slice(1);if(hash.startsWith('safety-')){const el=document.getElementById(hash);if(el instanceof HTMLDetailsElement)el.open=true;el?.scrollIntoView({block:'start'});}},[data]);
 async function save(command?:Row){setBusy(true);setNotice('');let cmd=command;try{if(!cmd){if(!confirmed||reason.trim().length<5)throw Error('Confirm the exact policy and provide a reason.');const values=Object.fromEntries(Object.entries(limits).map(([k,v])=>[k,v===''?null:Number(v)]));if(Object.values(values).some(v=>v!==null&&(!Number.isFinite(v)||v<0)))throw Error('Limits must be non-negative SGD amounts, or blank for unknown.');cmd={action:'safety_policy',id:'safety_'+crypto.randomUUID(),expectedVersion:controls.version,confirmation:true,limits:{currency:'SGD',...values},breakers,reason};setPending(cmd);try{sessionStorage.setItem(pendingKey,JSON.stringify(cmd));}catch{}}
 const r=await fetch('/api/owner/advisor/memory',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(cmd)});const body=await r.json();if(!r.ok){if([400,401,403,409,422].includes(r.status)){setPending(null);try{sessionStorage.removeItem(pendingKey);}catch{}}throw Error(body.error||`Policy refused (${r.status})`);}const result=obj(body.result);if(typeof result.id!=='string')throw Error('No durable policy receipt returned. Reconcile the same command.');setReceipt(result);const readback=await load(),c=obj(readback.controls);if(c.receiptId!==result.id||c.verifiedReadback!==true){if(c.verifiedReadback===true&&Number(c.version)>Number(cmd.expectedVersion)+1){setPending(null);try{sessionStorage.removeItem(pendingKey);}catch{}setConfirmed(false);setNotice('Your durable receipt is retained, but a newer owner policy superseded it. Review the current controlled state before another change.');return;}throw Error('Receipt returned, but controlled-state readback is not yet verified. Reconcile before changing policy again.');}setPending(null);try{sessionStorage.removeItem(pendingKey);}catch{}setConfirmed(false);setNotice('Policy receipt and controlled state independently re-read. Live commerce remains locked.');
 }catch(e){setError(e instanceof Error?e.message:'Outcome unknown. Reconcile the same command.');}finally{setBusy(false);}}
 return <section id="safety-command" aria-labelledby="safety-heading" className={s.page}><header className={s.header}><h2 id="safety-heading">Safety Command · all 15 guards</h2><p>What is protected, uncertain, stopped and awaiting King. Operational certification remains a Work 8 obligation.</p><span className={s.badge}>NOT_BORN · COMMERCE LOCKED</span></header>
 {error&&<div role="alert" className={s.error}>{error}<button onClick={()=>void load().catch(e=>setError(e.message))}>Refresh safety evidence</button></div>}{!data&&!error&&<p role="status">Loading safety evidence…</p>}
 {data&&<><p className={s.note}>Source read {txt(data.at)}. Unknown is never verified. Synthetic acceptance evidence is excluded from actual exposure.</p><div className={s.cards}>{['VERIFIED','AT_RISK','TRIPPED','UNKNOWN'].map(status=><article className={s.card} key={status}><p>{status.replaceAll('_',' ')}</p><strong className={s.value}>{guards.filter(g=>g.status===status).length}</strong></article>)}</div>
 <label>Show guards<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">All 15 protections</option>{['VERIFIED','AT_RISK','TRIPPED','UNKNOWN'].map(v=><option key={v}>{v}</option>)}</select></label>
 <div>{guards.map((g,i)=><details hidden={filter!=='ALL'&&filter!==g.status} id={`safety-${String(i+1).padStart(2,'0')}`} key={txt(g.id)} className={s.details} data-testid="safety-guard"><summary>{String(i+1).padStart(2,'0')} · {txt(g.title)} <span className={s.badge}>{txt(g.status)}</span></summary><p>{txt(g.detectionReason)}</p><Facts value={{lastEvidenceAt:g.lastEvidenceAt,affectedOrders:g.affectedOrders,affectedProducts:g.affectedProducts,financialExposure:g.financialExposure,actionTaken:g.actionTaken,recoveryEvidence:g.recoveryEvidence,kingMustAct:g.kingMustAct,classification:g.classification}}/><details><summary>Policy, enforcement and source evidence</summary><Facts value={{evidence:g.evidence,limitations:g.limitations}}/></details><div className={s.links}><Link className={s.button} href={i===10?'/cockpit/finance':i===11?'/cockpit/ceo#recommendations':i===12?'#safety-controls':'/cockpit/commerce/governed'}>Inspect {i===10?'financial reconciliation':i===11?'Pillow corrective decisions':i===12?'controlled state':'governed evidence'} →</Link><Link className={s.button} href="/cockpit/advisor">Independent Advisor readback →</Link></div></details>)}</div>
 <section id="safety-controls" className={s.card}><h3>Owner controls · policy and circuit breakers</h3><p className={s.note}>Version {txt(controls.version)} · {txt(controls.globalLock)}. Clearing an owner pause cannot unlock commerce. Blank ceilings remain unknown; zero permits no spend.</p><p className={s.note}>Spending basis: {txt(controls.spendBasis,'Conservative bound includes prior outstanding commitments until settlement release is verified; not just calendar-day spend.')}</p><div className={s.grid}>{Object.entries(labels).map(([key,label])=><article className={s.details} key={key}><h4>{label}</h4><p>Effective: {obj(controls.effectivePauses)[key]===true?'PAUSED / BLOCKED':'Not verified'}</p><label><input type="checkbox" checked={breakers[key as keyof Breakers]} onChange={e=>setBreakers({...breakers,[key]:e.target.checked})}/> Owner pause {label.toLowerCase()}</label></article>)}</div>
 <form onSubmit={e=>{e.preventDefault();void save();}}><div className={s.toolbar}>{Object.entries({perOrder:'Per-order ceiling SGD',daily:'Daily ceiling SGD',aggregate:'Aggregate ceiling SGD'}).map(([key,label])=><label key={key}>{label}<input type="number" min="0" step="0.01" value={limits[key as keyof typeof limits]} onChange={e=>setLimits({...limits,[key]:e.target.value})}/></label>)}</div><label>Policy change reason<textarea required minLength={5} value={reason} onChange={e=>setReason(e.target.value)} className="w-full"/></label><label className="flex items-center gap-3 py-3"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I confirm these exact pauses and spending ceilings. This grants no commerce authority.</label><button disabled={busy||!!pending||!confirmed||reason.trim().length<5}>Save confirmed safety policy</button></form>
 {pending&&<div role="status"><p>Pending command {txt(pending.id)}. Do not create another action while its outcome is unresolved.</p><button disabled={busy} onClick={()=>void save(pending)}>Reconcile same policy command</button></div>}{notice&&<p role="status">{notice}</p>}{receipt&&<details open className={s.details} data-testid="safety-receipt"><summary>Durable safety policy receipt</summary><Facts value={receipt}/><p>Readback policy: {txt(controls.receiptId)} · hash {txt(controls.receiptHash)}</p><Link className={s.button} href={'/cockpit/advisor?record='+encodeURIComponent('memory:'+txt(receipt.id,''))}>Independently inspect through King’s Advisor →</Link></details>}
 <details className={s.details}><summary>Enforced paths and current policy evidence</summary><Facts value={controls}/></details></section>
 <section className={s.card}><h3>Quarantined and failed-order evidence</h3><p className={s.note}>{txt(isolated.classification)}. Timeout does not establish failed purchase. Unknown outcomes must be reconciled before any retry.</p>{rows(isolated.unknownOutcomes).map(o=><Order key={txt(o.id)} order={o}/>)}{rows(isolated.failedOrPartialOrders).filter(o=>!rows(isolated.unknownOutcomes).some(u=>u.id===o.id)).map(o=><Order key={txt(o.id)} order={o}/>)}{!rows(isolated.unknownOutcomes).length&&!rows(isolated.failedOrPartialOrders).length&&<p>No affected isolated orders in this bounded read. Actual external exposure is unknown.</p>}<Link className={s.button} href="/cockpit/orders">Open order and package evidence →</Link></section><details className={s.details}><summary>Coverage, source gaps and future certification</summary><Facts value={{coverage:data.coverage,sourceErrors:data.sourceErrors}}/><p>Work 8 must independently exercise 1 / 10 / 100+ orders, duplicate submission, timeout, crash, stale stock, partial shipment, payout discrepancy, kill-switch recovery and loss reconciliation. These tests have not passed merely because this interface renders.</p></details></>}
 </section>;
}
function Order({order}:{order:Row}){return <details className={s.details} data-testid="safety-order"><summary>{txt(order.id)} · {order.unknownOutcome?'OUTCOME_UNKNOWN — quarantined':txt(order.outcome)}</summary><Facts value={order}/><p>No blind resubmission. Reconcile the canonical order and supplier receipt.</p><Link className={s.button} href={txt(order.href,'/cockpit/orders')}>Inspect order decision and receipt →</Link><button disabled title="No live external recovery authority exists while NOT_BORN and LOCKED">Retry external purchase — locked</button></details>;}
