import type { PersistenceModelRecord } from "./types.js";

/** Canonical persistence model registry (P5-03). */
export const PERSISTENCE_MODEL_REGISTRY: PersistenceModelRecord[] = [
  {
    id: "PM-REDIS-AUTH",
    name: "Redis Auth Sessions",
    mechanism: "Redis SETEX empireai:session:{token}",
    location: "backend/src/auth/session-store.ts",
    durabilityTier: "durable",
    expirationPolicy: "SESSION_TTL_SECONDS (default 604800)",
    cleanupPolicy: "TTL auto-expire · explicit destroy on logout",
    postgresCompatible: false,
    operationalImpact: "Auth survives Brain restart when Redis connected",
  },
  {
    id: "PM-INMEM-AUTH",
    name: "In-Memory Auth Fallback",
    mechanism: "Map<string, SessionRecord>",
    location: "backend/src/auth/session-store.ts",
    durabilityTier: "ephemeral",
    expirationPolicy: "SESSION_TTL_SECONDS (not enforced in-memory)",
    cleanupPolicy: "Lost on Brain restart",
    postgresCompatible: false,
    operationalImpact: "All logins lost on restart — degraded mode only",
  },
  {
    id: "PM-SQLITE-USERS",
    name: "SQLite User Store",
    mechanism: "users table",
    location: "backend/src/auth/session-store.ts",
    durabilityTier: "durable",
    expirationPolicy: "Permanent credentials",
    cleanupPolicy: "Manual admin only",
    postgresCompatible: true,
    operationalImpact: "User accounts survive restart",
  },
  {
    id: "PM-INMEM-PILLOW",
    name: "Pillow Host Session Store",
    mechanism: "Map<workspaceId:sessionId, WorkspaceSession>",
    location: "backend/src/orchestration/pillow-host/session-store.ts",
    durabilityTier: "ephemeral",
    expirationPolicy: "Until Brain restart or stop()",
    cleanupPolicy: "sessionStore.clear() on host stop",
    postgresCompatible: true,
    operationalImpact: "Chat history lost on restart",
  },
  {
    id: "PM-LOCALSTORAGE",
    name: "Browser localStorage",
    mechanism: "empireai:pillow:session:v1 JSON",
    location: "empireai-web/lib/cockpit/pillow/pillow-session-store.ts",
    durabilityTier: "semi_durable",
    expirationPolicy: "Until user clears storage",
    cleanupPolicy: "clearPillowHostSession() removes hostSessionId only",
    postgresCompatible: false,
    operationalImpact: "Turns survive browser refresh",
  },
  {
    id: "PM-SQLITE-EC",
    name: "Executive Council SQLite",
    mechanism: "ec_* tables",
    location: "backend/src/executive-council/",
    durabilityTier: "durable",
    expirationPolicy: "Permanent archive",
    cleanupPolicy: "None — governance records",
    postgresCompatible: true,
    operationalImpact: "Council sessions survive restart",
  },
  {
    id: "PM-INMEM-SUPERVISOR",
    name: "Supervisor Mission Registry",
    mechanism: "Map<string, SupervisedMission>",
    location: "pillow/src/supervisor/registry.ts",
    durabilityTier: "ephemeral",
    expirationPolicy: "Process lifetime",
    cleanupPolicy: "Lost on Brain restart",
    postgresCompatible: true,
    operationalImpact: "In-flight missions lost — re-launch from artifact",
  },
  {
    id: "PM-COI-SINGLETON",
    name: "Pillow COI Runtime Singleton",
    mechanism: "Module-level engine references",
    location: "pillow/src/session.ts",
    durabilityTier: "recoverable",
    expirationPolicy: "Until resetPillowSession()",
    cleanupPolicy: "Full re-bootstrap on startPillow()",
    postgresCompatible: false,
    operationalImpact: "~130s recovery chain on Brain restart",
  },
];

export function getPersistenceByTier(tier: import("./types.js").DurabilityTier): PersistenceModelRecord[] {
  return PERSISTENCE_MODEL_REGISTRY.filter((p) => p.durabilityTier === tier);
}
