import type { SessionLayerRecord } from "./types.js";

/** Canonical session layer registry — every session type with one documented model (P5-03). */
export const SESSION_LAYER_REGISTRY: SessionLayerRecord[] = [
  {
    id: "DS-AUTH",
    domain: "authentication",
    name: "Authentication Session",
    purpose: "Grand King login continuity — cookie/Bearer token auth",
    persistence: "Redis (empireai:session:{token}) or InMemorySessionStore fallback",
    durabilityTier: "durable",
    lifecycleState: "persisted",
    recoveryStrategy: "Redis: survives Brain restart · In-memory: lost on restart — re-login required",
    expirationPolicy: "SESSION_TTL_SECONDS (default 7 days) · POST /auth/refresh",
    securityControls: ["Opaque token (not JWT)", "HttpOnly cookie", "SESSION_SECRET signing", "Audit on login/logout"],
    knownLossScenarios: ["Redis unavailable → in-memory fallback", "Token expiry → 401"],
    owner: "Brain Auth · backend/src/auth/",
    futureEvolution: "Mandatory Redis in production · refresh wired on frontend",
  },
  {
    id: "DS-EXEC",
    domain: "executive",
    name: "Executive Council Session",
    purpose: "Multi-perspective executive deliberation records",
    persistence: "SQLite ec_* tables",
    durabilityTier: "durable",
    lifecycleState: "archived",
    recoveryStrategy: "Reload from SQLite on request",
    expirationPolicy: "Permanent archive — no auto-expiry",
    securityControls: ["Workspace scoped", "Internal only", "Audit logged"],
    knownLossScenarios: ["SQLite volume loss"],
    owner: "Executive Council · backend/src/executive-council/",
    futureEvolution: "PostgreSQL migration",
  },
  {
    id: "DS-PILLOW-HOST",
    domain: "pillow",
    name: "Pillow Host Workspace Session",
    purpose: "Server-side chat history · approval state · token usage per workspace",
    persistence: "In-memory Map (PillowSessionStore) — PILLOW-016",
    durabilityTier: "ephemeral",
    lifecycleState: "active",
    recoveryStrategy: "Client localStorage turns survive refresh · hostSessionId re-created on 503 boot",
    expirationPolicy: "Cleared on pillowHost.stop() · Brain restart",
    securityControls: ["Workspace scoped", "pillowAuth middleware", "No secrets in session"],
    knownLossScenarios: ["Brain restart loses all chat", "pillowHost.stop() clears store"],
    owner: "Pillow Host · backend/src/orchestration/pillow-host/",
    futureEvolution: "Redis or SQLite persistence for WorkspaceSession",
  },
  {
    id: "DS-PILLOW-COI",
    domain: "pillow",
    name: "Pillow COI Runtime Session",
    purpose: "Singleton in-process engine bundle after startPillow()",
    persistence: "In-process module singletons",
    durabilityTier: "recoverable",
    lifecycleState: "active",
    recoveryStrategy: "Automatic re-bootstrap via startPillow() on Brain restart (~130s chain)",
    expirationPolicy: "resetPillowSession() clears all engines",
    securityControls: ["Server-side only", "No client exposure"],
    knownLossScenarios: ["Brain restart", "resetPillowSession()"],
    owner: "Pillow COI · pillow/src/session.ts",
    futureEvolution: "Warm restart checkpoint for critical engines",
  },
  {
    id: "DS-BUILDER",
    domain: "builder",
    name: "Builder Mission Session",
    purpose: "Assembled engineering missions via Cursor Bridge",
    persistence: "Artifact files on disk + in-process mission state",
    durabilityTier: "semi_durable",
    lifecycleState: "persisted",
    recoveryStrategy: "Mission artifacts survive restart · re-dispatch from artifact path",
    expirationPolicy: "Artifacts permanent until cleaned",
    securityControls: ["Approval gate", "Grand King override", "Guardian pre-dispatch"],
    knownLossScenarios: ["In-flight dispatch lost on restart"],
    owner: "Cursor Bridge · PILLOW-CB-001",
    futureEvolution: "Persist in-flight dispatch queue",
  },
  {
    id: "DS-SUPERVISOR",
    domain: "supervisor",
    name: "Supervisor Mission Session",
    purpose: "Active supervised missions · heartbeat · recovery orchestration",
    persistence: "In-memory MissionRegistry",
    durabilityTier: "ephemeral",
    lifecycleState: "active",
    recoveryStrategy: "Re-launch from mission artifact if interrupted",
    expirationPolicy: "Lost on Brain restart",
    securityControls: ["Builder gate chain", "Recovery doctrine validation"],
    knownLossScenarios: ["Brain restart mid-mission"],
    owner: "Supervisor · PILLOW-007",
    futureEvolution: "SQLite mission checkpoint",
  },
  {
    id: "DS-JOURNEY",
    domain: "journey",
    name: "Journey Session",
    purpose: "Permanent execution history · traceability events",
    persistence: "In-session event store + JOURNEY.md via synchronizer",
    durabilityTier: "semi_durable",
    lifecycleState: "archived",
    recoveryStrategy: "JOURNEY.md reload · synchronizer writes on mission complete",
    expirationPolicy: "Permanent — never deleted",
    securityControls: ["Read-only governance", "Synchronizer owns writes"],
    knownLossScenarios: ["In-session events lost before synchronizer write"],
    owner: "Journey System · PILLOW-JR-001",
    futureEvolution: "Persistent journey archive DB",
  },
  {
    id: "DS-MISSION",
    domain: "mission",
    name: "Mission Planner Session",
    purpose: "Repository-derived mission plan and sequencing state",
    persistence: "Rebuilt from repository on memory refresh",
    durabilityTier: "recoverable",
    lifecycleState: "active",
    recoveryStrategy: "memoryEngine.ensureFresh() + planner.refresh()",
    expirationPolicy: "Rebuilt each Pillow boot",
    securityControls: ["Repository truth only — no hallucinated missions"],
    knownLossScenarios: ["Stale memory if watcher not running"],
    owner: "Mission Planner · PILLOW-006",
    futureEvolution: "Checkpoint plan hash",
  },
  {
    id: "DS-PRODUCTION",
    domain: "production",
    name: "Production Mode Session",
    purpose: "Operational state assessment · feature flag snapshot",
    persistence: "Re-assessed from env on each request",
    durabilityTier: "recoverable",
    lifecycleState: "active",
    recoveryStrategy: "collectProductionModeSnapshot() on API call",
    expirationPolicy: "Snapshot TTL = request scope",
    securityControls: ["Read-only assessment", "No secret exposure in snapshot"],
    knownLossScenarios: ["Env change between assessments"],
    owner: "Production Mode · PILLOW-PM-001",
    futureEvolution: "Historical production mode audit trail",
  },
  {
    id: "DS-BROWSER",
    domain: "browser",
    name: "Browser Pillow Session",
    purpose: "Client-side conversation turns · panel preferences",
    persistence: "localStorage (empireai:pillow:session:v1)",
    durabilityTier: "semi_durable",
    lifecycleState: "persisted",
    recoveryStrategy: "Survives browser refresh · hostSessionId re-bound on reconnect",
    expirationPolicy: "Until localStorage cleared",
    securityControls: ["No secrets stored", "Credentials via httpOnly cookie"],
    knownLossScenarios: ["localStorage cleared", "Orphaned hostSessionId after server restart"],
    owner: "Cockpit · empireai-web/lib/cockpit/pillow/",
    futureEvolution: "IndexedDB for larger history",
  },
  {
    id: "DS-API",
    domain: "api",
    name: "API Request Session",
    purpose: "Per-request auth context · workspace scope",
    persistence: "Request-scoped — derived from auth token",
    durabilityTier: "ephemeral",
    lifecycleState: "active",
    recoveryStrategy: "Re-authenticate on 401 · cookie refresh",
    expirationPolicy: "Request lifetime",
    securityControls: ["Auth middleware", "Workspace isolation", "Rate limiting"],
    knownLossScenarios: ["Token expiry mid-request"],
    owner: "Brain API · auth middleware",
    futureEvolution: "Request correlation IDs in audit",
  },
];

export function getLayersByTier(tier: import("./types.js").DurabilityTier): SessionLayerRecord[] {
  return SESSION_LAYER_REGISTRY.filter((l) => l.durabilityTier === tier);
}

export function getSessionLayer(id: string): SessionLayerRecord | undefined {
  return SESSION_LAYER_REGISTRY.find((l) => l.id === id);
}
