import { readFileSync } from "node:fs"; import { join } from "node:path";
import type { EmpireBootstrapContext } from "../bootstrap/types.js"; import { buildNotificationWorkerConfiguration } from "./configuration.js"; import { CHANNELS,NOTIFICATION_WORKER_SYSTEM_PATH,NTW_INTEGRATION_TARGETS } from "./paths.js"; import type { Channel,NotificationBuildReport,NotificationMessage,NotificationTransport,NotificationWorkerConfiguration,NotificationWorkerDependencies,NotificationWorkerState } from "./types.js"; import { ProviderRegistry } from "./provider-registry.js"; import { TemplateStore } from "./template-store.js"; import { PreferenceStore } from "./preference-store.js"; import { QueueManager } from "./queue-manager.js"; import { DeliveryTracker } from "./delivery-tracker.js"; import { SecretVault } from "./secret-vault.js"; import { NotificationAudit } from "./notification-audit.js"; import { ReportStore } from "./report-store.js"; import { DEFAULT_NOTIFICATION_TRANSPORT } from "./provider-adapters.js"; import { validateNotificationInput } from "./notification-validator.js"; import { bindNotificationWorkerIntegrations } from "./integrations.js";
const id=(prefix:string)=>`${prefix}-${crypto.randomUUID()}`,now=()=>new Date().toISOString();
export class NotificationWorkerEngine {
 private initializedAt:string|null=null;private deps:NotificationWorkerDependencies={};private transport:NotificationTransport=DEFAULT_NOTIFICATION_TRANSPORT;private requirementsReportId?:string;private architectureReportId?:string;
 readonly providers=new ProviderRegistry();readonly templates=new TemplateStore();readonly preferences=new PreferenceStore();readonly queue=new QueueManager();readonly deliveries=new DeliveryTracker();readonly vault=new SecretVault();readonly audit=new NotificationAudit();readonly reports=new ReportStore();readonly messages=new Map<string,NotificationMessage>();readonly config:NotificationWorkerConfiguration;
 constructor(private bootstrap:{repositoryRoot:string}|EmpireBootstrapContext,options:{configuration?:Partial<NotificationWorkerConfiguration>}={}){this.config=buildNotificationWorkerConfiguration(bootstrap.repositoryRoot,options.configuration)}
 async initialize(){let document="";try{document=readFileSync(join(this.bootstrap.repositoryRoot,NOTIFICATION_WORKER_SYSTEM_PATH),"utf8")}catch{throw new Error(`${NOTIFICATION_WORKER_SYSTEM_PATH} missing`)}if(!document.includes("Notification Worker"))throw new Error("Notification Worker governance document is invalid");this.initializedAt=now();this.audit.append("initialized",{doctrine:"PILLOW-NTW-001"});return this.getState()}
 bindIntegrations(deps:NotificationWorkerDependencies={}){this.deps=bindNotificationWorkerIntegrations(this.deps,deps);return this.deps}connect(deps:NotificationWorkerDependencies={}){return this.bindIntegrations(deps)}
 getState():NotificationWorkerState{return {engineVersion:"PILLOW-NTW-001",missionId:"Q6-12",status:this.initializedAt?"ready":"idle",initializedAt:this.initializedAt,configuration:this.config,latestReport:this.reports.latest()}}
 validate(input:Record<string,unknown>={}){return validateNotificationInput(input)} diagnostics(){return {valid:this.validate().valid,providers:this.providers.list().length,messages:this.messages.size,targets:[...NTW_INTEGRATION_TARGETS]}} getCockpitSnapshot(){return {missionId:"Q6-12",status:this.getState().status,workerId:"wkr-notification-01",providers:this.providers.list().length,messages:this.messages.size,neverFabricateDeliveryResults:true,neverImplementQ613OrLater:true}}validateForSupervisorSync(){return {valid:!!this.initializedAt,health:this.initializedAt?"healthy":"blocked",readinessScore:this.initializedAt?100:0,notes:[`Q6-12 ${this.getState().status}`]}}
 private checked(input:Record<string,unknown>){const result=this.validate(input);if(!result.valid)throw new Error(result.issues.join("; "))}
 receiveApprovedRequirementsReports(input:Record<string,unknown>={}){this.checked(input);this.requirementsReportId=String(input.reportId??id("ntw-bld"));return {buildId:id("ntw-bld"),requirementsReportId:this.requirementsReportId}}receiveApprovedRequirementsReport(input:Record<string,unknown>={}){return this.receiveApprovedRequirementsReports(input)}
 receiveApprovedArchitectureReports(input:Record<string,unknown>={}){this.checked(input);this.architectureReportId=String(input.reportId??id("ntw-bld"));return {buildId:id("ntw-bld"),architectureReportId:this.architectureReportId}}receiveApprovedArchitectureReport(input:Record<string,unknown>={}){return this.receiveApprovedArchitectureReports(input)}
 registerNotificationProviders(){return {stage:"provider_registration"}}supportEmailNotifications(){return {channel:"email"}}supportSmsNotifications(){return {channel:"sms"}}supportTelegramNotifications(){return {channel:"telegram"}}supportWhatsAppNotifications(){return {channel:"whatsapp"}}supportInternalApplicationNotifications(){return {channel:"in_app"}}supportTemplatedNotifications(){return {stage:"templates"}}supportNotificationQueuesAndRetries(){return {stage:"queue_retries"}}recordNotificationAuditHistory(){return this.getAuditEvents()} 
 registerProvider(input:{providerId?:string;name:string;channel:Channel;validated?:boolean}){this.checked(input);if(!CHANNELS.includes(input.channel))throw new Error("Unsupported notification channel");const provider={providerId:input.providerId??id("ntw-prv"),name:input.name,channel:input.channel,validated:input.validated===true,createdAt:now()};this.audit.append("provider_registered",{providerId:provider.providerId,channel:provider.channel});return this.providers.save(provider)}
 storeProviderCredentials(input:{providerId:string;secret:string;validated?:boolean}){this.checked(input);if(!this.providers.get(input.providerId))throw new Error("Provider not found");const ref=this.vault.store(input.providerId,input.secret);const provider=this.providers.get(input.providerId)!;provider.credentialRef=ref;this.providers.save(provider);this.audit.append("credentials_stored",{providerId:input.providerId,credentialRefId:ref.credentialRefId});return ref}
 createTemplate(input:{templateId?:string;name:string;channel:Channel;subject?:string;body:string;validated?:boolean}){this.checked(input);if(!input.body)throw new Error("Template body is required");const template={templateId:input.templateId??id("ntw-tpl"),name:input.name,channel:input.channel,subject:input.subject,body:input.body,validated:input.validated===true,createdAt:now()};return this.templates.save(template)}renderTemplate(input:{templateId:string;variables:Record<string,unknown>}){return this.templates.render(input.templateId,input.variables)}
 setUserPreference(input:{userId:string;channel:Channel;enabled:boolean}){return this.preferences.set({preferenceId:id("ntw-pref"),...input,updatedAt:now()})}setTransport(transport:NotificationTransport){this.transport=transport}
 enqueueNotification(input:{messageId?:string;channel:Channel;to:string;templateId?:string;subject?:string;body?:string;variables?:Record<string,unknown>;userId?:string;sendAt?:string;providerId?:string;validated?:boolean}){this.checked(input);if(!input.to)throw new Error("Notification recipient is required");let rendered={subject:input.subject,body:input.body??""};if(input.templateId)rendered=this.templates.render(input.templateId,input.variables??{});if(!rendered.body)throw new Error("Notification body is required");const future=input.sendAt&&new Date(input.sendAt)>new Date(),disabled=!!input.userId&&!this.preferences.enabled(input.userId,input.channel),message:NotificationMessage={messageId:input.messageId??id("ntw-msg"),channel:input.channel,to:input.to,providerId:input.providerId,templateId:input.templateId,subject:rendered.subject,body:rendered.body,variables:input.variables,userId:input.userId,sendAt:input.sendAt,status:disabled?"failed":future?"scheduled":"queued",attempts:0,createdAt:now()};this.messages.set(message.messageId,message);if(disabled){this.deliveries.record({deliveryId:id("ntw-evt"),messageId:message.messageId,status:"failed",attempt:0,timestamp:now(),reason:"User preference disabled"});this.audit.append("delivery_skipped_preference",{messageId:message.messageId});return message}this.queue.save({jobId:id("ntw-job"),messageId:message.messageId,attempts:0,availableAt:input.sendAt??now(),status:message.status,createdAt:now()});this.audit.append("notification_enqueued",{messageId:message.messageId});return message}
 async processQueue(input:{maxJobs?:number}={}){let processed=0;const max=input.maxJobs??100;while(processed<max){const job=this.queue.due().at(0);if(!job)break;const message=this.messages.get(job.messageId);if(!message)break;processed++;job.status="sending";message.status="sending";this.deliveries.record({deliveryId:id("ntw-evt"),messageId:message.messageId,status:"sending",attempt:message.attempts+1,timestamp:now()});const provider=message.providerId?this.providers.get(message.providerId):this.providers.byChannel(message.channel)[0];const result=await this.transport.send({providerId:provider?.providerId,channel:message.channel,to:message.to,subject:message.subject,body:message.body});message.attempts++;job.attempts=message.attempts;if(result.success){message.status="sent";job.status="sent";this.deliveries.record({deliveryId:id("ntw-evt"),messageId:message.messageId,status:"sent",attempt:message.attempts,timestamp:now()});this.audit.append("delivery_sent",{messageId:message.messageId});continue}if(message.attempts<=this.config.maxRetries){message.status="retrying";job.status="retrying";job.availableAt=new Date(Date.now()+this.config.backoffMs).toISOString();this.deliveries.record({deliveryId:id("ntw-evt"),messageId:message.messageId,status:"retrying",attempt:message.attempts,timestamp:now(),reason:result.reason});continue}message.status="failed";job.status="failed";this.deliveries.record({deliveryId:id("ntw-evt"),messageId:message.messageId,status:"failed",attempt:message.attempts,timestamp:now(),reason:result.reason});this.audit.append("delivery_failed",{messageId:message.messageId})}return {processed,messages:this.getMessages()}}
 async retryFailed(input:{messageId?:string;maxRetries?:number}={}){const failed=this.getMessages().filter(x=>x.status==="failed"&&(!input.messageId||x.messageId===input.messageId));for(const message of failed){message.status="retrying";message.attempts=0;this.queue.save({jobId:id("ntw-job"),messageId:message.messageId,attempts:0,availableAt:now(),status:"retrying",createdAt:now()})}return this.processQueue({maxJobs:input.maxRetries??100})}configureRetry(input:{maxRetries:number;backoffMs:number}){if(input.maxRetries<0||input.backoffMs<0)throw new Error("Retry values must be non-negative");(this.config as {maxRetries:number;backoffMs:number}).maxRetries=input.maxRetries;(this.config as {maxRetries:number;backoffMs:number}).backoffMs=input.backoffMs;return this.config}
 getProviders(){return this.providers.list()}getCredentialRefs(){return this.providers.list().flatMap(x=>x.credentialRef?[x.credentialRef]:[])}getTemplates(){return this.templates.list()}getMessages(){return [...this.messages.values()]}getDeliveryRecords(){return this.deliveries.list()}getQueueJobs(){return this.queue.list()}getPreferences(){return this.preferences.list()}getAuditEvents({limit=50}:{limit?:number}={}){return this.audit.list(limit)}
 broadcast(input:{channel:Channel;templateId?:string;body?:string;variables?:Record<string,unknown>;recipients:string[]}){return input.recipients.map(to=>this.enqueueNotification({...input,to}))}
 produceNotificationBuildReport(input:{platformId?:string;platformName?:string;businessId?:string;businessObjective?:string}={}){const messages=this.getMessages(),sent=messages.filter(x=>x.status==="sent").length,failed=messages.filter(x=>x.status==="failed").length;const report:NotificationBuildReport={buildId:id("ntw-bld"),timestamp:now(),platformId:input.platformId,platformName:input.platformName??"EmpireAI",notificationProviders:this.getProviders(),templates:this.getTemplates(),messagesSent:sent,deliveryStatus:`${sent} sent, ${failed} failed`,retryStatus:`${messages.filter(x=>x.status==="retrying").length} retrying`,failedDeliveries:failed,auditStatus:"recorded",outstandingIssues:[],confidenceScore:1,metadataVersion:"NTW-001-v1",buildStatus:"complete",neverReplaceWorkflowOrchestration:true,neverReplaceBusinessLogic:true,neverExposeCredentialsOrSecrets:true,neverFabricateDeliveryResults:true,neverImplementQ613OrLater:true,neverOverridePillowGrandKingApprovedArchitecture:true,followApprovedRequirementsAndArchitecture:true,preserveCompleteTraceability:true,preserveNotificationAuditHistory:true,maskSensitiveValues:true,requirementsReportId:this.requirementsReportId,architectureReportId:this.architectureReportId,factoryMissionId:"Q6-12",businessId:input.businessId,businessObjective:input.businessObjective,buildSteps:["validated boundaries","queued notifications","recorded explicit delivery outcomes"],selfReview:"Delivery success is recorded only from explicit transport outcomes.",workerId:"wkr-notification-01",reportVersion:"NTW-RPT-v1",traceabilityRefs:messages.map(x=>x.messageId),submittedToExecutiveReporting:false};return this.reports.save(report)}
 submitReport(input:{platformId?:string;platformName?:string}={}){const report=this.produceNotificationBuildReport(input);const result=(this.deps.executiveReportingRuntime as {submitWorkerReport?:(v:unknown)=>unknown}|undefined)?.submitWorkerReport?.({missionId:"Q6-12",report}) as {records?:Array<{reportId?:string}>}|undefined;report.executiveReportId=result?.records?.[0]?.reportId;report.submittedToExecutiveReporting=!!report.executiveReportId;return report}list(){return this.reports.list()}
}
export { NotificationWorkerEngine as NotificationWorker };
export const createNotificationWorker=(bootstrap:EmpireBootstrapContext,options?:{configuration?:Partial<NotificationWorkerConfiguration>;dependencies?:NotificationWorkerDependencies})=>{const engine=new NotificationWorkerEngine(bootstrap,options);if(options?.dependencies)engine.bindIntegrations(options.dependencies);return engine};
export const resetNotificationWorkerForTesting=()=>{/* stores are per-instance */};
