import type { CHANNELS } from "./paths.js";
export type Channel=(typeof CHANNELS)[number]; export type DeliveryStatus="queued"|"sending"|"sent"|"failed"|"retrying"|"scheduled";
export type ProviderRegistration={providerId:string;name:string;channel:Channel;validated:boolean;credentialRef?:CredentialRef;createdAt:string};
export type CredentialRef={credentialRefId:string;providerId:string;createdAt:string};
export type NotificationTemplate={templateId:string;name:string;channel:Channel;subject?:string;body:string;validated:boolean;createdAt:string};
export type NotificationMessage={messageId:string;channel:Channel;to:string;providerId?:string;templateId?:string;subject?:string;body:string;variables?:Record<string,unknown>;userId?:string;sendAt?:string;status:DeliveryStatus;attempts:number;createdAt:string};
export type QueueJob={jobId:string;messageId:string;attempts:number;availableAt:string;status:DeliveryStatus;createdAt:string};
export type DeliveryRecord={deliveryId:string;messageId:string;status:DeliveryStatus;attempt:number;timestamp:string;reason?:string};
export type UserPreference={preferenceId:string;userId:string;channel:Channel;enabled:boolean;updatedAt:string};
export type NotificationAuditEvent={eventId:string;event:string;timestamp:string;data:Record<string,unknown>};
export interface NotificationTransport { send(input:{providerId?:string;channel:Channel;to:string;subject?:string;body:string}):Promise<{success:boolean;reason?:string}>|{success:boolean;reason?:string} }
export type NotificationWorkerConfiguration={enabled:boolean;timeoutMs:number;maxRetries:number;backoffMs:number;neverReplaceWorkflowOrchestration:true;neverReplaceBusinessLogic:true;neverExposeCredentialsOrSecrets:true;neverFabricateDeliveryResults:true;neverImplementQ613OrLater:true;neverOverridePillowGrandKingApprovedArchitecture:true};
export type NotificationBuildReport={buildId:string;timestamp:string;platformId?:string;platformName:string;notificationProviders:ProviderRegistration[];templates:NotificationTemplate[];messagesSent:number;deliveryStatus:string;retryStatus:string;failedDeliveries:number;auditStatus:string;outstandingIssues:string[];confidenceScore:number;metadataVersion:"NTW-001-v1";buildStatus:"draft"|"in_progress"|"complete"|"failed";neverReplaceWorkflowOrchestration:true;neverReplaceBusinessLogic:true;neverExposeCredentialsOrSecrets:true;neverFabricateDeliveryResults:true;neverImplementQ613OrLater:true;neverOverridePillowGrandKingApprovedArchitecture:true;followApprovedRequirementsAndArchitecture:boolean;preserveCompleteTraceability:boolean;preserveNotificationAuditHistory:boolean;maskSensitiveValues:boolean;requirementsReportId?:string;architectureReportId?:string;factoryMissionId:"Q6-12";businessId?:string;businessObjective?:string;buildSteps:string[];selfReview:string;workerId:"wkr-notification-01";reportVersion:"NTW-RPT-v1";traceabilityRefs:string[];submittedToExecutiveReporting:boolean;executiveReportId?:string};
export type NotificationWorkerState={engineVersion:"PILLOW-NTW-001";missionId:"Q6-12";status:string;initializedAt:string|null;configuration:NotificationWorkerConfiguration;latestReport:NotificationBuildReport|null};
export type NotificationWorkerDependencies=Record<string,unknown>;
