import type { EmpireBootstrapContext } from "../bootstrap/types.js";
import { RepositoryReader } from "../bootstrap/repository-reader.js";
import { buildExecutiveEmpireDashboardConfiguration, type ExecutiveEmpireDashboardConfiguration } from "./configuration.js";
import { ExecutiveEmpireDashboardController } from "./executive-empire-dashboard-controller.js";
import { ExecutiveEmpireDashboardManager, type ExecutiveEmpireDashboardDependencies } from "./executive-empire-dashboard-manager.js";
import { EXECUTIVE_EMPIRE_DASHBOARD_SYSTEM_PATH } from "./paths.js";
import type { DashboardAnalysisInput, ExecutiveEmpireDashboardCockpitSnapshot, ExecutiveEmpireDashboardState } from "./types.js";
export type { ExecutiveEmpireDashboardDependencies };
export interface ExecutiveEmpireDashboardOptions { configuration?: Partial<ExecutiveEmpireDashboardConfiguration> }
export class ExecutiveEmpireDashboardEngine {
  private initializedAt: string | null = null; private readonly controller: ExecutiveEmpireDashboardController;
  constructor(private readonly bootstrap: EmpireBootstrapContext, dependencies: ExecutiveEmpireDashboardDependencies = {}, options: ExecutiveEmpireDashboardOptions = {}) { this.controller = new ExecutiveEmpireDashboardController(new ExecutiveEmpireDashboardManager(dependencies), buildExecutiveEmpireDashboardConfiguration(bootstrap.repositoryRoot, options.configuration)); }
  async initialize() { const doc = await new RepositoryReader(this.bootstrap.repositoryRoot).readText(EXECUTIVE_EMPIRE_DASHBOARD_SYSTEM_PATH); if (!doc?.includes("Executive Empire Dashboard")) throw new Error(`${EXECUTIVE_EMPIRE_DASHBOARD_SYSTEM_PATH} missing — X5-10 system doc required.`); this.controller.initialize(); this.initializedAt = new Date().toISOString(); return this.getState(); }
  getState(): ExecutiveEmpireDashboardState { if (!this.initializedAt) throw new Error("Executive Empire Dashboard not initialized. Call initialize() first."); const configuration = this.controller.getConfiguration(), engineRecord = this.getEngineRecord(), latestReport = this.controller.getLatestReport(), records = this.getDashboardRecords(); return { engineVersion: "PILLOW-EED-001", missionId: "X5-10", status: this.controller.getStatus(), initializedAt: this.initializedAt, configuration, latestReport, engineRecord, health: { status: engineRecord?.healthStatus ?? "standby", healthScore: engineRecord?.healthStatus === "healthy" ? 100 : engineRecord ? 70 : 50, engineEnabled: configuration.enabled, totalDashboardRecords: records.length, notes: ["Structural signals only; restricted enterprise information, credentials, and authentication tokens are never exposed."] } }; }
  connectExecutiveEmpireDashboard(input: Record<string, unknown> = {}) { return this.controller.connect(input); }
  aggregateEnterpriseWideKpis(input: DashboardAnalysisInput = {}) { return this.controller.run("aggregate_enterprise_kpis", input); } displayEnterpriseWideKpis(input: DashboardAnalysisInput = {}) { return this.aggregateEnterpriseWideKpis(input); }
  displayPortfolioPerformance(input: DashboardAnalysisInput = {}) { return this.controller.run("display_portfolio_performance", input); } displayCompanyPerformance(input: DashboardAnalysisInput = {}) { return this.controller.run("display_company_performance", input); } displayCapitalAllocationStatus(input: DashboardAnalysisInput = {}) { return this.controller.run("display_capital_allocation_status", input); } displayOpportunityPipeline(input: DashboardAnalysisInput = {}) { return this.controller.run("display_opportunity_pipeline", input); } displayInnovationPipeline(input: DashboardAnalysisInput = {}) { return this.controller.run("display_innovation_pipeline", input); } displayEnterpriseResilience(input: DashboardAnalysisInput = {}) { return this.controller.run("display_enterprise_resilience", input); } displaySelfImprovementProgress(input: DashboardAnalysisInput = {}) { return this.controller.run("display_self_improvement_progress", input); } displayExecutiveAlerts(input: DashboardAnalysisInput = {}) { return this.controller.run("display_executive_alerts", input); } displayStrategicRecommendations(input: DashboardAnalysisInput = {}) { return this.controller.run("display_strategic_recommendations", input); }
  refreshDashboardSnapshot(input: DashboardAnalysisInput = {}) { return this.controller.run("refresh_dashboard_snapshot", input); } buildDashboardSnapshot(input: DashboardAnalysisInput = {}) { return this.refreshDashboardSnapshot(input); } runDiagnostics() { return this.controller.diagnostics(); }
  getDashboardRecords() { return this.controller.getManager().getDashboardRecords(); } getRecommendations() { return this.controller.getManager().getRecommendations(); } getEngineRecord() { return this.controller.getManager().getEngineRecord(); }
  validateForSupervisorSync() { const state = this.getState(), decision = state.latestReport?.validation.decision ?? "partial", readinessScore = decision === "pass" ? 100 : decision === "partial" ? 70 : 40; return { valid: state.health.status !== "failed", health: readinessScore >= 75 ? "healthy" as const : readinessScore >= 50 ? "degraded" as const : "blocked" as const, readinessScore, notes: [`Engine status: ${state.status}`, `Dashboard records: ${state.health.totalDashboardRecords}`, ...state.health.notes] }; }
  getCockpitSnapshot(): ExecutiveEmpireDashboardCockpitSnapshot { const state = this.getState(), record = state.engineRecord; return { engineStatus: state.status, healthStatus: state.health.status, operationalState: record?.currentOperationalState ?? null, lastDecision: state.latestReport?.validation.decision ?? null, totalDashboardRecords: state.health.totalDashboardRecords, alertCount: this.getDashboardRecords().reduce((sum, record) => sum + record.executiveAlerts.length, 0), frameworkRegistered: Boolean(record?.frameworkModuleId), dependenciesConnected: Object.values(record?.dependencyPresence ?? {}).filter(Boolean).length, recentLogs: [] }; }
}
export function createExecutiveEmpireDashboardEngine(bootstrap: EmpireBootstrapContext, dependencies: ExecutiveEmpireDashboardDependencies = {}, options?: ExecutiveEmpireDashboardOptions) { return new ExecutiveEmpireDashboardEngine(bootstrap, dependencies, options); }
export function resetExecutiveEmpireDashboardForTesting() {}
