import type { StorefrontPreviewModel } from "@/lib/brain/store-execution/preview-types";
import type { StoreManufacturingData } from "@/lib/brain/store-execution/types";

export const COMMERCE_STORE_BUILD_STAGES = [
  { stage: "Catalog discovery", progress: 100, status: "complete" },
  { stage: "Brand manufacture", progress: 100, status: "complete" },
  { stage: "Store blueprint", progress: 72, status: "in_progress" },
  { stage: "Deploy preview", progress: 0, status: "pending" },
] as const;

export const COMMERCE_STORE_DEMO_DATA: StoreManufacturingData = {
  pipeline: {
    sessionId: "demo-session-nova",
    workspaceId: "demo-workspace",
    companyId: "nova-home",
    status: "in_progress",
    stages: [
      { stage: "Brand", moduleId: "brand", progress: 100, status: "complete" },
      { stage: "Portfolio", moduleId: "portfolio", progress: 100, status: "complete" },
      { stage: "Offer", moduleId: "offer", progress: 100, status: "complete" },
      { stage: "Blueprint", moduleId: "blueprint", progress: 72, status: "in_progress" },
      { stage: "Storefront", moduleId: "storefront", progress: 40, status: "in_progress" },
    ],
    ids: {
      brandId: "brand-nova",
      offerId: "offer-nova",
      pageId: "page-nova-home",
      storeId: "store-nova",
      storefrontId: "sf-nova",
      generatedStorefrontId: "gsf-nova",
      projectId: "proj-nova",
      productId: "prod-nova-hero",
    },
    summary: {
      brandName: "Nova Home",
      offerTitle: "Elevated everyday essentials",
      storeId: "store-nova",
      storefrontId: "sf-nova",
      projectId: "proj-nova",
      artifactCount: 6,
      overallConfidence: 78,
    },
    completedAt: "2026-06-21T10:00:00.000Z",
  },
  brand: {
    brandId: "brand-nova",
    brandName: "Nova Home",
    slogan: "Elevated essentials for modern living",
    niche: "Home & lifestyle",
    targetAudience: "Design-conscious homeowners",
    positioning: "Premium accessible",
    valueProposition: "Curated home products with boutique quality at scale.",
    recommendedProducts: ["Wireless ambient lamp", "Modular storage set", "Linen throw bundle"],
    confidence: 82,
  },
  portfolio: {
    brandId: "brand-nova",
    recommendedProducts: [],
    heroProducts: [
      { productId: "p1", displayName: "Ambient Lamp Pro", role: "hero" },
      { productId: "p2", displayName: "Modular Shelf System", role: "hero" },
    ],
    supportingProducts: [{ productId: "p3", displayName: "Linen Throw Set", role: "supporting" }],
    bundleProducts: [{ productId: "p4", displayName: "Starter Home Bundle", role: "bundle" }],
    portfolioScore: 88,
    confidence: 79,
  },
  offer: {
    offerId: "offer-nova",
    brandId: "brand-nova",
    productId: "prod-nova-hero",
    offerStyle: "Premium bundle",
    offerTitle: "Nova Home Starter Collection",
    headline: "Transform your space in one curated drop",
    valueProposition: "Hand-picked hero products with cohesive brand story and launch-ready pages.",
    keyBenefits: ["Fast time-to-market", "Brand-consistent catalog", "Demo-ready storefront"],
    keyFeatures: ["AI brand system", "Generated PDPs", "Preview routes"],
    callToAction: "Preview store",
    confidence: 76,
  },
  landingPage: {
    pageId: "page-nova-home",
    offerId: "offer-nova",
    brandId: "brand-nova",
    productId: "prod-nova-hero",
    pageTitle: "Nova Home — Launch",
    blueprint: { confidence: 74 },
    content: {
      heroCopy: "Elevated essentials for rooms that feel finished.",
      problemCopy: "Fragmented suppliers slow launch velocity.",
      solutionCopy: "EmpireAI manufactures brand, catalog, and storefront together.",
      benefitsCopy: "Cohesive design, faster go-live, demo-safe preview mode.",
      ctaCopy: "Shop the collection",
      confidence: 75,
    },
  },
  storeBlueprint: {
    storeId: "store-nova",
    brandId: "brand-nova",
    collectionPages: [{ id: "col-1" }],
    productPages: [{ id: "pdp-1" }, { id: "pdp-2" }],
    confidence: 72,
  },
  storePages: {
    storeId: "store-nova",
    brandId: "brand-nova",
    confidence: 74,
    pages: [
      {
        pageId: "page-home",
        route: "/",
        pageType: "HOME",
        title: "Nova Home",
        confidence: 80,
      },
      {
        pageId: "page-collection",
        route: "/collections/essentials",
        pageType: "COLLECTION",
        title: "Essentials Collection",
        confidence: 76,
      },
      {
        pageId: "page-product",
        route: "/products/ambient-lamp",
        pageType: "PRODUCT",
        title: "Ambient Lamp Pro",
        confidence: 78,
      },
    ],
  },
  storefront: {
    storefrontId: "sf-nova",
    storeId: "store-nova",
    brandId: "brand-nova",
    routes: [
      { path: "/", title: "Home", pageType: "HOME" },
      { path: "/collections/essentials", title: "Essentials", pageType: "COLLECTION" },
      { path: "/products/ambient-lamp", title: "Ambient Lamp", pageType: "PRODUCT" },
    ],
    assets: [],
    confidence: 77,
  },
  generatedCode: {
    generatedStorefrontId: "gsf-nova",
    storefrontId: "sf-nova",
    storeId: "store-nova",
    brandId: "brand-nova",
    generatedPages: [{ id: "page-home" }],
    generatedComponents: [{ id: "hero" }, { id: "product-grid" }],
    confidence: 71,
  },
  artifacts: {
    generatedStorefrontId: "gsf-nova",
    totalCount: 2,
    confidence: 73,
    artifacts: [
      {
        artifactId: "art-hero",
        filePath: "src/pages/index.tsx",
        fileType: "tsx",
        preview: "export default function Home() { ... }",
        confidence: 74,
        metadata: { module: "landing" },
      },
      {
        artifactId: "art-product",
        filePath: "src/pages/products/ambient-lamp.tsx",
        fileType: "tsx",
        preview: "export default function ProductPage() { ... }",
        confidence: 72,
        metadata: { module: "pdp" },
      },
    ],
  },
  materializedProject: {
    projectId: "proj-nova",
    generatedStorefrontId: "gsf-nova",
    projectStructure: {
      rootDirectory: "stores/nova-home",
      framework: "Next.js",
      files: ["src/pages/index.tsx", "src/pages/products/ambient-lamp.tsx", "package.json"],
    },
    materializedFiles: [
      {
        artifactId: "art-hero",
        relativePath: "src/pages/index.tsx",
        content: "// Demo storefront page — preview only",
        fileType: "tsx",
      },
    ],
    buildMetadata: {
      platform: "demo",
      buildCommand: "npm run build",
      startCommand: "npm run start",
      outputDirectory: ".next",
    },
    confidence: 70,
  },
};

export const COMMERCE_STORE_PREVIEW_MODEL: StorefrontPreviewModel = {
  storeName: "Nova Home",
  brandSlogan: "Elevated essentials for modern living",
  projectId: "proj-nova",
  projectRoot: "stores/nova-home",
  framework: "Generated storefront (demo)",
  storeId: "store-nova",
  defaultRoute: "/",
  routes: [
    { label: "Home", route: "/", pageType: "HOME", pageId: "page-home" },
    {
      label: "Essentials",
      route: "/collections/essentials",
      pageType: "COLLECTION",
      pageId: "page-collection",
    },
    {
      label: "Ambient Lamp",
      route: "/products/ambient-lamp",
      pageType: "PRODUCT",
      pageId: "page-product",
    },
  ],
  pages: [
    {
      pageId: "page-home",
      route: "/",
      pageType: "HOME",
      title: "Nova Home",
      confidence: 80,
      metadata: { description: "Demo storefront home page" },
      sections: [
        {
          sectionId: "hero-1",
          sectionType: "HERO",
          headline: "Elevated essentials for modern living",
          body: "Curated home products manufactured by EmpireAI — preview mode only.",
          bullets: [],
          callToAction: "Shop the collection",
          order: 1,
        },
        {
          sectionId: "grid-1",
          sectionType: "PRODUCT_GRID",
          headline: "Featured products",
          body: "",
          bullets: ["Ambient Lamp Pro", "Modular Shelf System", "Linen Throw Set"],
          callToAction: null,
          order: 2,
        },
      ],
    },
    {
      pageId: "page-collection",
      route: "/collections/essentials",
      pageType: "COLLECTION",
      title: "Essentials Collection",
      confidence: 76,
      sections: [
        {
          sectionId: "col-hero",
          sectionType: "HERO",
          headline: "Essentials Collection",
          body: "Starter catalog for Nova Home launch.",
          bullets: [],
          callToAction: "View products",
          order: 1,
        },
      ],
    },
    {
      pageId: "page-product",
      route: "/products/ambient-lamp",
      pageType: "PRODUCT",
      title: "Ambient Lamp Pro",
      confidence: 78,
      sections: [
        {
          sectionId: "pdp-hero",
          sectionType: "HERO",
          headline: "Ambient Lamp Pro",
          body: "Warm, dimmable lighting for living spaces.",
          bullets: ["Wireless", "Rechargeable", "3 tone presets"],
          callToAction: "Add to cart",
          order: 1,
        },
      ],
    },
  ],
};
