import { readFileSync } from "node:fs"; import { join } from "node:path"; import type { EmpireBootstrapContext } from "../bootstrap/types.js"; import { buildDeploymentWorkerConfiguration } from "./configuration.js"; import { InMemoryDeploymentExecutor } from "./deployment-executor.js"; import { InMemoryHealthProbe } from "./health-probe.js"; import { DEPLOYMENT_WORKER_SYSTEM_PATH,DPW_INTEGRATION_TARGETS,ENVIRONMENTS } from "./paths.js"; import type { ApprovalGate,DeploymentBuildReport,DeploymentExecutor,DeploymentMethod,DeploymentPackage,DeploymentRecord,DeploymentWorkerConfiguration,DeploymentWorkerDependencies,DeploymentWorkerState,Environment,EnvironmentConfig,HealthCheckResult,HealthProbe,RollbackRecord } from "./types.js";
const id=(p:string)=>`${p}-${crypto.randomUUID()}`,now=()=>new Date().toISOString();
export class DeploymentWorkerEngine {
 readonly config:DeploymentWorkerConfiguration; private initializedAt:string|null=null; private deps:DeploymentWorkerDependencies={}; private executor:DeploymentExecutor=new InMemoryDeploymentExecutor(); private probe:HealthProbe=new InMemoryHealthProbe(); private requirementsReportId?:string; private architectureReportId?:string;
 readonly environments=new Map<Environment,EnvironmentConfig>(); readonly packages=new Map<string,DeploymentPackage>(); readonly deployments=new Map<string,DeploymentRecord>(); readonly healthResults:HealthCheckResult[]=[]; readonly rollbacks:RollbackRecord[]=[]; readonly approvals:ApprovalGate[]=[]; readonly history:DeploymentRecord[]=[]; readonly events:Array<{eventId:string;event:string;timestamp:string;data:Record<string,unknown>}>=[]; readonly reports:DeploymentBuildReport[]=[];
 constructor(private bootstrap:{repositoryRoot:string}|EmpireBootstrapContext,options:{configuration?:Partial<DeploymentWorkerConfiguration>}={}){this.config=buildDeploymentWorkerConfiguration(bootstrap.repositoryRoot,options.configuration); for(const environment of ENVIRONMENTS)this.registerEnvironment({environment,configValid:true,secretsVerified:true,validated:true})}
 private audit(event:string,data:Record<string,unknown>={}){this.events.push({eventId:id("dpw-evt"),event,timestamp:now(),data})} private checked(input:Record<string,unknown>){const result=this.validate(input);if(!result.valid)throw new Error(result.issues.join("; "))}
 async initialize(){let text="";try{text=readFileSync(join(this.bootstrap.repositoryRoot,DEPLOYMENT_WORKER_SYSTEM_PATH),"utf8")}catch{throw new Error(`${DEPLOYMENT_WORKER_SYSTEM_PATH} missing`)}if(!text.includes("Deployment Worker"))throw new Error("Deployment Worker governance document is invalid");this.initializedAt=now();this.audit("initialized",{doctrine:"PILLOW-DPW-001"});return this.getState()}
 bindIntegrations(deps:DeploymentWorkerDependencies={}){this.deps={...this.deps,...deps};return this.deps} connect(deps:DeploymentWorkerDependencies={}){return this.bindIntegrations(deps)}
 getState():DeploymentWorkerState{return {engineVersion:"PILLOW-DPW-001",missionId:"Q6-14",status:this.initializedAt?"ready":"idle",initializedAt:this.initializedAt,configuration:this.config,latestReport:this.reports.at(-1)??null}}
 validate(input:Record<string,unknown>={}){const forbidden=["replaceTesting","replaceCertification","fabricateDeploymentSuccess","bypassApprovalGates","deployUnvalidatedBuild","implementQ615OrLater","overridePillow","overrideGrandKing","overrideApprovedArchitecture"];const issues=forbidden.filter(k=>input[k]===true).map(k=>`${k} is forbidden`);if(input.missionId&&input.missionId!=="Q6-14")issues.push("missionId must be Q6-14");return {valid:issues.length===0,issues}}
 diagnostics(){return {valid:this.validate().valid,packages:this.packages.size,deployments:this.deployments.size,targets:[...DPW_INTEGRATION_TARGETS]}} getCockpitSnapshot(){return {missionId:"Q6-14",status:this.getState().status,workerId:"wkr-deployment-01",packages:this.packages.size,deployments:this.deployments.size,neverFabricateSuccessfulDeploymentResults:true,neverBypassApprovalGates:true,neverDeployUnvalidatedBuilds:true,neverImplementQ615OrLater:true}} validateForSupervisorSync(){return {valid:!!this.initializedAt,health:this.initializedAt?"healthy":"blocked",readinessScore:this.initializedAt?100:0,notes:[`Q6-14 ${this.getState().status}`]}}
 receiveApprovedRequirementsReports(input:Record<string,unknown>={}){this.checked(input);this.requirementsReportId=String(input.reportId??id("dpw-bld"));return {buildId:id("dpw-bld"),requirementsReportId:this.requirementsReportId}} receiveApprovedRequirementsReport(input:Record<string,unknown>={}){return this.receiveApprovedRequirementsReports(input)}
 receiveApprovedArchitectureReports(input:Record<string,unknown>={}){this.checked(input);this.architectureReportId=String(input.reportId??id("dpw-bld"));return {buildId:id("dpw-bld"),architectureReportId:this.architectureReportId}} receiveApprovedArchitectureReport(input:Record<string,unknown>={}){return this.receiveApprovedArchitectureReports(input)}
 registerEnvironment(input:EnvironmentConfig){this.checked(input);if(!ENVIRONMENTS.includes(input.environment))throw new Error("Unknown environment");const item={...input};this.environments.set(item.environment,item);return item}
 createPackage(input:{packageId?:string;applicationVersion:string;platformId?:string;artifactRefs?:string[];checksum?:string;testingEvidenceId?:string;validatedBuild?:boolean}){this.checked(input);if(!input.applicationVersion)throw new Error("applicationVersion is required");const item:DeploymentPackage={packageId:input.packageId??id("dpw-pkg"),applicationVersion:input.applicationVersion,platformId:input.platformId??"empireai",artifactRefs:input.artifactRefs??[],checksum:input.checksum??`sha256:${crypto.randomUUID()}`,testingEvidenceId:input.testingEvidenceId,validatedBuild:input.validatedBuild===true,createdAt:now()};this.packages.set(item.packageId,item);this.audit("package_created",{packageId:item.packageId});return item}
 packageDeploymentArtifacts(input:{applicationVersion?:string;platformId?:string;artifactRefs?:string[];testingEvidenceId?:string}={}){return this.createPackage({applicationVersion:input.applicationVersion??"0.0.0",platformId:input.platformId,artifactRefs:input.artifactRefs,testingEvidenceId:input.testingEvidenceId})} markBuildValidated(input:{packageId:string;testingEvidenceId:string}){const pkg=this.packages.get(input.packageId);if(!pkg)throw new Error("Package not found");if(!input.testingEvidenceId)throw new Error("Approved testing evidence is required");pkg.validatedBuild=true;pkg.testingEvidenceId=input.testingEvidenceId;return pkg}
 validateReadiness(input:{packageId:string;environment:Environment}){const pkg=this.packages.get(input.packageId),env=this.environments.get(input.environment),issues:string[]=[];if(!pkg)issues.push("package missing");if(pkg&&!pkg.validatedBuild)issues.push("validated build required");if(pkg&&!pkg.testingEvidenceId)issues.push("approved testing evidence required");if(!env?.configValid)issues.push("environment configuration invalid");if(!env?.secretsVerified)issues.push("secret references not verified");if(!env?.validated)issues.push("environment not validated");return {ready:issues.length===0,issues}} validateDeploymentReadiness(input:{packageId:string;environment:Environment}){return this.validateReadiness(input)}
 requestDeploymentApproval(input:{deploymentId?:string;packageId?:string;environment:Environment;approverRole?:string}){const gate:ApprovalGate={gateId:id("dpw-env"),...input,status:"pending",createdAt:now()};this.approvals.push(gate);return gate} approveDeployment(input:{gateId?:string;deploymentId?:string;decision:"approved"|"rejected"}){const gate=this.approvals.find(g=>(input.gateId&&g.gateId===input.gateId)||(input.deploymentId&&g.deploymentId===input.deploymentId));if(!gate)throw new Error("Approval gate not found");gate.status=input.decision;gate.decidedAt=now();return gate}
 setDeploymentExecutor(executor:DeploymentExecutor){this.executor=executor} setHealthProbe(probe:HealthProbe){this.probe=probe} configureExecutorSuccess(input:{key:string;success:boolean}){if(!(this.executor instanceof InMemoryDeploymentExecutor))throw new Error("InMemoryDeploymentExecutor required");this.executor.configure(input.key,input.success)} configureHealthSuccess(input:{key:string;success:boolean}){if(!(this.probe instanceof InMemoryHealthProbe))throw new Error("InMemoryHealthProbe required");this.probe.configure(input.key,input.success)}
 async deploy(input:{packageId:string;environment:Environment;method?:DeploymentMethod;deploymentId?:string}){const readiness=this.validateReadiness(input);if(!readiness.ready)throw new Error(readiness.issues.join("; "));const deploymentId=input.deploymentId??id("dpw-dep");if(input.environment==="production"&&!this.approvals.some(g=>g.status==="approved"&&g.environment==="production"&&(g.deploymentId===deploymentId||g.packageId===input.packageId)))throw new Error("Production deployment requires explicit approved gate");const pkg=this.packages.get(input.packageId)!;const record:DeploymentRecord={deploymentId,packageId:pkg.packageId,platformId:pkg.platformId,environment:input.environment,method:input.method??"standard",status:"deploying",startedAt:now()};this.deployments.set(deploymentId,record);const result=await this.executor.execute(record,pkg);record.status=result.success?"success":"failed";record.executorEvidence=result.evidence;record.completedAt=now();record.durationMs=Date.parse(record.completedAt)-Date.parse(record.startedAt);this.history.push({...record});this.audit("deployment_executed",{deploymentId,status:record.status});return record}
 supportEnvironmentDeployments(input:{packageId:string;environment:Environment;method?:DeploymentMethod}){return this.deploy(input)} executeDeploymentWorkflows(input:{packageId:string;environment:Environment;method?:DeploymentMethod}){return this.deploy(input)} validateDeploymentSuccess(input:{deploymentId:string}){const record=this.deployments.get(input.deploymentId);return {success:record?.status==="success",deployment:record}}
 async runHealthChecks(input:{deploymentId:string}){const record=this.deployments.get(input.deploymentId);if(!record)throw new Error("Deployment not found");const outcome=await this.probe.probe(record);const result:HealthCheckResult={healthId:id("dpw-hlt"),deploymentId:record.deploymentId,healthy:outcome.healthy,checkedAt:now(),evidence:outcome.evidence};this.healthResults.push(result);return result} monitorPostDeploymentHealth(input:{deploymentId:string}){return this.runHealthChecks(input)} markHealthy(input:{deploymentId:string}){const latest=this.healthResults.filter(x=>x.deploymentId===input.deploymentId).at(-1);if(!latest?.healthy)throw new Error("Explicit healthy probe result required");return latest}
 async rollback(input:{deploymentId:string;reason?:string}){const record=this.deployments.get(input.deploymentId);if(!record)throw new Error("Deployment not found");const previous=[...this.history].reverse().find(x=>x.environment===record.environment&&x.platformId===record.platformId&&x.status==="success"&&x.deploymentId!==record.deploymentId);const outcome=previous&&this.executor.rollback?await this.executor.rollback(record,previous):{success:false,evidence:"No prior successful deployment or rollback executor"};const rollback:RollbackRecord={rollbackId:id("dpw-rbk"),deploymentId:record.deploymentId,previousDeploymentId:previous?.deploymentId,status:outcome.success?"success":"failed",reason:input.reason,createdAt:now(),evidence:outcome.evidence};if(outcome.success){record.status="rolled_back";this.history.push({...record})}this.rollbacks.push(rollback);return rollback} performControlledRollback(input:{deploymentId:string;reason?:string}){return this.rollback(input)}
 maintainDeploymentHistory(){return this.getHistory()} produceDeploymentEvidence(){return {evidenceId:id("dpw-evt"),deployments:this.getDeployments(),health:this.getHealthResults(),rollbacks:this.getRollbacks()}}
 getEnvironments(){return [...this.environments.values()]} getPackages(){return [...this.packages.values()]} getDeployments(){return [...this.deployments.values()]} getHealthResults(deploymentId?:string){return this.healthResults.filter(x=>!deploymentId||x.deploymentId===deploymentId)} getRollbacks(){return [...this.rollbacks]} getApprovals(){return [...this.approvals]} getHistory(){return [...this.history]} getAuditEvents({limit=50}:{limit?:number}={}){return this.events.slice(-limit)}
 produceDeploymentBuildReport(input:{platformId?:string;platformName?:string;businessId?:string;businessObjective?:string}={}){const latest=this.getDeployments().at(-1),pkg=latest&&this.packages.get(latest.packageId),health=latest?this.getHealthResults(latest.deploymentId):[],report:DeploymentBuildReport={buildId:id("dpw-bld"),deploymentId:latest?.deploymentId,latestDeploymentId:latest?.deploymentId,timestamp:now(),platformId:input.platformId??latest?.platformId,platformName:input.platformName??"EmpireAI",targetEnvironment:latest?.environment,applicationVersion:pkg?.applicationVersion,deploymentMethod:latest?.method,deploymentStatus:latest?.status,healthCheckResults:health,rollbackStatus:this.rollbacks.at(-1)?.status,deploymentDuration:latest?.durationMs,auditStatus:"recorded",outstandingIssues:[...this.getDeployments().filter(x=>x.status==="failed").map(x=>`Deployment ${x.deploymentId} failed`),...health.filter(x=>!x.healthy).map(x=>`Health check ${x.healthId} failed`)],confidenceScore:latest?.status==="success"&&health.at(-1)?.healthy?1:0,metadataVersion:"DPW-001-v1",buildStatus:"complete",neverReplaceTesting:true,neverReplaceCertification:true,neverFabricateSuccessfulDeploymentResults:true,neverBypassApprovalGates:true,neverDeployUnvalidatedBuilds:true,neverImplementQ615OrLater:true,neverOverridePillowGrandKingApprovedArchitecture:true,followApprovedRequirementsAndArchitecture:true,preserveCompleteDeploymentTraceability:true,preserveDeploymentAuditHistory:true,deployOnlyValidatedBuilds:true,requirementsReportId:this.requirementsReportId,architectureReportId:this.architectureReportId,factoryMissionId:"Q6-14",businessId:input.businessId,businessObjective:input.businessObjective,buildSteps:["validated deployment readiness","executed explicit deployment adapter","recorded explicit health probe outcomes"],selfReview:"Success is recorded only from deployment executor and health probe outcomes.",workerId:"wkr-deployment-01",reportVersion:"DPW-RPT-v1",traceabilityRefs:[...this.deployments.keys()],submittedToExecutiveReporting:false};this.reports.push(report);return report}
 submitReport(input:{platformId?:string;platformName?:string}={}){const report=this.produceDeploymentBuildReport(input);const runtime=(this.deps.executiveReportingRuntime??this.deps.executive_reporting_runtime) as {submitWorkerReport?:(v:unknown)=>{records?:Array<{reportId?:string}>}}|undefined;const result=runtime?.submitWorkerReport?.({missionId:"Q6-14",report});report.executiveReportId=result?.records?.[0]?.reportId;report.submittedToExecutiveReporting=!!report.executiveReportId;return report} list(){return [...this.reports]}
}
export { DeploymentWorkerEngine as DeploymentWorker };
export const createDeploymentWorker=(bootstrap:EmpireBootstrapContext,options?:{configuration?:Partial<DeploymentWorkerConfiguration>;dependencies?:DeploymentWorkerDependencies})=>{const engine=new DeploymentWorkerEngine(bootstrap,options);if(options?.dependencies)engine.bindIntegrations(options.dependencies);return engine};
export const resetDeploymentWorkerForTesting=()=>{};
