import type { DEPLOYMENT_METHODS, ENVIRONMENTS } from "./paths.js";
export type Environment=(typeof ENVIRONMENTS)[number]; export type DeploymentMethod=(typeof DEPLOYMENT_METHODS)[number]; export type DeploymentStatus="pending"|"deploying"|"success"|"failed"|"rolled_back"; export type BuildStatus="draft"|"in_progress"|"complete"|"failed";
export type EnvironmentConfig={environment:Environment;baseUrl?:string;configValid:boolean;secretsVerified:boolean;validated:boolean};
export type DeploymentPackage={packageId:string;applicationVersion:string;platformId:string;artifactRefs:string[];checksum:string;testingEvidenceId?:string;validatedBuild:boolean;createdAt:string};
export type DeploymentRecord={deploymentId:string;packageId:string;platformId:string;environment:Environment;method:DeploymentMethod;status:DeploymentStatus;startedAt:string;completedAt?:string;durationMs?:number;executorEvidence?:string};
export type HealthCheckResult={healthId:string;deploymentId:string;healthy:boolean;checkedAt:string;evidence?:string};
export type RollbackRecord={rollbackId:string;deploymentId:string;previousDeploymentId?:string;status:"success"|"failed";reason?:string;createdAt:string;evidence?:string};
export type ApprovalGate={gateId:string;deploymentId?:string;packageId?:string;environment:Environment;approverRole?:string;status:"pending"|"approved"|"rejected";createdAt:string;decidedAt?:string};
export type DeploymentBuildReport={buildId:string;deploymentId?:string;latestDeploymentId?:string;timestamp:string;platformId?:string;platformName:string;targetEnvironment?:Environment;applicationVersion?:string;deploymentMethod?:DeploymentMethod;deploymentStatus?:DeploymentStatus;healthCheckResults:HealthCheckResult[];rollbackStatus?:string;deploymentDuration?:number;auditStatus:string;outstandingIssues:string[];confidenceScore:number;metadataVersion:"DPW-001-v1";buildStatus:BuildStatus;neverReplaceTesting:true;neverReplaceCertification:true;neverFabricateSuccessfulDeploymentResults:true;neverBypassApprovalGates:true;neverDeployUnvalidatedBuilds:true;neverImplementQ615OrLater:true;neverOverridePillowGrandKingApprovedArchitecture:true;followApprovedRequirementsAndArchitecture:boolean;preserveCompleteDeploymentTraceability:boolean;preserveDeploymentAuditHistory:boolean;deployOnlyValidatedBuilds:true;requirementsReportId?:string;architectureReportId?:string;factoryMissionId:"Q6-14";businessId?:string;businessObjective?:string;buildSteps:string[];selfReview:string;workerId:"wkr-deployment-01";reportVersion:"DPW-RPT-v1";traceabilityRefs:string[];submittedToExecutiveReporting:boolean;executiveReportId?:string};
export interface DeploymentExecutor { execute(record:DeploymentRecord, packageInfo:DeploymentPackage):Promise<{success:boolean;evidence?:string}>|{success:boolean;evidence?:string}; rollback?(record:DeploymentRecord, previous:DeploymentRecord):Promise<{success:boolean;evidence?:string}>|{success:boolean;evidence?:string} }
export interface HealthProbe { probe(record:DeploymentRecord):Promise<{healthy:boolean;evidence?:string}>|{healthy:boolean;evidence?:string} }
export type DeploymentWorkerConfiguration={enabled:boolean;timeoutMs:number;neverReplaceTesting:true;neverReplaceCertification:true;neverFabricateSuccessfulDeploymentResults:true;neverBypassApprovalGates:true;neverDeployUnvalidatedBuilds:true;neverImplementQ615OrLater:true;neverOverridePillowGrandKingApprovedArchitecture:true};
export type DeploymentWorkerState={engineVersion:"PILLOW-DPW-001";missionId:"Q6-14";status:string;initializedAt:string|null;configuration:DeploymentWorkerConfiguration;latestReport:DeploymentBuildReport|null};
export type DeploymentWorkerDependencies=Record<string,unknown>;
