import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {AssuranceControlPlane,inspectControlPlaneMonitor} from '../../assurance/control-plane.mjs';
const w='synthetic:acceptance';
function fixture(t,authority='A',overrides={}){const root=fs.mkdtempSync(path.join(os.tmpdir(),'assurance-cp-'));let now=100000,calls=0;const book={version:'v1',authority,capability:'scheduler',timeoutMs:100,maxAttempts:2,cooldownMs:1000,execute:async()=>{calls++;return {action:'resume'};},verify:async()=>({healthy:true}),...overrides};const cp=new AssuranceControlPlane({root,now:()=>now,revision:'abc123',runbooks:{resume:book}});t.after(()=>{try{cp.close();}catch{}fs.rmSync(root,{recursive:true,force:true});});return {cp,root,book,calls:()=>calls,advance:n=>now+=n,now:()=>now};}
const fault={id:'scheduler-progress',capability:'scheduler',status:'DEGRADED',classification:'JOB_TIMEOUT',summary:'Scheduler stalled',runbookId:'resume',synthetic:true};
test('normal observation autonomously detects and verifies recovery, dedup and immutable evidence',async t=>{const {cp,calls}=fixture(t);const i=cp.observe(w,fault);cp.observe(w,fault);assert.equal(cp.snapshot(w).incidents.length,1);assert.equal(cp.snapshot(w).incidents[0].recurrence,2);await cp.tick(w);assert.equal(calls(),1);assert.equal(cp.snapshot(w).incidents[0].status,'RECOVERED');await cp.tick(w);assert.equal(calls(),1);assert.throws(()=>cp.db.exec('DELETE FROM cp_events'),/IMMUTABLE_EVENT/);assert.ok(cp.snapshot(w).events.some(e=>e.type==='RECOVERY_RESULT'));assert.equal(i.status,'DETECTED');});
test('B requires exact durable approval and follows through once; replay conflict denied',async t=>{const {cp,calls}=fixture(t,'B');cp.observe(w,fault);await cp.tick(w);assert.equal(calls(),0);const a=cp.snapshot(w).approvals[0];const command={id:'decision1',type:'approve',approvalId:a.id};assert.equal((await cp.command(w,'owner',command)).status,'ACCEPTED');assert.equal(calls(),1);await cp.command(w,'owner',command);assert.equal(calls(),1);await assert.rejects(cp.command(w,'other',command),/REPLAY/);assert.equal(cp.snapshot(w).approvals[0].consumed,true);});
test('expired and rejected approval cannot execute',async t=>{const {cp,calls,advance}=fixture(t,'B');cp.observe(w,fault);await cp.tick(w);const a=cp.snapshot(w).approvals[0];advance(3600001);assert.equal((await cp.command(w,'owner',{id:'expired',type:'approve',approvalId:a.id})).status,'ACTION_DENIED');await cp.tick(w);assert.equal(calls(),0);});
test('deployment lease defers repair; fenced finish triggers safe recovery',async t=>{const {cp,calls}=fixture(t);const r=await cp.command(w,'owner',{id:'lease1',type:'lease_begin',expectedRevision:'abc123',scope:['backend'],ttlMs:10000});cp.observe(w,fault);await cp.tick(w);assert.equal(calls(),0);assert.equal((await cp.command(w,'owner',{id:'wrong',type:'lease_finish',leaseId:r.lease.id,fence:999})).status,'ACTION_DENIED');await cp.command(w,'owner',{id:'finish',type:'lease_finish',leaseId:r.lease.id,fence:r.lease.fence});assert.equal(calls(),1);});
test('unknown outcome preserved across process replacement and never blindly replayed',async t=>{const {cp,root,book,calls,now}=fixture(t,'A',{execute:async()=>{throw Error('lost response');}});cp.observe(w,fault);await cp.tick(w);assert.equal(cp.snapshot(w).recoveries[0].status,'UNKNOWN');cp.close();const reopened=new AssuranceControlPlane({root,now,revision:'abc123',runbooks:{resume:book}});await reopened.tick(w);assert.equal(reopened.snapshot(w).recoveries.length,1);assert.equal(reopened.snapshot(w).incidents[0].attempts,1);reopened.close();});
test('partial recovery verification failure respects cooldown and attempt breaker',async t=>{const {cp,calls,advance}=fixture(t,'A',{verify:async()=>({healthy:false,reason:'Queue stalled'})});cp.observe(w,fault);await cp.tick(w);await cp.tick(w);assert.equal(calls(),1);advance(1001);await cp.tick(w);advance(1001);await cp.tick(w);assert.equal(calls(),2);assert.equal(cp.snapshot(w).incidents[0].limitation,'Recovery attempt budget exhausted');});
test('pause retains observation; monitoring freshness, isolation and prohibited recovery',async t=>{const {cp,calls,advance}=fixture(t,'C');assert.throws(()=>cp.observe('production',fault),/SYNTHETIC/);cp.observe(w,fault);await cp.command(w,'owner',{id:'pause',type:'pause'});await cp.tick(w);assert.equal(calls(),0);assert.equal(cp.snapshot('other').incidents.length,0);advance(90001);assert.equal(cp.snapshot(w).status,'STALE');assert.equal(cp.snapshot(w).paused.paused,true);});
test('concurrent recovery ticks execute only once',async t=>{let release;const gate=new Promise(r=>release=r);const {cp,calls}=fixture(t,'A',{execute:async()=>{await gate;return {executed:true};}});cp.observe(w,fault);const first=cp.tick(w);await Promise.resolve();await cp.tick(w);release();await first;assert.equal(cp.snapshot(w).recoveries.length,1);assert.equal(cp.snapshot(w).incidents[0].attempts,1);});
test('rejected decision remains denied without approval spam',async t=>{const {cp,calls}=fixture(t,'B');cp.observe(w,fault);await cp.tick(w);const a=cp.snapshot(w).approvals[0];await cp.command(w,'owner',{id:'reject',type:'reject',approvalId:a.id});await cp.tick(w);assert.equal(calls(),0);assert.equal(cp.snapshot(w).approvals.length,1);assert.equal((await cp.command(w,'owner',{id:'late-approve',type:'approve',approvalId:a.id})).status,'ACTION_DENIED');});
test('expired lease remains blocking until trusted live deployment reconciliation',async t=>{const {cp,calls,advance,now}=fixture(t);const lease=(await cp.command(w,'owner',{id:'start',type:'lease_begin',expectedRevision:'abc123',scope:['backend'],ttlMs:1000})).lease;advance(1001);cp.observe(w,fault);await cp.tick(w);assert.equal(calls(),0);assert.equal((await cp.command(w,'owner',{id:'unverified',type:'lease_reconcile',leaseId:lease.id,fence:lease.fence,evidence:{noActiveChanges:true}})).status,'ACTION_DENIED');cp.deploymentVerifier=async()=>({revision:'abc123',noActiveChanges:true,verifiedAt:now(),evidenceId:'platform-receipt',workspace:w,ownerId:'owner',leaseId:lease.id,fence:lease.fence});assert.equal((await cp.command(w,'owner',{id:'verified',type:'lease_reconcile',leaseId:lease.id,fence:lease.fence})).status,'ACCEPTED');assert.equal(calls(),1);});
test('unknown recovery reconciles completed state without repeat execution',async t=>{let executions=0;const {cp}=fixture(t,'A',{execute:async()=>{executions++;throw Error('response lost');},reconcile:async()=>({completed:true,evidenceId:'existing-result'})});cp.observe(w,fault);await cp.tick(w);await cp.tick(w);assert.equal(executions,1);assert.equal(cp.snapshot(w).incidents[0].status,'RECOVERED');assert.equal(cp.snapshot(w).recoveries.length,1);});
test('owner approval bound to revision cannot authorize a new release',async t=>{const {cp,root,book,now}=fixture(t,'B');cp.observe(w,fault);await cp.tick(w);const a=cp.snapshot(w).approvals[0];cp.close();const newer=new AssuranceControlPlane({root,now,revision:'new456',runbooks:{resume:book}});assert.equal((await newer.command(w,'owner',{id:'wrong-revision',type:'approve',approvalId:a.id})).status,'ACTION_DENIED');newer.close();});
test('deferred approvals can be revisited without losing exact scope',async t=>{const {cp,calls}=fixture(t,'B');cp.observe(w,fault);await cp.tick(w);const a=cp.snapshot(w).approvals[0];await cp.command(w,'owner',{id:'defer',type:'defer',approvalId:a.id});assert.equal(calls(),0);await cp.command(w,'owner',{id:'approve-deferred',type:'approve',approvalId:a.id});assert.equal(calls(),1);assert.equal(cp.snapshot(w).approvals.length,1);});
test('expired approval creates a new scoped request while original decision evidence survives',async t=>{const {cp,calls,advance}=fixture(t,'B');cp.observe(w,fault);await cp.tick(w);const first=cp.snapshot(w).approvals[0];advance(3600001);await cp.tick(w);const approvals=cp.snapshot(w).approvals;assert.equal(approvals.length,2);assert.equal(approvals.find(a=>a.id===first.id).decision,'EXPIRED');const next=approvals.find(a=>a.decision==='PENDING');assert.notEqual(first.id,next.id);assert.equal((await cp.command(w,'owner',{id:'old-approval',type:'approve',approvalId:first.id})).status,'ACTION_DENIED');await cp.command(w,'owner',{id:'renewed-approval',type:'approve',approvalId:next.id});assert.equal(calls(),1);assert.ok(cp.snapshot(w).events.some(e=>e.type==='APPROVAL_EXPIRED'));});

test('independent inspector detects lost primary heartbeat without hiding failure and records restoration',async t=>{const {cp,advance}=fixture(t);cp.heartbeat(w);advance(90001);assert.equal(inspectControlPlaneMonitor(cp,w).fresh,false);assert.equal(cp.snapshot(w).monitor.fresh,false);assert.ok(cp.get(w,'heartbeat','watchdog'));const lost=cp.snapshot(w).incidents.find(i=>i.classification==='MONITORING_COVERAGE_LOST');assert.equal(lost.status,'DETECTED');cp.heartbeat(w);assert.equal(inspectControlPlaneMonitor(cp,w).fresh,true);assert.equal(cp.get(w,'incident',lost.id).status,'RECOVERED');assert.ok(cp.snapshot(w).events.some(e=>e.type==='FUNCTION_VERIFIED'));});
