import test from 'node:test';
import assert from 'node:assert/strict';
import {createDeploymentVerifier} from '../../assurance/deployment-verifier.mjs';
import {AssuranceControlPlane} from '../../assurance/control-plane.mjs';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
const revision='a'.repeat(40),workspace='ws_empire_1';
const env={EMPIRE_RUNTIME_PROFILE:'LOCKED_COMMISSIONING_V1',ASSURANCE_RAILWAY_PROJECT_TOKEN:'test-railway',ASSURANCE_VERCEL_READ_TOKEN:'test-vercel',RAILWAY_PROJECT_ID:'project',RAILWAY_ENVIRONMENT_ID:'production',RAILWAY_SERVICE_ID:'backend',RAILWAY_DEPLOYMENT_ID:'railway-current',RAILWAY_GIT_COMMIT_SHA:revision,ASSURANCE_VERCEL_PROJECT_ID:'frontend',ASSURANCE_VERCEL_TEAM_ID:'team',ASSURANCE_VERCEL_PRODUCTION_HOST:'example.invalid'};
const lease={id:'lease1',ownerId:'owner',status:'ACTIVE',expiresAt:100,fence:7,scope:['backend','frontend']};
const context={workspace,ownerId:'owner',lease,revision};
function network(overrides={}){const calls=[];const fetcher=async(url,options)=>{calls.push({url,options});let body;if(url.includes('railway')&&JSON.parse(options.body).query.includes('LeaseTokenScope'))body={data:{projectToken:{projectId:'project',environmentId:'production'}}};else if(url.includes('railway'))body={data:{deployments:{edges:[{node:{id:'railway-current',status:'SUCCESS',meta:{commitHash:revision}}}],pageInfo:{hasNextPage:false,endCursor:null}}}};else if(url.includes('/v13/'))body={id:'vercel-current',readyState:'READY',target:'production',projectId:'frontend',alias:['example.invalid'],meta:{githubCommitSha:'b'.repeat(40)}};else body={deployments:[{uid:'vercel-current',state:'READY'}],pagination:{next:null}};body=overrides.body?.(url,body)??body;return {ok:overrides.ok!==false,text:async()=>JSON.stringify(body)};};return {calls,fetcher};}
test('authenticated fixed-origin reads bind complete platform evidence to the current owner lease',async()=>{const n=network();const result=await createDeploymentVerifier({env,fetcher:n.fetcher,now:()=>1000})(context);assert.equal(result.noActiveChanges,true);assert.equal(result.fence,7);assert.equal(result.workspace,workspace);assert.equal(result.leaseId,lease.id);assert.equal(result.revision,revision);assert.match(result.evidenceId,/^[a-f0-9]{64}$/);assert.equal(n.calls.length,4);assert.equal(n.calls[0].options.headers['Project-Access-Token'],'test-railway');assert.ok(n.calls.slice(2).every(c=>c.options.method==='GET'));assert.ok(n.calls.every(c=>c.options.redirect==='error'));assert.ok(!JSON.stringify(result).includes('test-railway'));});
for(const [name,change] of [
 ['missing credentials',e=>delete e.ASSURANCE_RAILWAY_PROJECT_TOKEN],
 ['wrong profile',e=>e.EMPIRE_RUNTIME_PROFILE='OPEN'],
 ['wrong runtime revision',e=>e.RAILWAY_GIT_COMMIT_SHA='c'.repeat(40)]
])test(name+' makes no network call',async()=>{const e={...env};change(e);const n=network();await assert.rejects(createDeploymentVerifier({env:e,fetcher:n.fetcher,now:()=>1000})(context));assert.equal(n.calls.length,0);});
for(const [name,patch] of [['other workspace',{workspace:'other'}],['other owner',{ownerId:'attacker'}],['unexpired',{lease:{...lease,expiresAt:2000}}]])test(name+' denied before platform reads',async()=>{const n=network();await assert.rejects(createDeploymentVerifier({env,fetcher:n.fetcher,now:()=>1000})({...context,...patch}));assert.equal(n.calls.length,0);});
for(const mode of ['building','wrong-revision','missing-page-info','graphql-error','wrong-frontend','queued-frontend','redirect-or-401'])test(mode+' cannot certify reconciliation',async()=>{const n=network({ok:mode!=='redirect-or-401',body:(url,b)=>{if(url.includes('railway')&&b.data?.deployments){if(mode==='graphql-error')return {errors:[{message:'denied'}]};if(mode==='building')b.data.deployments.edges.push({node:{id:'competing',status:'BUILDING'}});if(mode==='wrong-revision')b.data.deployments.edges[0].node.meta.commitHash='c'.repeat(40);if(mode==='missing-page-info')delete b.data.deployments.pageInfo;}else if(url.includes('/v13/')&&mode==='wrong-frontend')b.projectId='other';else if(url.includes('/v7/')&&mode==='queued-frontend')b.deployments.push({uid:'competing',state:'QUEUED'});return b;}});await assert.rejects(createDeploymentVerifier({env,fetcher:n.fetcher,now:()=>1000})(context));});
test('slow reads do not refresh stale evidence timestamps',async()=>{let clock=1000;const n=network();const fetcher=async(...args)=>{clock+=5000;return n.fetcher(...args);};await assert.rejects(createDeploymentVerifier({env,fetcher,now:()=>clock})(context),/STALE/);});
function control(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'lease-verifier-'));let clock=10000;const cp=new AssuranceControlPlane({root,now:()=>clock,revision});t.after(()=>{cp.close();fs.rmSync(root,{recursive:true,force:true});});return {cp,advance:()=>clock+=2000,now:()=>clock};}
test('existing finish control reconciles expired owner lease, advances fence, preserves audit and prevents replay',async t=>{const {cp,advance,now}=control(t);const l=(await cp.command(workspace,'owner',{id:'begin',type:'lease_begin',expectedRevision:revision,scope:['backend'],ttlMs:1000})).lease;advance();cp.deploymentVerifier=async()=>({workspace,ownerId:'owner',leaseId:l.id,fence:l.fence,revision,noActiveChanges:true,verifiedAt:now(),evidenceId:'trusted'});const cmd={id:'finish',type:'lease_finish',leaseId:l.id,fence:l.fence};const r=await cp.command(workspace,'owner',cmd);assert.equal(r.status,'ACCEPTED');assert.equal(r.lease.status,'RECONCILED');assert.equal(r.lease.fence,l.fence+1);assert.deepEqual(await cp.command(workspace,'owner',cmd),r);assert.equal((await cp.command(workspace,'owner',{...cmd,id:'replay'})).status,'ACTION_DENIED');assert.ok(cp.snapshot(workspace).events.some(e=>e.body.id==='finish'));});
for(const mode of ['forged','stale','future','missing-time','workspace','fence','owner'])test('control rejects '+mode+' verification and retains blocking lease',async t=>{const {cp,advance,now}=control(t);const l=(await cp.command(workspace,'owner',{id:'begin',type:'lease_begin',expectedRevision:revision,scope:['backend'],ttlMs:1000})).lease;advance();const evidence={workspace,ownerId:'owner',leaseId:l.id,fence:l.fence,revision,noActiveChanges:true,verifiedAt:now(),evidenceId:'trusted'};if(mode==='missing-time')delete evidence.verifiedAt;if(mode==='stale')evidence.verifiedAt-=30001;if(mode==='future')evidence.verifiedAt++;if(mode==='workspace')evidence.workspace='other';if(mode==='fence')evidence.fence++;if(mode!=='forged')cp.deploymentVerifier=async()=>evidence;const r=await cp.command(workspace,mode==='owner'?'attacker':'owner',{id:'reconcile',type:'lease_reconcile',leaseId:l.id,fence:l.fence,evidence});assert.equal(r.status,'ACTION_DENIED');assert.equal(cp.get(workspace,'lease','production').status,'ACTIVE');assert.equal((await cp.command(workspace,'owner',{id:'collision',type:'lease_begin',expectedRevision:revision,scope:['backend'],ttlMs:1000})).status,'ACTION_DENIED');});

test('concurrent identical commands preserve the first immutable receipt',async t=>{const {cp,advance,now}=control(t);const l=(await cp.command(workspace,'owner',{id:'begin',type:'lease_begin',expectedRevision:revision,scope:['backend'],ttlMs:1000})).lease;advance();let release;const gate=new Promise(r=>release=r);cp.deploymentVerifier=async()=>{await gate;return {workspace,ownerId:'owner',leaseId:l.id,fence:l.fence,revision,noActiveChanges:true,verifiedAt:now(),evidenceId:'trusted'};};const cmd={id:'finish',type:'lease_finish',leaseId:l.id,fence:l.fence};const a=cp.command(workspace,'owner',cmd),b=cp.command(workspace,'owner',cmd);release();const results=await Promise.all([a,b]);assert.deepEqual(results[0],results[1]);assert.equal(results[0].status,'ACCEPTED');assert.equal(cp.snapshot(workspace).events.filter(e=>e.body.id==='finish').length,1);});

test('provider diagnostics retain only stage and HTTP code, never response secrets',async()=>{
 const secret='private-provider-response';
 await assert.rejects(createDeploymentVerifier({env,now:()=>1000,fetcher:async()=>({ok:false,status:403,text:async()=>secret})})(context),e=>{
  assert.deepEqual(e.diagnostic,{stage:'RAILWAY_AUTH',code:'HTTP_403'});
  assert.ok(!JSON.stringify(e).includes(secret));return true;
 });
});
test('failed verification records bounded diagnostic and preserves lease without leaking thrown text',async t=>{
 const {cp,advance}=control(t);const l=(await cp.command(workspace,'owner',{id:'begin',type:'lease_begin',expectedRevision:revision,scope:['backend'],ttlMs:1000})).lease;advance();
 cp.deploymentVerifier=async()=>{throw Object.assign(Error('secret'),{diagnostic:{stage:'VERCEL_ALIAS',code:'HTTP_403',headers:'secret'}});};
 const r=await cp.command(workspace,'owner',{id:'diagnostic',type:'lease_finish',leaseId:l.id,fence:l.fence});
 assert.deepEqual(r.verificationFailure,{stage:'VERCEL_ALIAS',code:'HTTP_403'});assert.equal(r.status,'ACTION_DENIED');assert.equal(cp.get(workspace,'lease','production').status,'ACTIVE');assert.ok(!JSON.stringify(r).includes('secret'));
 cp.deploymentVerifier=async()=>{throw Object.assign(Error('secret'),{diagnostic:{stage:'secret',code:'secret'}});};
 const r2=await cp.command(workspace,'owner',{id:'redacted',type:'lease_finish',leaseId:l.id,fence:l.fence});assert.deepEqual(r2.verificationFailure,{stage:'VERIFIER',code:'UNCLASSIFIED'});assert.ok(!JSON.stringify(r2).includes('secret'));
});

for(const [name,scope] of [['wrong project',{projectId:'other',environmentId:'production'}],['wrong environment',{projectId:'project',environmentId:'other'}],['missing scope',null]])test(name+' blocks before deployment reads',async()=>{
 const n=network({body:(_url,b)=>b.data?.projectToken?{data:{projectToken:scope}}:b});
 await assert.rejects(createDeploymentVerifier({env,fetcher:n.fetcher,now:()=>1000})(context),e=>{assert.deepEqual(e.diagnostic,{stage:'RAILWAY_AUTH',code:'TOKEN_SCOPE_MISMATCH'});return true;});
 assert.equal(n.calls.length,1);
});
for(const [message,code,expected] of [['Not Authorized','INTERNAL_SERVER_ERROR','AUTHORIZATION_DENIED'],['secret-invalid-field','GRAPHQL_VALIDATION_FAILED','GRAPHQL_VALIDATION_FAILED'],['secret-provider-error','INTERNAL_SERVER_ERROR','INTERNAL_SERVER_ERROR'],['secret-unknown','secret-code','API_ERROR']])test('GraphQL classification '+expected+' retains no provider text',async()=>{
 const n=network({body:()=>({errors:[{message,extensions:{code,token:'secret-token'}}]})});
 await assert.rejects(createDeploymentVerifier({env,fetcher:n.fetcher,now:()=>1000})(context),e=>{assert.deepEqual(e.diagnostic,{stage:'RAILWAY_AUTH',code:expected});assert.ok(!JSON.stringify(e).includes('secret'));return true;});
});
test('scope-authorized deployment denial is distinguished and persisted without changing the lease',async t=>{
 const {cp,advance,now}=control(t);const l=(await cp.command(workspace,'owner',{id:'begin',type:'lease_begin',expectedRevision:revision,scope:['backend'],ttlMs:1000})).lease;advance();
 const n=network({body:(_url,b)=>b.data?.deployments?{errors:[{message:'Not Authorized',extensions:{code:'INTERNAL_SERVER_ERROR'}}]}:b});
 cp.deploymentVerifier=createDeploymentVerifier({env,fetcher:n.fetcher,now});
 const r=await cp.command(workspace,'owner',{id:'denied',type:'lease_finish',leaseId:l.id,fence:l.fence});
 assert.deepEqual(r.verificationFailure,{stage:'RAILWAY_READ',code:'AUTHORIZATION_DENIED'});assert.equal(n.calls.length,2);assert.equal(cp.get(workspace,'lease','production').status,'ACTIVE');assert.equal(cp.get(workspace,'lease','production').fence,l.fence);
});
