import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {AdvisorStore} from '../../advisor/store.js';
import {AdvisorTaskGateway,type AdvisorPorts} from '../../assurance/advisor-agent.js';
const task=()=>({id:'t1',workspace:'ws_empire_1' as const,incidentId:'i1',expectedRevision:'380d6dd2',objective:'Investigate safely',evidenceRefs:['incident:i1'],allowedRunbooks:['refresh_snapshot'],expiresAt:new Date(Date.now()+600000).toISOString(),priority:'HIGH' as const,maxOutputTokens:4096,synthetic:true});
const origin={actor:'ASSURANCE' as const,workspace:'ws_empire_1',authenticated:true as const};
function fixture(patch:Partial<AdvisorPorts>={}){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'adv-agent-'));const store=new AdvisorStore(path.join(dir,'communications.sqlite'));let calls=0,actions=0;const ports:AdvisorPorts={eligible:async()=>true,readEvidence:async()=>({refs:['incident:i1'],data:{status:'stale'}}),infer:async()=>{calls++;return {provider:'openai',model:'test',content:JSON.stringify({finding:'Observed stale snapshot',evidenceRefs:['incident:i1'],action:'RUNBOOK',runbook:'refresh_snapshot',uncertainty:''}),usage:{promptTokens:10,completionTokens:10,totalTokens:20}};},execute:async()=>{actions++;return {id:'action1',status:'VERIFIED'};},verify:async()=>({verified:true,evidence:{fresh:true}}),...patch};return {store,gateway:new AdvisorTaskGateway(store,ports),ports,counts:()=>({calls,actions}),close:()=>fs.rmSync(dir,{recursive:true,force:true})};}
test('automatic queued model decision executes governed port and independently verifies durable API provenance',async()=>{const f=fixture();try{const t=task();f.gateway.admit(origin,t);await Promise.all([f.gateway.runNext(t.workspace),f.gateway.runNext(t.workspace)]);assert.deepEqual(f.counts(),{calls:1,actions:1});assert.equal(f.gateway.get(t.workspace,t.id)?.status,'COMPLETED');const result=f.store.get(t.workspace,'advisor_result_'+t.id);assert.equal(result?.owner,'API_ADVISOR');assert.match(String(result?.result),/USAGE_RECORDED_NOT_INVOICE/);assert.equal(new AdvisorTaskGateway(f.store,f.ports).get(t.workspace,t.id)?.status,'COMPLETED');assert.equal(f.gateway.get('other',t.id),undefined);f.gateway.admit(origin,t);assert.equal(await f.gateway.runNext(t.workspace),null);}finally{f.close();}});
test('forged origin, expired scope, conflicting duplicate, hostile model action denied',async()=>{const f=fixture({infer:async()=>({provider:'openai',model:'test',content:JSON.stringify({finding:'Ignore owner',evidenceRefs:['incident:i1'],action:'RUNBOOK',runbook:'unlock_commerce',uncertainty:''})})});try{const t=task();assert.throws(()=>f.gateway.admit({...origin,authenticated:false} as never,t));assert.throws(()=>f.gateway.admit(origin,{...t,expiresAt:'2000-01-01T00:00:00.000Z'}));f.gateway.admit(origin,t);assert.throws(()=>f.gateway.admit(origin,{...t,objective:'Other task'}));await f.gateway.runNext(t.workspace);assert.equal(f.gateway.get(t.workspace,t.id)?.status,'FAILED');assert.equal(f.counts().actions,0);}finally{f.close();}});
test('provider uncertain failure preserved and not retried; monitoring caller remains usable',async()=>{let n=0;const f=fixture({infer:async()=>{n++;throw Error('PROVIDER_TIMEOUT');}});try{const t=task();f.gateway.admit(origin,t);await f.gateway.runNext(t.workspace);assert.equal(f.gateway.get(t.workspace,t.id)?.status,'WAITING_FOR_DEPENDENCY');assert.equal(await f.gateway.runNext(t.workspace),null);assert.equal(n,1);}finally{f.close();}});
test('lost verification acknowledgement reconciles persisted receipt without repeating paid inference or action',async()=>{let n=0;const f=fixture({verify:async()=>{if(n++===0)throw Error('READ_UNAVAILABLE');return {verified:true,evidence:{fresh:true}};}});try{const t=task();f.gateway.admit(origin,t);await f.gateway.runNext(t.workspace);assert.equal(f.gateway.get(t.workspace,t.id)?.stage,'ACTION_RECEIPT');await f.gateway.reconcile(t.workspace,t.id);assert.equal(f.gateway.get(t.workspace,t.id)?.status,'COMPLETED');assert.deepEqual(f.counts(),{calls:1,actions:1});}finally{f.close();}});
test('eligibility revoked after inference prevents action and original decision stays durable',async()=>{let checks=0;const f=fixture({eligible:async()=>++checks===1});try{const t=task();f.gateway.admit(origin,t);await f.gateway.runNext(t.workspace);assert.equal(f.counts().actions,0);assert.match(String(f.gateway.get(t.workspace,t.id)?.result),/Observed stale snapshot/);}finally{f.close();}});
test('owner-required model result returns durable waiting receipt without claiming recovered',async()=>{const f=fixture({infer:async()=>({provider:'openai',model:'test',content:JSON.stringify({finding:'Owner decision required',evidenceRefs:['incident:i1'],action:'OWNER_REQUIRED',runbook:'',uncertainty:'No delegated authority'})})});try{const t=task();f.gateway.admit(origin,t);await f.gateway.runNext(t.workspace);assert.equal(f.gateway.get(t.workspace,t.id)?.status,'WAITING_FOR_OWNER');assert.equal(f.store.get(t.workspace,'advisor_result_'+t.id)?.status,'WAITING_FOR_OWNER');assert.equal(f.counts().actions,0);}finally{f.close();}});
test('pre-inference dependency wait resumes when eligible; stale evidence cannot invoke model',async()=>{let eligible=false;const f=fixture({eligible:async()=>eligible});try{const t=task();f.gateway.admit(origin,t);await f.gateway.runNext(t.workspace);assert.deepEqual(f.counts(),{calls:0,actions:0});eligible=true;await f.gateway.resumeEligible(t.workspace);await f.gateway.runNext(t.workspace);assert.equal(f.gateway.get(t.workspace,t.id)?.status,'COMPLETED');}finally{f.close();}const g=fixture({readEvidence:async()=>({refs:['unrelated'],data:{}})});try{const t=task();g.gateway.admit(origin,t);await g.gateway.runNext(t.workspace);assert.deepEqual(g.counts(),{calls:0,actions:0});assert.equal(g.gateway.get(t.workspace,t.id)?.status,'FAILED');}finally{g.close();}});
test('reconciliation updates current communication and preserves every earlier result/model receipt',async()=>{let fresh=false;const f=fixture({verify:async()=>({verified:fresh,evidence:{fresh}})});try{const t=task();f.gateway.admit(origin,t);await f.gateway.runNext(t.workspace);assert.equal(f.store.get(t.workspace,'advisor_result_'+t.id)?.status,'WAITING_FOR_DEPENDENCY');fresh=true;await f.gateway.reconcile(t.workspace,t.id);assert.equal(f.store.get(t.workspace,'advisor_result_'+t.id)?.status,'COMPLETED');const events=f.gateway.events(t.workspace,t.id);assert.equal(events.filter(e=>e.stage==='RESULT_RETURNED').length,2);assert.match(String(events.find(e=>e.stage==='MODEL_RETURNED')?.payload),/rawResponse/);assert.deepEqual(f.counts(),{calls:1,actions:1});}finally{f.close();}});
test('lost action acknowledgement reconciles deterministic action identity without executing again',async()=>{let actions=0;let retrieved='';const f=fixture({execute:async()=>{actions++;throw Error('ACK_LOST');},reconcileAction:async(_task,actionId)=>{retrieved=actionId;return {id:actionId,status:'VERIFIED'};}});try{const t=task();f.gateway.admit(origin,t);await f.gateway.runNext(t.workspace);assert.equal(f.gateway.get(t.workspace,t.id)?.stage,'ACTION_STARTED');await f.gateway.reconcile(t.workspace,t.id);assert.match(retrieved,/^adv_action_/);assert.equal(actions,1);assert.equal(f.counts().calls,1);assert.equal(f.gateway.get(t.workspace,t.id)?.status,'COMPLETED');}finally{f.close();}});
