import test from 'node:test';
import assert from 'node:assert/strict';
import {assessAdmission,checkToolContract,assessWorkflowReceipt} from '../../assurance/functional-probes.js';
import {investigationOutputFormat} from '../../intelligence/model-output.js';
const now=Date.parse('2026-10-08T12:00:00Z');
test('pricing expiry warnings preserve provider attribution and admission window',()=>{const pricing=[{provider:'openai',expiresAt:'2026-10-09T00:00:00Z',source:'review-record'},{provider:'google',expiresAt:'2026-10-07T00:00:00Z',source:'review-record'}];assert.equal(assessAdmission({now,pricing,configured:['openai']}).status,'DEGRADED');assert.equal(assessAdmission({now,pricing,configured:['google']}).status,'BLOCKED');assert.equal(assessAdmission({now,pricing,configured:['openai'],windowEnd:now-1}).status,'BLOCKED');assert.equal(assessAdmission({now,pricing:[],configured:['openai']}).status,'BLOCKED');});
test('actual contract detects query, numeric, enum and collection drift without inference',()=>{assert.equal(checkToolContract().status,'HEALTHY');for(const mutate of [(s:any)=>s.subject.properties.query.anyOf[0].maxLength=121,(s:any)=>s.requestLimit.maximum=13,(s:any)=>s.capabilities.maxItems=5,(s:any)=>s.subject.properties.marketplace.enum.push('INVALID')]){const f:any=structuredClone(investigationOutputFormat('plan'));mutate(f.schema.properties.jobs.items.properties);assert.equal(checkToolContract(f).status,'BLOCKED');}});
test('successful paid output survives downstream failure without reinference',()=>{const r=assessWorkflowReceipt({requestId:'r1',status:'FAILED_FATAL',modelOutputDigest:'digest',accountingRef:'call1',handoff:'FAILED'});assert.equal(r.status,'DEGRADED');assert.equal((r.evidence as any).repeatInference,false);assert.equal((r.evidence as any).reuseCompletedOutput,true);});
test('claimed completion cannot replace durable response and closure evidence',()=>{assert.equal(assessWorkflowReceipt({requestId:'r1',status:'COMPLETED',missionState:'COMPLETE'}).status,'DEGRADED');assert.equal(assessWorkflowReceipt({requestId:'r1',status:'COMPLETED',responsePersisted:true,evidenceReturned:true,missionState:'COMPLETE',acceptanceRefs:['independent-readback']}).status,'HEALTHY');});
