import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {reconcileSources,reconciliationHash,rebuildReconciliation,verifyReconciliation,pillowReconciliationContext,type ReconciliationSources} from '../../assurance/evidence-reconciliation.js';
const w='ws_empire_1',rid='pcr_27fb1ed5ddb24f5a';
function fixture():ReconciliationSources{const answer='EVIDENCE-INSUFFICIENT. Engineering persistence and independent readback not yet verified.';return {missions:[{id:'EMPIREAI-CANDIDATE-001-FOLLOWUP',status:'COMPLETE',requestId:rid,predecessors:['pcr_9a70c5d827a746b3'],assessment:{answer,sha256:reconciliationHash(answer),requestId:rid,at:'2026-10-08T05:14:34.374Z',evidenceIds:['ev_1']},closure:{at:'2026-10-08T05:16:16.610Z',advisorReadback:{requestId:rid,assessmentHash:reconciliationHash(answer),attestedBy:'AUTHENTICATED_OWNER'},birth:'NOT_BORN',commerce:'LOCKED'}}],requests:[{requestId:rid,status:'COMPLETED',updatedAt:'2026-10-08T05:14:35.000Z',finalResult:{message:answer}},{requestId:'pcr_9a70c5d827a746b3',status:'FAILED_FATAL',failureClass:'BRAIN_FATAL'}],memory:[{id:'decision_1',request:rid,belief:answer,recordedAt:'2026-10-08T05:14:35.000Z',origin:{authenticity:'MODEL_GENERATED_CLAIM'}}],evidence:[{id:'ev_1',observedAt:'2026-10-08T05:13:53.000Z',authenticity:'LIVE_PROVIDER'}],accounting:{[rid]:[{requestKey:'key1',records:[{reservedMicroUsd:100,estimatedMicroUsd:30,invoiceActualMicroUsd:null}]}]}};}
test('Candidate001 later technical closure coexists with unchanged insufficient assessment, failures and unknown invoices',()=>{const s=fixture(),before=JSON.stringify(s),r=reconcileSources(w,s),i=r.investigations[0]!;assert.equal(i.commercial.status,'EVIDENCE_INSUFFICIENT');assert.equal(i.technicalWorkflow.status,'COMPLETE');assert.equal(i.durableResponse.status,'VERIFIED');assert.equal(i.independentReadback.status,'COMPLETED_OWNER_ATTESTED');assert.equal(i.providerInvoices.settledMicroUsd,null);assert.equal(i.internalAccounting.estimatedMicroUsd,30);assert.equal(i.predecessors[0].status,'FAILED_FATAL');assert.equal(i.predecessors[0].failureClass,'BRAIN_FATAL');assert.equal(i.locks.birth,'NOT_BORN');assert.equal(i.locks.commerce,'LOCKED');assert.equal(JSON.stringify(s),before);assert.equal(r.conflicts.length,0);});
test('unbound or earlier closure cannot supersede; missing evidence produces stable durable incident key',()=>{const s=fixture();s.missions[0]!.closure.advisorReadback.assessmentHash='bad';s.evidence=[];const r=reconcileSources(w,s);assert.equal(r.investigations[0]!.technicalWorkflow.status,'UNVERIFIED');assert.equal(r.conflicts.length,2);assert.deepEqual(r.conflicts,reconcileSources(w,s).conflicts);});
test('actual supported Pillow context reads materialized durable sources; restart, corruption repair, source change and workspace isolation',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'reconcile-')),dir=path.join(root,'commissioning');fs.mkdirSync(dir);const s=fixture();const put=(file:string,sql:string,insert:string,values:any[][])=>{const db=new DatabaseSync(path.join(dir,file));db.exec(sql);for(const v of values)db.prepare(insert).run(...v);db.close();};
 put('intelligence.sqlite','CREATE TABLE objects(workspace TEXT,kind TEXT,id TEXT,body TEXT)','INSERT INTO objects VALUES(?,?,?,?)', [...s.missions.map(m=>[w,'investigations',m.id,JSON.stringify(m)]),...s.evidence.map(e=>[w,'evidence',e.id,JSON.stringify(e)])]);
 put('pillow-request-receipts.sqlite','CREATE TABLE receipts(workspace TEXT,request TEXT,body TEXT)','INSERT INTO receipts VALUES(?,?,?)',s.requests.map(r=>[w,r.requestId,JSON.stringify(r)]));put('pillow-institutional.sqlite','CREATE TABLE records(workspace TEXT,kind TEXT,id TEXT,body TEXT)','INSERT INTO records VALUES(?,?,?,?)',s.memory.map(r=>[w,'EXPERIENCE',r.id,JSON.stringify(r)]));
 const before=fs.readFileSync(path.join(dir,'intelligence.sqlite'));const oldRoot=process.env.RAILWAY_VOLUME_MOUNT_PATH,oldProfile=process.env.EMPIRE_RUNTIME_PROFILE;try{process.env.RAILWAY_VOLUME_MOUNT_PATH=root;process.env.EMPIRE_RUNTIME_PROFILE='LOCKED_COMMISSIONING_V1';assert.equal(verifyReconciliation(root,w).status,'MISSING');rebuildReconciliation(root,w,'test-revision');assert.equal(verifyReconciliation(root,w).healthy,true);assert.equal(pillowReconciliationContext(w).investigations[0].technicalWorkflow.status,'COMPLETE');assert.equal(pillowReconciliationContext('other_workspace').investigations.length,0);fs.writeFileSync(path.join(dir,'reconciliation-'+w+'.json'),'broken');assert.equal(verifyReconciliation(root,w).healthy,false);assert.equal(pillowReconciliationContext(w).source,'VERIFIED_LOCAL_SOURCE_FALLBACK');rebuildReconciliation(root,w);assert.equal(verifyReconciliation(root,w).healthy,true);assert.deepEqual(fs.readFileSync(path.join(dir,'intelligence.sqlite')),before);const changed=new DatabaseSync(path.join(dir,'intelligence.sqlite'));changed.prepare("UPDATE objects SET body=? WHERE kind='evidence'").run(JSON.stringify({...s.evidence[0],quality:['new observation']}));changed.close();assert.equal(verifyReconciliation(root,w).status,'STALE');rebuildReconciliation(root,w);assert.equal(verifyReconciliation(root,w).healthy,true);}finally{if(oldRoot===undefined)delete process.env.RAILWAY_VOLUME_MOUNT_PATH;else process.env.RAILWAY_VOLUME_MOUNT_PATH=oldRoot;if(oldProfile===undefined)delete process.env.EMPIRE_RUNTIME_PROFILE;else process.env.EMPIRE_RUNTIME_PROFILE=oldProfile;fs.rmSync(root,{recursive:true,force:true});}});
test('Candidate001 exact live consultation keys correlate both ledger calls and exclude unrelated calls',async()=>{
 const {readMissionAccounting}=await import('../../assurance/evidence-reconciliation.js');
 // Keys independently read from production Mission Ledger on 2026-10-08; amounts below are synthetic test values.
 const keys=['6a5c21e154aac26c45960566dd213fdf884498644f29c3003ddc6a3c68630f65','b04422047f5ed71108543d6c242fde14b6b7f0ee8a8659b14b30af429947bf23'];
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'reconcile-cost-'));fs.mkdirSync(path.join(root,'commissioning'));const file=path.join(root,'commissioning','openai-october-2026.sqlite');const db=new DatabaseSync(file);
 try{db.exec('CREATE TABLE calls(id TEXT,timestamp TEXT,model TEXT,status TEXT,reserved_micro_usd INTEGER,estimated_micro_usd INTEGER,invoice_actual_micro_usd INTEGER,usage_json TEXT); CREATE TABLE call_providers(call_id TEXT,provider TEXT,request_key TEXT); PRAGMA application_id=1162430793; PRAGMA user_version=1;');for(const [i,k] of [...keys,'c'.repeat(64)].entries()){db.prepare('INSERT INTO calls VALUES(?,?,?,?,?,?,?,?)').run('call'+i,'2026-10-08T05:14:34.374Z','gpt-6.1-sol','settled_estimate',100,30,null,'{"input_tokens":10}');db.prepare('INSERT INTO call_providers VALUES(?,?,?)').run('call'+i,'openai',k);}db.close();fs.writeFileSync(file+'.initialized','test');const m=fixture().missions[0]!;m.assessment.provenance={requestKey:keys[1],consultations:keys.map(requestKey=>({requestKey,provider:'openai',model:'gpt-6.1-sol'}))};const before=fs.readFileSync(file),r=readMissionAccounting(root,w,m);assert.equal(r.length,2);assert.equal(r.flatMap(x=>x.records).length,2);assert.deepEqual(r.map(x=>x.requestKey),keys);assert.equal(r[0]!.records[0].invoiceActualMicroUsd,null);assert.deepEqual(fs.readFileSync(file),before);m.assessment.requestId='unbound';assert.equal(readMissionAccounting(root,w,m).length,1);assert.equal(readMissionAccounting(root,w,m)[0]!.requestKey,keys[0]);}finally{try{db.close();}catch{}fs.rmSync(root,{recursive:true,force:true});}
});
