import assert from 'node:assert/strict';import {test} from 'node:test';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {InstitutionalMemory} from '../../institutional-memory/store.js';import {readSafety} from '../../institutional-memory/safety.js';import {GovernedCommerceStore} from '../../runtime/commerce-runtime/governed/store.js';import {GovernedCommerceEngine} from '../../runtime/commerce-runtime/governed/engine.js';import {enforceOwnerSafety} from '../../runtime/commerce-runtime/governed/safety-admission.js';import {acceptanceScenario} from '../../runtime/commerce-runtime/governed/scenario.js';
test('15 guards stay unknown without evidence; owner policy fences and actual governed admission consume pause/limits without unlocking',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'work7-safety-')),store=new GovernedCommerceStore(':memory:');try{const memory=new InstitutionalMemory(path.join(root,'memory.sqlite')),now=Date.now(),scenario=acceptanceScenario('ws','owner',now),engine=new GovernedCommerceEngine(store,()=>now,(a,c,s)=>enforceOwnerSafety(memory,store,a,c,s,now));
 const before=readSafety(memory,'ws',{commerceAvailable:false});assert.equal(before.guards.length,15);assert.ok(before.guards.every(g=>g.status==='UNKNOWN'));assert.equal(before.controls.limits.perOrder,null);
 for(let i=0;i<5;i++)engine.execute(scenario.steps[i]!.actor,{id:'s'+i,missionId:'mission',expectedVersion:i,command:scenario.steps[i]!.command});
 const policy={action:'safety_policy',id:'pause',expectedVersion:0,confirmation:true,limits:{currency:'SGD',perOrder:50,daily:100,aggregate:100},breakers:{supplierPurchases:true,listingPublication:true,priceInventory:true},reason:'Owner explicitly confirms emergency pause'};memory.ownerCommand('ws','owner',policy);assert.equal(memory.ownerCommand('ws','owner',policy).created,false);assert.throws(()=>memory.ownerCommand('ws','owner',{...policy,id:'stale'}),/VERSION/);assert.throws(()=>memory.ownerCommand('ws','owner',{...policy,id:'no-confirm',expectedVersion:1,confirmation:false}));
 const prepare={id:'s5',missionId:'mission',expectedVersion:5,command:scenario.steps[5]!.command};assert.throws(()=>engine.execute(scenario.steps[5]!.actor,prepare),/OWNER_PURCHASES_PAUSED/);assert.equal(store.history('ws','mission').length,5);
 const paused=readSafety(memory,'ws',{commerceAvailable:true,missions:store.missions('ws')});assert.equal(paused.controls.version,1);assert.equal(paused.guards.find(g=>g.id==='circuit-breakers')!.status,'TRIPPED');assert.equal(memory.get('ws','pause').version,1);assert.equal(paused.externalEffects,0);
 memory.ownerCommand('ws','owner',{...policy,id:'resume-limited',expectedVersion:1,limits:{currency:'SGD',perOrder:1,daily:100,aggregate:100},breakers:{supplierPurchases:false,listingPublication:false,priceInventory:false}});assert.throws(()=>engine.execute(scenario.steps[5]!.actor,prepare),/OWNER_ORDER_LIMIT_EXCEEDED/);assert.equal(readSafety(memory,'ws',{commerceAvailable:true}).controls.effectivePauses.supplierPurchases,true,'resume cannot bypass global lock');
 memory.ownerCommand('ws','owner',{...policy,id:'resume-known',expectedVersion:2,breakers:{supplierPurchases:false,listingPublication:false,priceInventory:false}});const priorState=structuredClone(store.history('ws','mission').at(-1)!.state) as any;priorState.orders['order-fixture'].order.currency='USD';assert.throws(()=>enforceOwnerSafety(memory,store,scenario.actors.EXECUTOR!,prepare.command,priorState,now),/SAFETY_FX_UNVERIFIED/);const receipt=engine.execute(scenario.steps[5]!.actor,prepare);assert.equal(receipt.classification,'SYNTHETIC');assert.equal(receipt.externalEffects,0);assert.equal(readSafety(memory,'other',{commerceAvailable:false}).controls.version,0);
 const second=acceptanceScenario('ws','owner',now);second.order.orderId='second-order';for(let i=0;i<5;i++)engine.execute(second.steps[i]!.actor,{id:'second-'+i,missionId:'second',expectedVersion:i,command:second.steps[i]!.command});const secondPrepare={id:'second-prepare',missionId:'second',expectedVersion:5,command:{type:'prepare' as const,orderId:'second-order',offer:second.candidate.offer}};
 memory.ownerCommand('ws','owner',{...policy,id:'daily-bound',expectedVersion:3,limits:{currency:'SGD',perOrder:50,daily:30,aggregate:100},breakers:{supplierPurchases:false,listingPublication:false,priceInventory:false}});assert.throws(()=>engine.execute(second.actors.EXECUTOR!,secondPrepare),/OWNER_DAILY_LIMIT_EXCEEDED/);
 memory.ownerCommand('ws','owner',{...policy,id:'aggregate-bound',expectedVersion:4,limits:{currency:'SGD',perOrder:50,daily:100,aggregate:30},breakers:{supplierPurchases:false,listingPublication:false,priceInventory:false}});assert.throws(()=>engine.execute(second.actors.EXECUTOR!,secondPrepare),/OWNER_AGGREGATE_LIMIT_EXCEEDED/);
 memory.ownerCommand('ws','owner',{...policy,id:'unknown-bound',expectedVersion:5,limits:{currency:'SGD',perOrder:50,daily:null,aggregate:100},breakers:{supplierPurchases:false,listingPublication:false,priceInventory:false}});assert.throws(()=>engine.execute(second.actors.EXECUTOR!,secondPrepare),/OWNER_SPEND_LIMIT_UNKNOWN/);

 }finally{store.close();fs.rmSync(root,{recursive:true,force:true});}});
test('safety policy mutation remains founder-only and requires explicit confirmation; exact receipt readable',async()=>{const {default:Fastify}=await import('fastify');const {registerAdvisorRoutes}=await import('../../advisor/routes.js');const {AdvisorStore}=await import('../../advisor/store.js');const {createAuthMiddleware}=await import('../../auth/middleware.js');const {InMemorySessionStore}=await import('../../auth/session-store.js');const {env}=await import('../../config/env.js');const root=fs.mkdtempSync(path.join(os.tmpdir(),'work7-safety-route-'));fs.mkdirSync(path.join(root,'commissioning'));const old={RAILWAY_VOLUME_MOUNT_PATH:process.env.RAILWAY_VOLUME_MOUNT_PATH,EMPIRE_RUNTIME_PROFILE:process.env.EMPIRE_RUNTIME_PROFILE};Object.assign(process.env,{RAILWAY_VOLUME_MOUNT_PATH:root,EMPIRE_RUNTIME_PROFILE:'LOCKED_COMMISSIONING_V1'});const app=Fastify(),sessions=new InMemorySessionStore();const advisorStore=new AdvisorStore(path.join(root,'communications.sqlite'));registerAdvisorRoutes(app,createAuthMiddleware(sessions),advisorStore);try{assert.equal((await app.inject('/api/owner/advisor/safety')).statusCode,401);const owner={id:'owner',email:env.FOUNDER_EMAIL,name:'Owner',role:'founder' as const,workspaceId:'ws_empire_1'},token=(await sessions.create(owner)).token,headers={authorization:'Bearer '+token};const policy={action:'safety_policy',id:'owner-pause',expectedVersion:0,confirmation:true,limits:{currency:'SGD',perOrder:null,daily:null,aggregate:null},breakers:{supplierPurchases:true,listingPublication:true,priceInventory:true},reason:'Explicit pause'};
for(const u of [{...owner,role:'admin' as const},{...owner,workspaceId:'other'}]){const t=(await sessions.create(u)).token;assert.equal((await app.inject({method:'POST',url:'/api/owner/advisor/memory',headers:{authorization:'Bearer '+t},payload:policy})).statusCode,403);}assert.equal((await app.inject({method:'POST',url:'/api/owner/advisor/memory',headers,payload:{...policy,confirmation:false}})).statusCode,400);assert.equal((await app.inject({method:'POST',url:'/api/owner/advisor/memory',headers,payload:policy})).statusCode,200);const memory=new InstitutionalMemory(path.join(root,'commissioning','pillow-institutional.sqlite'));assert.equal(memory.get('ws_empire_1','owner-pause').version,1);assert.equal(memory.safetyPolicy('ws_empire_1').breakers.priceInventory,true);const executive=await app.inject({url:'/api/owner/advisor/executive',headers});assert.equal(executive.statusCode,200,executive.body);assert.match(executive.json().date,/^\d{4}-\d{2}-\d{2}$/);const originalAudit=advisorStore.audit.bind(advisorStore);advisorStore.audit=()=>{throw Error('isolated audit outage');};const uncertain={...policy,id:'audit-outage',expectedVersion:1};assert.equal((await app.inject({method:'POST',url:'/api/owner/advisor/memory',headers,payload:uncertain})).statusCode,503);assert.equal(memory.safetyPolicy('ws_empire_1').version,2);advisorStore.audit=originalAudit;assert.equal((await app.inject({method:'POST',url:'/api/owner/advisor/memory',headers,payload:uncertain})).statusCode,200);assert.equal(memory.safetyPolicy('ws_empire_1').version,2);
}finally{await app.close();for(const[k,v]of Object.entries(old)){if(v===undefined)delete process.env[k];else process.env[k]=v;}fs.rmSync(root,{recursive:true,force:true});}});
