import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {FinancialCentre,economics,forecast} from '../../finance/financial-centre.js';
const observedAt=new Date(Date.now()-1000).toISOString(),ev={kind:'INVOICE',reference:'test-only',sha256:'a'.repeat(64),observedAt};
const cost=(entityId='charge')=>({entityId,provider:'vercel',service:'Hosting',category:'TECHNOLOGY',classification:'VARIABLE',stage:'INVOICED',amountMicro:10000000,currency:'SGD',periodStart:'2026-10-01T00:00:00Z',periodEnd:'2026-11-01T00:00:00Z',invoiceNumber:entityId,authenticity:'REAL',evidence:[ev],attribution:{project:'EmpireAI',environment:'test',workload:'test',purpose:'isolated acceptance'}});
const approve=(f:FinancialCentre,target:string)=>f.append('test','owner',{id:'review-'+target,type:'review',data:{target,decision:'APPROVE',reason:'Isolated evidence reviewed',evidenceConfirmed:true}});
test('review, idempotency, conflicting retry, workspace isolation',()=>{const f=new FinancialCentre(':memory:'),c={id:'a',type:'cost',data:cost()};const a=f.append('test','owner',c);assert.equal(f.snapshot('test').costs.length,0);assert.deepEqual(f.append('test','owner',c),a);assert.throws(()=>f.append('test','owner',{...c,data:{...cost(),amountMicro:1}}),/CONFLICT/);approve(f,'a');assert.equal(f.snapshot('test').totals.INVOICED.sgdMicro,10000000);assert.equal(f.entries('other').length,0);f.close();});
test('accrual to invoice to settlement counts once; reversal retains history',()=>{const f=new FinancialCentre(':memory:');f.append('test','owner',{id:'a',type:'cost',data:{...cost(),stage:'ACCRUED_UNBILLED'}});approve(f,'a');f.append('test','owner',{id:'b',type:'cost',data:{...cost(),replaces:'a'}});approve(f,'b');assert.equal(f.snapshot('test').totals.ACCRUED_UNBILLED.sgdMicro,0);assert.throws(()=>f.append('test','owner',{id:'c',type:'cost',data:{...cost(),stage:'SETTLED',replaces:'b'}}),/PAYMENT/);f.append('test','owner',{id:'c',type:'cost',data:{...cost(),stage:'SETTLED',replaces:'b',paymentDate:observedAt,evidence:[ev,{...ev,kind:'PAYMENT'}]}});approve(f,'c');assert.equal(f.snapshot('test').totals.SETTLED.sgdMicro,10000000);assert.equal(f.snapshot('test').totals.INVOICED.sgdMicro,0);f.append('test','owner',{id:'r',type:'reversal',data:{target:'c',reason:'test reversal'}});assert.equal(f.snapshot('test').costs.length,0);assert.equal(f.entries('test').length,7);f.close();});
test('duplicate invoices and duplicate underlying sources rejected',()=>{const f=new FinancialCentre(':memory:');f.append('test','owner',{id:'a',type:'cost',data:{...cost(),sourceIds:['usage-1']}});assert.throws(()=>f.append('test','owner',{id:'b',type:'cost',data:{...cost('other'),invoiceNumber:'charge'}}),/DUPLICATE_INVOICE/);assert.throws(()=>f.append('test','owner',{id:'b',type:'cost',data:{...cost('other'),sourceIds:['usage-1']}}),/DUPLICATE_SOURCE/);f.close();});
test('non-real records excluded from actual KPIs and approval',()=>{const f=new FinancialCentre(':memory:');for(const authenticity of ['DEMO','SYNTHETIC','HISTORICAL_FIXTURE']){f.append('test','owner',{id:authenticity,type:'cost',data:{...cost(authenticity),authenticity,category:'REVENUE'}});assert.throws(()=>approve(f,authenticity),/NON_REAL/);}assert.equal(f.snapshot('test').kpis.verifiedRevenueSgdMicro,0);assert.equal(f.entries('test').length,3);f.close();});
test('FX unknown without evidence; tax credit allocation preserve original',()=>{const f=new FinancialCentre(':memory:');f.append('test','owner',{id:'a',type:'cost',data:{...cost(),currency:'USD'}});approve(f,'a');assert.equal(f.snapshot('test').costs[0]!.sgdMicro,null);f.append('test','owner',{id:'b',type:'cost',data:{...cost(),currency:'USD',taxMicro:1000000,creditMicro:2000000,replaces:'a',fx:{sgdPerUnit:1.3,observedAt,reference:'test FX'},attribution:{...cost().attribution,allocationBps:5000,allocationReason:'half allocation'}}});approve(f,'b');assert.equal(f.snapshot('test').costs[0]!.sgdMicro,5850000);assert.equal(f.snapshot('test').costs[0]!.originalMicro,9000000);f.close();});
test('malformed/future evidence and invalid arithmetic fail closed',()=>{const f=new FinancialCentre(':memory:');for(const data of [{...cost(),amountMicro:NaN},{...cost(),periodEnd:'invalid'},{...cost(),periodEnd:'2026-09-01T00:00:00Z'},{...cost(),evidence:[{...ev,observedAt:'2099-01-01T00:00:00Z'}]},{...cost(),evidence:[{...ev,content:'wrong hash'}]}])assert.throws(()=>f.append('test','owner',{id:'bad',type:'cost',data}));assert.equal(f.entries('test').length,0);f.close();});
test('cash unavailable and stale cash never become spendable',()=>{const f=new FinancialCentre(':memory:');assert.equal(f.snapshot('test').knownCashSgdMicro,null);assert.throws(()=>f.append('test','owner',{id:'cash',type:'cash',data:{account:'bank',balanceMicro:100,currency:'SGD',asOf:observedAt,evidence:ev}}),/BANK/);f.append('test','owner',{id:'cash',type:'cash',data:{account:'bank',balanceMicro:100,currency:'SGD',asOf:'2026-01-01T00:00:00Z',evidence:{...ev,kind:'BANK'}}});approve(f,'cash');assert.equal(f.snapshot('test').knownCashSgdMicro,null);f.close();});
test('budget, stale and renewal alerts',()=>{const f=new FinancialCentre(':memory:');f.append('test','owner',{id:'a',type:'cost',data:{...cost(),periodStart:new Date().toISOString(),periodEnd:'2027-01-01T00:00:00Z',renewalDate:observedAt,evidence:[{...ev,observedAt:'2026-01-01T00:00:00Z'}]}});approve(f,'a');f.append('test','owner',{id:'budget',type:'budget',data:{provider:'vercel',monthlySgdMicro:1,warningPercent:80,reason:'test limit'}});const codes=f.snapshot('test').alerts.map(a=>a.code);for(const c of ['BUDGET_ALERT','RENEWAL_DUE','STALE_EVIDENCE'])assert.ok(codes.includes(c));f.close();});
const unit={productId:'product',supplierId:'supplier',channel:'test',country:'SG',currency:'SGD',sellingPrice:100,productCost:20,freight:5,fulfilment:2,feePercent:10,paymentPercent:2,advertising:8,refundRate:.1,refundLoss:50,duties:1,tax:2,overhead:3,complete:false,evidenceRefs:[],assumptions:'Isolated example'};
test('independent unit arithmetic and zero-sales adverse forecasts',()=>{const e=economics(unit);assert.equal(e.gross,72);assert.equal(e.contribution,45);assert.equal(e.net,42);assert.ok(Math.abs(e.breakEven-46/.88)<1e-9);assert.equal(e.genuinelyProfitable,false);const f=forecast({monthlyFixed:100,monthlyApi:20,units:10,economics:unit,cash:null,liabilities:30,receivables:100,committed:40,providerIncrease:.5,supplierIncrease:.2,fxIncrease:.1,advertisingIncrease:.3,refundIncrease:.1,assumptions:'Test only',observedAt});assert.equal(f.scenarios[0]!.monthlyProfit,300);assert.equal(f.scenarios[0]!.runwayMonths,null);assert.equal(f.zeroSales[2]!.cashRequired,460);assert.equal(f.zeroSales[0]!.cashRemaining,null);assert.ok(f.scenarios[2]!.monthlyProfit<300);});
test('durable reopen preserves journal and approvals',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'work5-')),file=path.join(dir,'evidence.sqlite');let f=new FinancialCentre(file);f.append('test','owner',{id:'a',type:'cost',data:cost()});approve(f,'a');const before=f.snapshot('test');f.close();f=new FinancialCentre(file);assert.equal(f.snapshot('test').entryDigest,before.entryDigest);assert.equal(f.snapshot('test').totals.INVOICED.sgdMicro,10000000);f.close();fs.rmSync(dir,{recursive:true});});
test('reviewed complete cash scope and linked outcome learning are explicit',()=>{const f=new FinancialCentre(':memory:');f.append('test','owner',{id:'cash',type:'cash',data:{account:'bank',balanceMicro:1000000,currency:'SGD',asOf:observedAt,evidence:{...ev,kind:'BANK'}}});approve(f,'cash');assert.equal(f.snapshot('test').completeCashPosition,false);f.append('test','owner',{id:'scope',type:'coverage',data:{accounts:['bank'],liabilitiesComplete:true,commitmentsComplete:true,reason:'Isolated complete account scope',evidence:ev}});approve(f,'scope');assert.equal(f.snapshot('test').completeCashPosition,true);assert.equal(f.snapshot('test').availableCashSgdMicro,1000000);f.append('test','owner',{id:'limit',type:'provider_limit',data:{provider:'openai',monthlyMicroUsd:1000000,reason:'Owner configured test limit'}});assert.equal(f.entries('test').at(-1)?.type,'provider_limit');f.close();});
test('missing durable journal marker fails closed without erasing history',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'work5-loss-')),file=path.join(dir,'evidence.sqlite');const f=new FinancialCentre(file);f.close();fs.renameSync(file,file+'.retained');assert.throws(()=>new FinancialCentre(file),/JOURNAL_MISSING/);assert.equal(fs.existsSync(file),false);fs.rmSync(dir,{recursive:true});});
test('filtered reports cannot certify cash; unpaid costs reduce complete available cash',()=>{const f=new FinancialCentre(':memory:');f.append('test','owner',{id:'cash',type:'cash',data:{account:'bank',balanceMicro:20000000,currency:'SGD',asOf:observedAt,evidence:{...ev,kind:'BANK'}}});approve(f,'cash');f.append('test','owner',{id:'scope',type:'coverage',data:{accounts:['bank'],liabilitiesComplete:true,commitmentsComplete:true,reason:'Isolated full coverage',evidence:ev}});approve(f,'scope');f.append('test','owner',{id:'invoice',type:'cost',data:cost()});approve(f,'invoice');assert.equal(f.snapshot('test').availableCashSgdMicro,10000000);assert.equal(f.snapshot('test','0000','9999','vercel').availableCashSgdMicro,null);f.close();});
import {validateFinancialClosure} from '../../finance/closure.js';
test('financial closure requires every fixed criterion and matching actual source digests',()=>{const digest='a'.repeat(64),revision='b'.repeat(40);const c={id:'closure',type:'mission_close',state:'COMPLETE',backendSha:revision,frontendSha:'c'.repeat(40),railwayDeployment:'railway-test',vercelDeployment:'vercel-test',ciRunIds:['1','2'],legacyDigest:digest,accountingDigest:digest,journalDigest:digest,criteria:Array.from({length:16},(_,i)=>({id:'F'+String(i+1).padStart(2,'0'),passed:true,evidence:'isolated test proof'})),limitations:['No external data invented']};const current={revision,legacyDigest:digest,accountingDigest:digest,journalDigest:digest,profile:'LOCKED_COMMISSIONING_V1'};assert.equal(validateFinancialClosure(c,current).state,'COMPLETE');assert.throws(()=>validateFinancialClosure({...c,criteria:c.criteria.map((r,i)=>i===0?{...r,passed:false}:r)},current),/UNVERIFIED/);assert.throws(()=>validateFinancialClosure(c,{...current,legacyDigest:'d'.repeat(64)}),/UNVERIFIED/);assert.throws(()=>validateFinancialClosure({...c,criteria:c.criteria.map(()=>c.criteria[0])},current),/DUPLICATE/);});

test('missing obligation FX cannot certify available cash',()=>{const f=new FinancialCentre(':memory:');f.append('test','owner',{id:'cash',type:'cash',data:{account:'bank',balanceMicro:20000000,currency:'SGD',asOf:observedAt,evidence:{...ev,kind:'BANK'}}});approve(f,'cash');f.append('test','owner',{id:'scope',type:'coverage',data:{accounts:['bank'],liabilitiesComplete:true,commitmentsComplete:true,reason:'Isolated full coverage',evidence:ev}});approve(f,'scope');f.append('test','owner',{id:'invoice',type:'cost',data:{...cost(),currency:'USD'}});approve(f,'invoice');assert.equal(f.snapshot('test').availableCashSgdMicro,null);assert.equal(f.snapshot('test').completeCashPosition,false);f.close();});

test('consumed unbilled usage remains a liability against available cash',()=>{const f=new FinancialCentre(':memory:');f.append('test','owner',{id:'cash',type:'cash',data:{account:'bank',balanceMicro:20000000,currency:'SGD',asOf:observedAt,evidence:{...ev,kind:'BANK'}}});approve(f,'cash');f.append('test','owner',{id:'scope',type:'coverage',data:{accounts:['bank'],liabilitiesComplete:true,commitmentsComplete:true,reason:'Isolated full coverage',evidence:ev}});approve(f,'scope');f.append('test','owner',{id:'usage',type:'cost',data:{...cost(),stage:'ACCRUED_UNBILLED'}});approve(f,'usage');assert.equal(f.snapshot('test').availableCashSgdMicro,10000000);f.close();});
test('conversion overflow is rejected before a record can break financial readback',()=>{const f=new FinancialCentre(':memory:');assert.throws(()=>f.append('test','owner',{id:'overflow',type:'cost',data:{...cost(),amountMicro:1000000000000,currency:'USD',fx:{sgdPerUnit:10000,observedAt,reference:'Isolated overflow input'}}}),/FINANCIAL_OVERFLOW/);assert.equal(f.entries('test').length,0);f.close();});

test('reversed outcomes stop financial learning while original history survives',()=>{const f=new FinancialCentre(':memory:');const data={monthlyFixed:100,monthlyApi:20,units:10,economics:unit,cash:null,liabilities:30,receivables:100,committed:40,providerIncrease:.5,supplierIncrease:.2,fxIncrease:.1,advertisingIncrease:.3,refundIncrease:.1,assumptions:'Test only',observedAt};f.append('test','owner',{id:'forecast',type:'forecast',data});f.append('test','owner',{id:'outcome',type:'outcome',data:{forecastId:'forecast',actualProfitSgdMicro:1000000,evidence:{...ev,kind:'OUTCOME'},lesson:'Isolated result',nextAssumption:'Isolated revision'}});approve(f,'outcome');assert.equal(f.snapshot('test').outcomes[0]!.learningEligible,true);assert.ok(f.snapshot('test').recommendations.some(r=>r.topic==='Outcome calibration outcome'));f.append('test','owner',{id:'reverse',type:'reversal',data:{target:'outcome',reason:'Evidence withdrawn'}});assert.equal(f.snapshot('test').outcomes[0]!.learningEligible,false);assert.equal(f.snapshot('test').outcomes[0]!.verified,false);assert.equal(f.snapshot('test').outcomes.length,1);assert.equal(f.snapshot('test').recommendations.some(r=>r.topic==='Outcome calibration outcome'),false);f.close();});

 test('committed liabilities reduce cash without becoming technology expenses',()=>{const f=new FinancialCentre(':memory:');f.append('test','owner',{id:'cash',type:'cash',data:{account:'bank',balanceMicro:20000000,currency:'SGD',asOf:observedAt,evidence:{...ev,kind:'BANK'}}});approve(f,'cash');f.append('test','owner',{id:'scope',type:'coverage',data:{accounts:['bank'],liabilitiesComplete:true,commitmentsComplete:true,reason:'Isolated full coverage',evidence:ev}});approve(f,'scope');f.append('test','owner',{id:'commitment',type:'cost',data:{...cost(),category:'LIABILITY',stage:'COMMITTED'}});approve(f,'commitment');const snapshot=f.snapshot('test');assert.equal(snapshot.completeCashPosition,true);assert.equal(snapshot.position.commitmentsSgdMicro,10000000);assert.equal(snapshot.availableCashSgdMicro,10000000);assert.equal(snapshot.totals.COMMITTED.sgdMicro,0);assert.equal(snapshot.kpis.knownTechnologySgdMicro,0);f.close();});
