import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {GovernedCommerceStore,digest} from '../../runtime/commerce-runtime/governed/store.js';
import {GovernedCommerceEngine} from '../../runtime/commerce-runtime/governed/engine.js';
import {CommerceWorker} from '../../runtime/commerce-runtime/governed/worker.js';
import {acceptanceScenario} from '../../runtime/commerce-runtime/governed/scenario.js';
const start=Date.parse('2026-10-09T08:00:00Z');
function seed(e:GovernedCommerceEngine,n:number){const ids:string[]=[];for(let i=0;i<n;i++){const f=acceptanceScenario('ws','owner',start),m='m'+i;f.candidate.productId=m;f.candidate.offer.productId=m;f.candidate.offer.sku='sku'+i;f.candidate.offer.variantId='variant'+i;f.candidate.economics.productId=m;f.listing.productId=m;f.listing.variants[0]!.sku='sku'+i;f.listing.variants[0]!.variantId='variant'+i;const d=digest({candidate:f.candidate,listing:f.listing});const commands=[{type:'research',candidate:f.candidate},{type:'listing',listing:f.listing},{type:'review',digest:d,decision:'APPROVE',reason:'isolated policy'},{type:'approve',digest:d,expiresAt:new Date(start+3600000).toISOString(),maxExposure:100}];for(let j=0;j<4;j++)e.execute(f.steps[j]!.actor,{id:m+':'+j,missionId:m,expectedVersion:j,command:commands[j]});ids.push(m);}return ids;}
function capacity(n:number){return {account:'synthetic-account',marketplace:'SG',mode:'NEW_ASIN' as const,asin:null,newAsinRemaining:n,unsoldRemaining:n,requestsPerSecond:5,eligibility:'ELIGIBLE' as const,provenance:acceptanceScenario('ws','owner',start).candidate.offer.provenance};}
test('1000 candidate batch reuses queue; ranking, backpressure and restart deduplicate intents',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'w6-scale-')),file=path.join(dir,'runtime.sqlite');let now=start,store=new GovernedCommerceStore(file);try{let e=new GovernedCommerceEngine(store,()=>now),w=new CommerceWorker(e);const ids=seed(e,1000);assert.deepEqual(w.screen('ws',ids,100),w.screen('ws',[...ids].reverse(),100));assert.equal(w.screen('ws',ids,100).filter(r=>r.selected).length,100);const input={id:'batch-1000',missions:ids,reviewLimit:1000,capacity:capacity(1000)};let tasks=w.enqueuePreparationBatch('ws','owner',input);assert.equal(tasks.length,1000);assert.throws(()=>w.enqueuePreparationBatch('ws','owner',{...input,id:'overflow'}),/BACKPRESSURE/);assert.equal(w.tick('ws',tasks[1]!.id,0).cursor,0);now+=300000;for(const t of tasks.slice(0,100))w.runBounded('ws',t.id);store.close();store=new GovernedCommerceStore(file);e=new GovernedCommerceEngine(store,()=>now);w=new CommerceWorker(e);tasks=w.enqueuePreparationBatch('ws','owner',input);for(const t of tasks)if(t.status!=='COMPLETE')w.runBounded('ws',t.id);const p=w.batchProgress('ws','batch-1000');assert.equal(p.intercepted,1000);assert.equal(p.blocked,0);assert.equal(p.externalEffects,0);assert.equal(store.history('ws','m0').length,5);assert.throws(()=>w.enqueuePreparationBatch('ws','other',input),/IDEMPOTENCY/);assert.throws(()=>w.enqueuePreparationBatch('ws','owner',{...input,id:'duplicate'}),/DUPLICATE_LISTING/);}finally{store.close();fs.rmSync(dir,{recursive:true,force:true});}});
test('capacity exhaustion preserves per-item partial success and replay',()=>{const s=new GovernedCommerceStore(':memory:');try{let now=start;const e=new GovernedCommerceEngine(s,()=>now),w=new CommerceWorker(e),missions=seed(e,5),input={id:'partial',missions,reviewLimit:5,capacity:capacity(2)};const ts=w.enqueuePreparationBatch('ws','owner',input);now+=1000;for(const t of ts)w.runBounded('ws',t.id);const p=w.batchProgress('ws','partial');assert.equal(p.intercepted,2);assert.equal(p.blocked,3);assert.ok(p.items.filter(t=>t.status==='BLOCKED').every(t=>t.error==='NEW_ASIN_CAPACITY_UNKNOWN_OR_EXHAUSTED'));assert.equal(w.enqueuePreparationBatch('ws','owner',input).length,5);const failed=p.items.filter(t=>t.status==='BLOCKED').map(t=>t.mission);const repaired=w.enqueuePreparationBatch('ws','owner',{...input,id:'repair',missions:failed,capacity:capacity(3)});now+=1000;for(const t of repaired)w.runBounded('ws',t.id);assert.equal(w.batchProgress('ws','repair').intercepted,3);assert.equal(w.batchProgress('ws','partial').blocked,3);assert.throws(()=>w.tick('ws',ts[0]!.id,0),/FENCE/);}finally{s.close();}});
test('unknown capacity, missing ASIN mapping, stale and actual capacity assertions fail closed',()=>{for(const mode of ['unknown','existing','stale','real'] as const){const s=new GovernedCommerceStore(':memory:');try{const e=new GovernedCommerceEngine(s,()=>start),w=new CommerceWorker(e),missions=seed(e,1);const c={...capacity(1),newAsinRemaining:mode==='unknown'?null:1,mode:mode==='existing'?'EXISTING_ASIN_OFFER':'NEW_ASIN'};if(mode==='stale')c.provenance.expiresAt=new Date(start-1).toISOString();if(mode==='real')c.provenance.classification='REAL_READ_ONLY' as typeof c.provenance.classification;const t=w.enqueuePreparationBatch('ws','owner',{id:mode,missions,reviewLimit:1,capacity:c})[0]!;assert.equal(w.runBounded('ws',t.id).status,'BLOCKED',mode);assert.equal(s.history('ws','m0').length,4);}finally{s.close();}}});
test('existing ASIN offer mapping does not consume new-ASIN capacity',()=>{const s=new GovernedCommerceStore(':memory:');try{const e=new GovernedCommerceEngine(s,()=>start),w=new CommerceWorker(e),missions=seed(e,1);const t=w.enqueuePreparationBatch('ws','owner',{id:'existing',missions,reviewLimit:1,asins:{m0:'B000000001'},capacity:{...capacity(1),mode:'EXISTING_ASIN_OFFER',newAsinRemaining:null}})[0]!;assert.equal(w.runBounded('ws',t.id).status,'COMPLETE');}finally{s.close();}});
