import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {InstitutionalMemory} from '../../institutional-memory/store.js';
import {IntelligenceStore} from '../../intelligence/store.js';
import {digest,type Evidence} from '../../intelligence/model.js';
import {readIntelligence} from '../../intelligence/runtime.js';
import {reconcileSignals} from '../../intelligence/engines.js';
import {freightOrigin} from '../../intelligence/freight-origin.js';
import {CanvaVisualProvider} from '../../orchestration/visual-generation-layer/providers/canva-visual-provider.js';
import {getCanvaConnectService} from '../../execution/canva-connect-connector/services/canva-connect-service.js';
function setup(t:any){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'work1-new-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const now=Date.now();return {m:new InstitutionalMemory(path.join(dir,'memory.sqlite')),s:new IntelligenceStore(path.join(dir,'eyes.sqlite'),()=>now)};}
function evidence(s:IntelligenceStore,id='ev',over:Partial<Evidence>={}):Evidence{const facts={price:100,currency:'USD'};return {id,capabilityId:'amazon.offers',eye:'MARKET',provider:'Amazon',endpoint:'/offers',subject:{id:'product',marketplace:'US'},observedAt:new Date(s.now()-100).toISOString(),retrievedAt:new Date(s.now()).toISOString(),staleAfter:new Date(s.now()+100000).toISOString(),authenticity:'LIVE_PROVIDER',facts,digest:digest(facts),jobId:'job',quality:[],lineage:['test'],grantsAuthority:false,...over};}
test('active doctrine survives 45 newer claims with supersession and workspace isolation',t=>{const {m}=setup(t);const d={action:'doctrine',id:'old',scope:{domain:'executive'},statement:'Retain evidence provenance',explicitDurableInstruction:true};m.ownerCommand('w','owner',d);m.ownerCommand('w','owner',{...d,id:'active',supersedes:'old'});for(let i=0;i<45;i++)m.captureDecision('w',{request:'r'+i,session:'s',question:'recommend strategy',answer:'Unreviewed claim',influences:[]});assert.deepEqual(m.bootstrap('w','recommend strategy').records!.map((r:any)=>r.id),['active']);assert.equal(m.bootstrap('other','recommend strategy').records!.length,0);assert.equal(m.get('w','old').current.status,'SUPERSEDED');assert.equal(m.bootstrap('w','strategy').authority.grantsAuthority,false);});
test('invalid evidence clocks are rejected before storage',t=>{const {s}=setup(t);for(const over of [{staleAfter:'bad'},{retrievedAt:'bad'},{observedAt:'bad'},{retrievedAt:new Date(s.now()-1000).toISOString()},{staleAfter:new Date(s.now()-1).toISOString()}]){assert.throws(()=>s.evidence('w',evidence(s,'ev',over)),/EVIDENCE_TIME/);assert.equal(s.get('w','evidence','ev'),null);}s.evidence('w',evidence(s));assert.ok(s.cached('w','amazon.offers',evidence(s).subject));});
test('future health and heartbeat cannot establish current capability',t=>{const {s}=setup(t);const future=new Date(s.now()+60000).toISOString();s.put('w','health','internet.safety',{lastGoodAt:future,authenticatedAt:future});const c=s.arsenal('w').find(c=>c.id==='internet.safety')!;assert.equal(c.readState,'UNVERIFIED');assert.equal(c.authenticationState,'UNVERIFIED');assert.notEqual(c.availability,'AVAILABLE');s.put('w','scheduler','health',{heartbeatAt:future,status:'RUNNING'});assert.equal((readIntelligence(s,'w','intelligence') as any).scheduler.fresh,false);});
test('historical success cannot override missing credentials or stale reads',t=>{const {s}=setup(t);const keys=['AMAZON_SP_API_CLIENT_ID','AMAZON_SP_API_CLIENT_SECRET','AMAZON_SP_API_REFRESH_TOKEN'];const old=keys.map(k=>process.env[k]);t.after(()=>keys.forEach((k,i)=>{if(old[i]===undefined)delete process.env[k];else process.env[k]=old[i];}));keys.forEach(k=>delete process.env[k]);s.put('w','health','amazon.account',{lastGoodAt:new Date(s.now()).toISOString(),authenticatedAt:new Date(s.now()).toISOString()});const c=s.arsenal('w').find(c=>c.id==='amazon.account')!;assert.equal(c.configurationState,'NOT_CONFIGURED');assert.equal(c.availability,'UNAVAILABLE');assert.equal(c.authenticationState,'UNVERIFIED');s.put('w','health','internet.safety',{lastGoodAt:new Date(s.now()-400*86400000).toISOString()});assert.equal(s.arsenal('w').find(c=>c.id==='internet.safety')!.readState,'STALE');});
test('fresh exact cache survives unrelated volume; synthetic and other workspace excluded',t=>{const {s}=setup(t);s.evidence('w',evidence(s,'original'));for(let i=0;i<110;i++)s.evidence('w',evidence(s,'new'+i,{subject:{id:'other'+i,marketplace:'US'}}));assert.equal(s.cached('w','amazon.offers',evidence(s).subject)?.id,'original');assert.equal(s.cached('other','amazon.offers',evidence(s).subject),undefined);s.evidence('w',evidence(s,'synthetic',{subject:{id:'synthetic',marketplace:'US'},authenticity:'SYNTHETIC'}));assert.equal(s.cached('w','amazon.offers',{id:'synthetic',marketplace:'US'}),undefined);});
test('price comparison uses latest observation pair despite out of order ingestion',t=>{const {s}=setup(t);for(const [id,price,age] of [['new',180,100],['old',100,300],['middle',120,200]] as const){const facts={price,currency:'USD'};s.evidence('w',evidence(s,id,{facts,digest:digest(facts),observedAt:new Date(s.now()-age).toISOString()}));}reconcileSignals(s,'w');const c=s.list('w','changes')[0]!;assert.equal(c.changePct,50);assert.deepEqual(c.evidenceRefs,['new','middle']);reconcileSignals(s,'w');assert.equal(s.list('w','changes')[0]!.newObservation,false);});
const stock=(rows:unknown[])=>({capabilityId:'cj.stock',provider:'CJ',authenticity:'LIVE_PROVIDER',subject:{variant:'v'},facts:{response:rows}});
test('freight requires exact variant and unique supported warehouse country',()=>{assert.equal(freightOrigin(stock([{vid:'v',countryCode:'CN',storageNum:0,totalInventoryNum:50}]),'v'),'CN');for(const value of [undefined,stock([{vid:'other',countryCode:'CN'}]),stock([{vid:'v',note:'CN'}]),stock([{vid:'v',countryCode:'CN'},{vid:'v',countryCode:'US'}]),stock([{vid:'v',countryCode:'GB'}]),{...stock([{vid:'v',countryCode:'CN'}]),authenticity:'SYNTHETIC'}])assert.equal(freightOrigin(value,'v'),null);assert.equal(freightOrigin(stock([{vid:'v',countryCode:'CN'}]),'other'),null);});
test('Canva unfinished export does not report asset success',async t=>{const service=getCanvaConnectService();t.mock.method(service,'createDesign',async()=>({designId:'fixture'}));for(const status of ['in_progress','failed','success'] as const){const mock=t.mock.method(service,'exportDesign',async()=>({status,format:'png',downloadUrl:status==='success'?'mock://fixture':null}));const r=await new CanvaVisualProvider().createVisualAsset({workspaceId:'fixture',companyId:'fixture',useCase:'product_image',format:'png'} as any);assert.equal(r.status,status);mock.mock.restore();}});
