/** Permanent executive operating loops (Digital Soul V2). */

export const EXECUTIVE_THINKING_LOOP = [
  "Observe",
  "Understand",
  "Question",
  "Investigate",
  "Collect Evidence",
  "Identify Problems",
  "Identify Opportunities",
  "Generate Alternatives",
  "Estimate Value",
  "Estimate Risk",
  "Recommend",
  "Execute when constitutionally authorised",
  "Measure",
  "Learn",
  "Improve",
  "Repeat Forever",
] as const;

export const LEARNING_LOOP = [
  "Observe",
  "Question",
  "Research",
  "Generate Hypothesis",
  "Estimate Expected Value",
  "Prioritise",
  "Approve",
  "Launch",
  "Observe Reality",
  "Collect Evidence",
  "Measure Results",
  "Explain Outcomes",
  "Identify Lessons",
  "Update Executive Knowledge",
  "Improve",
  "Repeat Forever",
] as const;

export const OPPORTUNITY_PIPELINE = [
  "Discover",
  "Understand",
  "Research",
  "Collect Evidence",
  "Estimate Value",
  "Estimate Risk",
  "Compare Alternatives",
  "Rank",
  "Recommend",
  "Approve",
  "Build",
  "Launch",
  "Observe",
  "Improve",
  "Scale",
  "Re-evaluate",
  "Retire when justified",
] as const;

export const DECISION_CYCLE = [
  "Recognise",
  "Understand",
  "Collect Evidence",
  "Identify Assumptions",
  "Generate Alternatives",
  "Evaluate Consequences",
  "Estimate Value",
  "Estimate Risk",
  "Estimate Confidence",
  "Recommend",
  "Approve when authorised",
  "Execute",
  "Observe Reality",
  "Review Outcome",
  "Capture Lessons",
  "Improve Future Decisions",
] as const;

export const KNOWLEDGE_LIFECYCLE = [
  "Observe",
  "Capture",
  "Verify",
  "Organise",
  "Connect",
  "Retrieve",
  "Apply",
  "Evaluate",
  "Improve",
  "Retain",
  "Repeat",
] as const;

export const PERMANENT_OPERATING_CYCLE = [
  "Observe",
  "Understand",
  "Question",
  "Prioritise",
  "Recommend",
  "Approve when required",
  "Execute",
  "Verify",
  "Measure",
  "Learn",
  "Improve",
  "Prepare",
  "Repeat Forever",
] as const;

export const CONTINUOUS_EXECUTIVE_CYCLE = [
  "Observe",
  "Understand",
  "Question",
  "Discover",
  "Prioritise",
  "Recommend",
  "Coordinate",
  "Verify",
  "Learn",
  "Improve",
  "Repeat Forever",
] as const;

export const REASONING_PROCESS = [
  "Observe",
  "Understand",
  "Define",
  "Question",
  "Generate Alternatives",
  "Evaluate Evidence",
  "Compare Trade-offs",
  "Estimate Outcomes",
  "Recommend",
  "Verify",
  "Learn",
] as const;

export const ENTERPRISE_DOMAINS = [
  "Commerce",
  "Finance",
  "Media",
  "Marketing",
  "Supplier Intelligence",
  "Marketplace Intelligence",
  "Human Studio",
  "AI Workforce",
  "Knowledge",
  "Infrastructure",
  "Production",
  "Security",
  "Cloud Operations",
  "Executive Governance",
  "Business Creation",
  "Capital Allocation",
  "Opportunity Pipeline",
  "Risk",
  "Constitutional Compliance",
] as const;
