import type { PerformanceBaselineRecord } from "./types.js";

/** Constitutional performance baselines (P5-06). */
export const PERFORMANCE_BASELINE_REGISTRY: PerformanceBaselineRecord[] = [
  {
    id: "PG-BL-001",
    surface: "Executive Home",
    domain: "cockpit",
    currentPerformance: "Client-side render · BFF proxy to Railway",
    targetPerformance: "Interactive < 2s · LCP < 2.5s",
    acceptableThreshold: "LCP ≤ 3s · TTI ≤ 4s",
    criticalThreshold: "LCP > 5s · blank screen > 3s",
  },
  {
    id: "PG-BL-002",
    surface: "Pillow Chat",
    domain: "pillow",
    currentPerformance: "Full startPillow() chain on first session · LLM round-trip",
    targetPerformance: "First response < 5s · steady < 3s",
    acceptableThreshold: "Response ≤ 8s · context build ≤ 4s",
    criticalThreshold: "Response > 15s · timeout",
  },
  {
    id: "PG-BL-003",
    surface: "Builder",
    domain: "builder",
    currentPerformance: "Mission assembly + pre-mission checks + dispatch",
    targetPerformance: "Mission ready < 2s · dispatch < 5s",
    acceptableThreshold: "Assembly ≤ 5s",
    criticalThreshold: "Assembly > 10s · gate failure",
  },
  {
    id: "PG-BL-004",
    surface: "Supervisor",
    domain: "supervisor",
    currentPerformance: "Launch validation + registry + heartbeat",
    targetPerformance: "Launch < 500ms · heartbeat < 100ms",
    acceptableThreshold: "Launch ≤ 1s",
    criticalThreshold: "Launch blocked · heartbeat stale > 60s",
  },
  {
    id: "PG-BL-005",
    surface: "Journey",
    domain: "journey",
    currentPerformance: "Event recording synchronous in mission path",
    targetPerformance: "Event write < 50ms",
    acceptableThreshold: "Event write ≤ 200ms",
    criticalThreshold: "Event loss · journey gap",
  },
  {
    id: "PG-BL-006",
    surface: "Authentication",
    domain: "authentication",
    currentPerformance: "Redis session lookup · JWT verify",
    targetPerformance: "Auth < 200ms",
    acceptableThreshold: "Auth ≤ 500ms",
    criticalThreshold: "Auth > 2s · session invalid",
  },
  {
    id: "PG-BL-007",
    surface: "Production APIs",
    domain: "api",
    currentPerformance: "Fastify Brain · event-loop cooperative",
    targetPerformance: "P95 API < 500ms · P99 < 2s",
    acceptableThreshold: "P95 ≤ 1s · event loop lag < 200ms",
    criticalThreshold: "P95 > 3s · event loop lag > 500ms",
  },
  {
    id: "PG-BL-008",
    surface: "Business Dashboard",
    domain: "business_engines",
    currentPerformance: "Commerce intelligence + dashboard aggregation",
    targetPerformance: "Dashboard load < 3s",
    acceptableThreshold: "Load ≤ 5s",
    criticalThreshold: "Load > 8s · stale data",
  },
  {
    id: "PG-BL-009",
    surface: "Mission Generation",
    domain: "pillow",
    currentPerformance: "Planner refresh + preamble chain (~12 engines)",
    targetPerformance: "Generate < 3s",
    acceptableThreshold: "Generate ≤ 6s",
    criticalThreshold: "Generate > 12s · blocked mission",
  },
  {
    id: "PG-BL-010",
    surface: "Repository Operations",
    domain: "brain_runtime",
    currentPerformance: "Memory refresh + intelligence scan",
    targetPerformance: "Refresh < 2s · sync < 5s",
    acceptableThreshold: "Refresh ≤ 4s",
    criticalThreshold: "Refresh > 10s · stale memory",
  },
];
