import type { EmpireBootstrapContext } from "../bootstrap/types.js";
import { RepositoryReader } from "../bootstrap/repository-reader.js";
import { buildFrontendWorkerConfiguration, type FrontendWorkerConfiguration } from "./configuration.js";
import { FrontendWorkerController } from "./frontend-worker-controller.js";
import { FrontendManager } from "./frontend-manager.js";
import type { FrontendWorkerDependencies } from "./integrations.js";
import { resetFewLogsForTesting } from "./few-logging.js";
import { resetFrontendSequenceForTesting } from "./frontend-builder.js";
import { FRONTEND_WORKER_SYSTEM_PATH } from "./paths.js";
import type { FrontendWorkerCockpitSnapshot, FrontendWorkerInput, FrontendWorkerState } from "./types.js";
export interface FrontendWorkerOptions { configuration?: Partial<FrontendWorkerConfiguration>; dependencies?: FrontendWorkerDependencies; }
export class FrontendWorker {
  private initializedAt: string | null = null; private readonly controller: FrontendWorkerController;
  constructor(private readonly bootstrap: EmpireBootstrapContext, options: FrontendWorkerOptions = {}) { const manager = new FrontendManager(); if (options.dependencies) manager.bindIntegrations(options.dependencies); this.controller = new FrontendWorkerController(manager, buildFrontendWorkerConfiguration(bootstrap.repositoryRoot, options.configuration)); }
  async initialize() { const doc = await new RepositoryReader(this.bootstrap.repositoryRoot).readText(FRONTEND_WORKER_SYSTEM_PATH); if (!doc?.includes("Frontend Worker")) throw new Error(`${FRONTEND_WORKER_SYSTEM_PATH} missing — Q6-04 system doc required.`); this.controller.initialize(); this.initializedAt = new Date().toISOString(); return this.getState(); }
  bindIntegrations(deps: FrontendWorkerDependencies = {}) { this.controller.bindIntegrations(deps); }
  getState(): FrontendWorkerState { if (!this.initializedAt) throw new Error("Frontend Worker not initialized. Call initialize() first."); const configuration = this.controller.getConfiguration(); const engineRecord = this.controller.getManager().getEngineRecord(); const latestReport = this.controller.getLatestReport(); return { engineVersion: "PILLOW-FEW-001", missionId: "Q6-04", status: this.controller.getStatus(), initializedAt: this.initializedAt, configuration, latestReport, engineRecord, health: { status: engineRecord?.healthStatus ?? "standby", healthScore: engineRecord?.healthStatus === "healthy" ? 100 : engineRecord ? 70 : 50, engineEnabled: configuration.enabled, lastOperationAt: latestReport?.runTimestamp ?? null, lastValidationDecision: latestReport?.validation.decision ?? null, totalFrontendBuildReports: engineRecord?.totalFrontendBuildReports ?? 0, lastFrontendBuildReportId: engineRecord?.lastFrontendBuildReportId ?? null, lastConfidenceScore: engineRecord?.lastConfidenceScore ?? null, notes: ["Frontend Worker builds structural UI signals from approved requirements and architecture; it does not implement backend business logic, design databases, deploy applications, override authority, or implement Q6-05 or later."] } }; }
  connect(i: Record<string, unknown> = {}) { return this.controller.connect(i); } receiveApprovedRequirementsReports(i: FrontendWorkerInput = {}) { return this.controller.receiveApprovedRequirementsReports(i); } receiveApprovedRequirementsReport(i: FrontendWorkerInput = {}) { return this.controller.receiveApprovedRequirementsReport(i); } receiveApprovedArchitectureReports(i: FrontendWorkerInput = {}) { return this.controller.receiveApprovedArchitectureReports(i); } receiveApprovedArchitectureReport(i: FrontendWorkerInput = {}) { return this.controller.receiveApprovedArchitectureReport(i); } buildApplicationLayouts(i: FrontendWorkerInput = {}) { return this.controller.buildApplicationLayouts(i); } buildDashboards(i: FrontendWorkerInput = {}) { return this.controller.buildDashboards(i); } buildPages(i: FrontendWorkerInput = {}) { return this.controller.buildPages(i); } buildFormsAndInputValidation(i: FrontendWorkerInput = {}) { return this.controller.buildFormsAndInputValidation(i); } buildUserWorkflows(i: FrontendWorkerInput = {}) { return this.controller.buildUserWorkflows(i); } integrateApprovedApis(i: FrontendWorkerInput = {}) { return this.controller.integrateApprovedApis(i); } supportResponsiveAndAccessibleUi(i: FrontendWorkerInput = {}) { return this.controller.supportResponsiveAndAccessibleUi(i); } produceFrontendBuildReport(i: FrontendWorkerInput = {}) { return this.controller.produceFrontendBuildReport(i); } submitReport(i: FrontendWorkerInput = {}) { return this.controller.submitReport(i); } list() { return this.controller.list(); } validate(i: FrontendWorkerInput = {}) { return this.controller.validate(i); } diagnostics() { return this.controller.diagnostics(); }
  getFrontendBuildReports() { return this.controller.getManager().getFrontendBuildReports(); } getCatalog() { return this.controller.getManager().getCatalog(); } getEngineRecord() { return this.controller.getManager().getEngineRecord(); } getLatestFrontendBuildReportId() { return this.controller.getManager().getLatestFrontendBuildReportId(); } getAuditTrail() { return this.controller.getManager().getAuditTrail(); } getIntegrations() { return this.controller.getManager().getIntegrations(); }
  validateForSupervisorSync() { const state = this.getState(); const score = state.latestReport?.validation.decision === "fail" ? 40 : state.latestReport?.validation.decision === "partial" ? 70 : 100; return { valid: state.health.status !== "failed", health: score >= 75 ? "healthy" as const : score >= 50 ? "degraded" as const : "blocked" as const, readinessScore: score, notes: state.health.notes }; }
  getCockpitSnapshot(): FrontendWorkerCockpitSnapshot { const state = this.getState(); return { missionId: "Q6-04", status: state.status, healthStatus: state.health.status, totalFrontendBuildReports: state.health.totalFrontendBuildReports, latestFrontendBuildReportId: this.getLatestFrontendBuildReportId(), lastConfidenceScore: state.health.lastConfidenceScore, workerId: state.configuration.workerId, neverImplementBackendBusinessLogic: true, neverDesignDatabases: true, neverDeployApplications: true, neverImplementQ605OrLater: true }; }
}
export const createFrontendWorker = (bootstrap: EmpireBootstrapContext, options?: FrontendWorkerOptions) => new FrontendWorker(bootstrap, options);
export function resetFrontendWorkerForTesting() { resetFewLogsForTesting(); resetFrontendSequenceForTesting(); }
