import { FEW_CAPABILITIES, FEW_METADATA_VERSION, FRONTEND_WORKER_ID, INTEGRATION_TARGETS } from "./paths.js";
import type { FrontendWorkerConfiguration } from "./configuration.js";
import { FrontendBuilder } from "./frontend-builder.js";
import { FrontendStore } from "./frontend-store.js";
import { FrontendValidator, HealthMonitor, RecoveryManager } from "./frontend-validator.js";
import { IntegrationCoordinator, type FrontendWorkerDependencies } from "./integrations.js";
import { appendFewLog } from "./few-logging.js";
import type { FrontendBuildReport, FrontendWorkerCatalog, FrontendWorkerEngineRecord, FrontendWorkerInput, FrontendWorkerRunReport, IntegrationHandshake } from "./types.js";
export class FrontendManager {
  private readonly store = new FrontendStore(); private readonly builder = new FrontendBuilder(); private readonly validator = new FrontendValidator(); private readonly health = new HealthMonitor(); private readonly recovery = new RecoveryManager(); private readonly integrations = new IntegrationCoordinator(); private engineRecord: FrontendWorkerEngineRecord | null = null; private seeded = false; private handshakes: IntegrationHandshake[] = [];
  bindIntegrations(deps: FrontendWorkerDependencies = {}) { this.integrations.bind(deps); }
  ensureSeeded(config: FrontendWorkerConfiguration) { if (!this.seeded) { this.store.seed(config.seedFrontendBuildReports); this.seeded = true; this.record("connected", config, "pass"); } }
  connect(_: Record<string, unknown>, config: FrontendWorkerConfiguration) { this.ensureSeeded(config); this.handshakes = this.integrations.connect(config.workerId); this.record("connected", config, "pass"); return this.report("connect", [], null, this.validator.finalize("pass", [], [], Date.now()), Date.now()); }
  receiveApprovedRequirementsReports(input: FrontendWorkerInput, config: FrontendWorkerConfiguration) { return this.stage("receive_approved_requirements_reports", input, config, (r) => r, true, true); }
  receiveApprovedArchitectureReports(input: FrontendWorkerInput, config: FrontendWorkerConfiguration) { return this.stage("receive_approved_architecture_reports", input, config, (r) => ({ ...r, architectureReportId: input.architectureReportId ?? r.architectureReportId, confidenceScore: Math.max(r.confidenceScore, 50) }), true); }
  buildApplicationLayouts(input: FrontendWorkerInput, config: FrontendWorkerConfiguration) { return this.stage("build_application_layouts", input, config, (r) => this.builder.addLayouts(r)); }
  buildDashboards(input: FrontendWorkerInput, config: FrontendWorkerConfiguration) { return this.stage("build_dashboards", input, config, (r) => this.builder.addDashboards(r)); }
  buildPages(input: FrontendWorkerInput, config: FrontendWorkerConfiguration) { return this.stage("build_pages", input, config, (r) => this.builder.addPages(r)); }
  buildFormsAndInputValidation(input: FrontendWorkerInput, config: FrontendWorkerConfiguration) { return this.stage("build_forms_and_input_validation", input, config, (r) => this.builder.addForms(r)); }
  buildUserWorkflows(input: FrontendWorkerInput, config: FrontendWorkerConfiguration) { return this.stage("build_user_workflows", input, config, (r) => this.builder.addWorkflows(r)); }
  integrateApprovedApis(input: FrontendWorkerInput, config: FrontendWorkerConfiguration) { return this.stage("integrate_approved_apis", input, config, (r, arch) => this.builder.addApis(r, arch?.apiArchitecture ?? [])); }
  supportResponsiveAndAccessibleUi(input: FrontendWorkerInput, config: FrontendWorkerConfiguration) { return this.stage("support_responsive_and_accessible_ui", input, config, (r) => this.builder.addAccessibility(r)); }
  produceFrontendBuildReport(input: FrontendWorkerInput, config: FrontendWorkerConfiguration) { return this.stage("produce_frontend_build_report", input, config, (r) => this.builder.complete(r), false); }
  submitReport(input: FrontendWorkerInput, config: FrontendWorkerConfiguration) { const started = Date.now(); const produced = this.produceFrontendBuildReport(input, config); const latest = produced.latestFrontendBuildReport; if (!latest || produced.validation.decision === "fail") return produced; const submission = this.integrations.submitReport(latest); const saved = submission.submitted ? this.store.markSubmitted(latest.buildId, submission.executiveReportId!)! : latest; const v = this.validator.validateFrontendBuildReports([saved], input, started); return this.finish("submit_report", [saved], saved, v, started, config); }
  list(config: FrontendWorkerConfiguration) { this.ensureSeeded(config); const reports = this.store.list(); return this.finish("list", reports, reports.at(-1) ?? null, this.validator.validateFrontendBuildReports(reports.length ? reports : null, { validated: true }, Date.now(), true), Date.now(), config); }
  validate(input: FrontendWorkerInput, config: FrontendWorkerConfiguration) { const reports = this.store.list(); return this.finish("validate", reports, reports.at(-1) ?? null, this.validator.validateFrontendBuildReports(reports.length ? reports : null, input, Date.now()), Date.now(), config); }
  diagnostics(config: FrontendWorkerConfiguration) { return this.list(config); }
  getFrontendBuildReports() { return this.store.list(); } getLatestFrontendBuildReportId() { return this.store.getLatestFrontendBuildReportId(); } getAuditTrail() { return this.store.getAuditTrail(); } getIntegrations() { return this.handshakes.map((h) => ({ ...h })); } getEngineRecord() { return this.engineRecord ? structuredClone(this.engineRecord) : null; }
  getCatalog(): FrontendWorkerCatalog { return { reportVersion: "FEW-RPT-v1", workerId: this.engineRecord?.workerId ?? "wkr-frontend-01", frontendBuildReports: this.store.list(), integrations: this.getIntegrations(), metadataVersion: FEW_METADATA_VERSION, executiveAuthority: "pillow", neverImplementBackendBusinessLogic: true, neverDesignDatabases: true, neverDeployApplications: true, neverOverridePillow: true, neverOverrideGrandKing: true, neverImplementQ605OrLater: true }; }
  private stage(action: string, input: FrontendWorkerInput, config: FrontendWorkerConfiguration, mutate: (r: FrontendBuildReport, architecture?: ReturnType<IntegrationCoordinator["enrich"]>["architecture"]) => FrontendBuildReport, incomplete = true, newShell = false) { const started = Date.now(); this.ensureSeeded(config); const enriched = this.integrations.enrich(input); const violations = this.validator.validateFrontendBuildReports(null, enriched.input, started); if (violations.decision === "fail") return this.finish(action, [], null, violations, started, config); let r = !newShell ? this.store.list().at(-1) : null; if (!r) r = this.builder.createShell(enriched.input, config); r = mutate(r, enriched.architecture); if (action === "receive_approved_architecture_reports") r = { ...r, architectureReportId: enriched.input.architectureReportId ?? r.architectureReportId }; this.store.save(r, action); const v = this.validator.validateFrontendBuildReports([r], enriched.input, started, incomplete); return this.finish(action, [r], r, v, started, config); }
  private finish(action: string, reports: FrontendBuildReport[], latest: FrontendBuildReport | null, validation: FrontendWorkerRunReport["validation"], started: number, config: FrontendWorkerConfiguration) { if (validation.decision === "fail") this.recovery.recordFailure(); else this.recovery.reset(); this.record(validation.decision === "fail" ? "failed" : "active", config, validation.decision, latest); appendFewLog({ event: action, details: `build=${latest?.buildId ?? "none"}` }); return this.report(action, reports, latest, validation, started); }
  private record(state: string, config: FrontendWorkerConfiguration, validation: "pass" | "partial" | "fail", latest: FrontendBuildReport | null = null) { const report = latest ?? this.store.list().at(-1) ?? null; this.engineRecord = { engineRecordId: this.engineRecord?.engineRecordId ?? `few-eng-${Date.now()}`, timestamp: new Date().toISOString(), engineId: FRONTEND_WORKER_ID, engineVersion: "PILLOW-FEW-001", currentOperationalState: state, healthStatus: this.health.status(validation, config.enabled), validationStatus: validation === "pass" ? "passed" : validation === "fail" ? "failed" : "partial", supportedCapabilities: [...FEW_CAPABILITIES], totalFrontendBuildReports: this.store.count(), lastFrontendBuildReportId: report?.buildId ?? null, lastConfidenceScore: report?.confidenceScore ?? null, workerId: config.workerId, integrationTargets: [...INTEGRATION_TARGETS], metadataVersion: FEW_METADATA_VERSION }; }
  private report(action: string, reports: FrontendBuildReport[], latest: FrontendBuildReport | null, validation: FrontendWorkerRunReport["validation"], started: number): FrontendWorkerRunReport { return { frontendRunReportId: `few-run-${Date.now()}`, runTimestamp: new Date().toISOString(), action, engineRecord: this.engineRecord!, catalog: this.getCatalog(), frontendBuildReports: reports, latestFrontendBuildReport: latest, integrations: this.getIntegrations(), validation, durationMs: Date.now() - started, metadataVersion: FEW_METADATA_VERSION }; }
}
