import type { FrontendWorkerConfiguration } from "./configuration.js";
import type { FrontendWorkerDependencies } from "./integrations.js";
import { FrontendManager } from "./frontend-manager.js";
import type { EngineStatus, FrontendWorkerInput, FrontendWorkerRunReport } from "./types.js";
export class FrontendWorkerController {
  private status: EngineStatus = "idle"; private latest: FrontendWorkerRunReport | null = null;
  constructor(private readonly manager: FrontendManager, private readonly config: FrontendWorkerConfiguration) {}
  initialize() { this.manager.ensureSeeded(this.config); this.status = "active"; } bindIntegrations(deps: FrontendWorkerDependencies = {}) { this.manager.bindIntegrations(deps); }
  getStatus() { return this.status; } getManager() { return this.manager; } getConfiguration() { return structuredClone(this.config); } getLatestReport() { return this.latest; }
  connect(input: Record<string, unknown> = {}) { this.status = "connecting"; return this.finish(this.manager.connect(input, this.config)); }
  receiveApprovedRequirementsReports(i: FrontendWorkerInput = {}) { this.status = "receiving_requirements"; return this.finish(this.manager.receiveApprovedRequirementsReports(i, this.config)); } receiveApprovedRequirementsReport(i: FrontendWorkerInput = {}) { return this.receiveApprovedRequirementsReports(i); }
  receiveApprovedArchitectureReports(i: FrontendWorkerInput = {}) { this.status = "receiving_architecture"; return this.finish(this.manager.receiveApprovedArchitectureReports(i, this.config)); } receiveApprovedArchitectureReport(i: FrontendWorkerInput = {}) { return this.receiveApprovedArchitectureReports(i); }
  buildApplicationLayouts(i: FrontendWorkerInput = {}) { return this.finish(this.manager.buildApplicationLayouts(i, this.config)); } buildDashboards(i: FrontendWorkerInput = {}) { return this.finish(this.manager.buildDashboards(i, this.config)); } buildPages(i: FrontendWorkerInput = {}) { return this.finish(this.manager.buildPages(i, this.config)); } buildFormsAndInputValidation(i: FrontendWorkerInput = {}) { return this.finish(this.manager.buildFormsAndInputValidation(i, this.config)); } buildUserWorkflows(i: FrontendWorkerInput = {}) { return this.finish(this.manager.buildUserWorkflows(i, this.config)); } integrateApprovedApis(i: FrontendWorkerInput = {}) { return this.finish(this.manager.integrateApprovedApis(i, this.config)); } supportResponsiveAndAccessibleUi(i: FrontendWorkerInput = {}) { return this.finish(this.manager.supportResponsiveAndAccessibleUi(i, this.config)); } produceFrontendBuildReport(i: FrontendWorkerInput = {}) { return this.finish(this.manager.produceFrontendBuildReport(i, this.config)); } submitReport(i: FrontendWorkerInput = {}) { return this.finish(this.manager.submitReport(i, this.config)); } list() { return this.finish(this.manager.list(this.config)); } validate(i: FrontendWorkerInput = {}) { return this.finish(this.manager.validate(i, this.config)); } diagnostics() { return this.finish(this.manager.diagnostics(this.config)); }
  private finish(report: FrontendWorkerRunReport) { this.latest = report; this.status = report.validation.decision === "fail" ? "failed" : "active"; return report; }
}
