import type { ENGINE_STATUSES, FEW_CAPABILITIES, INTEGRATION_TARGETS, UI_COMPONENTS } from "./paths.js";
import type { FrontendWorkerConfiguration } from "./configuration.js";

export type EngineStatus = (typeof ENGINE_STATUSES)[number];
export type UiComponent = (typeof UI_COMPONENTS)[number];
export type IntegrationTarget = (typeof INTEGRATION_TARGETS)[number];
export type FrontendWorkerCapability = (typeof FEW_CAPABILITIES)[number];
export type BuildStatus = "draft" | "in_progress" | "complete" | "failed";
export type BuildEntry = { id: string; name: string; description: string; source?: string; fields?: string[]; validationRules?: string[] };
export type BuildStep = { stepId: string; stepType: string; title: string; order: number; summary: string };
export type ReviewFinding = { findingId: string; category: string; severity: "info" | "warning" | "error"; message: string };
export type PreservedDecision = { decisionId: string; topic: string; decision: string; recordedAt: string };
export type FrontendBuildReport = {
  buildId: string; timestamp: string; platformId: string; platformName: string; uiComponents: UiComponent[];
  pagesCreated: BuildEntry[]; dashboardsCreated: BuildEntry[]; formsCreated: BuildEntry[]; workflowScreens: BuildEntry[];
  apiIntegrations: BuildEntry[]; accessibilityStatus: "wcag_aa_pass" | "partial" | "pending"; buildStatus: BuildStatus;
  confidenceScore: number; metadataVersion: string; requirementsReportId: string; architectureReportId: string;
  factoryMissionId: string; businessId: string; businessObjective: string; layouts: BuildEntry[]; responsiveVerified: boolean;
  accessibilityFindings: string[]; buildSteps: BuildStep[]; selfReviewPassed: boolean; selfReviewFindings: ReviewFinding[];
  selfReviewSummary: string; qualityReview: string; complianceReview: string; frontendCompliance: "compliant" | "partial" | "non_compliant";
  frontendComplianceNotes: string; workerId: string; reportVersion: string; traceabilityRefs: string[];
  preservedDecisions: PreservedDecision[]; submittedToExecutiveReporting: boolean; executiveReportId: string | null;
  neverImplementBackendBusinessLogic: true; neverDesignDatabases: true; neverDeployApplications: true;
  neverOverridePillow: true; neverOverrideGrandKing: true; neverImplementQ605OrLater: true;
  followApprovedRequirementsAndArchitecture: true; preserveCompleteTraceability: true; buildReusableComponents: true;
  validateAccessibilityAndResponsiveness: true; preserveAuditHistory: true; structuralSignalOnly: true; maskSensitiveValues: true;
};
export type FrontendWorkerInput = {
  buildId?: string | null;
  requirementsReportId?: string | null;
  architectureReportId?: string | null;
  platformId?: string | null;
  platformName?: string | null;
  businessId?: string | null;
  factoryMissionId?: string | null;
  businessObjective?: string | null;
  validated?: boolean;
  implementBackendBusinessLogic?: boolean;
  designDatabases?: boolean;
  deployApplications?: boolean;
  overridePillow?: boolean;
  overrideGrandKing?: boolean;
  implementQ605OrLater?: boolean;
};
export type IntegrationHandshake = { target: IntegrationTarget; status: "ready" | "bound" | "unavailable"; details: string; timestamp: string };
export type FrontendWorkerValidationReport = { validationReportId: string; validationTimestamp: string; decision: "pass" | "partial" | "fail"; errors: string[]; warnings: string[]; durationMs: number; metadataVersion: string };
export type FrontendWorkerEngineRecord = { engineRecordId: string; timestamp: string; engineId: string; engineVersion: "PILLOW-FEW-001"; currentOperationalState: string; healthStatus: "healthy" | "degraded" | "failed" | "standby"; validationStatus: string; supportedCapabilities: FrontendWorkerCapability[]; totalFrontendBuildReports: number; lastFrontendBuildReportId: string | null; lastConfidenceScore: number | null; workerId: string; integrationTargets: IntegrationTarget[]; metadataVersion: string };
export type FrontendWorkerCatalog = { reportVersion: string; workerId: string; frontendBuildReports: FrontendBuildReport[]; integrations: IntegrationHandshake[]; metadataVersion: string; executiveAuthority: "pillow"; neverImplementBackendBusinessLogic: true; neverDesignDatabases: true; neverDeployApplications: true; neverOverridePillow: true; neverOverrideGrandKing: true; neverImplementQ605OrLater: true };
export type FrontendWorkerRunReport = { frontendRunReportId: string; runTimestamp: string; action: string; engineRecord: FrontendWorkerEngineRecord; catalog: FrontendWorkerCatalog | null; frontendBuildReports: FrontendBuildReport[]; latestFrontendBuildReport: FrontendBuildReport | null; integrations: IntegrationHandshake[]; validation: FrontendWorkerValidationReport; durationMs: number; metadataVersion: string };
export type FrontendWorkerState = { engineVersion: "PILLOW-FEW-001"; missionId: "Q6-04"; status: EngineStatus; initializedAt: string; configuration: FrontendWorkerConfiguration; latestReport: FrontendWorkerRunReport | null; engineRecord: FrontendWorkerEngineRecord | null; health: { status: "healthy" | "degraded" | "failed" | "standby"; healthScore: number; engineEnabled: boolean; lastOperationAt: string | null; lastValidationDecision: "pass" | "partial" | "fail" | null; totalFrontendBuildReports: number; lastFrontendBuildReportId: string | null; lastConfidenceScore: number | null; notes: string[] } };
export type FrontendWorkerCockpitSnapshot = { missionId: "Q6-04"; status: EngineStatus; healthStatus: "healthy" | "degraded" | "failed" | "standby"; totalFrontendBuildReports: number; latestFrontendBuildReportId: string | null; lastConfidenceScore: number | null; workerId: string; neverImplementBackendBusinessLogic: true; neverDesignDatabases: true; neverDeployApplications: true; neverImplementQ605OrLater: true };
