import type { ProductionComponentRecord } from "./types.js";

/** Canonical registry — every production subsystem with one documented state (P5-02). */
export const PRODUCTION_COMPONENT_REGISTRY: ProductionComponentRecord[] = [
  {
    id: "PM-BRAIN",
    domain: "brain",
    name: "Brain Executor",
    purpose: "Single dispatch hub — tools, LLM, Guardian, orchestrator",
    currentState: "production_enabled",
    productionState: "production_enabled",
    reason: "ADR-CON-003 — critical routes always registered",
    dependencies: ["Redis (optional degraded)", "SQLite", "Guardian"],
    owner: "Brain Runtime · P3-01",
    activationRules: "Always active on API boot · workers via worker.ts in production",
    knownLimitations: ["200+ tools at boot", "Degraded queue without Redis"],
    futureEvolution: "Postgres migration · worker colocation option",
  },
  {
    id: "PM-PILLOW",
    domain: "pillow",
    name: "Pillow COI",
    purpose: "Executive intelligence · mission planning · constitutional governance",
    currentState: "production_limited",
    productionState: "production_limited",
    reason: "CON-008 — production uses minimal chat path until EMPIRE_V1_OPERATIONAL_READY",
    dependencies: ["EMPIRE_V1_OPERATIONAL_READY", "Brain LLM Router"],
    owner: "Pillow Architecture · PILLOW-001",
    activationRules: "Lazy boot in production · full COI when operational ready flag set",
    knownLimitations: ["Sequential startPillow() chain", "First panel may 503 during boot"],
    futureEvolution: "Full COI production path when capacity allows",
  },
  {
    id: "PM-COCKPIT",
    domain: "cockpit",
    name: "Executive Cockpit",
    purpose: "Grand King operational surface — empireai-web",
    currentState: "production_enabled",
    productionState: "production_enabled",
    reason: "Critical auth + executive-home + pillow routes always available",
    dependencies: ["empireai-web", "Backend BFF", "Auth"],
    owner: "Cockpit Architecture · P2",
    activationRules: "Vercel deploy · BFF proxy to Railway backend",
    knownLimitations: ["ADR-CON-001 dual frontend pending resolution"],
    futureEvolution: "Single canonical client authority",
  },
  {
    id: "PM-BUILDER",
    domain: "builder",
    name: "Builder (Cursor Bridge)",
    purpose: "Supervised engineering missions via Cursor Protocol",
    currentState: "production_limited",
    productionState: "production_limited",
    reason: "ADR-CON-004 — requires approval gate; artifact dispatch default in prod",
    dependencies: ["Supervisor", "Cursor Protocol", "Vision Sync"],
    owner: "Builder Architecture · PILLOW-CB-001",
    activationRules: "Internal engineering use · Grand King override available",
    knownLimitations: ["SDK dispatch requires CURSOR_API_KEY"],
    futureEvolution: "Full autonomous dispatch when governance permits",
  },
  {
    id: "PM-GUARDIAN",
    domain: "guardian",
    name: "Guardian",
    purpose: "Pre-dispatch governance · health monitoring",
    currentState: "production_enabled",
    productionState: "production_enabled",
    reason: "GUARDIAN_ENABLED=true default · fail-closed on critical violations",
    dependencies: ["Brain orchestrator"],
    owner: "Brain Governance",
    activationRules: "GUARDIAN_ENABLED env var",
    knownLimitations: [],
    futureEvolution: "Expanded subsystem probes",
  },
  {
    id: "PM-SUPERVISOR",
    domain: "supervisor",
    name: "Cursor Supervisor",
    purpose: "Mission launch · monitor · recovery orchestration",
    currentState: "production_limited",
    productionState: "production_limited",
    reason: "Runs when Pillow session active — not always hot in minimal prod mode",
    dependencies: ["Pillow session", "Mission Planner"],
    owner: "Supervisor · PILLOW-007",
    activationRules: "Pillow boot required",
    knownLimitations: [],
    futureEvolution: "Always-on supervisor in full production mode",
  },
  {
    id: "PM-JOURNEY",
    domain: "journey",
    name: "Journey System",
    purpose: "Permanent execution history · traceability",
    currentState: "production_enabled",
    productionState: "production_enabled",
    reason: "P4-08 — governance layer; read-only JOURNEY.md truth",
    dependencies: ["JOURNEY.md", "Synchronizer for writes"],
    owner: "Journey · PILLOW-JR-001",
    activationRules: "Always available when Pillow initialized",
    knownLimitations: ["In-session store; disk via synchronizer"],
    futureEvolution: "Persistent journey archive",
  },
  {
    id: "PM-COMMERCE",
    domain: "commerce",
    name: "Commerce Intelligence",
    purpose: "Live commerce · Amazon · CJ integration",
    currentState: "production_limited",
    productionState: "production_limited",
    reason: "LIVE_COMMERCE_INTEGRATION_MODE=sandbox default · production requires credentials",
    dependencies: ["LIVE_COMMERCE_INTEGRATION_MODE", "CREDENTIAL_VAULT_KEY", "SP-API tokens"],
    owner: "Commerce · ADR-CON-006",
    activationRules: "Production mode + credential vault + marketplace tokens",
    knownLimitations: ["Fail-closed without credentials"],
    futureEvolution: "Multi-marketplace expansion",
  },
  {
    id: "PM-BUSINESS",
    domain: "business_engines",
    name: "Business Engines (REAL modules)",
    purpose: "Grand King business automation subsystems",
    currentState: "deferred",
    productionState: "deferred",
    reason: "EMPIRE_ENABLE_EXTENSION_ROUTES=false in production by default",
    dependencies: ["EMPIRE_ENABLE_EXTENSION_ROUTES"],
    owner: "Programme REAL namespace",
    activationRules: "Explicit env flag + 10min defer after boot",
    knownLimitations: ["~150 extension routes not registered in prod API"],
    futureEvolution: "Graduated production enablement per module",
  },
  {
    id: "PM-API-CRITICAL",
    domain: "api_routes",
    name: "Critical API Routes",
    purpose: "Auth · health · pillow · brain dispatch · events",
    currentState: "production_enabled",
    productionState: "production_enabled",
    reason: "Always registered at boot — earlyListen in production",
    dependencies: [],
    owner: "Brain API · app.ts",
    activationRules: "Unconditional at boot",
    knownLimitations: [],
    futureEvolution: "Route policy consolidation CON-007",
  },
  {
    id: "PM-API-EXT",
    domain: "api_routes",
    name: "Extension API Routes",
    purpose: "REAL module HTTP surfaces",
    currentState: "production_disabled",
    productionState: "production_disabled",
    reason: "ADR-CON-002 — gated off in production for stability",
    dependencies: ["EMPIRE_ENABLE_EXTENSION_ROUTES=true"],
    owner: "Brain API · index.ts",
    activationRules: "Opt-in env flag only",
    knownLimitations: ["Not available unless explicitly enabled"],
    futureEvolution: "Per-module production graduation",
  },
  {
    id: "PM-WORKERS",
    domain: "workers",
    name: "BullMQ Workers",
    purpose: "Background task processing",
    currentState: "production_disabled",
    productionState: "production_disabled",
    reason: "startWorkers=false in production API process",
    dependencies: ["Redis", "worker.ts separate process"],
    owner: "Brain Runtime · worker.ts",
    activationRules: "Run backend/src/worker.ts in production",
    knownLimitations: ["Queue no-op in degraded Redis mode"],
    futureEvolution: "Managed worker service on Railway",
  },
  {
    id: "PM-QUEUES",
    domain: "queues",
    name: "Task Queue (BullMQ)",
    purpose: "empireai-brain-tasks job queue",
    currentState: "production_limited",
    productionState: "production_limited",
    reason: "Enqueue available; processing requires worker process + Redis",
    dependencies: ["REDIS_URL", "worker.ts"],
    owner: "Brain · task-queue.ts",
    activationRules: "Redis connected or DegradedTaskQueue no-op",
    knownLimitations: ["Degraded mode silently drops jobs"],
    futureEvolution: "Production Redis mandatory policy",
  },
  {
    id: "PM-RUNTIME",
    domain: "runtime_modules",
    name: "Brain Runtime Governance",
    purpose: "P5-01 runtime stability monitoring",
    currentState: "production_enabled",
    productionState: "production_enabled",
    reason: "Pillow governance layer — always when Pillow active",
    dependencies: ["Pillow session"],
    owner: "PILLOW-BR-001",
    activationRules: "Pillow boot",
    knownLimitations: [],
    futureEvolution: "Live Brain metrics bridge expansion",
  },
  {
    id: "PM-INFRA",
    domain: "infrastructure",
    name: "V1 Split Stack",
    purpose: "Vercel · Railway · Upstash · SQLite volume",
    currentState: "production_enabled",
    productionState: "production_enabled",
    reason: "ADR-CON-005 — production validated split stack",
    dependencies: ["Railway", "Vercel", "Upstash optional"],
    owner: "Infrastructure · P3-06",
    activationRules: "Managed deployment pipeline",
    knownLimitations: ["SQLite single-writer", "Postgres migration pending"],
    futureEvolution: "PostgreSQL HA",
  },
  {
    id: "PM-FLAGS",
    domain: "feature_flags",
    name: "Feature Flag Registry",
    purpose: "Documented env gates for production behaviour",
    currentState: "production_enabled",
    productionState: "production_enabled",
    reason: "P5-02 — every flag documented in FEATURE_FLAG_REGISTRY",
    dependencies: [],
    owner: "Production Mode · PILLOW-PM-001",
    activationRules: "Always available via Cockpit panel",
    knownLimitations: [],
    futureEvolution: "Centralized flag service",
  },
  {
    id: "PM-EXT",
    domain: "extensions",
    name: "REAL Extension Modules",
    purpose: "Deferred business automation HTTP modules",
    currentState: "deferred",
    productionState: "deferred",
    reason: "Production stability — extension routes off by default",
    dependencies: ["EMPIRE_ENABLE_EXTENSION_ROUTES"],
    owner: "Programme governance",
    activationRules: "Explicit enable + defer timer",
    knownLimitations: ["Grand King must know extensions are off"],
    futureEvolution: "Module-by-module production graduation",
  },
];

export function getComponentsByState(state: import("./types.js").ProductionState): ProductionComponentRecord[] {
  return PRODUCTION_COMPONENT_REGISTRY.filter((c) => c.productionState === state);
}

export function getComponent(id: string): ProductionComponentRecord | undefined {
  return PRODUCTION_COMPONENT_REGISTRY.find((c) => c.id === id);
}
