import { readFileSync } from "node:fs"; import { join } from "node:path";
import type { EmpireBootstrapContext } from "../bootstrap/types.js"; import { buildTestingWorkerConfiguration } from "./configuration.js"; import { TESTING_WORKER_SYSTEM_PATH,TSW_INTEGRATION_TARGETS } from "./paths.js"; import type { CaseResult,CoverageSummary,FailureEvidence,RegressionFinding,RemediationRecommendation,TestCase,TestDomain,TestRunner,TestSuite,TestType,TestingBuildReport,TestingWorkerConfiguration,TestingWorkerDependencies,TestingWorkerState } from "./types.js"; import { InMemoryTestRunner } from "./test-runner.js"; import { validateTestingInput } from "./testing-validator.js"; import { bindTestingWorkerIntegrations } from "./integrations.js";
const id=(prefix:string)=>`${prefix}-${crypto.randomUUID()}`,now=()=>new Date().toISOString();
export class TestingWorkerEngine {
 private initializedAt:string|null=null;private deps:TestingWorkerDependencies={};private runner:TestRunner=new InMemoryTestRunner();private requirementsReportId?:string;private architectureReportId?:string;private baselineRunId?:string;
 readonly config:TestingWorkerConfiguration;readonly suites=new Map<string,TestSuite>();readonly cases=new Map<string,TestCase>();readonly runs=new Map<string,{runId:string;suiteIds:string[];startedAt:string;completedAt?:string;status:"in_progress"|"complete";results:CaseResult[]}>();readonly failures:FailureEvidence[]=[];readonly findings:RegressionFinding[]=[];readonly recommendations:RemediationRecommendation[]=[];readonly events:Array<{eventId:string;event:string;timestamp:string;data:Record<string,unknown>}>=[];readonly reports:TestingBuildReport[]=[];
 constructor(private bootstrap:{repositoryRoot:string}|EmpireBootstrapContext,options:{configuration?:Partial<TestingWorkerConfiguration>}={}){this.config=buildTestingWorkerConfiguration(bootstrap.repositoryRoot,options.configuration)}
 private audit(event:string,data:Record<string,unknown>={}){this.events.push({eventId:id("tsw-evt"),event,timestamp:now(),data})}
 async initialize(){let document="";try{document=readFileSync(join(this.bootstrap.repositoryRoot,TESTING_WORKER_SYSTEM_PATH),"utf8")}catch{throw new Error(`${TESTING_WORKER_SYSTEM_PATH} missing`)}if(!document.includes("Testing Worker"))throw new Error("Testing Worker governance document is invalid");this.initializedAt=now();this.audit("initialized",{doctrine:"PILLOW-TSW-001"});return this.getState()}
 bindIntegrations(deps:TestingWorkerDependencies={}){this.deps=bindTestingWorkerIntegrations(this.deps,deps);return this.deps}connect(deps:TestingWorkerDependencies={}){return this.bindIntegrations(deps)}
 getState():TestingWorkerState{return {engineVersion:"PILLOW-TSW-001",missionId:"Q6-13",status:this.initializedAt?"ready":"idle",initializedAt:this.initializedAt,configuration:this.config,latestReport:this.reports.at(-1)??null}}
 validate(input:Record<string,unknown>={}){return validateTestingInput(input)}diagnostics(){return {valid:this.validate().valid,suites:this.suites.size,cases:this.cases.size,targets:[...TSW_INTEGRATION_TARGETS]}}getCockpitSnapshot(){return {missionId:"Q6-13",status:this.getState().status,workerId:"wkr-testing-01",suites:this.suites.size,runs:this.runs.size,neverFabricateSuccessfulTests:true,neverImplementQ614OrLater:true}}validateForSupervisorSync(){return {valid:!!this.initializedAt,health:this.initializedAt?"healthy":"blocked",readinessScore:this.initializedAt?100:0,notes:[`Q6-13 ${this.getState().status}`]}}
 private checked(input:Record<string,unknown>){const result=this.validate(input);if(!result.valid)throw new Error(result.issues.join("; "))}
 receiveApprovedRequirementsReports(input:Record<string,unknown>={}){this.checked(input);this.requirementsReportId=String(input.reportId??id("tsw-bld"));return {buildId:id("tsw-bld"),requirementsReportId:this.requirementsReportId}}receiveApprovedRequirementsReport(input:Record<string,unknown>={}){return this.receiveApprovedRequirementsReports(input)}
 receiveApprovedArchitectureReports(input:Record<string,unknown>={}){this.checked(input);this.architectureReportId=String(input.reportId??id("tsw-bld"));return {buildId:id("tsw-bld"),architectureReportId:this.architectureReportId}}receiveApprovedArchitectureReport(input:Record<string,unknown>={}){return this.receiveApprovedArchitectureReports(input)}
 createSuite(input:{suiteId?:string;name:string;testType:TestType;domain?:TestDomain;validated?:boolean}){this.checked(input);const suite:TestSuite={suiteId:input.suiteId??id("tsw-suite"),name:input.name,testType:input.testType,domain:input.domain,validated:input.validated===true,createdAt:now()};this.suites.set(suite.suiteId,suite);this.audit("suite_created",{suiteId:suite.suiteId});return suite}
 generateTests(input:{suiteId?:string;testType:TestType;domain?:TestDomain;count?:number;requirementIds?:string[];names?:string[]}){this.checked(input);const suite=input.suiteId?this.suites.get(input.suiteId):this.createSuite({name:`${input.testType} generated suite`,testType:input.testType,domain:input.domain});if(!suite)throw new Error("Suite not found");const count=input.count??input.names?.length??1,created:TestCase[]=[];for(let i=0;i<count;i++)created.push(this.addTestCase({suiteId:suite.suiteId,name:input.names?.[i]??`${input.testType} case ${i+1}`,testType:input.testType,assertion:"Explicit runner assertion required",requirementId:input.requirementIds?.[i]}));return created}
 addTestCase(input:{suiteId:string;caseId?:string;name:string;testType:TestType;assertion?:string;requirementId?:string}){this.checked(input);const suite=this.suites.get(input.suiteId);if(!suite)throw new Error("Suite not found");const testCase:TestCase={caseId:input.caseId??id("tsw-case"),suiteId:input.suiteId,name:input.name,testType:input.testType,domain:suite.domain,assertion:input.assertion,requirementId:input.requirementId,status:"pending",createdAt:now()};this.cases.set(testCase.caseId,testCase);return testCase}
 generateUnitTests(){return this.generateTests({testType:"unit",domain:"backend"})}generateIntegrationTests(){return this.generateTests({testType:"integration",domain:"platform"})}generateEndToEndTests(){return this.generateTests({testType:"end_to_end",domain:"platform"})}generateUserAcceptanceTests(){return this.generateTests({testType:"acceptance",domain:"platform"})}
 setTestRunner(runner:TestRunner){this.runner=runner}configureCaseOutcome(input:{caseId:string;outcome:"passed"|"failed"|"skipped";evidence?:string;coverageDelta?:CoverageSummary}){if(!(this.runner instanceof InMemoryTestRunner))throw new Error("configureCaseOutcome requires InMemoryTestRunner");this.runner.configure(input.caseId,input);return input}
 async executeSuite(input:{suiteId:string;runId?:string}){if(!this.suites.has(input.suiteId))throw new Error("Suite not found");return this.executeCases([...this.cases.values()].filter(x=>x.suiteId===input.suiteId),input.runId)}
 async executeAll(input:{runId?:string}={}){return this.executeCases([...this.cases.values()],input.runId)}
 async executeAutomatedTestSuites(input:{runId?:string;suiteId?:string}={}){return input.suiteId?this.executeSuite({suiteId:input.suiteId,runId:input.runId}):this.executeAll(input)}
 private async executeCases(cases:TestCase[],runId?:string){const run=this.runs.get(runId??"")??{runId:runId??id("tsw-run"),suiteIds:[...new Set(cases.map(x=>x.suiteId))],startedAt:now(),status:"in_progress" as const,results:[]};for(const testCase of cases){const result=await this.runner.run(testCase),record:CaseResult={resultId:id("tsw-evt"),runId:run.runId,caseId:testCase.caseId,status:result.outcome,timestamp:now(),evidence:result.evidence,coverageDelta:result.coverageDelta};run.results.push(record);if(record.status==="failed")this.failures.push({failureId:id("tsw-evt"),runId:run.runId,caseId:testCase.caseId,message:record.evidence??"Test runner returned failed",evidence:record.evidence,createdAt:now()})}run.status="complete";run.completedAt=now();this.runs.set(run.runId,run);this.audit("tests_executed",{runId:run.runId,count:cases.length});return run}
 produceCodeCoverageMetrics(input:{runId?:string}={}){return this.getCoverage(input)}getCoverage(input:{runId?:string}={}){const run=input.runId?this.runs.get(input.runId):[...this.runs.values()].at(-1);const total:CoverageSummary={runId:run?.runId,lines:0,branches:0,functions:0,statements:0};for(const result of run?.results??[])for(const key of ["lines","branches","functions","statements"] as const)total[key]+=result.coverageDelta?.[key]??0;return total}
 setBaselineRun(input:{runId:string}){if(!this.runs.has(input.runId))throw new Error("Baseline run not found");this.baselineRunId=input.runId;return {runId:input.runId}}
 detectRegressions(input:{runId?:string}={}){const runId=input.runId??[...this.runs.values()].at(-1)?.runId;if(!runId||!this.baselineRunId)return [];const current=this.runs.get(runId),baseline=this.runs.get(this.baselineRunId);if(!current||!baseline)return [];const passed=new Set(baseline.results.filter(x=>x.status==="passed").map(x=>x.caseId));const found=current.results.filter(x=>x.status==="failed"&&passed.has(x.caseId)).map(x=>({findingId:id("tsw-reg"),runId,caseId:x.caseId,baselineRunId:this.baselineRunId!,message:"Case newly failed after baseline pass",createdAt:now()}));this.findings.push(...found);return found}
 recordFailuresWithEvidence(input:{runId?:string}={}){return this.getFailures(input.runId)}recordFailureEvidence(input:{caseId:string;runId:string;message:string;evidence?:string}){const failure:FailureEvidence={failureId:id("tsw-evt"),...input,createdAt:now()};this.failures.push(failure);return failure}
 produceRemediationRecommendations(input:{runId?:string}={}){return this.recommendRemediation(input)}recommendRemediation(input:{runId?:string}={}){const created=this.getFailures(input.runId).map(f=>({recommendationId:id("tsw-plt"),runId:f.runId,caseId:f.caseId,recommendation:`Investigate and correct failure: ${f.message}`,createdAt:now()}));this.recommendations.push(...created);return created}
 getSuites(){return [...this.suites.values()]}getTestCases(suiteId?:string){return [...this.cases.values()].filter(x=>!suiteId||x.suiteId===suiteId)}getRuns(){return [...this.runs.values()]}getResults(runId?:string){return runId?this.runs.get(runId)?.results??[]:this.getRuns().flatMap(x=>x.results)}getFailures(runId?:string){return this.failures.filter(x=>!runId||x.runId===runId)}getRecommendations(runId?:string){return this.recommendations.filter(x=>!runId||x.runId===runId)}getAuditEvents({limit=50}:{limit?:number}={}){return this.events.slice(-limit)}
 produceTestingBuildReport(input:{platformId?:string;platformName?:string;businessId?:string;businessObjective?:string}={}){const results=this.getResults(),report:TestingBuildReport={buildId:id("tsw-bld"),timestamp:now(),platformId:input.platformId,platformName:input.platformName??"EmpireAI",testSuites:this.getSuites(),testsExecuted:results.length,passed:results.filter(x=>x.status==="passed").length,failed:results.filter(x=>x.status==="failed").length,skipped:results.filter(x=>x.status==="skipped").length,coverageSummary:this.getCoverage(),regressionFindings:this.findings,criticalFailures:this.failures,recommendations:this.recommendations,auditStatus:"recorded",outstandingIssues:this.failures.map(x=>x.message),confidenceScore:results.length?results.filter(x=>x.status==="passed").length/results.length:0,metadataVersion:"TSW-001-v1",buildStatus:"complete",neverFabricateSuccessfulTests:true,neverModifyUnrelatedProductionCode:true,neverReplaceDeployment:true,neverReplaceCertification:true,neverImplementQ614OrLater:true,neverOverridePillowGrandKingApprovedArchitecture:true,followApprovedRequirementsAndArchitecture:true,preserveCompleteTraceability:true,preserveAuditHistory:true,preserveReproducibleTestExecution:true,requirementsReportId:this.requirementsReportId,architectureReportId:this.architectureReportId,factoryMissionId:"Q6-13",businessId:input.businessId,businessObjective:input.businessObjective,buildSteps:["generated test definitions","recorded explicit runner outcomes","analyzed recorded coverage"],selfReview:"Passed outcomes require explicit TestRunner results.",workerId:"wkr-testing-01",reportVersion:"TSW-RPT-v1",traceabilityRefs:results.map(x=>x.caseId),submittedToExecutiveReporting:false};this.reports.push(report);return report}
 submitReport(input:{platformId?:string;platformName?:string}={}){const report=this.produceTestingBuildReport(input),result=(this.deps.executiveReportingRuntime as {submitWorkerReport?:(v:unknown)=>unknown}|undefined)?.submitWorkerReport?.({missionId:"Q6-13",report}) as {records?:Array<{reportId?:string}>}|undefined;report.executiveReportId=result?.records?.[0]?.reportId;report.submittedToExecutiveReporting=!!report.executiveReportId;return report}list(){return [...this.reports]}
}
export { TestingWorkerEngine as TestingWorker };
export const createTestingWorker=(bootstrap:EmpireBootstrapContext,options?:{configuration?:Partial<TestingWorkerConfiguration>;dependencies?:TestingWorkerDependencies})=>{const engine=new TestingWorkerEngine(bootstrap,options);if(options?.dependencies)engine.bindIntegrations(options.dependencies);return engine};
export const resetTestingWorkerForTesting=()=>{};
