import assert from "node:assert/strict"; import path from "node:path"; import { beforeEach,describe,test } from "node:test"; import { runBootstrap } from "../../bootstrap/engine.js"; import { AIW_INTEGRATION_TARGETS,buildApiIntegrationWorkerConfiguration,createApiIntegrationWorker,InMemoryTestTransport,resetApiIntegrationWorkerForTesting } from "../../api-integration-worker/index.js";
const ROOT=path.resolve(import.meta.dirname,"..","..","..","..");async function build(){const w=createApiIntegrationWorker(await runBootstrap({repositoryRoot:ROOT,skipHeavyScans:true}));await w.initialize();return w} async function registered(w:Awaited<ReturnType<typeof build>>){return w.registerIntegration({name:"Supplier",providerType:"supplier",protocol:"rest",baseUrl:"https://supplier.example"})}
describe("Q6-10 API Integration Worker",()=>{beforeEach(resetApiIntegrationWorkerForTesting);
test("1 locks boundaries",()=>{const c=buildApiIntegrationWorkerConfiguration(ROOT,{neverExposeApiSecretsOrCredentials:false as never,neverImplementQ611OrLater:false as never});assert.equal(c.neverExposeApiSecretsOrCredentials,true);assert.equal(c.neverImplementQ611OrLater,true)});
test("2 initializes targets",async()=>{const w=await build();assert.equal(w.getState().missionId,"Q6-10");assert.ok(AIW_INTEGRATION_TARGETS.includes("billing_worker"));assert.ok(AIW_INTEGRATION_TARGETS.includes("secrets_management_system"))});
test("3 receives architecture reports",async()=>{const w=await build();assert.match(w.receiveApprovedRequirementsReports().buildId,/^aiw-bld-/);assert.match(w.receiveApprovedArchitectureReports().buildId,/^aiw-bld-/)});
test("4 registers credentials safely",async()=>{const w=await build(),i=await registered(w),r=w.storeCredentials({integrationId:i.integrationId,authMethod:"bearer",secret:"super-secret"});assert.equal("secret" in r,false);assert.equal(JSON.stringify(w.getCredentialRefs()).includes("super-secret"),false)});
test("5 authenticates only credentialed integrations",async()=>{const w=await build(),a=await registered(w),b=w.registerIntegration({name:"B",providerType:"custom",protocol:"rest"});w.storeCredentials({integrationId:a.integrationId,authMethod:"bearer",secret:"x"});assert.equal(w.authenticateIntegration({integrationId:a.integrationId}),true);assert.equal(w.authenticateIntegration({integrationId:b.integrationId}),false)});
test("6 records explicit transport outcomes",async()=>{const w=await build(),i=await registered(w);w.setTransport(new InMemoryTestTransport().set("GET https://supplier.example/",{status:200}));assert.equal((await w.executeRequest({integrationId:i.integrationId})).success,true);assert.equal((await w.executeRequest({integrationId:i.integrationId,path:"/missing"})).success,false)});
test("7 retries retryable outcomes",async()=>{const w=await build(),i=await registered(w);w.configureRetry({integrationId:i.integrationId,maxRetries:2,timeoutMs:100,baseDelayMs:0});w.setTransport(new InMemoryTestTransport().set("GET https://supplier.example/",[{status:503},{status:503},{status:200}]));assert.equal((await w.executeRequest({integrationId:i.integrationId})).attempts,3)});
test("8 limits requests",async()=>{const w=await build(),i=await registered(w);w.configureRateLimit({integrationId:i.integrationId,maxRequests:1,windowMs:1000});assert.equal((await w.executeRequest({integrationId:i.integrationId})).status,503);assert.equal((await w.executeRequest({integrationId:i.integrationId})).status,429)});
test("9 processes webhooks",async()=>{const w=await build(),i=w.registerIntegration({name:"hook",providerType:"custom",protocol:"webhook"});assert.equal((await w.processWebhook({integrationId:i.integrationId,eventType:"created",payload:{id:1}})).signatureValid,true)});
test("10 monitors health",async()=>{const w=await build(),i=await registered(w);await w.executeRequest({integrationId:i.integrationId});assert.equal(w.getHealth()[0]?.status,"degraded")});
test("11 produces safe complete report",async()=>{const w=await build(),i=await registered(w);w.storeCredentials({integrationId:i.integrationId,authMethod:"bearer",secret:"hidden"});const r=w.produceApiIntegrationBuildReport();assert.equal(r.buildStatus,"complete");assert.equal(JSON.stringify(r).includes("hidden"),false)});
test("12 validates ERR constraints",async()=>{const w=await build();assert.equal(w.validate({missionId:"Q6-11"}).valid,false);assert.equal(w.validate({fabricateIntegrationSuccess:true}).valid,false);assert.equal(w.validate({implementQ611OrLater:true}).valid,false);assert.equal(w.getCockpitSnapshot().missionId,"Q6-10")});
});
