import assert from "node:assert/strict";
import path from "node:path";
import { beforeEach, describe, test } from "node:test";
import { runBootstrap } from "../../bootstrap/engine.js";
import { AZW_INTEGRATION_TARGETS, buildAuthorizationWorkerConfiguration, createAuthorizationWorker, resetAuthorizationWorkerForTesting } from "../../authorization-worker/index.js";
const root = path.resolve(import.meta.dirname, "..", "..", "..", "..");
const input = { requirementsReportId: "rqw-req-01", architectureReportId: "arw-arch-01", platformId: "azw-plt-01", platformName: "Platform", businessId: "azw-biz-01", factoryMissionId: "azw-msn-01", businessObjective: "Protect platform resources", validated: true };
const requirementsWorker = { getRequirementsReports: () => [{ requirementsId: input.requirementsReportId }], getLatestRequirementsReportId: () => input.requirementsReportId };
const architectureWorker = { getArchitectureReports: () => [{ architectureId: input.architectureReportId }], getLatestArchitectureReportId: () => input.architectureReportId };
const authenticationWorker = { validateSession: ({ sessionToken }: { sessionToken: string }) => { if (sessionToken === "valid") return { userId: "user-1", sessionId: "s-1", expiresAt: "2099-01-01", status: "active" }; if (sessionToken === "inactive") return { userId: "user-1", status: "revoked" }; throw new Error("invalid session"); } };
async function build(dependencies: Record<string, unknown> = {}) { const bootstrap = await runBootstrap({ repositoryRoot: root, skipHeavyScans: true }); const engine = createAuthorizationWorker(bootstrap, { dependencies: { requirementsWorker, architectureWorker, backendWorker: {}, databaseWorker: {}, authenticationWorker, ...dependencies } }); await engine.initialize(); engine.connect(); return engine; }
describe("Q6-08 Authorization Worker", () => {
  beforeEach(resetAuthorizationWorkerForTesting);
  test("1 force locks boundaries", () => { const config = buildAuthorizationWorkerConfiguration(root, { defaultDeny: false as never }); assert.equal(config.defaultDeny, true); assert.equal(config.neverAuthenticateUsers, true); assert.equal(config.neverImplementQ609OrLater, true); });
  test("2 initializes required identity and targets", async () => { const engine = await build(); assert.equal(engine.getState().missionId, "Q6-08"); assert.equal(engine.getState().engineVersion, "PILLOW-AZW-001"); assert.ok(AZW_INTEGRATION_TARGETS.includes("authentication_worker")); });
  test("3 receives approved reports", async () => { const engine = await build(); assert.ok(engine.receiveApprovedRequirementsReports(input).latestAuthorizationBuildReport!.buildId.startsWith("azw-bld-")); assert.equal(engine.receiveApprovedArchitectureReports(input).latestAuthorizationBuildReport!.architectureReportId, input.architectureReportId); });
  test("4 creates roles and permissions", async () => { const engine = await build(); assert.ok(engine.createRole({ name: "Reader" }).roleId.startsWith("azw-role-")); assert.ok(engine.createPermission({ name: "Read", resource: "reports", action: "read" }).permissionId.startsWith("azw-perm-")); });
  test("5 allows a permitted assigned role", async () => { const engine = await build(); const role = engine.createRole({ name: "Reader" }); engine.createPolicy({ name: "read reports", effect: "allow", roleId: role.roleId, resource: "reports", action: "read" }); engine.assignRole({ principalId: "user-1", roleId: role.roleId }); assert.equal(engine.evaluateAccess({ sessionToken: "valid", resource: "reports", action: "read" }).decision, "allow"); });
  test("6 denies unauthorized resources", async () => { const engine = await build(); const role = engine.createRole({ name: "Reader" }); engine.createPolicy({ name: "read reports", effect: "allow", roleId: role.roleId, resource: "reports", action: "read" }); engine.assignRole({ principalId: "user-1", roleId: role.roleId }); assert.equal(engine.evaluateAccess({ principalId: "user-1", resource: "billing", action: "read" }).decision, "deny"); });
  test("7 default denies missing identity", async () => { const engine = await build(); assert.equal(engine.evaluateAccess({ resource: "reports", action: "read" }).decision, "deny"); });
  test("8 deny policy overrides allow", async () => { const engine = await build(); const role = engine.createRole({ name: "Editor" }); engine.assignRole({ principalId: "user-1", roleId: role.roleId }); engine.createPolicy({ name: "allow", effect: "allow", roleId: role.roleId, resource: "reports", action: "write" }); engine.createPolicy({ name: "deny", effect: "deny", roleId: role.roleId, resource: "reports", action: "write" }); assert.equal(engine.evaluateAccess({ principalId: "user-1", resource: "reports", action: "write" }).decision, "deny"); });
  test("9 inherited parent policy allows child", async () => { const engine = await build(); const parent = engine.createRole({ name: "Parent" }); const child = engine.createRole({ name: "Child", parentRoleId: parent.roleId }); engine.createPolicy({ name: "parent read", effect: "allow", roleId: parent.roleId, resource: "reports", action: "read" }); engine.assignRole({ principalId: "user-1", roleId: child.roleId }); assert.equal(engine.evaluateAccess({ principalId: "user-1", resource: "reports", action: "read" }).decision, "allow"); });
  test("10 invalid sessions deny", async () => { const engine = await build(); assert.equal(engine.evaluateAccess({ sessionToken: "invalid", resource: "reports", action: "read" }).decision, "deny"); assert.equal(engine.evaluateAccess({ sessionToken: "inactive", resource: "reports", action: "read" }).decision, "deny"); });
  test("11 builds complete traceable report", async () => { const engine = await build(); const report = engine.produceAuthorizationBuildReport(input).latestAuthorizationBuildReport!; assert.equal(report.buildStatus, "complete"); assert.equal(report.neverAuthenticateUsers, true); assert.equal(report.canonicalAuthzReference, "backend/src/auth/permissions.ts"); });
  test("12 rejects forbidden scope and exposes cockpit audit", async () => { const engine = await build({ executiveReportingRuntime: { submitWorkerReport: () => ({ records: [{ reportId: "ert-azw-01" }] }) } }); assert.equal(engine.produceAuthorizationBuildReport({ ...input, factoryMissionId: "Q6-08", authenticateUser: true }).validation.decision, "fail"); assert.equal(engine.produceAuthorizationBuildReport({ ...input, implementQ609OrLater: true }).validation.decision, "fail"); engine.evaluateAccess({ resource: "reports", action: "read" }); assert.equal(engine.getCockpitSnapshot().missionId, "Q6-08"); assert.ok(engine.getAuthorizationAuditEvents().length > 0); });
});
