import assert from "node:assert/strict";
import path from "node:path";
import { beforeEach, describe, test } from "node:test";
import { runBootstrap } from "../../bootstrap/engine.js";
import { BEW_INTEGRATION_TARGETS, buildBackendWorkerConfiguration, createBackendWorker, resetBackendWorkerForTesting } from "../../backend-worker/index.js";
const root = path.resolve(import.meta.dirname, "..", "..", "..", "..");
const input = { requirementsReportId: "rqw-req-saas-01", architectureReportId: "arw-arch-saas-01", platformId: "epfc-plt-saas-01", platformName: "EmpireAI SaaS Platform", businessId: "epfc-biz-saas-01", factoryMissionId: "epfc-msn-saas-01", businessObjective: "Coordinate enterprise lifecycle.", validated: true };
const requirementsWorker = { getRequirementsReports: () => [{ requirementsId: input.requirementsReportId, platformId: input.platformId, platformName: input.platformName, businessId: input.businessId, factoryMissionId: input.factoryMissionId, businessObjective: input.businessObjective }], getLatestRequirementsReportId: () => input.requirementsReportId };
const architectureWorker = { getArchitectureReports: () => [{ architectureId: input.architectureReportId, platformId: input.platformId, platformName: input.platformName, businessId: input.businessId, factoryMissionId: input.factoryMissionId, businessObjective: input.businessObjective, requirementsReportId: input.requirementsReportId, apiArchitecture: [{ apiId: "arw-api-1", name: "Platform API", protocol: "REST", endpoints: ["/v1/platform"], direction: "external" }] }], getLatestArchitectureReportId: () => input.architectureReportId };
const frontendWorker = { getFrontendBuildReports: () => [{ buildId: "few-bld-01", platformId: input.platformId, architectureReportId: input.architectureReportId, requirementsReportId: input.requirementsReportId }], getLatestFrontendBuildReportId: () => "few-bld-01" };
async function build() { const bootstrap = await runBootstrap({ repositoryRoot: root, skipHeavyScans: true }); const engine = createBackendWorker(bootstrap, { dependencies: { requirementsWorker, architectureWorker, frontendWorker } }); await engine.initialize(); engine.connect(); return engine; }
describe("Q6-05 Backend Worker", () => {
  beforeEach(resetBackendWorkerForTesting);
  test("1 locks mandatory boundaries", () => { const config = buildBackendWorkerConfiguration(root, { neverBuildFrontendUi: false as never, neverImplementQ606OrLater: false as never }); assert.equal(config.neverBuildFrontendUi, true); assert.equal(config.neverImplementQ606OrLater, true); });
  test("2 initializes with integrations", async () => { const state = (await build()).getState(); assert.equal(state.missionId, "Q6-05"); assert.equal(state.engineVersion, "PILLOW-BEW-001"); for (const target of BEW_INTEGRATION_TARGETS) assert.ok(state.configuration.integrationTargets.includes(target)); assert.ok(state.configuration.integrationTargets.includes("frontend_worker")); });
  test("3 receives requirements", async () => { const report = (await build()).receiveApprovedRequirementsReports(input).latestBackendBuildReport!; assert.ok(report.buildId.startsWith("bew-bld-")); assert.equal(report.requirementsReportId, input.requirementsReportId); });
  test("4 receives architecture", async () => { const engine = await build(); engine.receiveApprovedRequirementsReports(input); assert.equal(engine.receiveApprovedArchitectureReports(input).latestBackendBuildReport!.architectureReportId, "arw-arch-saas-01"); });
  test("5 builds APIs and business logic", async () => { const engine = await build(); engine.receiveApprovedRequirementsReports(input); engine.receiveApprovedArchitectureReports(input); assert.ok(engine.buildRestAndGraphqlApis(input).latestBackendBuildReport!.apisImplemented.length); assert.ok(engine.implementBusinessLogic(input).latestBackendBuildReport!.servicesImplemented[0]!.id.startsWith("bew-svc-")); });
  test("6 configures auth and integrations", async () => { const engine = await build(); engine.receiveApprovedRequirementsReports(input); engine.receiveApprovedArchitectureReports(input); assert.equal(engine.implementAuthenticationAndAuthorization(input).latestBackendBuildReport!.authenticationStatus, "configured"); assert.ok(engine.implementExternalApiIntegrations(input).latestBackendBuildReport!.integrationsCompleted[0]!.id.startsWith("bew-int-")); });
  test("7 builds jobs validation and modular services", async () => { const engine = await build(); engine.receiveApprovedRequirementsReports(input); engine.receiveApprovedArchitectureReports(input); engine.implementBackgroundWorkersAndScheduledJobs(input); engine.implementValidationAndErrorHandling(input); const report = engine.produceSecureMaintainableBackendModules(input).latestBackendBuildReport!; assert.ok(report.backgroundJobs.length && report.validationRules.length); assert.equal(report.configurationManagement, "configured"); });
  test("8 produces complete report with minimum fields", async () => { const report = (await build()).produceBackendBuildReport(input).latestBackendBuildReport!; assert.ok(report.apisImplemented.length && report.servicesImplemented.length && report.integrationsCompleted.length && report.backgroundJobs.length && report.middleware.length && report.validationRules.length); assert.equal(report.buildStatus, "complete"); assert.equal(report.selfReviewPassed, true); assert.equal(report.metadataVersion, "BEW-001-v1"); });
  test("9 rejects forbidden boundary attempts", async () => { const engine = await build(); for (const forbidden of [{ buildFrontendUi: true }, { designNewRequirements: true }, { overrideApprovedArchitecture: true }, { overridePillow: true }, { overrideGrandKing: true }, { implementQ606OrLater: true }]) assert.equal(engine.produceBackendBuildReport({ ...input, ...forbidden }).validation.decision, "fail"); });
  test("10 lists submits cockpit and audit", async () => { const submitted: string[] = []; const bootstrap = await runBootstrap({ repositoryRoot: root, skipHeavyScans: true }); const engine = createBackendWorker(bootstrap, { dependencies: { requirementsWorker, architectureWorker, frontendWorker, executiveReportingRuntime: { submitWorkerReport: (record) => { submitted.push(String(record.missionId)); return { records: [{ reportId: "ert-bew-01" }] }; } } } }); await engine.initialize(); engine.connect(); const built = engine.produceBackendBuildReport(input); const submittedReport = engine.submitReport({ buildId: built.latestBackendBuildReport!.buildId, validated: true }); assert.deepEqual(submitted, ["Q6-05"]); assert.equal(submittedReport.latestBackendBuildReport!.executiveReportId, "ert-bew-01"); assert.ok(engine.list().backendBuildReports.length && engine.getAuditTrail().length); assert.equal(engine.getCockpitSnapshot().missionId, "Q6-05"); });
});
