import assert from "node:assert/strict"; import path from "node:path"; import { beforeEach,describe,test } from "node:test"; import { runBootstrap } from "../../bootstrap/engine.js"; import { BLW_CAPABILITIES, INTEGRATION_TARGETS, buildBillingWorkerConfiguration, createBillingWorker, resetBillingWorkerForTesting } from "../../billing-worker/index.js";
const ROOT=path.resolve(import.meta.dirname,"..","..","..",".."); async function build(){const worker=createBillingWorker(await runBootstrap({repositoryRoot:ROOT,skipHeavyScans:true}));await worker.initialize();return worker;}
describe("Q6-09 Billing Worker",()=>{beforeEach(resetBillingWorkerForTesting);
test("1 locks boundary configuration",()=>{const c=buildBillingWorkerConfiguration(ROOT,{neverFabricateSuccessfulPaymentResults:false as never,neverReplacePaymentGatewayIntegrations:false as never,neverImplementQ610OrLater:false as never});assert.equal(c.neverFabricateSuccessfulPaymentResults,true);assert.equal(c.neverReplacePaymentGatewayIntegrations,true);assert.equal(c.neverImplementQ610OrLater,true)});
test("2 initializes Q6-09 targets",async()=>{const w=await build();assert.equal(w.getState().engineVersion,"PILLOW-BLW-001");assert.ok(INTEGRATION_TARGETS.includes("authentication_worker"));assert.ok(INTEGRATION_TARGETS.includes("authorization_worker"));assert.ok(BLW_CAPABILITIES.includes("generate_invoices"))});
test("3 receives requirements architecture",async()=>{const w=await build();assert.ok(w.receiveApprovedRequirementsReports().buildId.startsWith("blw-bld-"));assert.ok(w.receiveApprovedArchitectureReports().buildId.startsWith("blw-bld-"))});
test("4 creates account and plan",async()=>{const w=await build();const a=w.createBillingAccount({customerId:"c"}),p=w.createSubscriptionPlan({name:"Pro",interval:"monthly",amountCents:1000,currency:"USD"});assert.equal(a.customerId,"c");assert.equal(p.amountCents,1000)});
test("5 creates active or trialing subscription",async()=>{const w=await build(),a=w.createBillingAccount({}),p=w.createSubscriptionPlan({name:"Trial",interval:"monthly",amountCents:1,currency:"USD",trialDays:7});assert.equal(w.createSubscription({accountId:a.accountId,planId:p.planId}).status,"trialing")});
test("6 generates and issues invoice",async()=>{const w=await build(),a=w.createBillingAccount({});const i=w.generateInvoice({accountId:a.accountId,lineItems:[{description:"x",amountCents:1}]});assert.match(i.invoiceNumber,/^INV-\d{4}-\d{6}$/);assert.equal(w.issueInvoice({invoiceId:i.invoiceId}).status,"issued")});
test("7 records success then marks paid",async()=>{const w=await build(),a=w.createBillingAccount({}),i=w.generateInvoice({accountId:a.accountId});w.issueInvoice({invoiceId:i.invoiceId});w.recordPaymentProviderResult({invoiceId:i.invoiceId,status:"succeeded"});assert.equal(w.markInvoicePaid({invoiceId:i.invoiceId}).status,"paid")});
test("8 forbids fabricated paid status",async()=>{const w=await build(),a=w.createBillingAccount({}),i=w.generateInvoice({accountId:a.accountId});assert.throws(()=>w.markInvoicePaid({invoiceId:i.invoiceId}))});
test("9 records refund lifecycle",async()=>{const w=await build(),a=w.createBillingAccount({}),i=w.generateInvoice({accountId:a.accountId,lineItems:[{description:"x",amountCents:100}]});assert.equal(w.recordRefund({invoiceId:i.invoiceId,amountCents:50}).amountCents,50);assert.equal(w.getInvoices()[0]?.status,"partially_refunded")});
test("10 creates credit note and history",async()=>{const w=await build(),a=w.createBillingAccount({});w.createCreditNote({accountId:a.accountId,amountCents:10});assert.equal(w.getBillingHistory(a.accountId).creditNotes.length,1);assert.ok(w.getBillingAuditEvents().length>0)});
test("11 builds complete report",async()=>{const r=(await build()).produceBillingBuildReport();assert.equal(r.buildStatus,"complete");assert.equal(r.canonicalPaymentGatewayReference,"pillow/src/payment-gateway-integration/");assert.equal(r.neverFabricateSuccessfulPaymentResults,true)});
test("12 rejects wrong mission and forbidden inputs",async()=>{const w=await build();assert.equal(w.validate({missionId:"Q6-10"}).valid,false);assert.equal(w.validate({fabricatePaymentSuccess:true}).valid,false);assert.equal(w.validate({implementQ610OrLater:true}).valid,false);assert.equal(w.getCockpitSnapshot().missionId,"Q6-09")});
});
