import assert from "node:assert/strict";
import path from "node:path";
import { beforeEach, describe, test } from "node:test";
import { runBootstrap } from "../../bootstrap/engine.js";
import { DBW_INTEGRATION_TARGETS, buildDatabaseWorkerConfiguration, createDatabaseWorker, resetDatabaseWorkerForTesting } from "../../database-worker/index.js";

const root = path.resolve(import.meta.dirname, "..", "..", "..", "..");
const input = { requirementsReportId: "rqw-req-saas-01", architectureReportId: "arw-arch-saas-01", platformId: "epfc-plt-saas-01", platformName: "EmpireAI SaaS Platform", businessId: "epfc-biz-saas-01", factoryMissionId: "epfc-msn-saas-01", businessObjective: "Coordinate enterprise lifecycle.", validated: true };
const requirementsWorker = { getRequirementsReports: () => [{ requirementsId: input.requirementsReportId, platformId: input.platformId, platformName: input.platformName, businessId: input.businessId, factoryMissionId: input.factoryMissionId, businessObjective: input.businessObjective }], getLatestRequirementsReportId: () => input.requirementsReportId };
const architectureWorker = { getArchitectureReports: () => [{ architectureId: input.architectureReportId, platformId: input.platformId, platformName: input.platformName, businessId: input.businessId, factoryMissionId: input.factoryMissionId, businessObjective: input.businessObjective, requirementsReportId: input.requirementsReportId, moduleArchitecture: [{ id: "arw-mod-core", name: "Core Platform" }] }], getLatestArchitectureReportId: () => input.architectureReportId };
const backendWorker = { getBackendBuildReports: () => [{ buildId: "bew-bld-01", platformId: input.platformId, architectureReportId: input.architectureReportId, requirementsReportId: input.requirementsReportId, servicesImplemented: [{ id: "bew-svc-01", name: "Core service" }] }], getLatestBackendBuildReportId: () => "bew-bld-01" };
async function build() { const bootstrap = await runBootstrap({ repositoryRoot: root, skipHeavyScans: true }); const engine = createDatabaseWorker(bootstrap, { dependencies: { requirementsWorker, architectureWorker, backendWorker } }); await engine.initialize(); engine.connect(); return engine; }
describe("Q6-06 Database Worker", () => {
  beforeEach(resetDatabaseWorkerForTesting);
  test("1 locks mandatory boundaries", () => { const config = buildDatabaseWorkerConfiguration(root, { neverBuildFrontend: false as never, neverImplementQ607OrLater: false as never }); assert.equal(config.neverBuildFrontend, true); assert.equal(config.neverImplementQ607OrLater, true); });
  test("2 initializes with integrations", async () => { const state = (await build()).getState(); assert.equal(state.missionId, "Q6-06"); assert.equal(state.engineVersion, "PILLOW-DBW-001"); for (const target of DBW_INTEGRATION_TARGETS) assert.ok(state.configuration.integrationTargets.includes(target)); assert.ok(state.configuration.integrationTargets.includes("backend_worker")); });
  test("3 receives requirements", async () => { const report = (await build()).receiveApprovedRequirementsReports(input).latestDatabaseBuildReport!; assert.ok(report.buildId.startsWith("dbw-bld-")); assert.equal(report.requirementsReportId, input.requirementsReportId); });
  test("4 receives architecture", async () => { const engine = await build(); engine.receiveApprovedRequirementsReports(input); assert.equal(engine.receiveApprovedArchitectureReports(input).latestDatabaseBuildReport!.architectureReportId, "arw-arch-saas-01"); });
  test("5 designs schemas and structures", async () => { const engine = await build(); engine.receiveApprovedRequirementsReports(input); engine.receiveApprovedArchitectureReports(input); assert.ok(engine.designRelationalAndNonRelationalSchemas(input).latestDatabaseBuildReport!.schemasCreated.length); const report = engine.createTablesRelationshipsAndConstraints(input).latestDatabaseBuildReport!; assert.ok(report.tablesCreated.length && report.relationships.length && report.constraints.length); });
  test("6 creates indexes and migrations", async () => { const engine = await build(); engine.receiveApprovedRequirementsReports(input); engine.receiveApprovedArchitectureReports(input); assert.ok(engine.createIndexesForPerformance(input).latestDatabaseBuildReport!.indexes[0]!.id.startsWith("dbw-idx-")); assert.equal(engine.generateDatabaseMigrations(input).latestDatabaseBuildReport!.migrationStatus, "generated"); });
  test("7 validates integrity recovery and optimization", async () => { const engine = await build(); engine.receiveApprovedRequirementsReports(input); engine.receiveApprovedArchitectureReports(input); engine.designRelationalAndNonRelationalSchemas(input); engine.createTablesRelationshipsAndConstraints(input); assert.equal(engine.validateReferentialIntegrity(input).latestDatabaseBuildReport!.integrityValidation, "passed"); engine.supportBackupAndRecoveryPlanning(input); const report = engine.produceOptimizedProductionReadyDatabaseStructures(input).latestDatabaseBuildReport!; assert.ok(report.backupStrategy && report.views.length); });
  test("8 produces complete report with minimum fields", async () => { const report = (await build()).produceDatabaseBuildReport(input).latestDatabaseBuildReport!; assert.ok(report.schemasCreated.length && report.tablesCreated.length && report.relationships.length && report.indexes.length && report.constraints.length && report.views.length && report.primaryKeys.length && report.foreignKeys.length && report.seedData.length); assert.equal(report.migrationStatus, "generated"); assert.equal(report.integrityValidation, "passed"); assert.equal(report.selfReviewPassed, true); assert.equal(report.metadataVersion, "DBW-001-v1"); });
  test("9 rejects forbidden boundary attempts", async () => { const engine = await build(); for (const forbidden of [{ buildFrontend: true }, { buildBackendBusinessLogic: true }, { overrideApprovedArchitecture: true }, { overridePillow: true }, { overrideGrandKing: true }, { implementQ607OrLater: true }, { implementApplicationBusinessLogic: true }]) assert.equal(engine.produceDatabaseBuildReport({ ...input, ...forbidden }).validation.decision, "fail"); });
  test("10 lists submits cockpit and audit", async () => { const submitted: string[] = []; const bootstrap = await runBootstrap({ repositoryRoot: root, skipHeavyScans: true }); const engine = createDatabaseWorker(bootstrap, { dependencies: { requirementsWorker, architectureWorker, backendWorker, executiveReportingRuntime: { submitWorkerReport: (record) => { submitted.push(String(record.missionId)); return { records: [{ reportId: "ert-dbw-01" }] }; } } } }); await engine.initialize(); engine.connect(); const built = engine.produceDatabaseBuildReport(input); const sent = engine.submitReport({ buildId: built.latestDatabaseBuildReport!.buildId, validated: true }); assert.deepEqual(submitted, ["Q6-06"]); assert.equal(sent.latestDatabaseBuildReport!.executiveReportId, "ert-dbw-01"); assert.ok(engine.list().databaseBuildReports.length && engine.getAuditTrail().length); assert.equal(engine.getCockpitSnapshot().missionId, "Q6-06"); });
});
