import assert from "node:assert/strict"; import path from "node:path"; import { describe,test } from "node:test"; import { runBootstrap } from "../../bootstrap/engine.js"; import { buildDeploymentWorkerConfiguration,createDeploymentWorker,DPW_INTEGRATION_TARGETS } from "../../deployment-worker/index.js";
const ROOT=path.resolve(import.meta.dirname,"..","..","..",".."); async function build(){const worker=createDeploymentWorker(await runBootstrap({repositoryRoot:ROOT,skipHeavyScans:true}));await worker.initialize();return worker} async function ready(w:Awaited<ReturnType<typeof build>>,version="1.0.0"){const p=w.createPackage({applicationVersion:version});w.markBuildValidated({packageId:p.packageId,testingEvidenceId:"testing-evidence-approved"});return p}
describe("Q6-14 Deployment Worker",()=>{
 test("1 boundary locks force true",()=>{const c=buildDeploymentWorkerConfiguration(ROOT,{neverFabricateSuccessfulDeploymentResults:false as never,neverDeployUnvalidatedBuilds:false as never});assert.equal(c.neverFabricateSuccessfulDeploymentResults,true);assert.equal(c.neverDeployUnvalidatedBuilds,true)});
 test("2 initializes doctrine and targets",async()=>{const w=await build();assert.equal(w.getState().missionId,"Q6-14");assert.ok(DPW_INTEGRATION_TARGETS.includes("testing_worker"))});
 test("3 receives requirements and architecture",async()=>{const w=await build();assert.match(w.receiveApprovedRequirementsReports().buildId,/^dpw-bld-/);assert.match(w.receiveApprovedArchitectureReports().buildId,/^dpw-bld-/)});
 test("4 validates readiness",async()=>{const w=await build(),p=w.createPackage({applicationVersion:"1"});assert.equal(w.validateReadiness({packageId:p.packageId,environment:"development"}).ready,false);w.markBuildValidated({packageId:p.packageId,testingEvidenceId:"evidence"});assert.equal(w.validateReadiness({packageId:p.packageId,environment:"development"}).ready,true)});
 test("5 generates deployment package",async()=>{const w=await build();assert.match(w.createPackage({applicationVersion:"1",artifactRefs:["artifact://x"]}).packageId,/^dpw-pkg-/)});
 test("6 executes only configured success",async()=>{const w=await build(),p=await ready(w),failed=await w.deploy({packageId:p.packageId,environment:"development"});assert.equal(failed.status,"failed");w.configureExecutorSuccess({key:"staging",success:true});const success=await w.deploy({packageId:p.packageId,environment:"staging"});assert.equal(success.status,"success")});
 test("7 health checks require probe",async()=>{const w=await build(),p=await ready(w);w.configureExecutorSuccess({key:"development",success:true});const d=await w.deploy({packageId:p.packageId,environment:"development"});assert.equal((await w.runHealthChecks({deploymentId:d.deploymentId})).healthy,false);w.configureHealthSuccess({key:d.deploymentId,success:true});assert.equal((await w.runHealthChecks({deploymentId:d.deploymentId})).healthy,true)});
 test("8 rolls back to previous success",async()=>{const w=await build(),a=await ready(w,"1"),b=await ready(w,"2");w.configureExecutorSuccess({key:"development",success:true});const v1=await w.deploy({packageId:a.packageId,environment:"development"}),v2=await w.deploy({packageId:b.packageId,environment:"development"});w.configureExecutorSuccess({key:`rollback:${v2.deploymentId}`,success:true});const rollback=await w.rollback({deploymentId:v2.deploymentId});assert.equal(rollback.status,"success");assert.equal(rollback.previousDeploymentId,v1.deploymentId)});
 test("9 records deployment history",async()=>{const w=await build(),p=await ready(w);w.configureExecutorSuccess({key:"development",success:true});await w.deploy({packageId:p.packageId,environment:"development"});assert.equal(w.getHistory().length,1)});
 test("10 gates production approval",async()=>{const w=await build(),p=await ready(w);await assert.rejects(w.deploy({packageId:p.packageId,environment:"production"}));const gate=w.requestDeploymentApproval({packageId:p.packageId,environment:"production"});w.approveDeployment({gateId:gate.gateId,decision:"approved"});w.configureExecutorSuccess({key:"production",success:true});const d=await w.deploy({packageId:p.packageId,environment:"production"});w.configureHealthSuccess({key:"production",success:true});assert.equal(d.status,"success");assert.equal((await w.runHealthChecks({deploymentId:d.deploymentId})).healthy,true)});
 test("11 produces complete deployment report",async()=>{const w=await build(),p=await ready(w);w.configureExecutorSuccess({key:"development",success:true});await w.deploy({packageId:p.packageId,environment:"development"});const report=w.produceDeploymentBuildReport();assert.equal(report.buildStatus,"complete");assert.equal(report.metadataVersion,"DPW-001-v1");assert.equal(report.neverBypassApprovalGates,true)});
 test("12 rejects forbidden inputs and reports cockpit",async()=>{const w=await build();assert.equal(w.validate({missionId:"Q6-15"}).valid,false);assert.equal(w.validate({fabricateDeploymentSuccess:true}).valid,false);assert.equal(w.validate({implementQ615OrLater:true}).valid,false);assert.equal(w.getCockpitSnapshot().missionId,"Q6-14")});
});
