import assert from "node:assert/strict";
import path from "node:path";
import { beforeEach, describe, test } from "node:test";
import { runBootstrap } from "../../bootstrap/engine.js";
import { FEW_INTEGRATION_TARGETS, buildFrontendWorkerConfiguration, createFrontendWorker, resetFrontendWorkerForTesting } from "../../frontend-worker/index.js";
const root = path.resolve(import.meta.dirname, "..", "..", "..", "..");
const input = { requirementsReportId: "rqw-req-saas-01", architectureReportId: "arw-arch-saas-01", platformId: "epfc-plt-saas-01", platformName: "EmpireAI SaaS Platform", businessId: "epfc-biz-saas-01", factoryMissionId: "epfc-msn-saas-01", businessObjective: "Coordinate enterprise lifecycle.", validated: true };
const requirementsWorker = { getRequirementsReports: () => [{ requirementsId: input.requirementsReportId, platformId: input.platformId, platformName: input.platformName, businessId: input.businessId, factoryMissionId: input.factoryMissionId, businessObjective: input.businessObjective }], getLatestRequirementsReportId: () => input.requirementsReportId };
const architectureWorker = { getArchitectureReports: () => [{ architectureId: input.architectureReportId, platformId: input.platformId, platformName: input.platformName, businessId: input.businessId, factoryMissionId: input.factoryMissionId, businessObjective: input.businessObjective, requirementsReportId: input.requirementsReportId, moduleArchitecture: [{ moduleId: "arw-mod-1", name: "Core", responsibility: "Core" }], apiArchitecture: [{ apiId: "arw-api-1", name: "Platform API", protocol: "REST", endpoints: ["/v1/platform"], direction: "external" }] }], getLatestArchitectureReportId: () => input.architectureReportId };
async function build() { const bootstrap = await runBootstrap({ repositoryRoot: root, skipHeavyScans: true }); const engine = createFrontendWorker(bootstrap, { dependencies: { requirementsWorker, architectureWorker } }); await engine.initialize(); engine.connect(); return engine; }
describe("Q6-04 Frontend Worker", () => {
  beforeEach(resetFrontendWorkerForTesting);
  test("1 locks mandatory boundaries", () => { const c = buildFrontendWorkerConfiguration(root, { neverDeployApplications: false as never, neverDesignDatabases: false as never }); assert.equal(c.neverDeployApplications, true); assert.equal(c.neverDesignDatabases, true); });
  test("2 initializes with integrations", async () => { const s = (await build()).getState(); assert.equal(s.missionId, "Q6-04"); assert.equal(s.engineVersion, "PILLOW-FEW-001"); for (const t of FEW_INTEGRATION_TARGETS) assert.ok(s.configuration.integrationTargets.includes(t)); assert.ok(s.configuration.integrationTargets.includes("architecture_worker")); });
  test("3 receives requirements", async () => { const r = (await build()).receiveApprovedRequirementsReports(input); assert.ok(r.latestFrontendBuildReport!.buildId.startsWith("few-bld-")); assert.equal(r.latestFrontendBuildReport!.requirementsReportId, input.requirementsReportId); });
  test("4 receives architecture", async () => { const e = await build(); e.receiveApprovedRequirementsReports(input); const r = e.receiveApprovedArchitectureReports(input); assert.equal(r.latestFrontendBuildReport!.architectureReportId, "arw-arch-saas-01"); });
  test("5 builds layouts dashboards", async () => { const e = await build(); e.receiveApprovedRequirementsReports(input); e.receiveApprovedArchitectureReports(input); assert.ok(e.buildApplicationLayouts(input).latestFrontendBuildReport!.layouts.length); assert.ok(e.buildDashboards(input).latestFrontendBuildReport!.dashboardsCreated[0]!.id.startsWith("few-dash-")); });
  test("6 builds pages forms", async () => { const e = await build(); e.receiveApprovedRequirementsReports(input); e.receiveApprovedArchitectureReports(input); assert.ok(e.buildPages(input).latestFrontendBuildReport!.pagesCreated.length); assert.ok(e.buildFormsAndInputValidation(input).latestFrontendBuildReport!.formsCreated[0]!.id.startsWith("few-form-")); });
  test("7 builds workflows integrations accessibility", async () => { const e = await build(); e.receiveApprovedRequirementsReports(input); e.receiveApprovedArchitectureReports(input); e.buildUserWorkflows(input); e.integrateApprovedApis(input); const r = e.supportResponsiveAndAccessibleUi(input).latestFrontendBuildReport!; assert.ok(r.workflowScreens.length && r.apiIntegrations.length); assert.equal(r.accessibilityStatus, "wcag_aa_pass"); });
  test("8 produces complete report", async () => { const r = (await build()).produceFrontendBuildReport(input).latestFrontendBuildReport!; assert.ok(r.layouts.length && r.dashboardsCreated.length && r.pagesCreated.length && r.formsCreated.length && r.workflowScreens.length && r.apiIntegrations.length); assert.equal(r.buildStatus, "complete"); assert.equal(r.selfReviewPassed, true); });
  test("9 rejects forbidden boundaries", async () => { const e = await build(); for (const forbidden of [{ implementBackendBusinessLogic: true }, { designDatabases: true }, { deployApplications: true }, { overridePillow: true }, { overrideGrandKing: true }, { implementQ605OrLater: true }]) assert.equal(e.produceFrontendBuildReport({ ...input, ...forbidden }).validation.decision, "fail"); });
  test("10 lists submits cockpit audit", async () => { const submitted: string[] = []; const bootstrap = await runBootstrap({ repositoryRoot: root, skipHeavyScans: true }); const e = createFrontendWorker(bootstrap, { dependencies: { requirementsWorker, architectureWorker, executiveReportingRuntime: { submitWorkerReport: (x) => { submitted.push(String(x.missionId)); return { records: [{ reportId: "ert-few-01" }] }; } } } }); await e.initialize(); e.connect(); const p = e.produceFrontendBuildReport(input); const s = e.submitReport({ buildId: p.latestFrontendBuildReport!.buildId, validated: true }); assert.deepEqual(submitted, ["Q6-04"]); assert.equal(s.latestFrontendBuildReport!.executiveReportId, "ert-few-01"); assert.ok(e.list().frontendBuildReports.length && e.getAuditTrail().length); assert.equal(e.getCockpitSnapshot().missionId, "Q6-04"); });
});
