import assert from "node:assert/strict"; import path from "node:path"; import { describe,test } from "node:test"; import { runBootstrap } from "../../bootstrap/engine.js"; import { buildNotificationWorkerConfiguration,createNotificationWorker,InMemoryNotificationTransport,NTW_INTEGRATION_TARGETS } from "../../notification-worker/index.js";
const ROOT=path.resolve(import.meta.dirname,"..","..","..",".."); async function build(){const worker=createNotificationWorker(await runBootstrap({repositoryRoot:ROOT,skipHeavyScans:true}));await worker.initialize();return worker} async function delivered(channel:"email"|"sms"|"telegram"|"whatsapp"){const worker=await build(),provider=worker.registerProvider({name:channel,channel,validated:true}),transport=new InMemoryNotificationTransport().set(provider.providerId,{success:true});worker.setTransport(transport);const message=worker.enqueueNotification({channel,to:`${channel}@example.test`,body:"Hello",providerId:provider.providerId});await worker.processQueue();return {worker,message}}
describe("Q6-12 Notification Worker",()=>{
test("1 boundary locks force true",()=>{const c=buildNotificationWorkerConfiguration(ROOT,{neverFabricateDeliveryResults:false as never,neverImplementQ613OrLater:false as never});assert.equal(c.neverFabricateDeliveryResults,true);assert.equal(c.neverImplementQ613OrLater,true)});
test("2 initializes doctrine and targets",async()=>{const w=await build();assert.equal(w.getState().missionId,"Q6-12");assert.ok(NTW_INTEGRATION_TARGETS.includes("workflow_builder_worker"));assert.ok(NTW_INTEGRATION_TARGETS.includes("api_integration_worker"))});
test("3 receives requirements and architecture",async()=>{const w=await build();assert.match(w.receiveApprovedRequirementsReports().buildId,/^ntw-bld-/);assert.match(w.receiveApprovedArchitectureReports().buildId,/^ntw-bld-/)});
test("4 sends email only through transport success",async()=>{const {worker,message}=await delivered("email");assert.equal(worker.getMessages().find(x=>x.messageId===message.messageId)?.status,"sent")});
test("5 sends SMS only through transport success",async()=>{const {worker,message}=await delivered("sms");assert.equal(worker.getMessages().find(x=>x.messageId===message.messageId)?.status,"sent")});
test("6 sends Telegram only through transport success",async()=>{const {worker,message}=await delivered("telegram");assert.equal(worker.getMessages().find(x=>x.messageId===message.messageId)?.status,"sent")});
test("7 sends WhatsApp only through transport success",async()=>{const {worker,message}=await delivered("whatsapp");assert.equal(worker.getMessages().find(x=>x.messageId===message.messageId)?.status,"sent")});
test("8 renders template substitutions",async()=>{const w=await build(),t=w.createTemplate({name:"welcome",channel:"push",subject:"Hi {{name}}",body:"Welcome {{name}}"}),r=w.renderTemplate({templateId:t.templateId,variables:{name:"Ada"}});assert.equal(r.subject,"Hi Ada");assert.equal(r.body,"Welcome Ada")});
test("9 retries transport failure then success",async()=>{const w=await build(),p=w.registerProvider({name:"mail",channel:"email"});w.configureRetry({maxRetries:1,backoffMs:0});w.setTransport(new InMemoryNotificationTransport().set(p.providerId,[{success:false},{success:true}]));const m=w.enqueueNotification({channel:"email",to:"a@example.test",body:"retry",providerId:p.providerId});await w.processQueue();assert.equal(w.getMessages().find(x=>x.messageId===m.messageId)?.status,"sent");assert.ok(w.getDeliveryRecords().some(x=>x.status==="retrying"))});
test("10 records delivery statuses",async()=>{const {worker}=await delivered("email");const statuses=worker.getDeliveryRecords().map(x=>x.status);assert.ok(statuses.includes("sending"));assert.ok(statuses.includes("sent"))});
test("11 produces safe complete report",async()=>{const w=await build(),p=w.registerProvider({name:"mail",channel:"email"});w.storeProviderCredentials({providerId:p.providerId,secret:"super-secret"});const report=w.produceNotificationBuildReport();assert.equal(report.buildStatus,"complete");assert.equal(report.metadataVersion,"NTW-001-v1");assert.equal(JSON.stringify(report).includes("super-secret"),false)});
test("12 rejects forbidden Q6-13 inputs and reports cockpit",async()=>{const w=await build();assert.equal(w.validate({missionId:"Q6-13"}).valid,false);assert.equal(w.validate({fabricateDeliveryResults:true}).valid,false);assert.equal(w.validate({implementQ613OrLater:true}).valid,false);assert.equal(w.getCockpitSnapshot().missionId,"Q6-12")});
});
