import assert from "node:assert/strict"; import path from "node:path"; import { describe,test } from "node:test"; import { runBootstrap } from "../../bootstrap/engine.js"; import { buildTestingWorkerConfiguration,createTestingWorker,TSW_INTEGRATION_TARGETS } from "../../testing-worker/index.js";
const ROOT=path.resolve(import.meta.dirname,"..","..","..","..");async function build(){const worker=createTestingWorker(await runBootstrap({repositoryRoot:ROOT,skipHeavyScans:true}));await worker.initialize();return worker}async function executed(type:"unit"|"integration"|"end_to_end"|"acceptance"){const w=await build(),[c]=w.generateTests({testType:type,domain:"platform"});w.configureCaseOutcome({caseId:c.caseId,outcome:"passed"});const run=await w.executeSuite({suiteId:c.suiteId});return {w,c,run}}
describe("Q6-13 Testing Worker",()=>{
test("1 boundary locks force true",()=>{const c=buildTestingWorkerConfiguration(ROOT,{neverFabricateSuccessfulTests:false as never,neverImplementQ614OrLater:false as never});assert.equal(c.neverFabricateSuccessfulTests,true);assert.equal(c.neverImplementQ614OrLater,true)});
test("2 initializes doctrine and targets",async()=>{const w=await build();assert.equal(w.getState().missionId,"Q6-13");assert.ok(TSW_INTEGRATION_TARGETS.includes("notification_worker"))});
test("3 receives requirements and architecture",async()=>{const w=await build();assert.match(w.receiveApprovedRequirementsReports().buildId,/^tsw-bld-/);assert.match(w.receiveApprovedArchitectureReports().buildId,/^tsw-bld-/)});
test("4 generates and executes unit tests without fabricated success",async()=>{const w=await build(),[unknown]=w.generateTests({testType:"unit"}),unknownRun=await w.executeSuite({suiteId:unknown.suiteId});assert.equal(unknownRun.results[0].status,"failed");const [testCase]=w.generateTests({testType:"unit"});w.configureCaseOutcome({caseId:testCase.caseId,outcome:"passed"});assert.equal((await w.executeSuite({suiteId:testCase.suiteId})).results.at(-1)?.status,"passed")});
test("5 executes integration tests",async()=>{const {run}=await executed("integration");assert.equal(run.results[0].status,"passed")});
test("6 executes end-to-end tests",async()=>{const {run}=await executed("end_to_end");assert.equal(run.results[0].status,"passed")});
test("7 executes acceptance tests",async()=>{const {run}=await executed("acceptance");assert.equal(run.results[0].status,"passed")});
test("8 reports explicit coverage only",async()=>{const {w,c,run}=await executed("unit");w.configureCaseOutcome({caseId:c.caseId,outcome:"passed",coverageDelta:{lines:3,branches:2,functions:1,statements:4}});const covered=await w.executeSuite({suiteId:c.suiteId});assert.deepEqual(w.getCoverage({runId:covered.runId}),{runId:covered.runId,lines:3,branches:2,functions:1,statements:4});assert.notEqual(w.getCoverage({runId:run.runId}).lines,100)});
test("9 detects regression after baseline pass",async()=>{const {w,c,run}=await executed("unit");w.setBaselineRun({runId:run.runId});w.configureCaseOutcome({caseId:c.caseId,outcome:"failed",evidence:"assertion failed"});const changed=await w.executeSuite({suiteId:c.suiteId});assert.equal(w.detectRegressions({runId:changed.runId}).length,1)});
test("10 records evidence and recommendations",async()=>{const w=await build(),failure=w.recordFailureEvidence({caseId:"tsw-case-x",runId:"tsw-run-x",message:"assertion failed",evidence:"stack"});const recommendations=w.recommendRemediation({runId:failure.runId});assert.equal(recommendations.length,1);assert.match(recommendations[0].recommendation,/assertion failed/)});
test("11 produces complete testing report",async()=>{const {w}=await executed("unit");const report=w.produceTestingBuildReport();assert.equal(report.buildStatus,"complete");assert.equal(report.metadataVersion,"TSW-001-v1");assert.equal(report.neverFabricateSuccessfulTests,true)});
test("12 rejects forbidden inputs and reports cockpit",async()=>{const w=await build();assert.equal(w.validate({missionId:"Q6-14"}).valid,false);assert.equal(w.validate({fabricateSuccessfulTests:true}).valid,false);assert.equal(w.validate({implementQ614OrLater:true}).valid,false);assert.equal(w.getCockpitSnapshot().missionId,"Q6-13")});
});
