import assert from "node:assert/strict"; import path from "node:path"; import { beforeEach,describe,test } from "node:test"; import { runBootstrap } from "../../bootstrap/engine.js"; import { buildWorkflowBuilderWorkerConfiguration,createWorkflowBuilderWorker,InMemoryStepHandler,WBW_INTEGRATION_TARGETS } from "../../workflow-builder-worker/index.js";
const ROOT=path.resolve(import.meta.dirname,"..","..","..",".."); async function build(){const w=createWorkflowBuilderWorker(await runBootstrap({repositoryRoot:ROOT,skipHeavyScans:true}));await w.initialize();return w} async function basic(w:Awaited<ReturnType<typeof build>>,name="workflow"){const x=w.createWorkflow({name});w.addStep({workflowId:x.workflowId,step:{stepId:"start",type:"task",name:"start",nextStepIds:["end"]}});w.addStep({workflowId:x.workflowId,step:{stepId:"end",type:"end",name:"end"}});w.setEntryStep({workflowId:x.workflowId,entryStepId:"start"});w.validateWorkflow({workflowId:x.workflowId});w.publishWorkflow({workflowId:x.workflowId});return x}
describe("Q6-11 Workflow Builder Worker",()=>{beforeEach(()=>{});
test("1 boundary locks force true",()=>{const c=buildWorkflowBuilderWorkerConfiguration(ROOT,{neverFabricateSuccessfulWorkflowExecution:false as never,neverImplementQ612OrLater:false as never});assert.equal(c.neverFabricateSuccessfulWorkflowExecution,true);assert.equal(c.neverImplementQ612OrLater,true)});
test("2 initializes doctrine and targets",async()=>{const w=await build();assert.equal(w.getState().missionId,"Q6-11");assert.ok(WBW_INTEGRATION_TARGETS.includes("api_integration_worker"))});
test("3 receives requirements and architecture",async()=>{const w=await build();assert.match(w.receiveApprovedRequirementsReports().buildId,/^wbw-bld-/);assert.match(w.receiveApprovedArchitectureReports().buildId,/^wbw-bld-/)});
test("4 creates validated ready sequential workflow",async()=>{const w=await build(),x=await basic(w);assert.equal(w.getWorkflows().find(a=>a.workflowId===x.workflowId)?.status,"ready")});
test("5 conditionally branches from context",async()=>{const w=await build(),x=w.createWorkflow({name:"branch"});for(const s of [{stepId:"d",type:"decision",name:"d"},{stepId:"yes",type:"end",name:"yes"},{stepId:"no",type:"end",name:"no"}] as const)w.addStep({workflowId:x.workflowId,step:s});w.addDecisionNode({workflowId:x.workflowId,decision:{decisionId:"wbw-step-d",stepId:"d",expression:"go",trueNextStepId:"yes",falseNextStepId:"no"}});w.setEntryStep({workflowId:x.workflowId,entryStepId:"d"});w.validateWorkflow({workflowId:x.workflowId});w.publishWorkflow({workflowId:x.workflowId});const r=w.startWorkflowRun({workflowId:x.workflowId,context:{go:true}});await w.executeRun({runId:r.runId});assert.ok(w.getStepRecords(r.runId).some(a=>a.outcome&&JSON.stringify(a.outcome).includes("yes")))});
test("6 executes parallel fork join",async()=>{const w=await build(),x=w.createWorkflow({name:"parallel"});for(const s of [{stepId:"f",type:"parallel_fork",name:"f",nextStepIds:["a","b"]},{stepId:"a",type:"task",name:"a",nextStepIds:["j"],parallelGroup:"g"},{stepId:"b",type:"task",name:"b",nextStepIds:["j"],parallelGroup:"g"},{stepId:"j",type:"parallel_join",name:"j",nextStepIds:["e"]},{stepId:"e",type:"end",name:"e"}] as any[])w.addStep({workflowId:x.workflowId,step:s});w.setEntryStep({workflowId:x.workflowId,entryStepId:"f"});w.validateWorkflow({workflowId:x.workflowId});w.publishWorkflow({workflowId:x.workflowId});w.setStepHandler(new InMemoryStepHandler().set("a",{success:true}).set("b",{success:true}));const r=w.startWorkflowRun({workflowId:x.workflowId});assert.equal((await w.executeRun({runId:r.runId})).status,"completed")});
test("7 retries explicit handler failure",async()=>{const w=await build(),x=await basic(w);w.addRetryPolicy({workflowId:x.workflowId,policy:{policyId:"r",maxRetries:1,backoffMs:0}});w.getWorkflows()[0]!.steps[0]!.retryPolicyId="r";w.setStepHandler(new InMemoryStepHandler().set("start",[{success:false},{success:true}]));const r=w.startWorkflowRun({workflowId:x.workflowId});await w.executeRun({runId:r.runId});assert.equal(w.getStepRecords(r.runId).filter(a=>a.stepId==="start").length,2)});
test("8 approval pauses then requires approval",async()=>{const w=await build(),x=w.createWorkflow({name:"approval"});for(const s of [{stepId:"a",type:"approval",name:"a",nextStepIds:["e"],approvalGateId:"g"},{stepId:"e",type:"end",name:"e"}] as any[])w.addStep({workflowId:x.workflowId,step:s});w.addApprovalGate({workflowId:x.workflowId,gate:{gateId:"g",stepId:"a",requiredApproverRole:"Pillow",status:"pending"}});w.setEntryStep({workflowId:x.workflowId,entryStepId:"a"});w.validateWorkflow({workflowId:x.workflowId});w.publishWorkflow({workflowId:x.workflowId});const r=w.startWorkflowRun({workflowId:x.workflowId});assert.equal((await w.executeRun({runId:r.runId})).status,"paused");w.approveGate({runId:r.runId,gateId:"g",decision:"approved"});assert.equal((await w.executeRun({runId:r.runId})).status,"completed")});
test("9 follows recovery after retries",async()=>{const w=await build(),x=await basic(w);w.addStep({workflowId:x.workflowId,step:{stepId:"recover",type:"task",name:"recover",nextStepIds:["end"]}});w.addRetryPolicy({workflowId:x.workflowId,policy:{policyId:"r",maxRetries:0,backoffMs:0}});w.addFailureRecoveryPath({workflowId:x.workflowId,path:{pathId:"p",fromStepId:"start",toStepId:"recover",strategy:"compensate"}});const s=w.getWorkflows()[0]!.steps[0]!;s.retryPolicyId="r";s.recoveryPathId="p";w.setStepHandler(new InMemoryStepHandler().set("start",{success:false}).set("recover",{success:true}));const r=w.startWorkflowRun({workflowId:x.workflowId});assert.equal((await w.executeRun({runId:r.runId})).status,"completed")});
test("10 succeeds only configured handlers",async()=>{const w=await build(),x=await basic(w);w.setStepHandler(new InMemoryStepHandler().set("start",{success:true}));const r=w.startWorkflowRun({workflowId:x.workflowId});assert.equal((await w.executeRun({runId:r.runId})).status,"completed")});
test("11 produces complete build report",async()=>{const w=await build(),x=await basic(w);const r=w.produceWorkflowBuildReport({workflowId:x.workflowId});assert.equal(r.buildStatus,"complete");assert.equal(r.metadataVersion,"WBW-001-v1");assert.equal(r.neverReplaceApprovalGovernance,true)});
test("12 rejects Q6-12 and fabricated execution",async()=>{const w=await build();assert.equal(w.validate({missionId:"Q6-12"}).valid,false);assert.equal(w.validate({fabricateWorkflowExecution:true}).valid,false);assert.equal(w.validate({implementQ612OrLater:true}).valid,false);assert.equal(w.getCockpitSnapshot().missionId,"Q6-11")});
});
