import type { CurrentArchitectureRecord } from "./types.js";

/** Current V1 production architecture — single instance (P5-05). */
export const CURRENT_ARCHITECTURE_REGISTRY: CurrentArchitectureRecord[] = [
  {
    id: "CA-BRAIN",
    domain: "brain",
    name: "Brain API (Railway)",
    topology: "Single Fastify process · earlyListen · critical routes at boot",
    limitation: "Single instance · no horizontal scaling · 200+ tool boot",
    owner: "Brain · ADR-CON-003",
  },
  {
    id: "CA-PILLOW",
    domain: "pillow",
    name: "Pillow COI",
    topology: "In-process singleton · lazy boot in production",
    limitation: "Sequential startPillow() ~130s · single writer",
    owner: "Pillow · PILLOW-001",
  },
  {
    id: "CA-COCKPIT",
    domain: "cockpit",
    name: "Executive Cockpit (Vercel)",
    topology: "empireai-web BFF → Railway Brain",
    limitation: "Single Brain endpoint · no load balancer",
    owner: "Cockpit · P2",
  },
  {
    id: "CA-DB",
    domain: "database",
    name: "SQLite (sql.js WASM)",
    topology: "Single file · Railway volume /data/",
    limitation: "Single-writer · no replication · sync cold load",
    owner: "Brain Database · BR-BN-001",
  },
  {
    id: "CA-REDIS",
    domain: "redis",
    name: "Upstash Redis",
    topology: "Single Redis instance · optional degraded mode",
    limitation: "Not cluster · auth/queue depend on availability",
    owner: "Infrastructure · ADR-CON-005",
  },
  {
    id: "CA-QUEUES",
    domain: "queues",
    name: "BullMQ Task Queue",
    topology: "empireai-brain-tasks · Redis-backed or DegradedTaskQueue",
    limitation: "No-op without Redis · single queue",
    owner: "Brain · task-queue.ts",
  },
  {
    id: "CA-WORKERS",
    domain: "workers",
    name: "BullMQ Workers",
    topology: "Separate worker.ts process · not in API boot",
    limitation: "Manual worker deployment · single worker instance",
    owner: "Brain Runtime · worker.ts",
  },
  {
    id: "CA-SESSIONS",
    domain: "sessions",
    name: "Session Storage",
    topology: "Redis auth · in-memory Pillow chat · localStorage browser",
    limitation: "Pillow chat ephemeral · in-memory auth fallback",
    owner: "Sessions · P5-03",
  },
  {
    id: "CA-STORAGE",
    domain: "storage",
    name: "SQLite Volume + Artifacts",
    topology: "Railway persistent volume · local artifact files",
    limitation: "No object storage · single volume",
    owner: "Infrastructure",
  },
  {
    id: "CA-HOST",
    domain: "production_infrastructure",
    name: "V1 Split Stack",
    topology: "Vercel + Railway + Upstash",
    limitation: "Single-region · no HA · no disaster recovery automation",
    owner: "Infrastructure · ADR-CON-005",
  },
  {
    id: "CA-AI",
    domain: "ai_providers",
    name: "LLM Provider Abstraction",
    topology: "LLMRouter · OpenAI primary",
    limitation: "Single provider path · no provider failover cluster",
    owner: "Brain LLM",
  },
  {
    id: "CA-COMMERCE",
    domain: "commerce",
    name: "Commerce Integration",
    topology: "Sandbox default · credential vault",
    limitation: "Single marketplace path until credentials configured",
    owner: "Commerce · PILLOW-CI-001",
  },
];
